### ISSUE TITLE
Custom Caption Not Following Image Positioning

### ISSUE THREAD

**Issue by gentlegianted** [elementor/elementor#10003]
https://share.getcloudapp.com/6quLQ4yk

**Comment by cirkut** [comment]
Although it would make sense that the caption follows the alignment of the image overall by default, there **_is_** the alignment options for the caption under the style tab of the Image widget, which controls this in the manner you're requesting. This technically provides greater overall customization by allowing users to adjust the caption alignment differently from the image alignment overall.

<img width="298" alt="Screenshot 2019-12-27 23 40 00" src="https://user-images.githubusercontent.com/3690775/71538970-794d3d80-2902-11ea-8640-b9c6bc5d0cd9.png">

**Comment by cirkut** [comment]
I looked into the root of this more, and it appears that the reason this doesn't follow by default is that Hello Elementor's styling center caption text by default. 

I've created a pull request to remove the center text caption from the Hello Elementor `theme.css` stylesheet, which then will fallback to the Image Widget's overall alignment instead of being forced to set a caption alignment in the Style tab.

**Comment by lior-sh** [comment]
Hi @gentlegianted,

You can change the Custom Caption position by the Style tab.
Edit Image > Style > Caption > Alignment.
Thanks.

**Comment by cirkut** [comment]
@lior-sh I do want to bring up that this specific example is not solved by that method. Using that alignment manually works, but the expected alignment of the caption should be (and is from Elementor's perspective) in line with what the image is aligned to (if the image is right aligned, the caption is right aligned by default).

The issue is that the caption is set in Hello Elementor to be centered, and is more specific than the default caption alignment set by Elementor unless specifically choosing caption alignment.

I would suggest you review my pull request to see if this is something that can be implemented to help solve this issue.
