### ISSUE TITLE
Troublesome handling sections in havigator, bugs?

### ISSUE THREAD

**Issue by tamelander** [elementor/elementor#10178]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

Hi,
How is the Navigator supposed to work? I am struggling with it.
1. When I select a page section with Edit section, isn't that section supposed to be highlighted in the Navigator? When I enter Edit section more than one section in the Navigator has got a blue mark.
2. When I try to draw a section and place it a the bottom of the page it usually ends up somewhere in the middle and never at the bottom.
3. Some means of identifying the section in the navigator would be great. Like having an Elementor settings to show/hide the section's unique ID (that I suppose must exist) in the Edit Section sidebar and showing the same IDs in the Navigators accordion sections.  Like it is now (since the blue mark does not mark the section being edited, perhaps a bug) I can identify the Navigator sections only by toggling their visibility – and that only works if I have that section in the browser viewport.

**Comment by DorShahar** [comment]
Hi
Sorry for the late response.
You can see a full explanation about the Navigator in our help-center [here](https://elementor.com/help/navigator/).
In general - GitHub is not for support: it uses for bug reports and feature requests. 

If there is an optional bug - we will need the System info in order to investigate and reproduce the bug. 

You are welcome to ask questions in one of Elementor's Facebook communities. 

Thanks.
