### ISSUE TITLE
Conflict with Shortcodes Ultimate plugin

### ISSUE THREAD

**Issue by iameviliam** [elementor/elementor#1033]
I disabled everything, I'm using Generatepress

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.32
	PHP Version: 5.5.38
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.7
	Site URL: http://www.sublimemilbus.com
	Home URL: http://www.sublimemilbus.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 64MB
	Permalink Structure: /%postname%/
	Language: it-IT
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 1.3.41
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

== Active Plugins ==
	Elementor
		Name: Elementor
		Version: 1.0.4
		Author: Elementor.com

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Name: ManageWP - Worker Loader
		Version: 
		Author: ManageWP

**Comment by Himaghiri** [comment]
Hi uninstall elementor and re-install it. Guess this should solve your problem.

**Comment by peepshow** [comment]
I'm also having an issues with the loading of the editor.
It gets stuck on the grey screen with the E loading icon.

The console error states:
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

I've also just updated as well as upgrading to Pro. I tried deleting and reinstalling Elementor but it's still stuck on this 500 error.

Thanks

**Comment by iameviliam** [comment]
Still here, upgraded to pro and I get the same problem as peepshow, Elementor is stuck to the loading page. I also increased my memory to 512mb.

**Comment by agusmu** [comment]
@peepshow @iameviliam is it possible to upload screenshot of your console errors here? interesting to see what resource that makes 500 internal server error.

**Comment by iameviliam** [comment]
@agusmu I don't get a 500 internal server error, Elementor is just stuck to the loading page!

**Comment by agusmu** [comment]
@iameviliam Elementor is stuck to the loading page, means something is not right. and it can be identified from browser console error. 

500 internal server error is on browser console error, not a full page with 500 internal server error.

**Comment by iamntz** [comment]
Guys, I think it would be more useful to do one of the following:

1. enable `WP_DEBUG` in `wp-config.php` and see what's the response of that 500 error page;
1. Check error logs (either in your server log file or by enabling `define( 'WP_DEBUG_LOG', true );` in wp-config).

Because "I got 500 error" doesn't help too much. But "I got this _specific_ error" does. ;)

**Comment by iameviliam** [comment]
@iamntz I enabled the debug but I don't get any errors in the log file.

**Comment by kadoogan55** [comment]
Could try installing on a different hosting service to see if that is the issue. Try the free x10hosting.com. I had a pal do that for an issue he was having with another builder and it wound up helping him a lot. X10 is free, fast to sign up for, and has quick Wordpress installation. When you are done testing you can delete the site. Or just forget about it and it will get deleted automatically as they have a check in policy. Migrate your existing site over with WP All In One Migration or your own fave method. See how it goes. Not everyone's cup of tea but an option regardless. And no, I am not an advocate for x10 hosting. :)

**Comment by kadoogan55** [comment]
Also try switching themes first maybe. I updated using a different theme and Elementor seems to run fine on it.

**Comment by iamntz** [comment]
@iameviliam: check your server config then to enforce errors. It's impossible to have error 500 without nothing in logs :)

**Comment by SniffleValve** [comment]
I am successfully running the latest version of Elementor and GeneratePress on a number of sites, so it appears that there may be an issue with your server config and/or plugins.

As many have mentioned, there should be something in the logs with a 500 error.

Additionally, your memory allocation is on the low side, so I would also up that as outlined below (one way to do it):

- Edit your wp-config.php file.

- Add this to the very bottom, right before the line that says, “Happy Blogging”:

define('WP_MEMORY_LIMIT', '256M');

Cheers!
Lyle

**Comment by peepshow** [comment]
Sorry about the slow reply. I have been offline for a couple of days.

I have been through the error logs and found the issue seems to caused by an error or conflict with **Shortcodes Ultimate**. Disabling the plugin has allowed Elementor to work again, and for now I'm not using Shortcodes Ultimate.

`PHP Fatal error:  Call to undefined function is_plugin_active() in */wp-content/plugins/shortcodes-ultimate/inc/core/tools.php on line 252`

**Comment by ryanlabelle** [comment]
Thanks for sharing your info guys. I'm experiencing a similar issue as https://github.com/pojome/elementor/issues/864

The Shortcode button is non-responsive. I think it should probably work anywhere that the Content Editor shows up. 

I created an issue with the team at Shortcode Ultimate, we'll see what they have to say...

https://wordpress.org/support/topic/elementor-compatibility/

ref:

`Thank you for creating an amazing plugin.

I’d love to recommend this plugin in our WordPress themes. The issue is that we use the Elementor Page Builder and I can’t get the modal window to activate when I click ‘Insert Shortcode’.

* I don’t see any errors in the JS console.
* wp-debug enabled but no error messages.
* Using Twenty Fifteen Theme
* Only active plugins are Elementor and Shortcodes Ultimate

I took a video: https://cl.ly/0c010W1M2S1K

I’ll post on the Elementor Forum as well.

Your advice is greatly appreciated. Thank you.`

**Comment by carasmo** [comment]
+1

**Comment by carasmo** [comment]
I tested Shortcake with Beaver Builder and the Add Post Element also doesn't work (doesn't launch).

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account.
