### ISSUE TITLE
Elementor and Elementor PRO seriously lacks Dynamic Display Conditions for it's widgets and sections based on any conditions (Including custom fields)

### ISSUE THREAD

**Issue by bapun26** [elementor/elementor#10353]
Being such a popular and efficient page builder of late, Elementor and it's PRO version desperately lacks dynamically displaying any widgets or sections (Including any third party widget extensions) based on any sort of conditions (Including custom fields by ACF, Pods etc. ).

Without this feature it is way behind any real world website development and design. Because in most cases, the websites need to be dynamic after all. With static display of blocks and widgets, it's absolutely lagging behind.

Page builder like Beaver Builder (https://www.wpbeaverbuilder.com/) and Brizy (https://www.brizy.io/) have this feature by default.
So, that makes Elementor a less efficient page builder in the real world scenario.

I hope, this feature request to be considered as a high priority implementation rather than going for the features that don't matter too much as far as the functional design and build is concern (Example, to celebrate it's 4 million users, Elementor announced 4 new feature request options, which are barely needed by the end-users) [** Please remember** Your end-users are not the designers who purchase or use Elementor to design client sites. Your end-users are the clients of your clients, who, from a practical point of view doesn't care for those multi-step forms or the AE after effects. Rather they need an advanced functional design for their business.]

Thanks. Hope to see this sooner rather than later.

**Comment by der-rote-hund** [comment]
While I find the wording a little strong, I tend to agree with the general notion. Just now I thought it would be very useful to have a dynamic field for the recipient email address in elementor forms, so it could be updated in a central place for all forms instead of having to go into each and every form individually. We tend to make websites with lots of different forms. I would have voted for that feature had it been eligible… ;)

**Comment by mister-Sito** [comment]
Hi everyone, my name is Carlo and I write about the Elementor plugin, as it sends too many requests. Do you have any advice to give me? https://www.mistersito.com/

**Comment by samheavyside** [comment]
Hi all, 

Totally agree with you. I think it should definitely be added as a core feature of Elementor PRO (since dynamic content is a PRO feature). 

But, I'm not holding my breath... progress can be slow on features like this. 

Until it is included however, this plugin does what you are talking about. 
[https://wordpress.org/plugins/dynamicconditions/](https://wordpress.org/plugins/dynamicconditions/)

Cheers.

**Comment by BEKWL** [comment]
I would like to see the possibilty to implement multi step forms with dynamic content and conditional logic. I wonder why this is not available in the Pro version I recently bought. I don't want to buy other plug ins like Piotnet (https://pafe.piotnet.com/) and Dynamic Content for Elementor (https://www.dynamic.ooo/). Please fix this Elementor.

**Comment by nfspck** [comment]
I'm a recent (as of March 2020) convert from Beaver Builder and I love Elementor but there are two features that I really miss and this is one of them. In BB you can write IF and IF ELSE statements using their shortcode 'language', which you can read about [HERE](https://kb.wpbeaverbuilder.com/article/581-test-for-values-in-shortcodes-for-advanced-custom-fields), which gave me a tonne of flexibility in custom post type templates and in the custom post loops it selfs. I can test for fields and perform an appropriate action. They have had this feature for some time. If Elementor can include this it would be a game-changer because right now I have to choose which page builder to use based on the requirements.

**Comment by Aviad-Herman** [comment]
Hi, I'm merging this discussion with: #4246

**Comment by nicholaszein** [comment]
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
