### ISSUE TITLE
Elementor Pro: Custom fonts file URLS are static and are not changed when using URL-Replacer

### ISSUE THREAD

**Issue by maitNoserYoung** [elementor/elementor#10382]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.
## Description
When creating a custom font, Elementor Pro links the fonts with a static url. When changing URL it is not affected by Elementors own URL-Replacer, that for with every domain change, the links break. The only way to fix this as the moment, is to delete each font-file link and readd them, after the new URL has been defined

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by DorShahar** [comment]
Hey all,

This issue has been resolved in Elementor v3.2.0

Feel free to update!

**Comment by Alexandero89** [comment]
Seems to be back.
Using elementor 3.19.4 and Elementor Pro 3.19.3. 

Just changed the url and everything gets the new url but the fonts. they seem to be hardcoded somewhere to the old url.

**Comment by Alexandero89** [comment]
Ahh, found why.

Go into Elementor Custom Fonts -> Click on your Custom Font -> click on "Edit" on the row of each uploaded weight and style of your custom font. There you will see that elementor just saved the absolute url to the old font file (for example woff2) instead of an relative path.
So for example:
https:/olddomain.com/wp-content/my-font.woff2

Just click on the url, choose the woff2 file you need and click on save. It will then save the path with the newly url.

@DorShahar maybe make this a relative path? So set the url to "/wp-content/my-font.woff2" for example. Or get notified when wordpress and/or elementor are changing the url of the site so this value gets updated too?

**Comment by Marian-Umeleon** [comment]
Same issue. This must be a relative path imho. For ages elementor needs special care after setting up local/staging environments (importing Kit/custom fonts not loading locally).
