### ISSUE TITLE
Error Slides per view in Testimonial Carousel

### ISSUE THREAD

**Issue by MiguelFalcon** [elementor/elementor#10518]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Since the last update, the "Testimonial Carousel" Widget stopped working with the "Slides per view" option, keeping the same value set in Computer on Tablet and mobile.

**Comment by kaspergram** [comment]
I am having this issue too.

**Comment by emsi68219** [comment]
I´m having this issue two. Photo Carousel is working on phone but not on desktop. It shows only one picture, instead of sliding one photo after the other. Either with Safari, nor with Google Chrome it is working on the desktopn. I rebuild to the previous version again, and everything was working fine again. You can see the working slider on www.van-der-voorden.com

**Comment by shilo-ey** [comment]
I merged this issue with  #10508, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
