### ISSUE TITLE
The version 2.9.1 is not available.

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#10537]
It is not possible to install/download version 2.9.1. On Wordpress, in the extension details, it always says 2.8.5

**Comment by godvsgodvs** [comment]
I think you mean 2.9. It appears Elementor has finally realized that it was no where near ready to release. The blog post about it on the Elementor site has been removed with no explanation. This has turned out to be a major mess and from the beginning it appeared development was under pressure to get this out ready or not. My guess is that Marketing was feeling the heat from Divi's recent feature additions.

Of course the same thing happened with Divi 3.0 which was also a mess and caused numerous conflicts with 3rd party plugins. It took months for that to get corrected.

**Comment by shilo-ey** [comment]
A few hours after launching v2.9, we noticed that some of our Pro users reported that they can't access their Popup Builder.

In order to avoid potentially affecting more users, we decided to do the responsible thing and hold back the version to anyone who didn't update yet. 
In addition, we changed the latest version tag back in the WordPress repository to `v2.8.5`.

We resolved those issues and currently, v2.9.1 is released only to users who previously updated their Elementor to v2.9. 
You should see the version in 24-48 hours, or you can download it directly from WordPress repository: https://downloads.wordpress.org/plugin/elementor.2.9.1.zip 

Thanks
