### ISSUE TITLE
WooCommerce Archive Products 

### ISSUE THREAD

**Issue by dsgolfside** [elementor/elementor#10655]
the products no matter what i do are always 2 columns on mobile ...this creates tiny thumbnails ...i really want 1 column on mobile ...there is no option for this .....astra pro has an option to set 1 column on mobile for product archive but conflicts with your widget or block whatever the correct term is ...how can i achieve this?

**Comment by rocketeer76** [comment]
I have the same problem. Had to add some custom CSS, which is not optimal due to different viewports.

**Comment by monica123m** [comment]
I was looking for this too! Same problem! Personally, I'd like to avoid other CSS like rocketeer76 suggests, because i just added a lot of customization through it in the archive page, so if there's a fix for this would be better. I'll follow up the post.

**Comment by parfilov** [comment]
Same issue. Only with Astra. Astra's support says that it's not their problem.

**Comment by monica123m** [comment]
Seems like the only solution is using CSS. 
Elementor uses CSS grid system that eventually didin't fit well when editing the standard woocommerce product archive structure. Maybe a conflict between css sheets, i really don't know, but the problem lies in a media query.

From the official elementor FB group, the only provided solution is to add this few CSS lines to our code:

@media (max-width: 414px) {
.elementor-element.elementor-products-grid ul.products {
grid-template-columns: 1fr;
}
}

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
