### ISSUE TITLE
⛔ 🧩 Products import via CSV files

### ISSUE THREAD

**Issue by obenseven** [elementor/elementor#10704]
Hi,
There is problem between WooCommerce Product Import and Elementor.
I imported a lot of products via WooCommerce Product Import with CSV file.
But, new descriptions are not showing in frontend.
Then, I exported all products via WooCommerce Product Export and looked what is the problem.
I saw there is right descriptions that I changed.

But still not showing on frontend. It is still showing old descriptions.

There is 2 descriptions version. One of them is WordPress default editor descriptions and one of them Elementor's descriptions.

How can I import products from CSV file to Elementor's description ?

**Comment by nicholaszein** [comment]
Hello @obenseven,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party plugins.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

Regards
