### ISSUE TITLE
Border color on hover for button

### ISSUE THREAD

**Issue by qwik3r** [elementor/elementor#10782]
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

The border color on hover cannot be changed to be something different on hover when editing a button. 

## Steps to reproduce

Add a button widget, then go to style -> hover and change the border color. It will also change for the normal state, thus there is no way to change the border color on hover

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by lior-sh** [comment]
Hi @qwik3r 

Thanks for reporting,
We cannot reproduce your issue as described.
 
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.

This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

Thanks.

**Comment by etasia79** [comment]
@lior-sh  I've got the exact same problem : why did you close this issue ?

The manipulation is very simple : 
1. you create a button
2. you set a border color
3. you try to set another border color on the HOVER section : the modification applies to both states (normal and hover).

So you CANNOT set a different border color for normal and hover states.

**Comment by pixelloop** [comment]
I can confirm this is still a missing feature or bug in Elementor.

I'd love it if Elementor could fix the basics instead of spending time on fancy stuff. 

I have to CSS this to set the button border color to change on hover state.

**Comment by nadworks** [comment]
Yes, this is still a missing feature. Puzzled that this is not possible. 
So straight forward: B**order colour change needs to be included in the hover state settings.**

**Comment by Heavy-meta** [comment]
This is actually not a bug or missing feature. The feature is already there and works fine, no extra CSS is needed. What makes it confusing is the fact that you can change in border color on hover in two places. These settings have always been like this at least, since Elementor Version 3.4.6 and Elementor Pro Version 3.4.1. Please see the screenshot below.
![image](https://user-images.githubusercontent.com/57484529/152954617-b57fa53d-157f-43b6-9d92-01e0faa684e4.png)

**Comment by webster-mcwebby** [comment]
Actually, this isn't true for me. I was already changing the color in the right place. The problem for me (and maybe I should have already known this?) is that when you hover, the "normal" state isn't replaced, it's just covered. So when I was trying to have the hover color be semi-transparent blue while the normal state was a fully opaque outline of white, the white outline was still showing under the semi-transparent blue. So that is a missing feature IMO. I am sure there is a solution via CSS to just hide the "normal" state of the button. I guess that is what I'll do :)

> This is actually not a bug or missing feature. The feature is already there and works fine, no extra CSS is needed. What makes it confusing is the fact that you can change in border color on hover in two places. These settings have always been like this at least, since Elementor Version 3.4.6 and Elementor Pro Version 3.4.1.
> Please see the screenshot below.

**Comment by tableconnect** [comment]
> This is actually not a bug or missing feature. The feature is already there and works fine, no extra CSS is needed. What makes it confusing is the fact that you can change in border color on hover in two places. These settings have always been like this at least, since Elementor Version 3.4.6 and Elementor Pro Version 3.4.1.
> 
> Please see the screenshot below.

thanks, this was exactly my problem. (confusing UI by Elementor in this case)
