### ISSUE TITLE
⛔ 🧩 double scroll bar appeared and the footer disappeared - elementor, phlox, wordpress

### ISSUE THREAD

**Issue by eminakben** [elementor/elementor#10836]
Hello,

I made a website using elementor on Phlox theme, here is the link https://entfairs.com
however after several weeks, the footer suddenly disappeared and for no reason a second vertical scrollbar appeared. while the footer is missing in all pages, the scroll bar issue is only in the other pages not in the main page. I'm no coder or webmaster or anything. So I have no idea what's going on.

I had the elementor footer override the theme footer. I try to turn off the elementor footer and turn on the theme footer but that is missing too. No footer shows up.

The footer template is still there in the templates section in worpress dashboard. The name of the footer template is "footerent" if it will help you search it in the codes of the page.

I'Ll really appreicate any help, I'm so stuck

**Comment by riadcitaku** [comment]
Have you tried changing the page template from Full Width to Default?

**Comment by eminakben** [comment]
Thanks Rriadcitaku, that solved the scrollbar problem. The page template in the pages section is already set to default however I went to customization and changed site width from full to boxed, the double scroll bar disappeared, however it didnt help with the footer. Do you have any idea what's going on with the footer. I try a to make a new footer, it doesnt appear either.

Should I maybe change some page width options inside the elementor editor?

**Comment by nicholaszein** [comment]
Hello @eminakben ,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
