### ISSUE TITLE
Elementor Tabs with Image Carousel in them

### ISSUE THREAD

**Issue by ava3a13** [elementor/elementor#10841]
Hello.
The problem is that, on changing Tabs,  Carousels built in them are breaking.
I have tried to give attributes to the swiper, using console:
```javascript        
const imageCarousel = jQuery ( '#bblock .swiper-container' ),
swiperInstance = imageCarousel.data( 'swiper' );
swiperInstance.params.observer = true
swiperInstance.params.observeParents = true
```
which results in Carousels working fine on changing active Tab.
But when I insert HTML box after the tabs (with <script></script> of course):
```javascript        
$(document).ready(function() {
        const imageCarousel = jQuery ( '#bblock .swiper-container' ),
        swiperInstance = imageCarousel.data( 'swiper' );
        swiperInstance.params.observer = true
        swiperInstance.params.observeParents = true
});
```
Result is:
`Uncaught TypeError: Cannot read property 'observer' of undefined` - Console Error

Do you know any other fix or can help me to change observer parameters without error.
Thank you

**Comment by Shini-D** [comment]
Hello,

I'm having the same problem. I created multiple section templates with one image carousel in them. I put the template shortcodes inside the content of the tabs and only the carousel of the first tab kind of worked, the rest were all broken.

The broken carousels didn't played automatically and the width of every item in the carousel was 100% of the carousel itself. The images themself had the correct size.

The carousel of the first tab didn't always played automatically.

I also tried to making it "manually". I created 2 section, one with four columns with buttons to use as tabs and other with all carousels inside. Until here everything worked fine, but when I added the jquery code to add an "active" class to the corresponding tab and carousel it broke again in the same way as described before.

The closed I got it to almost work was to put every carousel, but the first one, with absolute position and top 0, so they overlapped in the same position. And I change the CSS of the "active" class to chage the opacity from 0 to 1 instead of the display from none to block. The visual appereance was normal and they played automatically, but clicking the navigation arrows did nothing.

In the end I have to use the Slide Anything plugin to get them done instead of the elementor widgets.

**Comment by anybany** [comment]
@ava3a13 
i think you have to add `;` after your params like:

<pre>
$(document).ready(function() {
        const imageCarousel = jQuery ( '#bblock .swiper-container' ),
        swiperInstance = imageCarousel.data( 'swiper' );
        swiperInstance.params.observer = true ;
        swiperInstance.params.observeParents = true ;
});
</pre>

and maybe you have to update the swiper like:
<pre>
$(document).ready(function() {
        const imageCarousel = jQuery ( '#bblock .swiper-container' ),
        swiperInstance = imageCarousel.data( 'swiper' );
        swiperInstance.params.observer = true ;
        swiperInstance.params.observeParents = true ;

        swiperInstance.update();
});
</pre>

hope this helps ;)

**Comment by romapad** [comment]
Same problem, the code above from @anybany giving the same error, as mentioned in first post

**Comment by Cristianooo** [comment]
@anybany Hi I was having this problem as well with a media carousel instead of an image carousel. Could this code still work? And if so, can you explain the code further? Is #bblock the id of the carousel? Thanks
