### ISSUE TITLE
403 error 

### ISSUE THREAD

**Issue by ukasz-adm** [elementor/elementor#10913]
I see 403 error after updating my website.
I turned off security plugins but it do not work.

**Comment by color-space** [comment]
More information necessary

**Comment by drawcard** [comment]
403 is a forbidden error so I would start by checking the permissions of files on your server.

https://www.howtogeek.com/357785/what-is-a-403-forbidden-error-and-how-can-i-fix-it/

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it we simply can't help.

Try using this doc for better debugging: https://docs.elementor.com/article/185-the-update-button-does-not-work

Thanks.

**Comment by linehammer** [comment]
This error indicates that the server has determined that you are not allowed access to the thing you've requested, either on purpose or due to a misconfiguration . It's probably because the site owner has limited access to it and you don't have permission to view it.  The vast majority of the time, there's not much you can do to fix things on your (*client) end. There are three common causes for 403 [Forbidden](http://net-informations.com/q/mis/403.html) error (server side) . Here they are listed from most likely to least likely:

- An empty website directory
- No index page
- Permission / Ownership error
