### ISSUE TITLE
[BUG] Dont run redirect action with shortcode in url [Elementor PRO 2.9.1]

### ISSUE THREAD

**Issue by eduardovillao** [elementor/elementor#10919]
## Prerequisites
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

Dont run redirect action with shortcode in url. Like: https://www.google.com/search?q=[field id=name]

## Steps to reproduce

Add shortcode auto generated in url redirect like: https://www.google.com/search?q=[field id=name]
IMPORTANT: In input tab the auto shortcode generated dont have " " in id. 
IMPORTANT 2: Missing " " in shortcode its the BUG. If you add id between " " in shortcode action is run.

![Captura de Tela 2020-03-21 às 13 34 01](https://user-images.githubusercontent.com/60461940/77231396-69e43600-6b79-11ea-9f86-e2f93f07c0a5.png)

Elementor PRO version 2.9.1

## Isolating the problem
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lior-sh** [comment]
Hi @eduardovillao,

Thanks for reporting, this issue is not reproducible.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
*** Steps to replicate.**
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
