### ISSUE TITLE
✅ 🚀 Feature Request: Gallery widget lacks hide caption option

### ISSUE THREAD

**Issue by simonclay** [elementor/elementor#10972]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

The Gallery Widget lacks the ability to hide the caption. The Basic Gallery has this feature, but the Gallery does not.

Therefore you have to delete the title from every image in the gallery to stop the caption showing.

I think the Gallery widget should have the option to hide the caption, like the Basic Gallery does.

**Comment by nicholaszein** [comment]
Hello @simonclay!

Thank you for sharing your suggestion, and for being so patient! 🙏 

We are migrating all remaining Feature Requests from Issues to [Discussions](https://elemn.to/gh-feature-requests). 

While researching your request, we concluded that the feature you are requesting already exists in the (Pro) Gallery widget. It's just under a different setting because it has some extra features.

The option you are looking for can be controlled by changing both **`Title`** and **`Description`** settings to **`None`** in the **`Overlay`** section of the **`Content`** tab, as well as disabling the **`Background`** option. See the image below:

![image](https://github.com/elementor/elementor/assets/113993460/9f862be1-f8cf-4385-9db5-6622c3bc8a26)

For this reason, I'm closing this issue as solved.

Thank you for contributing! 💪
