### ISSUE TITLE
Popup close button not working

### ISSUE THREAD

**Issue by isaacharrisholt** [elementor/elementor#11055]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I created a popup for a mobile menu, but the entrance/exit animations weren't working. As soon as I added an exit animation, the close button stops working.

## Steps to reproduce

1. Create a new popup and view in mobile responsive mode
2. Set height to fit to screen and width as 70% vw
3. Set an exit animation
4. Use a button to open the popup (mine was in the header)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by lior-sh** [comment]
Hi @isaacharrisholt,

In Editor mode, we are not allowed to close the pop-up. 
Click on the Preview in order to check the close button.
Thanks.

**Comment by isaacharrisholt** [comment]
> Hi @isaacharrisholt,
> 
> In Editor mode, we are not allowed to close the pop-up.
> Click on the Preview in order to check the close button.
> Thanks.

I was using preview mode.

**Comment by JustinDouglas16** [comment]
Hi has this issue been solved cuz i also have the same problem

**Comment by MagneticArrow** [comment]
I had a similar issue and my root cause was that I had full screen for a mobile view on the pop up and the section that my content was in was overlapping the active area of the close icon.  I was using padding to move the content in the section, when I should have used margin to scoot the whole section down below the close button.

In this image, the padding is used, notice the blue section container perimeter encompassing (overlaying) the close button)
<img width="521" alt="Screen Shot 2023-02-21 at 11 57 55 AM" src="https://user-images.githubusercontent.com/74466276/220423318-c352546e-b183-48a1-b5a4-bcb2fe51f3d6.png">

This is with margin rather than padding applied, the section is now not covering the close button.
<img width="510" alt="Screen Shot 2023-02-21 at 12 00 06 PM" src="https://user-images.githubusercontent.com/74466276/220423679-cf6fb96c-863d-49fd-b79a-b43a98de9e07.png">

**Comment by ommiamin** [comment]
thanx , that worked

**Comment by HazmeUnaPaginaCL** [comment]
> I found this [solution](https://element.how/elementor-pop-ups-problems/#:~:text=If%20you%20have%20an%20intro,apply%20on%20tablets%20on%20mobile.), basically it mentions that you have to disable the animation in the desktop view and enable it in the mobile view. It works for me

Works pretty good, thanks a lot!

**Comment by felipenneto** [comment]
> Encontrei esta [solução](https://element.how/elementor-pop-ups-problems/#:~:text=If%20you%20have%20an%20intro,apply%20on%20tablets%20on%20mobile.) , basicamente ela menciona que você precisa desabilitar a animação na visualização do desktop e habilitá-la na visualização do celular. Funcionou para mim.

I had this problem today and managed to solve it this way, thanks a lot!
