### ISSUE TITLE
Media carousel media library image links crash after domain change

### ISSUE THREAD

**Issue by vladarte** [elementor/elementor#11054]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After standard domain change using config.php and themes functions.php the Media carousel image links to Media file located in Media library still point to old domain. Maybe absolute/relative issue.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by udidol** [comment]
Hi @vladarte,
You should **back up your database**, and then try using Elementor's _Replace URL_ tool. This should be done whenever running into issues like yours after changing the domain for an Elementor site.

To use our Replace URL tool, go to your WP dashboard, and in the sidebar menu go to Elementor > Tools > Replace URL.

This should solve your issue. Before you use it, it is highly recommended you back up your database, since it is an irreversible process.

**Comment by vladarte** [comment]
> Hi @vladarte,
> You should **back up your database**, and then try using Elementor's _Replace URL_ tool. This should be done whenever running into issues like yours after changing the domain for an Elementor site.
> 
> To use our Replace URL tool, go to your WP dashboard, and in the sidebar menu go to Elementor > Tools > Replace URL.
> 
> This should solve your issue. Before you use it, it is highly recommended you back up your database, since it is an irreversible process.

Thank you, that helps
