### ISSUE TITLE
Elementor + MailChimp | Form Tag Not Being Added To Contact If Already Exists In MailChimp Audience

### ISSUE THREAD

**Issue by maxlatitude** [elementor/elementor#11111]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

This issue involves native Elementor forms with the Mailchimp API integration.

During form submission, if a contact already exists in the Mailchimp audience with a tag, the Elementor form's new tag is not added to the Mailchimp contact, and the contact is not updated. In essence, the contact is ignored as already existing.

The logical, preferred behavior is to add the form's tag to the existing Mailchimp contact. This functionality is possible, and is seen in other form platforms, such as GravityForms. Adding the form's tag to an existing contact highlights an action performed. This is very important for Elementor sites with multiple forms with different purposes linking to Mailchimp, and allows targeted replies based on the contact's tag without creating a new audience in Mailchimp.

## Steps to reproduce

Create an Elementor form with the Mailchimp API integration and audience. Set unique tag for form submissions, and link fields with Mailchimp fields. Save. Fill out the default form with an already existing contact in Mailchimp and submit.

The existing contact in Mailchimp is not updated with the unique tag, and new action.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
Operating System: | Linux |  
-- | -- | --
Software: | Apache/2.4.43 (Unix) OpenSSL/1.1.1 |  
MySQL version: | (Ubuntu) v5.7.29 |  
PHP Version: | 7.3.16 |  
PHP Max Input Vars: | 5000 |  
PHP Max Post Size: | 1024M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected


```
</details>

**Comment by MirkoMontagna** [comment]
I have the same problem. Do you have any feedback about this problem?

**Comment by PaulinHalenria** [comment]
On the Elementor's webpage https://docs.elementor.com/article/211-mailchimp we can read this affirmation 

"Please note also that the API of MailChimp does not allow joining a list with the same email address more than once. You will receive an error in this case.

In addition, the MailChimp API does not allow updating tags for existing contacts. Tags can only be added to new contacts."

But on the API documentation on Mailchimp's website https://mailchimp.com/developer/guides/organize-contacts-with-tags/ we can found how to add a tag to an existing subscriber.

So Elementor should intercept the error message when trying to subscribe the user as already subscribed and then send the command to add the tag to an already subscribed user (using the md5 value of lowercase version of its email address).

Doing this Elementor would be really a tool for landing pages.

**Comment by huntertl** [comment]
+1

**Comment by studioukkonen** [comment]
+1

**Comment by yandaq** [comment]
+1 for this. This is desperately needed.

**Comment by 851000** [comment]
Any workaround?
My client decided to go for MailChimp because it's cheaper and just know I find this issue.

I want to implement a sequence for newsletter subscribers and another one for lead magnets.
What's the best approach?
Create 2 audiences?

**Comment by aidanmcnally** [comment]
We are also having this issue. 

We keep resources behind forms (e.g. PDFs). If someone who has already filled in a form (and thus added to our mailchimp list) tries to fill in another form to get another resource, the form redirect to the page that hosts the resource fails, so they never receive the resource. 

The steps we have are 'email', 'redirect', 'mailchimp'. The redirect fails even if it is before mailchimp in the sequence of steps. 

There should be an option in Elementor 'What to do if the person is already subscribed to the mailchimp list' - And the obvious options would be 'update the user details', 'don't update the user details', 'add to group A' etc. 

Right now it just fails, which is really surprising for a plugin that is so ubiquitous on WordPress. 

This is really a crucial component of integration with MailChimp and needs to be addressed ASAP. 

Thank you

**Comment by earthcub** [comment]
I'm having the same issue.  Tags implementation is critical for use with Mailchimp and updating a user instead of failing is critical for users to not consider your web site malfunctioning.  The psychology behind trust is super important here.

**Comment by coachdesign** [comment]
I have the same problem, and it is a very serious problem.
Right now, I have found that if the registered email is already present in audience, it updates the fields such as name, surname, phone, but does not add any tags.

Could it be a solution to manage with groups?

**Comment by ajmalsnap** [comment]
me too, trying to create two forms with different tag. any solution?

**Comment by EmilieEsposito** [comment]
Same problem for me, and very annoying.
I've bought the standard plan of mailchimp, to use automation with adding a tag as a starting point, so that my audience can get pdf lead magnet. But if Elementor cannot add a tag to an existing contact, I will have to create a new audience for each of my lead magnet... Or use Mailchimp form embedded in my elementor page, which doesn't suit me, because they enable not as much customization as Elementor's ones...
So please, please Elementor ! Make my life easier and correct that feature :-)

**Comment by coachdesign** [comment]
Waiting and hoping elementor fixes the problem... i used a little workout using groups.
It will probably only help whoever is in the same case as me.
I assign the contact already present in the audience to a group, then I create an automation such that as soon as the contact is added to the group, it receives the welcome email and as a post-sending action assigns the tag.

**Comment by EmilieEsposito** [comment]
Very interesting, @coachdesign! Do you mean that if your elementor form add a existing contact to a group (and not to a tag), it works? Is it the case if the contact already was in one or several groups ?

**Comment by coachdesign** [comment]
> Very interesting, @coachdesign! Do you mean that if your elementor form add a existing contact to a group (and not to a tag), it works? Is it the case if the contact already was in one or several groups ?

yep it works...

**Comment by EmilieEsposito** [comment]
Thanks a lot @coachdesign, you just made my day!

**Comment by EmilieEsposito** [comment]
@coachdesign it worked perfectly ! I haven't automated the adding of the tag, since it is possible to trigger an automation when a contact joins a group.
@earthcub this is how I've done it :
- create a group in mailchimp
- create an automation in mailchimp, with a trigger when a contact joins this group
- in the elementor form, in the actions, I have selected Mailchimp, my audience and the group I had just created. And no tag.

**Comment by adambirds** [comment]
Does anyone know when this will be resolved, it is kind of critical to be able to use mailchimp effciently.

**Comment by markd91** [comment]
Another workaround for this - use hidden fields on your signup forms. 

Groups are supposed to be user-facing so that may not be ideal for everyone.

Mailchimp > signup forms > form builder.

Add a text field & make it hidden. Leave default value blank. Give it a title you'll recognize (what you would've titled your tag).

In the elementor form create a hidden field, call it "mailchimp tag" (or whatever you want) and in advanced set its default value to "yes" (or anything you want).

In your mailchimp submission settings for the form, find the hidden signup form field you created, and map the hidden elementor form field to it. 

Now you can create a segment in mailchimp whose criteria is [hidden signup form field] = "yes"

You can also create a mailchimp automation based on -- Subscriber Updates > Respond to Subscriber Updates > then choose your hidden field and make the criteria "yes"

**Comment by shilo-ey** [comment]
Hey all,

This feature has been added to Elemetnor Pro v3.3.0

Feel free to update

Cheers!

**Comment by gonzalobarria** [comment]
Hello!!!!... I just found that this version (3.3.0) is deleting all my costumer's tags. If you have an user with tags and he is filling a new form, automatically delete all my tags! Ihad to rollback to the 3.2.2 to fix this problem.

**Comment by Aviad-Herman** [comment]
> Hello!!!!... I just found that this version (3.3.0) is deleting all my costumer's tags. If you have an user with tags and he is filling a new form, automatically delete all my tags! Ihad to rollback to the 3.2.2 to fix this problem.

Thank you for raising this issue @gonzalobarria . We have a PR and will release a hotfix shortly

**Comment by rfgdeleeuw** [comment]
Just updated to Elementor Pro 3.4.0-dev12. However, I keep getting an error message (a red cross without text underneath the form) when I try to register an email address that already exists in my database (even though it's archived).

The scenario I need (like many here):
- User registers for event
- User later decides to register for newsletter (or other event)

Either I am messing something up, or the fix isn't fixing it.

Update:
- Also audience seems to take forever to load with the default API key. A custom key (and then using the same one) works fine though.
![image](https://user-images.githubusercontent.com/74461599/125096008-061aaf00-e0d5-11eb-8776-da806721fa06.png)

- Any thoughts?

**Comment by Aviad-Herman** [comment]
@rfgdeleeuw I'll answer here but if you have any followup questions please open a new issue thread and tag me.

Regarding archived users:
I need to know the exact steps to reproduce this because Mailchimp have their own complex rules about handling existing users. They act different depending on the way someone opted out. Sometimes it is impossible to re-sign someone. The only thing we can do on our end is to supply better error messages (if Mailchimp supplies them)

Regarding the Default API. Make sure it's configured correctly in Elementor --> Settings --> Integrations.

If you need to open a conversation, please open a new thread.
