### ISSUE TITLE
Video background stops after lock screen

### ISSUE THREAD

**Issue by haywirephoenix** [elementor/elementor#11142]
To reproduce:

Set youtube url video background 
Enable 'show on mobile'
Load page, lock and unlock screen, video is stopped. Suggested links display.

To resolve:

Maybe a listener that runs when the window resumes focus and plays the video?

**Comment by lior-sh** [comment]
Hi @haywirephoenix,

Please keep in mind that due to [Google autoplay policy ](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) the websites that will play autoplay websites are only the ones with high media engagement score.

The initial click on the image opens the video lightbox with an autoplay attribute which might not work immediately in some cases when the Media Engagement score is relatively low.

Thanks.
