### ISSUE TITLE
Cannot control the style of the input element in the Search Form Widget

### ISSUE THREAD

**Issue by princesshorsepower** [elementor/elementor#11258]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

1. Define a global theme style for form elements
2. Place a search form widget somewhere on a page
3. Found no way to control the border style of the input field

To see life
1. Goto [fernschmecker.blog/test](https://fernschmecker.blog/test)
2. See my attached screenshots which explain my issue
2a. screen1.png the green border + radius comes from the global theme style, when the input is active
2b. screen2.png the red border + radius comes from the Search Form

So how can I control the green border + radius of the Input Element

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

System Info attached...
![screen1](https://user-images.githubusercontent.com/52812059/80669692-9f186800-8ad7-11ea-8ab8-5785d39466bc.png)
<img width="209" alt="screen2" src="https://user-images.githubusercontent.com/52812059/80669705-a8093980-8ad7-11ea-8d2e-210b7f1efea3.png">
[system-info-fernschmecker.blog-30-04-2020.txt](https://github.com/elementor/elementor/files/4556004/system-info-fernschmecker.blog-30-04-2020.txt)

**Comment by lior-sh** [comment]
Hi @princesshorsepower,

You can control the Style of the input in the Search Form widget like that:
Go to Theme Style > Open the Form Fields section > There you can set the Text Color, BG Color, Typography, etc..
Thanks.

**Comment by princesshorsepower** [comment]
I know, that I cannot control the Style. This is why I created the ticket.
All Widgets are able to override the Global Theme Style. 
But the Search Widget seems to be an exception.

I want to achieve the following, see Screenshot. The upper example comes from the Global Style.
But I want to have the lower example. Not as global style, only in one popup.
This popup has a dark background, so I don't want to use the global style. And I cannot use a border radius here, since the border should merge straight into the search button.

![image](https://user-images.githubusercontent.com/52812059/81542752-bbee4e80-93a7-11ea-9e59-adb5c2e34fe9.png)

**Comment by artifex-media** [comment]
Related to #11345, much bigger problem than it seems as it is being applied globally and on ALL of the element types (button css goes to all buttons, etc., etc.,)

**Comment by princesshorsepower** [comment]
> 
> 
> Related to #11345, much bigger problem than it seems as it is being applied globally and on ALL of the element types (button css goes to all buttons, etc., etc.,)

Basically I think this is not an issue, since it is a global setting. But there should be a way to override it for every Widget.

**Comment by udidol** [comment]
Hi @princesshorsepower ,
The input **Border Size** and **Border Radius** controls apply to the entire widget, meaning both the text input and the button.
Theme Style's form controls target specific inputs, that is why this issue is occuring.

The Search Form widget does not currently have controls that allow handling just the search input. We will look into the possibility of adding new controls, but in the meantime, you can use CSS to manually control the border design of the search form input.

If you have Elementor Pro, you can use the widget's Custom CSS feature in the widget's Advanced tab > Custom CSS, and paste the following there:
```
selector .elementor-search-form__container input[type="search"].elementor-search-form__input {
    border-width: 10px;
    border-color: red;
    border-style: solid;
    border-radius: 10px;
}
```
Change the property values to the ones you need. 

If you don't have Elementor Pro, here is the CSS that will do the trick:
```
.elementor-widget-search-form .elementor-search-form__container input[type="search"].elementor-search-form__input {
    border-width: 10px;
    border-color: red;
    border-style: solid;
    border-radius: 10px;
}
```
Again, change the property values to the ones you need. 
You can add this CSS to either your **child theme's** `style.css` file, or in the WordPress Theme Customizer's "Additional CSS" section.

**Comment by princesshorsepower** [comment]
@udidol thanks for this temp solution
