### ISSUE TITLE
Swiper slider not working in multiple tabs

### ISSUE THREAD

**Issue by arjun1638** [elementor/elementor#11250]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

the layout is broken when Tabs are used with a slider inside it. 

## Steps to reproduce

I have created a template with a slider and entered the shortcode inside the tabs but somehow having an issue when we switch tabs it's broken, somehow tried to reinit with js but didn't work out as expected.

tried using following code
 var imageCarousel = jQuery ( '#elementor-tab-content-4081 .swiper-container' ),
        swiperInstance = imageCarousel.data( 'swiper' );
        swiperInstance.params.observer = true ;
        swiperInstance.params.observeParents = true ;
        swiperInstance.update();

but index images are still broken

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

Elementor Pro: by Elementor.com – 2.9.3
Elementor: by Elementor.com – 2.9.8
Elementor - Header, Footer & Blocks: by Brainstorm Force
</details>

**Comment by lior-sh** [comment]
Hi @arjun1638,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by seanbrokenshire** [comment]
I wrote the following to overcome this problem (I had a different slider on every tab, so needed a generic way to refresh each slider when the tab was clicked).

`
<script>
  | function refreshTabSlider(tabID) {
  | console.log('Refreshing Tab Slider' + tabID);
  | var imageCarousel = jQuery("#" + tabID + " .swiper-container");
  | swiperInstance = imageCarousel.data('swiper');
  | swiperInstance.params.observer = true;
  | swiperInstance.params.observeParents = true;
  | swiperInstance.update();
  | imageCarousel.css('visibility','visible');
  | }
  |  
  | jQuery(document).ready(function() {
  |  
  | jQuery(".elementor-tab-title").on("click", function(){
  |  
  | var $this = jQuery(this);
  |  
  | var tabID = $this.attr('aria-controls');
  |  
  | var imageCarousel = jQuery("#" + tabID + " .swiper-container");
  | imageCarousel.css('visibility','hidden');
  |  
  | setTimeout(
  | function(){
  | refreshTabSlider($this.attr('aria-controls'));
  | },100);
  |  
  | });
  |  
  | });
  |  
  | </script>
`

**Comment by woodydaniel** [comment]
This worked for me.
Thanks for the solution!!

**Comment by foss-friendly** [comment]
Just a small hack which might be useful to someone still struggling with this in mid-2021. I have a page with 7 Swiper Slider instances, 4 of which are nested in Elementor accordion tabs via templates. The slider is configured to show 5 slides per row with 10 px padding between the items of this "sliding catalog". The 3 instances outside the accordion tabs are working fine, but the remaining  4 instances were showing just the first item (and not 5 per row), and the right margin was in the void. I read in the Swiper Docs that a swiper.update() shall be fired since it can't fetch the screen size if it's hidden while the page is loading. However, I couldn't target dynamically all instances of the slider using the snippet in the Swiper Docs, nor the one in the Elementor blog post, since it was only partially working, depending of the page load time. And after 12 hours banging my brain around this issue and trying everything I found on Google, I figured a workaround. See... after a deeper dive in the Swiper Docs, I discovered that a Resize Event in the browser fires a swiper.update() ! And so, here is the solution:

1. Target the tabs using **document.querySelectorAll**.
2. When user clicks, start spamming **Event('resize')** every 1 second.
3. **Timeout** the spam after five seconds, which shall be enough for the DOM to be loaded.

This code goes to Elementor -> Custom code. Just don't forget to configure the appropriate instances, since you don't need the Event('resize') spam on every page, featuring '.elementor-tab-title'.
**Disclaimer:** I'm very weak in coding... I can only read code. If a master coder sees something stupid in this snippet (p.ex. if it doesn't do what I think it does), I'll be extremely grateful if it gets fixed. Anyway... it's working now so I can continue with my project.

`<script>
document.querySelectorAll('.elementor-tab-title').forEach(item => {
const interval = setInterval(function() {
 window.dispatchEvent(new Event('resize'));
 }, 1000);
setTimeout(function( ) { clearInterval( setInterval ); }, 5000);
	});
</script>`

**Comment by davidduong90** [comment]
> ar refreshSliders = function(){
> 
> 		jQuery( ".swiper-container" ).each(function( index ) {
> 			swiperInstance = jQuery(this).data('swiper');
> 			swiperInstance.params.observer = true;
> 			swiperInstance.params.observeParents = true;
> 			swiperInstance.update();
> 		});
> 
> }
> 
> window.onload = function()
> {
> 	console.log('Document loaded');
>    
>    jQuery(".elementor-tab-title").on("click", function(){ 
>        console.log('Tab has been clicked');
>    			var $this = jQuery(this);
> 	
> 	refreshSliders();
> 	
> 	jQuery('html,body').animate({
>     					scrollTop: $this.offset().top - 220
> 					}, 500); 
> 
> 		
> 	});
> }

It work for me. Thank you so much!

**Comment by dimav-code** [comment]
Hi the code works in desktop, but in mobile my second tab doesn't Work :(

**Comment by davidduong90** [comment]
Hello @dimav-code 

I have checked my code on iPhone 6 but it works fine.  If you need more help please add my skype duongquyet90

**Comment by jahanzaib-j** [comment]
can anyone help me? where I write this code?

var refreshSliders = function(items){ 
	items.each(function( index ) {
		swiperInstance = jQuery(this).data('swiper');
		swiperInstance.params.observer = true;
		swiperInstance.params.observeParents = true;
		swiperInstance.update();
	});
}

window.onload = function()
{
	jQuery(".eael-tab-item-trigger").on("click", function(){
		var $this = jQuery(this);
		
		var items = jQuery(this).closest( ".eael-advance-tabs" ).find('.eael-tab-content-item.active').find('.swiper-container');

		refreshSliders(items);
	});
}

**Comment by Shahnawaz-AbdulRehman** [comment]
> davidduong90

Man you are a life saver :)
