### ISSUE TITLE
Theme Style also apply's Button CSS to Audio Player/Media Element JS

### ISSUE THREAD

**Issue by artifex-media** [elementor/elementor#11345]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When setting Button styles within Theme Style, the CSS get's applied to áll input[type=submit],input[type=button] elements causing the audio player with me-js have broken buttons.

![image](https://user-images.githubusercontent.com/43996366/81619078-0cd26700-93e9-11ea-8e0b-f1a7726c264c.png)

## Steps to reproduce

Apply Button styling within Theme Style, add Audio player widget to page.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
https://pastebin.com/mwF6k67E
</details>

**Comment by princesshorsepower** [comment]
I have similar issue with the Search Form widget.
[https://github.com/elementor/elementor/issues/11258](https://github.com/elementor/elementor/issues/11258)

But they just ignored it and closed the ticket

**Comment by artifex-media** [comment]
> I have similar issue with the Search Form widget.
> #11258
> 
> But they just ignored it and closed the ticket

I see they re-opened it, let's hope it'll be fixed soon

**Comment by udidol** [comment]
Hi @artifex-media,

Since Media Element is an external plugin, we cannot control its elements' CSS selectors.
Theme Style's CSS gets applied to all `input[type=submit]` and `input[type=button]` elements because it is a global setting for the entire website, and that's exactly what it should do.

To solve your problem, you should either manually add CSS styling selectors to the Media Element plugin's elements, or contact the Media Element plugin authors and ask them to harden their CSS with more selectors so it overrides Theme Style.

The Search Form widget, in the issue that was mentioned (#11258), is an Elementor Pro element, so we will address this issue in that specific widget and harden it's inputs CSS selectors to override Theme Style.

**Comment by artifex-media** [comment]
@udidol I do not agree, as a website with only WordPress core and Elementor running, without any changes except for modifications on Theme Style, causes this issue since WordPress has Media Element built-in, not running as third party plugin, meaning a normal user cannot disable it even though they would want it since the styling is broken when using Theme Style. 

Since it's built-in to WordPress and your Theme Style breaks a core functionality/styling, shouldn't it be fair enough to exclude the Media Element's (parent) classes from your selectors? I can understand it's annoying as Media Element does not apply classes to the button elements itself but rather it's parent, but still - not hard to do :)

And I don't agree on the suggestion to add manual CSS, as above mentioned it's a built-in feature in WP - it should not even break at all and you cannot expect 'normal' users which use Elementor without code (because it's advertised as magic and 'no code required') to add CSS styles themselves to fix the broken players.

**Comment by udidol** [comment]
Oh, I didn't get that you were referring to the native WordPress audio widget that's included in Elementor's WordPress widget package. 

What browser are you using?
I tried to reproduce your issue, and at least in up-to-date Chrome and Firefox browsers, Theme Style does not affect the audio player layout.
It looks completely different for me:

In Chrome:
![image](https://user-images.githubusercontent.com/36724484/82412349-2aa06b80-9a7c-11ea-96b4-fa074e3d51dc.png)

In Firefox:
![image](https://user-images.githubusercontent.com/36724484/82412450-591e4680-9a7c-11ea-8467-b0431f1c2693.png)

Try to update your browser.

**Comment by artifex-media** [comment]
Hi @udidol,

I am using latest Chrome, however, this issue is present on clean installs with ONLY WordPress, Elementor, Elementor Pro and Hello Theme and Hello Theme Child active.

I can understand you cannot control all markups, however, I think it should be fair enought that Theme Styles should append it's styles on .elementor classes, and not randomly all buttons. 

Take a look at this clean example with jus WP, Elementor, Elementor Pro and Hello Theme:
http://artifexmedia.nl/test/

I gave the buttons with Theme Style a simple background and different typography, gave it a border and some padding, made a front page with just audio player and now look what happens below. Is it possible you maybe did not edit the Theme Style Buttons (as you could not re-produce)?

![image](https://user-images.githubusercontent.com/43996366/82844128-9d2ba400-9edf-11ea-95cf-49eb2dc9b82b.png)

This happens on all browsers, also mobile. Within Elementor Preview it will look great, however, live it will have changed buttons related to Theme Style. So, if you add a border, it will add borders to audio player buttons as well. If you add padding, same thing.

![image](https://user-images.githubusercontent.com/43996366/82844124-96049600-9edf-11ea-8ba3-557106cf2d96.png)


All of those in combination with background changes causes the ugly player on my first post, I have used padding, border, background color, text color and typography on Button with Theme Style, which then appends it to áll buttons and inputs with type submit.

I think that should either try to exclude the core (!!) audio player from WordPress ór trigger only .elementor classes. If it can do that in the preview area, why not live?

**Comment by udidol** [comment]
Hi @artifex-media ,

I was able to reproduce this issue. You are right, Theme Style's selectors should not override native WP elements. This is a complicated issue to solve, since hardening Theme Style's CSS selectors could cause them to override previously-harder selectors in existing elements.

Unfortunately, we cannot change the audio player setup generated by WordPress at this point, since it can affect the appearance of a large number of existing websites.

Right now the best thing I can suggest is custom CSS to override Theme style in this instance, or alternatively, just not to use Theme Style to style buttons. You can use custom fields and dynamic values for colors if you want to control site-wide values in a central location.

In the upcoming Elementor 3, we are overhauling the whole Theme Style section and the entire way we handle site-wide styles, so such problems are expected to be solved.

**Comment by artifex-media** [comment]
Hi @udidol,

Glad to hear you were able to reproduce :)
For now I will use custom CSS to override, but I sincerely hope it will be fixed in Elementor 3, as I noticed it causes issues on many more elements than just the audio player.

Thank you for your effort so far!

**Comment by tomherold** [comment]
Hello @udidol,

Could you share the CSS to override the audio player?

**Comment by udidol** [comment]
@tomherold 
You can use any 3 selectors that match the audio player.
An example for a selector that works:
```
.elementor-widget-wp-widget-media_audio .mejs-container button {
   // Your CSS properties here
   // e.g.: background-color: initial;
}
```

**Comment by tomherold** [comment]
Great, thank you! Any idea when Elementor 3.0 comes out?

**Comment by udidol** [comment]
@tomherold
Oh, can't help you with that one 😉
