### ISSUE TITLE
How to listener event when user click Update button?

### ISSUE THREAD

**Issue by notrealdev** [elementor/elementor#11414]
Hi, how to listener event when user click Update button? I have find some thing in `elementor/assets/js/editor.js` file but i don't see any positive signs
Can anyone suggest me for this case? Thanks.

Please check my image:
![Imgur](https://i.imgur.com/WnGwTj6.jpg)

**Comment by notrealdev** [comment]
Hi there, i tried add js file with hook
```php
add_action( 'elementor/editor/before_enqueue_scripts', array( $this, 'enqueue_editor_scripts' ) );
```

And some js like this:
```js
elementor.saver.on(
    'after:save',
    function( data ) {
        console.log( 'Updated!' );
    }
);
```

This worked when user click Update/Publish button.

But it seems that it will be deprecated in the next versions:
https://developers.elementor.com/v2-9-0-planned-deprecations/
```
// console warning
`elementor.saver.on` is soft deprecated since 2.9.0 - Use `$e.hooks` instead
```
So I'm looking for a way to switch to `$e.hooks`, but I'm stuck here.
How to listener Update event using `$e.hooks`?
I need your help. Thanks.

**Comment by webdevs-pro** [comment]
Please answer here

**Comment by iNewLegend** [comment]
See this as an example:
https://github.com/elementor/elementor/blob/master/core/kits/assets/js/hooks/ui/document/save/save/after.js

But instead of `import After from 'elementor-api/modules/hooks/data/after';`
use `$e.modules.hookData.After`

examples & more information available here:
https://github.com/elementor/elementor/blob/master/docs/core/common/assets/js/api/core/hooks.md
