### ISSUE TITLE
"javascript:history.back()" bug since last update

### ISSUE THREAD

**Issue by Code711** [elementor/elementor#11460]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Since the last Elementor update all my buttons with a "javascript:history.back()" link are broken. in Elementor's backend everything looks correct, but the output in all browsers ist now "www.mydomain.com/javascript:history.back()" which produces a 404 error! 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41
	MySQL version: Source distribution v5.6.19-67.0
	PHP Version: 7.2.19
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Not connected (cURL error 28: Operation timed out after 5000 milliseconds with 0 bytes received)

== WordPress Environment ==
	Version: 5.4.1
	Site URL: https://www.XXXXX.de
	Home URL: https://www.XXXXX.de
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 2.4.4
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

== Active Plugins ==
	Adminimize
		Version: 1.11.6
		Author: Frank Bültge

	Advanced Custom Fields PRO
		Version: 5.8.11
		Author: Elliot Condon

	Antispam Bee
		Version: 2.9.2
		Author: pluginkollektiv

	Crazy Lazy
		Version: 1.0.4
		Author: pluginkollektiv

	Duplicate Post
		Version: 3.2.4
		Author: Enrico Battocchi

	Elementor
		Version: 2.9.9
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.5
		Author: Elementor.com

	iThemes Security
		Version: 7.7.1
		Author: iThemes

	JetElements For Elementor
		Version: 2.2.14
		Author: Crocoblock

	Login LockDown
		Version: v1.8.1
		Author: Michael VanDeMar

	WP Super Cache
		Version: 1.7.1
		Author: Automattic

	Yoast SEO
		Version: 14.1
		Author: Team Yoast


== Elements Usage ==
	
	archive : 3
		archive-posts : 2
		global : 1
		heading : 1
		nav-menu : 2
		posts : 1
		spacer : 1
		text-editor : 4
	footer : 1
		button : 1
		nav-menu : 1
		text-editor : 3
	header : 1
		button : 1
		image : 2
		menu-anchor : 1
		nav-menu : 1
	popup : 1
		accordion : 1
		heading : 1
		image : 1
	single : 4
		button : 5
		heading : 2
		nav-menu : 3
		spacer : 3
		text-editor : 9
		theme-post-content : 3
		theme-post-featured-image : 3
		theme-post-title : 3
	widget : 0
		jet-slider : 2
		nav-menu : 1
		slides : 2
	wp-post : 
		button : 1
		global : 9
		heading : 3
		image : 26
		image-carousel : 2
		nav-menu : 2
		slides : 1
		spacer : 3
		text-editor : 229
		theme-post-featured-image : 4
		toggle : 4


== Log ==
	
Log: showing 20 of 382019-10-30 16:38:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.7.5',
)]
2019-10-30 16:38:04 [info] elementor::elementor_updater Started 
2019-10-30 16:38:04 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-10-30 16:38:04 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-10-30 16:38:04 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-10-30 16:38:05 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-10-30 16:38:05 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Start  
2019-10-30 16:38:05 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2019-10-30 16:38:05 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start  
2019-10-30 16:38:06 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2019-10-30 16:38:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.7.5',
)]
2019-10-30 16:38:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.11',
  'to' => '2.7.3',
)]
2020-05-08 17:36:37 [info] elementor::elementor_updater Started 
2020-05-08 17:36:37 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-05-08 17:36:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.9.8',
)]
2020-05-08 17:36:37 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-05-08 17:36:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.9.8',
)]
2020-05-08 17:36:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.3',
  'to' => '2.9.4',
)]
2020-05-24 17:22:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '2.9.9',
)]
2020-05-25 10:37:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]

PHP: showing 4 of 4PHP: 2019-04-25 20:05:18 [warning X 1][/kunden/195062_70734/webseiten/wp-content/plugins/elementor-pro/core/upgrade/upgrades.php::705] in_array() expects parameter 2 to be array, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-26 14:37:12 [notice X 82][/kunden/195062_70734/webseiten/wp-content/plugins/elementor/core/files/css/base.php::703] Undefined index: _id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-10-30 16:38:56 [notice X 90397][/kunden/195062_70734/webseiten/wp-content/plugins/elementor/includes/widgets/accordion.php::505] Undefined index: icon_active [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-08 17:43:38 [error X 17][/kunden/195062_70734/webseiten/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 104857600 bytes exhausted (tried to allocate 8739236 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>

**Comment by shilo-ey** [comment]
Hi @Code711 

Thanks for your input.

We removed the option to add JavaScript to the URL to avoid potential security issues.

You can still achieve this functionality by adding custom JS externally:

Set a class for your button (e.g `classname`)
And add this JS code to your page/site footer.
```JS
$('.classname').on('click', function(e){
    e.preventDefault();
    window.history.back();
});
```

Or if you add it externally make sure your document was loaded:
```JS
jQuery(document).ready(function($){
	$('.classname').on('click', function(e){
 	   e.preventDefault();
 	   window.history.back();
	});
});
```

**Comment by plm2950** [comment]
Hello shilo-ey, @Code711 or anyone who can help me out. I have exactly the same issue and while the change is an inconvenience, I can understand why the change was made. My problem is that I don't know how to add the above script or where to place it. I have tried using a plugin for adding JS but to no avail. I have also read that the "$" isn't recognised by WordPress, not sure about this. I use a previous button (created as atemplate) on most pages. I'm not sure who to ask for help so hope this is ok.

**Comment by Libero96** [comment]
@Code711 I have experienced the exact same problem. Elementor support gave me this topic as advice. 

@plm2950 I've got the same situation. I get why they changed it, but I do not have the knowledge to know exactly where to past the code provided above. If anyone does know how it's needs to be done, feel free to post it here :).

**Comment by frantzolasf** [comment]
Same with me. I've got the same situation. If anyone does know how it's needs to be done, please post it here :).

**Comment by frantzolasf** [comment]
I found a (temporary?) solution. I used the Premium Button widget from Premium Addons for Elementor. It is free, widely used and highly commented. The Premium Button widget supports "onclick Event", where you can enter your javacript (probably without the "javascript:" prefix).

**Comment by shilo-ey** [comment]
Hi all,

If the above script doesn't work for you, please make sure you are defining $ as jQuery as updated in the first line.

Make sure to change the selector based on your button selector.

For example:
1. To add this functionality cross-site, add an HTML widget to your footer and place this code there:
```HTML
<script>
$ = jQuery;
$('#back-btn').on('click', function(e){
    e.preventDefault();
    window.history.back();
});
</script>
```
We place it in the footer to be included in each page that this button is placed in. in the same manner you can add this script to your functions.php file:
```PHP
function your_scripts() {
	?>
<script>
jQuery(document).ready(function($){
	$('#back-btn').on('click', function(e){
 	   e.preventDefault();
 	   window.history.back();
	});
});
</script>
	<?php
}
add_action( 'wp_footer', 'your_scripts' );
```

2. Go to the button you wish to act as back button and add this ID to the button: `back-btn`
3. Once you click on this button - you will see that the user will go back.

You can either use 3rd party plugin to add this code to your site.

I hope it makes things more clear.

Thanks

**Comment by Libero96** [comment]
@shilo-ey Thanks a lot for the additional information! I got it working now. 

As my footer is custom made, I simply added a Elementor HTML widget to it and choose to hide it on all devices with the 'responsive'-settings located under the 'custom' tab of the widget. 

After that was done, I copied and pasted the code you provided in step 1 in this HTML widget. 

I saved the footer, by pressing the green button below, and moved on to the page where my 'go back' button is located. Once I selected the settings of the button, I added the `back-btn` to the 'Button ID'.

**Comment by catcontent2020** [comment]
@shilo-ey Thanks for your information. 
But here it only works as long as I am logged in to the site. With a "fresh" broswer e.g. a incogito-window it doesn't work.
Any ideas?

**Comment by Libero96** [comment]
@catcontent2020 When I log out of my website, delete all my cookies and visit my own website with an incognito-window, the 'previous page' button works just fine.

**Comment by frantzolasf** [comment]
Thank you @shilo-ey for the valuable information! It works now! Much obliged!

**Comment by pe56** [comment]
I have the same problem. For me the above mentioned works only when logged in WP (though cursor hover (arrow –> finger pointing) seems not to work). After log out this is not functioning at all in any browser with caches cleared.

**Comment by catcontent2020** [comment]
@shilo-ey @pe56 
For now I've tried an switched off all plugins, changed the theme to "Hello - from elementor" and still: It doesn' work. Any ideas?

**Comment by pe56** [comment]
I decided (or had to) leave the back button all away, I could not get it to work properly.

Anyway I noticed in the browser console that the jQuery did not load, the first line on the script did fall off ($ = jQuery;). On my proto site this worked ok, but on the actual site not.

I also tried this (which also worked ok on demo but not in production), I don‘t know if it’s of any use (I did put it in the html-widget in the footer):

<script>
var button = document.getElementById("back-btn");
button.addEventListener("click", goBack);
function goBack() {
window.history.back();
}
</script>

**Comment by jacalakie** [comment]
I have also been passed to this page from Elementor support. I don't think this is a JAVA issue but an issue using shortcodes to pass information to a shopping cart via an Elementor button link.

Until now I have been able to pre-populate my shopping cart (ThriveCart) with a user's/member's Name and Email address from an Elementor button. This is REALLY useful in preventing data input mistakes, particularly as the CORRECT data is _already_ availabe in Wordpress.

**An exmple Elementor button link for this looks like:**

`https://mydomain.thrivecart.com/sample-product-cart/?passthrough[customer_email]=[mbr_db_email]&passthrough[customer_firstname]=[mbr_db_first_name]&passthrough[customer_lastname]=[mbr_db_last_name]`

The plugin that generates the shorcode is AM360 (a membership plugin that links ActiveCampaign with Wordpress) - The AM360 developers have confirmed this is an issue from a recent Elementor update. Elementor have confirmed this themselves saying it was changed due to a security issue.

[mbr_db_email] [mbr_db_first_name] and [mbr_db_last_name] are the shortcodes from the plugin.

Can anyone give me advice on how to pass this data to the shoping cart.

Thanks to you all.
---
John

**Comment by plm2950** [comment]
Hi John, I am not sure about your situation but I had the problem with a
back button which I used on most pages of my site. For the life of me I
couldn’t get their work around to do the job for me, I have to say that I
was pretty pissed that they could stuff up a really simple function so
well, especially where they could have added the back function as a
selectable function of their own button widget.  So  I did find a work
around eventually but would rather not make it public for fear of them
doing the same again without offering a reasonable solution.  Let me know
how to pm you and I will let you know what I did, pretty sure it will work
for you.

**Comment by jacalakie** [comment]
Hi plm2950, thanks for getting back to me so quickly. If you are happy to email me please use:

github*at*elanmedia.co.uk

Best wishes
---
John

**Comment by BrockwayProd** [comment]
A simple would be that Elementor Team give us a filter to call that can reactivate this capability / desactivate this IMO useless security feature.

**Comment by wplaunchify** [comment]
My 2 Cents... while I appreciate the need for security, it would seem very easy to allow a conscious choice by the author to enable a javascript function in any url link widget, instead of forcing us to go 'back to code' within a wysiwyg page builder. I do write code and full plugins, but it just seems a bit like telling a Tesla owner that they need to bring a horse along to pull their electric car for this one reason...because of a concern for "security".

**Comment by BigBearLio** [comment]
Hi there!
Still no solution to have a "BACK button"?
I really need it to return from a search result to the previous page. I had it with a plugin [javascript:history.back()] but now I'm working on a website based only on Elementor/Pro.
Any solution?
Thanks

**Comment by plm2950** [comment]
Hi, If you add the "Happy Addons plugin" (free) then you will get a
"wrapper link". You can add your Javascript to that link and it should
work, at least it works for me!
I use [javascript:history.go(-1)] but should work fine with
[javascript:history.back()].
[image: image.png]
I have a button template, if you do the same then simply edit your button
in elementor and you will see the wrapper link option.
Good luck.

**Comment by lee2422** [comment]
Hi,
Can someone please help me with elementor and adding google ads onclick event?

This is the what I added to the footer of the page:

<script>
$ = jQuery;
$('#back-btn').on('click', function(e){
    e.preventDefault();
});
</script>

I need to add this :

onclick="return gtag_report_conversion('http://example.com/your-link')"

How do I need to add this to the solution described here?

Thanks.
Lior.

**Comment by BilDoc** [comment]
Greetings, everybody, and thank you for being there.  I was directed here from WordPress Elementor forum.  I even understand some of what you've said here.  I started my website believing it could be done with no knowledge of coding languages, which is exactly what I had, though I have learned a few words since.

May I have help in understanding how to add these code things

$ = jQuery;
$('.classname').on('click', function(e){
e.preventDefault();
window.history.back();
});
 
to the header/footer in Elementor?  I can't locate any code editor in it, and when I try to use the WordPress Editor code mode, it shows only the title of a blank page.  The documentations for the Elementor </>html element are so vague and assuming user knowledge I simply don't have, I don't know where to begin.

Other Not-Elementor pages on my site just use 'javascript:window.history.back();' for the link of an image, which I got from a WordPress forum and that's all the JavaScript I know.  But a certain page of my site will only be right if I can make a Back Button out of an Image Carousel, which is an Elementor Element, not a WordPress Block. 

I tried the Happy Addons plugin and assigned 'javascript:window.history.back();' and 'javascript:history.go(-1);' (from this very forum thread) to the Image Carousel and the Container in a matrix of all combinations, and all it does is send me to the Home Page, no matter which page I click in from, even with fresh-purged caches and even in an InPrivate window.  Elementor support says go to Happy Addon Plugin Support, Happy Addon says go to the WordPress forum, whatever.

The Events Tracker looked like mainly analytics, which I haven't set up and haven't yet studied, and I don't want to do that now.  I just want a simple back-to-last-page link, but on an Image Carousel this time instead of a single image.

I like to keep the plugins to a minimum, anyway, so the best option is to put this Classname-on-Click thing in the Header/Footer.  Can you please instruct me how?

I did have one other idea, which I don't even know enough about coding to even try out, but here it is:  Can I just put a link to a special Not-Elementor page that just automatically executes 'javascript:window.history.back();' or 'javascript:history.go(-1);' without showing the Visitors much more than a flicker?

Thanks.
