### ISSUE TITLE
Bug gallery with background

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#11470]
When there is the presence of a background, the colors of the pointer no longer display. See : https://youtu.be/oNOQ5CTEMsM

**Comment by lior-sh** [comment]
Hi @rodolphebertozzo,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by rodolphebertozzo** [comment]
The background for the filter bar selector does not appear if there is a section background. Did you watch my video? https://youtu.be/oNOQ5CTEMsM

**Comment by lior-sh** [comment]
Hi @rodolphebertozzo,

I watched the video but I couldn't reproduce the issue. I assume this issue is related to the Color Palette, did you check what is the ACCENT color there? 
Go to the hamburger icon > Click on 'Default Colors' and check the ACCENT color.
Try to set a color there and check if it's fixed your issue
Thanks.

**Comment by shilo-ey** [comment]
Hi @rodolphebertozzo 

This is a feature request. not a bug.

As for this you already created an issue, there's no need for multiple ones.

Currently, there's no option for selecting the background color of the filter bar. 

Thanks. let's keep this discussion here: #11463
