### ISSUE TITLE
⛔ 🐞 Bug Report: Nonbreaking space, <br> and <p> disappear in the editors

### ISSUE THREAD

**Issue by babasteve** [elementor/elementor#11560]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

- The publisher has always suppressed line breaks. When we create a line break in visual mode or in text mode, they are recognized first, then if we touch a little on everything before returning to the editor, they disappear.
- If we go to the editor in text mode and add a <br/>, it too is taken into account first, and when we save, they disappear.
- And it's worse for the breaking space! To begin with, if we add an unbreakable space in visual mode with the keyboard, it creates normal space. If we add a non-breaking space in text mode with the keyboard, it is first taken into account by the editor, then it becomes normal space after a few manipulations and recording.

Where it is serious is that for certain languages ​​like French in my case, there are a lot of non-breaking spaces: before the exclamation mark ( ! ), Before the question mark ( ? ), before the 2 points ( : ), around the quotes ( « » ), etc.

## Temporary solution

- To correct the problem of `<br/>` and line breaks, in the meantime, I am obliged to write all my texts in `<ul> <li>`, to which I add a specific class to hide the bullets, put a margin-top at 0px and a padding-left at 0px. Visually it gives the same impression as `<br>`.

- To give the impression of a line break `<p>`, I add a 15px margin-top in the `<li>`.

- To create non-breaking spaces, I add `&nbsp;` everywhere, again and again.

These are workarounds but it takes a lot of time to format the text, and it's tiring.

## Steps to reproduce

To reproduce this bug, simply use any Elementor editor:
- Add a long text (3 lines to see the bug) then: jump the line with "enter" on the keyboard, add `<br>` in the visual mode, and create a non-breaking space with the keyboard (in visual mode and in text mode).
- Then navigate in the style of the elements, select another element (for example a title).
- Return to the text editor, then add a single word in visual mode, and save.
- Select yet another item, then return to the text editor to add a word.

You will not notice that the non-breaking space has become a normal space if the created space is not at the end of the line, on the other hand you will notice that the texts have returned on a single line.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

- WordPress 5.4.1
- Elementor 2.9.11

Thank you for your time.

**Comment by zevrix** [comment]
still same issue with disappearing line breaks in Elementor 3.x

**Comment by zayter88** [comment]
Same issue Elementor free 26 March 2021

**Comment by dvjrickkraft** [comment]
+1 Having the same issues also with &emsp; &ensp; and <br> disappearing whenever I try to update a text section containing it.  I don't want to have to copy paste from Notepad++ every time and save every section there.  Can this be addressed please?

**Comment by zevrix** [comment]
check this video - i think it contains a solution for this annoying issue via some CSS trickery:
https://www.youtube.com/watch?v=q9ZOYRZ12M8

(that's as far as I recall. i didn't try this yet and will need to re-watch the video yet myself)

**Comment by DellaMoraWalter** [comment]
I have the same problem. The solution I've found is to use a text editor for each sentence or group of sentences. But that's not what I want. Since the text editor allows you to insert line breaks with Shift+return in my opinion this is a bug, and also quite relevant, given the frequency with which this component is used.

Is there any plans to fix this problem?

**Comment by jerry-ne** [comment]
@zevrix : your ytb advice is only for the end of paragraph. But this issue is also about non breaking space using in text.

**Comment by avatar1024** [comment]
Same issue, it makes it really tedious to edit text.

**Comment by Thebys** [comment]
Hello. 
I have this issue in Elementor/Pro 3.13.1. Specifically with " " (alt+0160 - &nbsp; - non-breaking space) turning into " " (regular breaking space) while using text editor widget. Sometimes this behavior produces typographically unacceptable results, such as leaving czech conjunctions (e. g. "u", "k", "o", "s", "v", "z", "a", "i", "se", …) at the end of lines. I do not have a solution, only a workaround not mentioned above in the thread that may or may not be better than "fighting" with the Text editor widget.

**Possible workaround using HTML widget**

- Prepare your text in the text editor widget
- Before addding non-breaking spaces, switch to the HTML tab, copy the content
- Replace the Text editor widget with HTML widget and paste the content
- Check the text and add all the non-breaking spaces, newlines and paragraphs you desire
- Now you have proper typography and nbsps are even conveniently marked in the html code with red dots
- (alt+0160 gets turned into &nbsp; in the resulting page)

**Comment by black-eye** [comment]
@Thebys 
> Sometimes this behavior produces typographically unacceptable results, such as leaving czech conjunctions (e. g. "u", "k", "o", "s", "v", "z", "a", "i", "se", …) at the end of lines.

It won't resolve the issues caused by Elementor, but concerning the non-breaking spaces and Czech conjuctions, you can try one of these plugins: https://wordpress.org/plugins/zalomeni/ (after a long time, recently updated) or https://cs.wordpress.org/plugins/cestina-zalomeni-radku/. Please note, that you won't see the effect in the editor, only on the frontend - the non-breaking spaces are added later in the process, so Elementor cannot mess them up.

**Comment by nicholaszein** [comment]
Hello everyone,

Thank you for reaching out and thank you for your patience! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is the expected behavior of the text widget which is essentially the TinyMCE text editor widget. In order for it to work as expected, including embeds and shortcodes, it does not include the `wpautop()` filter. This means that after you write something in the text editor it removes any paragraph `<p>`, and line-break `<br>` characters.

### ✅ What you can do to solve your issue:
If you need to maintain paragraphs and line breaks, you need to install the [Advanced Editor Tools](https://wordpress.org/plugins/tinymce-advanced/) (former TinyMCE Advanced) plugin and enable the option to `Keep paragraph tags in the Classic block and the Classic Editor`. This will prevent WordPress from sanitizing the content of the Text Editor widget.

For line breaks, you can however simply use the XML version of the line-break character `<br />`. This should work without needing any additional plugins.

### 👍 For now, that's all we can help with. 

Please understand that for the time being we have no plans to change this behavior both for backward compatibility as well as for maintaining the functionality of the Text Editor and compatibility with third-party plugins that add buttons to the text editor.

Kind regards
