### ISSUE TITLE
⛔ HTML field type duplicated from a required field causes validation errors on Form widget submission

### ISSUE THREAD

**Issue by vsimon51** [elementor/elementor#11607]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Header type field in Elementor form (single step).
If you copy another field *that is marked required* and change the type to HTML, the required status is *not removed*. This causes the form to be rejected with error message on submission because there is no field to be required in a Heading.
If you create a *new* field and make it a Heading, then all works properly.
This problem has appeared only in the last day or two after updating to WP 5.4.2 and the latest versions of Elementor 2.9.11 and Pro 2.10.0.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by nicholaszein** [comment]
Hello @vsimon51,

Thank you for reaching out, and apologies for the delay in answering you! 🙏

We are currently making some much necessary changes to our GitHub repository to better answer our users. I hope you can understand. 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
While testing a Form widget on the latest version of Elementor and Elementor Pro (3.25.9 and 3.25.4 respectively), we concluded this is no longer an issue. We were able to copy a required field and switch the field type to HTML without causing validation issues when the form is submitted. You can see our tests on the video below:

https://github.com/user-attachments/assets/8b7fc6ac-f1dc-40a4-81dc-04a97d531c0a



### ✅ What you can do to solve your issue:
Make sure you are running the latest versions of Elementor and Elementor Pro, and this issue won't happen anymore.

### 👍 For now, that's all we can help with. 

Kind regards
