### ISSUE TITLE
🔗 🔃 🚀 Feature Request: Lottie States (burger menu animation reversing on 2nd click). (Merged with #20444)

### ISSUE THREAD

**Issue by erylands** [elementor/elementor#11707]
It would be great to have more control over lottie states. 
I wanted to add a lottie animation in my nav bar to control my burger menu states. Essentially, onClick 1 - menu opens and animation completes. onClick 2, menu closes and lottie burger menu animation reverses. 

## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by drawcard** [comment]
You may need to do this with some custom coding:

https://github.com/airbnb/lottie-web/issues/1315

**Comment by minty-owen** [comment]
I have made an hamburger icon and I found out that there's no option for that... It sucks, now I cannot use my hamburger icon.

**Comment by Panksi** [comment]
> You may need to do this with some custom coding:
> 
> [airbnb/lottie-web#1315](https://github.com/airbnb/lottie-web/issues/1315)
> https://wordpress.org/support/topic/reverse-animations-on-second-tap/#post-12734538 (for another plugin but the method may work too)

hey @drawcard Do you maybe know how can I call instance of lottie animation? 
the thing is, our usage of lottie is much more extended than the possiblities of lottie widget, but we would really like to use the elementor to put the lottie animations on our website.
So the question basically is:

normally the instance is saved in varable
as var lottieSomething = lottie.loadAnimation ();

but I see that there is some kind of factory that generates the instances.
I am trying to figure this out but no luck....

**Comment by drawcard** [comment]
Hi @Panksi, my knowledge is limited on this, but perhaps if you can let me know what your use case is I can try to help. The Pro Lottie widget will only do what the code for it allows, so modifying that to change how it calls instances is risky, since the changes would be wiped out in a plugin update.

So if you want to do something custom, eg playback control or use event listeners, you might have to create a JS block on your page somewhere (using the HTML widget) and call your Lottie instance in that manually.

You might find this guide useful: https://css-tricks.com/animating-with-lottie/

**Comment by Panksi** [comment]
Use case:
all of my animations have intro sequence and then loop sequence
lets say from 1 to 40 is intro and from 41 to 80 is loop.
It would be great only to know what is the actual name of the instance so I
can set sequences
like so:
animation.playSegments([[0, 40],[41,80]]);

this is actually something that I already have in my JS files since I
realized there is no way to do this with elementor.
BUT if I would have instance name displayed somewhere somehow then I could
just call the instance and set it to play segments.
There is no problem when you have only a few animations on your page to
manually make instances but when you have 10+ on one page that is a pain in
the a$$.
Nevermind I already decided to drop this Idea...

**Comment by nicholaszein** [comment]
Hello!

Thank you for your submission! 🙏 

### 🔃  This request is being merged with #20444.

Which is on the same subject. 

For this reason, I'm closing the comments, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Best regards,

Nick
