### ISSUE TITLE
Closed Issue #2806 is not resolved. Animation .elementor-invisible is creeping in on it's own

### ISSUE THREAD

**Issue by denisbetsi** [elementor/elementor#11720]
#2806 

Opening up new issue as all the comments and complaints going into that issue aren't being addressed.

**Comment by erosenin** [comment]
I updated my server php version to 7.2 from 5.6.4 and after that I had the same issue as everyon else here.
Even with all plugins disabled it is not working correctly.
If I do the set animation to default the image carousel, sliders, h1s etc are not displaying correctly.

Please help!! :)

**Comment by Morgunov-Vitaly** [comment]
The same issue - sometimes the widgets in  the footer sections with animation get .elementor-invisible class and dissapear.
I use Jet plugins.

**Comment by mahofficial** [comment]
The issue is still not fixed. I am still having this issue with the latest version. I got this issue after using the latest version of new experiments. Before that everything was working fine.

**Comment by Khubaib27** [comment]
.elementor-invisible {
	visibility: visible!important;
}
I used this in custom css and it start working fine. Is this a right approach?

**Comment by mahofficial** [comment]
> .elementor-invisible {
> visibility: visible!important;
> }
> I used this in custom css and it start working fine. Is this a right approach?

I don't think that it is the right approach and also on my side it was a problem with elementor rendering SVG image after the update.

On my end, the SVG icon with the style attribute wasn't rendered correctly. Seems like the style attributes got sanitized causing every section to be in it and stopping animation from occurring. What I did is used presentation attributes instead of style attributes in my SVG icon and it fixed the issue.

Seems like the latest update of elementor got an issue with SVG icon rendering.

**Comment by Khubaib27** [comment]
> it was a problem with elementor rendering SVG image

How do you came to know this?

**Comment by mahofficial** [comment]
> > it was a problem with elementor rendering SVG image
> 
> How do you came to know this?

I removed animations from my site and then checked but the issue remained. So, I went through inspect element again and founded that all of my sections are under SVG style tag.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
