### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor mini-cart menu brokes styling 

### ISSUE THREAD

**Issue by DiegoMaK** [elementor/elementor#11752]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

Test flow:
1.Install & Activate a theme that has it’s own mini-cart template. (in MY CASE Astra).
I use the last menu item"woocommerce" in header of astra.

2.Make sure WooCommerce is installed, activated, and your shop is set up with products
3. Create a new header and drag in a Menu Cart widget and design it --> The same header of astra.
Set your header to Entire Site condition

4. Go to frontend, navigate to your Shop page and add a product to cart

5.Click on the Menu Cart button and see your mini-cart drawer design
Until this moment everything is working well, the dropdown menu, or the hover menu works perfectly,  when I'm on home page, if I pass the mouse over the mini-cart the information, and products in the cart are showed without issues.

6. Now in this step, I  try to explore not the astra mini-cart, if not the elementor minicar.
Just to test, I add in the home page the elementor mini-cart.   and preview the page.

Just with that action, everything is broken in styling in my normal mini-cart-menu.
I don't even need to save the elementor edition, just with drag and drop the elementor menu item all is broken.  

Colors are changed, my personalization design on buttons disappear, all shapes,fonts, colors, etc. In addition the principal issue is that all text is totally broken, all lines written in only one line.

7. I read a lot and try to fix the issue , but nothing works.

8. I execute this:
Go to your Dashboard > Elementor > Settings > Integrations tab > WooCommerce section and choose “Disable”
I clear cache, on server and my browser, I also disable cache and put site on developer mode, but the problem still occurs.

After I disable the elementor settings, I recover my original colors and buttons configuration, but the text is still broken.
Check the image, to see how the text is still broken.
 ![image](https://user-images.githubusercontent.com/55402447/85971528-fed5a700-b992-11ea-8e5a-750fa3a44190.png)

I also try to regenerate all css on elementor tools

**THE ONLY SOLUTION IS TO RESTORE MY SYSTEM, TO THE POINT BEFORE DRAG AND DROP ELEMENTOR MINI_CART to home page.**

## Isolating the problem

- [ X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | LiteSpeed |  
MySQL version: | MySQL Community Server (GPL) v5.7.30 |  
PHP Version: | 7.4.7 |  
PHP Max Input Vars: | 5000 |  
PHP Max Post Size: | 64M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

WordPress Environment |   |  
-- | -- | --
Version: | 5.4.2

</details>

**Comment by nicholaszein** [comment]
Hello @DiegoMaK,

Thank you for reaching out, and thank you for your patience! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* Elementor implements its own styles and template for the menu cart. You need to either edit the cart with Elementor or with your theme. You can't style in one place and expect it works for the other.
* Disabling the option in the WordPress Dashboard > Elementor > Settings > Integrations > WooCommerce to use the Elementor template for the Menu Cart, requires you to also remove the Menu Cart widget and use your theme's menu cart, otherwise the styles won't be applied correctly.


I'm marking this issue as not a bug.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
