### ISSUE TITLE
Add Font Awesome Pro SVG support

### ISSUE THREAD

**Issue by Pab89** [elementor/elementor#11772]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently, elementor only supports the Web Fonts options I Font awesome 5 Kits. Per https://docs.elementor.com/article/585-icon-library . Please add support for the SVG options, it's more flexible and gives smaller file sizes, which will increase pagespeed.

**Describe the solution you'd like**
Make elementor compatible with Font Awesome 5 Pro SVG kit's instead of only Web Fonts.

**Comment by Pab89** [comment]
I did some more research, going from using web fonts to SVG saves 54 KB, which is a lot. The main problem is that the widgets use "fill" as the CSS attribute to change color if that switches to "color" instead, everything works. Currently, I have switched to SVG to save the 54 kilobytes, and manually write the CSS to change the color of all the icons I use, but that's a big hassle. I don't think it would be a big change to give the option to use "color" instead of "fill" for icons, which would solve the problem.

**Comment by jazir5** [comment]
As in my thread, could you automatically replace all icons with individual svgs instead of loading the whole font library? Lots of unnecessary icons downloaded if you download the whole font file. Only icons that are used should be loaded

**Comment by DorShahar** [comment]
Hi 
We are about to release a new experiment that will convert Font Awesome icons to be used with SVG.
With that being said, if you are using FA Pro you can convert icons to be used as SVG by yourself:
In FA - go to Kit settings, and under Technology, change to SVG instead of Web Font: 
![image](https://user-images.githubusercontent.com/19154938/126057880-57016696-762d-4172-9457-8e0ddd6f584c.png)

The experiment will not convert FA Pro to be used as SVG, it will stay as Web Font **only** for the Pro icons. 

Thanks

**Comment by jazir5** [comment]
@DorShahar 

When are you releasing it?

**Comment by DorShahar** [comment]
In the next Core version (v3.4.0)

**Comment by Yahav** [comment]
@DorShahar ETA on this available yet? still having issues when using FA-Pro SVG icons, the icon color are changed to the global link color site-wide..
