### ISSUE TITLE
Technical questions

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#12402]
Why did you introduce the new theme builder in Elementor core and the screen capture mechanism in Elementor Pro? Is it related to good performance management?
I also wanted to know if it would ever be possible to access the private repository in Elementor Pro and possibly make some contributions?

**Comment by shilo-ey** [comment]
Hi @rodolphebertozzo 

First of all, thanks for your helpful contributions. we truly appreciate it.

As for your questions:
1. The new Theme Builder framework introduced in the Core version because we have plans for using this mechanism in other places.
2. The Screenshots mechanism currently in the Pro version because it's relevant to the Pro version for now. if needed, we will migrate it to the Core version in the future.
3. Elementor Pro, just like Elementor is an open source plugin. To keep being competitive our Elementor Pro repo is a private one.
We would be happy to get some code contributions in a separate issue with code diffs. 

Thanks again.
