### ISSUE TITLE
Fatal error: Uncaught Error after Update Elementor Pro v3.0.3

### ISSUE THREAD

**Issue by ghccristia** [elementor/elementor#12420]
WordPress v5.5.1

Fatal error: Uncaught Error: Class 'ElementsKit\Modules\Controls\Controls_Manager' not found in /var/www/vhosts/prosenor.es/beta.prosenor.es/wp-content/themes/blo/components/editor/elementor/widgets/blo-case-study.php:38 Stack trace: #0 /var/www/vhosts/prosenor.es/beta.prosenor.es/wp-content/plugins/elementor/includes/base/controls-stack.php(1929): Elementor\Blo_Case_Study_Widget->_register_controls() #1 /var/www/vhosts/prosenor.es/beta.prosenor.es/wp-content/plugins/elementor/includes/base/controls-stack.php(488): Elementor\Controls_Stack->init_controls() #2 /var/www/vhosts/prosenor.es/beta.prosenor.es/wp-content/plugins/elementor/includes/base/widget-base.php(148): Elementor\Controls_Stack->get_stack() #3 /var/www/vhosts/prosenor.es/beta.prosenor.es/wp-content/plugins/elementor/includes/base/controls-stack.php(294): Elementor\Widget_Base->get_stack() #4 /var/www/vhosts/prosenor.es/beta.prosenor.es/wp-content/plugins/elementor/core/files/css/global-css.php(120): Elementor\Controls_Stack->get_controls() #5 /var/www/vhosts in /var/www/vhosts/prosenor.es/beta.prosenor.es/wp-content/themes/blo/components/editor/elementor/widgets/blo-case-study.php on line 38

LINE 38
 'type' => ElementsKit_Controls_Manager::IMAGECHOOSE,

Help !!!!!

**Comment by shilo-ey** [comment]
Hi @ghccristia 

According to your stack trace it seems like your Theme, Blo theme, `themes/blo/components/editor/elementor/widgets/blo-case-study.php` is not compatible with Elementor.

Please try to verify it by switching to Hello theme or any other basic theme and check if this issue occurs.

If this issue is related to your theme- please contact their support for help

Thanks.
