### ISSUE TITLE
Feature Reuquest - Add inherited field values as placeholders in tablet/mobile mode

### ISSUE THREAD

**Issue by davidmondok** [elementor/elementor#12608]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When in mobile or tablet mode in the editor it's unclear which values are inherited for specific settings like paddings, margins and many others when those same fields are empty. When working in those modes this information would be quite helpful because decisions often depend on those values.

**Describe the solution you'd like**
If for example I add 100px custom margin to an element in desktop mode and switch over to tablet or mobile mode it would be great to have the inherited value of 100px as a placeholder inside the four input fields that define the margins. This would be especially helpful for mobile where values can be inherited by desktop as well as tablet, depending if the latter is set.

**Comment by euene** [comment]
+1

That's a great suggestion for UX, to always know the inherited values between the different breakpoints, instead of having to constantly switch back-and-forth between breakpoints in order to double-check what's inherited.

To add something similar that I've been thinking about for awhile - it's not clear enough that Elementor has some "hidden" default values for some elements - for example, a brand new column will always have a 5px padding even though the default padding values are blank - and the only way to remove the default is to set the value of padding to "0".

Please add these default Elementor values as placeholders as well, so that it's clear that a column has 5px padding by default, as it might be confusing for somebody who wants no padding on a column, to realise that they have to explicitly set it to "0" in order to remove it completely.

**Comment by MichaelDarko** [comment]
+1

I agree, something should be done about this. Right now, the workflow involves CONSTANT switching between breakpoints to check the values.

I'm pretty sure the whole thing is probably complicated, but there must be a way to make this better.

**Comment by black-eye** [comment]
+1
Yes, another long time issue:
- https://github.com/elementor/elementor/issues/3356 (since 01/2018)
- https://github.com/elementor/elementor/issues/7575 (03/2019)

And another related margin/padding UX improvement suggestions:
- https://github.com/elementor/elementor/issues/2219 (since 08/2017)
- https://github.com/elementor/elementor/issues/3319  (since 01/2018)

Hopefully this time it gets more attention.

**Comment by marcocarrozzini** [comment]
+1

**Comment by imsyedabdullah** [comment]
+1

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3356, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
