### ISSUE TITLE
Section fixed background attachment working on tablet and mobile

### ISSUE THREAD

**Issue by feidaman** [elementor/elementor#12656]
Like the title says. Fixed background attachment works fine on desktop, doesn't on pad and mobile. The following CSS at the section level fixes the issue:

`selector {
    background-attachment: fixed;
} 
`

**Comment by arielk** [comment]
This feature does not work well on mobile devices, which is why we added the following note:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/1778512/94238833-9490bc00-ff19-11ea-9852-2de5b3ecffff.png">

Thanks for your feedback!

**Comment by feidaman** [comment]
Thanks for replying, Arielk. I must admit I hadn't noticed the note when I selected "Fixed", but now it's clear this is a known issue. However, I'm a confused: if I was able to fix the problem with one line of CSS code, can't Elementor do something like that to achieve the expected result? From my perspective as a user this is a UX bug, since the setting promises the background image will be fixed but fails to deliver on that promise. Is this something you guys plan to improve in the future? Thanks

**Comment by arielk** [comment]
Please check your solution on real mobile devices (iPhone/iPad/etc) and let me know if it works for you

**Comment by RonR-WebDesign** [comment]
Confirmed problem on mobile (iPhone).

**Comment by checkall** [comment]
> Like the title says. Fixed background attachment works fine on desktop, doesn't on pad and mobile. The following CSS at the section level fixes the issue:
> 
> `selector { background-attachment: fixed; } `

Thanks this really saved my day, used in a wordpress website with elementor.

**Comment by Maxthesmall** [comment]
On wix.com for example it is not a problem

**Comment by rezaamya** [comment]
Can I help to solve this problem?

**Comment by RudiHIbk01** [comment]
@arielk thank you fot the solution above. The code works with android powered devices. On all mobile i-devices it does not work at all, we have tried on 5 divices newer and older and on at least 5 browesers, neither tablet nor are phone working. 
You gus have a solution for that in the pipline? I mean we pay for the pro version and there is no security that what elementor shows you in the responsive "mobile" mode will actually be the representation seen on the devices. Quite bozering if you relay on it for business perpouses. 

And just to get an Idea, do you use ratios to adjust the representation (zoom) of the pictures, instead of predefined screen sizes? (Sorry if the queistion seemed stupid, I am just starting with CSS.)

Thank you in advance and dispite all quite the achievment that elementor. :)

**Comment by canyon1991** [comment]
For anyone looking for a solution for this issue with `background-attachment: fixed;` on tablets (mainly iPadOS) in landscape mode - please see my workaround https://github.com/elementor/elementor/issues/10951#issuecomment-1820007878 .
