### ISSUE TITLE
wp_enqueue_style in the render method just works in the page view and does not work in the Elementor editor mode (Screenshot Included)

### ISSUE THREAD

**Issue by liberl** [elementor/elementor#12667]
## Description
I have some wp_enqueue_style in the render method of my custom Elementor widgets after updating to Elementor 3 they don't render in Elementor editor mode but it works in the page view.

Widget View in editor mode
![image](https://user-images.githubusercontent.com/35874489/94341336-62fd1b00-0015-11eb-9683-108c019fcdb9.png)

Widget View in page (This is the correct style)
![image](https://user-images.githubusercontent.com/35874489/94341355-8627ca80-0015-11eb-93f9-ce8bd34cd65d.png)

Code example (It was working for a long time before updating to version 3)
![image](https://user-images.githubusercontent.com/35874489/94341402-e0289000-0015-11eb-90d4-0ab765dffe8d.png)

**Comment by udidol** [comment]
Hi @liberl ,
It is bad practice to call `wp_enqueue_style` in the `render()` method. 
I am surprised you said it even used to work at all before, I would imagine that wouldn't work at all.

The `render()` method is called just once in the Front End (what you called "Page View"), but it may be called multiple times in the Elementor Editor, whenever the widget is re-rendered. Having `wp_enqueue_style()` be called after the page is loaded, multiple times, will not do anything, since WordPress only enqueues styles (with the `wp_print_styles` hook) once on the page load.

Any loading of CSS for your widget should be run only once and early in the loading sequence, not in the `render()` method.

Elementor's best practice for loading CSS for your widget is registering the style somewhere in your plugin file before registering the widget (you can use the `elementor/frontend/before_register_styles` or `elementor/frontend/after_register_styles` actions for example), then inside your widget class, return the style handle from elementor's `get_style_depends()` method. If your plugin is a PHP class, you can implement it similarly to the following example:

1. Inside your plugin class, add the `before_register_styles` action to the class constructor (as demonstrated below), and the 'register_widget_styles' function as a method to the class:
```
public function __construct() {
    add_action( 'elementor/frontend/before_register_styles', [ $this, 'register_widget_styles' ] );
}

public function register_widget_styles() {
    // replace the handle name, file path and version number to match your plugin obviously
    wp_register_style( 'my-style-handle', 'css-file-path/style.css', [], '1.0.0' ) 
}
```

2. Inside your widget class, include the following method:
```
public function get_style_depends() {
    return [ 'elementor-gallery' ];
}
```

From what I gather of your code example, you want to load different CSS for different user-selected modes. I would suggest including all of this CSS in one file, and using class names to handle the different displays per user selection.
