### ISSUE TITLE
Site Settings > Background > Attachment > Fixed - Doesn't work on Tablet or Mobile

### ISSUE THREAD

**Issue by RonR-WebDesign** [elementor/elementor#12665]
[x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
[x ] The issue still exists against the latest stable version of Elementor.

Site Settings > Background > Attachment > Fixed Doesn't work on Tablet or Mobile

Using latest versions core and pro and with the Hello theme.  I've reproduced on other installations.

Fixed it by adding to Site Settings > Custom CSS:

body { 
    background-attachment: fixed;
}

**Comment by arielk** [comment]
This feature does not work well on mobile devices, which is why we added the following note:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/1778512/94238833-9490bc00-ff19-11ea-9852-2de5b3ecffff.png">

Please read more here: https://github.com/elementor/elementor/issues/12656

Thanks for your feedback!
