### ISSUE TITLE
feature request: please add gradient color options to global colors

### ISSUE THREAD

**Issue by joehdevwp** [elementor/elementor#12708]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

3.0 global colors are great but there's no option to set gradients

**Describe the solution you'd like**

Ability to use gradients when defining global colors in theme builder

Little bit surprised this wasnt thought of already.

**Comment by MichaelDarko** [comment]
+1 Absolutely needed.

Using consistent gradients thorough your website without global option means constantly setting every single value of the gradient by hand - terrible workflow. 

Global colors and fonts sped up my workflow by a lot. It's great, but it doesent feel complete because there is so much more we should be able to set a globally. Hopefully, gradients and other things will be added.

Global box shadows and text shadows should also be added.

**Comment by oliveandlake** [comment]
+1

**Comment by udidol** [comment]
Hi @joehdevwp,

Gradients are currently supported only in specific elements, such as sections and columns (as background), as well as page backgrounds. 
They are created using two separate color controls. 
You can use global colors in these gradients. 
Is that not what you are looking for?

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #8202, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by arielk** [comment]
I'm closing an issue due to Global colors are currently supported on gradient background. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!

**Comment by tiger440** [comment]
Hi @arielk,

I think that the issue actually needs to be reopened, I explain:

I suppose that @joehdevwp was talking about defining all the option of the gradient in the global color:
- First Color
- Location
- Second color
- Location Type
- Angle

Currently, when we set the background, we can define the first and second color as global colors and use them in the gradient options but still need to define values for the other options.

Why would it be useful to define a gradient as a global color ( or even add the option to define a "global gradient" if it fit better in Elementor current behaviors) ?

We could actually use the full potential of the "site settings" in our website building workflow since the goal is to use these settings as much as possible and almost never touche the options of an element.

Currently, when i want to define a gradient, i just create it in the custom css as a class and i put this class on each element where I want the background to be since it's faster than putting the global colors and re-enter the values of the location/location-type/angle (i still use the the "global colors" sass values to optimize it).
I don't think that it's the best way to work with elementor since the "sites settings" are made to replace these kind of task.

AND MOSTLY (for myself so maybe for other, tell me)

If i can define a gradient with all the options as a "global color", i could use it on fonts settings, and for a lot of design i work with currently, a lot of titles use gradients as colors.

Feel free to tell me if it relate to the current issue or if i should open a new one to suggest this feature.

Thank you

**Comment by codewizard13** [comment]
+1 This is definitely still needed and not available for all elements. For instance, I want to have a button with a complex **multi-stop** gradient to make a shiny gold effect, but I cannot do it easily on Buttons. The best I can do is build it in a text editor widget, but that doesn't have any easy way to add a link.

This is what I mean by a complex gradient:

    background:linear-gradient(to right, #BF953F, #FCF6BA, #B38728, #FBF5B7, #AA771C);

**Comment by wren-valles** [comment]
+1!
