### ISSUE TITLE
🔗 🚀 Feature Request: Registration Form widget (Duplicate of #2775, #5184)

### ISSUE THREAD

**Issue by FIJOR** [elementor/elementor#12821]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Setup a registration form for users.

**Describe the solution you'd like**
A registration form just like there is already a login form.

**Describe alternatives you've considered**
There are other addons but I don't want to install them, this should be a EPro core feature.

**Additional context**

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #5184, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #2775 and #5184 , which is on the same subject. For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
