### ISSUE TITLE
Astra & Elementor Conflict - Disappearing Menu's

### ISSUE THREAD

**Issue by asconley** [elementor/elementor#12834]
This may be a problem with other theme platforms using Elementor, but this is specific to Astra

When using Elementor > Templates > Creating a Footer
When using Astra Pro Headers

**Problem**
The entire header menu will disappear with no errors or warnings. Some people would think it would be a plugin conflict, CSS issue or wrong layout, but it is something between these two platforms

I was able to bring back the menu after disabling the Elementor footer by removing the rule to display it across the entire site.

**Workaround:**
Save the elementor footer template as a newly saved template

I decided to use Astra's Custom Layouts, Similar to Elementors templates, and just copy the saved template in there footer template system.

**Comment by arielk** [comment]
Thanks for reporting,

I'm trying to figure out exactly where the problem is, If you deactivate this plugin Elementor works well for you?

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.

Without it we simply can't help.

Thanks
