### ISSUE TITLE
Accordion scrolling with whole page - jQuery issue

### ISSUE THREAD

**Issue by david-strejc** [elementor/elementor#12873]
https://github.com/jquery/jquery/issues/3812

Issue discribed above is occuring in Elementor Accordion.

Solution is simple as:

`	
.elementor-accordion-item {
overflow-anchor: none;
}`

**Comment by Aviad-Herman** [comment]
Hi David,
The issue you raised is caused by the fact that WordPress uses an older branch of jQuery. They do have plans to upgrade it to a modern version in the future. Meanwhile you can try to update the jQuery version independently using plugins like the following: https://wordpress.org/plugins/wp-jquery-update-test/

Best,
