### ISSUE TITLE
⛔ Image Carousel does not autoplay or show pagination on a multisite for the administrator role

### ISSUE THREAD

**Issue by yoneth** [elementor/elementor#13029]
Step  to reproduce:

1. Login using Administrator role
2. Drag Image Carousel element onto canvas
3. Add few images
4. Under Style tab, change the image spacing to 'Custom' and enter 40px in the value box

The carousel worked fine in the editor. When you check in the frontend, auto slide and dot pagination stopped working.
But if you logged in using Super administrator role and repeat the steps above, the auto slide and dot pagination worked just fine.

Thanks

**Comment by nicholaszein** [comment]
Hi @yoneth!

Thank you for submitting your issue, and apologies for the delay in the response. 🙏 

As we work to organize GitHub issues, we have been revisiting old issues to check if they are still valid, and after testing the Image Carousel in a Multisite with both the **`administrator`** and **`super administrator`** roles, we found no problems in the functionality of the widget. This lead us to conclude that either your problem was local, related to site settings or cache, or since you've posted it, it has been addressed already.

Therefore I'm closing this issue as not a bug.

Again, thank you for contributing and for being so patient! 🙏 

If you think this is till an issue using the latest version of Elementor, please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Kind regards
