### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor Dev version does not update if using WP-CLI

### ISSUE THREAD

**Issue by Kaochkidu** [elementor/elementor#13090]
Hello, 

When we want to update the Elementor plugin we get this error:
```
PHP Fatal error:  Uncaught UnexpectedValueException: Invalid version string "3.1.0-dev1" in phar:///usr/local/bin/wp/vendor/composer/semver/src/VersionParser.php:172
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/composer/semver/src/Semver.php(39): Composer\Semver\VersionParser->normalize('3.1.0-dev1')
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(785): Composer\Semver\Semver::satisfies('3.1.0-dev1', '2.9.x')
#2 phar:///usr/local/bin/wp/vendor/wp-cli/extension-command/src/WP_CLI/CommandWithUpgrade.php(583): WP_CLI\Utils\get_named_sem_ver('3.1.0-dev1', '2.9.14')
#3 phar:///usr/local/bin/wp/vendor/wp-cli/extension-command/src/WP_CLI/CommandWithUpgrade.php(342): WP_CLI\CommandWithUpgrade->get_minor_or_patch_updates(Array, 'minor')
#4 phar:///usr/local/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php(640): WP_CLI\CommandWithUpgrade->update_many(Array, Array)
#5 [internal function]: Plugin_Command->update(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFacto in phar:///usr/local/bin/wp/vendor/composer/semver/src/VersionParser.php on line 172
Fatal error: Uncaught UnexpectedValueException: Invalid version string "3.1.0-dev1" in phar:///usr/local/bin/wp/vendor/composer/semver/src/VersionParser.php:172
```

This error is reproducible with the CLI of wordpress by doing the following command:
```
wp plugin update elementor --minor --dry-run
```

Additional information:
* Wordpress version :
```
WordPress version: 5.3.6
Database revision: 45805
TinyMCE version:   4.960 (4960-20190918)
Package language:  fr_FR
```
* Wodpress CLI version:
```
WP-CLI 2.4.0
```
Elementor version : 2.9.14 

Could you solve this problem or propose a solution quickly please?

Kind regards

**Comment by shilo-ey** [comment]
Hey @Kaochkidu 

Are you subscribed as a beta tester?
Please share your System Info.

**Comment by Kaochkidu** [comment]
Hey @shilo-ey 

Thank you for your response. I am not registered as a beta tester, however I might be interested in your proposal.
We use the Elementor plugin with [a docker image of Wordpress](https://github.com/fjudith/docker-wordpress).

Kinds reagrds

**Comment by shilo-ey** [comment]
Thanks,

You can always add yourself as a beta tester - [explanation here](https://elementor.com/help/tools/).
As for your issue - can you please share where is the composer in your docker image? can you please share it? 

Thanks

**Comment by Kaochkidu** [comment]
Hey @shilo-ey 

Sorry I gave you the wrong link, here is the image we use: [the Monogramm docker image of Wordpress](https://github.com/Monogramm/docker-wordpress)

Kinds regards,

**Comment by madmath03** [comment]
@shilo-ey what's the link between this issue and the beta tester mode?  especially if it's not enabled

**Comment by Kaochkidu** [comment]
Hey @shilo-ey , The issue still exists and impacts our production. 
Have you made any progress in solving it ?

Kinds regards

**Comment by ypcs** [comment]
This seems to be related to the fact, that WordPress.org Plugin API, which is accessed in WP-CLI `wp plugin update` command in function `WP_CLI\CommandWithUpgrade->get_minor_or_patch_updates()`

https://github.com/wp-cli/extension-command/blob/a877c5e08c24e86db306da7c5fcde6a737cb9d29/src/WP_CLI/CommandWithUpgrade.php#L588-L641

using `WpOrgApi::get_plugin_info()` as data source, defined in https://github.com/wp-cli/wp-cli/blob/f8207adcb7f800a91ba380e4411611f36373f143/php/WP_CLI/WpOrgApi.php#L203-L231

returns list of all downloadable versions of Elementor. This information is fetched from https://api.wordpress.org/plugins/info/1.0/elementor.json , which contains a list of versions, currently eg.

```shell
$ curl --silent https://api.wordpress.org/plugins/info/1.0/elementor.json |jq .versions |grep \"3.7
  "3.7.0": "https://downloads.wordpress.org/plugin/elementor.3.7.0.zip",
  "3.7.0-beta1": "https://downloads.wordpress.org/plugin/elementor.3.7.0-beta1.zip",
  "3.7.0-beta2": "https://downloads.wordpress.org/plugin/elementor.3.7.0-beta2.zip",
  "3.7.0-beta3": "https://downloads.wordpress.org/plugin/elementor.3.7.0-beta3.zip",
  "3.7.0-beta4": "https://downloads.wordpress.org/plugin/elementor.3.7.0-beta4.zip",
  "3.7.0-dev1": "https://downloads.wordpress.org/plugin/elementor.3.7.0-dev1.zip",
  "3.7.0-dev10": "https://downloads.wordpress.org/plugin/elementor.3.7.0-dev10.zip",
  "3.7.0-dev2": "https://downloads.wordpress.org/plugin/elementor.3.7.0-dev2.zip",
  "3.7.0-dev3": "https://downloads.wordpress.org/plugin/elementor.3.7.0-dev3.zip",
  "3.7.0-dev4": "https://downloads.wordpress.org/plugin/elementor.3.7.0-dev4.zip",
  "3.7.0-dev5": "https://downloads.wordpress.org/plugin/elementor.3.7.0-dev5.zip",
  "3.7.0-dev6": "https://downloads.wordpress.org/plugin/elementor.3.7.0-dev6.zip",
  "3.7.0-dev7": "https://downloads.wordpress.org/plugin/elementor.3.7.0-dev7.zip",
  "3.7.0-dev8": "https://downloads.wordpress.org/plugin/elementor.3.7.0-dev8.zip",
  "3.7.0-dev9": "https://downloads.wordpress.org/plugin/elementor.3.7.0-dev9.zip",
  "3.7.1": "https://downloads.wordpress.org/plugin/elementor.3.7.1.zip",
  "3.7.2": "https://downloads.wordpress.org/plugin/elementor.3.7.2.zip",
  "3.7.3": "https://downloads.wordpress.org/plugin/elementor.3.7.3.zip",
  "3.7.4": "https://downloads.wordpress.org/plugin/elementor.3.7.4.zip",
```
This data originates from WordPress.org Plugin SVN http://plugins.svn.wordpress.org/elementor/tags .

Thus, when WP-CLI tries to find a patch version to update, executes comparison against each of these versions. In OP the version was `3.1.0-dev1`, I've seen issues with eg. `3.7.0-dev1` and with many earlier similar versions.

I wasn't able to find any "rules" for using WordPress plugin SVN (ie. how eg. development versions should be named). Thus, I'd say that this is a bug in WP-CLI handling of versions instead of in how Elementor uses SVN and does versioning. (Feel free to prove me wrong, I didn't look that much for WordPress.org docs.)

The breakage occurs in `get_named_sem_ver()`, defined in https://github.com/wp-cli/wp-cli/blob/f8207adcb7f800a91ba380e4411611f36373f143/php/utils.php#L898-L932

It seems that this function already handles a case where the original version contains a dash (`-`), but doesn't do the same for the new version. Thus, invalid data is passed to SemVer library, which then dies. `satisfies()` is defined here https://github.com/composer/semver/blob/3953f23262f2bff1919fc82183ad9acb13ff62c9/src/Semver.php#L24-L43 , and this calls `VersionParser::normalize()`, from same library:

https://github.com/composer/semver/blob/3953f23262f2bff1919fc82183ad9acb13ff62c9/src/VersionParser.php#L93-L177

Normalize handles quite a lot different formats of a version number.

So, IMHO there are at least three different options:

 - a) patch WP-CLI to handle new version numbers like it does with the original version in `get_named_sem_ver()`
 - b) patch SemVer library to handle versions like `3.7.0-dev1` (I didn't read the logic, if it should do it already)
 - c) drop those -dev versions from WordPress Plugin SVN

**Comment by ypcs** [comment]
Related WP-CLI issue: https://github.com/wp-cli/extension-command/issues/274

**Comment by nicholaszein** [comment]
Hello there, 

As @ypcs correctly pointed out, this is a limitation with the WP-CLI, which Elementor does not intend to modify/adapt in any way to avoid incompatibility issues.

We are reconsidering how we distribute beta and developer versions of our plugin, and we might change this in the near future.

As such, this issue became incompatible with our future plans.

We will announce changes to our release cycle in the near future. Please keep an eye on our Developers Blog:

https://developers.elementor.com/blog/

Kind regards
