### ISSUE TITLE
FR: Lottie File OR an image within the Image Box widget

### ISSUE THREAD

**Issue by zachkinsey** [elementor/elementor#13192]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Currently you can only create 'fake' image boxes with Lottie files by putting them into seperate columns. When you do this, one is forced to used Margins for 'widget' seperation and the responsiveness isn't that great incomparison to a set of proper image box widgets residing in 1 column that uses flex horizontal align for spacing, responsiveness, and container wrapping.

By adding the ability to add a Lottie file in place of an image within an image box widget, you get rid of the above issues.

**Describe the solution you'd like**
Ability to set a Lottie File OR an image within the Image Box widget.

**Comment by shilo-ey** [comment]
Hi @zachkinsey 

Thanks for your suggestion.

When we added the Lottie widget, we had this request in mind, so instead of bloating the current widgets with a lot of controls, we allowed users to trigger the animations based on interaction in the column, and not just on the widget itself.

Therefore currently, we won't add this as an option, but we are working on a way for you to create better complex widgets
