### ISSUE TITLE
WooCommerce Pages Styling Options 

### ISSUE THREAD

**Issue by jaysonwebtel** [elementor/elementor#13218]
Please make the WooCommerce pages individual widgets and add styling options for them, especially the cart tables & checkout pages.

eg. 
Button Colours
Remove or change colour of table borders

Full customisation of these pages would be ideal too but even if we can just style existing items when using Hello Elementor theme to avoid the ugly WooCommerce defaults that would help.

**Comment by fuzenco** [comment]
Yes, this is just plain awful. I know the root lies with WooCommerce but this would be the main reason I ditch Webflow and Shopify. As a new WordPress and Elementor “developer,” this is my main gripe.

**Comment by marfilag** [comment]
I have bought an extra plugin for this and is giving me serious problems. If Elementor had this simple and necessary option it would be a success.

I lost the money from that plugin due to its incompatibility with other Woocommerce plugins. In conclusion, we all know that Woocommerce is quite basic and to meet certain fundamental requirements for almost any store you have to install some extra plugins (or do a lot of code work). If we also have to add plugins for the styles and small changes, things get complicated.

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v3.5.0

Feel free to update

Thanks!

**Comment by qwik3r** [comment]
> This feature has been added to Elementor Pro v3.5.0
> 
> Feel free to update
> 
> Thanks!

It would be great if you could add a thumbnail of the product on the Woocommerce checkout form. It seems like you guys did the bare minimum with the Woocommerce cart widget options.
