### ISSUE TITLE
Issue with Elementor PRO - php

### ISSUE THREAD

**Issue by Fla1220** [elementor/elementor#13211]
<img width="1320" alt="issue" src="https://user-images.githubusercontent.com/75316307/100745300-5dd69680-33df-11eb-9402-3ca00ce84219.png">

Good afternoon
I reported to Elementor pro some issues that we fixed however I still have this issue with PHP, I am beginner I do not know what to do
Please your help
THanks
Kind Regards

**Comment by Aviad-Herman** [comment]
Hey @Fla1220 ,
The GitHub channel is intended for feature requests and bugs.

If you have a Pro account the fastest way to solve this issue is through our support team but heads up - they might not be able to help you if the problem is unrelated to our plugin.

You can open a ticket here:
https://my.elementor.com/support/

Something I would try while you wait fo the support team to answer:
If you can access WordPress admin, try turning off all plugins and then turning them back on one by one until you figure out which one is causing the problems.

I'm going to close the this issue but feel free to tag me if you run into trouble.

Thanks!
