### ISSUE TITLE
html code element is altered or deleted by other user's session, without touching it

### ISSUE THREAD

**Issue by estlacksensory** [elementor/elementor#13231]
WPEngine
WP Multisite
Genesis Framework
Other plugins could be conflicting but not sure (standard plugins are being used [yoast, cloudflare, autoptimize]).

Shortcodes ultimate has been problematic and working on removing this from site in question.

If adding an "html code" element/widget to elementor layout. Sometimes (almost always) other content editors', or admins' sessions will cause the contents of the "html code" to be deleted or changed. These editors aren't editing the contents of the html code sections. They are editing only text areas or something unrelated to the html code. However, after the session has ended, and they have saved their work the html code is changed or deleted in those areas.

**Comment by shilo-ey** [comment]
Hi @estlacksensory 

Thanks for your feedback.

By default, the only role in a Multisite instance who allowed to add code is Super Administrator. This behavior is because of security reasons.

When entering a page Elementor updates the content that was changed, and in this case - updates the code snippet that was added.

I would suggest modifying the capabilities of your role to allow this for non Super-Administrator users

Thanks
