### ISSUE TITLE
possibility to predefine global colors in CSS for developers

### ISSUE THREAD

**Issue by matthiaswagnerwy** [elementor/elementor#1324]
hy, 
i am aware of the global colors feature, but i guess that many developers would like another feature. when i use elementor for client sites, it is usually embedded into a pretty designed theme, with specific colors.

so far i write css rules for the different widgets (of course the standard colors are disabled in elementor-menu). this works, but i have to check the sites when i update elementor, as new widgets are introduced and sometimes things change a bit inside widgets.

it would be the best if you have classes defined for each widgets, like .textColor1, .bgColor3, ...
so it would be easy to override these classes in our own css and all widgets would depend on them. 

this would also address the problem, that so far it is very hard to override some rules, as you have very much nested selectors in your plugins css.

thanks,
matt

**Comment by matthiaswagnerwy** [comment]
any updates on this? how do other developers address this?

**Comment by bdthemes** [comment]
This option need me too.

**Comment by nicomollet** [comment]
Gutenberg project has a color palette features, interesting to see:
https://github.com/WordPress/gutenberg/pull/2186

**Comment by HelmutGoebel** [comment]
So, when will you implement this? The first request is 15 month old.

**Comment by TerenceMilbourn** [comment]
I understand why "Hello Theme" is meant to be more of a starter/template theme, and this is the reason why it's "missing" styling, but that simply means you have every designer reinventing the wheel, ending up with different answers. And while that is inevitable, to some extent, I don't see why you can't include a common starting point which includes, at least, all of those functions and features of Elementor (Pro?).

**Comment by HelmutGoebel** [comment]
In terms of default styling for text color and typographie settings, hello theme is crap, from my point of view.

**Comment by black-eye** [comment]
+1

**Comment by dotpdesign** [comment]
Global CSS control within Elementor is a must for Professionals. I honestly don't understand why this hasn't been done earlier. At the very least, allow a global custom CSS window to be accessible within Elementor. Doing custom CSS by widget is insane.

+1000 for getting this implemented asap.

**Comment by Hanleymade** [comment]
+1 Professional Developers have different requirements than DIY folks. Pro Devs want high level controls because having to go into each element individually to make adjusts is the most time consuming way to create CSS styles. 
Why not create options for PRO level users and for GENERAL or BUSINESS level users? 

All us to control CSS site wide but beyond just a blank CSS file. Empower us to change all the CSS options on a global level that gives hints on the CSS div names, etc. 

Make changing CSS globally as deep and developed as customizing individual elements.

**Comment by TerenceMilbourn** [comment]
+1 This is what I find easiest to use at the moment --> [Flat UI Colors 2 — 13 Countries, 13 Designers, 14 Color Palettes](https://flatuicolors.com/palette/defo)

**Comment by dotpdesign** [comment]
What is the update on global CSS control within Elementor? Very frustrating for Pro users that this BASIC feature has not been implemented but keeps being asked for over and over again while other less useful features are rolled out with each new update. @bainternet @benpines.

Please make this a priority.

**Comment by squarepixel** [comment]
Any updates? I dont see much feedback from the Elementor team. I just purchased the pro version and was surprised that this is not possible. I create a button as a global element, then have to un-link it to add the link, after that I would have to go and change every button if I change the color of one.

**Comment by dotpdesign** [comment]
@squarepixel Nada. Silence from Elementor. Been too busy creating popovers and buying WP Layers I guess. Undermines my faith in this tool for pro designers to use.

**Comment by shilo-ey** [comment]
@squarepixel 
Thanks for your reply. This feature is on our to-do list for a while, and it requires some infrastructure development that we created and are still working on for this feature to be as best as possible when it will be released.

Thanks.

**Comment by erfan-ilyas** [comment]
Hello Everyone!

While the beautiful people at Elementor Working on this feature, You can use this plugin with SCSS Preprocessor that supports Global Styles:

Please check out:

https://wordpress.org/plugins/rabbitbuilder-global-central-js-css/

It's a Free plugin and hope it helps.

Thanks,
Erfan

**Comment by gravnetic** [comment]
An alternative approach that might be less development would allow for a {twig} or variable to be selectable on all options.  Then developers could set up their variables and select them in colors, fonts, sizes, etc.  This would be a powerful option since it would be more ubiquitous to any of the Elementor options and allow for global control.

Please consider updating users on the status of globals I am getting quite tired of setting up each theme the Elementor way that currently exists.

Thank you!

**Comment by PwrSrg** [comment]
+1  Can't believe this wasn't in Elementor 1.0.  Styles are the industry standard, and is essentially what this is.

**Comment by visim** [comment]
Agreed. I would focus on this issue because it presents a serious workflow issue for professionals or those who would like to maintain consistency sitewide.  I also can't believe this is not implemented to date but the focus has been on more flashy features instead. 

**There should be the ability to:**
- Set a font style and assign it a name that is referenced in the "HTML tag" select box in elementor globally.  It can be all the H tags or custom styles as well. 
- Set global colors that can be referenced in the color palette globally. The current setup is limiting and awkward to use. The colors should also reference the color codes. 
- I would build this in an area called globals organized by fonts, colors, etc. Then you would visually create a font the way you want it and then assign it to an HTML tag. Once assigned it shows up everywhere. 

Just think about my workflow. Right now I have to write down on paper what each "style" is for each section of my site. Then I have to create new pages and manually edit each font to those specifications or I have to write a custom class to overwrite the font which kind of defeats the purpose of using elementor to begin with. 

Thanks

**Comment by jonburdon** [comment]
I am staggered that this is not already in existence. It's standard on rival page builders like Fusion Builder for Avada, which isn't even considered to be one of the builders. Doesn't everyone want to work like this? PLEASE add it, either to Elementor, or to Hello Theme.

**Comment by Aerendir** [comment]
Any news on this?

It maybe helpful to give colors in the colorpicker a name that can then be referenced in custom CSS (in Advanced > Custom CSS).

In this moment I need to use an hardcoded color and if I decide to change it, I have to change it also in all the elements I used it: very very annoying, time consuming and prone to errors.

Instead, we could:

1. Set a color in the colorpicker (like described here: https://docs.elementor.com/article/612-color-picker)
2. Give the color a name (ex.: `$my-color-picked-color`)
3. In Advanced > Custom CSS, we can now write something like:

```scss
selector {
    background-color: $my-color-picked-color
}
```

This way our work as developers is really easier and if we need to change a color something else (darker or clearer, for example) we only need to edit it in one place and it is automatically changed everywhere.

**Comment by ahmetsali** [comment]
This is a must-have feature for Elementor that prevents to build a solid design system with Elementor, static colors are lame when you need to update any color that is used more than once in any section or widget.

IMO: The ideal solution would be like;

- A panel where we can define globally our color variables with a name given.

- Extend the current color picker with a list of these pre-defined colors to allow using of dynamic globally updateable pre-defined colors.

The workaround I follow for this gap is to use CSS Classes,

I add a class like below to the Additional CSS field;

```
.-bg-accent.elementor-section,
.-bg-accent > .elementor-column-wrap { background-color: #0a48ff; }
```

then I add this class to any section, column or widget which I want to have set it's bg color to global accent bg color.

Please make this priority for future updates.

Thanks.

**Comment by Aerendir** [comment]
@ahmetsali , this is really a complex workaround unfortunately: it causes anyway a lot of repetition. Imagine I want to use the same color for the text in one place, for the borders of a table in another place, as a background in another place... If I want to change this color I have to change it in at least three different places. Multiply by at least three (the number of colors present on a standard website) and you have 9 places.

This comment is not to criticize your solution, but to point out once more the needs for a solution by Elementor itself as this is really a pain in this moment.

**Comment by Aerendir** [comment]
PS @ahmetsali 
As a better workaround, you can use a plugin that supports scss directly in Wordpress: I've never used one as I use a custom theme child that already supports SCSS, but I've seen it used on very big sistes with very good layouts.

**Comment by ahmetsali** [comment]
@Aerendir thanks for your comment, I see your point and it makes sense, I eventually plan to add the colors as options to the Customizer, so the repeated CSS (3 times as you pointed out) will be generated automatically by the Customizer option. But, this limits the colors I can use to the options count I will add to the Customizer.  

Elementor should definitely add this to the core.

**Comment by PwrSrg** [comment]
The BEST "workaround" I have found so far is **WunderWP** and **Style Kits**.

https://wunderwp.com
https://analogwp.com

I just wish the Elementor team would get their act together and finish implementing this aleady.  They announced it _over a year ago_.  😑

**Comment by erfan-ilyas** [comment]
Guys give this plugin a try. It supports SCSS/CSS/JS/HTML

And it also supports Elementor Global Colors and Color Picker colors.

https://wordpress.org/support/plugin/rabbitbuilder-global-central-js-css/

**Comment by Aerendir** [comment]
@erfan-ilyas , thank you for the suggestion... Maybe I will try it, also if I prefer not installing other plugins... I would like Elementor offers this feature built-in :)

**Comment by erfan-ilyas** [comment]
Thanks for your consideration.

Looks like you really care about site optimal experience.

The best advise I can give is that you can use this plugin to generate
final and critical css.
Once generated you can use it directly in your theme. Be it a child theme
and uninstall the CSS plugin.

That will be the only faster and efficient way of doing things.

As you may already know Elementor generate css dynamically and it generates
100s of them.

Each page, Each template has a different CSS.

If you are using Elementor css internally in page head its going to put
some serious load on the CPU.

If you are using Elementor CSS as external file. You will notice a issues
like FOUC, Where you will notice a page initially has default styles but
suddenly everything seems to fine.

Some good read about FOUC:

https://www.techrepublic.com/google-amp/blog/web-designer/how-to-prevent-flash-of-unstyled-content-on-your-websites/

Some good read about Critical CSS:

https://wp-rocket.me/blog/critical-css/#:~:text=Critical%20CSS%20is%20the%20process,so%20it%20can%20load%20faster
.

For everything advance this plugin can help and save time.

Thanks.

**Comment by utsavmadaan823** [comment]
For what i understand, you guys need control on global colors i.e. change colors globally wherever they have been used.

Probable solution you guys are looking for is support of CSS Variables but alternative solution which i am using is -
1. Create options page with ACF (https://www.advancedcustomfields.com/resources/options-page/)
2. Create Global Colors group in ACF and assign it to created options page
3. Add your Global Colors (Primary, secondary, background, etc) as color fields to Global Colors Group created above
4. Now instead of directly assigning color via color picker in elementor to any element/section instead take color from Dynamic tag > ACF Option > Global Colors > your defined color (Primary, secondary, background, etc)

Now all colors in elementor will be linked to ACF Option which you can change in ACF Options page created above all at one place. Would like to hear from you guys.

**Comment by mbaierl** [comment]
Hi @utsavmadaan823 ,
that's exactly what I use in one of my projects, however there are so many bugs within Elementor... for example popups can't use the global colors. According to the support, that's not supported. Sometimes in the editor the colors don't show up, which makes editing content really hard...
Too bad.

**Comment by dotpdesign** [comment]
Since I first commented on the lack of global colors in 2018 then again in 2019 (see above) and now in 2020, I've come to realize that Elementor is NOT a tool for professional developers. It is a tool for DIYers and small business in house marketers. 
**Elementor is all about capturing market share for these groups, not professional designers and developers.** Oxygen is now the clear tool for pro design and dev. Unfortunately, Oxygen is terrible for client use, and that is where Elementor shines. If Elementor would ever address the core issues of pro devs in a timely manner then Elementor would be a win for both clients and professionals.

**Comment by utsavmadaan823** [comment]
> Hi @utsavmadaan823 ,
> that's exactly what I use in one of my projects, however there are so many bugs within Elementor... for example popups can't use the global colors. According to the support, that's not supported. Sometimes in the editor the colors don't show up, which makes editing content really hard...
> Too bad.

Actually i have used this method in 3-4 projects and one was very extensive and i have never felt any issue using this method, colors update instantly but haven't checked Popups but just checked loading one Popup and since Popups are also ultimately made from section/column/widgets and they all support dynamic tags + acf  (i believe so - someone may confirm) so can't think of any reason that why it is not working for you. 

Using this method i have even created multiple themes + light/dark mode (by just overriding acf color options at runtime based on conditions). 

It could be difference in implementation. I could compile and share if people here need.

**Comment by utsavmadaan823** [comment]
> Since I first commented on the lack of global colors in 2018 then again in 2019 (see above) and now in 2020, I've come to realize that Elementor is NOT a tool for professional developers. It is a tool for DIYers and small business in house marketers.
> **Elementor is all about capturing market share for these groups, not professional designers and developers.** Oxygen is now the clear tool for pro design and dev. Unfortunately, Oxygen is terrible for client use, and that is where Elementor shines. If Elementor would ever address the core issues of pro devs in a timely manner then Elementor would be a win for both clients and professionals.

Maybe you can use alternative solution i have provided ? At some point i was also looking at Oxygen but never moved to it.

**Comment by mbaierl** [comment]
> Actually i have used this method in 3-4 projects and one was very extensive and i have never felt any issue using this method, colors update instantly but haven't checked Popups but just checked loading one Popup and since Popups are also ultimately made from section/column/widgets and they all support dynamic tags + acf (i believe so - someone may confirm) so can't think of any reason that why it is not working for you.
According to the support Elementor only reads the ACF values from the current page (for popups), but not from the ACF options page. Therefore it does not work.
The so-called "support" never responded when I asked them to file a bug report and fix this.

**Comment by ahmetsali** [comment]
Elementor is not a complete design tool without global colors :/ Global colors should be the #1 priority for the update list, not fancy Lottie animation widget!

**Comment by PwrSrg** [comment]
I have since discovered and moved to [**OXYGEN**](https://oxygenbuilder.com) for exactly this.  It no longer makes sense to wait for an aging product to play "catch up".

You can't teach an old dog new tricks.

Thank you Elementor for all that you did for me.  Rest in peace.

**Comment by freelancesam** [comment]
@PwrSrg @ahmetsali - Global colours are introduced in the next update

**Comment by Aerendir** [comment]
> @PwrSrg @ahmetsali - Global colours are introduced in the next update

Where did this news came from?

If truw we will be very very happy!

**Comment by ahmetsali** [comment]
@freelancesam thanks for the info, really appreciate it.

I have just seen Global Colors Sneak Peek video on youtube;

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.0

Feel free to update

Thanks!

**Comment by gsusI** [comment]
In case it helps someone, I use  var(--e-global-color-accent) in my Custom CSS fields and it works just fine.

**Comment by ahmetsali** [comment]
> This issue has been resolved in Elementor v3.0
> 
> Feel free to update
> 
> Thanks!

great but they can't be exported and then imported to a different wordpress site :/

as mentioned here;

https://github.com/elementor/elementor/issues/12340

**Comment by NilsDannemann** [comment]
> In case it helps someone, I use var(--e-global-color-accent) in my Custom CSS fields and it works just fine.

Thank you for mentioning this!

**Comment by jared-rice** [comment]
I have used `color: var( --e-global-color-primary );` with some success, however, from first glance it seems that these only generate if a page/post is using the Elementor Builder.

Has anyone been able to use these variables on other pages not edited with the Elementor Builder?

**Comment by jared-rice** [comment]
> I have used `color: var( --e-global-color-primary );` with some success, however, from first glance it seems that these only generate if a page/post is using the Elementor Builder.
> 
> Has anyone been able to use these variables on other pages not edited with the Elementor Builder?

There might be a better way to do this, but I am manually enqueue the `post-...` CSS file that the variables are set in located in the `wp-content/uploads/elementor` folder.

I assume these CSS file names will change on each website, so it isn't perfect. If anyone has more thoughts on this you're welcome to provide them!

**Comment by mlifshitz** [comment]
How to do an example:
`<meta name = "theme-color" content = "# 1D1E32" />`
That instead the color will attract from the global primary color?

**Comment by mindfullsilence** [comment]
Really not sure why this required so much infrastructure work. CSS variables - great. That helps. But from what I can tell, it's a matter of just adding a filter to the global-colors.php file so developers can hook in. 

```php
$default_colors = [
	[
		'_id' => 'primary',
		'title' => esc_html__( 'Primary', 'elementor' ),
		'color' => '#6EC1E4',
	],
	[
		'_id' => 'secondary',
		'title' => esc_html__( 'Secondary', 'elementor' ),
		'color' => '#54595F',
	],
	[
		'_id' => 'text',
		'title' => esc_html__( 'Text', 'elementor' ),
		'color' => '#7A7A7A',
	],
	[
		'_id' => 'accent',
		'title' => esc_html__( 'Accent', 'elementor' ),
		'color' => '#61CE70',
	],
];

$global_colors = apply_filters('elementor/global/colors', $global_colors);
```

Shoot, could do the same with icons and fonts as well. Then developers could easily create a plugin to modify the colors:

```php
function my_brand_colors($colors) {
  $colors[] = [
    '_id' => 'brand_red',
    'title' => esc_html__('Brand Red', 'my_brand'),
    'color' => '#0000FF',
  ]

  return $colors;
}

add_filter('elementor/global/colors', 'my_brand_colors');
```

Seems silly to take so long to create a way for devs to add their own colors programmatically, IMHO.

**Comment by black-eye** [comment]
@mindfullsilence You are completely right! Unfortunately, Elementor doesn't care. There's also one open issue for the same request here: https://github.com/elementor/elementor/issues/12866 Maybe you could add you comment there as well.

**Comment by wppunk** [comment]
@mindfullsilence @black-eye 

I've found a way how to use default colors and why it's too hard to implement in Elementor.
1. Add the next snippet with your default colors in the `functions.php` or  somewhere else:
```
add_action( 'elementor/frontend/before_enqueue_scripts', ( $element, $section_id, $args ) {
	if ( 'section_global_colors' === $section_id ) {
		$element->update_control(
			'system_colors',
			[
				'default' => [
						[
							'_id'   => 'primary',
							'title' => __( 'Primary', 'elementor' ),
							'color' => '#F6DA04',
						],
				]
			]
		);
	}
}, 10, 3 );
2. Drop postmeta for the Default Kit post. The post ID you can on the frontend: https://a.supportally.com/xIK9IB
3. When you visit the Default Kit it will be broken and Elementor suggests you to recreate the kit, after recreating you will have only one Primary color.

**Comment by wpexplorer** [comment]
Its 2025 and we still don't have the ability to modify the System Colors via a hook? Even Gutenberg allows this...
