### ISSUE TITLE
Problem with Elementor Pro Theme Builder and ACF Pro

### ISSUE THREAD

**Issue by pacgit** [elementor/elementor#13355]
After installing Advanced Custom Fields Pro, then going into the Elementor Pro Theme Builder, there is an apparent bug in the the forms used for "Single tab" and "Single Post" tab.

After Clicking either Tab, there is a green button that reads "ADD NEW SINGLE" or "ADD NEW SINGLE POST"

Both lead to a form that shows 2 dropdowns, where there should be 3 dropdowns.  I know this because using "Inspect Element" in Google, there are 3 dropdowns...

The display HTML for the id "elementor-new-template__form__post-type" is missing.

It shows:
1. Select the type of template you want to work on
2. Name Your Template

It should show:
1. Select the type of template you want to work on
**2. Select Post Type**
3. Name Your Template

This simple BUG prevents anyone from identifying a custom post type - where dynamic content could be displayed.

I have created a webpage that shows exactly what I saying above.  Here is the link:
https://www.myrobotadmin.com/elementor-pro-bug.html

**Comment by twokickers** [comment]
I have the same behavior here. The dropdowns appears only when when getting back to 3.0.3, but mixing up "Single" and "Single post" tabs, and even then, the ACF fields keys don't show in any widget.

**Comment by fuzenco** [comment]
This needs fixed ASAP. :(

**Comment by DorShahar** [comment]
Hi,
Thanks for reporting.

The 2 dropdown been updated from 3 (instead of doing singe > post or page, now you can choose directly single post or single page) . 

Truly there is a bug in the ACF fields key. We are on it!

**Comment by sermalefico** [comment]
ASSAP!!!!
is imposible work whithout it!
All custom fields dissapear!

**Comment by DorShahar** [comment]
Hi
The fix will be released in the next version. 

Thanks.

**Comment by DorShahar** [comment]
Hi 
Just an update that the bug been fixed and will be released in v3.1.0.

Thanks

**Comment by DorShahar** [comment]
Hi @pacgit

I’m sorry for the confusion, I didn’t understand you.

As explained earlier in this thread, we changed this a while ago. This was since our users misled by the previous dropdown with the “Single”.
If you desire to add a new value to the list, you need to add a new Location. You can check how to do it in [this documentation](https://developers.elementor.com/theme-locations-api/registering-locations/).

The reason that you see the old dropdown is for backward compatibility.
As for all the rest, the bug in dynamic fields been fixed and been released with the new version (v3.1.0)


Thanks

**Comment by Giacomo92** [comment]
Hi @DorShahar, we have currently have v3.1.1, but the bug is still there. Can you please check? Thanks
<img width="1444" alt="Schermata 2021-02-03 alle 23 14 42" src="https://user-images.githubusercontent.com/11694429/106816413-9ad83700-6675-11eb-94fc-23e655ae6766.png">
<img width="983" alt="Schermata 2021-02-03 alle 23 16 12" src="https://user-images.githubusercontent.com/11694429/106816535-d115b680-6675-11eb-8044-ae2ba446159b.png">

**Comment by DorShahar** [comment]
Hi @Giacomo92 
I don't understand what do you call "the bug"?
What you shared in the screenshot is the current behavior. 

In my previous comments,  I referred to a bug as a problem we had in dynamic fields.

Please let me know if there is a problem. 

Thanks.
