### ISSUE TITLE
JavaScript error on new update

### ISSUE THREAD

**Issue by titch98** [elementor/elementor#13372]
Hi peeps,

Just had Elementor updated in my Wordpress site to release 3.0.15. As soon as it updated, it threw up the following error in my Complianz (free version) plugin 4.8.2 which was working fine prior to the update:

Uncaught_ReferenceError:_elementorModules_is_not_defined on line 2 of https://nnpg_org_uk/wordpress/wp-content/plugins/elementor/assets/js/elementor-admin-bar_min_js

**Comment by shilo-ey** [comment]
Hi @titch98 

We haven't changed anything in the latest version that relates to this area.

This issue is probably caused by the Cookie consent plugin which interferes with the order of the scripts being loaded and makes the `elementorModules` throw this error.

See if you can exclude this script from loading
