### ISSUE TITLE
set_settings not working

### ISSUE THREAD

**Issue by OTW-DEV-1** [elementor/elementor#13399]
Hi, i am trying to overwrite elementor display settings by using this hook 

```PHP
add_action( 'elementor/frontend/before_render', [ $this, 'before_render_content' ], 10, 1);

public function before_render_content($widget){
  if($widget->get_name() == 'theme-post-title'){
	$widget->set_settings('title', 'new heading');
        //var_dump($widget->get_settings_for_display());
  }
}
```
But the above code isn't working.

**Comment by DorShahar** [comment]
Hi 
Our developers suggest to use `get_settings` instead `get_settings_for_display `.

If this ain't solved, open a new issue - and link to this one. 

Good luck

**Comment by symplTech** [comment]
You have suggested using something not related to the original post request.

I get same issue - when using:
`$widget->set_settings('text', 'test');
`
inside "elementor/frontend/widget/before_render" of button widget

there is no effect on render, that something that used to work well before few updates (guess since you added get_settings_for_display)

As I see in the code, best solution for that would be to add "set_settings_for_display" function on Elementor plugin.
