### ISSUE TITLE
Nav menu only shows one item of the nav menu bar

### ISSUE THREAD

**Issue by snelzing** [elementor/elementor#13536]
There is a header with a navbar that looks nothing like it will actually look in the page. 

This in the header, for some reason this issue is not in the footer.

Custom CSS has been controlled for.

This is in elementor pro.

![image](https://user-images.githubusercontent.com/39928924/104060422-ddb50500-51c4-11eb-9439-82e2ad21212f.png)
![image](https://user-images.githubusercontent.com/39928924/104060614-27055480-51c5-11eb-9d10-f3bf8eca1881.png)

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* **Isolating the problem.**
* **System info.**
* One issue per thread

Without it, we simply can't help.

Also, please try to deactivate other plugins and use Elementor Hello Theme. 
Since you are using Elementor Pro - you can contact our support and they could help you out. 

Thanks.
