### ISSUE TITLE
responsive layout for Archive Posts widget

### ISSUE THREAD

**Issue by LievenLitaer** [elementor/elementor#13676]
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have created my blog archive template with Elementor Pro and it all works fine. But I have noticed that when I set the image to be "left", it will keep the same layout on mobiles, which makes the text disappear outside of the screen. Also, when I switch to edit mode for mobile, and move the image to "top", of course it will remain there in desktop view. So my wish is to set the layout to adapt to screen size, like it does with columns.

**Describe the solution you'd like**
I want: 

desktop view: 
image | text

mobile view:
image
text

**Describe alternatives you've considered**
I can partially solve that by setting the layout to cards, but I don't really want the cards layout. But at least, the layout works on bot screens.

**Comment by bkjproductions** [comment]
Overall, Elementor needs more settings for Responsive adjustments. Each property that is settable really deserves it. Attached is how it could look for the Posts Widget in Elementor Pro.

![posts-widget--missing-responsive-controls](https://user-images.githubusercontent.com/4551281/108890836-0a3da880-75dc-11eb-8ece-8cc1b572c456.jpg)

**Comment by arielk** [comment]
Please use loop builder feature for this: https://elementor.com/blog/introducing-the-loop-builder/

Thanks for your feedback!

**Comment by bkjproductions** [comment]
@arielk I think we are pointing out that there is an inconsistency in the interface, it seems like the Posts widget is fine, otherwise, just needing a little bit of extra control. Nice as the Loop Builder is, it is not immediately clear how to use it for  the situation described. 

Many people would just like a simple widget for Posts that will display them and provide basic controls that are currently missing in it. To have to go out-of-the-box and create a widget is sort of overkill for this task.  If I create a Template for the Loop Builder, and I want to use it on another website, I have to export that Template, so that's a hassle, too.

**Comment by arielk** [comment]
@bkjproductions There are countless options that can be added to each element, so the direction we are going is to break down the large components into smaller elements to increase flexibility and customization options for users. 

Additionally, we will be introducing a Loops library that will provide users with a starting point for editing, eliminating the need for exporting and importing between sites.
