### ISSUE TITLE
Slow loading times after 3.1 and 3.1.1

### ISSUE THREAD

**Issue by kromeninja** [elementor/elementor#13762]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

The latest versions of Elementor cause much slower total load times on the site, the content loaded is much larger in size than it was previously and nothing content wise has changed since 3.0.16 which is working fine in regards to load times. I have attached a print screen of the speed test, the page loading times are the same for the latest version3.1.1 also:

[https://i.imgur.com/rjDrQv0.jpg](url)

## Steps to reproduce
I can reproduce this each time by loading version 3.1 or 3.1.1, re generate CSS and purge cache and run a new speed test, the result is as shown in the above print screen, as soon as I rollback to 3.016 the load time is much faster at 1.7 seconds.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

**Comment by kromeninja** [comment]
An update to this:

Removing the video element with a youtube link resolves the speed issue, adding the video player causes the website to load much slower than normal. The video element has a image overlay set and lazy loading enabled.

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by shilo-ey** [comment]
Hi @kromeninja 

Sorry to hear that it inflicts your loading time.

Please try to use the Improved Asset Load experiment under Elementor > Settings > Experiments

Thanks

**Comment by kromeninja** [comment]
Hey @shilo-ey I have tried those settings and sadly they did not resolve the slow loading time with the video player element.

**Comment by zhiv12** [comment]
Hi Shilo-ey

There is a problem related to the 'Improved Assets Loading' experiment. You are developing something counter-productive there.

The improved asset loading is calling JS files from other JS files.  I have managed to preload extra JS calls from JS files via adding to the HTML something like:
<link rel=”preload” as=”script” href=”/wp-content/plugins/elementor-pro/assets/js/form.9c115e6f5683e739f4d6.bundle.min.js” />
For wiper.JS I have to use a different option by adding crossorigin=”anonymous” :
<link rel=”preload” href=”/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js?ver=5.3.6″ crossorigin=”anonymous” as=”script” />

So, the extra JS files are preloaded and thus are already there before the “DOM is ready” event and should not slow down the parsing process. However, your implementation of the new “Improved Asset Loading” results in an extra second of JavaScript files' parsing on mobile and desktop devices. 

**The overall size in bites for JS files is smaller, but the parsing time is much longer.**

Choosing the 'Improved Assets Loading' option leads to irreversible degradation of the page loading speed. I had to restore from the backup to gain my previous page speed results.

Overall, I have found a drop in the mobile page load speed by about 15 units (from 90 to 75) and the desktop page load speed by about five units (from 97 to 92) during your recent changes introduced in January/February. By turning on the 'Improved Assets Loading' experiment, the mobile page load speed drops by about 25 units (to 50) in addition to the 15 units mentioned above. Overall, it is 40 units drop (from 90 to 50) in the mobile speed. It is more than a worry – it is a disaster.

Best regards

Victor

**Comment by rotemee** [comment]
Hi Victor (@zhiv12),

Thank you for your feedback.

Please note that the "Improved Assets Loading" mode is part of an experiment that we are currently running, and you can disable it at any time (go to dashboard >> Elementor >> Settings >> Experiments >> Improved Assets loading) instead of a rollback to the previous version.

From multiple tests that we've made, we couldn't find any indication of increased parsing time that delays the "Full Page Load" metric - for example:
![swiper-performance1](https://user-images.githubusercontent.com/61740845/108987874-77187780-769c-11eb-9649-077a16d36fa5.png)

As you can see on the "Optimized" version (on the right), where the script is loaded in a much later period, there is no indication of a longer parsing process.

We are constantly working on improving the page's performance, and any additional info can be helpful.
It will be great if you can elaborate regarding the metrics that you've experienced.
Do you have any screenshots or links of "before" and "after" results? do you have any suggestions on improving the current solution?

Thanks.

**Comment by zhiv12** [comment]
Hi Rotemee,

I am afraid that your tests are incomplete. And this was a reason to contact Elementor. You are failing to test your features.

The Google mobile page speed loading is the primary concern of many people as from this May it will directly impact Google ranking. Your Experiment with “Improved Assets Loading” degrade this metric from 75 to 45 on my website. Your recent changes made in January/February had also reduced my mobile page load speed score from 90 to 75. So overall, I have seen the drop from 90 to 45 in the space of just two months. This is a complete disaster, and I am in a state of disbelief that the Elementor testing team is not aware of the enormous impact your recent changes are making on the mobile page load speed. It is going to be a PR disaster to Elementor – this May everyone will go bombastic to unload their frustration on your developers. The drop in the Google ranking is not a minor issue in the community – you better change your development and testing direction to prepare to answer to the angry mob.

Best regards

Victor

**Comment by zhiv12** [comment]
And please don't substitute the tools. Your GTMetrix is measuring performance on the ideal desktop device with unlimited bandwidth. JavaScript parsing is the main obstacle on a mobile device. So, please, please instead of going for defensive rejection of the bug, try to use proper tools and listen to what is coming to you in just a few month time.

**Comment by zhiv12** [comment]
Another person had suggested that preloading did not help because there was no option to define that the new JS files have to be parsed after the DOM is loaded. So, they start parsing as soon as received and thus became a blocking asset.

The watershed moment for Elementor will come this summer. This May, Google will change algorithms to include Page Speed as one of the significant metrics. The angry mob will attack Elementor just in time when WordPress will release a new version of the Guttenberg capable of editing any element on the website in June.

Numerous bloggers will write the post like  “Elementor is dead, vivat to Guttenberg!”

Your development team is just playing with the fire in a perilous Orwellian way, announcing new features that should accelerate our websites. We test such features ON THE MOBILE DEVICES to find out that they are making our website slower. 

Marvellous!
