### ISSUE TITLE
Accordion doesn't open anymore

### ISSUE THREAD

**Issue by xecampa2** [elementor/elementor#13874]
Place an elementor accordion widget and then change its content with javascript:

var foo = document.getElementById("IDBOX").innerHTML; 
foo = foo.replace("AAA", "AAA");
document.getElementById("IDBOX").innerHTML = foo;

After this, the accordion doesn't open anymore.
The html portion before and after javascript runs is exactly the same.

**Comment by DorShahar** [comment]
Hi 
Thanks for reaching out.
It is not clear what are you trying to achieve. 
`innerHTML` returns a markup. The opening and closing of the accordtion changes the markup (see the DOM changes in the dev-tools).
Maybe try to use `innerText` (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText) to work with a string, since `replace` returns a string as well. 


Good luck
