### ISSUE TITLE
Nav Drop Down Not Work And Cards Not Displaying In Element 3.1 

### ISSUE THREAD

**Issue by trynet** [elementor/elementor#13881]
2 issues found in Edge Browser

> Nav not working, no dropdown. 
> Card display not working

These were not issues until 3.1

Environment

Device:
HP Probook 430 G4

Windows 10 Pro
Version: 1909
Installed: 10/3/2019
OS Build: 18363.1316

About Microsoft Edge
Microsoft Edge: 44.18362.449.0
Microsoft EdgeHTML: 18.18363
c. 2019 Microsoft

Elementor 3.1

GeneratePress  [3.0.2[](url)](url
![correcly](https://user-images.githubusercontent.com/5448478/107645918-5802fa00-6c47-11eb-87ac-fa8d225e369e.png)
![incorrectly](https://user-images.githubusercontent.com/5448478/107645919-5802fa00-6c47-11eb-8025-ba6344e22703.png)

)

**Comment by JonnyP27** [comment]
Don't know about the cards but I can definitely confirm that the nav menu dropdowns don't work in Edge in 3.1. In my case they're not showing at all.

Browser console error messages show a syntax error in frontend.min.js and the highlighted code refers to swiper (soz...can't remember exact reference and I don't want to break the site to check again!)

Using Elementor Hello theme. Tested with all plugins deactivated to confirm that the issue was with Elementor.

**Comment by JonnyP27** [comment]
Seems as though this problem is limited to Edge legacy version only. There is a solution offered here:

[https://wordpress.org/support/topic/elementor-3-1-doesnt-display-properly-in-microsoft-edge-legacy/](https://wordpress.org/support/topic/elementor-3-1-doesnt-display-properly-in-microsoft-edge-legacy/)

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
