### ISSUE TITLE
No way to make it work

### ISSUE THREAD

**Issue by FabQuimbaya** [elementor/elementor#13885]
Hi!
I just installed a new WordPress on our dedicated server.
It doesn't allow the editor in any way.
I already tried everything as per your instructions about enabling the safe mode and even the other instructions to follow when the previous ones don't work.
All plugins are deactivated, WordPress is the last version, I changed the theme, changed permalinks, etc.

**Comment by DorShahar** [comment]
Hi,
Thanks for reaching out, but your issue is very specific and abstract. 
Our policy is that GitHub issues only for bugs reports and feature requests.

If you have questions or need general support, Please try:
Elementor Community on Facebook
Elementor Knowledge base
Support forums on WordPress.org
Elementor Developers docs
**If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.**

Thanks.

**Comment by FabQuimbaya** [comment]
Yes you’re right. I’m sorry. Anyway I solved the problem it was due to a problem with the SSL certificate.

**Comment by DorShahar** [comment]
I'm happy that it worked out for you! :)
