### ISSUE TITLE
Language files are incomplete since Update to Elementor 3.1.1 an 3.0.10 Pro

### ISSUE THREAD

**Issue by dbfischer** [elementor/elementor#13910]
Since the update to 3.1.1 and 3.0.10 Pro, the translation for German is no longer complete.
I have noticed this on several installations.
For example, the "Save" button is now called "Update".
The settings menu is completely in English instead of German as before.
The same applies to some context menus (right mouse button).
![Screenshot_2021-02-15 Elementor Neuanlage](https://user-images.githubusercontent.com/15387379/107943560-2cf11100-6f8d-11eb-9fbc-905c9257dbdb.png)

**Comment by shilo-ey** [comment]
Thanks,

This is due to a change we had in the translation mechanism.

It takes about 24 hours for the assets to be updated and then you will be able to get the proper translations.

If this issue isn't resolved in 24 hours from now, go to your WordPress dashboard > Updates and check for translations.

If the issue persists please create a new issue.

Thanks!
