### ISSUE TITLE
Server Error (500 errors)

### ISSUE THREAD

**Issue by yeahbrunz** [elementor/elementor#13958]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by parasshah195** [comment]
@yeahbrunz, 500 server error can be caused by a plethora of reasons. It basically means - some code is messed up and throwing errors, so I can't load the page. 

But what exact errors? It doesn't tell you that.

You'll find the exact cause/error in the server error log file. Contact your hosting provider to locate and check it out. If it says that the error is in some PHP file in the Elementor plugin folder, then it's an Elementor issue, otherwise, it could be some other plugin/theme functionality clashing or causing the problem.

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

Thanks.
