### ISSUE TITLE
⛔ 🚀 Feature Request: Give an option to have Elementor always use relative URLs

### ISSUE THREAD

**Issue by hades200082** [elementor/elementor#13972]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When using multiple environments in modern WordPress hosting such as WP-Engine or Pantheon you get 3 total environments:

- Development
- Staging
- Live

If we include a local environment using a tool such as Flywheel or Lando then we have 4 different environments with 4 different base URLs.

Currently, Elementor and Elementor Pro both store absolute URLs for media assets embedded into templates.

This prevents any kind of CI/CD being used with sites that use Elementor because the image URLs are then broken when the CI/CD deploys site changes to a different environment.

The same issue appears when deploying/staging changes from one environment to another manually or using the hosts own tools. Pantheon, for example, has its own tool that deploys the site and database from one environment to another.

**Describe the solution you'd like**
While Elementor does include a tool to find and replace these URLs it would be a better developer and user experience if Elementor used relative URLs instead and negated the need for this tool altogether.

**Describe alternatives you've considered**
WPBakery

**Additional context**
This appears to be a very common issue that causes lots of other "symptoms" to be posted as issues here on your github:

- https://github.com/elementor/elementor/issues/1453
- https://github.com/elementor/elementor/issues/7376
- https://github.com/elementor/elementor/issues/6764
- https://github.com/elementor/elementor/issues/6727
- https://github.com/elementor/elementor/issues/4400
- https://github.com/elementor/elementor/issues/2715
- https://github.com/elementor/elementor/issues/1538
- https://github.com/elementor/elementor/issues/1191
- https://github.com/elementor/elementor/issues/740
- https://github.com/elementor/elementor/issues/403
- https://github.com/elementor/elementor/issues/12659

Every one of these linked issues is directly or indirectly related to the fact that Elementor is storing absolute URLs that include the domain. Changing this to store relative URLs instead would resolve all of these issues AND negate the need for a URL change tool at all.

**Comment by euene** [comment]
While I agree with all of your points, and I much prefer relative URLs over absolute URLs, unfortunately the WordPress core itself is built around absolute URLs and it has been a long-time stance of WordPress core developers that absolute URLs are here to stay and they are a "design decision that's not likely to change" - a direct quote from a WordPress core dev.

This is one of the many topics in which the issue has been discussed over the years.
https://core.trac.wordpress.org/ticket/17048

I disagree with the reasoning of core WordPress devs on this matter, but due to that fact, relative URLs would likely never happen as a result in Elementor as well.

The best possible workaround at the moment is to integrate a database find/replace tool in your deployment workflow. The pro version of the WP Migrate DB plug-in is supposedly good and suited to such multi-environment scenario, but I haven't personally used it in such a way.

**Comment by hades200082** [comment]
I thought the point of plugins was that the plugins can do things differently to make life better?

Just because core WordPress does it one way doesn't mean that Elementor have to also.

In addition, I have no problem with image URLs that are embedded in posts, set as preview images, etc. when deploying between environments with WordPress. The only time I have issues is with Elementor ... this suggests that there is something either wrong with Elementor, or there needs to be some special consideration given here to the way in which Elementor is storing URls.

**Comment by euene** [comment]
As far as I know, Elementor currently uses a number of core WP image functions in some of its widgets - such as wp_get_attachment_image() - and possibly others. For example, when native lazy loading for images landed in WP core in v5.5 - as a result, some Elementor image widgets now have that feature as well - but other widgets which aren't using the built-in functions don't have it as a result.

So that's one example why Elementor might be dependent on WP core for some things, and image URLs is unfortunately a big one.

**Comment by hades200082** [comment]
Ok, I understand.

So, in regards to deploying between environments; Pantheon (the host I use) and Lando (the local dev tool) both use the WP-CLI to do find/replace of URLs after migration to update all URLs in the database with the domain of the new environment. They do this automatically as part of the deployment (or in Lando's case the push/pull) process.

Would it be possible to get Elementor to hook into that somehow so that it can update its own URLs at the same time?

**Comment by ChrisASearles** [comment]
I'm a huge second on this for relative URLs. The core issues we have are that the links to pages auto-populate with an absolute URL when it would be really easy to just load the slug and make it relative. The other, more important one that's not covered by the URL change tool are URLs used in CSS for things like background images. These are much harder to find and there is no control or visibility into the URL being used when setting a background image.

**Comment by ian-a-anderson** [comment]
If the team doesn't wish to build-in this functionality, could a hook be provided so that devs can implement it themselves if desired? It seems like adding a filter right before the CSS file write to the filesystem would allow the necessary extensibility:

**\wp-content\plugins\elementor\core\files\base.php** LINE 178:
```
public function write() {
    $file_content = apply_filters( 'elementor/cssfile/content',  $this->content );
    return file_put_contents( $this->path, $file_content);
}
```

**Comment by dwasyl** [comment]
I've recently had need to have a WP site answer to two different URLs and wasted a lot of time trying to fix this exact issue.

Would it be at all possible to have Elementor generate the URLs dynamically so that they at least mirror `WP_SITEURL` or `WP_HOME`? (for example I have `define( 'WP_SITEURL', 'https://' . $_SERVER['SERVER_NAME'] );` set, so the page loads fine but some of the elements being loaded by Elementor fail due to CORS rules.

**Comment by nicholaszein** [comment]
Hello there,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap for the time being.

WordPress has many ways to handle permalinks, change folder locations, and rewrite rules. This means that there is no way we can accurately predict what will be the final path of each file since there are infinite different paths they can take. Adding such a feature would be simply impossibly complicated and would probably mean causing lots of incompatibility issues and unforeseen cases.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
