### ISSUE TITLE
Theme builder Header

### ISSUE THREAD

**Issue by Dcclow** [elementor/elementor#14127]
Running php 7.4 dedicated server with very good resources.

Not sure if this is a bug but its not happening elsewhere when building pages.

In theme builder and making a header when uploading a new image im getting Post-processing of the image failed likely because the server is busy or does not have enough resources. Uploading a smaller image may help. Suggested maximum size is 2500 pixels.

This error does not appear anywhere else on the site only in Theme header

**Comment by DorShahar** [comment]
Thanks for reporting,
There is not enough info so we can investigate. 

Since you are a Pro user, you are welcome to contact our support, where they can access your environment and look if there is any problem from our side. 

It is recommended that you gave them steps to reproduce the error, and the error itself. 

Thanks.
