### ISSUE TITLE
Text editor element text color not working

### ISSUE THREAD

**Issue by DesignInvento** [elementor/elementor#14219]
Hi Guys,
There is fix required for default text editor element, right now colors are beings applied to parent rather than directly to the selected tag from editor. it would not work if theme has defined color for these tags, text editor styling should be applied on tag directly.

**Comment by shilo-ey** [comment]
Hi @DesignInvento 

Thanks for your feedback.

This is the normal behavior, because if you have a theme that sets design rules (style.css) to your site - it is the expected behavior.

Same for using the Theme Style in Elementor - control over non-elementor HTML elements.

Needless to say that a change like this will cause design alterations in many sites without the intention.

Either don't use the style provided by your theme or replace the specific css rule that overrides this setting.

Thanks

**Comment by DesignInvento** [comment]
No, i think you did not understand the point, page builder is mean to override theme's default styling, Otherwise there is no sense to use a page builder. 
Right now text editor element is not able to implement styling for editor tags if theme has defined default css for those tags e.g H tags and p tag. Problem is within text editor element because styling is not implemented on tag itself but parent.

**Comment by shilo-ey** [comment]
I understand, but this specificity is from day one of Elementor.
You can create an entire site without the need of a theme using Elementor.

If the theme conflicts or applies this setting - you can either switch theme or change the specific css rule.


Thank you
