### ISSUE TITLE
🕵️ 🐞 Form Submission is not GDPR friendly - [ED-14127]

### ISSUE THREAD

**Issue by tobias992** [elementor/elementor#14285]
Its very easy:

The new Form Submission feature is not GDPR friendly. It stores things like User-Agent and also the IP.
Maybe the Dev-Team can improve this.

**Comment by dtugend** [comment]
Another big problem is it's turned on by default currently and collects all forms by default.

Since it contains custom messages: potentially a notable GDPR violation regardless of the IP / User-Agent problem for website owners that have EU visitors / customers submitting forms storing them in a website database.

Suggestion: Make a one-time admin notification (fresh install or not decided yet) to ask them if to turn it on and it should be off by default for new installs.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.22.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
