### ISSUE TITLE
✔️ 🐞 Bug Report: Optimized DOM Output -> Removal of .elementor-row -> Columns Gap Issues

### ISSUE THREAD

**Issue by JoeHana** [elementor/elementor#14286]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Creating layouts with Elementor has always been quite a difficult task. Surely, adding sections and columns is obviously easy and filling them with content is even easier. The difficulty starts when it comes to the alignments. Having multiple sections over one page, you end up using different column gaps for them as well. The problem is: Using different column gaps will mis-align the whole page layout - see this screenshot.

![Layout Test __ K](https://user-images.githubusercontent.com/122551/111701099-9b4e1b00-883a-11eb-9b52-4eacf32ebeb2.png)

The black border is basically applied on the column itself. Within each column I'm having a heading widget with text and applied a blue background to it to better visualize this issue.

Since I'm using Elementor the Columns Alignment Fix for Elementor Plugin has been a great help since it simply does what is needed to have good looking layouts while still enabling us the freedom to use different column gaps on various sections.

However, with the latest improvments in regards to the Optimized DOM Output and the removal of the .elementor-row - this does not work anymore and it seems like there is nothing to fix this since the columns gap class gets applied to the elementor-container which is set to margin: auto. Applying negative margins to this container will basically bust the whole layout since it overwrites the margin: auto which is responsible to center the container within the section.

I tried various possible solutions but none of them very really satisfying. Perhaps I oversee something - in which case I'd be grateful to get pointed in the right direction but overall I'm pretty skeptical if the removal of the .elementor-row  is a good idea.

**Comment by Webtica** [comment]
+1 Following this

**Comment by black-eye** [comment]
+1000
Thanks for bringing this issue back to the attention.

The column gap issue is here literally since the very beginning of Elementor itself. More specifically since Aug 2016 (https://github.com/elementor/elementor/issues/452)!!! And since then, there are no signs of the will for fixing it.

As you mentioned, the saddest thing is, that in version 3.0 it got even worse with optimized DOM, where .elementor-row has been removed and thus ruined the only possible hack to repair this issue. And developers cannot say, they were not aware of this situation, as it was reported in the thread several times, starting this comment: https://github.com/elementor/elementor/issues/452#issuecomment-662486644_

At least there is a legacy mode for the DOM, but I would really like to make use of the DOM reduction too.

There are several solution to it:
1. Elementor has to fix this problem in the core (no real hope for it, since it wasn't fixed after almost 5 years)
2. Add an option for _Optimized DOM "Light"_ with .elementor-row preserved. (As an extra option, original Optimized DOM would stay the same.)
3. CSS Grid??? It would be about time - Oxygen, your possibly biggest competitor, already has it.

Please fix this problem and make Elementor real pixel perfect design tool! Thanks

**Comment by cbwstudios** [comment]
I find it truly boggling that the Elementor team has not solved this problem to date.  I build hundreds of sites per year.  This is the biggest issue I ALWAYS HAVE with Elementor.  Until they address this issue Elementor will continue to play second fiddle to Oxygen and WIX.

**Comment by nicholaszein** [comment]
Hello @JoeHana, @Webtica, @cbwstudios, and @black-eye!

### 📢 We're happy to announce that the issue you raised can now be solved by using the Flexbox Container experiment that is now stable in Elementor **v3.8**! 🥳 

With the full power of CSS Flexbox, you can now easily align your containers correctly without having to resource to custom CSS or 3rd party plugins. I encourage you to check it out and update your plugin to the new version!

Thank you for being so patient! 🙏 

Cheers 🥂
