### ISSUE TITLE
📣 Elementor Hello Theme v2.4 Beta Release 📣

### ISSUE THREAD

**Issue by shilo-ey** [elementor/elementor#14283]
Hi Elementor Beta testers,

We introduced our Hello theme to provide web-creators with a conflict-free, and fast website creation process, coupled with Elementor of course. 

To provide you with more flexibility and professionalism when building your sites, we are introducing a new header and footer functionality everyone can enjoy! 
Up until today, you could not design and customize your header or edit your footer with Hello Theme. Those days are over.

Users who use Elementor in combination with Hello theme now can do just that. We're giving you additional design possibilities and control when using the Elementor Hello theme. You can add a customized header and footer to your site faster than ever!
 
Test out the new Header & Footer design capabilities in Hello theme and let us know what you think about the new capabilities we added.
 
**Below are the main topics we will cover in this post:** 
 
- Set your Header & Footer layouts
- Appearance modification options
- How will this impact new vs. existing sites?
- How does this work with Elementor Pro’s Theme Builder?
- Effect on Hello Theme’s performance

![Hello](https://user-images.githubusercontent.com/45009641/111670677-c3c91b80-8820-11eb-90cf-cf013a4fe1a2.png)

**Comment by fabianenzensperger** [comment]
Hi @shilo-ey ... My thoughts on this are there under the beta post:

https://github.com/elementor/hello-theme/issues/150#issuecomment-802324781

**Comment by maurocarreraok** [comment]
**"The addition of a header/footer functionality to Hello Theme will not negatively affect Elementor Pro users or hurt the performance of the theme! There will be no change to your existing sites unless you opt-in via the Site Settings. This is an optional feature which can be turned on and off."**

Now we are talking!

Well done.-

**Comment by fabianenzensperger** [comment]
> **"The addition of a header/footer functionality to Hello Theme will not negatively affect Elementor Pro users or hurt the performance of the theme! There will be no change to your existing sites unless you opt-in via the Site Settings. This is an optional feature which can be turned on and off."**
> 
> Now we are talking!
> 
> Well done.-


Nah, not really. It is incomprehensible and absolutely the opposite of what Elementor is all about. I don't think there are two opinions here as you can read in the beta thread. 😉

**Comment by julien-paris** [comment]
Elementor just raised a lot of money, is currently running a pretty massive advertising campaign with multiple creatives, and has clearly set out to take on Wix, VC, and all the new turnkey website solutions. They are aggressively out to protect and expand their market share. Not only within the WP ecosystem, but expanding beyond that. 
Making it easy to create a header/footer makes sense in that environment. 

That being said, as an advanced user, I also find it to be a very odd allocation of ressources. I am here now because I'm reporting a bug which is pretty serious. And seeing this kind of announcement kind of makes you wonder if priorities are straight, with close to 2k open issues he in github -- a good deal of them being legit issues. 

In Elementor's CTO's shoes, I'd be very, very cautious about keeping priorities straight. And I whole heartedly agree that this new Hello feature sounds like someone at Elementor is not thinking straight.

**Comment by 79ho3ein** [comment]
Hi
Please add an option to display WooCommerce notifications with elementor pop-up.
This option can be great for a site designed with zero to one hundred elementor.
Currently elementor desperately needs this option.
Please share your opinion on this.

Thanks

**Comment by alexcumbers** [comment]
is there another beta coming or will this be released out of beta soon?

**Comment by fabianenzensperger** [comment]
> is there another beta coming or will this be released out of beta soon?


I hope that Hello 2.4 will never come in this form. 😅

**Comment by alexcumbers** [comment]
> Elementor just raised a lot of money, is currently running a pretty massive advertising campaign with multiple creatives, and has clearly set out to take on Wix, VC, and all the new turnkey website solutions. They are aggressively out to protect and expand their market share. Not only within the WP ecosystem, but expanding beyond that.
> Making it easy to create a header/footer makes sense in that environment.
> 
> That being said, as an advanced user, I also find it to be a very odd allocation of ressources. I am here now because I'm reporting a bug which is pretty serious. And seeing this kind of announcement kind of makes you wonder if priorities are straight, with close to 2k open issues he in github -- a good deal of them being legit issues.
> 
> In Elementor's CTO's shoes, I'd be very, very cautious about keeping priorities straight. And I whole heartedly agree that this new Hello feature sounds like someone at Elementor is not thinking straight.

Yes, it concerns me that many issues have no tag, so you're left to wonder if they've been considered at all.

**Comment by DavidGMiles** [comment]
> > Elementor just raised a lot of money, is currently running a pretty massive advertising campaign with multiple creatives, and has clearly set out to take on Wix, VC, and all the new turnkey website solutions. They are aggressively out to protect and expand their market share. Not only within the WP ecosystem, but expanding beyond that.
> > Making it easy to create a header/footer makes sense in that environment.
> > That being said, as an advanced user, I also find it to be a very odd allocation of ressources. I am here now because I'm reporting a bug which is pretty serious. And seeing this kind of announcement kind of makes you wonder if priorities are straight, with close to 2k open issues he in github -- a good deal of them being legit issues.
> > In Elementor's CTO's shoes, I'd be very, very cautious about keeping priorities straight. And I whole heartedly agree that this new Hello feature sounds like someone at Elementor is not thinking straight.
> 
> Yes, it concerns me that many issues have no tag, so you're left to wonder if they've been considered at all.

I don’t think that they have - Some big issues are totally Ignored

**Comment by alexcumbers** [comment]
Perhaps Elementor need to commit to either tagging all entries or closing them, so that we know the state of every issue.

Perhaps go back 3 months, and comment that they will close all issues older than this *unless* people comment that it is still an issue?

Feature requests should *not* be made in the issues list, it’s polluting that list, and people should create issues with effective titles, complete description and better still a video demoing the issue (e.g: use loom.com <http://loom.com/>)

Product Board is a good service for managing / commenting / voting on feature requests.

**Comment by alexcumbers** [comment]
@shilo-ey  any comments?

**Comment by DavidGMiles** [comment]
_Perhaps go back 3 months, and comment that they will close all issues older than this *unless* people comment that it is still an issue?_

It is taking over 4 weeks for them to even look at an issue - despite repeated prompting about it - its pretty poor

**Comment by shilo-ey** [comment]
We are working on improving this version based on the feedback given.

We will update once the changes are implemented.

Please keep comments in the original issue only.

Thank you

**Comment by shilo-ey** [comment]
Hey all,

This version is now live

Feel free to update!
