### ISSUE TITLE
⛔ Multiple Image Carousels are not working on Single Page.

### ISSUE THREAD

**Issue by hemanttejwani2610** [elementor/elementor#14360]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When Elemntor > Settings > Experiments > Improved Asset Loading is Active:
   Then multiple Image Carousels are not working. For example, I have added only one Image Carousel then it's working fine.
   But If I add two or more Image Carousels on a single page then all carousels will stop working.

**Error Message:**
`Uncaught (in promise) TypeError: Cannot read property 'prototype' of undefined
    at SwiperBC.createSwiperInstance (frontend.js?ver=3.2.0-beta1:3802)
    at frontend.js?ver=3.2.0-beta1:3786`

## Steps to reproduce

Edit a page with Elementor and add two or more Image Carousel widgets, save it and then check it on the frontend.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by asrour1** [comment]
+1

**Comment by nicholaszein** [comment]
Hello @hemanttejwani2610 and @asrour1!

Thank you for your contribution, and apologies for the delay in the response. 🙏 

Since this issue was submitted, a lot has changed, including fixes and improvements to the Improved Asset Loading feature, which is now permanent and integral part of Elementor.

While testing the reported issue here, we were able to load multiple Image Carousel widgets (more than 50) in a single page without any problems. Therefore we consider this issue as solved.

Thank you again for reporting this issue, and for being so patient! 🙏 

I'm closing this issue.

If you are still experiencing this issue and still think it's a bug, please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Kind regards
