### ISSUE TITLE
Elementor Editor not opening after update

### ISSUE THREAD

**Issue by H3npi** [elementor/elementor#14384]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I updated a blog from a really old version (2.8.3) to 3.1.4.
After updating i found out that the editor does not open and just shows the grey page.
Investigating the developer console i found the following error:

```
[Error] {message: "The string did not match the expected pattern.", code: 12, data: []}
consoleError (common.min.js:2:114887)
notify (editor-document.min.js:2:238852)
onCatchApply (editor-document.min.js:2:230456)
onCatchApply
promiseReactionJob
[Error] SyntaxError: The string did not match the expected pattern.
consoleError (common.min.js:2:114887)
onCatchApply (editor.min.js:2:414517)
onCatchApply
promiseReactionJob
[Error] Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.
(anonyme Funktion)
promiseReactionJob
```

So i tried save mode, did not work. Disabled every plugin beside elementor, did not work.
I switched the theme to "hello elementor" and it worked.
Then i digged into the current theme (child theme of hello-elementor) and found out that when i remove everything from the `functions.php` the editor loads again.
I went through the file and tried to find the issue, but couldn't find it. Sadly the error message in the developer console does not help either.

After contacting the support via email `support@elementor.com` i was told to open an issue here.

Do you have any idea how we can pin-point the issue?

When needed we can provide the `functions.php` via email.

## Steps to reproduce

- install custom child theme for `hello-elementor`
- update to elementor 3.x
- try to open elementor editor

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
[https://pastebin.com/ThHfnNtz](https://pastebin.com/ThHfnNtz)
</details>

**Comment by Jonathlee** [comment]
This is one of the common issue especially in version 2 to version 3 due to your web browser may have cached old scripts (including editor)

1. Best way is to clear cache (low chance of fixing this depends on browsers cache)
2. Login and open the editor using other web browsers (plus may clear cache, may use Microsoft Edge)
3. Use Incognito or Private Browsing mode to disable the cache saving

**Comment by H3npi** [comment]
Hi @Jonathlee,

thanks for the fast feedback.
Sadly I guess there is no caching Issue, because we cleared server and browser cache while testing.
We also tried a new installed browser just to make sure there is no caching issue.

**Comment by shilo-ey** [comment]
Hi @H3npi 

Thanks for contacting us.

It is clearly an issue with the customized child theme.

We only support the official Hello child theme: https://github.com/elementor/hello-theme-child

Please use it and this way you will avoid the problem, otherwise - contact the custom child theme author.

Thanks
