### ISSUE TITLE
Broken Media Carousel for desktop

### ISSUE THREAD

**Issue by jirkalukas** [elementor/elementor#14394]
Hello, 

I am using the newest updates of  Elementor Pro and Elementor and WordPress 5.7. After I deactivated all plugins except Elementor Pro and Elementor and also I used the theme Twenty Twenty-One the bug was still there you can see it on the link here:

Link: https://www.vegfit.cz/media-carousel/

PROBLEM: Two effects are initiated simultaneously I think 1. CAROUSEL and also 2. FADE ----- it is visible only on desktop view.

And it must be caused by the newest ELEMENTOR/ ELEMENTOR PRO updates because I tried the older version and the problem is not appearing there...

Please can you fix it because it has to affect ALL YOUR PAYING USERS? 

Regards,
Jiří Lukáš

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.

In the link above I didn't found any carousel, so it is hard to understand exactly what the problem is. 
**Since you are a Pro user, you are welcome to contact our support team and they will help you**  


Thanks.
