### ISSUE TITLE
Flicking popup in the exit animation.

### ISSUE THREAD

**Issue by ofmarconi** [elementor/elementor#14459]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello I already use elementor on several sites and I always had this problem with the popup output animation: https://youtu.be/zjqSMh9bygQ

It doesn't always happen, I had to try it 10 times to be able to record this one.

It looks like the animation ends before the popup actually disappears ...

## Steps to reproduce

I had to try it several times, but with chrome inspection tool I got it more often.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by riadcitaku** [comment]
@shilo-ey the issue still persists.

**Comment by riadcitaku** [comment]
@ofmarconi I guess I've found the solution, I am testing in multiple devices no issues till now.

Elementor did not create further animations for the exit option, only reversing the existing ones. So, when the reversing is done the animation goes back to the normal position for a millisecond (0% of keyframe) because of the animation-fill-mode.

Click in the 'forwards' option and you'll spot the difference: https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode


```
.animated.reverse {
   animation-fill-mode: forwards;
}
```

**Comment by ofmarconi** [comment]
@riadcitaku Very good!

It makes perfect sense! I will test on my sites too! Thank you very much!

I hope the @elementorbot developers see this.

**Comment by ofmarconi** [comment]
Helo @riadcitaku !

Could this CSS be causing these crashes in my animations?
https://imgur.com/a/wZsS13F


> ```
> .animated.reverse {
>    animation-fill-mode: forwards;
> }
> ```

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.3.0

Feel free to update

Thanks!
