### ISSUE TITLE
Custom Code Bug Report

### ISSUE THREAD

**Issue by shay1383** [elementor/elementor#14515]
Whenever I add custom scripts (JS, src, and etc. using the proper start and closing), it seems that the code only works when viewing a page as an admin. And when viewing as a guest from another browser/device, code doesn't appear/apply.

I was able to regenerate the issue on multiple new WordPress installations

The code I tried to implement using Custom Code:
https://github.com/alvarotrigo/fullPage.js/

**Comment by euene** [comment]
If you're using any jQuery/$ in your custom code, it will only work for admins or users that are logged in.
This is because jQuery is loaded in `<head>` when logged in, but loaded at the end of `<body>` for users that aren't logged in.

Elementor has an issue that still hasn't been solved where it lacks high enough priority to print code after jQuery loaded by WordPress core - #14266

So if this is your issue - you may need to rewrite your jQuery code to pure JS or wait for Elementor developers to fix this issue (which may not happen anytime soon if following their track record).

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.5.0

Feel free to update

Thanks!
