### ISSUE TITLE
Please add a feature so that we can dynamically link widgets such as buttons, etc. to tabs.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14669]
Now if http changes to https, all previous http links will be. But if you add this feature, they will change automatically. This would be great.

**Comment by avivu** [comment]
hello @79ho3ein,
Can you please add more details for your suggestion?

**Comment by d19dotca** [comment]
You can always use relative URLs to avoid any HTTP(S) protocol changes completely. Also Elementor offers Internal URL as a dynamic field option which is supposed to take care of any slug changes and things like that since it'll point to the post ID instead internally which never changes. Maybe those two options may help.

**Comment by 79ho3ein** [comment]
hello @avivu 
I checked and realized that this is possible now
I close this request to prevent any additional requests in GitHub.

With thanks for your attention.
