### ISSUE TITLE
Add Title for icon list widget

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#14696]
Hello, sometimes I need to add an icon list with a title for compare block. If I use the inner section with 2 title widgets and 2 icon lists I create more code. I try to adapted table price but the header not setting for alignment. I try to design this block 
![image](https://user-images.githubusercontent.com/66754335/115997561-282f8580-a5ec-11eb-8862-f1455c3f6fe0.png)

**Comment by DorShahar** [comment]
Hi @promocot 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

With that being said, we are constantly working on [removing more DOM Elements ](https://elementor.com/help/what-is-the-optimized-dom/) so building this kind of layout shouldn't worry you in the future. 

We will be glad if you could work with that experiment and let us know if there are any problems. 

Thank you for your understanding.
