### ISSUE TITLE
PHP Deprecated:  Elementor\Scheme_Color is <strong>deprecated</strong> since version 2.8.0! Use Elementor\Core\Schemes\Color instead.

### ISSUE THREAD

**Issue by Justin704** [elementor/elementor#14699]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by d19dotca** [comment]
There's no information in here at all to really help, but I believe you're referring to an issue that has already been filed and was due to third-party plugins: https://github.com/elementor/elementor/issues/14656 - So I'd recommend disabling your other plugins temporarily and see if the issue still occurs. Also update the other issue I linked you to, this one should be closed as a duplicate.

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

Without it we simply can't help.

Thanks.
