### ISSUE TITLE
3.3.0-dev4 - Feedbacks

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#14868]
Template Library :
* * First, be sure to remove the "Go Pro" button at the bottom of the template capture on the fly. And at the top left when you land on the template viewing page for users who already have the Pro version activated.
* Template viewing does not work
* I suppose that other improvements are already in work.

Loading of widgets CSS : nothing to report

Eye dropper :
* first, when I select a widget with the selector (in my case an image), if there is an activated link, I am redirected to the page of the site to which the link points without leaving my front end editor
* finally, I have the impression that I can only select colors in the heading and images widgets.

**Comment by dtbaker** [comment]
I think you may have missed some files in the release?

e.g. this is the dev4 export code:

https://github.com/elementor/elementor/blob/v3.3.0-dev4/core/app/modules/import-export/module.php#L157-L173

however this is the latest master branch code:

https://github.com/elementor/elementor/blob/master/core/app/modules/import-export/module.php#L57-L91

The export process doesn't run at all because it's missing some front end query params and it just returns a json success blob

**Comment by d19dotca** [comment]
Yes, the eye dropper didn't work too well for me either in my testing today. Same issue as you had, where clicking on a button with the eye dropper active would just take me to the linked page instead. Additionally, it seemed like it couldn't load all the colours for some reason. It loaded all colours for a designed page from the Elementor Template library, but not some of the Elementor widgets from my design which existed prior to activating that experiment. Unsure if that's because it doesn't work well until things are loaded after the experiment is enabled rather than what existed before it, but it didn't seem to reliable in my testing, unfortunately.

**Comment by rodolphebertozzo** [comment]
Okay, so there is a problem when links are assigned to elements. And indeed, it doesn't work optimally with all widgets.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.3.0

Feel free to update

Thanks!
