### ISSUE TITLE
Facebook Icon Issue

### ISSUE THREAD

**Issue by FauzanEdris** [elementor/elementor#14918]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

This issue occurs when working with Font Awesome version 4 and below. The Facebook icon will become a square (no icon). This issue was caused by writing incorrect Unicode FA (Font Awesome).
![result](https://user-images.githubusercontent.com/30016486/117983923-f6e3e300-b369-11eb-9bb2-14ac74f495fb.png)

## Steps to reproduce
- The simple way is to use a Theme that works with Font Awesome 4 as the base icon.
- `Load Font Awesome 4 Support` is Enabled
![Load Font Awesome 4 Support is Enabled](https://user-images.githubusercontent.com/30016486/117983874-ecc1e480-b369-11eb-95d3-9f15b16fe70a.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

- FontAwesome 4

**Comment by arielk** [comment]
HI @FauzanEdris,  

Sorry for the late replay,

I just checked your PR and if I change your code, the icon will have a circle instead of just an F:

<img width="103" alt="image" src="https://user-images.githubusercontent.com/1778512/187596894-48518248-daae-4a07-8f2b-4adf62d7d52e.png">

We work with the Font Awesome guidelines, so if you see something wrong in this case, you should change it in the Font Awesome library: https://github.com/FortAwesome/Font-Awesome/blob/5.x/css/v4-shims.css

Thanks for you feedback.

**Comment by FauzanEdris** [comment]
Hi @arielk,

Thanks for the reply, I think the team has done the custom code before. I'll try to reach the FontAwesome team on this issue.
