### ISSUE TITLE
Responsive issues near breakepoints

### ISSUE THREAD

**Issue by webmaster-adcom** [elementor/elementor#15082]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I report this bug [here](https://github.com/elementor/elementor/issues/14968), but you closed it. Please read it first it is a big issue for elementor.
I used elementor default settings so nothings is changed from my side. The default breakepoints for the tablet and mobile are 1025px and 767px but at the two exact width of the windows 1025px and 767px the responsivity is not working.  With google chrome at the 1025px width the responsivity is ok but with firefox not. The issue is same for both of chrome and firefox at 767px width of windows. 
In the image i upload it below, I have two menu in footer. They are the same, but one of them(number 2 in blue) must be shown in desktop and tablet and the other(number 3 in blue) must be shown in the mobile. I used responsive option in the advanced menu of these elements to make them visible or hidden. But you can see at the exact 767px width of windows(number 1 in blue) this hidden option is not working and i can see both of these elements. If i change the width of windows to the 766px or 768px, it is fine.

![1](https://user-images.githubusercontent.com/84316503/119482932-bb2b1f00-bd54-11eb-91d7-a897f28fc328.PNG)

## Steps to reproduce

1. Create one element and then duplicate it
2. Select the first element then Advanced->Responsive->turn on Hide on Mobile
3. Select the second element then Advanced->Responsive->turn on Hide on Desktop and Hide on Tablet![2](https://user-images.githubusercontent.com/84316503/119485805-d0ee1380-bd57-11eb-862f-7252bc92ce9e.PNG)
4. Publish the page
5. Visit the page and use browser inspection tool
6. Make the width of the windows 767px
7. Both elements are shown

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
https://pastebin.com/rfxcfxp2
</details>

**Comment by JeroenvanderPoll** [comment]
Hi, this is due to the scaling settings of your OS. I have the same thing. If WIndows is not scaled to 100% the issue appears with every breakpoint. Going a px under or over and the issue is gone. See: https://github.com/elementor/elementor/issues/5221

I got a response from Elementor. No fix soon

_Regarding the issue here, I want to share with you that we are aware
of this issue regarding the 1px gap in breakpoints, most times when
using the responsive visibility feature to hide/show elements on the
mobile/tablet/desktop view.

As fixing these glitches requires core code changes, it will take some
time to ensure that fixing this particular glitch does not affect
other areas of Elementor. Regrettably, I won't be able to provide you
with an ETA for a resolution of this issue, but once the fix is
released we will update it on our changelog page: Changelog of
Elementor_

**Comment by theavic** [comment]
Is there an update on this issue, since it still appears to be reoccuring

**Comment by daniniko** [comment]
Almost 5 years later, is there an update? Still not fixed
