### ISSUE TITLE
Site Settings typography does not have a section for captions, please add one

### ISSUE THREAD

**Issue by Moonwards** [elementor/elementor#15103]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
If Site Settings is used to set colors and styles across the website, it can't be used to do that for captions. Image captions will take the color and style of body text, and each caption has to be set by hand if a different color or style is desired

**Describe the solution you'd like**
Please add a section to Site Settings Typography where default values can be set for captions.

**Describe alternatives you've considered**
They can be set by hand only.

**Additional context**
Nope.

**Comment by DorShahar** [comment]
Hi 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

As you know - caption could use global fonts, and you can create a specific one for Caption, which can answer your need in the meantime. 

Thank you for your understanding.
