### ISSUE TITLE
🔥Request for future update of hello elementor theme. Elementor developers please check🔥

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15109]
@shilo-ey 
Apparently elementor intends to update the hello template. And it wants to add a new header and footer section.
In my opinion and that of most elementor users, this feature (new heaser & footer) is not required at all and gives the opposite result.
elementor pro largely meets our need for header and footer design. So why add it in hello format?
I think what's needing too much elementor is optimizing the template code. Please do not confuse us by adding additional features.
If you look at the beta version of hello elementor (https://github.com/elementor/hello-theme/issues/150) , you will see that many users are unhappy with this update.
Certainly the opinion of users is very important for elementor. I hope elementor stops publishing header and footer capabilities. And focus on more important things like optimization.
We all strive to improve the elementor plugin. And I hope we are all finally satisfied.
**I hope elementor responds to this request.**

Thanks to the elementor team

**Comment by d19dotca** [comment]
This should be discussed in the thread you referenced already and were participating in earlier today. The Hello Theme is not the same as the Elementor product, thus it has it's own repository in GitHub. Discussions on Hello Theme should be done in the Hello Theme repository.

**Comment by 79ho3ein** [comment]
Can you send the link? thanks

**Comment by d19dotca** [comment]
You already referenced it, lol. https://github.com/elementor/hello-theme/issues/150

If you notice, that post is in the Hello Theme repository which is separate from the Elementor repository (because they are different products). If you need to open your own dialogue on the Hello Theme, then it'd be better to take it up in the appropriate thread (which already exists) or if you must then create a new post in the Hello Theme repository instead of the Elementor repository. In my opinion, this post should be closed as it's not the appropriate place for it.

**Comment by 79ho3ein** [comment]
Yes thank you.
