### ISSUE TITLE
CSS selector not working at single sites in combination with icon elements

### ISSUE THREAD

**Issue by Flake-Webagentur** [elementor/elementor#15222]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description

**At single posts sites** the css selector for icon elements works perfect. 
For Example: https://webagentur-flake.de/2021/06/01/facebook/
The arrow is moving like the GIF is shown.
![2021-06-06_10h52_41](https://user-images.githubusercontent.com/78703171/120918608-7dfc5080-c6b5-11eb-9c1e-3ac789e35e32.gif)

**Code for CSS:** `selector{-webkit-animation: scrolling 3s ease infinite;-moz-animation: scrolling 3s ease infinite;-o-animation: scrolling 3s  ease infinite;animation: scrolling 3s ease infinite;}
@keyframes scrolling {
  0% {transform: translate(0);}
  50% {transform: translate(0,40px);}
  100% {transform: translate(0);}}
`

**At single sites** the same element with the same code doesnt work.
As example see: https://webagentur-flake.de/

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

	Elementor
		Version: 3.2.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.2
		Author: Elementor.com
					
</details>

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

Since you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
