### ISSUE TITLE
Columns Background images not loading

### ISSUE THREAD

**Issue by bodhi1970** [elementor/elementor#15243]
The background images of Elementor columns are not loading.
Not worked before and after updating to latest version.
It only works if scroll effects are turned off.
![Screenshot 2021-06-07 at 15 45 44](https://user-images.githubusercontent.com/5292941/121027673-71f0bb80-c7a7-11eb-862b-be2b5255e542.png)

**Comment by Aviad-Herman** [comment]
Hey, 
I was not able to reproduce your bug locally.
Please add exact steps to reproduce your bug, a video will be great (loom is a great tool for this).

I advise trying to disable all other plugins and using elementor hello theme or a WP default theme to make sure the problem is really with Elementor and not something else.

**Comment by bodhi1970** [comment]
Hi
I have recorded this little screen video:
https://sternen1713.ch/videos/Screen%20Recording%202021-06-16%20at%2012.14.47.mov

**Comment by mikmanic** [comment]
It works if i add spacer in the column and reload the page. With empty column i'm getting the same problem - background image disappears. With empty column the markup seems to be incomplete: 
![Screenshot 2021-06-28 at 10 49 33](https://user-images.githubusercontent.com/3008732/123599807-ad0e6980-d7fe-11eb-96a7-62d9dd344758.png)

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
