### ISSUE TITLE
🔥Please add the number entry feature to the icon list widget.Important request

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#15264]
It would be great if we could insert a number in addition to the icon in the icon list widget.
This image is for the power pack plugin icon list widget : https://prnt.sc/14pioe2
As you can see in the image above, it is possible to insert a number in addition to the icon, which is very useful.
For example, I have chosen to insert a number so that I can enter the desired number to display.
And you see the result : https://prnt.sc/14pjoq0
I also had another request (#14700) regarding this widget which is very necessary to complete this widget.
Please check this feature and add it to elementor if possible. This feature is extremely important and necessary.

thanks

**Comment by d19dotca** [comment]
Unrelated side note, but I'm not certain how to inform you of this outside of these tickets... 

I've noticed you've filed 94 "issues" (mostly feature requests) in the Elementor repository in just the last 3 or so months. That's a lot! And almost all of them seems to end with "Very important", or "Please look", or "Please review", or "Important request". These words seem superfluous and unnecessary, in my opinion. It may be better to just keep the title lean and clean and then call out how important it is to you in the actual body of the message. 

Also, almost all of the issues you've filed don't follow the recommended template that Elementor team prefers and provides users when creating a "new issue", and I've seen many of your items get marked closed as a result of not following the recommendations or missing critical information. I will be honest and say I don't love all the ideas you've presented, but I definitely think some of your ideas are good and worth supporting and I would hate for them to get missed or closed prematurely because of technical/procedural issues. So please follow the templates that Elementor recommends - it makes it much easier for people to view and follow, and also makes it harder to be marked closed. 

Take it for what you will, it's just my two cents after all, but I want to ensure your good ideas are kept around longer and actually properly reviewed by both the Elementor team and power users like me, and make them better understood by everyone who will then have an easier time upvoting your feature requests so they can gain traction and attention by the developers. It's all around better for everyone, in my opinion. Not meaning to be rude or anything, just trying to help get you on the right track for filing feature requests properly. 😇

**Comment by DorShahar** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Description and examples.
* One request per thread

In addition to what @d19dotca  said, we would love to understand the motive for your request. We had a lot of requests we need to prioritze among our users. Without this information, we cannot take the right decision.
 
Thanks.
