### ISSUE TITLE
Poor UX of Elmentor while adding widgets

### ISSUE THREAD

**Issue by vkassingh** [elementor/elementor#15417]
**What problem is your feature request going to solve? Please describe.**
The widgets have no proper description that what you can do style, Advanced or general etc. This wastes a lot of time of the users while switching to different sections. They have to scroll down and read the sections completely which lead to a lot of frustration.

**Describe the solution you'd like**
My solution will definitely improve  the User Experience and help in increasing customers and user number of Elementor.

**Describe alternatives you've considered**
Under all the widget section , add a small description of what the user can do in the style, advanced etc. sections. So that by just reading they can switch to the respective section. 

**Additional context**
![Elementor](https://user-images.githubusercontent.com/42089632/122674703-f86bbb00-d1f3-11eb-989c-664483065dbb.JPG)

**Comment by vkassingh** [comment]
@drawcard  i would like to work on this issue? can i start working on it?

**Comment by drawcard** [comment]
Did you tag me by mistake? 

It looks like you're using a third party widget in your screenshot. You should chat to the plugin developer to see if that can add that for you.

Off the top of my head I can't think of a native Elementor widget that has an empty panel and would require a message like that, I might be wrong though. There is also a "Help?" link at the bottom of the panel where users can learn more about what to do in each of these panels.

**Comment by d19dotca** [comment]
For what it's worth, in 3.4.0 currently being developed, there is a new "search" function in each widget to quickly find the setting you're looking for without needing to know what tab its on for example. This may help improve that UX. But like @drawcard said, your screenshot isn't from a native Elementor widget so it's unclear if what you're wanting is to do with Elementor itself or only affects third-party widgets.

**Comment by Aviad-Herman** [comment]
Hey,
I took note of your suggestions.
There is definitely a learning curve when starting to use Elementor.
After a while things become a little more intuitive.

The Advanced tab remains mostly the same for all widgets.
Style is for, well, css styles
and Content is everything else. Usually related to the structure and functionality of the widget

BTW the control search will not be released in 3.4.0 because we didn't crack the correct UX yet

If anyone wants to schedule a 1x1 feell free to do that here:
https://calendly.com/aviadh/feedback-session-with-elementor
