### ISSUE TITLE
Load google fonts directly from google

### ISSUE THREAD

**Issue by mushlih-almubarak** [elementor/elementor#15426]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**
I noticed that elementor stores google font files on the server, and doesn't fetch them directly from google.
I want elementor not to save the file on the server because it will burden the server, it's best to serve fonts directly from the google font site

**Describe alternatives you've considered**

**Additional context**

**Comment by d19dotca** [comment]
Do you mean it stores Google font files in your own web server, or do you mean it's calling an Elementor server they are hosting as a CDN? In my experience, the Google Fonts (WOFF2) files are all called from Google servers, so if you're seeing them elsewhere then I might suggest that's because of a performance optimization plugin in your site which hosts them locally instead for improved performance.

**Comment by mushlih-almubarak** [comment]
> Do you mean it stores Google font files in your own web server, or do you mean it's calling an Elementor server they are hosting as a CDN?

yes, what i mean is calling google font from google server.  Is that what Elementor is doing now?  and not save on our own server?

**Comment by d19dotca** [comment]
> Is that what Elementor is doing now?  and not save on our own server?

Correct, it is pulling from Google directly on each page load by default. I suspect if you're seeing it self-hosted then you've got another plug-in (there are many that do this) which hosts the fonts locally instead for improved performance.

**Comment by mushlih-almubarak** [comment]
Ok, thank you
