### ISSUE TITLE
Disable/Remove CSS

### ISSUE THREAD

**Issue by lagiulsss90** [elementor/elementor#15508]
Hi!

Anyone know how to disable or remove completely a specific elementor css file? 
It overrides my theme css even in the pages I'm not using Elementor. The solution I found for now is to block it with Asset CleanUp but I'm sure it can be done with a script in function.php file

Thank you

**Comment by Aviad-Herman** [comment]
Try checking these two boxes:
![image](https://user-images.githubusercontent.com/73067562/123989622-bc91dc00-d9d1-11eb-8152-f55421ab66ce.png)

Also, if you can provide specific screenshots and examples that would be great.

**Comment by lagiulsss90** [comment]
I already ticked the boxes..

This is the page with Elementor CSS:
[https://www.dropbox.com/s/xev219nayi7263t/with-elementor.JPG?dl=0](url)

This is the page with the css disabled:
[https://www.dropbox.com/s/fad145zgmt9g94k/without-elementor.JPG?dl=0](url)

**Comment by Aviad-Herman** [comment]
OK the images are very helpful.
We need some more info to help you debug this.

You said the page is NOT edited with Elementor?
Does this happen also in new pages or only in the specific example you sent?
Does this problem still happen if you deactivate all plugins except Elementor? (Including cache plugins)

In any case, it would be much more effective to contact Elementor support because you can give them your site credentials and they can actually see what is going on.
