### ISSUE TITLE
Unable to create new templates/popups

### ISSUE THREAD

**Issue by EzooDeen** [elementor/elementor#15558]
Hi, I keep receiving this error when I want to create new templates/popups.
Here I attached the screenshot.

![Screenshot 2021-07-05 at 3 21 44 PM](https://user-images.githubusercontent.com/18120911/124433232-1a913b80-dda5-11eb-8544-792e3e3549cf.png)

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

Since you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
