### ISSUE TITLE
Image Carousel Centering and Masking Error

### ISSUE THREAD

**Issue by HMSuperGeek** [elementor/elementor#15668]
Please see the images below for examples of the errors that are effecting the Image Carousel Widget for Elementor.

In Elementor v2.9.2/Elementor Pro 2.8.3 Image Carousel is correct and as you can see, the image is centered and cropped by masking of the border.

![Screen Shot 2021-07-15 at 3 27 25 PM](https://user-images.githubusercontent.com/73197861/125846511-b25101e8-ad07-41b9-8bf0-a4b9feef91e9.png)

Below is Elementor v3.3.0/Elementor Pro 3.3.2 and now the current issue. The image is going off to the right and outside the mask. I deleted the Elementor post CSS in an effort to clear any formatting issues.

![Screen Shot 2021-07-15 at 3 28 46 PM](https://user-images.githubusercontent.com/73197861/125846501-176be519-787f-424a-b0fb-0d84ff406131.png)

I've managed to replace this widget with another third party plugin that restores the expected outcome. Again, there have been no major changes with the website other than updating versions of plugins and Wordpress.

https://prairiefossilmuseum.com/

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.

In case you have the Jetpack plugin, please deactivate it since at the moment they have a bug relates to this issue on their end, which can resolve the problem.

Thanks.

**Comment by ixns** [comment]
This problem is not solved DORSHAHAR
