### ISSUE TITLE
in elementor I'm having an error in the image carousel widget

### ISSUE THREAD

**Issue by zuhdi-in** [elementor/elementor#15682]
in elementor I'm having an error in the image carousel widget,
The error I experienced was that the distance between the images was too large even though I had reduced the distance to 0, besides that the "edit image carosel" section in the "slide to show" could not be adjusted accordingly, if I chose 3 or the other I would displayed, he still shows all his pictures

how to handle it ? please help

![Screenshot_52](https://user-images.githubusercontent.com/73019174/126038769-31ddc6e1-9884-4588-a858-c75d08c62ada.png)
![Screenshot_53](https://user-images.githubusercontent.com/73019174/126038771-66630201-4d8b-4ac6-8c3d-d31ce13088db.png)
![Screenshot_54](https://user-images.githubusercontent.com/73019174/126038814-9f0d3edd-b18a-4152-be82-cbec7e0ddc53.png)

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread

Without it, we simply can't help.
If you have the Jetpack plugin, please deactivate it since they have bug on their end. 

Thanks.
