### ISSUE TITLE
404 error on Elementor 3.3.0 with backend uploaded files

### ISSUE THREAD

**Issue by smythsys** [elementor/elementor#15703]
Elementor version 3.3.0 has a problem with files uploaded from the backend. At least with GeneratePress (we tested in 3 webs with GeneratePress but haven't yet tested with another theme).

When the permalink is set to post name (most common). Not with default settings (number).

The files uploaded via backed (pdf files, images) give a 404 if you try to access their post permalink (file url is ok).
Files uploaded on an article are fine (because the article Id was appended on the post permalink, at least in our files).

Reverting version to 3.2.5 makes everything work again.

Php versions tried 7.0, 7.2 and 7.4 , made no difference.

We know it is Elementor because:
        a) Deactivating all plugins except Elemetor causes the error. Deactivating ELementor made it work.
        b) Reverting the version makes it work.

**Comment by udidol** [comment]
Hi @smythsys,
Thank you for your report.
Could you provide some more details? 
Where exactly in the backend are you trying to upload files?

**Comment by jmanningppbh** [comment]
Hello - we are having the same issue.  The PDF files in our sites (which were in the media library already at the time of upgrade to elementor 3.3.0 / elementor pro 3.3.2) now show a 'page not found' when you use the 'view' link from the media library to try to open them.  I have deactivated all plugins and systematically re-activated them and I also think it's an elementor issue.  If I deactivate elementor & elem. pro then the permalinks and the view link work again.

As  @smythsys mentioned, if you attach the file to a post, the permalink works again.  But unattached pdfs are all showing a 404 error page.  I have tried this on 2 different elementor sites and the results are the same.

**Comment by smythsys** [comment]
> Hi @smythsys,
> Thank you for your report.
> Could you provide some more details?
> Where exactly in the backend are you trying to upload files?

Hi @shilo-ey  we are uploading them in the Media section. As I said if you upload them in an article it works. But not when it's uploaded through the Media section.
By the way, it still happens in Elementor 3.31.
If you upload the file, then go to "edit more details" so you see the permalink of the  media file, permalink doesn't work, url works.
If you disable elementor both work.

For example I've uploaded this file: https://www.smythsys.es/wordpress/wp-content/uploads/2021/07/elementorerror.png  This is the url which as you see works.
This is the permalink of the image, which doesn't work with Elementor on https://www.smythsys.es/elementorerror/ 
The screenshot is of a pdf which you can see doesn't work either.

**Comment by Morpheis83** [comment]
@smythsys 
I have the same probleme and I found the solution to resolve quickly :
==> You have to inactivate the experimental option OPTION : landingpage 
Elementor > Setting > Experience > (Set the landing page option to inactif cf. screenshots at the end of the post)

=================================================

@udidol  : 
- It's a real problem, when you have commit this source code==> https://github.com/elementor/elementor/pull/15221/files)
you have force the defaut value for the experimental option landing page to true.

In Fact, when an user try to access a page with the attribut post_type to "attachment".

------STACKTRACE------
**_Wordpress side_** 
01 --> wp-includes/class-wp-query.php line 1784 (in function get_posts) : Trigger  the hook 'pre_get_posts' in order to initialize the $q var to compute the SQL request for displaying the page

_**Plugin Elementor v3.3.0 side**_
02 --> elementor/modules/landing-pages/module.php line 420 (constructor function) : the wordpress hook 'pre_get_posts' is fired when the page is loaded and the function "adjust_landing_page_query" is called.

03 --> line 330 : in the function "adjust_landing_page_query" we initialize the var query_post_types  to an array that contains only ['post', 'page', 'e-landing']. There is no presence of 'attachment' post type, maybe a missing ???

**_Wordpress side_** 
04 --> wp-includes/class-wp-query.php line 1787 (in function get_posts) : the var $q['post_type'] is filled with the array ['post', 'page', e-landing']

05 --> wp-includes/class-wp-query.php line 1868 (in function get_posts) : $post_type = $q['post_type']; // array ['post', 'page', e-landing']

06 -->  wp-includes/class-wp-query.php line 2432 (in function get_posts) : Build the SQL request with "AND post_type IN ('post', 'page', e-landing')" ==> which return nothing because the post_type of this post in the data_base is set to 'attachment'. In this case, Wordpress dispatch the request to a 404 error.

======= Diff with 2.5.0 ======= 

**_Wordpress side_** 
In Fact the first step 
01 --> wp-includes/class-wp-query.php line 1784 (in function get_posts) : Trigger  the hook 'pre_get_posts' **is NEVER CALLED because the experimental e-landing option is inactive by default !!!**

02 --> wp-includes/class-wp-query.php line 1787 (in function get_posts) : the var $q['post_type'] is filled with nothing

03 --> wp-includes/class-wp-query.php line 2168 (in function get_posts) : the var $q['post_type'] is correctly filled with 'attachment'

06 -->  wp-includes/class-wp-query.php line 2438 (in function get_posts) : Build the correct SQL request and foudn the good item to display.


![screen1](https://user-images.githubusercontent.com/49004792/126447946-d3ef6668-c1d9-4801-97f2-6b1e3c36d8ca.jpg)
![screen2](https://user-images.githubusercontent.com/49004792/126447948-130d21c1-add7-41d3-96cc-4e6f348add2d.jpg)

**Comment by smythsys** [comment]
EXCELLENT @Morpheis83 !!!
That was the cause. 
Disabling the landing page solves the problem.
Many thanks.

**Comment by Morpheis83** [comment]
@smythsys 

You're welcome Man !! 

Now we have to wait the fix by the elementor team :D to re activate this option.

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!
