### ISSUE TITLE
Outdated jQuery function used

### ISSUE THREAD

**Issue by amindiary** [elementor/elementor#15813]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I've noticed this error
**plugins/elementor/assets/lib/tipsy/tipsy.min.js: jQuery.fn.live() is deprecated**

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by rami-elementor** [comment]
@amindiary 

This is a 3rd party plugin - https://github.com/jaz303/tipsy

You should report this over at tipsy repository.

**Comment by amindiary** [comment]
@rami-elementor if you don't have responsibility to fix bugs on that 3rd party plugin, then delete it from elementor please and use your own code. 

This is a plugin that elementor is using.

**Comment by amindiary** [comment]
Interesting...

@shilo-ey shilo-ey added the maintenance label on Aug 4, 2021



@rami-elementor closed this 1 hour ago

**Comment by rami-elementor** [comment]
Hi @temsool ,

First of all, thank you for taking the time reporting issues. Community and user involvement helps us improve the product.

As for this purpose of this GitHub repo, it is used for Elementor issues. The maintenance label can help us track external libraries, when they release new versions. But we are not responsible for those libraries and we can't change them locally for our internal use, because when the next version will be released, the changes we made locally will be overridden.

This is why I added the link to the original GitHub repo. It the original library will be fixed, Elementor will inherit those fixed the next time we update tipsy version.
