### ISSUE TITLE
Product Breaking Issue: Content Elements not editable if Table Of Contents is in use

### ISSUE THREAD

**Issue by Lampenbauer** [elementor/elementor#16013]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
The Table of Contents element somehow breaks the edit function of content elements. The issue appeared after updating Elementor und Elementor Pro.

## Steps to reproduce
https://www.youtube.com/watch?v=dLjxaLX6Uj0

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

Thanks.

**Comment by Lampenbauer** [comment]
Update: First I thought it has something to do with the Table of Contents element, but that’s not it. I can remove that element (and any other global widgets) from that page, save everything, reload the editor and it still isn’t working. Also unlinking global widgets isn’t working either. So what I was showing in the video isn’t working all the time. But maybe the errors in the console is helping you at least.
A workaround that always works and gives us the ability to edit all the content elements is by jumping between two revisions.
https://www.youtube.com/watch?v=kPDDcyo8xCM (watch with audio)

**Comment by Mal027** [comment]
For the last week and half, some pages have sections that are not editable. Right-clicking on any of the widgets, be it headings, images, text editor, etc just displays "Edit Section." 

As a solution, I have been duplicating the affected section, which allows me to edit it until I save and refresh. I need to do that every time I want to edit any content within that section. So far, about 15 of my pages are affected.
![image](https://user-images.githubusercontent.com/46428121/130162038-36c41963-a05e-41ab-a436-acfb80eb27a2.png)

**Comment by Lampenbauer** [comment]
@shilo-ey May I ask why this issue was closed? As it seems it's not just me.

**Comment by Lampenbauer** [comment]
We finally figured it out. On some pages we had the content element "Icon List" and "Meta Data" (both saved as a Global) in a section. All other content elements (not Globals) in that section became unresponsive. And those Globals never rendered in the editor. It was just a grey rectangle, not showing the content. As soon as we unlinked those two Globals, saved the page, reloaded it, the rest of the sections content elements became editable again. Reproducible. We unlinked all mentioned Globals on the pages that didn't worked in the editor after a recent Elementor update. Now we can edit them again.
But saving those two mentioned content elements as a new global, results in a non working section again.
@Mal027 Do you as well have Globals in those sections that aren't working for you?

**Comment by Mal027** [comment]
We have global widgets (Circle Menu, Help Desk, Scroll Up Button) in a section that are also behaving similarly to what you have described (globals not rendering visuals in the editor). The Circle Menu, Help Desk, and Table of Contents widgets seem to be causing this issue specifically where sections become uneditable - Scroll Up Button Globals seem to be fine.
![image](https://user-images.githubusercontent.com/46428121/131782240-c01c62aa-d294-489f-95fe-95211a0593a1.png)

Since our global widgets are featured on almost every page and are updated frequently, unlinking and readjusting is not an ideal solution for us at this time! The solution we have had in the meantime: 

1. Duplicate the impacted section. The duplicated section can be edited. 
2. Delete the original section. 
3. Add an empty inner section at the bottom of the page. 
4. Move the global widgets that are causing this issue to this section.
5. Save. 

Going forward, our pages have been editable and are working as normal so long as we have those global widgets in their own respective inner section. Scroll Up buttons also seem to render afterwards as well. 

![image](https://user-images.githubusercontent.com/46428121/131782767-78d18c76-ce83-4ff2-ae10-f463356ff06f.png)


@shilo-ey Could this be looked into further?
