### ISSUE TITLE
E 3.4.2 Incorrect styling in TOC and icons in Accordion

### ISSUE THREAD

**Issue by iStuff0** [elementor/elementor#16092]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Styling of TOC widget (heading, normal, hover, and active) are incorrect on the front end (fine on back end).

Icons in accordion widget no longer inherit colour of content. Style > Icon > colour settings also don't work. Again, this is on the front end. Everything is fine on back end. 

DOM, Asset, CSS, Font-Awesome, and accessibility experiments are inactive . 

## Steps to reproduce

No idea. I just installed the update and there they were.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

https://pastebin.com/Cis2Qe7F

**Comment by DorShahar** [comment]
Hi @iStuff0 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by MauriceW2** [comment]
I have the same problem. The first 3 items in the accordion look good on the front end. All other items are not styled properly. In the backend it looks good. Front end not. So it does NOT work properly and closing this issue because you cannot replicate it is really ridiculous. All plugins disabled, default theme, no conflicting code. Problem remains. I am a PRO user with 25 sites. I have this on 1 site (the only site where I use this widget).
