### ISSUE TITLE
⛔ 🐞 Empty page URL on form submit by spammers

### ISSUE THREAD

**Issue by iJorji** [elementor/elementor#16107]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Spammers have found a way to send spam without the URL in the form submission being filled in. It seems like they've found an non-existant form. My suggestion would be to not submit the form if the URL field is empty.

## Steps to reproduce

Cannot reproduce, do not know what it is that makes spammers do this. I've found people with the same issues on the community. For example: https://www.facebook.com/groups/Elementors/posts/3997242673734822/ or https://www.facebook.com/groups/Elementors/posts/3905563536236070/

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

I've found this bug to be used by spammers on version 3.0.X till the most recent version.

**Comment by astbarc** [comment]
Same happening on my site. I've received several spam contact form messages with empty url. Would be great to have a solution for this.

**Comment by astbarc** [comment]
I just think that one temporary solution would be to use the [elementor_pro/forms/validation](https://developers.elementor.com/forms-api/) action to check if the 'page_url' meta is empty and and throw and ajax error.

**Comment by iJorji** [comment]
> I just think that one temporary solution would be to use the [elementor_pro/forms/validation](https://developers.elementor.com/forms-api/) action to check if the 'page_url' meta is empty and and throw and ajax error.

That was exactly my suggestion to Elementor but they wouldn't do anything about it. They just said to use an external spam filter, as this issue didn't seem important to them.

**Comment by astbarc** [comment]
The external spam filter is not a solution for this. I have recaptcha and honeypot in all my contact forms and from time to time, I still receiving these submissions with the empty url.

**Comment by iJorji** [comment]
> The external spam filter is not a solution for this. I have recaptcha and honeypot in all my contact forms and from time to time, I still receiving these submissions with the empty url.

I recommend you install CleanTalk to bypass this issue. You won't even have to use reCAPTCHA or Honeypot if you have this installed. I do this as well, as Elementor isn't responding to this issue what so ever.

**Comment by Axel186** [comment]
Same here... 

I added the `elementor_pro/forms/validation` and check if the Page URL is not empty.
But still getting spam emails with empty Page URL.

I have a feeling that this is some kind of bug. 
Maybe spammers discovered a way of sending these email by using one of REST APIs?

**Comment by nicholaszein** [comment]
Hello there,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We cannot reproduce your issue at all. We tried every possible scenario shared here, including trying to submit forms via REST-API, hiding forms with CSS, using Popups, and other methods we can't disclose. I none of the cases we could force a form submission without being blocked by honeypot, recaptcha, akismet, 3rd-party security, or even a raw and simple form. We also did an extensive review of our Forms API and code, and couldn't find anything that would allow for this type of exploit.

### ✅ What you can do to solve your issue:
Since this issue was submitted, a lot has changed, and Elementor has consistently improved the quality and security of its entire codebase, including Forms. If you haven't already we recommend updating to the latest version, and ensuring honeypot, and other spam preventing methods are used.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor after following the troubleshooting steps above, feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Kind regards
