### ISSUE TITLE
Some section in my about page does not show images and text any more when i view my about page, but when i edit it with the elementor page builder i will see my text and images clearly.  I really need help urgently. This has not been happening to my about page before, it only happen when i update my elementor page builder. I also contacted my hosting company. but they ask me to check my page builder elementor pro. I lastly create another elementor template but i still experience the same problem This is my about page website link:https://lloydrandall.com/about1/

### ISSUE THREAD

**Issue by JohnYambasu** [elementor/elementor#16177]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 
* Prerequisites.
* **Steps to replicate.**
* Isolating the problem.
* **System info.**
* One issue per thread

Without it, we simply can't help.
Since you are a Pro user, you are welcome to reach to our support.

Thanks.
