### ISSUE TITLE
Issue with E_COMPILE_ERROR

### ISSUE THREAD

**Issue by almoria83430** [elementor/elementor#16379]
Hi everyone,

I have an issue with this error : 

Une erreur de type E_COMPILE_ERROR a été causée dans la ligne 627 du fichier /home/setoudxq/www2/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php. Message d’erreur : Access level to ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_create_url() must be public (as in class Elementor\Core\Base\Document)

Do you have any recommandation ? 

Thanks

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

Since you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).

Thanks.
