### ISSUE TITLE
Display the number of views of each post in the posts widget

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#16425]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

It is great to be able to display the number of views per post. This is super great and practical. Currently, we can only display information such as number of comments, time and author.
![Screenshot (170)](https://user-images.githubusercontent.com/88034902/135356434-8cd55270-d6e0-4e30-a238-525233f0ddcb.png)

It would be great if the ability to display the number of views was added

**Comment by DorShahar** [comment]
Hi @Michaelgimii 
Thank you for your input.

At the moment, this issue is not in our focus. In case we will see more requests for this option, we would definitely consider developing this.

You can look for other solutions at https://gretathemes.com/count-post-views/#how-to-count-post-views-in-wordpress-without-using-plugins

Thank you for your understanding.

**Comment by ooDr0n** [comment]
I'm also interested in this functionality.

@Michaelgimii  Did you find a solution?

**Comment by christiaan1981** [comment]
me too please

**Comment by nadworks** [comment]
me three.
