### ISSUE TITLE
BUG / Icon List Widget Divider

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#16431]
There is a problem with the icon list widget Divider. The Divider is not placed vertically in the center. This bug has occurred in the latest version.
In this video, the bug is quite obvious :

https://user-images.githubusercontent.com/88034902/135406069-f3d5e1d4-c395-49a9-9c84-d357c4fce90f.mp4

**Comment by m1ga** [comment]
The issue is that
`.elementor-widget .elementor-icon-list-items.elementor-inline-items .elementor-icon-list-item::after` is set into center using top/transform but the outer flex element already is aligning to the center:
https://github.com/elementor/elementor/blob/fab0d46aac98a4b09a92b7a0a7bf4fcbe1942b46/assets/dev/scss/frontend/widgets/icon-list.scss#L61

removing those lines:
https://github.com/elementor/elementor/blob/fab0d46aac98a4b09a92b7a0a7bf4fcbe1942b46/assets/dev/scss/frontend/widgets/icon-list.scss#L30-L31
(only tested in Firefox and Chrome)

**Comment by m1ga** [comment]
looks like there is a PR already: https://github.com/elementor/elementor/pull/16440

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!
