### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Allow to add links individually to each image in the Image Carousel (Duplicate of #216)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#16604]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The image carousel widget has a major drawback. For example, if we display 20 images as a carousel, we can only apply one link to all images. This is very bad.

Please add a feature to this widget, so that we can link to each image we add individually.

**Comment by nicholaszein** [comment]
Hey @Michaelgimii! How's it going?

Long time no see! 🙂 

Thank you for submitting your suggestion! 🙏 

While we understand the need to set different links for each image in the Image Carousel widget, we also want to maintain our widgets as close to the default WordPress behavior as possible. The Image Carousel widget uses the default methods of WordPress Galleries, and fetches the information from each gallery created. The only difference is that instead of displaying the images in a grid, we display them in a Carousel. But the principles are the same. Since there is no field to determine a URL for each image in the default WordPress attachments, there is also no built-in way to find that information. 

For this widget, the idea was to be as simple and straightforward as possible. The addition of a URL field in the media attachment to make this work would not follow these principles. For this reason Elementor created the Media Carousel widget, where you can define custom links for each image in the Media Carousel without having to rely on external sources. 

The Media Carousel was created back in Elementor Pro version 1.9 (a long time ago), and has fulfilled this necessity quite well. We also now have the Nested Carousel, that allows you to add Image widgets and define custom URLs. 

There are plenty of alternatives for the Image Carousel. For this reason, I'm closing this issue as it has already been solved. I hope you can understand. 🙏 

Kind regards
