### ISSUE TITLE
⛔ 🛟 Support Request: Pixels we don't need that slow down our website in China!

### ISSUE THREAD

**Issue by hagarips** [elementor/elementor#16665]
We are pro users. 

We see that with the pro version there are pixels integrated in the code. 
This is what we see: 
<script type="text/javascript" id="elementor-pro-frontend-js-before">var ElementorProFrontendConfig={"ajaxurl":"https:\/\/www.ladingo.com\/wp-admin\/admin-ajax.php","nonce":"fbb31889df","urls":{"assets":"https:\/\/www.ladingo.com\/wp-content\/plugins\/elementor-pro\/assets\/","rest":"https:\/\/www.ladingo.com\/wp-json\/"},"i18n":{"toc_no_headings_found":"No headings were found on this page."},"shareButtonsNetworks":{"facebook":{"title":"Facebook","has_counter":!0},"twitter":{"title":"Twitter"},"google":{"title":"Google+","has_counter":!0},"linkedin":{"title":"LinkedIn","has_counter":!0},"pinterest":{"title":"Pinterest","has_counter":!0},"reddit":{"title":"Reddit","has_counter":!0},"vk":{"title":"VK","has_counter":!0},"odnoklassniki":{"title":"OK","has_counter":!0},"tumblr":{"title":"Tumblr"},"digg":{"title":"Digg"},"skype":{"title":"Skype"},"stumbleupon":{"title":"StumbleUpon","has_counter":!0},"mix":{"title":"Mix"},"telegram":{"title":"Telegram"},"pocket":{"title":"Pocket","has_counter":!0},"xing":{"title":"XING","has_counter":!0},"whatsapp":{"title":"WhatsApp"},"email":{"title":"Email"},"print":{"title":"Print"}},"facebook_sdk":{"lang":"en_US","app_id":""},"lottie":{"defaultAnimationUrl":"https:\/\/www.ladingo.com\/wp-content\/plugins\/elementor-pro\/modules\/lottie\/assets\/animations\/default.json"}}</script>

We do not need most

**Comment by caspervoogt** [comment]
Those are not pixels. I agree, though, that Elementor should only print code it actually needs. The presence of a "nonce" in code like this can lead to false positives in security scans, for example. That is something I am running into right now. Elementor, please provide a way to disable this 'feature'

**Comment by nicholaszein** [comment]
Hello @hagarips,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
As @caspervoogt correctly pointed out, these are scripts required to load content dynamically on your website. These are not pixels, tracking codes, or if flagged by security scans, are only false positives. We have no plan to remove these.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
