### ISSUE TITLE
While using the Video Gallery module, If you select "Vimeo" as the source, the "Contents Tabs" option is no longer present to add additional information. It is there for Youtube and self hosted but not there for vimeo?  

### ISSUE THREAD

**Issue by filament72** [elementor/elementor#16714]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by rami-elementor** [comment]
Hi @filament72 ,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/pojome/elementor/issues/new?template=Bug_report.md).

Please feel free to open a new issue in accordance with these guidelines.

Regards,
