### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Add link in  Badge Taxonomy, Avatar in Archive Posts Widget (Duplicate of #13058)

### ISSUE THREAD

**Issue by careofweb** [elementor/elementor#16747]
Mr. Erik Svec ask a question in Elementor official forum, I am quoting him:

"I found an interesting issue with ‘Archive Posts Widget’. It was really surprising, that I could’t find anything about this topic here on the forum. Let me explain:
When you create a page archive posts, one would expect all meta to be linked to other archive pages (based on the author, category, tag, etc.).
It’s a logical internal linking and it’s helpful not only for visitors, but also for SEO. 
Why is Elementor missing such and elementary feature?"

[](https://forum.elementor.com/fixing-common-issues-33/archive-posts-widget-pro-no-clickable-meta-data-avatar-and-badge-8006?postid=24732#post24732)

I am completely agree with him and also request for the feature.
Thank You

**Comment by nicholaszein** [comment]
Hello @careofweb!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #13058, on the same subject. This issue will be solved by the Loop builder though, which will allow you to build your own templates for posts, and it has been discussed in #4440.

For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
