### ISSUE TITLE
LivingWithPixels (117K youtube subs) report and suggestions

### ISSUE THREAD

**Issue by paauserrat** [elementor/elementor#16814]
https://www.youtube.com/watch?v=E0DD--QwuBc

**Comment by antonkeller** [comment]
+1 THESE HAVE to be taken care of.
The youtuber Rino talks about every point that annoyed me as well and apparently everyone thinks the same so they are super important yet easy fixes for elementor team to implement.
(I am pro member.)

**Comment by marketingspectrumNL** [comment]
I wrote a similar list on the Elementor forum ideas section. So more people in the market are experiencing the same thing which is a product that can be better. If you are on the hub, feel free to upvote this there as well: 

https://forum.elementor.com/ideas/existing-widget-improvements-8295

Focus on reliability and usability.

**Examples of ‘bugs / boundaries’ :**

- CTA widget takes the widget color style when setting html <p> in the text. *(GREAT!) But when you use the imagebox or iconbox the color set in the widget for content gets overwritten by the global style.

- The icon of the “post widget” is actually not possible to create. (image left, text right)

- Setting the layout to ‘image left’ won't work on tablet / mobile. You'll have to add manual CSS to it ( @ media -> display block. ), and getting the content to align; Margin: auto. If you look online this ‘bug’ is present for 2 years without resolve, while you can set it with 3 lines of CSS.

- Text widget paragraphs running together or simply deleting html set to the widget.

- Trying to type texts in toggle widget is almost impossible because the widget will start opening and closing slowing on every keystroke. So you'll have to type in your desktop notepad and add it to the widget. 

- Some widgets accept HTML, other don't.

- Not being able to change section overlay gradients per viewport. No image settings for background images - but they will appear on the image overlay. 

- CTA widget is recommended to improve page speed, but has no way to set the image  position or adapt in height to the image. To avoid a color on hover you'll need to set a overlay color and set it to #ffffff00. (adds unneccesary css).

- Multi form widgets keep going to the first step making editting multi step forms extremely hard. When image upload is required you need to upload an image while you are in the edittor trying to get to the next step. 

- Blog pagination jumps to the top of the page instead the top of the blog.

**Comment by shilo-ey** [comment]
Hi @paauserrat 

Thank you for your feedback.

We are aware of this video and already implemented several fixes.
We are planning to address most of this list in the near future.

Almost every item here has already a gituhb issue.
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.
* **One request per thread**

Thanks.
