### ISSUE TITLE
❌ Icon list bug - inserting SVGs bloats the DOM immensely

### ISSUE THREAD

**Issue by jazir555** [elementor/elementor#16904]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I inserted 5 SVGS in the icon list widget. The DOM size increased by 300 elements. From ~800 to 1100. My pagespeed score instantly dropped significantly. There is no reason inserting an SVG should increase the DOM size this much. Using SVGs is pointless in Elementor, since the entire point is smaller file sizes which is supposed to improve page load speed, not instantly tank it to the point where my CWV go out of the green.

## Steps to reproduce
1. Run a lighthouse test prior to inserting the SVGs into an icon list widget

2. Insert an icon list widget onto the page and upload 5 svgs. If necessary I can provide the icons I used. 

3. Re-run lighthouse and see that DOM has blown up immensely, tanking pagespeed.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by nicholaszein** [comment]
Hello @jazir555.

As explained [here](https://github.com/elementor/elementor/issues/14092), and [here](https://github.com/elementor/elementor/issues/18117), the size of the DOM output of your icons, will depend directly on how they were designed. If your SVGs have multiple elements and groups, they will all be printed as nested HTMLs. You need to optimize your SVGs to have the minimal items inside if you want to reduce the DOM output. A good way to do this is to create compound paths, and expand any text and strokes you might be using on your SVGs. If you don't do that, they will affect your DOM output, and this has nothing to do with Elementor. Elementor will only output the contents of your SVGs. Optimizing them is your responsibility.

Here is a good article you can follow to learn how to optimize your SVGs:
https://element.how/all-svg-icon-elementor-compatible/

I hope this helps you find the perfect balance between performance and DOM output. To be clear, inline SVGs will always load faster than images, and the warning you see in tools like Page Speed Insights about excessive DOM size, are only guidelines to help you optimize your pages, they are not errors, and should not affect performance as much as they may indicate.

I'm closing this issue because it's not an Elementor bug.

Kind regards
