### ISSUE TITLE
Feedback for Flexbox Container (3.6.0-dev2)

### ISSUE THREAD

**Issue by fabianenzensperger** [elementor/elementor#16911]
@shilo-ey @DorShahar Yesterday I played around a lot with the new containers and I wrote down the following things:

- Where are the sticky options? And for columns there was also the sticky in columns function, which does not (yet) work with the containers.
- "Spacing" replaces "Columns Gap", correct? It's already great that it is now responsive adjustable.
Something that doesn't fit is that the space is always the same left and right. It makes more sense to determine whether there should be less (or no) distance on the outside and more on the inside. Exactly the same above and below. That is essential.
- Positioning is in layout now, right? I think it's much better. Somehow belongs together.
- Please, please add to the new containers that you can assign a link to the whole container (regardless of whether it is a row or a column). So no matter where you click in this area, it is clickable. Many users have wanted this for a long time for Column’s.
At the latest when the custom loop / skin builder appears, this function is a must. But better sooner than later.
I have read that this should now work in your points in the new Forum, but I was unable to discover it yesterday. Maybe you can explain where I can find it.
- In this context, please finally make the background and, above all, background overlays responsive. For example, the gradient can only be set once, but for mobile devices this gradient hardly ever fits as it is set on the desktop.
- Editing icons for mouse contact are missing. It works everywhere, just not with the new containers. For the first (highest) container widget, it is clear that the display is different there, but as soon as another container such as Inner Row or Column is created earlier, these edit icons can be opened (if they have been activated under the user settings in the editor ) unavailable. I think this could be useful.

That was all for now and I look forward to your feedback.

**Comment by 79ho3ein** [comment]
I think the "Add new Column" option is still needed. It is strange that it has been removed! Because of this, I had trouble adding a new column.
https://user-images.githubusercontent.com/77163248/141331626-951eadd3-61a9-4d5c-a352-7f45f388afc3.mp4


Another thing I came across was that enabling wrap affects the width of the content. If we have two widgets with a width of 50% (each), they will be placed next to each other and there is no problem. But if we enable the wrap, the row breaks.
It is clear in this video. Maybe I'm wrong.
https://user-images.githubusercontent.com/77163248/141332177-a5b2a928-af7e-4ed0-ba07-6d33954a209c.mp4

**Comment by shilo-ey** [comment]
@fabianenzensperger thank you!
Great feedback.
We will review your suggestions and will update you.

As for the link - please make sure you are setting the Container HTML tag option to ‘<a>’.

@79ho3ein thanks!

Every Container is a standalone one, and in contrary to a column, it can be dragged directly from the Panel, or simply duplicate the container you want to add.

As for the wrapping option - make sure 0 is placed in your spacing to make it next to each other (50%+20px+50% makes it more than available hence the row breaks)

thanks!

**Comment by black-eye** [comment]
> * Spacing" replaces "Columns Gap", correct? It's already great that it is now responsive adjustable.
>   Something that doesn't fit is that the space is always the same left and right. It makes more sense to determine whether there should be less (or no) distance on the outside and more on the inside. Exactly the same above and below. That is essential.
> 

I've just done some initial testing and I was exclusively concentrating on the layouts and gaps. Spacing is really meant to replace the Column Gap, and it's actually executed by the CSS property of the same name - gap. More precisely it's the flexbox version of this property (more on this later).

As you mentioned, this property creates the gap solely BETWEEN the "columns" (or whatever other entities placed inside the container). Which is the only correct way, how to do it, at least from my designer's perspective.

So far, so good. But some of the problems still persist - above all this long-time problem: https://github.com/elementor/elementor/issues/452. Unfortunately, all the containers have default 10px padding, which creates layout inconsistencies, when the containers are nested:

![obrazek](https://user-images.githubusercontent.com/5634870/141378610-538a4b22-345c-4907-8ac5-f0af9fa20291.png)

Yes I know, I can change the padding in the Container Layout settings to 0px:

![obrazek](https://user-images.githubusercontent.com/5634870/141378670-8cd9484c-5e71-4bab-888a-0689e226baeb.png)

But what if I want this behaviour to be my default? - I will have to do it for EVERY container ever used! I cannot change it even by custom CSS to be used globally, because it's defined in the widget itself, it's pre-filled. So I have to change it manually, for every widget. This should be changed - **please, please give us the option to define this value as an option similar to Content Width or Widgets Space**:

![obrazek](https://user-images.githubusercontent.com/5634870/141376926-52be11bf-485a-411b-803b-9677cf310af6.png)

If this is done, everything is perfect.

One note on the flexbox gap - this property still doesn't have 100% browser support - see: https://caniuse.com/flexbox-gap. Although it got much better during the last year, more than 10% of the browsers still doesn't support it. No big deal for me (the worst thing that can happen is, there won't be gaps, but the page doesn't get broken) - but it should be mentioned somewhere.

Thanks

**Comment by black-eye** [comment]
Oh and one more thing concerning the spacing. The gap property can have 2 variants: column-gap and row-gap. I would be very handy to have them both.

**Comment by 79ho3ein** [comment]
Friends, where are the float ups and downs In the Motion Effects tab? Also the option to stay in column.
Is the option to stay in the column really removed? Wow scary changes.
I did not examine everything carefully. Maybe I missed something

**Comment by fabianenzensperger** [comment]
> Friends, where are the float ups and downs In the Motion Effects tab? Also the option to stay in column.
> Is the option to stay in the column really removed? Wow scary changes.
> I did not examine everything carefully. Maybe I missed something


I don't think they have forgotten, just not integrated yet. And the "Stay in Column" or soon "Stay in Container" was only published a few months ago, and I also can't imagine that all these things should be dropped.

Especially the sticky options and motion effects, Elementor really can't seriously plan that. 😅

**Comment by fabianenzensperger** [comment]
> Oh and one more thing concerning the spacing. The gap property can have 2 subvariants: column-gap and row-gap. It would be very handy to have them both.


Yeah, this would be great. It is smart to have it automatically adapted to the direction, but there are areas of application where both are necessary.

**Comment by shilo-ey** [comment]
Hey all thanks for reporting and sharing insights!

We improved the container and are going to release it soon to an alpha stage experiment in all versions.

If you encounter any other issue please create a new issue for us to inspect and fix it.

As for column/row-gap options - we will work on adding this soon.

Thanks!

**Comment by nicholaszein** [comment]
Hello all!

Thanks for your insightful feedback! 🙏 

Since this issue was raised, my improvements were made to the Flexbox Container, and almost all of the items were improved.

We now have:

* Sticky Containers
* Anchor tags for the container `<a>` with links
* Responsive background images (the latest bugs will be fixed in v3.8)
* Editing handles were added to all containers
* Background overlays have now responsive images
* The "Add new Container ➕" option is now working as expected
* "Stay in column" for sticky containers
* Default padding for Containers in Site Settings

What we are still analyzing the best way to implement (and if we are going to implement them now):

* Flexbox row-gap/column-gap

This will be discussed in another thread in the future. Thank you all for helping us make the Flexbox Container a thing!

Best Regards

**Comment by nicholaszein** [comment]
Hey peeps,

I just wanted to update you, if you want to comment about the **row-gap/column-gap** request, please refer to issue #18331.

Kind regards,

Nick
