### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null  at pageHeaderHeight

### ISSUE THREAD

**Issue by dchandrika** [elementor/elementor#16982]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by rami-elementor** [comment]
Hi @dchandrika ,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/pojome/elementor/issues/new?template=Bug_report.md).

Please feel free to open a new issue in accordance with these guidelines.

Regards,
