### ISSUE TITLE
✅ 🐞 Lightbox not playing youtube videos with autostart

### ISSUE THREAD

**Issue by webboyon** [elementor/elementor#17080]
Lightbox not playing youtube videos with autostart, 
I can see the autoplay parameter eg &autostart=1 , work on videos?

**Comment by ofmarconi** [comment]
This also happens with the Inline Video Widget, without lightbox but with Thumbnail overlay.

I don't understand why this doesn't work, I see news sites like this:
https://www.uol.com.br/tilt/reportagens-especiais/olhos-no-espaco-como-telescopio-james-webb-deve-revolucionar-a-ciencia/#:~:text=Tempo%20de%20miss%C3%A3o,%C3%A9%20algo%20impens%C3%A1vel.

Operating normally.

Is there any work in operation?

**Comment by Nazrinn** [comment]
This is an issue with browsers, not Elementor per say. [Chrome no longer allow video autoplay with sound since 2019.](https://stackoverflow.com/questions/50490304/how-to-make-audio-autoplay-on-chrome).

While workaround technically exist (see link above), they are old and might have been patched since (they have no guarantee to work). I'd be surprised Elementor can issue a reliable fix for this.

**Comment by JxxIT** [comment]
I have the same issue, but with vimeo. It seems that if the iframe has "allow=autoplay" that it will autoplay. Has anyone else already a solution?

**Comment by ofmarconi** [comment]
Without solution

**Comment by JxxIT** [comment]
Yeah, I used WPBakery for testing, and autoplay work fine with "allow=autoplay"

**Comment by JxxIT** [comment]
I just made another issue specifying this fix: #24273

**Comment by KoshaK0** [comment]
It's does not play for me specificly when LightBox enalbed, but works well, as expected without LightBox. So, the statement about "[Chrome no longer allow video autoplay with sound since 2019](https://stackoverflow.com/questions/50490304/how-to-make-audio-autoplay-on-chrome)" not quete correct. That would be correct, if the video would be on the screen starting to play streight away... but in this case user have to press PLAY button on Overlay image/icon and that hte way it works without LightBox. So, something not right with Lightbox there...

**Comment by parfilov** [comment]
There is a similar need

**Comment by JxxIT** [comment]
I made a PR that fixes this: #24324. I am still waiting for a review, but if you need the code, you can download the code (upper right button) and run grunt build from your terminal to get a working plugin.

**Comment by JxxIT** [comment]
@webboyon @ofmarconi @Nazrinn @KoshaK0 @parfilov. My PR has been merged: #24324, this should be in the next update of elementor.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.23.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
