### ISSUE TITLE
THERE HAS BEEN A CRITICAL ERROR ON THIS WEBSITE. 

### ISSUE THREAD

**Issue by courtneygoff88** [elementor/elementor#17132]
Greetings,

About 30 minutes ago, I downloaded this developer plug-in, and immediately after downloading, I lost access to my website & even full functionality to my admin dashboard. Totally unacceptable.  I tried backing up/restoring but I am unable to do this, as I keep getting the error: "There has been a critical error on this website."

I have never experienced this, and am disappointed and bereaved. Please help me immediately. My website is my store front. 

This is my first time opening a request, so I ask for your patience as I navigate this. Please let me know if you need any additional information from me.

- Regards

**Comment by DorShahar** [comment]
Hi,

Please create GitHub issues only for bugs reports and feature requests.
**GitHub issues are not for support.**

If you have questions or need general support, Please try:
- Elementor Community on Facebook
- Elementor Knowledge base
- Support forums on WordPress.org
- Elementor Developers docs

**If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details, or check [here](https://elementor.com/support/).**

Thanks.

**Comment by courtneygoff88** [comment]
Good morning,

Thank you for your response. As I already stated, I am new to your forum &
processes. With all due respect, I have not & will not purchase your "PRO"
version, just to get support for my website crashing due to your free
product.

I don't need my ticket closed, what I need is immediate assistance to get
my website back up & running. As I mentioned, immediately after
downloading your developer plug-in, my entire site crashed. So I need your
assistance please.

Can you actually give me links to these bullet pointed avenues you've
mentioned? Links would be more helpful, rather than just a bullet pointed
list.


- Regards

**Comment by leecollings-sb** [comment]
Just a personal observation by an outsider here, as has been outlined, this isn't really the place for general support for 'your website'. This is a very vague request. You need to find out what's wrong first before deciding who to go to.

Firstly, this isn't a plug-in, this is a theme.

Secondly, as your first point of call, I would suggest you ask your web host to look at the logs and find out what the exact issue is that caused the crash.

Finally, your point about not wanting to purchase a pro subscription but you just want help, that's now their support procedure works. The free version of Elementor doesn't come with support. For this, you should go to the Wordpress support forum instead.

I don't believe this issue will be re-opened until there is something more substantial that shows there is a fault with Elementor itself, because to be honest, the fact that you've experienced a crash when installing, is a very rare thing, which would mean there is something either wrong with your hosting configuration or something else that's very specific to your installation, and not Elementor in general.

That would take it outside of the 'bug issue' scope I'm afraid.

And just lastly before I go, your tone seems to suggest you believe the Elementor team 'owe' you support? This is not the case, and you should be more polite when asking for help.

**Comment by courtneygoff88** [comment]
Good morning,

I apologize that I was unable to read your full message, as quite honestly
the tone immediately came off as condescending & lecturing.😅🙏

As I mentioned in my post from 48 hours ago, I was new to the forum & on
how to navigate it all. This ticket was actually closed yesterday. 🙏

I have since spoken with two employees/representatives with the actual
company, in addition to the actual Wordpress platform, and my issue was
resolved early yesterday. Are you even an official employee with Elementor
or Wordpress?

Respectfully, Mr. Collins you are a hypocrite. You have attempted to
lecture me, an adult on how to speak, when in all of my correspondence I
greeted said representatives & apologized within my messages for any
frustrations. You have lectured me, without practicing your own advice. If
my messages were of offense to you, when I didn't express curse, name-call,
but expressed my displeasure respectfully, then you're in for a rude
awakening in the realm of customer service. I know that it felt good for
you to attempt to take time to type a lecture, but it really is actually
telling of your own character. Please stay in your place, if you're unable
to speak to the public in a respectful fashion.

If I may make a suggestion, when giving pointers to the general public &
complete strangers you do not know, try opening up with a greeting & try
speaking from a place of solidarity & not in a condescending, lecturing or
annoyed fashion.

I will be keeping a copy of your email, and should you email me again, I
may share your email and the occurrence to social media in review & with
your corporate. superiors.

Not trying to be rude- just honest. This is your official notice to not
email me again; any further emails from you will be considered harassment.
God bless.


Respectfully,

Courtney

**Comment by leecollings-sb** [comment]
Hi Courtney,

I humbly disagree with everything you have said. I was helping you in the same way that your initial response from this issue came about (which told you this was not the place for general support issues).

I'm in no way a member of staff at WordPress or Elementor, I'm a regular developer / user (much like yourself), offering my help and advice. Nothing more.

Glad you managed to get your issue resolved in the end.
