### ISSUE TITLE
No Elementor Pro docs?

### ISSUE THREAD

**Issue by babakfp** [elementor/elementor#17173]
Why there is no documentation for Elementor Pro?! Current docs only contain some basic stuff and there is no documentation for Elementor Pro.

**Comment by rami-elementor** [comment]
Hi @babakfp 

Great question. 

The old developers website had a few articles on Elementor Pro. Those articles are no longer relevant as we improved our code base. We prefer developers won't use those old code practices. This is why we didn't publish them in the new site.

We are already working on new tutorials with updated code practices. For example, in Elementor Pro 3.5 we made it much easier to interact with Elementor Forms. Now you can create your own Field Types instead of just modifying existing fields.

Be patient, it's worth the wait.

**Comment by babakfp** [comment]
👍
