### ISSUE TITLE
BUG / In elementor 3.5, the finder does not work.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17238]
hello
As mentioned in the title, Finder does not work in the new version. For example, I searched for a header or footer but it was not found. Completely disrupted. I went back to the previous version and the problem was solved.

**Comment by zeinnicholas** [comment]
I can confirm this is a bug. Searching the Finder doesn't return any results.

**Comment by DorShahar** [comment]
Hi @79ho3ein and @zeinnicholas ,
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Comment by 79ho3ein** [comment]
excuse me @DorShahar.
Why do you close the issue immediately? I test each bug on several different websites and then report.
In the new version, Finder finds pages, but does not recognize templates built into the elementor theme builder. Like a header or footer.

**Comment by zeinnicholas** [comment]
@DorShahar Thanks for the reply.

Here, I recorded a video of the issue. As @79ho3ein mentioned, you can't find any Elementor Template using the finder, and I'm not sure if it was always like that, but you can only find Pages that were created with Elementor. Since usually, I do build everything in Elementor (except blog posts) I can't say if this is a bug or feature.

But please do check again to see if there isn't something wrong with the finder.

### Video:
https://user-images.githubusercontent.com/26891676/146867264-07c3ee4f-2ea4-4ce2-82f9-4c438dd30b3f.mp4

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.19.3
	MySQL version: mariadb.org binary distribution v10.4.22
	PHP Version: 7.4.26
	PHP Max Input Vars: 10000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.2
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 1024M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: America/Sao_Paulo
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.4.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.5.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.5.2
		Author: Elementor.com


== Elements Usage ==
	
	archive : 2
		archive-posts : 1
		nav-menu : 1
		theme-archive-title : 1
	wp-page : 7
		button : 3
		call-to-action : 4
		container : 4
		divider : 12
		heading : 45
		icon : 1
		icon-box : 5
		icon-list : 1
		image : 20
		image-carousel : 2
		nav-menu : 1
		spacer : 3
		tabs : 1
		text-editor : 16


== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive by default


== Log ==
	
Log: showing 20 of 432021-12-16 09:17:05 [info] elementor::elementor_updater Started 
2021-12-16 09:17:05 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-16 09:17:06 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-16 09:17:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev18',
  'to' => '3.6.0-dev19',
)]
2021-12-17 09:17:03 [info] elementor::elementor_updater Started 
2021-12-17 09:17:03 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-17 09:17:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev19',
  'to' => '3.6.0-dev20',
)]
2021-12-17 09:17:05 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-17 09:17:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev19',
  'to' => '3.6.0-dev20',
)]
2021-12-20 09:17:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev20',
  'to' => '3.6.0-dev21',
)]
2021-12-20 09:17:04 [info] elementor::elementor_updater Started 
2021-12-20 09:17:04 [info] Elementor/Upgrades - _on_each_version Start  
2021-12-20 09:17:04 [info] Elementor/Upgrades - _on_each_version Finished 
2021-12-20 09:17:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev20',
  'to' => '3.6.0-dev21',
)]
2021-12-21 00:30:43 [info] elementor-pro::elementor_pro_updater Started 
2021-12-21 00:30:43 [info] Elementor Pro/Upgrades - _on_each_version Start  
2021-12-21 00:30:43 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2021-12-21 00:30:43 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2021-12-21 00:30:43 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2021-12-21 00:30:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.0-dev14',
  'to' => '3.6.0-dev20',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==


</details>

**Comment by 79ho3ein** [comment]
hello @zeinnicholas, Thanks for the great video.
Yes, that's exactly the problem. Elemental theme builder templates are not displayed in the finder results.

**Comment by Joseph089** [comment]
I had the same issue, elementor finder didn't show any results at all. That is after updating to 3.5.2. I contacted the elementor support. The fix for me was to go to Elementor settings, deactivate Usage Data Sharing, click save, reactivate and save.
