### ISSUE TITLE
Custom border CSS in Page settings not woking after 3.5.2 update

### ISSUE THREAD

**Issue by Zebraoutput** [elementor/elementor#17286]
Hi!

I have installed the Hello Theme Version: 2.4.2  and Elementor Pro 3.5.2

I use custom CSS in the PAGE SETTINGS panel so I can have a white border around my page. css code to make a border around my page. 
------
body {
    margin:0px;
    border:20px solid white;
}
------
I don’t know what happened but after the update the border is not there any more. It is visible in the Elementor builder but not in a browser. I have checked Safari, Chrome and Firefox. see image

Is this a bug or does anybody know how to fix this / workaround?

Thanks in advanced.

![3fb2e294-6db8-47e5-8a4d-aa1cb3c6f5ab](https://user-images.githubusercontent.com/898054/147263796-de14ad24-6d81-4dc1-a2b0-8d10340c0193.png)

 

Regards, Marlon

**Comment by DorShahar** [comment]
Hi @Zebraoutput 
Thank you for taking the time and reporting this.

We recreated your process of work and it seems to work properly.

Please try ti deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

Since you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

I used the same CSS but with the color of red :
`body {
    margin:0px;
    border:20px solid red;
}`

And It seems to work properly: 
![image](https://user-images.githubusercontent.com/19154938/147878617-835476bc-5e3a-4298-b0df-c29029e6de99.png)


Thanks.
