### ISSUE TITLE
'the_content' missing code 

### ISSUE THREAD

**Issue by cheyennewe** [elementor/elementor#17321]
"you must call "the_content' function in the current template in order for elementor to work on this page"
I am not able to do any editing, I cleared the cache, changed browsers, deactivtated plugins. So i reached out Elementor for help. 

They told me to report this to you all- 
"we suggest you report this issue to the plugin authors and see if they can provide a fix on their end. If they need help from us, they can open an issue on our Github account and our developers will be happy to on our github account" 

Please help
![Screenshot 2021-12-28 135921](https://user-images.githubusercontent.com/96794948/147602623-6de0d460-fb81-46ce-aeda-4cc118b72f1b.png)

**Comment by DorShahar** [comment]
Hi

1. Please view: https://elementor.com/help/the-content-area-was-not-found-error/
2. A quick solution might be since your template (single post - I guess) does not contain the widget of "Post content". So please make sure that your single page/post includes this widget.

We are working on this matter to make sure you won't see this error.

Thanks
