### ISSUE TITLE
Search and Replace doesn't chnage any contents created with Elementor

### ISSUE THREAD

**Issue by maninvatsa** [elementor/elementor#17343]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce
1. Create text
2. Search and Replace the text
3. The old texts shows up 
4. Manually replaced the value in tables, Yet Elementor plugin shows old value
5. Deactivating the plugin shows the new value. 
6. There are no CDN or Cache plugin
7. Tried it with multiple theme and no other plugins except Elementor.
8.  

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Apache
WordPress 
Elementor plugin 3.0.2 - 3.5.4
<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!

**Comment by wadert3** [comment]
Running into this currently. Have 1500< instances of a phrase were needing to replace and specifically elementor links and text will not update. Tried several different search and replace plugins all with the same result. If there's an update to this/a fix let me know otherwise if this could get looked at that would be great, thanks!

**Comment by nathan951** [comment]
I as well I'm having the same issue. Is there any resolve to it?

**Comment by rondeo-balos** [comment]
I am having the same issue too. It seems that Elementor is ignoring this issue. I've found [this ](https://wordpress.org/support/topic/search-and-replace-doesnt-chnage-any-contents-created-with-elementor/page/2/)thread and they've closed it without having any fix, not even replying to the person who opened the case.

**Comment by deanna** [comment]
Chiming in to say I'm having this issue as well!

**Comment by diegodtlaprint** [comment]
I am also having this issue

**Comment by diegodtlaprint** [comment]
When I use the elementor search and replace I get '0 database rows affected'

**Comment by ericdsd** [comment]
I have the same issue using wp search-replace

**Comment by CodeHakx** [comment]
I had the same issue. Turns out Elementor also keeps track of the content of pages in the `wp_glowcontactpostmeta` table. Entries with `meta_key`='elementor_data'. Replacing the appropriate value in the `meta_value` column. I am currently not aware of any wp plugin search and replace tool that actually makes those changes, although they might exist. I used a Database tool, , phpmyadmin, also available as a WP plugin. If you are unfamiliar with SQL, I would advise extreme caution before making any changes to any DB table with such tools. And always create a backup before modifying anything.
