### ISSUE TITLE
Logo Site problem

### ISSUE THREAD

**Issue by Or7graphic** [elementor/elementor#17387]
Hello, since I agreed to developer mode to help elementor to improve their service.. My logo site is appear like 300% bigger then usual - also some other features. it happens on my Shop Page, Product pages.
at the homepage is the example of the write logo size.

https://km-mobile-store.com/

thank you, 

<img width="1728" alt="צילום מסך 2022-01-06 ב-11 23 19" src="https://user-images.githubusercontent.com/97223113/148360163-26e14012-c666-48b2-88fb-87307f12b488.png">
.

**Comment by SteveKinzey** [comment]
On your home page, the logo width is set to 118px; on your shop page, the logo is set to a width of 637px and an aspect ratio of auto 637 / 507. My suggestion would be to set the image width to 118px on the pages with a larger image.

**Comment by Or7graphic** [comment]
Thank you. I worked with the same size of logo at this site for 2 years..
never had a problem. the logo is the same logo at every page - I did the
header at the site theme builder of Elemntor..


‫בתאריך יום ה׳, 6 בינו׳ 2022 ב-11:37 מאת ‪Steve Kinzey‬‏ <‪
***@***.***‬‏>:‬

**Comment by shilo-ey** [comment]
Thank you, I can see that @SteveKinzey note helped.

Cheers.

**Comment by Or7graphic** [comment]
No it's not helped. still has issue

‫בתאריך יום ה׳, 6 בינו׳ 2022 ב-12:55 מאת ‪shilo-ey‬‏ <‪
***@***.***‬‏>:‬

**Comment by SteveKinzey** [comment]
@Or7graphic 

The CSS/HTML code for your logo is as follows:

`<img width="637" height="507" src="https://km-mobile-store.com/wp-content/uploads/2020/07/cropped-Km-Logo-vector-_2-e1611761187671.png" class="attachment-full size-full" alt="" loading="lazy" srcset="https://km-mobile-store.com/wp-content/uploads/2020/07/cropped-Km-Logo-vector-_2-e1611761187671.png 637w, https://km-mobile-store.com/wp-content/uploads/2020/07/cropped-Km-Logo-vector-_2-e1611761187671-300x239.png 300w, https://km-mobile-store.com/wp-content/uploads/2020/07/cropped-Km-Logo-vector-_2-e1611761187671-600x478.png 600w" sizes="(max-width: 637px) 100vw, 637px">`

SIDENOTE: If you never want the logo to be larger than the size shown on the home page, you might consider resizing to the actual size, which is 118 px x 93.91 px.

I presume you created a header template and applied it to your entire site.  

My guess is, without knowing anything else about how you created your site, what plug-ins you are using, etc., that the suggestion below will solve your problem.

**FIRST: REPLACE THE WORDPRESS PAGE ID WITH THE PAGE TITLE IN THE URL**
Your shop and about us pages have URLs that include the WordPress page id rather than the page title; please change the shop page's URL from https://km-mobile-store.com/?page_id=307 to https://km-mobile-store.com/shop. To do this, you need to remove ?page_id=307 and replace it with shop in the slug field.

**IF THAT FAILS - DEACTIVATE THE ACCESSIBILITY PLUG-IN YOU ARE RUNNING**
If changing your slug does not fix the issue, I would temporarily deactivate the accessibility function or plug-in you have installed to see if it is causing some conflict. Yes, one would think that it is because you do not have a size issue on the homepage that it should be the same on all the other pages. However, the homepage, about page, and shop pages are three unique pages especially, if you have a template for the about us and shop pages. 

If this fails, don't hesitate to contact me, and I will help you solve the issue. Because I am not always logged in to GitHub, you will get a much more rapid response from me if you follow up in this thread and then send me a message using the Telegram App. My Telegram username is @skinzey

**Comment by Markhetding** [comment]
Exactly the same issue since i've updated my Elementor plugins. 
Also activated developer mode. 

My website: www.jouwbrief.nl

Looks like it doesn't matter what I try (adjusting sizes), it remains the same size (way too big).

**Comment by Or7graphic** [comment]
Hey thank you for your response, everything that  i tried did not work..
I just switched off the "DEVELOPERS MODE" of elementor and everything works
good and the logo size is updated to his regular size automatically.
so i think it's a bug at your side.
Thank you.

‫בתאריך שבת, 8 בינו׳ 2022 ב-21:24 מאת ‪Markhetding‬‏ <‪
***@***.***‬‏>:‬
