### ISSUE TITLE
❌ ⛔ 🐞 Bug Report: Shape Divider will cause Nav Menu dropdown to not work on tablet and mobile

### ISSUE THREAD

**Issue by mohammad7S7** [elementor/elementor#17408]
Hi,
Found a bug which i want to report. The Shape divider feature if activated in a div will cause menu dropdown via hamburger icon to not work on tab and mobile. Menu is build using elementor pro nav menu feature. Once shape divider is selected as "None" this bug goes away.
Hope, this issue get resolved soon. Thanks.

**Comment by nicholaszein** [comment]
Hello  @mohammad7S7!

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We couldn't reproduce your issue using the latest version of Elementor (v3.8.1) and the Hello Elementor theme (v2.6.1).
* Your issue could be related to the option to `Bring to Front` of the shape divider. Maybe hiding your dropdown menu under it.

### ✅ What you can do to solve your issue:
* Increase the z-index of the Nav Menu widget to 999.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
