### ISSUE TITLE
Gallery not updated with post image attachement

### ISSUE THREAD

**Issue by numerosept** [elementor/elementor#17531]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

Hello i have the same exact problem as issue : https://github.com/elementor/elementor/issues/11471
When removing some post images attachement or updating, the old images does not disappear. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by rami-elementor** [comment]
Hi @numerosept ,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/pojome/elementor/issues/new?template=Bug_report.md).

Please feel free to open a new issue in accordance with these guidelines.

Regards,

**Comment by mattsimplepixels** [comment]
@numerosept 

Did you ever find a solution?
