### ISSUE TITLE
✔️ 🐞 Bug Report: Unstable Container in Elementor Core 3.6 Dev Edition

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#17597]
Hi,
There are a lot of bugs with the new container feature in the dev version of Elementor core 3.6, and no real update to address them for a long while. My question is will the container feature be released for the 3.6 beta or pushed back? (or have you been fixing the bugs but applying to a soon to be released beta version?).

PS: game-changer feature when it is released and stable, very good job!

**Comment by 79ho3ein** [comment]
hello @perks98
Yes, unfortunately the bug in this version is very large. Of course, it is natural. Because it is a big change that elementor is going to make in its infrastructure. Therefore, it is unlikely that this version will be released in at least another 4 months. Maybe the next update will be related to elementor pro 3.7.
I think so, because elementor has not yet completed the 2021 updates in the pro version. Features like megamenu, nested elements and more

**Comment by nicholaszein** [comment]
Hey @perks98!

I'm making some cleanup and came across this issue. I think it's safe to say it has been **solved** already since we have now a stable Flexbox Container. Thanks to you, @79ho3ein, and others, we now can enjoy a much better experience with the flex container. Thank you for your feedback! 🙏 

Cheers 🥂
