### ISSUE TITLE
🔗 🚀 Feature Request: Add custom popup conditions available? (Duplicate of #6899)

### ISSUE THREAD

**Issue by Webtica** [elementor/elementor#17596]
Hi there, 

I was wondering: Are there hooks available we can use to add custom popup conditions? So we can add them to the list besides Show up to X times, Show when coming from URL etc. 

Is there any docs available on this? 

Thanks,
Dieter

**Comment by rami-elementor** [comment]
@Webtica 

You can read the Elementor Developers Docs.

See "Theme Conditions" at https://developers.elementor.com/docs/theme-conditions/

**Comment by nicholaszein** [comment]
Hi there,

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #6899

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉
