### ISSUE TITLE
🐞 Bug report: Docs - Controls - Simple Example

### ISSUE THREAD

**Issue by babakfp** [elementor/elementor#17634]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi
I exactly implement this [simple example](https://developers.elementor.com/docs/controls/simple-example/) and there was a bug and it was because of this:
```
$controls_manager->register( 'currency', new \Elementor_Currency_Control() );
```
It needs to be like this:
```
$controls_manager->register( new \Elementor_Currency_Control(), 'currency' );
```

I was going to make a PR but then I realized that the second arg ('currency') is optional. So, I wasn't 100% sure that it's really optional or it's going to break something for other users. [Complex Example](https://developers.elementor.com/docs/controls/complex-example/) doesn't have that second arg at all.
Thanks

---

Elementor Version: 3.5.4

### Steps to reproduce

_

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

_

**Comment by babakfp** [comment]
There is also another problem. Let's say I created a control with the minimum requirements (`get_type`, `content_template`). If I use the `Base_Control`, Elementor editor cant load but if I use `Base_Data_Control` it works fine. Am I missing something? because the `Base_Control` should work with the min requirements, same as the `Base_Data_Control`.

**Comment by LuigiPulcini** [comment]
The Simple example is definitely wrong and should be corrected.

As for your second point, it works with both parent classes for me. When you look at the [register method of the Controls_Manager class](https://github.com/elementor/elementor/blob/master/includes/managers/controls.php#L491-L500), the second parameter is currently ineffective, even when you pass something.

In fact, there is a `TODO` comment followed by commented-out code reminding to uncomment the code once Elementor Pro is adjusted to use this method instead of the deprecated `register_controls` one.

But at the moment, this new method always gets the `$control_id` through the `get_type()` method of control instance. So, it should work with any custom control extending the `Base_Control` class. There must be something else, in your case, preventing the control from registering correctly.

**Comment by rami-elementor** [comment]
@babakfp Thank you for the bug report. It was definitely a bug.

When we updated all the snippets and addon examples to Elementor 3.5 standards we missed this page.

In any case, I fix the example in the Docs.
