### ISSUE TITLE
The safe mode is not working, please solve it

### ISSUE THREAD

**Issue by eshopriver** [elementor/elementor#17633]
![مشكلة المنتور](https://user-images.githubusercontent.com/98463313/151706133-4c4dd519-47df-48c0-8588-dd6e5b935a4a.jpg)
![Untitled-2](https://user-images.githubusercontent.com/98463313/151706135-4398172e-29b2-4d00-bbb7-28f17dbc63cb.jpg)

**Comment by rami-elementor** [comment]
Hi @eshopriver ,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/pojome/elementor/issues/new?template=Bug_report.md).

Please feel free to open a new issue in accordance with these guidelines.

Regards,
