### ISSUE TITLE
Create a Discord Group

### ISSUE THREAD

**Issue by babakfp** [elementor/elementor#17717]
Hi
Please create a Discord group for the developer community. (I'm aware of the community website and the Facebook group or whatever it is).

**Comment by samheavyside** [comment]
This may not be a product "bug", but nevertheless, I second this in principle.

I do feel like the Elementor team will be reluctant to introduce yet another channel for conversations that they are unable to acknowledge or engage with. Ultimately, that will just breed further frustration from the user base. But, let's not be completely pessimistic about it!

Sure, Team Elementor needs to invest more in creating a space for engaging with the Pro/Expert/Agency users more directly, but that investment might just prove to be the best move they make in 2022. 

We (the Pro/Expert/Agency users) are a large, passionate, skillful, and invested cohort that _need_ Elementor to succeed or better yet, Thrive!  As one of these users, it often feels like our ideas, feedback, and "constructive criticism" fall on deaf ears. 

It would be great to have a platform where these users (who are gladly paying license fees so ongoing development can continue) are able to discuss some technical aspects of the product, provide solid insight/feedback to the development team (and possibly muster some engagement from them). 

The product is developing and changing rapidly, and it can only be to the benefit of the development team that we utilize the collective knowledge and insight of the very people that are using it every single day. In my opinion, that is the simplest way to make the progress faster and laser-focused on creating a product that those users (the paying ones) want!

To the point of the Original Post, a Discord Server may be an obvious/useful tool to provide this space. It is very simple and intuitive to use, but also very powerful and customizable.

Many industries (Gaming and NFT are two big ones) are turning to Discord to host their communities because it promotes dynamic and lively conversation instead of the stale forums of old. 

If not Discord, then please at the very least, consider this notion as something worth pursuing. 

Thanks.

**Comment by babakfp** [comment]
If it's not gonna be Discord, then it's gonna be useless as the community website and Facebook group. They just need to create a group and send the link to customers and link it in the website, GitHub repo, and everywhere else. It doesn't need to be exclusive to pro users. it's just a group and anyone can share their experiences and help each other. I also recommend removing the community website and the whole Facebook account.

**Comment by paauserrat** [comment]
Hi guys! Any of you have experience with discord? I'm add me *#*7898 (Pau Serrat)

**Comment by paauserrat** [comment]
> This may not be a product "bug", but nevertheless, I second this in principle.
> 
> I do feel like the Elementor team will be reluctant to introduce yet another channel for conversations that they are unable to acknowledge or engage with. Ultimately, that will just breed further frustration from the user base. But, let's not be completely pessimistic about it!
> 
> Sure, Team Elementor needs to invest more in creating a space for engaging with the Pro/Expert/Agency users more directly, but that investment might just prove to be the best move they make in 2022.
> 
> We (the Pro/Expert/Agency users) are a large, passionate, skillful, and invested cohort that _need_ Elementor to succeed or better yet, Thrive! As one of these users, it often feels like our ideas, feedback, and "constructive criticism" fall on deaf ears.
> 
> It would be great to have a platform where these users (who are gladly paying license fees so ongoing development can continue) are able to discuss some technical aspects of the product, provide solid insight/feedback to the development team (and possibly muster some engagement from them).
> 
> The product is developing and changing rapidly, and it can only be to the benefit of the development team that we utilize the collective knowledge and insight of the very people that are using it every single day. In my opinion, that is the simplest way to make the progress faster and laser-focused on creating a product that those users (the paying ones) want!
> 
> To the point of the Original Post, a Discord Server may be an obvious/useful tool to provide this space. It is very simple and intuitive to use, but also very powerful and customizable.
> 
> Many industries (Gaming and NFT are two big ones) are turning to Discord to host their communities because it promotes dynamic and lively conversation instead of the stale forums of old.
> 
> If not Discord, then please at the very least, consider this notion as something worth pursuing.
> 
> Thanks.



> If it's not gonna be Discord, then it's gonna be bad as the community website and Facebook group. They just need to create a group and send the link to customers and link it in the website, GitHub repo, and everywhere else. It doesn't need to be exclusive to pro users. it's just a group and anyone can share their experiences and help each other. I also recommend removing the community website and the whole Facebook account.

Hi guys! Any of you have experience with discord? I'm add me *#*7898 (Pau Serrat)

**Comment by babakfp** [comment]
Hey @rami-elementor

> After review, we have decided not to create an official Discord group.

Why? Will it be taking anything away from you guys? What are the cons here?

> You can always create an unofficial Discord group for your Elementor community.

I don't want an empty group.
