### ISSUE TITLE
elementor drag and drop issue  

### ISSUE THREAD

**Issue by ARSabeshan** [elementor/elementor#17776]
Hi, 

When I drag and drop any type of widget in the box it drops it twice every time. Anyone having the same problem as me ?

**Comment by wstam88** [comment]
I do!

**Comment by penum** [comment]
Me too

**Comment by rami-elementor** [comment]
Hi @XXX,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/elementor/elementor/issues/new?assignees=&labels=bug&template=bug.yml&title=%F0%9F%90%9E+Bug+report%3A+).

Please feel free to open a new issue in accordance with these guidelines.

Regards,
