### ISSUE TITLE
PHP: 2022-02-07 11:02:46 [warning X 60][/home/sites/10b/a/a985e17e56/public_html/wp-content/plugins/elementor/core/base/document.php::210] Trying to access array offset on value of type null [array (   'trace' => ' #0: Elementor\Core\Logger\Manager -> shutdown() ', )]

### ISSUE THREAD

**Issue by Monianka** [elementor/elementor#17798]
I have this PHP error and Elementor gives me ‘Preview Could Not Be Loaded’ Error, moreover some content is not displaying on the website. I have followed the all steps to fix the issues, which Elementor advise, however still have the same error. I run the safe mode, and I have checked the plugins and theme (I have switched to different one), I have increased WordPress memory from 40 MB to 250 MB,  I reinstalled Elementor. Nothing helped. I don't have idea how to solve it, ;( Anyone can help ? 
[system-info-hydra-scubadiving.com-09-02-2022.txt](https://github.com/elementor/elementor/files/8044669/system-info-hydra-scubadiving.com-09-02-2022.txt)

**Comment by rami-elementor** [comment]
Hi @Monianka ,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/pojome/elementor/issues/new?template=Bug_report.md).

Please feel free to open a new issue in accordance with these guidelines.

Regards,
