### ISSUE TITLE
✔️ 🔗 🚀 Feature Request: Dynamic due date in countdown widget (Duplicate of #7737)

### ISSUE THREAD

**Issue by kickslhfr** [elementor/elementor#17855]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

In the countdown wiget there is currently no possibility to predefine new countdown periods dynamically. 

### Describe the solution you'd like

The countdown widget should dynamically indicate on the homepage an event that takes place annually at the same time without having to be manually reset for the next year. For example, the event then goes 2 days, in which the countdown can then be provided with a text via "Action After Expire" with "Show Message". As soon as the event is over, the countdown for the next event starts counting.

Desired repeat times would be for example:
- Daily
- Weekly
- Monthly
- On every first, second, third, fourth / Monday, Tuesday, Wednesday, Thursday, Friday, Saturday Sunday of the month

**Comment by 79ho3ein** [comment]
+1

**Comment by tizum** [comment]
Guys, this functionality is very necessary in Elementor Pro, because I'm currently using the JetElements plugin to overcome the need for countdown with dynamic tag, even with only this one enabled in the crocoblock widget settings, it's an extra script/css to load on the site that it is even detected on google pagespeed, hindering the site in having a better performance.

Even the configuration of Elementor's current style is very good and I like it, so that's all it takes to be 100%, less a plugin and more performance.

![image](https://user-images.githubusercontent.com/6773491/191884377-e4995782-2cfa-4063-92bf-14d089f11077.png)


Looking forward to hearing from you, have a great weekend!

**Comment by tizum** [comment]
+1

**Comment by dyonatandias** [comment]
+1

**Comment by arielk** [comment]
Ref: https://github.com/elementor/elementor/issues/7737

**Comment by adoubler** [comment]
+1

**Comment by nicholaszein** [comment]
Hello, everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor Pro **v3.10**! 🥳 

You can learn more about it [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
