### ISSUE TITLE
⛔ 🐞 Bug report: date picker field not showing

### ISSUE THREAD

**Issue by teozu22** [elementor/elementor#17850]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

With any contact form plugin I tried, I can't make the date picker field show up.
I am using a shortcode.

Thanks.

### Steps to reproduce

Add contact form shortcode with date picker to contact page

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server (GPL) v5.7.37
	PHP Version: 7.4.27
	PHP Max Input Vars: 15000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	Site URL: https://www.raymondandpartners.com
	Home URL: https://www.raymondandpartners.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: office@raymondandpartners.com
	Debug Mode: Inactive

== Theme ==
	Name: Kinsey
	Version: 1.2.2
	Author: Artem Semkin
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:97.0) Gecko/20100101 Firefox/97.0

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.11.4
		Author: Delicious Brains

	Arts Custom Fonts
		Version: 1.0.0
		Author: Artem Semkin

	Arts Mouse Cursor Follower
		Version: 1.0.1
		Author: Artem Semkin

	Arts Smooth Scrolling
		Version: 1.0.2
		Author: Artem Semkin

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.5.5
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.5.5
		Author: Elementor.com

	Envato Market
		Version: 2.0.7
		Author: Envato

	Intuitive Custom Post Order
		Version: 3.1.3
		Author: hijiri

	Kinsey Core
		Version: 1.2.2
		Author: Artem Semkin

	Kirki Customizer Framework
		Version: 4.0.21
		Author: David Vongries

	Ninja Forms
		Version: 3.6.7
		Author: Saturday Drive

	Under Construction
		Version: 3.92
		Author: WebFactory Ltd

	WP Mail SMTP
		Version: 3.2.1
		Author: WPForms

	Yoast Duplicate Post
		Version: 4.4
		Author: Enrico Battocchi & Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
JS: showing 3 of 3JS: 2022-02-08 13:58:52 [error X 4][https://www.raymondandpartners.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.5.5:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `kinsey-widget-portfolio-fullscreen-slider-backgrounds-1` got as `cursor_clickable_links_icon` value. Expected array or object.',
)]
JS: 2022-02-09 10:51:45 [error X 11][https://www.raymondandpartners.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.5:2:453830] T is null 
JS: 2022-02-09 11:37:13 [error X 11][https://www.raymondandpartners.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.5.5:2:29700] elementor.settings.page is undefined 

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @teozu22,

Thank you for reaching out! 🙏 

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party plugins and add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party plugin, or only when the 3rd party plugin is active, you'll need to contact the support for that plugin or its developers.

This is also more of a support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards
