### ISSUE TITLE
✅ 🐞 Social Icons widget (Outdated)

### ISSUE THREAD

**Issue by stormit** [elementor/elementor#17931]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

I'm a theme developer. I'm having a problem with the Social Icons widget. I created a custom post type which allows user to create their own footer. User can edit footer with Elementor. I add the Social Icons widget to footer. It works fine on page which is editted with Elementor. But, it has a problem with the page which is not editted with Elementor (Ex: the WooCommerce Shop page). Please see my screenshot [https://prnt.sc/l7hiwYK4m73P](https://prnt.sc/l7hiwYK4m73P). In my case, I enabled the Improved CSS Loading option in Elementor > Settings (this option is enabled by default). Please help and fix this issue.

Thank you!

### Steps to reproduce

- Create a custom post type for footer
- Add the Social Icons widget to footer
- Check pages which is not editted by Elementor

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Any

**Comment by rami-elementor** [comment]
Hi @stormit 

Looks like a CSS issue. This can be a theme issue.

Please switch to the [Hello theme](https://wordpress.org/themes/hello-elementor/) to see if the problem still exists.

**Comment by stormit** [comment]
Hi @rami-elementor 

Thank you for reply!

Yes, it is a CSS issue. On an Elementor page, the CSS file (elementor/assets/css/frontend-lite.min.css) loads before the inline CSS. So, the inline CSS can override CSS in file.

Inline CSS

`.elementor-social-icon{
	display: inline-flex;
}`

CSS file

`.elementor-icon{
	display: inline-block;
}`

In the pages which are not the Elementor page, the CSS files are loaded in footer. So, this causes the problem.

Thank you!

**Comment by rami-elementor** [comment]
@stormit 

Can you attach your system info please?

**Comment by stormit** [comment]
Hi @rami-elementor 

Why do you need system info? It is a CSS issue and you can simple check it on your site. You just do things which I described. You will see issue.

Have a nice day!

**Comment by toineenzo** [comment]
Related? https://github.com/elementor/elementor/issues/28676

**Comment by nicholaszein** [comment]
Hi @stormit!

It has been a while... Since at the time of the publishing this issue, a lot has changed. Including in the latest version of Elementor (v3.24.0). We completely reworked the way the Improved CSS Loading experiment, and by version 3.24.2 we shouldn't have this problem happening again.

For this reason I'm closing this issue.

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [Elementor System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Kind regards
