### ISSUE TITLE
🔗 🔃 🐞 Bug report: container gap offset (Merged with #18309)

### ISSUE THREAD

**Issue by bobhuf** [elementor/elementor#17985]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Container items that have a gap defined need their widths to be subtracted with that gap or the layout will break.

For instance: 2 container items of 50% with a parent container gap of 20px should get:

`--width: calc(50%  - 20px);`

in stead of:

`--width: 50%;`

### Steps to reproduce

N/A

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

== WordPress Environment ==
    Version: 5.9.1

    Elementor
        Version: 3.6.0-dev40
        Author: Elementor.com

    Elementor Beta (Developer Edition)
        Version: 1.1.1
        Author: Elementor.com

    Elementor Pro
        Version: 3.7.0-dev26
        Author: Elementor.com

**Comment by davidmondok** [comment]
While I agree with you, that we will need a mechanic to take gaps into account(else it will be very difficult to build layouts easily) your numbers are off.

It should be `--width: calc(50% - 10px);` instead of `--width: calc(50% - 20px);` because there is only one gap between those two columns, so you were deducting more than necessary.

There is always one less gap in a row as the number columns, so you will have to take that into account.

In case of three columns with a gap of `20px` the width would have to be `--width: calc(33.333% - (20px * 2 / 3));`, or `--width: calc(25% - (20px * 3 / 4));` for 4 columns.

**Comment by black-eye** [comment]
The problem with the flex gap feature is, that it works as expected only when the flex-wrap is set to no-wrap. Otherwise the gap width is added to the container width and causes the problem described here (the content won't fit as expected).

Unfortunately the flex gap is not suitable for the situations like these. For the layout purposes we should be using CSS grid, but I'm afraid that's a dream far far away (considering how long it took to implement at least the flex container). For some reson Elelementor decided to resign on implementong CSS grid and brings us only a half part of the solution, which is dated yet before releasing.

I think the best way how to solve the problem is good old "negative margin, positive padding" approach. Give some padding to each child container and a negative margin of the same value to the parent and you are done. The value of the gap is 2 times the padding value. It can be also done as CSS preset globally. 

The drawback of this method is that the padding and margin values are "blocked" for other usage (e.g. you cannot set different inner padding for the inner container). You have to bear in mind that when you change the values for margins and padding for the respective containers, the layout gets broken.

**Comment by davidmondok** [comment]
@black-eye I have actually implemented exactly that approach (negative margins + additional max-width) but without having to set things manually but with a simple on/off switch and everything will be taken care for you in the background. I combined this with a couple of other additional features that help us be a lot more productive and deliver cleaner designs like:

- Define more global content widths additionally to the boxed width
- Define a global horizontal section padding and also vertical spacings between containers (you can pick between margins and paddings).
- Define row-gaps for sections (affecting the vertical gap between columns)
- Define row-gaps and column-gaps seperately for columns (affecting the contained widgets).
- Overwrite the column-gaps in your global layout settings (responsively)
- Disable vertical paddings for columns per section or define them separately
- ...

All of these features are integrated with each other, so whatever you set up, the feature for fixing inconsistent column alignments always works. Drop me a message if anybody is interested in this. I might move all this into its own plugin.

**Comment by perks98** [comment]
Hi,
I'm not great with CSS but I've put together this for the gap spacing issue:
.e-container {
	--parent-gap: var(--gap, 0px);
}

.e-container > .e-container {
	--parent-gap: inherit;
	width: calc(var(--width) - var(--parent-gap));  
}

I've added this to a DEV version to the theme customiser 'Additional CSS' area. There is still a minor left and right gap still though.

**Comment by nicholaszein** [comment]
Hey everybody!

### 🔃 I'm Merging this issue with issue #18309.

Which is on the same subject but is more detailed.

Please, feel free to continue the conversation there. 😉 

Nick
