### ISSUE TITLE
PHP Notice:  A non well formed numeric value encountered

### ISSUE THREAD

**Issue by JidWictut** [elementor/elementor#17998]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello,
I have noticed that in the  WP error log this entry appears very often:

[22-Feb-2022 03:39:27 UTC] PHP Notice:  A non well formed numeric value encountered in /www/htdocs/w0187f99/dinkelliebe.de/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php on line 748
[22-Feb-2022 03:39:27 UTC] PHP Notice:  A non well formed numeric value encountered in /www/htdocs/w0187f99/dinkelliebe.de/wp-content/plugins/elementor/includes/libraries/bfi-thumb/bfi-thumb.php on line 751

Regards

### Steps to reproduce

I use the latest Version of Elementor/Pro.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.5.11
	PHP Version: 7.4.26
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
== WordPress Environment ==
	Version: 5.8.3
	Max Upload Size: 200 MB
	Memory limit: 512M
	Language: de-DE
	Parent Theme Name: Astra

**Comment by rami-elementor** [comment]
Hi @JidWictut ,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/pojome/elementor/issues/new?template=Bug_report.md).

Please feel free to open a new issue in accordance with these guidelines.

Regards,
