### ISSUE TITLE
🚀 Ability to insert a custom icon (svg) for nav menu.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18007]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi @rami-elementor , I apologize for asking this question. But does eleemntor have a program to add the ability to insert a custom icon in the nav menu widget? https://prnt.sc/u94LEWrmkdD7
This feature is really great and popular. Using third party plugins to meet this need is really painful. Will we see this feature in 2022?

### Describe the solution you'd like

Ability to insert custom icons for nav menu items. https://prnt.sc/Wuu7Lg5Nj9TA

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!

**Comment by sanbec** [comment]
It is very nice that the icons for the dropdown and the "burger menu" are customizable, I congratulate you. 

BUT, what was asked here was to add icons for EVERY menu entry, as you can **clearly see in the screenshots** provided in the description.

The problem I see is that those icons should be added where the menus are actually created, in Desktop > Appearance > Menus.

There is a plugin that allows to add icons, it's called (surprise!) Menu icons https://wordpress.org/plugins/menu-icons/

On the other hand, it would be desirable that in Elementor's "site settings" the menus could be edited, and that custom fields could be added so that the menu widgets could show for each entry different icons, colors, tooltips, etc...

**Comment by FullstackWEB-developer** [comment]
I don't know why this popular feature hasn't been added yet.
