### ISSUE TITLE
⛔ 🚀 Feature Request: Custom URL for Gallery Images

### ISSUE THREAD

**Issue by katart** [elementor/elementor#1801]
Currently, the Gallery Images have 3 options for Links:

1. Media Link
2. Attachment Page
3. None

It would be nice to add a 4th option:

4. Custom URL

You will have to add a new field in the Media Details section called "Custom URL"

**Comment by lgibson212** [comment]
https://github.com/pojome/elementor/issues/216

**Comment by ChriKn** [comment]
Strange this isn't a thing.
Why do I have to use a carousel (which doesn't properly work on mobile view...)
A solution would be great !

**Comment by rogerhorning** [comment]
Is this something that is going to be addressed?  It seems like basic and needed functionality.

**Comment by MamadioCMCC** [comment]
Please address this! The lack of this feature is very annoying.

**Comment by TrueAegis** [comment]
Is there any word on if this feature will be added or looked in to?

**Comment by nicholaszein** [comment]
Hello everyone!

Thank you for submitting your suggestions, and for showing interest in this enhancement! 🙏 

While the issue pointed refers to the Image Carousel, both widgets behave in quite the same way. They both use the default WordPress Gallery component. The only difference is that with the Image Carousel, instead of showing your images in a grid, they are shown, well, in a carousel... So I wanted to take this opportunity to explain why this is something we are not currently planning to add to both the Image Carousel, Basic Gallery, and Gallery (Pro) widgets:

We understand the need to set different links for each image in these widgets, but we also want to maintain our widgets as close to the default WordPress behavior as possible to allow for backward or any other compatibility. Since there is no field to determine a URL for each image in the default WordPress Media Attachments, there is also no built-in way to find that information and apply it to each image, and we don't want to add custom information that may conflict with other plugins, custom scripts, or break if WordPress decides to change the way attachments behave.

This is why we have no plans to add this functionality to these widgets. We hope you can understand our decision.

Kind regards
