### ISSUE TITLE
🐞 Bug report: Not Editing page

### ISSUE THREAD

**Issue by ParassioClothing** [elementor/elementor#18178]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

not editing page

### Steps to reproduce

not editing page

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Not Editing Page

**Comment by rami-elementor** [comment]
Hi @XXX,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/elementor/elementor/issues/new?assignees=&labels=bug&template=bug.yml&title=%F0%9F%90%9E+Bug+report%3A+).

Please feel free to open a new issue in accordance with these guidelines.

Regards,
