### ISSUE TITLE
🐞 Bug report: Elementor Sidepanel is keep on loading

### ISSUE THREAD

**Issue by JMCoh04** [elementor/elementor#18262]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

![image](https://user-images.githubusercontent.com/28562972/160050899-a826c340-3c07-499c-8646-4f3f3754f8a6.png)

### Steps to reproduce

https://pixify.net/blog/fix-elementor-stuck-on-loading-screen/

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<html>
<body>

Operating System: | Linux |  
-- | -- | --
Software: | Apache |  
MySQL version: | Source distribution v5.7.32-35 |  
PHP Version: | 7.3.33 |  
PHP Memory Limit: | 768M |  
PHP Max Input Vars: | 3000 |  
PHP Max Post Size: | 256M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

</body>
</html>

**Comment by dertutor** [comment]
Hello, sorry for my bad english. I had the same problem. But then I put my WP installation in debug mode. And in doing so, I found that Elementor is not the problem, but the 'Table Addons for Elementor' plugin. If I deactivated this, everything worked again. Maybe it will help you too

**Comment by rami-elementor** [comment]
Hi @JMCoh04 ,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/pojome/elementor/issues/new?template=Bug_report.md). We just can't fix the problem if we can't recreate it. Please add the steps to reproduce and your system info.

Please feel free to open a new issue in accordance with these guidelines.

Regards,
