### ISSUE TITLE
🚀 Feature Request: More control over size of Flexbox Container

### ISSUE THREAD

**Issue by MateuszKlups** [elementor/elementor#18306]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

There is no easy option to set min/max size of Flexbox Container and using calculations. Having these options would save us much time on writing custom css in each containers and setting media queries. This would have a significant impact on the workflow using Flexbox Containers and would bring even more control of our layouts.

### Describe the solution you'd like

Adding to Flexbox Container options to set:
- min/max width/height
- calculated values in width/height/min-width/max-width/min-height/max-height, eg. calc(100% - 120px)

All of this options should have responsive option.

**Comment by perks98** [comment]
+1

**Comment by poziomapl** [comment]
During the development and rollout of version 3.6, this topic has already been brought up, but unfortunately with no response. This would be an excellent feature that should be mandatory in the new Container. There is even an example in thread [#17151](https://github.com/elementor/elementor/issues/17151) of how to implement this in the Elementor interface.

**Comment by pauserratgutierrez** [comment]
I feel very limited when creating layouts with Elementor basically because the lack of smart calculations.

I'm designing the Error 404 page with a height of 100% vh so basically I have a full page template. I also want to include my header and my footer. But then the Error 404 page takes more than 100% vh, it takes exactly: 404 height + (header height + footer height).

So in this case I would need Elementor to let me set the height of the Error 404 template to be: 100% vh - (header height + footer height).

So my suggestion here is make Elementor have smart calculations and pull dynamically data about each template's heights, widths... (Exactly how Global Color or Fonts work) so that if we change something, it automaticlly updates.

**Comment by joehdevwp** [comment]
+1

**Comment by nicholaszein** [comment]
Hello all! 

This is something that we are planning to bring in the future, and it's part of something more advanced that we've been researching for quite some time. There is already a discussion about this issue, and for the sake of being able to follow all the requests and gather all the feedback as well as understanding the real demand for this new feature, I will be closing this issue and merging it with issue [#2219](https://github.com/elementor/elementor/issues/2219).

Please continue the conversation there!

Best regards,

Nick

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

You can learn more about the new **Custom Units** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
