### ISSUE TITLE
🐞 Bug report: Copy/paste section does not include section CSS ID

### ISSUE THREAD

**Issue by raabmar** [elementor/elementor#18375]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I copy and paste a section to a new page, it does not include the CSS ID of that section.

### Steps to reproduce

- Give section a CSS ID
- Copy Section
- Go to new or any other page (in another tab)
- Paste section

Expected result:
- Section with CSS ID that is added in the source

Actual result:
- Section without CSS ID

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Elementor 3.5.6
Elementor Pro  3.6.4
Tested on two different installs

**Comment by rami-elementor** [comment]
Hi @raabmar ,

It's not a bug, It's by design.

In HTML, you can use multiple classes but [IDs should be unique](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id). You should not use the same ID more than one time in the page.

This is why when you copy&paste a section/column/widget, Elementor duplicates all the values except the ID.
