### ISSUE TITLE
⛔ 🐞  woocommerce notice does not support Ajax add to cart.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18628]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hi @avivu , As you know, elementor does not currently have the feature to add to cart as Ajax. So, I'm using the "jetwoobuilder" plugin add to cart widget, which allows to add to the cart as Ajax. Using Ajax Add to cart , I noticed important bug ...

**The problem is that the WooCommerce notice customization feature in elementor does not support adding to the cart as Ajax.**
In this case, if we add the product to the cart, no WooCommerce notice will be displayed! Therefore , The page must be reloaded to display the message.
Please review this issue and fix it in future versions. it's too important. thanks

### Steps to reproduce

If you add the product to the cart as Ajax, no notice be displayed.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hi, @Michaelgimii,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
