### ISSUE TITLE
🐞 Bug report: PHP Warning message in nav-menu.php since elementor pro version 3.7.0

### ISSUE THREAD

**Issue by astbarc** [elementor/elementor#18636]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm seeing lots of warnings messages in the php log since the update to elementor pro version 3.7

`PHP Notice:  Trying to access array offset on value of type null in /wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php on line 1459`

### Steps to reproduce

You need to have a nav menu in the website to see this error.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 11 v10.5.15
	PHP Version: 7.4.28
	PHP Memory Limit: 128M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - .htaccess file
	Elementor Library: Connected

**Comment by ShadowXVII** [comment]
This bug is present on lines 1446, 1459, 1470, 1483.
The `toggle_icon_normal` property is null, so it fails to enumerate the `library` key.

Perhaps needs a better guarding clause similar to the above which checks if it's got a value first.

![image](https://user-images.githubusercontent.com/446329/174726120-7b4b292c-3881-4824-914c-5f426b85bb12.png)

**Comment by Hans-101** [comment]
Same with me, with different themes, i.e. Blocksy.

**Comment by greenknightca** [comment]
This is also occurring for me in Elementor Pro 3.7.3 using a Hello child theme. Applying the dirty fix from @aloMalbarez is removing the warnings at least, but next Pro update will undo that unless it's patched.

**Comment by it7steve** [comment]
Have this too. Still an issue in lementor Pro 3.7.4 (using Hello child theme). When will it be patched ?

**Comment by deputt** [comment]
Glad to see this report. We lodged a similar report dated 6 July 2022, with the final reply from the Elementor team dated 16 July 2022:

>  I have got an update fromour Tier 3 team, and they have tested the website as per their investigation, the issue was caused because of the corrupted contents possibly caused by the 3rd party plugin. They created a new header template and found that there is no error with the new template.
> Our Tier 3 team and I also tried to reproduce the issue on our test sites, and we cannot replicate the issue on our end.
> So, It is advised to create new header templates with only Elementor and Elementor Pro activated and see if it helps!

Unfortunately, we haven't gotten down to doing what they suggested yet. Hope this helps.

**Comment by jordan-webdev** [comment]
@deputt I've actually been creating a new website with just Elementor and PRO and am getting this same error. It's a header I created. I did import it from another site I created, so just to be safe I recreated it. Same issue.

**Comment by deputt** [comment]
Recreating the menu(s) from scratch resolved it for me :)
------- Original Message -------

**Comment by jghaanstra** [comment]
Any news on this, it's flooding my error log.

**Comment by it7steve** [comment]
Yes, we still have this error on more than 20 sites, so that's 20 logs getting flooded, not very ecological ! Hey Elementor Pro, any news ?

**Comment by raabmar** [comment]
I get the same error - perhaps a hint to further troubleshoot, it might be related to a child theme. I generated a child theme with https://wordpress.org/plugins/child-theme-configurator/ and from there on some things were a bit strange on my site. The plugin also gave me a hint to those errors. I am not sure yet, if they have been there before generating the child theme

**Comment by Jojo852** [comment]
Exactly as @ ShadowXVII described... "This bug is present on lines 1446, 1459, 1470, 1483.
The toggle_icon_normal property is null, so it fails to enumerate the library key."

I'm using:
Elementor Version 3.7.8
Elementor Pro  Version 3.7.7
PHP 8.0

Everything was working great until a couple of days ago...now LearnDash courses cannot be found (404 error) in the frontend

I'll try recreating the menus as @deputt suggests before going through a debug routine.

**Comment by Joinfield** [comment]
Any news here? Still have it!

**Comment by rb-ar** [comment]
Still facing this issue. Recreating the menu from scratch did nothing, just like deactivating every plugin and only using hello-elementor. Even recreating the menu from scratch after having deactivated all plugins and the child-theme did nothing.

**Comment by kino89** [comment]
same for me, the bug persist.

**Comment by youlikeitcp** [comment]
Here the same. Contacted helpdesk of elementor:  They ask for a screenshot Lol.
Script above solved floating logfiles

**Comment by Jojo852** [comment]
I got rid of it a while back but I've got it again, too.  Support suggested WPRocket was causing the error.  But that wasn't it.  I rolled back PHP, rolled back Elementor, rebuilt all my nav menus... and it worked.  Then Elementor said they had fixed the bug so I put everything up to date.  Since the site was working, I didn't bother checking the error log.  And in any case, as soon as you tell support there is a php error showing up, they say "just disable the php error log"...lol.

**Comment by Jojo852** [comment]
PHP Warning: Trying to access array offset on value of type null in /mydomain/public/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php on line 1446, 1459, 1470, 1483

**Comment by Jojo852** [comment]
I found this on the site xtemos with the exact [same error mentioned ](https://xtemos.com/forums/topic/trying-to-access-array-offset-on-value-of-type-null-in/) 
 
And this was Elementor support's response:
“As previously mentioned, you have a deprecation notice, which means that something is not compatible with Elementor, and an error with our Nav menu widget, but the header was not built with Elementor so that is out of the scope of Elementor’s technical support since we do not provide support for features that were not built with Elementor’s theme builder or standard WordPress features.”

What's interesting is they say "something is not compatible with Elementor"...  And yet,  I have two sites with the same plugins.  One site shows this error, and the other doesn't.  In fact, the one that doesn't have this error is way more complicated and has more plugins than the one that does.  

As others have done, I have also rebuilt the header and the footer.  I've also compared the settings of both sites and disabled the header to see if that would change anything.  Upon deactivating the plugins... the error shows up with all plugins deactivated and only Elementor and Elementor Pro activated.

My site is working fine but I really hate that error message...

**Comment by Jojo852** [comment]
Rolling back to php 7.4 results works to stop the error message

**Comment by freschstudio** [comment]
> it happens with php 7.4, 8.0, 8.1
> 
> dirty fix on every line where it happens:
> 
> `if ( 'svg' === ($settings['toggle_icon_normal']['library']??'lol') ) {`

Thanks, this _dirty_ fix still works. It stopped flooding PHP error log.

Specs:
- Elementor 3.8.1
- Elementor Pro 3.8.1
- PHP 8.0.24
- WordPress 6.1.1

**Comment by Jojo852** [comment]
So, just to confirm, I should try **replacing** every line of code where the error occurs with this line? 

if ( 'svg' === ($settings['toggle_icon_normal']['library']??'lol') ) {

**Comment by freschstudio** [comment]
> So, just to confirm, I should try **replacing** every line of code where the error occurs with this line?
> 
> if ( 'svg' === ($settings['toggle_icon_normal']['library']??'lol') ) {

Yes. Make sure to backup **nav-menu.php** first. 

You can also replace 'lol' with 'fix' or any other string.

**Comment by Jojo852** [comment]
Yes, of course.  I'll try it on my dev site first.
I kinda like 'lol' :) 

Thanks!  I'll let you know how it goes.

**Comment by Pikamander2** [comment]
This has been flooding our error log for months as well. I'm glad there's a workaround but this really needs a fix on the plugin side.

**Comment by Coyote6** [comment]
Is there a way to up the priority on this fix? There is a simple solution posted above.  Thanks.

**Comment by mcrowell** [comment]
+1

**Comment by Jojo852** [comment]
+2

**Comment by gsuez** [comment]
+3

**Comment by kpapamanos** [comment]
+4

**Comment by SoftIcePink** [comment]
Had to rollback to PHP 7.4 to fix it.
I know some said it didn't work.

**Comment by rb-ar** [comment]
@Coyote6 @mcrowell @Jojo852 @gsuez @kpapamanos 
Use the thumbs-up emoji response on the very first comment of this issue. That is what ups the visibility.

**Comment by FullLinks** [comment]
This bug is still present on the latest version of elementor.
It is so hard to code properly and add a simple variable check? Looks like some code is written by amateurs.
`if ( 'svg' === ( $settings['toggle_icon_normal']['library'] ?? '' ) )`
On a high traffic site the error log is flooded and is not a solution to update the file manually each time elementor is updated.
@nicholaszein

**Comment by jlemonz** [comment]
I think they won't fix this because they want to remake menu widget with mega menu etc

**Comment by FullLinks** [comment]
I tried to raise the issue https://github.com/elementor/elementor/issues/20766 and they closed it since is not elementor's fault. So we need to find ourselves invalid items, instead of them fixing the code and do some proper validations.
Same thing happened when they messed the global colors with an update, they asked the clients to rebuild the websites instead.

**Comment by aloMalbarez** [comment]
at least we know the safe values to inject there? is it a meta in the post template?

**Comment by jlemonz** [comment]
It looks like beta 2 is going to fix this finally

**Comment by raabmar** [comment]
Is this just closed for fun now, or is there a solution? I don't get it

**Comment by FullLinks** [comment]
Elementor 3.9.2 looks like it fixed
