### ISSUE TITLE
⛔ 🐞 WooCommerce notice in elementor have a lot of free space at the bottom by default.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18649]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi
This is not really a bug, but it is something that severely damages the UI. As you know, in elementor we can customize WooCommerce notifications. But the problem is that WooCommerce notifications have a lot of empty space at the bottom. Please look at this photo : https://prnt.sc/H9v2JRcV5Cir

Please check this if possible @avivu. 

thank you

### Steps to reproduce

Customize WooCommerce notifications with elementor. If you look closely at the WooCommerce notifications that appear, they have a lot of space at the bottom. This space will only be removed using css And there is no control in elementor to remove this space.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hi,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- This feature is not yet supported by Elementor.

### ✅ What you can do to solve your issue:
- Please cast your vote in Feature Request #25711 

### 👍 For now, that's all we can help with. 

Kind regards
