### ISSUE TITLE
✔️ 🚀 Feature Request: Dynamic tag for countdown widget (Duplicate of #7737)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18701]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Please add the possibility of making the countdown time dynamic : https://prnt.sc/NmwPAi7VXHtS
This feature is now available in the jet elements plugin countdown widget : https://prnt.sc/9dHmviQ7Z5U2

It is also great if you add a separator to the countdown widget. This item is also available in the jet elements plugin.
https://prnt.sc/uxzS8rhuRliZ

thank you!

### Describe the solution you'd like

**Dynamic tag for countdown widget**

**Comment by tizum** [comment]
Guys, this functionality is very necessary in Elementor Pro, because I'm currently using the JetElements plugin to subsist the need for countdown with dynamic tag, even leaving it only enabled in widgets, it's an extra script to load on the site that is even detected on google pagespeed hindering the site in having a better performance.

Even the configuration of Elementor's current style is very good and I like it, so that's all it takes to be 100%, less a plugin and more performance.

Looking forward to hearing from you, have a great weekend!

**Comment by marreiradigital** [comment]
+1 Up

**Comment by dyonatandias** [comment]
+1

**Comment by DaviDuarte22** [comment]
+1

**Comment by royallogic** [comment]
+1 very important

**Comment by dantetesta** [comment]
+1 go go go

**Comment by arielk** [comment]
I merged this issue with another issue https://github.com/elementor/elementor/issues/7737 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by nicholaszein** [comment]
Hello, everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor Pro **v3.10**! 🥳 

You can learn more about it [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
