### ISSUE TITLE
🚀 Feature Request: Registration Form | Activation Email Template + SMS Activation (Duplicate of #5184 + Won't-fix)

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#18702]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

So, trying to create a Form for Users Registration i cant create an email to get the User Activation.
This should be a MUST for Users Registration.

### Describe the solution you'd like

1. have the posibility to send an activation email wih a custom template.
2. Add a 3rd party integration with SMS Providers to activate account with SMS Code.

**Comment by 79ho3ein** [comment]
+1
This is really great and needed. I think the form widget in elementor has the ability to become a professional login and registration widget. Just like the action pack plugin, which developed the elementor form in this area.
Please see this issue : #16401

**Comment by nicholaszein** [comment]
Hello @maurocarreraok, nice to see you here!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #5184 , which is on the same subject. For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

⛔ After reviewing your request for adding **3rd party integration with SMS Providers**, we have decided not to add this to our roadmap for the time being. You can already achieve this using the **[Zapier integration](https://elementor.com/help/zapier-elementor-integration/)** already available with Elementor Pro's Form [Actions After Submit](https://elementor.com/help/actions-after-submit/).

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
