### ISSUE TITLE
🚀 Remove JQuery from Front-end (Performance improvements)

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#18750]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Removing jQuery from the Front-end is effective in increasing performance. This feature is applied in the new version of bricks builder (rival page builder). So please run this in elementor.

### Describe the solution you'd like

Remove JQuery from Front-end

**Comment by rami-elementor** [comment]
Hi @Joliamendi 

I'm closing this issue as this request is already part of our roadmap.

I should add that each Elementor version improves the frontend code. In most cases we can replace jQuery with Vanilla code but keep in mind that Elementor serves over 11 million active websites, we have to be careful when deleting old jQuery code as it can break sites.

Addon developers need time to update their code when we change our code base. This is why we have a [deprecation proccess](https://developers.elementor.com/docs/deprecations/). It takes time, but it's much safer that way. Eventually all jQuery code will be replaced with Vanilla JS.

**Comment by vincentvanhoven** [comment]
@rami-elementor Sorry to revive an old issue, but I couldn't help but notice that the removal of jQuery isn't listed on the public roadmap ([link](https://elementor.com/roadmap/#)). I also couldn't find it in the Deprecations Archive ([link](https://developers.elementor.com/category/deprecations/)), though there is a mention of a jquery-dependant package being deprecated and then deleted.

I understand this is a fairly lengthy process because the Elementor ecosystem needs to catch up to any drastic changes, but could you elaborate on where it currently stands on the roadmap?

Eagerly awaiting this improvement.

**Comment by rami-elementor** [comment]
@vincentvanhoven you won't see this in the public roadmap as the roadmap mainly lists features while jQuery removal is a tech issue.
