### ISSUE TITLE
⛔ 🐞 Bug report: Can't find the order controls on mobile view when using Containers

### ISSUE THREAD

**Issue by donwattz1459** [elementor/elementor#18775]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

When I try to reorder the columns in a container, the order field does not show on mobile to reorder the items on mobile. 

### Steps to reproduce

Create a container, go to mobile view and go to advanced and click on order then custom.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.16.1
	MySQL version: mariadb.org binary distribution v10.5.4
	PHP Version: 7.4.8
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Not connected (cURL error 28: Operation timed out after 5000 milliseconds with 0 bytes received)

== WordPress Environment ==
	Version: 6.0
	Site URL: https://jarringjars.com
	Home URL: https://jarringjars.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: info@wattzwebdesign.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15

== Active Plugins ==
	CartFlows
		Version: 1.9.1
		Author: CartFlows Inc

	Elementor
		Version: 3.6.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.1
		Author: Elementor.com

	Fluent Forms
		Version: 4.3.7
		Author: Contact Form - WPManageNinja LLC

	FluentSMTP
		Version: 2.1.1
		Author: FluentSMTP & WPManageNinja Team

	GridPane Redis Object Cache
		Version: 1.5.6
		Author: Version Forked by GridPane | Till Krüss

	Kadence WooCommerce Email Designer
		Version: 1.5.1
		Author: Kadence WP

	Metorik Helper
		Version: 1.5.2
		Author: Metorik

	Nginx Helper
		Version: 2.2.2
		Author: rtCamp

	SEOPress
		Version: 5.7.2
		Author: SEOPress

	ShortPixel Image Optimizer
		Version: 4.22.9
		Author: ShortPixel

	SVG Support
		Version: 2.4.2
		Author: Benbodhi

	WooCommerce
		Version: 6.5.1
		Author: Automattic

	WooCommerce - ShipStation Integration
		Version: 4.1.48
		Author: WooCommerce

	WooCommerce Cart Abandonment Recovery
		Version: 1.2.18
		Author: CartFlows Inc

	WooCommerce Cost of Goods
		Version: 2.11.1
		Author: SkyVerge

	WooCommerce Product Add-Ons Ultimate
		Version: 3.11.0
		Author: Plugin Republic

	WooCommerce Square
		Version: 3.0.2
		Author: WooCommerce

	WordPress Backup & Security Plugin - BlogVault
		Version: 4.78
		Author: Backup by BlogVault

== Must-Use Plugins ==
	WP CLI Login Command Server
		Version: 1.3
		Author: Evan Mattson

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 1 of 1PHP: 2022-05-24 23:17:59 [notice X 6][/var/www/jarringjars.com/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	CartFlows: Incompatible
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

			

https://user-images.githubusercontent.com/16137152/170842777-03bf76cc-05a3-4f5c-8285-242fd4c560e6.mov

**Comment by nicholaszein** [comment]
Hello @donwattz1459 ,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- The control you're mentioning is there, and it's working as expected.
- When you select the "Custom" option while on the Desktop view, the mobile view will inherit that selection unless you change it.
- Your video explains this exactly how it is.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
