### ISSUE TITLE
🐞 Bug report: Critical vulnerability allowing not paying users browse protected content

### ISSUE THREAD

**Issue by kangarko** [elementor/elementor#18781]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

We are using a simple code snippet from the official support to hide
content from customers who did not purchase a given course.

Official snippet from your support is here:
https://github.com/elementor/elementor/issues/8062#issuecomment-524805319

It stopped working and showing up completely after migrating to the
Flexbox Container experiment. It still works on the old sections that
are not migrated yet: https://i.imgur.com/nb9Ywt9.png but not sections
are shown for the container: https://i.imgur.com/q31IIRv.png

Matej 

### Steps to reproduce

See above

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

https://pastebin.com/SEQctpKf

**Comment by kangarko** [comment]
@shilo-ey any news?

**Comment by udidol** [comment]
Hi @kangarko,
The snippet in the link you provided indeed does not work for the Container element.
Notice that in line 3 of the snippet, it checks for `section_advanced`. 
This is a controls section that exists in Section elements in the "Advanced" tab.
It indeed does not exist in the container tab, as your own screenshots can attest.

You would have to decide where you want to position your custom control section in the Container element. Is it after the "Layout" section? Before the "Layout" section? Somewhere else completely?

Once you decide on that, all you have to do is add the name of the section you want to inject your own custom controls section to the `if` statement.

For example, if you would like to add it after the "Layout" section in containers, you can change the if block to run as follows:
```
if( 'section_advanced' === $section_id || ( $section instanceof \Elementor\Includes\Elements\Container && 'section_layout' === $section_id  ) ) {
```
This way, your section would be added after the layout section in containers.

There is also another action you can listen to, which is even more accurate, and does not require you to add an `if` statement to check where you are at all, but you can just directly add your controls: `'elementor/element/container/section_layout/after_section_end'` - Notice that this targets the `container` element and the layout section. 

Then, in your callback function, without checking which section it is, you can just run the code that follows the `#Start Custom Settings Section` line in the example in the ticket you linked above.

One last thing - this is not a critical vulnerability. Going forward it would be better not to use such wording for no good reason, because it can lead to "boy who cried wolf" situations.

Good luck!

**Comment by kangarko** [comment]
Thanks for addressing this, and sorry for the confusing label, it appeared as critical on my production site where paying customers cannot view certain content, but I understand that Container is still marked as an experiment.

Good luck with development of Elementor!
