### ISSUE TITLE
⛔ 🐞 Bug report: My account widget don't show Woocommerce notices

### ISSUE THREAD

**Issue by AV-Projects** [elementor/elementor#19007]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Woocommerce my account widget don't show notices when user try registrate with bad email or try login with bad pass. If I put native [woocommerce_my_account] shortcode notices show up but then I lost all elementor styling capability. Tested My Account widget with Woocommerce Notice widget together and this combination also don't work. 

### Steps to reproduce

Install latest Wordpress, Woocommerce, Hello Theme, Elementor & Elementor Pro. Edit Woocommerce My Account page with Elementor. Add My Account Widget.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<html><body>

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | MariaDB Server v10.3.35 |  
PHP Version: | 7.4.29 |  
PHP Memory Limit: | 256M |  
PHP Max Input Vars: | 10000 |  
PHP Max Post Size: | 64M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

</body>
</html>
<html><body>

WordPress Environment |   |  
-- | -- | --
Version: | 6.0 |  
WP Multisite: | No |  
Max Upload Size: | 64 MB |  
Memory limit: | 40M |  
Max Memory limit: | 256M |  
Language: | en-US |  
Debug Mode: | Active

</body>
</html>

**Comment by Bamstian** [comment]
I can confirm this is also happening to one of my sites. Still.

**Comment by sunjava11** [comment]
Happening for me too

**Comment by nicholaszein** [comment]
Hello everyone!

Thank you for reaching out, and thank you for your patience! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We have decoupled WooCommerce Notices from the My Account widget and created a dedicated WooCommerce Notice widget so users can control the Notices design, and position in the layout. This was a request by public demand.

### ✅ What you can do to solve your issue:
* Remember to add the WooCommerce Notices widget when editing your My Account template as explained in these articles.
   * [WooCommerce Notice Widget](https://elementor.com/help/woocommerce-notice-widget/)
   * [WooCommerce Notice Settings](https://elementor.com/help/woocommerce-notice-settings/)
   * [Elementor 3.6 Pro: Elevate the Shopping Experience on Your Website With a Strong Brand Identity](https://elementor.com/blog/introducing-new-ecommerce-design-capabilities/)

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
