### ISSUE TITLE
✔️ 🔗 🔃 🚀 Feature Request: Add default padding for Containers in Site Settings > Layout (Merged with #19687)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19039]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I am facing an important problem in the container, I wanted to make a suggestion to solve this problem, in addition I wanted to ask if you have a solution for it?
In section, all sections had a normal distance around them, and this meant that the content always had a normal distance around it.
Also, if we viewed the website with a mobile phone, there was also that gap and it prevented the content in the section from sticking to the side of the screen.
**But in the container, this distance does not exist and all the content sticks to the edge of the mobile screen and even the desktop.** This is really problematic. So we have to consider a padding from the left and right for the mother containers, which does not seem interesting and standard.
**So my suggestion is to please add a new option to site settings > layout , to determine how far the content of the website is from left and right.** 
I think this is now one of the most important container problems in elementor. I do not know. Maybe it's just me who has a problem with it.

### Describe the solution you'd like

please add a new option to site settings > layout , to determine how far the content of the website is from left and right.**

**Comment by nicholaszein** [comment]
Hey @Michaelgimii!

I am organizing all issues related to Containers, and it seems this issue was solved with the Global Padding options on `Site Settings > Layout`. There was another issue raised where we announced it was solved!

I'm 🔃 Merging this issue with issue #19687, which was on the same subject, and marking it as solved!

✔️ Please feel free to check it out and update your plugin to the new version if you haven't already!

Thanks for your contribution! 🙏
