### ISSUE TITLE
🐞 Bug report: Multi Site Absolute Link is not working.

### ISSUE THREAD

**Issue by javothemes** [elementor/elementor#19062]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have multi network sites.

Let's say

domain.com/site1/contact/

When I add the url .. "/contact/"

It goes to "domain.com/contact/".
I was expecting to move to "domain.com/site1/contact"

<img width="594" alt="image" src="https://user-images.githubusercontent.com/28474304/176988153-bc5fd44d-14f6-48eb-beb6-e09eb63debb0.png">

We are not able to add full URL due to import, export data which we will pass it to our clients.

Site URL is this. "domain.com/site1/"
But the absolute URL detects only "domain.com/"

Thank you,

### Steps to reproduce

We just added any buttons and list widget. But it's not working.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

I can't provide this. But this problem is just a normal case in Elementor

**Comment by rami-elementor** [comment]
It's not a multisite issue, it's how browsers interpret relative addresses. Try using `./contact/` or `./../contact/` to match your needs.

**Comment by javothemes** [comment]
Hello,

I already tried. But it's not working. 

You should just have a test with a button. 
If you can, please have a test on a multi-network site.


<img width="319" alt="image" src="https://user-images.githubusercontent.com/28474304/177046120-c0550b46-731c-4714-a1cc-cd93580430ef.png">

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/28474304/177046097-133fef77-49f3-4674-a284-b54f602ba8a2.png">

**Comment by rami-elementor** [comment]
Ok, I see a bug.

When using `./sample-page/` in the link control, the html is `<a href="http://./sample-page/"`

**Comment by javothemes** [comment]
Thank you,

I also believe the multi-site permalink should be also added. Because the site URL is saved as the full of site URL in wp-option table. 

So when you add "/contact" on a multi-site ( ex. https://abc.com/site1 )
Then it should be linked to "https://abc.com/site1/contact".

Not to "https://abc.com/contact". 

Anyway it should be fixed soon. 

Thank you for the great! plugin

**Comment by pulla** [comment]
It should be fixed soon. It's really bothering.

**Comment by rami-elementor** [comment]
**Update:**

We talked about this issue with our R&D teams and they checked the issue.

All input fields should be escaped to harden the plugin security. WordPress recommends using the `esc_url()` function to escape URL field before outputting them.

[Elementor escapes URLs](https://github.com/elementor/elementor/blob/6e3e13789340b0134bfe00fe96fc6954ae4b71ee/includes/base/element-base.php#L382) using the [esc_url() function](https://github.com/WordPress/WordPress/blob/866abfda9f7ec056e5828da2c7b3736799c72ef0/wp-includes/formatting.php#L4362). This function [requires](https://github.com/WordPress/WordPress/blob/866abfda9f7ec056e5828da2c7b3736799c72ef0/wp-includes/formatting.php#L4382-L4390) the URL to contain a scheme (http://) prepended, unless it's a relative link starting with `/`, `#` or `?`. Seems like you can't use `./` or `../` in URL fields.

As a WordPress plugin, we have to follow WordPress security recommendations. We can't change this behavior as it is inherited from a WordPress core function.

It's not an Elementor bug so I'm closing this issue as "won't fix" because removing `esc_url()` will loosen security.

My recommendation is to use absolute URLs or open a WordPress bug report.
