### ISSUE TITLE
🐞 Bug report: ui issue in Progress Bar widget

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19422]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

There is a problem in the UI of this section: https://prnt.sc/8qCbk3_FsAhe

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by rami-elementor** [comment]
Hi @Michaelgimii ,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/pojome/elementor/issues/new?template=Bug_report.md).

Please feel free to open a new issue in accordance with these guidelines.

Regards,

**Comment by Michaelgimii** [comment]
@rami-elementor , I zoom in more. If you pay attention, the input field is a little shorter than the dynamic box.

![download](https://user-images.githubusercontent.com/88034902/186403638-f0f9a857-c5fd-44b5-a4c4-b3d9748b8088.png)
