### ISSUE TITLE
🚀 Feature Request: global style for all widgets (The style of the widgets is dynamically received from the template widget)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19432]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi elementor team!

A new feature to create a global style for all widgets would be great. please pay attention. **This is completely different from the global widget.**
I will give an example to use this wonderful feature.
Let's say we use 5 loop builder widgets (or any other widgets) on the website. All these 5 widgets have a similar style. If we want to change the style of these widgets, we must apply the changes to each of these widgets. This is very time consuming.We may also forget to change some styles. But using this feature, we set one of these 5 widgets as a template. **If we change the style of that widget, it will be dynamically applied to the other 4 widgets.** This feature is really great and needed.
We can use this method for all widgets.

### Describe the solution you'd like

For each widget, set a template widget. Therefore, we can connect similar widgets to it to get the style dynamically. It is optional whether the desired widget is standalone, or follows its own template widget to get styling.

**Comment by perks98** [comment]
Sounds like you are asking for dynamic presets so you can change the base defaults of a widget then you can add on top of.

So almost like this [[https://ultimateelementor.com/widgets/presets/](https://ultimateelementor.com/widgets/presets/)] but you create your own presets?

**Comment by perks98** [comment]
Hi @79ho3ein, I do get what you mean. What I meant from that link provided is how you are looking for it to be implemented (although in that link that plugin provider uses static presets), so that once you drag a widget, like an icon box widget, into the preview editor you can select from a dropdown for that widget to inherit a preset from a group of controls. I think in your use case you would stylise the widget then like with the global widgets right click to save but instead as a preset. So once you drag in the same widget again you can select that preset from a list of presets you define but you can then add on to the inherited values (e.g. add padding, margin or alignment)?

I can see this being better used than the global widget area as with global widgets you can't change the alignment or the input values, such as the button widget, if set as a global widget you can't change the link or button text unless it is applied to all of them.

**Comment by 79ho3ein** [comment]
hi @perks98 , Thank you for your participation. I apologize if sometimes I don't understand what you mean. I use Google Translate...

In my opinion, the global widgets feature that is now in elementor is not really useful. Because as you mentioned, we are not even able to change the link and other things by using this feature. This is of no use. If elementor checks how many users use this feature, I don't think even 5% use this feature.

About how to implement this new feature, the only idea I have at the moment is to add a new section called global style in the style tab of each widget. In this section, we can save or delete or sync widget styles.

**Example :**
We add the button widget and customize it. In the style tab > global style option, we save its style. 
After that, if we add another button widget, in the Style > Global Style tab, there will be an option (the style we saved in the previous step) Just select it and sync it.
After that, if we have 10 or any number of button widgets in the entire website, if we change the style of one of them, the style of the other button widgets will change immediately.

**2 tip :**

1- If this feature is added, we should be able to store multiple styles for each widget. Because there may be 3 types of buttons with different styles on a website.
2- We should be able to assign a name to each style we save.

**Comment by Michaelgimii** [comment]
This is a unique idea @79ho3ein. I look forward to it. But I hope we'll be alive when elementor adds it, or at least our hair hasn't turned white.

**Comment by 79ho3ein** [comment]
hi friends
I will close this issue and discuss this issue in more detail in the new issue. I hope it will be noticed by the elementor team.

thank you
