### ISSUE TITLE
🐞 Bug report: Bug in custom font

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19439]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If you first click close on the custom font and then click edit, there is a problem.
Options are duplicated.

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by rami-elementor** [comment]
Hi @Michaelgimii ,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/pojome/elementor/issues/new?template=Bug_report.md).

Please feel free to open a new issue in accordance with these guidelines.

Regards,

**Comment by Michaelgimii** [comment]
hi @rami-elementor , Unfortunately, I cannot describe the details more precisely than this. 
Isn't the problem obvious? > https://prnt.sc/ULcCrixDupnD

If you pay attention to the two arrows in this screenshot, it is quite clear that the options (delete, edit, style, weight and even font preview) are displayed twice each. This bug was created in the last 4 versions.

**Comment by 1235news** [comment]
I don't know English properly and I want to cancel my subscription and the
worst thing is that even the admin section of my WordPress website won't
open.
please help.


   - *Sayed Ismail Hashimi*
   - *WhatsApp number: 00989044287758*
   - ***@***.****
   -
   -



‫‪Rami Yushuvaev‬‏ ***@***.***‬‏> در تاریخ شنبه ۳ سپتامبر
۲۰۲۲ ساعت ۱۳:۰۸ نوشت:‬
