### ISSUE TITLE
⛔ 🐞 Bug report: Editor Preview's Responsive animations are not as smooth when transitioning from Desktop to any other mode

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19525]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hi @shilo-ey , @rami-elementor 
When we switch between desktop, tablet and mobile mode in the editor, the size of the editor environment changes smoothly between desktop, tablet and mobile. By smoothly , I mean the video below.

https://user-images.githubusercontent.com/88034902/185379302-6fcf0080-5b47-49ab-800f-a072c6e517b3.mp4

But if the editor view is desktop and then we enter the tablet or mobile view, this smoothly does not exist. See the following video :

https://user-images.githubusercontent.com/88034902/185379865-be68b784-d8c8-4cb2-b06b-6e03b01c9d1d.mp4

As you can see in the video above, the switch from desktop to tablet and desktop to mobile does not work well (as in the video above).

**Generally**

Desktop to tablet : It has a problem
Desktop to mobile : It has a problem
tablet to mobile : without problem
mobile to tablet : It has a problem
mobile to desctop : It has a problem
tablet to desctop : It has a problem

In connection with the last two cases, when we switch from tablet or mobile mode to desktop mode, the editor switches to desktop mode in an italic way. To better understand the issue, I have slowed down the video below so that the problem is fully understandable.

https://user-images.githubusercontent.com/88034902/185383587-5bbc56e6-e6d3-4d78-82ee-29a111528d25.mp4

As you can see in the video above, the transition does not work well. While it should be like this :

https://user-images.githubusercontent.com/88034902/185384706-b8f2db12-c3e3-4458-9d5a-639593fd7b3c.mp4

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hi @Michaelgimii.

What you are describing is more of an issue related to how CSS animations work, browser rendering, and your device's performance.

When we apply the transition between every breakpoint, the animation duration is the same. But due to the performance of certain types of animations, in this case, **`width`** animation, CSS is known for struggling to render these animations as smoothly as transform animations. The larger the difference between widths, the more performance-intensive the animation is, and since these animations are not prioritized by the browser rendering engines, they might not look as smooth.

What you are suggesting would require us to create intricate and complicated logical rules for each transition between each of the 6 responsive modes, between each other. This would mean applying at least 36 different rules using both JS and CSS.

Performance-wise, this is simply much more resource-intensive and complicated to implement and would add many more points of possible conflicts between the variety of different preview modes, and interfaces we have. To summarize, the result of adding these conditions would be worse than simply having them as they are now. 

I see you have requested in #20911, to remove these transitions altogether. The idea here is that the user understands through visual hints that the viewport width is being changed. This also helps catch possible issues with the layout by visualizing the transition in real-time.

I will maintain the request in question opened and will eventually migrate it to Discussions. If enough users vote for this feature, we might consider adding it to our roadmap. But for now, we have no intention of making any changes to this UI, neither to fix the issue you are reporting here nor to remove the animation altogether.

I hope you can understand why.

Regardless, we appreciate your contribution! Thank you for taking the time to share your feedback! 🙏 

Kind regards
