### ISSUE TITLE
🚀 Feature Request: 

### ISSUE THREAD

**Issue by myrnaspringer1122** [elementor/elementor#19613]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Notice: Trying to get property 'ID' of non-object in /home3/myrnasp1/public_html/wp-content/plugins/elementor/core/base/document.php on line 249

Notice: Trying to get property 'ID' of non-object in /home3/myrnasp1/public_html/wp-content/plugins/elementor/core/base/document.php on line 249

### Describe the solution you'd like

please fix my elementor pro!

**Comment by rami-elementor** [comment]
Hi @myrnaspringer1122 ,

Thank you for the feedback.

While reviewing your report, we noticed it was missing one of the following key information:

* Prerequisites
* Steps to replicate
* Isolating the problem
* System info
* One issue per thread

In order to efficiently deal with the issues submitted to us, we ask that all submissions follow the guidelines outlined [here](https://github.com/elementor/elementor/issues/new/choose).

Please feel free to open a new issue in accordance with these guidelines.

Regards,
