### ISSUE TITLE
🐞 Bug Report : Bug in icon widget custom width (3.7 bug)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19809]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor team.

First of all, thank you for version 3.7.5. Many bugs have been fixed in this version. But there is still a bug in the width of the widgets that I mentioned in [this issue.](https://github.com/elementor/elementor/issues/19542)

If you add 4 icon widgets in a **section** and consider the width of each one as 25%, the height of the last icon will be higher than the other icons. I'm only experiencing this in icons and haven't checked other widgets.

![bug](https://user-images.githubusercontent.com/77163248/190265193-06d52c4e-5791-4bb5-81f9-8217def2b9c9.png)

Note that when you add the first icon, their width should be the default on the desktop, but consider 25% on the tablet. It will work in the same way on mobile. Please watch the video below.
Please note that this bug does not exist in the container.

### Steps to reproduce

https://user-images.githubusercontent.com/77163248/190230887-3daf8879-7db7-44b2-8125-a4ddb8a0554b.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by 79ho3ein** [comment]
This bug also occurs in the icon box widget.

**Comment by udidol** [comment]
This isn't a 3.7 bug.
This happens because each widget in in a section-column/container receives a margin, except for the last item (so the section/container doesn't get an unwanted bottom margin).

You can actually control this margin if you go to:
Site Settings > Layout > Gap between elements (if using Containers)
Site Settings > Layout > Widgets Space (if using Sections)

Elementor doesn't have a way of knowing you want to put all section contents in one row.

If you have Elementor Pro, it is easy to mitigate this. With Elementor Pro, you can add the missing margin by clicking on the last item in your section/container, going to the Advanced tab > Custom CSS, and adding the following:
```
selector {
    margin-bottom: 20px;
}
```
This will add the missing margin to the last element.

**Comment by 79ho3ein** [comment]
thank you @udidol , Yes you are right. I checked that this bug also occurs before 3.7. I apologize for taking up your time.
