### ISSUE TITLE
🚀 Feature Request: Provide a way to set "Equal Heights" to Loop Builder items

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19879]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor

Equal height is a necessary property for the loop builder. Please keep it in mind for the next version.

### Describe the solution you'd like

Equal height for loop builder

**Comment by nicholaszein** [comment]
Thanks @Michaelgimii,

we will consider this for our future releases! 😉 👍

**Comment by pauserratgutierrez** [comment]
> Thanks @Michaelgimii,
> 
> we will consider this for our future releases! 😉 👍 

But implement an option switch to activate / deactivate equal height 😊

**Comment by black-eye** [comment]
+1

**Comment by fabianenzensperger** [comment]
+1

**Comment by 79ho3ein** [comment]
+1

**Comment by perks98** [comment]
+1

**Comment by Gab1899ii** [comment]
I found a workaround solution with the following CSS code:

selector {
    min-height: 500px;
  max-height: 500px;
  overflow: auto;
}

I am using the Loopbuilder and have the post content widget, so needed to have them all aligned with the option to scroll since some content is longer than others.

You need to apply this code in the Loop Builder template for the main container that has all the widgets in it.

**Comment by perks98** [comment]
@Gab1899ii if you can wait until December 4th (or a bit later depending) version 3.9 should include an option for equal heights in the new update. You can follow the beta update in the discussions tab.
Also as a temporary CSS snippet since you are applying to the loop item parent container this also works without setting a limiting max height but it depends on your setup:

```
selector {
    height: 100%;
}
```

**Comment by Gab1899ii** [comment]
Thanks!

**Comment by fabianenzensperger** [comment]
With 3.9 the feature will come! 🤗

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this issue was solved with Elementor Pro **v3.9**! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
