### ISSUE TITLE
⛔ 🐞 Bug Report: The argument $finder_category_name is deprecated since version 3.5.0 !

### ISSUE THREAD

**Issue by zup44** [elementor/elementor#19916]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

As described in the title you are using the $finder_category_name argument in elementor which is deprecated since version 3.5.0 of WordPress. The location of the problem: wp-content/plugins/elementor/modules/dev-tools/deprecation.php:304.
Thanks for the correction!

### Steps to reproduce

You go to the following file: wp-content/plugins/elementor/modules/dev-tools/deprecation.php:304.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.39
	PHP Version: 7.4.25
	PHP Memory Limit: 512M
	PHP Max Input Vars: 16000
	PHP Max Post Size: 130M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://pixeltribu.com/creator
	Home URL: https://pixeltribu.com/creator
	WP Multisite: No
	Max Upload Size: 128 Mo
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Admin Email: afouquet31@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Kava Child
	Version: 1.0.0
	Author: Zemez
	Child Theme: Yes
	Parent Theme Name: Kava
	Parent Theme Version: 2.1.4
	Parent Theme Author: Crocoblock

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	Crocoblock Wizard
		Version: 1.2.5
		Author: Crocoblock

	Elementor
		Version: 3.7.7
		Author: Elementor.com

	Jet Appointments Booking
		Version: 2.0.0
		Author: Crocoblock

	JetBlocks For Elementor
		Version: 1.3.3
		Author: Crocoblock

	JetBlog For Elementor
		Version: 2.3.1
		Author: Crocoblock

	JetBooking
		Version: 2.5.2
		Author: Crocoblock

	JetCompareWishlist For Elementor
		Version: 1.5.1
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.7
		Author: Crocoblock

	JetEngine
		Version: 3.0.4
		Author: Crocoblock

	JetEngine - dynamic tables builder
		Version: 1.0.4
		Author: Crocoblock

	JetMenu
		Version: 2.2.3
		Author: Crocoblock

	JetPopup
		Version: 1.5.6
		Author: Crocoblock

	JetProductGallery
		Version: 2.1.6
		Author: Crocoblock

	JetReviews For Elementor
		Version: 2.2.7
		Author: Crocoblock

	JetSearch
		Version: 3.0.2
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.14
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.19
		Author: Crocoblock

	JetThemeCore
		Version: 2.0.7
		Author: Crocoblock

	JetTricks
		Version: 1.4.2
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 2.0.4
		Author: Crocoblock

	Query Monitor
		Version: 3.10.1
		Author: John Blackbourn


== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif par défaut
	Amélioration du chargement des ressources: Actif par défaut
	Optimisation du chargement du CSS: Actif par défaut
	Inline Font Icons: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	Kit de modèles pour importation et exportation: Actif par défaut
	Masquer les widgets natifs de WordPress des résultats de recherche: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Inactif par défaut
	Page d’atterrissage: Actif par défaut
	Echantillon de couleurs: Actif par défaut
	Widgets favoris: Actif par défaut
	Barre supérieure d’administration: Actif par défaut


== Journal ==
	
PHP: showing 2 of 2PHP: 2022-09-17 18:34:10 [notice X 769][/home/pixeltrilg/www/creator/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] L’argument $control_id est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-17 18:34:57 [notice X 496][/home/pixeltrilg/www/creator/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] L’argument $finder_category_name est obsolète depuis la version 3.5.0 ! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-09-20 17:45:14 [error X 2][https://pixeltribu.com/creator/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.6:3:1060720] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-09-23 15:44:21 [error X 9][https://pixeltribu.com/creator/wp-content/plugins/jet-appointments-booking/assets/js/public/appointments-init.js?ver=2.0.0:50:14] calendar.destroy is not a function 
JS: 2022-09-25 17:39:55 [error X 2][https://pixeltribu.com/creator/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.7:3:692080] T.getContainer is not a function 

Log: showing 5 of 52022-09-21 13:59:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-21 13:59:05 [info] elementor::elementor_updater Started 
2022-09-21 13:59:05 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-21 13:59:05 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-21 13:59:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]



== Elementor - Compatibility Tag ==
	
	JetBlocks For Elementor: Non compatible
	JetBlog For Elementor: Non compatible
	JetCompareWishlist For Elementor: Non compatible
	JetElements For Elementor: Non compatible
	JetProductGallery: Compatible
	JetReviews For Elementor: Non compatible
	JetTabs For Elementor: Non compatible
	JetWooBuilder For Elementor: Compatible
				
````

</details>

**Comment by nicholaszein** [comment]
Hello @zup44!

Thank you for contacting us.

While reviewing your report, we couldn't reproduce your issue on our testing environment. The Warning you're seeing is being generated by Elementor when a 3rd party add-on is using a deprecated method **from** Elementor and not the other way around.

We also noticed that your report was missing some key pieces of information:

* Steps to replicate _(please provide a detailed procedure to reproduce the issue, or share a video recording)_
* Isolating the problem _(you need to be able to reproduce this issue using only Elementor)_

Your issue most likely is related to one of your 3rd party add-ons.

To isolate this conflict please try these **Troubleshooting steps**:

⚠️  Backup your website before proceeding, and if possible do it in a staging environment! ⚠️ 

1. Disable/Deactivate all your plugins  except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2.  Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3.  Clear all types of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

If the problem persists, try contacting Elementor support (for Pro Users). To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon.

For non-Elementor Pro users, check out these resources:
* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

👍 Please feel free to open a new issue in accordance with these guidelines.

Regards,

Nick
