### ISSUE TITLE
Elementor generates a lot of additional code.

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#19936]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor developer.

The one criticism that has always been leveled at Elementor over the years is that it generates a lot of extra code. **But what is the real reason for creating additional codes in Elementor?**
This is the reason why in websites built with Elementor, the amount of DOM Element always skyrockets. For example, I add a button widget in Elementor and another page builder in a container. See the difference.

**elementor**

![elementor](https://user-images.githubusercontent.com/103376243/192750147-76a773fe-b80a-42ff-a0c0-1db9e2e2ca0e.png)

**Another page builder**

![page builder](https://user-images.githubusercontent.com/103376243/192750415-f817a5ba-55c3-4b5b-8ed7-a3e0f6c275da.png)

Adding the container was an important step to reduce the extra code in the Elementor layout. But do you have a plan to remove extra codes in Elementor widgets? If you have this decision, will this action cause the existing sites to break? If yes, is Elementor supposed to carry its extra codes forever?

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello @Joliamendi.

Thanks for submitting your issue.

It's difficult to answer your questions because I'm not sure what you mean. Yes, Elementor widgets have more tags inside, but each has its own reason to be there. Many of the features Elementor has rely on these nested elements. While we are constantly seeking to improve on performance, there are more considerations to be made regarding our widgets, like backward compatibility, motion effects, custom positioning, and transforms (just to mention a few) that would suffer if we simply removed everything from one day to another. So it takes time to plan how we can improve the DOM without causing breaking changes. 

I can't give you more information than that because the questions you are making are speculative.

Right now we can't provide any ETA on any of our plans or reveal our roadmap. But stay tuned, we are going to change this.

This is more of a support question, not really something we can answer here.

⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports** , and should not be used for support. ⚠️ 

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

For  💡 **New Ideas** or 🚀 **Feature Requests** please [create a new Discussion](https://github.com/elementor/elementor/discussions/new) in the [Discussions](https://github.com/elementor/elementor/discussions) tab.

Regards,

Nick
