### ISSUE TITLE
🐞 Bug Report: CSS for Image widget's fixed width of 48px for SVG files inside anchor tags is too specific

### ISSUE THREAD

**Issue by oooh-boi** [elementor/elementor#19952]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

This started to happen upon the latest update to Elementor 3.7.7 as I recall...

So if your website uses SVG (image) hyperlinks, the SVG itself gets squashed to the width of 48px due to some weird idea in Elementor's `frontend.css`

```
.elementor-widget-image a img[src$=".svg"] {
      width: 48px;
}
```

...it's on line #5455, `frontend.css`

Why in the name of God would anyone do that (sabotage)?! Please fix it up ASAP!

Cheers!

### Steps to reproduce

1) add svg with Image widget
2) turn it into hyperlink
3) enjoy

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

not relevant in this case

**Comment by nicholaszein** [comment]
Hello @oooh-boi! 

Thank you for submitting your issue! 🙏 

This was [added](https://github.com/elementor/elementor/commit/7573bbd3881cbd801e1fb6af72727f9479b344c8) on version 2.3.0 to fix this issue: #5987.

📋 This issue is a **Duplicate** of #6136, which is on the same subject. For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, please remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
