### ISSUE TITLE
🚀 Feature Request: Container - Add the "flex-basis" property to the containing element (Duplicate of #18432)

### ISSUE THREAD

**Issue by denohemisalz** [elementor/elementor#19975]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It is essential to use flexbox correctly

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

Add Custom CSS but it's annoying.

**Comment by nicholaszein** [comment]
Hello @denohemisalz!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #8432, which is on the same subject. For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
