### ISSUE TITLE
php error in wp debug

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19983]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi
Every time I enable wp-debug, this error keeps repeating. 

PHP Notice:  Trying to access array offset on value of type null in /home2/xxxxxx/domains/domain.com/public_html/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php on line 1483

**Active plugins**
elementor 3.7.8
e pro 3.7.7
wp 6.0.2
php 7.4
hello elementor

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hey @Michaelgimii!

Thanks for the feedback! 🙏 

This notice usually happens when you have a menu item that is no longer available on your website. For example, if you added a link to a category, but since then have removed that category from your site. The item pointing to that category will remain in your menu, but it won't return the link for that category because it doesn't exist anymore. Please check your menus in your _Dashboard > Appearance > Menus_ and make sure they aren't highlighted in red with a warning. Remove the problematic items, and then save the menu. 

Alternatively, make sure you also haven't removed a menu from your list of menus, but it is still being used inside the Nav Menu widget somewhere on your website.

If that doesn't work, please try these **Troubleshooting steps**:

⚠️  **Backup** your website before proceeding, and if possible do it in a staging environment! ⚠️ 

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all types of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

If the issue persists, try contacting Elementor support (for Pro Users). To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon.

For non-Elementor Pro users, check out these resources:
* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

For now, we can't help you with this issue because it's not an Elementor bug. 

Regards
