### ISSUE TITLE
🚀 Feature Request: Form/Action - User Login & Register action for Form widget (Duplicate of #5184)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19994]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team!

It would be great if you add two actions user login & user register action to the form widget. Using these two actions, we can design a login and registration form using the form widget, and this is great.
Of course, along with these two actions, an action to create a forget password form will be great and needed.

### Describe the solution you'd like

- action for user login
- action for user register
- action for forget password

for form widget

**Comment by nicholaszein** [comment]
Hello @79ho3ein !

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #5184, which is on the same subject. For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently. Also you already made this request in the past.

**We also already have a Login widget since Elementor Pro v1.4**, which was [launched in 2017](https://elementor.com/blog/pro-v140-login-widget/)! You can find more about it [here](https://elementor.com/help/login-widget-pro/).

Please feel free to continue the conversation there. 👉  #5184 😉 

In the future, remember to check if there isn't an issue similar to yours already opened, and avoid making duplicate request. ✔️ 

Best regards,

Nick
