### ISSUE TITLE
Inline Font Icons breaks Submenu Indicator 

### ISSUE THREAD

**Issue by jonathansoltero** [elementor/elementor#19995]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Icon doesn't load in on frontend, but it does in the backend, even picked up by Google Insights.

```
A large DOM will increase memory usage, cause longer style calculations, and produce costly layout reflows.

a#sm-16650062821154136-1 > span.sub-arrow > svg.e-font-icon-svg > use
<use xlink:href="#fas-caret-down">
```

### Steps to reproduce

Enable Inline Font Icons and add a submenu indicator. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Operating System: | Linux |  
-- | -- | --
Software: | LiteSpeed |  
MySQL version: | MariaDB Server v10.5.12 |  
PHP Version: | 8.1.10 |  
PHP Memory Limit: | 4096M |  
PHP Max Input Vars: | 5000 |  
PHP Max Post Size: | 1024M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

**Comment by nicholaszein** [comment]
Hello @jonathansoltero ,

Thank you for reaching out! 🙏 

#### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We tested in both Elementor **v3.7**, and **v3.8** (and Pro as well) with the **Inline Font Icons** experiment active;
* We used multiple browsers, and tested in both normal and private/incognito modes;
* Cache was disabled, and any performance optimization was disabled as well;
* Every time the icon appeared with no issue.

What you're reporting is most likely a result of a **conflict with a 3rd party plugin**, issue with **mixed-content** or **CORS** restrictions, or perhaps a misconfiguration in your performance optimizations.

![image](https://user-images.githubusercontent.com/113993460/194633234-a98ff8b4-af18-4f6d-9483-c7240666526c.png)

#### Regarding Google Insights:

This is not an issue, since no matter how many DOM elements you have inside your page, that notice will always appear (test it with a blank page, and you'll see the same notice). Don't take it too seriously. It should be used for guidance, and it won't affect your page performance at all in this case. In fact it will improve it.

### ✅ What you can do to solve your issue:
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure your performance optimizations are not causing the issue you're reporting.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues **ARE NOT FOR SUPPORT** or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure to **provide a **full copy** of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

❓ If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
