### ISSUE TITLE
simple bug in finder

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20007]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

It seems that these [two arrows](https://prnt.sc/3Z3DGHR4_BpS) were added in version 3.7 and have no use. Is this a mistake?

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for reporting! 🙏 

Please note that this is not an Elementor bug. These are the arrows of the Scrollbar that is applied to the Finder because there is a limited height. This is normal.

❓ If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Or use the [new Discussions](https://github.com/elementor/elementor/discussions/new) page to start a discussion with the community and ask your questions there. This is not the correct channel to clarify all your doubts about the builder. Please use this channel with responsibility.

Kind regards
