### ISSUE TITLE
🚀 Feature Request: Copy & Paste Styles from one widget to another (Already Delivered)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20002]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi

Suppose we have several similar widgets such as icon boxes and I want to create a css transform for each of them. We do this for the first widget. When we click on another widget, the widget panel is displayed. After that, we must enter the advanced tab and then transform, and we must repeat this for each and every similar widget. This is time consuming and could work much better as I will explain below...

### Describe the solution you'd like

Suppose we have 5 or x similar widgets and we decide to consider an Entrance Animation for them. In the first widget, we select the desired animation in the Entrance Animation section. **When we click on the next widget, the Entrance Animation section of that widget will open.** This is what will save time.
But now, after clicking on the widget, the content tab will be displayed by default. Please note that this feature increases the speed of moving between **similar widgets**.

**Comment by nicholaszein** [comment]
Hello @79ho3ein,

Thank you for reaching out! 🙏 

#### The feature you're describing already exists, it's the option to Copy & Paste Styles. It has been around since v2.1! Check it out! 👉 https://elementor.com/help/right-click/

When you copy and paste styles, every style that is native from Elementor will be copied, including Advanced settings, like Transform, Motion effects, CSS Classes, and Custom CSS. 

❓ If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Comment by 79ho3ein** [comment]
@nicholaszein , I have been working with Elementor for more than 5 years. So Copy & Paste Styles is the most basic thing I need to know!
The purpose of this request is to improve the user interface in the Elementor editor. This feature occurs between two similar widgets. **A clearer example of this feature**

Suppose we have two similar widgets like icon box. A and B
In Widget A, we are in Advanced > Responsive tab. **After clicking on another similar widget (B), the Advanced > Responsive tab will be displayed first.**
This feature is now available in the Bricks page builder.

**Comment by nicholaszein** [comment]
@79ho3ein I know what you mean. You want something similar to another page builder. I knew it as soon as I read your request.

By default, Elementor will honor the last tab you have opened in a specific element on the page, so you know where you stopped and can continue from there. If you haven't yet opened the settings for that element, it will show the first tab, which is the Content tab, where you start placing the content of your element before you style it. This is the default behavior, and it has its logic. Content first, then design, and lastly advanced stuff. This is also a feature that was introduced after a user request. A lot of users requested this behavior, and it's likely it won't change because of that. We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
