### ISSUE TITLE
✔️ 🔗 🚀 Feature Request: [v3.8-Beta] Loop Builder - Provide a way to add Dynamic background image (Related to #5253, #4440)

### ISSUE THREAD

**Issue by fabianenzensperger** [elementor/elementor#20017]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If I create a loop item and set a background image to dynamic, for example "featured image", so on all list items appears the same image as it shows on loop item editor. I mean the "loop preview" picture is the same for all items, and not dynamic.

I think it' is an issue like this: #5253

<img width="1543" alt="Bildschirmfoto 2022-10-10 um 22 57 04" src="https://user-images.githubusercontent.com/57997262/194951717-9b796c22-35a7-4cc9-96d2-be589e0d9bed.png">

### Steps to reproduce

Create Loop Listing, create a new Template, set a container and for the container a background image, set image do dynamic (for example "featured image") and save. Now the image shows, but for all the same image and not theirselve featured image.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

–

**Comment by Stevemoretz** [comment]
Yes this could be related to https://github.com/elementor/elementor/issues/5253 since it was never really resolved.

**Comment by nicholaszein** [comment]
Hello @fabianenzensperger,

thanks for submitting your report! 🙏 

As you can see, I changed the title to "Feature Request"... This is something we are still not planning to fix since it's related to how Background Images are stored directly in the CSS, which can be an external source as explained by @bainternet [here](https://github.com/elementor/elementor/issues/5253#issuecomment-441433271). So we are not going to implement this right now. This will be revisited in future phases of the Loop Builder as it matures. Perhaps we might find an uncompromising solution for this.

Since this is a long-standing discussion, I will also mention issue #5253, and more important issue #4440.

There is a workaround, which is to add an image widget and set the position to absolute with custom CSS, z-index -1, and set the image height to 100%, and object-fit to cover. The advantage of this is also that these images will be easier to lazy-load.

Please understand that while we do welcome new feature requests, we can't promise they will be considered or added to our roadmap anytime soon. 

Best regards

**Comment by fabianenzensperger** [comment]
> Hello @fabianenzensperger,
> 
> thanks for submitting your report! 🙏
> 
> As you can see, I changed the title to "Feature Request"... This is something we are still not planning to fix since it's related to how Background Images are stored directly in the CSS, which can be an external source as explained by @bainternet [here](https://github.com/elementor/elementor/issues/5253#issuecomment-441433271). So we are not going to implement this right now. This will be revisited in future phases of the Loop Builder as it matures. Perhaps we might find an uncompromising solution for this.
> 
> Since this is a long-standing discussion, I will also mention issue #5253, and more important issue #4440.
> 
> There is a workaround, which is to add an image widget and set the position to absolute with custom CSS, z-index -1, and set the image height to 100%, and object-fit to cover. The advantage of this is also that these images will be easier to lazy-load.
> 
> Please understand that while we do welcome new feature requests, we can't promise they will be considered or added to our roadmap anytime soon.
> 
> Best regards

@nicholaszein 

Thanks for your answer. So what are your approaches to solving this?

Is it that hard to solve? So far I haven't noticed it and it's not the most important thing for me because I haven't used it yet, but that will definitely change with the Loop Builder.

As I can see, the first complaints about this came in over 4 years ago. So I'm wondering, like many others (including the well-known plugin creator "ohhboi"), why this is taking so long. You're used to that from Elementor (hehe), but I don't expect such a long time to think about it.

But yes, I think it's great that you want to devote yourself to the (unpleasant) topic in the future, but I think it should definitely be communicated in the Elementor Editor. If someone ever gets into this situation without knowing all this, he or she will wonder what went wrong.

Maybe I question too much about many things, but I'm definitely good at it! Ah and for me this sounds more like an bug as an feature request, but you decide this! 😁

**Comment by nicholaszein** [comment]
Hey @fabianenzensperger!

Unfortunately, I can't give you more information than that. To change this behavior we would have to change how CSS is generated just to accommodate backgrounds generated by dynamic-tags. This would mean having to create whole new methods for background image controls. This is not like a simple switch you can turn on and off. The CSS for the background image would have to be loaded inline only if the feature image dynamic-tag is enabled, otherwise we would probably compromise on performance for every other case scenario, and it would have to happen independently from the already established method for generating CSS. Pair this with the Loop builder, which requires every background image to be different, if the image exists, and it becomes very complex very fast. There are probably even more things to consider.

Besides, in my opinion, in this case, it's really not recommended to use background images because they wouldn't be accessible either. We can't have srcsets, alt tags, or anything that would be good for accessibility. It's better to use a proper image widget in this case.

It's not about the time it takes to find a solution. 

There is no problem in questioning at all. This is a healthy discussion, and we appreciate that you're taking the time to give feedback and engage. Sometimes it might not feel like it, but we do care.

I hope this sheds some light on the matter. 

Kind regards...

**Comment by nicholaszein** [comment]
Hey @fabianenzensperger!

Just passing by to let you know that:

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.1**! 🥳 

But something tells me you already knew that 😉 

✔️ If you haven't already, feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Comment by fabianenzensperger** [comment]
> Hey @fabianenzensperger!
> 
> Just passing by to let you know that:
> 
> ### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.1**! 🥳
> But something tells me you already knew that 😉
> 
> ✔️ If you haven't already, feel free to check it out and update your plugin to the new version!
> 
> Cheers 🥂

Thank you!
