### ISSUE TITLE
BuddyBoss registration page

### ISSUE THREAD

**Issue by JHEmerge** [elementor/elementor#20016]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have Buddy boss plugin installed and their registration page is not working. I contacted them and they ran test on the website. they found that elementor have some errors that are creating issues with buddyboss page. and they asked me to contact you guys to help fix it

### Steps to reproduce

![download (2)](https://user-images.githubusercontent.com/115500610/194935973-36432d6a-89fe-4034-81d7-fab1b258577d.png)

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 7.4.29
	PHP Memory Limit: 
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://emergegx.com
	Home URL: https://emergegx.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: emergegx@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: BuddyBoss Theme
	Version: 2.0.7
	Author: BuddyBoss
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	BuddyBoss Platform
		Version: 2.1.1.1
		Author: BuddyBoss

	BuddyBoss Platform Pro
		Version: 2.1.3.1
		Author: BuddyBoss

	BuddyPress Xprofile Custom Field Types
		Version: 1.2.4
		Author: BuddyDev

	Conditional Profile Fields for BuddyPress
		Version: 1.2.5
		Author: BuddyDev

	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 9.0.123
		Author: HubSpot

	LearnDash Licensing &amp; Management
		Version: 1.1.3
		Author: LearnDash

	LearnDash LMS
		Version: 4.3.1.3
		Author: LearnDash

	LiteSpeed Cache
		Version: 5.2
		Author: LiteSpeed Technologies

	Login and Logout Redirect
		Version: 2.0.2
		Author: Swapnil V. Patil

	WP Mail SMTP
		Version: 3.5.2
		Author: WPForms

== Must-Use Plugins ==
	WHC.CA
		Version: 1.0.0
		Author: WHC.CA

	WHC.CA
		Version: 1.0.0
		Author: WHC.CA

	WHC.CA
		Version: 1.0.0
		Author: WHC.CA

== Elements Usage ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
JS: showing 5 of 5JS: 2022-08-23 02:30:06 [error X 2][https://wp172024.wpdns.ca/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.2:3:548596] Element type not found: \&#039;nav-menu\&#039; 
JS: 2022-08-29 13:56:11 [error X 3][https://emergegx.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.2:3:1060434] Cannot read properties of null (reading \&#039;getBoundingClientRect\&#039;) 
JS: 2022-08-29 14:26:38 [error X 18][https://emergegx.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.2:3:767290] Cannot read properties of undefined (reading \&#039;localized\&#039;) 
JS: 2022-09-21 01:24:02 [error X 812][https://emergegx.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \&#039;clone\&#039;) 
JS: 2022-09-21 01:24:08 [error X 23][https://emergegx.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \&#039;changestop\&#039;) 

PHP: showing 2 of 2PHP: 2022-08-31 03:20:10 [notice X 10][/home/aydyas19/public_html/wp-content/plugins/elementor/includes/embed.php::184] Undefined index: lazy_load [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-10 18:50:44 [notice X 1][/home/aydyas19/public_html/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property &#039;email&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52022-10-09 05:14:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.8',
)]
2022-10-09 05:14:44 [info] elementor::elementor_updater Started 
2022-10-09 05:14:44 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-09 05:14:44 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-09 05:14:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.8',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hey @digitalmurph,

Thank you for the feedback. 🙏

⚠️ While reviewing your report, we noticed it was missing some key pieces of information:

* **Steps to replicate**: Provide us with enough information to be able to reproduce your issue consistently, like a screen recording or an actual representation of the error you're reporting. The screenshot you provided is not enough. It would be nice if you also could share the link for the problematic page.
* **Isolating the problem**: In your System Info, we are seeing that you are using 3rd party add-ons for Boddy Press as well as plugins that modify redirections, and the LiteSpeed cache, which is something that can definitely cause your issue. In order to help you, we need you to make sure that these plugins are not affecting your page. It's also important to note that we do not provide support in this channel, especially for 3rd party software like BuddyBoss. As it's stated on **[this page](https://www.buddyboss.com/integrations/elementor-page-builder/)**, they say **they are the ones that maintain the integration with Elementor, and they are responsible for keeping this integration updated to ensure it works as described.**

Without them, we simply can't help. 😕

👉 Please follow the guidelines for opening a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

If you are still having problems with your website, **_even after checking with BuddyBoss if their integration is up-to-date according to their claims_**, please **CONTACT ELEMENTOR SUPPORT** first before posting here. We can't give you support here.

⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support. ⚠️ 

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Best regards,

Nick
