### ISSUE TITLE
🚀Feature Request: Toggle hide responsive hidden elements

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#20025]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Been trying the 3.8 beta on client sites more and something that I didn't like with the current state of Elementor of sections and columns is the fact that hidden elements while editing push other elements about but on preview it is hidden as expected, but while editing it can get in the way. Please implement a quick easy toggle option to hide hidden responsive options while editing.

The only workaround is to make the items have a width of 0% which adds more CSS to the final product. Please look at implementing in 3.8 please.

**Comment by nicholaszein** [comment]
Hello @perks98,

Thank you for reaching out! 🙏 

#### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
1. There is already an option to show or hide hidden elements on responsive modes as explained in [this article](https://elementor.com/academy/make-elementor-yours-how-to-the-customize-elementor-editor/).
2.  You can also use the **Navigator** to quickly show-hide any element on demand as [documented here](https://elementor.com/help/navigator-indicators/).

### ✅ What you can do to solve your issue:

1. Follow the instructions in the video below:

https://youtu.be/TpSmiyrIKy4?t=98

2. [Learn more about the navigator](https://elementor.com/help/navigator/).

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* Make sure to check the [Elementor Documentation](https://elementor.com/help/) before submitting your issue, chances are what you're looking for is already available.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

❓ If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
