### ISSUE TITLE
⛔ 🛟 Support Request: Report of a bug was closed.  It really is a bug.

### ISSUE THREAD

**Issue by bhs67** [elementor/elementor#20038]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

See https://github.com/elementor/elementor/issues/20032.

This is a bug.  I've been using Elementor for a long time for many websites.  Upgrading should not damage an existing website.  This occurred after I upgraded Elementor for this one site.  

In addition, "Edit with Elementor" is no longer listed under Page ... see attachments.

![el4 1](https://user-images.githubusercontent.com/18146997/195716783-f2f1d822-4836-4cc7-8998-80f49cf3f04b.jpg)
![el4 2](https://user-images.githubusercontent.com/18146997/195716787-6ccf7c8a-fa6c-46ef-a8c7-5c3868976074.jpg)

### Steps to reproduce

See https://github.com/elementor/elementor/issues/20032.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Win10, WordPress, Install Elementor (not Pro). update Elementor.

**Comment by m1ga** [comment]
I just looks like its a normal Wordpress page now. 
So click on "edit" and then it should show a blue "edit with Elementor" button in the top row. Click on that and it should be fine again.

**Comment by bhs67** [comment]
That works.  After "edit with Elementor" => Update, it displays correctly!

**Comment by bhs67** [comment]
Oops.  Not completely solved.  

For a new website.  The "edit with Elementor" works fine. 

This is the Edit with Elementor page (https://ftcnd.foxping.com/wp-admin/...) 
![fo4](https://user-images.githubusercontent.com/18146997/195913722-752410e7-e63b-4bca-9ad6-b2383a76eda1.jpg)

This is the page displayed  (https://ftcnd.foxping.com/)
![fo5](https://user-images.githubusercontent.com/18146997/195914083-058f75d9-c86b-4e6f-8244-9cb6693752cb.jpg)

Strange result after an Update.  This has never been a problem before (span of many years).

**Comment by nicholaszein** [comment]
Hello @bhs67,

Thanks for contacting us! 🙏 

As I mentioned before, this is more of a support question, not really something we can answer here. Your issue is simply related to cache.

I also mentioned that you didn't share the information required in our guidelines. This is another reason why we can't help you.

⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports** , and should not be used for support. ⚠️ 

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
