### ISSUE TITLE
[🧐 Evaluating] Not able to remove Elementor Header Elements on Mobile

### ISSUE THREAD

**Issue by todianec** [elementor/elementor#20043]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I cannot remove the Primary Menu or Button 1 from the mobile header, because they do not show up in the header builder drag and drop section. 
![Screenshot 2022-10-14 114209](https://user-images.githubusercontent.com/115808807/195887276-62110170-6706-4fa2-84b9-ab4269ed0e66.jpg)

### Steps to reproduce

I'm just trying to edit the mobile header in the header builder.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.32
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: http://robertb201.sg-host.com
	Home URL: http://robertb201.sg-host.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: diane@magicalaccess.com
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.9.2
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.42

== Active Plugins ==
	Advanced iFrame Pro
		Version: 2022.5
		Author: Michael Dempfle

	Astra Pro
		Version: 3.9.2
		Author: Brainstorm Force

	Astra Widgets
		Version: 1.2.12
		Author: Brainstorm Force

	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	Make Column Clickable Elementor
		Version: 1.4.0
		Author: Fernando Acosta

	Premium Starter Templates
		Version: 3.1.17
		Author: Brainstorm Force

	Prime Slider
		Version: 3.1.1
		Author: BdThemes

	SiteGround Central
		Version: 2.0.8
		Author: SiteGround

	SiteGround Optimizer
		Version: 7.2.4
		Author: SiteGround

	SiteGround Security
		Version: 1.3.4
		Author: SiteGround

	Spectra
		Version: 2.0.13
		Author: Brainstorm Force

	Ultimate Addons for Elementor
		Version: 1.36.11
		Author: Brainstorm Force

	WordPress Importer
		Version: 0.8
		Author: wordpressdotorg

	WPForms Lite
		Version: 1.7.7.2
		Author: WPForms

	WP Portfolio
		Version: 1.11.3
		Author: Brainstorm Force

== Elements Usage ==
	
	page : 2
		button : 3
		divider : 9
		heading : 36
		icon : 4
		image : 6
		nav-menu : 2
		prime-slider-mount : 1
		star-rating : 4
		text-editor : 4
		uael-infobox : 8
	popup : 3
		google_maps : 1
		heading : 1
		icon : 1
		image : 1
		text-editor : 1
		uael-business-hours : 1
		wpforms : 2
	wp-post : 0
		button : 18
		divider : 6
		heading : 24
		icon : 5
		image : 20
		image-box : 17
		nav-menu : 1
		text-editor : 21
		uael-infobox : 2
	wp-page : 17
		button : 11
		divider : 17
		heading : 73
		icon : 8
		image : 34
		nav-menu : 12
		prime-slider-mount : 2
		shortcode : 6
		spacer : 12
		star-rating : 8
		text-editor : 13
		uael-infobox : 12

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 332022-09-01 01:15:57 [info] elementor::elementor_updater Started 
2022-09-01 01:15:57 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-01 01:15:58 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-01 01:15:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-09-01 01:15:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.3',
  'to' => '3.7.4',
)]
2022-09-01 01:16:33 [info] elementor-pro::elementor_pro_updater Started 
2022-09-01 01:16:33 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-01 01:16:33 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-01 01:16:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-09-01 01:16:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.4',
  'to' => '3.7.5',
)]
2022-10-03 23:06:26 [info] elementor::elementor_updater Started 
2022-10-03 23:06:26 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-03 23:06:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.8',
)]
2022-10-03 23:06:26 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-03 23:06:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.8',
)]
2022-10-03 23:10:20 [info] elementor-pro::elementor_pro_updater Started 
2022-10-03 23:10:20 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-03 23:10:20 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-03 23:10:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.7.7',
)]
2022-10-03 23:10:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.7.7',
)]

PHP: showing 4 of 4PHP: 2022-08-23 04:48:39 [notice X 2785][/home/customer/www/robertb201.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-23 04:48:41 [notice X 333][/home/customer/www/robertb201.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/customer/www/robertb201.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/customer/www/robertb201.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/customer/www/robertb201.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/customer/www/robertb201.sg-host.com/public_html/wp-content/plugins/bdthemes-prime-slider-lite/traits/query-controls/select-input/dynamic-select.php(124): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-08-30 21:10:40 [notice X 2][/home/customer/www/robertb201.sg-host.com/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The Plugin::$instance->posts_css_manager argument is deprecated since version 2.7.0! Use Plugin::$instance->files_manager instead. [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-06 20:32:28 [notice X 3][/home/customer/www/robertb201.sg-host.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-08-23 04:50:24 [error X 3][http://robertb201.sg-host.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.2:2:14029] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `menu_link` value. Expected array or object.',
)]
JS: 2022-09-01 21:20:22 [error X 1][http://robertb201.sg-host.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4145\") has already been destroyed and cannot be used. 
JS: 2022-09-01 21:32:38 [error X 12202][http://robertb201.sg-host.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \'clone\') 
JS: 2022-09-01 21:32:39 [error X 168][http://robertb201.sg-host.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \'changestop\') 
JS: 2022-10-14 01:34:31 [error X 1][http://robertb201.sg-host.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:767341] Cannot read properties of undefined (reading \'toLowerCase\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Make Column Clickable Elementor: Compatibility not specified
	Prime Slider: Compatible
	Ultimate Addons for Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Ultimate Addons for Elementor: Compatible

**Comment by nicholaszein** [comment]
Hello @todianec,

Thank you for reaching out! 🙏 

#### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* You haven't provided enough information to debug your issue. 
* We don't know if you have built your Header with Elementor Pro's Theme Builder or not.
* It looks like you're trying to edit your header from the Customizer. That's not the correct way of editing Elementor Site Parts.
* You haven't really isolated your problem as instructed on our guidelines for opening a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). I can see you have multiple plugins active, and that you're not using the Hello Elementor theme.

### ✅ What you can do to solve your issue:
* Please follow [this guide](https://elementor.com/academy/how-to-create-a-wordpress-header-using-elementor-theme-builder/) to learn how to create and edit a Header Site Part with Elementor Pro's Theme Builder.

## Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

❓ If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
