### ISSUE TITLE
I couldn't add layout to my custom post type because it didn't show that I put

### ISSUE THREAD

**Issue by TonyBoss16** [elementor/elementor#20046]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I tried to change single-event.php by Elementor page editor, but suddenly it didn't function after I put a custom header for this section.

### Steps to reproduce

I charge a custom block created by Elementor pro team, 
2) Put a custom header 
3) change that for another one.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.32
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://siresortscapcana.com
	Home URL: https://siresortscapcana.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: 0
	Admin Email: soporte@lancergroup.org
	Debug Mode: Inactive

== Theme ==
	Name: Traveler Child
	Version: 3.0.1.1651515352
	Author: Shinetheme
	Child Theme: Yes
	Parent Theme Name: Traveler
	Parent Theme Version: 3.0.3
	Parent Theme Author: Shinetheme

== User ==
	Role: administrator
	WP Profile lang: es_ES
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0

== Active Plugins ==
	Advanced Editor Tools (previously TinyMCE Advanced)
		Version: 5.6.0
		Author: Automattic

	Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd
		Version: 6.15.4
		Author: SeedProd

	Contact Form 7
		Version: 5.6.3
		Author: Takayuki Miyoshi

	Custom Fonts
		Version: 1.3.7
		Author: Brainstorm Force

	Elementor
		Version: 3.9.0-dev2
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0-dev2
		Author: Elementor.com

	Envato Elements
		Version: 2.0.11
		Author: Envato

	Events Manager
		Version: 6.1.2.1
		Author: Marcus Sykes

	GTranslate
		Version: 2.9.13
		Author: Translate AI Multilingual Solutions

	Gutenberg
		Version: 14.3.0
		Author: Gutenberg Team

	JetFormBuilder
		Version: 2.1.7
		Author: Crocoblock

	Layouts for WPBakery
		Version: 1.0.6
		Author: Techeshta

	Loco Translate
		Version: 2.6.2
		Author: Tim Whitlock

	MC4WP: Mailchimp for WordPress
		Version: 4.8.10
		Author: ibericode

	OptionTree
		Version: 2.7.4.1
		Author: Derek Herman

	OTGS Installer
		Version: 3.0.3
		Author: OnTheGoSystems

	SiteGround Optimizer
		Version: 7.2.4
		Author: SiteGround

	SiteGround Security
		Version: 1.3.4
		Author: SiteGround

	Tidio Chat
		Version: 5.4.2
		Author: Tidio Ltd.

	Traveler code
		Version: 3.0.0
		Author: Shinetheme

	WooCommerce
		Version: 6.8.2
		Author: Automattic

	WPBakery Page Builder
		Version: 6.9.0
		Author: Michael M - WPBakery.com

	WP File Manager
		Version: 7.1.6
		Author: mndpsingh287

	WP Maintenance Mode & Coming Soon
		Version: 2.5.4
		Author: Themeisle

	Xl Tab
		Version: 1.3
		Author: Ashraf

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Uso de los elementos ==
	
	header : 5
		button : 2
		image : 1
		nav-menu : 1
	page : 3
		accordion : 2
		countdown : 1
		divider : 4
		form : 1
		google_maps : 1
		heading : 10
		icon-list : 3
		image : 2
		share-buttons : 1
		text-editor : 3
	section : 2
		button : 2
		counter : 4
		form : 2
		google_maps : 1
		heading : 32
		image : 15
		image-box : 6
		text-editor : 2
	wp-page : 1
		countdown : 1
		divider : 1
		heading : 3
	single-post : 3
		button : 2
		form : 1
		heading : 6
		image : 1
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		spacer : 4
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1

== Experimentos de Elementor ==
	Salida del DOM optimizada: Inactivo
	Carga de recursos mejorada: Inactivo
	Carga de CSS mejorada: Inactivo
	Fuentes de iconos integradas: Inactivo
	Mejoras de accesibilidad: Inactivo
	Puntos de ruptura personalizados adicionales: Inactivo
	Import Export Website Kit: Inactivo
	Ocultar los widgets nativos de WordPress de los resultados de búsqueda: Inactivo
	admin_menu_rearrangement: Inactivo por defecto
	Contenedor Flexbox: Activo
	Por defecto, el nuevo constructor de temas: Activo por defecto
	Páginas de destino: Inactivo
	Muestrario de colores: Inactivo
	Widgets favoritos: Inactivo
	Barra superior de administración: Inactivo
	Transiciones de páginas: Activo por defecto
	Notes: Activo por defecto
	Bucle: Activo por defecto
	Envíos de formulario: Activo por defecto
	Ajuste de scroll: Activo por defecto

== Registro ==
	
Log: showing 20 of 372022-10-06 21:43:26 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2022-10-06 21:43:26 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2022-10-06 21:43:26 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2022-10-06 21:43:26 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2022-10-06 21:43:26 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-10-06 21:43:26 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-10-06 21:43:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.7.7',
)]
2022-10-06 21:43:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.7.7',
)]
2022-10-13 04:10:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.9.0-dev2',
)]
2022-10-13 04:10:27 [info] elementor-pro::elementor_pro_updater Started 
2022-10-13 04:10:27 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-13 04:10:27 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-13 04:10:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.9.0-dev2',
)]
2022-10-13 04:10:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.9.0-dev2',
)]
2022-10-13 04:10:27 [info] elementor::elementor_updater Started 
2022-10-13 04:10:27 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-13 04:10:28 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-13 04:10:28 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-10-13 04:10:28 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-13 04:10:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.9.0-dev2',
)]

PHP: showing 4 of 4PHP: 2022-10-06 21:44:08 [notice X 1][/home/customer/www/siresortscapcana.com/public_html/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-06 21:45:35 [notice X 26][/home/customer/www/siresortscapcana.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-13 01:00:36 [notice X 8][/home/customer/www/siresortscapcana.com/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/site-logo.php::33] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-14 19:37:42 [notice X 1][/home/customer/www/siresortscapcana.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-10-14 19:17:25 [error X 1][https://siresortscapcana.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev2:3:1061491] can\'t access property \"getBoundingClientRect\", $ is null 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	Envato Elements: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Envato Elements: Incompatible

**Comment by nicholaszein** [comment]
Hey @TonyBoss16,

Thank you for the feedback. 🙏

While reviewing your report, we noticed it was missing some key pieces of information.

👉 Please follow the guidelines for opening a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

⚠️ This report is missing essential information:

- **Steps to replicate:** It wasn't clear what you did. Try recording a video or taking screenshots to elaborate your report.
- **Isolating the problem:** You need to ensure you are testing this without any add-on active, only the latest versions of Elementor active.

I can see in your System Info you are using Incompatible Elementor Addons, as well as the Elementor Developer Edition plugin, which shouldn't be used on production websites. Please update all your plugins before reporting, and remove the developer edition. We do not provide support for issues with an unstable version of Elementor.

Before you re-submit your issue, in order to solve your problem, please try these Troubleshooting steps:

⚠️  **Backup** your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all types of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

⚠️ Please note that GitHub issues are reserved for 🐞Bug Reports, and should not be used for support. 

If you have questions or need general support, please use one of the following channels:

For non-Elementor Pro users, check out these resources:
* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
