### ISSUE TITLE
I am facing the following problem, how do I fix it?

### ISSUE THREAD

**Issue by MurshediSultan** [elementor/elementor#20045]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Deprecated: الوظيفة _register_controls أصبحت مهجورة منذُ الإصدار 3.1.0! استخدم الوظيفة الآتية Elementor\Controls_Stack::register_controls() بدلاً عن السابقة. in /home/arabifi/public_html/wp-includes/functions.php on line 5379

Deprecated: الوظيفة Elementor\Controls_Stack::_register_controls أصبحت مهجورة منذُ الإصدار 3.1.0! استخدم الوظيفة الآتية Elementor\Controls_Stack::register_controls() بدلاً عن السابقة. in /home/arabifi/public_html/wp-includes/functions.php on line 5379

### Steps to reproduce

Deprecated: الوظيفة _register_controls أصبحت مهجورة منذُ الإصدار 3.1.0! استخدم الوظيفة الآتية Elementor\Controls_Stack::register_controls() بدلاً عن السابقة. in /home/arabifi/public_html/wp-includes/functions.php on line 5379

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Deprecated: الوظيفة Elementor\Controls_Stack::_register_controls أصبحت مهجورة منذُ الإصدار 3.1.0! استخدم الوظيفة الآتية Elementor\Controls_Stack::register_controls() بدلاً عن السابقة. in /home/arabifi/public_html/wp-includes/functions.php on line 5379
Deprecated: الوظيفة _register_controls أصبحت مهجورة منذُ الإصدار 3.1.0! استخدم الوظيفة الآتية Elementor\Controls_Stack::register_controls() بدلاً عن السابقة. in /home/arabifi/public_html/wp-includes/functions.php on line 5379

**Comment by nicholaszein** [comment]
Hey @MurshediSultan, 

Thank you for the feedback. 🙏 

While reviewing your report, we noticed it was missing some key pieces of information.

👉 Please follow the guidelines for opening a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

⚠️ This report is missing key information: 

* **Steps to replicate:** We need a way to know how to replicate your issue
* **Isolating the problem:** You need to make sure you are testing this without any add-on active, only Elementor active.
* **System info:** You need to follow the guidelines and provide us with the information required so we can understand what's going on

Without them, we simply can't help. 😕 

Before you re-submit your issue, and in order to solve your issue, please try these **Troubleshooting steps**:

⚠️  **Backup** your website before proceeding, and if possible do it in a staging environment! ⚠️ 

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.

⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports** , and should not be used for support. ⚠️ 

If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

For  💡 **New Ideas** or 🚀 **Feature Requests** please [create a new Discussion](https://github.com/elementor/elementor/discussions/new) in the [Discussions](https://github.com/elementor/elementor/discussions) tab.

Regards,

Nick
