### ISSUE TITLE
🚀 Feature Request: Ability to set multiple types of Units to Margin and Padding (Duplicate of #2219)

### ISSUE THREAD

**Issue by gheorghe9512** [elementor/elementor#20053]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

At the moment you cannot set different Units for margin and padding

### Describe the solution you'd like

I want to see the option of being able to set different Units for margin and padding as e.g and pixel and rem

Padding Top and Bottom 100px, and Left and Right 5rem

<a href="https://imgur.com/87Hx9Dp"><img src="https://i.imgur.com/87Hx9Dp.png" title="source: imgur.com" /></a>

**Comment by nicholaszein** [comment]
Hello @gheorghe9512!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #2219, which is on the same subject. For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

You can learn more about the new **Custom Units** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
