### ISSUE TITLE
3rd Party: Use of the wrong methods can cause conflicts with Elementor widgets (Related to #19673)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20061]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor team.

Please take a look [here](https://github.com/helloideabox/powerpack-lite-elementor/issues/31). The answer of the Powerpack plugin developer...

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for reaching out! 🙏 

While we do welcome bug reports, we can't provide support for 3rd party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers, and they need to use the correct methods to implement their functionalities that won't negatively affect other core features. See a similar discussion here: #19673.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

⚠️  Backup your website before proceeding, and if possible do it in a staging environment! 

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2.  Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3.  Clear all types of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

If after following these steps the problem persists, you can submit a new issue with details to reproduce it so we can take a look.

They need to make sure they are using the correct methods available in our [Developers API](https://developers.elementor.com/).

Regards
