### ISSUE TITLE
🚀 Feature Request: Enlarge Replace URL's input fields (Duplicate of #19559, #19955)

### ISSUE THREAD

**Issue by hogash** [elementor/elementor#20067]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hey guys,

The Replace URLs page needs a bit of tweaking. Since this is an important tool that needs extra attention, the inputs should be much larger. At the moment they're very small and need to keep bouncing to start end of the input. Here's a screenshot with a longer domain name:

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/1725925/196363075-fa0ca605-ef93-48a0-bd01-a3cf2d537c23.png">

Thanks!

### Describe the solution you'd like

Enlarge the inputs with `large-text` css class and make the wrapper `flex-direction: column; gap: 20px;`.

<img width="1901" alt="image" src="https://user-images.githubusercontent.com/1725925/196362611-50e235cd-7a3a-4365-9f9a-ec6a77181b72.png">

**Comment by nicholaszein** [comment]
Hello @hogash!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #19559, and #19955, which are on the same subject. And it has already been set to be updated in v3.8 as seen on #19565.

For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick

**Comment by nicholaszein** [comment]
Hi, @hogash!

This feature was released with Elementor **v3.8**! 🥳 

(Just cleaning up 😉)
