### ISSUE TITLE
🚀 Feature Request: Ability to manage wp-menu in Elementor editor.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20070]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team!

I think it would be great if you add the possibility to manage wp-menu through the element editor. This feature will have many advantages. The first is that if we make wp-menu in the element editor, we can set a condition for each of the menu items. For example, item x should be displayed when the user is logged in.
If we have the possibility to manage wp-menu in the Elementor editor, we will even have the possibility to add an icon for the menu (nav menu widget).

### Describe the solution you'd like

Ability to manage wp-menu in Elementor editor

**Comment by nicholaszein** [comment]
Hello @79ho3ein,

thanks for submitting your feature request! 🙏 

Please understand that while we do welcome new feature requests, we can't promise they will be considered or added to our roadmap anytime soon. This might not be necessary when we introduce our nested widgets, which would probably include the Mega Menu Builder that was promised a while back. I do not have an ETA on this though...

Best regards

**Comment by 79ho3ein** [comment]
thank you @nicholaszein, May I ask what version Mega Manu will be released in? At least, will it be released in 2022?

**Comment by nicholaszein** [comment]
@79ho3ein,

we do not have a public roadmap yet. This is a WIP, and when we do, we'll let everyone know. For the time being, I can't share this information with you. I hope you understand.

**Comment by arielk** [comment]
HI @Michaelgimii,

As @nicholaszein wrote above, we are currently working on the nested capability which will include some solutions that our users have requested for years, such as: Nested Tabs, Accordion, Slides and... Mega Menu! We hope to have it ready in the coming months (beta/experiment).

Regarding the public road map. The main reason we are here is to listen to our users and assess their needs through your feedback and discussions. I know it doesn't look that cool yet, but we plan to move all feature requests to the Discussions section on GitHub so that users can upvote and prioritize the requests better than now.

Until than, you can see the public roadmap right here on GitHub (unofficial!): https://github.com/elementor/elementor/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc

Thanks for your feedback!

**Comment by Michaelgimii** [comment]
thank you @arielk

**Comment by nicholaszein** [comment]
Hi there,

### 📅  This request is scheduled to be Migrated to the new [Discussions](https://github.com/elementor/elementor/discussions/categories/feature-request) section.

Please do not duplicate this request.

Once we migrate it, we encourage you to cast your **⬆️ Upvote** on the first comment if you feel it should be considered for our roadmap.
