### ISSUE TITLE
⛔ 📚 🐞 Bug Report: Incorrect sorting of select control options

### ISSUE THREAD

**Issue by sanzeeb3** [elementor/elementor#20082]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using select control, the options are sorted incorrectly. For example, the options:

```
		$this->add_control(
			'border_style',
			[
				'label' => esc_html__( 'Border Style', 'plugin-name' ),
				'type' => \Elementor\Controls_Manager::SELECT,
				'default' => 'solid',
				'options' => [
					'13'  => esc_html__( 'Solid', 'plugin-name' ),
					'2' => esc_html__( 'Dashed', 'plugin-name' ),
					'4' => esc_html__( 'Dotted', 'plugin-name' ),
					'1' => esc_html__( 'Double', 'plugin-name' ),
					'0' => esc_html__( 'None', 'plugin-name' ),
				],
			]
		);
```

The options order above and the options in output are different 

![screenshot-2](https://user-images.githubusercontent.com/16817248/196603828-849f46a6-d049-4c67-becf-1b4ac410029d.PNG)

### Steps to reproduce

1) Create a custom widget and add options to Select control as above code snippet.
2) Observe the output with incorrect sorting.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

https://pastebin.com/UdTVZSAD

**Comment by nicholaszein** [comment]
Hello @sanzeeb3,

Thank you for reaching out! 🙏 

#### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
The numbers in your array are responsible for defining the order of the options. In your case you have:

````
'13'  => esc_html__( 'Solid', 'plugin-name' ),
'2' => esc_html__( 'Dashed', 'plugin-name' ),
'4' => esc_html__( 'Dotted', 'plugin-name' ),
'1' => esc_html__( 'Double', 'plugin-name' ),
'0' => esc_html__( 'None', 'plugin-name' ),
````

### ✅ What you can do to solve your issue:
If you want the order to be the same as the order you're writing them, change the numbers:

````
'0'  => esc_html__( 'Solid', 'plugin-name' ),
'1' => esc_html__( 'Dashed', 'plugin-name' ),
'2' => esc_html__( 'Dotted', 'plugin-name' ),
'3' => esc_html__( 'Double', 'plugin-name' ),
'4' => esc_html__( 'None', 'plugin-name' ),
````

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

❓ If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Comment by sanzeeb3** [comment]
Hi @nicholaszein ,

Thanks for checking out. However, the solution to change the number doesn't make sense. Those are the values of the items - you can't simply assign one item's value to other. Is there any other way to send the value/option pair to the select box where the value is the number? In other words, how do you achieve the following without changing the order of options?

```
<select>
    <option value="10"> Ten </option>
    <option value="5"> Five </option>
</select>
```

**Comment by nicholaszein** [comment]
Hello @sanzeeb3,

we are talking about two different things here. One is a numerical PHP array, that after is parsed is showing items in ascending order related to their keys, and the other is plain HTML. You'll need to explain what you're trying to achieve exactly because this was not clear enough. I would advise avoiding using numeric values for these.

**Comment by sanzeeb3** [comment]
Hi @nicholaszein - Apologies for the late reply & thanks for sharing the details.

> I would advise avoiding using numeric values for these.

We actually can't avoid that. The practical use is we're using a custom post type, and so the options are dynamically generated where value is `ID` which is numeric and the label is `Title`, we'd want to sort the list by `Title`.  Is this possible in any way?


> We are talking about two different things here. 

I don't see two different things. Is there?

**Comment by sanzeeb3** [comment]
Hey @nicholaszein - any update on this?

**Comment by nicholaszein** [comment]
Hi, @sanzeeb3,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
