### ISSUE TITLE
🚀 Feature Request: Container - Move "Overflow" and "HTML tag" controls to Container section in the Layout tab.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20086]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi

Currently, we have two tabs in the container panel. **Container** and **additional settings**.

But it is much better if the container settings are not divided into two parts. Rather, all should be placed in the same section. Is there a special reason that the two Overflow and HTML Tag options are included in a separate tab?

### Describe the solution you'd like

 I think it would be much better if the Overflow and HTML Tag options were added to the other container settings. **Like the picture below**

![1](https://user-images.githubusercontent.com/88034902/196626909-cb5b951a-adad-4309-b17a-6529e8a8fbfe.jpg)

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for submitting a feature request! 🙏 

⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

The reason for that is that these controls are not often used, and we wanted to simplify the user experience since there are lots of items already in place. On smaller screens, it can be overwhelming. Not to mention we want to make sure users can see the link for the Help Center too.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
