### ISSUE TITLE
📋 Feature Request: Replace URL: Fields not wide enough (Duplicate of #19559, #19955, #20067)

### ISSUE THREAD

**Issue by bkjproductions** [elementor/elementor#20088]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using the Elementor: Tools: Replace URL tab, the search and replace fields are WAY too short. This causes a problem, because you cannot see the contents of the field so it is quite possible to make a mistake, such as leaving off a trailing slash or not including the https protocol.

### Steps to reproduce

Go to **Elementor: Tools: Replace URL** tab. 
Paste or type in a URL in the **Search** field. If it is longer than 20 or so characters, you cannot see the entire contents of the search field. Same problem for the **Replace** field.
![image](https://user-images.githubusercontent.com/4551281/196746165-ea6d9081-e54d-43f3-8c5c-9a131db6519d.png)

This can be a serious problem for the novice, and even an expert user can accidentally make a mistake.

To fix this, you need to add this CSS to the WP-admin:
`tr.elementor_replace_url input {width: 100%}`

![image](https://user-images.githubusercontent.com/4551281/196746474-5eb3f37a-826e-432a-b4d5-7a35a8c2f107.png)

'Tis simple fix, should be easy enough for Elementor to add to the core Elementor admin css. :)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Elementor - 3.7.8 
Elementor Pro - 3.7.7
WordPress 6.0.3

**Comment by nicholaszein** [comment]
Hello @bkjproductions!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #19955, which is on the same subject. For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Please, in the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
