### ISSUE TITLE
❌ 🐞 Bug Report: google maps not working with elementor (both instaled) & Traveler theme

### ISSUE THREAD

**Issue by kaysenjp** [elementor/elementor#20089]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

hello guys any solution please about Google map which is not showing with elementor & traveler theme
(Google API key already in the theme option)
I tried to deactivate the free elementor and keep the pro version then it works
but when reactivate the free version the maps disappear
I tried downgrade all elemetor version but the problem still

### Steps to reproduce

<img width="846" alt="github sup" src="https://user-images.githubusercontent.com/68028032/196758177-c2026f8e-3051-459c-90ca-09ae4540c711.PNG">
-----------------------
not working
<img width="859" alt="not showing" src="https://user-images.githubusercontent.com/68028032/196758193-95faf85c-7a78-46fd-9c69-a7aa89291972.PNG">
----------------------
working after deactivate the elementor and keeping the elementor pro
<img width="516" alt="showing after deac" src="https://user-images.githubusercontent.com/68028032/196758551-ca7f6094-896a-4f68-8fae-e6970b01b375.PNG">

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

WordPress Environment |   |  
-- | -- | --
Version: | 6.0.3 |  
Site URL: | http://shopa9.sg-host.com |  
Home URL: | http://shopa9.sg-host.com |  
WP Multisite: | No |  
Max Upload Size: | 256 MB |  
Memory limit: | 256M |  
Max Memory limit: | 768M |  
Permalink Structure: | /%postname%/ |  
Language: | en-US |  
Timezone: | 1 |  
Admin Email: | spiritucef@gmail.com |  
Debug Mode: | Inactive

</body>
</html>

**Comment by nicholaszein** [comment]
Hey @kaysenjp, 

Thank you for the feedback. 🙏 

⚠️ While reviewing your report, we noticed it was missing some key pieces of information:

- **Isolating the problem:** We do not provide support for 3rd party products. You need to make sure the problem happens only if Elementor, Elementor Pro, and Hello Elementor (theme) are active.
- **System info:** We need the full System Info from your Elementor > System Info page as explained in our guidelines. A screenshot of part of your configuration is not enough.

Without them, we simply can't help. 😕 

Moreover, it's important to mention that we do not provide support for 3rd party themes or features. If the issue is happening with a feature of your theme, but it works in Elementor, then you need to contact the theme developer and ask them to help you fix your issue. It's also important to mention that when you disable Elementor Core, Elementor Pro stops working as well since Elementor Pro is an add-on for Elementor Core and it needs Elementor Core active in order to work properly.

What you can try to do is to add the Google API Key to Elementor instead, by following [this article](https://elementor.com/help/google-maps-integration/), and see if the map works.

👉 Please follow the guidelines for opening a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Best regards,

Nick
