### ISSUE TITLE
🚀 Feature Request: tooltips feature for all widgets (In Advanced tab) (Duplicate of #18720, #16415, #11302, #5512)

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#20096]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

The tooltip feature in Elementor will be very useful. Using this feature, we can consider a help text for all widgets if desired, and this will be very useful for the user experience.

![Screenshot (832)](https://user-images.githubusercontent.com/103376243/196959787-07acb902-67c3-4fa5-a911-75f0f00f6b60.png)

### Describe the solution you'd like

tooltip feature in elementor

**Comment by nicholaszein** [comment]
Hello @Joliamendi!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #18720, #16415, #11302, and #5512, on the same subject, especially #18720 which is your own issue.

For this reason, I'm closing this issue and ↔️ **Merging** it with #16415, so we can have all the discussions in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened, and please do not post duplicate issues. 

Best regards,

Nick
