### ISSUE TITLE
✔️ 🐞 Bug Report: [v3.8-Beta] - Container - "UI Overlay" add horizontal scrolling to the document when hovering elements inside the container in some cases

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#20097]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If the container does not have padding by default, if we hover the widgets inside it, the horizontal scroll of the browser will appear. A very annoying ux in container.

### Steps to reproduce

https://user-images.githubusercontent.com/103376243/196962499-8aa5597c-3156-4373-8cda-7d598454e1c0.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

.

**Comment by nicholaszein** [comment]
Hello @Joliamendi! 

Thank you for submitting your issue! 🙏 

I can reproduce the issue. We will look into this and see if we can mitigate this issue.

Best regards

**Comment by Michaelgimii** [comment]
Hi @nicholaszein , I still see this bug in the version (3.8) you mentioned. Am I wrong?

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

I cannot reproduce this issue anymore. Tested with both v3.8 and Beta v3.9. This could actually be related to the complete viewport width of the browser window. If the document has less space than the Desktop breakpoint (1025px), including the vertical scrollbar width (usually 16px), it will show a horizontal scrollbar. But this happens by design because we can't simply zoom out the document viewport to fit it inside the space, this would make users confused. So if the document has less than 1025px + 16px of space, it will show the horizontal scrollback.

A simple "fix" would be to reduce the width of the Widget Panel.

I hope this clarifies your question.

If you think this is still a bug, please submit a [new bug report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) with the title "Container - UI Overlay STILL adds horizontal scrolling when hovering elements inside it".
