### ISSUE TITLE
[🧐 Evaluationg] Copy and Pasting from one tab to another not working properly on Safari

### ISSUE THREAD

**Issue by donwattz1459** [elementor/elementor#20091]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In safari, when copying and pasting from one page to another through different tabs, it is not working properly. See video recording. 

### Steps to reproduce

See Recording. 

https://user-images.githubusercontent.com/16137152/196798663-f0b968a5-e16a-4b52-9ec3-c4886b70ea00.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.16.1
	MySQL version: mariadb.org binary distribution v10.5.4
	PHP Version: 8.0.12
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://boob.wpdevurl.com
	Home URL: https://boob.wpdevurl.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: info@wattzwebdesign.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15

== Active Plugins ==
	CartFlows
		Version: 1.11.2
		Author: CartFlows Inc

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	Fluent Forms
		Version: 4.3.18
		Author: Contact Form - WPManageNinja LLC

	FluentSMTP
		Version: 2.2.0
		Author: FluentSMTP & WPManageNinja Team

	Kadence WooCommerce Email Designer
		Version: 1.5.7
		Author: Kadence WP

	ShortPixel Image Optimizer
		Version: 5.0.9
		Author: ShortPixel

	User Menus
		Version: 1.3.0
		Author: Code Atlantic

	Variation Swatches for WooCommerce
		Version: 1.0.5
		Author: CartFlows

	WooCommerce
		Version: 7.0.0
		Author: Automattic

	WooCommerce Cart Abandonment Recovery
		Version: 1.2.19
		Author: CartFlows Inc

	WooCommerce Product Add-Ons Ultimate
		Version: 3.11.8
		Author: Plugin Republic

	WooCommerce Stripe Gateway
		Version: 6.9.0
		Author: WooCommerce

	WOOCS - WooCommerce Currency Switcher
		Version: 1.3.9.2
		Author: realmag777

	WordPress Backup & Security Plugin - BlogVault
		Version: 4.82
		Author: Backup by BlogVault

	WP Social Ninja
		Version: 3.7.2
		Author: WPManageNinja LLC

	WP Social Ninja Pro
		Version: 3.7.1
		Author: WPManageNinja LLC

== Must-Use Plugins ==
	WP CLI Login Command Server
		Version: 1.3
		Author: Evan Mattson

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 3 of 3PHP: 2022-10-18 15:43:01 [warning X 7][/var/www/boob.wpdevurl.com/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-18 16:16:41 [warning X 2][/var/www/boob.wpdevurl.com/htdocs/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-18 16:23:11 [error X 1][/var/www/boob.wpdevurl.com/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/boob.wpdevurl.com/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/boob.wpdevurl.com/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/boob.wpdevurl.com/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/boob.wpdevurl.com/htdocs/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/boob.wpdevurl.com/htdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/boob.wpdevurl.com/htdocs/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/boob.wpdevurl.com/htdocs/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-10-18 20:30:46 [error X 6][https://boob.wpdevurl.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:767848] undefined is not an object (evaluating \'this.store.find((function(T){return T.original===C})).localized\') 
JS: 2022-10-19 12:49:12 [error X 2][https://boob.wpdevurl.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:1060991] null is not an object (evaluating \'$.getBoundingClientRect\') 
JS: 2022-10-19 13:01:14 [error X 1][https://boob.wpdevurl.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:767340] undefined is not an object (evaluating \'T.originalEvent.key.toLowerCase\') 

== Elementor - Compatibility Tag ==
	
	CartFlows: Compatible
	Ele Custom Skin: Compatible
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Ele Custom Skin: Compatible

**Comment by nicholaszein** [comment]
Hi @donwattz1459!

Thank you for contacting us.

You seem to have a Plugin conflict. What I'm seeing in your video is that a social icon is being pasted. This seems like a conflict with the plugin WP Social Ninja.

To isolate this conflict please try these **Troubleshooting steps**:

⚠️  Backup your website before proceeding, and if possible do it in a staging environment! ⚠️ 

1. Disable/Deactivate all your plugins  except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the plugin's support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2.  Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3.  Clear all types of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

If the problem persists, try contacting Elementor support (for Pro Users). To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon.

For non-Elementor Pro users, check out these resources:
* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

Regards
