### ISSUE TITLE
🚀 Feature Request: Client Basic Editing Mode

### ISSUE THREAD

**Issue by seanbajuice** [elementor/elementor#20116]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Whenever we build sites, we then hand them off to the client, where they can go crazy with elements we didn't use and settings they shouldn't touch.

### Describe the solution you'd like

If would be nice if we could have a client or basic editing mode that hides any elements not used on the site, and hides any settings that aren't typically needed after hand off.

### Describe alternatives you've considered

Providing very detail instructions and telling them not to touch stuff.

**Comment by nicholaszein** [comment]
Hello there @seanbajuice!

📢 We have great news! 

### We're happy to announce that this feature is already available in Elementor since version 2.0! 🥳 

You can find out more about it in the following links:

https://elementor.com/blog/role-manager/

https://elementor.com/blog/wordpress-user-roles-elementor-role-manager/

https://elementor.com/help/role-manager/

Feel free to check it out! 💪 

Cheers 🥂
