### ISSUE TITLE
❌ 🐞 Bug Report: Dynamic-tag - Internal URL' default value is empty

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20129]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi

In the dynamic tag > internal url, the default value is not displayed.

![Screenshot (840)](https://user-images.githubusercontent.com/88034902/197579539-1f81555e-85d6-4a47-b7f3-1c82bc9a34b2.png)

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for reaching out! 🙏 

#### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is the intended behavior of this feature. You need to select one of the queries to be able to find the internal URL you're looking for.

### ✅ What you can do to solve your issue:
Click on the dropdown to select what type of content you want to look for.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

❓ If you have questions or need general support, please use one of the following channels:

* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
