### ISSUE TITLE
The reason for having two similar widgets in Elementor (Accordion and toggle widgets)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20134]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team!

Since the beginning of working with Elementor, there has always been one question for me. **Why does Elementor offer two completely identical widgets?** (Accordion and toggle widgets)

These two widgets have a completely similar application. In some cases, they are superior to each other. Wouldn't it be better for you to merge these two widgets together?
If you check the new page builders, they only offer one widget (accordion).

### Describe the solution you'd like

If you think it would be better if these two widgets were merged together, now is not too late. So by releasing the nested element feature, only implement the accordion widget as nested. Users will certainly welcome the integration of these two widgets.

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for submitting a feature request! 🙏 

⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. These widgets have different use cases, and we won't remove them because of backward compatibility.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
