### ISSUE TITLE
🚀 Feature Request: Apply different styles when an element is set to Sticky

### ISSUE THREAD

**Issue by BlackSheep42** [elementor/elementor#20148]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

A fully featured shrinking sticky header built into the core would negate the use of additional 3rd party plugins, removing their additional code, performance penalties and any compatibility issues.

### Describe the solution you'd like

The built in shrinking header should be able to control when it is activated ie: by window scroll depth. It should be able to alter the header background colour and/or transparency, change the site logo size with the ability to alter its colour or be replaced by an alternative version. Also it should have the ability to remove chosen elements within the header. All of these features should be amendable at any of the custom break points available.

### Describe alternatives you've considered

I currently use 3rd party plugins and custom css to achieve the results I require.

**Comment by nicholaszein** [comment]
Hello @BlackSheep42,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. Here's why:

Since the sticky effect is universal (can be applied to virtually any native Elementor element), there is no way to provide consistent settings for every use case without compromising on usability. 

#### 👍 But we do have a way for you to customize your elements when they are sticky.

Simply use the Custom CSS box of the sticky element with the class `.elementor-sticky--effects`. This way you can add your own custom CSS to change the design of your sticky elements. I do this all the time, and it's really cool! All you need to do is to use the following declaration:

````
selector.elementor-sticky--effects {
    /* Do something here */
}
````

For example, let's say I have a Container that I want to be sticky. I want the background to change from transparent to white, and I want to change the height of the container as well. This is what I would do:

````
/* First we set some variables to be easy to change in one location */
selector {
    --header-min-height: 6rem;
    --header-bg-color: rgba(255,255,255,0); /* Safari fix for transparency */
}

/* Now we set the values for when the element is sticky */
selector.elementor-sticky--effects {
    --header-min-height: 4rem;
    --header-bg-color: rgba(255,255,255,1);
}

/* Finally we apply the styles */
selector {
    min-height:  var(--header-min-height);
    background-color: var(--header-bg-color);
    transition: height .2s ease-out, background-color .2s ease-out;
}
````

You can read more about this feature here: #4923.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
