### ISSUE TITLE
🚀 Feature Request: Find And Replace Content Or Text, Elementor To Code View

### ISSUE THREAD

**Issue by dverma85** [elementor/elementor#20157]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

so, i am looking for find and replace content or text in elementor which is not available right now . So please add find and replace text features so that we can build multiple pages with same content .
and also add code view editor in elementor .

### Describe the solution you'd like

so, i am looking for find and replace content or text in elementor which is not available right now . So please add find and replace text features so that we can build multiple pages with same content .
and also add code view editor in elementor .

**Comment by nicholaszein** [comment]
Hello @dverma85,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. Here's why:

Find & Replace are database-related features, and should be handled by a plugin that handles the database. This goes beyond what Elementor is intended to be used. 

For "code view", it wasn't clear what you meant, since there was no detailed explanation. But we do have these two features:

- [Custom Code (Pro)](https://elementor.com/help/custom-code-pro/)
- [Code Highlight (Pro)](https://elementor.com/help/code-highlight-pro/)

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
