### ISSUE TITLE
❌ Invalid Issue: Issue with my website

### ISSUE THREAD

**Issue by richardsautorae** [elementor/elementor#20165]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Edit in Elementor looks how I want my website to look. But on the internet the website looks horrible. All the header pictures have gone weird.

### Steps to reproduce

Have a look on my website.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Sorry dont know

**Comment by richardsautorae** [comment]
== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: MariaDB Server v10.4.25
	PHP Version: 8.0.24
	PHP Memory Limit: 512M
	PHP Max Input Vars: 6144
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://richardsauto.com.au
	Home URL: https://richardsauto.com.au
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: Australia/Adelaide
	Admin Email: olivia@richardsauto.com.au
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.9.2
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) WordPressDesktop/7.2.0 Chrome/89.0.4389.128 Electron/12.0.13 Safari/537.36

== Active Plugins ==
	Advanced Shipment Tracking for WooCommerce
		Version: 3.4.7
		Author: zorem

	Akismet Anti-Spam
		Version: 5.0.1
		Author: Automattic

	Crowdsignal Forms
		Version: 1.6.6
		Author: Automattic

	Crowdsignal Polls & Ratings
		Version: 3.0.9
		Author: Automattic, Inc.

	Elementor
		Version: 3.9.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0-dev5
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 2.6.28
		Author: Facebook

	Force Refresh
		Version: 2.6.0
		Author: Jordan Leven

	Gutenberg
		Version: 14.4.0
		Author: Gutenberg Team

	Jetpack
		Version: 11.5-a.9
		Author: Automattic

	Layout Grid
		Version: 1.8.2
		Author: Automattic

	Mailchimp for WooCommerce
		Version: 2.7.5
		Author: Mailchimp

	Page Optimize
		Version: 0.5.2
		Author: Automattic

	PDF Invoices & Packing Slips for WooCommerce
		Version: 3.2.2
		Author: WP Overnight

	Starter Templates
		Version: 3.1.17
		Author: Brainstorm Force

	Storefront Powerpack
		Version: 2.0.0
		Author: WooCommerce

	Variation Swatches for WooCommerce
		Version: 1.0.5
		Author: CartFlows

	WooCommerce
		Version: 7.0.0
		Author: Automattic

	WooCommerce Payments
		Version: 4.9.0
		Author: Automattic

	WooCommerce PayPal Checkout Gateway
		Version: 2.1.3
		Author: WooCommerce

	WooCommerce PayPal Payments
		Version: 1.9.4
		Author: WooCommerce

	WooCommerce Product Add-ons
		Version: 5.0.0
		Author: WooCommerce

	WooCommerce Shipping & Tax
		Version: 1.26.3
		Author: WooCommerce

	WordPress.com Editing Toolkit
		Version: 3.46638
		Author: Automattic

	WPForms Lite
		Version: 1.7.7.2
		Author: WPForms


== Must-Use Plugins ==
	WP.com Site Helper
		Version: 
		Author: 


== Elements Usage ==
	
	page : 1
		button : 4
		heading : 1
		icon-box : 3
		image-box : 3
		video : 1
	wp-post : 0
		button : 5
		container : 1
		divider : 1
		google_maps : 1
		heading : 10
		icon-box : 6
		image-box : 3
		shortcode : 2
		social-icons : 1
		text-editor : 2
	wp-page : 12
		accordion : 1
		button : 1
		divider : 7
		heading : 11
		icon-box : 2
		image : 25
		spacer : 2
		text-editor : 32
		video : 17
		wc-categories : 1


== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Default to New Theme Builder: Active by default
	Landing pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
Log: showing 20 of 362022-09-21 00:25:47 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-09-21 00:25:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev4',
  'to' => '3.9.0-dev1',
)]
2022-09-21 00:25:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0-dev4',
  'to' => '3.9.0-dev1',
)]
2022-10-04 13:25:37 [info] elementor::elementor_updater Started 
2022-10-04 13:25:37 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-04 13:25:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev1',
  'to' => '3.9.0-dev2',
)]
2022-10-24 01:36:45 [info] elementor::elementor_updater Started 
2022-10-24 01:36:45 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-24 01:36:46 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-24 01:36:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev3',
)]
2022-10-24 01:36:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev2',
  'to' => '3.9.0-dev3',
)]
2022-10-28 01:26:14 [info] elementor::elementor_updater Started 
2022-10-28 01:26:15 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-28 01:26:15 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-28 01:26:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.9.0-dev4',
)]
2022-10-28 01:26:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-dev3',
  'to' => '3.9.0-dev4',
)]
2022-10-28 12:39:43 [info] elementor-pro::elementor_pro_updater Started 
2022-10-28 12:39:43 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-28 12:39:43 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-28 12:39:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev35',
  'to' => '3.9.0-dev5',
)]

PHP: showing 4 of 4PHP: 2022-08-26 11:43:20 [warning X 22][/srv/htdocs/wp-content/plugins/elementor/core/base/document.php::249] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-04 13:25:39 [notice X 54758][/srv/htdocs/wp-content/plugins/elementor/modules/performance-lab/module.php::31] Required parameter $url follows optional parameter $size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-28 04:22:35 [warning X 1][/srv/htdocs/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/srv/htdocs/wp-content/uploads/elementor/css/post-1305.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-28 12:45:21 [warning X 1][/srv/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2022-10-17 02:45:56 [error X 2][https://richardsauto.com.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.0-dev2:3:694256] T.getContainer is not a function 
JS: 2022-10-28 02:08:38 [error X 11][https://richardsauto.com.au/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:31703] Cannot read property \'tools\' of undefined 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @richardsautorae,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

We can't reproduce your issue, and it seems you're not only running multiple plugins that might be conflicting with Elementor, but you're also running the Elementor Developer Edition, which **SHOULDN'T BE USED ON PRODUCTION WEBSITES** as it's built to be used by developers to test **unstable new features**.

## ⚠️ Please note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

### You can try to follow the troubleshooting steps outlined in [this article](https://elementor.com/help/changes-dont-appear-online/). If they don't work, then follow the steps below:

⚠️  **Backup** your website before proceeding, and if possible do it in a staging environment! 

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

If the issue persists, try contacting Elementor support (for Pro Users). To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon.

For non-Elementor Pro users, check out these resources:
* [Elementor Community](https://facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

Regards,

Nick
