### ISSUE TITLE
🐞 Bug Report: Template Widget doesn't correctly load responsive styles of embedded template (Duplicate of #19924, #19917, #19922, #19894, #19930, #20001)

### ISSUE THREAD

**Issue by elosha** [elementor/elementor#20172]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Template Widget doesn't correctly load responsive styles of an embedded template.

Generated a template. Used different paddings in a column for each responsive viewport size. Template looks like expected.👍

Once the template was embedded inside a Template Widget, only desktop padding was applied to the column for all viewports. 😳

### Steps to reproduce

1) Generate an empty template
2) Put a Column widget inside a section
3) Define padding for this widget,
a) one for desktop and
b) a different one for mobile viewports
4) Put Lorem Ipsum text into the column, save template

5) Go to any page and add the Template Widget to a section
6) Embed our template
7) Save page

8) View page in mobile preview –> mobile padding isn't applied, just desktop padding

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Wordpress 6.0.2
Elementor 3.7.8

**Comment by nicholaszein** [comment]
Hello @elosha! 

Thank you for submitting your issue! 🙏 

We are already aware of this issue, and a fix will be introduced in **Elementor v3.8** that should solve it as it is related to a few other issues.

#### ⚠️ While reviewing your report, we noticed it was missing some key pieces of information.

👉 Please follow the guidelines for opening a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

* **System info:** You did not provide your [System Info](https://elementor.com/help/systems-info/) as outlined in our guidelines.

📋 This issue is a **Duplicate** of #19924, #19917, #19922, #19894, #19930, and #20001, which are on the same subject. For this reason, I'm closing this issue.

Feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards

**Comment by nicholaszein** [comment]
Hello there @elosha!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.8.0**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
