### ISSUE TITLE
⛔ 🚀 Feature Request: Form - Keep the name of Uploaded Files and append a uniqid() to the file name instead (Duplicate of #8443, #11746)

### ISSUE THREAD

**Issue by mohammad-mekawy** [elementor/elementor#20170]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Keeping the original name for the uploaded files + Adding a uniqid

### Describe the solution you'd like

I've found a suitable solution for that
You could go to this path
elementor-pro\modules\forms\fields\upload.php

Go to line 434
			$filename = uniqid() . '.' . $file_extension;
Add $file['name'] . before uniqid()

So the line should be 
			$filename = $file['name'] . uniqid() . '.' . $file_extension;

This should keep the original name plus a uniqid, so both security and keeping original file name are achieved

**Comment by nicholaszein** [comment]
Hello @mohammad-mekawy,

Thank you for submitting a feature request! 🙏 

⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

You can instead use the method described in [this comment](https://github.com/elementor/elementor/issues/8443#issuecomment-509007423) to filter the file name and make it your own.

📋 This issue is a **Duplicate** of #8443 and #11746, which are on the same subject. I'm closing this issue and ↔️ **Merging** it with the [original](https://github.com/elementor/elementor/issues/8443), so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
