### ISSUE TITLE
🚀 Feature Request: Container - Set Default padding only for the Root Container

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20186]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor developer.

Since the introduction of containers, there has been a fundamental challenge for containers. And the problem was that by adding any content inside the page, it would stick to the sides. So, the only way was to manually add a left and right padding for each container we add. This was very time consuming, as we had to repeat this for each container.
For this reason, in version 3.7, you added the default padding feature in the site settings. This was a nice feature because using it we could set the default padding once and for all so we don't have to repeat it for every container. But the problem with the default padding option is that it applies to all containers (inner containers). So, if we nest two containers and then add content, if the default padding is 10 pixels, since the two containers are nested, our content will be 20 pixels from the margin, which is problematic. In this case, we have to manually set the padding of the inner container to 0 so that our content is 10 pixels away from the border.
So I think this challenge is still there. But it can be solved.

### Describe the solution you'd like

If the default padding, which is in the site settings, is applied only to the first containers, this problem will be completely solved. There is really no need for all containers to have padding. We only need padding so that our content doesn't stick to the side of the screen. So, I think it would be much better if the default padding is added **only for the first container or rather the parent containers**. So the default padding in inner containers will be 0.

I hope this is a useful solution.

**Comment by nicholaszein** [comment]
Hello @79ho3ein,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. Here's why:

The default padding covers more than the root container. It helps select inner containers as well. For this reason, we do not wish to regress something that has been already decided in order to cover multiple use cases.

An alternative is to set your own custom CSS to cover this case. Here's a tested snippet that works:

For Fullwidth Containers:
````
.elementor[data-elementor-type] > .e-con-full {
    --padding-left: 8rem;
    --padding-right: 8rem;
}

````

For Boxed Containers:
````
.elementor[data-elementor-type] > .e-con:not(.e-con-full) {
    --padding-left: 8rem;
    --padding-right: 8rem;
}

````

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
