### ISSUE TITLE
❌ 🐞 Bug Report: loop builder bugs - elementor pro 3.8

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20198]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor team.

There are a few bugs in the loop builder that I recently came across. Please check them out if possible.

1- When editing the loop template, basic widgets such as heading and button widgets are not displayed in the widgets panel. The only way to access them is to search.

2- If we do not put any content in the ring format and return to the previous page where the ring grid widget is, it is not possible to access the ring format. In fact, the edit template handle disappears.

https://user-images.githubusercontent.com/77163248/198959703-57acf396-e772-48bc-a5d3-ad3305ab95af.mp4

### Steps to reproduce

The steps are simple and clear above.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-localhost-31-10-2022.txt](https://github.com/elementor/elementor/files/9899172/system-info-localhost-31-10-2022.txt)

**Comment by fabianenzensperger** [comment]
+1

**Comment by 79ho3ein** [comment]
The post title widget is not displayed in the loop.

**Comment by nicholaszein** [comment]
Hello @79ho3ein! 

Thank you for submitting your issue! 🙏 

Please allow me some time to investigate it, and get back to you with my findings. 🧐 

### ⚠️ Please, when submitting a Bug Report make sure you are submitting ONE BUG PER ISSUE. We cannot track multiple bugs in one issue.

Thanks 🙏 

Best regards

**Comment by nicholaszein** [comment]
Hello @79ho3ein ,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- I can see all widgets inside the widget panel when editing the Loop Item template, both inside an Archive Page or directly by editing the template from the Library.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

For issue #2, you'll need to submit a new report since we won't be able to track it here.

Kind regards
