### ISSUE TITLE
❌ Invalid Issue: ACF fields not working

### ISSUE THREAD

**Issue by 3l3mentor** [elementor/elementor#20208]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor and Elementor Pro has been automatically updated to 3.8.
Since then all the ACF fields disappear of my website frontend.

After few tests, I discovered that the problem is linked to Elementor Pro 3.8 only (not Elementor core).
After few tests, I also discovered that this problem have been reported 21 days ago. Long before the release:
https://github.com/elementor/elementor/issues/20015

But guess what? You close it arguing that is not reproductible...
After three updates breaking websites, I decided to stop using Elementor at all.

### Steps to reproduce

1. Update Elementor Pro to 3.8

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

### System Info

I have roll-back to Elementor Pro 3.7.7 and I can't add the system info as I don't have the time to create a staging environnement for you. Do your job, don't count on other to do it for you.

**Comment by nicholaszein** [comment]
Hey @3l3mentor, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- **Steps to replicate:** You did not provide any way for us to try to reproduce your issue;
- **Isolating the Problem:** You need to ensure this only happens while using Elementor, Elementor Pro, and the Hello Elementor theme. We do not provide support for 3rd-party themes and plugins.
- **System info:** You did not provide any information about your [System Info](https://elementor.com/help/systems-info/) as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Without them, we can't help because we can't reproduce the same issue if we don't know how to reproduce it. On our preliminary test ACF fields are working as expected. The issue reported might be related to Object Cache, or something else. If we do not have the appropriate information to validate your issue, we can't solve it. There are infinite combinations of plugins and themes that might cause the issue you're reporting.

👉 Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Feel free to open a new issue in accordance with these guidelines. 😉 

Best regards,

Nick

**Comment by nicholaszein** [comment]
Hello @3l3mentor,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:

Updating to the latest version of Elementor and Elementor Pro, I was able to add several fields without reproducing your issue. All fields returned the correct values.

![image](https://user-images.githubusercontent.com/113993460/199230294-aabff6c8-2790-4005-90a7-cfcb1872fe81.png)
_ACF Field Group Settings_


![image](https://user-images.githubusercontent.com/113993460/199230444-cf469811-b545-45fe-9c73-f475380b93aa.png)
_Selected options_


#### Then in the Elementor Editor, I added dynamic tags to various widgets, and the values always returned correctly.


![image](https://user-images.githubusercontent.com/113993460/199230807-5ec4dfd2-98d5-4a79-846c-1153b602f303.png)
_Elementor Editor_



![image](https://user-images.githubusercontent.com/113993460/199231291-5cddd1b1-fe08-4317-adc3-c5bb0e2a3932.png)
_Website Frontend_


### You can verify my System Info
<details>
<summary>System Info</summary>
		
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.4
	MySQL version: mariadb.org binary distribution v10.5.17
	PHP Version: 7.4.32
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: localhost
	Home URL: localhost
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Sao_Paulo
	Admin Email: redacted
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.0.3
		Author: WP Engine

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com


== Elements Usage ==
	
	wp-post : 0
		button : 1
		container : 1
		heading : 8
		image : 1
		image-gallery : 1


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Inactive
	Scroll Snap: Active by default


== Log ==
	
Log: showing 13 of 132022-11-01 07:57:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 07:57:03 [info] elementor-pro::elementor_pro_updater Started 
2022-11-01 07:57:03 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-01 07:57:03 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-01 07:57:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 07:57:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 07:57:03 [info] elementor::elementor_updater Started 
2022-11-01 07:57:03 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-01 07:57:03 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-01 07:57:03 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-01 07:57:03 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-01 07:57:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 07:57:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
</details>

__________________________________

### ✅ What you can do to solve your issue:

⚠️  **Backup** your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

#### 👎 If the issue persists, try contacting 💎 **Elementor Support** (for Pro Users). 
To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Comment by nicholaszein** [comment]
Hello @3l3mentor.

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- I could consistently update Elementor to the latest version and see all issues appearing as expected.

### ✅ What you can do to solve your issue:⚠️  **Backup** your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

#### 👎 If the issue persists, try contacting 💎 **Elementor Support** (for Pro Users). 
To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Comment by rexrainey** [comment]
I'm having the same issue. When using ACF fields within a "Template" widget, the info will not show on the live page.

**Comment by wpsupportconsulting** [comment]
Same problem here. ACF fields within a template. The data will not show on the front end. I checked on a staging installation and v3.7.7 of Pro ran everything fine. As soon as I updated to 3.8 on Pro (core was OK), the data from the ACF fields literally disappear.

**Comment by hax1** [comment]
same problem here. some fields show, some don't.

**Comment by reuhno** [comment]
Same issue here, and I know an other person who is having the problem. ACF fields suddenly stopped working in loops on front, this needs to be fixed ASAP

Meanwhile, rollback to 3.7.7...

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.1**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
