### ISSUE TITLE
⛔ 🐞 Bug Report: Single Product (WC) - Share Buttons not working on Mobile

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20212]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

**Describe the bug**

Hi

If we use elementor share buttons widget in single product, it doesn't work. After clicking on the share buttons, only a white page of the browser opens with the address about:blank and nothing else happens.

### Steps to reproduce

1- Add share buttons widget on single product page.
2- Using a mobile phone, enter the website and click on the sharing buttons (especially WhatsApp and Telegram)

I am experiencing this bug using an Android phone - Chrome browser. If I'm not mistaken, this bug appeared in version 3.6.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-domain.com-01-11-2022.txt](https://github.com/elementor/elementor/files/9909947/system-info-domain.com-01-11-2022.txt)

**Comment by nicholaszein** [comment]
Hello @79ho3ein! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hey @79ho3ein!

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* Using Elementor v3.8.0 and Elementor Pro v3.8.1, with the Hello Elementor theme v.2.6.1, WooCommerce v7.1, and WordPress version 6.1, I was able to add and use every social media icon available in the Social Share widget on an Android phone without any issues.
* Your issue most likely is either related to your mobile device configurations or browser, your internet connection, or your server.

### ✅ What you can do to solve your issue:

#### 🧐 Before continuing, and in order to solve your issue, please try these **Troubleshooting steps**:

⚠️  **Backup** your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.
5. 5. Try with another device or browser.

#### 👎 If the issue persists, try contacting 💎 **Elementor Support** (for Pro Users). 
To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon.

For non-Elementor Pro users, check out these resources:
- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Regards
