### ISSUE TITLE
❌ Invalid Issue: You can edit a box in live

### ISSUE THREAD

**Issue by DigitalRefresh** [elementor/elementor#20218]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I've just launched another Elementor site - it's excellent btw.

https://hohohomevisitsanta.co.uk/

When you're in live, you can type in new text to the White box/section near the end of the page

I recreated the issue on Google Chrome, MS Edge and Opera

### Steps to reproduce

Login into any browser... 
go to https://hohohomevisitsanta.co.uk/
Find the white box near bottom and find the text ''Countless adult visitors to our Santa have turned back as the children head excitedly out the door and whispered, “Best Santa EVER!”''

You can select the text and delete it and you can change it... it doesn't save... it just I have never seen this

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Not sure what this section is for

**Comment by nicholaszein** [comment]
Hey @DigitalRefresh, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- **Steps to replicate:** You did not provide any way for us to try to reproduce your issue. Please do not describe how to see the issue, but how to make it happen. What did you do prior to the issue happening?;
- **Isolating the Problem:** You need to ensure this only happens while using Elementor, Elementor Pro, and the Hello Elementor theme. We do not provide support for 3rd-party themes and plugins. Without providing complete System Info, we can't try to reproduce your issue;
- **System info:** You did not provide any information about your [System Info](https://elementor.com/help/systems-info/) as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). As indicated above, there is no way for us to verify and validate your issue if we don't know anything about your website in order to try to reproduce it. My suspicion is that you have a performance optimization plugin that is conflicting with Elementor and causing the issue you're reporting. Either this or you have another plugin causing it. This doesn't happen with only Elementor and Elementor Pro installed.

Without them, we simply can't help. 😕 

👉 Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Feel free to open a new issue in accordance with these guidelines. 😉 

Best regards,

Nick
