### ISSUE TITLE
[🧐 Evaluating] Vimeo Background video

### ISSUE THREAD

**Issue by feriamsidera** [elementor/elementor#20219]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Vimeo background videos are now showing the play button for a few seconds after they load. 

### Steps to reproduce

Add Vimeo video link to background element. 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: Percona Server (GPL), Release '42', Revision 'b0a7dc2da2e' v5.7.39-42
	PHP Version: 8.0.20
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://radeuslab.wpengine.com
	Home URL: https://radeuslab.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: -5
	Admin Email: jeff@design903.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.10.2
		Author: Delicious Brains

	Ajax Search Pro
		Version: 4.23
		Author: Ernest Marcinko

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	Dynamic Visibility for Elementor
		Version: 5.0.1
		Author: Dynamic.ooo

	Easy Updates Manager
		Version: 9.0.14
		Author: Easy Updates Manager Team

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com

	Gravity Forms
		Version: 2.6.7
		Author: Gravity Forms

	Gravity Forms reCAPTCHA Add-On
		Version: 1.1
		Author: Gravity Forms

	GTranslate
		Version: 2.9.14
		Author: Translate AI Multilingual Solutions

	OoohBoi Steroids for Elementor
		Version: 2.0.3
		Author: OoohBoi

	SVG Support
		Version: 2.5.1
		Author: Benbodhi

	Timeline Widget For Elementor
		Version: 1.4
		Author: Cool Plugins

	WooCommerce
		Version: 7.0.1
		Author: Automattic

	YITH WooCommerce Catalog Mode
		Version: 2.15.0
		Author: YITH

	Yoast SEO
		Version: 19.9
		Author: Team Yoast

== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	WP Engine Cache Plugin
		Version: 1.1.0
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.6.0
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.10
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 362022-11-01 13:23:26 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-01 13:23:26 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-01 13:23:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-01 13:23:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 13:23:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-01 13:23:28 [info] elementor-pro::elementor_pro_updater Started 
2022-11-01 13:23:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-01 13:23:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-01 13:23:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 13:23:29 [info] elementor-pro::elementor_pro_updater Started 
2022-11-01 13:23:29 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-01 13:23:29 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-01 13:23:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 13:23:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-01 13:23:30 [info] elementor::elementor_updater Started 
2022-11-01 13:23:30 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-01 13:23:30 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-01 13:23:30 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-01 13:23:30 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-01 13:23:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]

PHP: showing 3 of 3PHP: 2022-11-01 13:23:37 [warning X 30][/nas/content/live/radeuslab/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1482] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-01 13:29:25 [notice X 24][/nas/content/live/radeuslab/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-01 13:29:27 [notice X 6][/nas/content/live/radeuslab/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /nas/content/live/radeuslab/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /nas/content/live/radeuslab/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /nas/content/live/radeuslab/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /nas/content/live/radeuslab/wp-content/plugins/dynamic-visibility-for-elementor/class/controls.php(48): Elementor\Controls_Manager -> register_control()
',
)]

JS: showing 3 of 3JS: 2022-11-01 18:48:49 [error X 1][https://radeuslab.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:119704] undefined is not an object (evaluating \'elementorModules.editor.views\') 
JS: 2022-11-01 18:48:49 [error X 1][https://radeuslab.wpengine.com/wp-content/plugins/ooohboi-steroids-for-elementor/assets/js/ob-steroids-editor.js?ver=2.0.315072022:22:14] Can\'t find variable: elementor 
JS: 2022-11-01 18:48:49 [error X 1][https://radeuslab.wpengine.com/wp-content/plugins/elementor/assets/js/container-converter.min.js?ver=3.8.0:2:3369] undefined is not an object (evaluating \'$e.modules.document.CommandHistory\') 

== Elementor - Compatibility Tag ==
	
	Dynamic Visibility for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	OoohBoi Steroids for Elementor: Compatibility not specified
	Timeline Widget For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @feriamsidera! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hey @feriamsidera!

Thank you for being so patient! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This was tested with multiple videos and multiple connection velocities, with the latest versions of Elementor (v3.8.1), Elementor Pro (v3.8.1), and Hello Elementor (v.2.6.1), and we couldn't reproduce your issue. The video might take some time to load (see the screencast below using throttled 3g connection) which is understandable considering it's a 4k video, but no play button appears during that time.


https://user-images.githubusercontent.com/113993460/201533224-51955d10-b6d2-4f0b-a7f7-4d4e7803b2ad.mp4



### ✅ What you can do to solve your issue:
* Try temporarily disabling your performance optimization solutions. It's most likely an issue caused by them conflicting with Elementor.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
