### ISSUE TITLE
🔗 🚀 Feature Request: Self-host Font Awesome for GDPR compliance (Related to #4544)

### ISSUE THREAD

**Issue by clmnsm** [elementor/elementor#20210]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

To make a website fully GDPR/DSGVO compliant, it needs to only load resources from the local server.

Google Fonts can easily be locally cached via the third-party OMGF Plugin, which is great. But for Font Awesome, there's no such feature.

### Describe the solution you'd like

Allow us to (optionally) upload a downloaded font awesome pro package (as a zip) instead of supplying a Kit ID. 

The packages can be downloaded here after login:
https://fontawesome.com/download

### Describe alternatives you've considered

Converting Font Awesome to an icomoon package might be possible, but is probably really tedious.

**Comment by nicholaszein** [comment]
Hello @clmnsm,

thanks for submitting your feature request! 🙏 

Please understand that while we do welcome new feature requests, we can't promise they will be considered or added to our roadmap for the time being. 

### 🔗 This issue is a Duplicate or Related to #4544.

Which is on the same subject. 

For this reason, I'm 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick
