### ISSUE TITLE
🐞 Bug Report: Posts / Loop Pagination: "Load on Click" option shows spinner not centralized in the button when loading

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20224]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

after clicking on load page button , the spinner is not exactly in the center of the button.

![Screenshot (865)](https://user-images.githubusercontent.com/77163248/199433665-17d616c9-e3f6-44d0-8915-bc0f70114b09.png)

This bug seems to have appeared in the new version.

### Steps to reproduce

in posts or loop Grid widget, enable **load on click** pagination. after click on it , the spinner It will not be in the center of the button.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-localhost-01-11-2022.txt](https://github.com/elementor/elementor/files/9917820/system-info-localhost-01-11-2022.txt)

**Comment by nicholaszein** [comment]
Hi @79ho3ein! 

Thank you for submitting your issue! 🙏 

Let me check this issue and I'll get back to you soon! 😉

**Comment by nicholaszein** [comment]
Hello @79ho3ein,

Thank you for your patience! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* Using Elementor v3.8.1, Elementor Pro v3.8.1, and Hello Elementor v2.6.1, with the same experiments enabled, I couldn't reproduce your issue in any way. 
* The spinner icon always appears centralized. 
* This might be something related to how you setup your styles, or your browser cache. 
* You can see both videos below, one from the blog page, the other from the homepage, neither of the widget behaved like you reported.

https://user-images.githubusercontent.com/113993460/201535160-a8742dfb-4de0-41f4-aaa6-2705faef4b19.mp4


https://user-images.githubusercontent.com/113993460/201535177-363d7649-22d5-41ff-8b11-9480f5d242c2.mp4



### ✅ What you can do to solve your issue:
* Check the styles you applied to the pagination button.
* Clear your browser cache.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Comment by 79ho3ein** [comment]
Hi @nicholaszein , I apologize for the delay. Everything works fine in the new version. Thanks for the great videos and also for your time.
