### ISSUE TITLE
❌ Invalid Issue: This plugin failed to load properly and is paused during recovery mode - msg in WP 6.1

### ISSUE THREAD

**Issue by milosrad22** [elementor/elementor#20237]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

website inaccessible after updates, compatibility issues. Error is shown in WP dashboard, plug-ins section:
Msg:
"
Version 3.1.1 | By [Elementor.com](https://elementor.com/) | [Visit plugin site](https://elementor.com/)
 This plugin failed to load properly and is paused during recovery mode.
An error of type E_ERROR was caused in line 46 of the file /home3/realnetc/public_html/wp-content/plugins/elementor-pro1/modules/theme-builder/documents/theme-document.php. Error message: Uncaught ReflectionException: Method get_site_editor_type does not exist in /home3/realnetc/public_html/wp-content/plugins/elementor-pro1/modules/theme-builder/documents/theme-document.php:46 Stack trace: #0 /home3/realnetc/public_html/wp-content/plugins/elementor-pro1/modules/theme-builder/documents/theme-document.php(46): ReflectionClass->getMethod('get_site_editor...') #1 /home3/realnetc/public_html/wp-content/plugins/elementor-pro1/modules/theme-builder/documents/theme-document.php(127): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_site_editor_type_bc() #2 /home3/realnetc/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(94): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_create_url() #3 /home3/realnetc/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create->create_item_url_by_document_class('ElementorPro\\Mo...') #4 /home3/realnetc/publ
"

### Steps to reproduce

1. update WP to 6.1
2. have Elementor PRO 3.1.1 plug in installed
3. Try accessing the website
4. Error message:
" There has been a critical error on this website, putting it in recovery mode. Please check the Themes and Plugins screens for more details. If you just installed or updated a theme or plugin, check the relevant page for that first.

[Learn more about troubleshooting WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)
"plug-in

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

here attached
[system-info-realnetcre.com-02-11-2022.txt](https://github.com/elementor/elementor/files/9920683/system-info-realnetcre.com-02-11-2022.txt)

**Comment by mateitudor** [comment]
Elementor Pro 3.1 is about 2 years old, have you considered upgrading to a newer version?

**Comment by nicholaszein** [comment]
Hello @milosrad22,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* You are using an older version of Elementor Pro that is not supported anymore and might be incompatible with the latest version of Elementor Core. Please read [this article](https://elementor.com/help/what-happens-to-my-site-if-i-cancel-elementor-pro/) to know more about your issue.

### ✅ What you can do to solve your issue:
* Update Elementor Pro to the latest 3.8 version

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
