### ISSUE TITLE
⛔ 🐞 Bug Report: Additional Breakpoints - Laptop @media queries overriding Table @media queries on frontend

### ISSUE THREAD

**Issue by FauzanEdris** [elementor/elementor#20234]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

have a weird issue with css in responsive mode, where when in tablet mode it will use the laptop css.. for more details please see the image..

**External File**
Editor:
![image](https://user-images.githubusercontent.com/30016486/199490012-f5fca78e-a685-4e31-b0d2-762126519cc9.png)

Frontend:
![image](https://user-images.githubusercontent.com/30016486/199490056-4be1f920-0478-474a-9836-72568e3f9a2b.png)

**Internal Embedding**
Editor:
![image](https://user-images.githubusercontent.com/30016486/199490131-41891413-caba-46a9-91aa-dd462527c156.png)

Frontend:
![image](https://user-images.githubusercontent.com/30016486/199490174-debaf4a8-09d9-4567-b123-c4d7a73be932.png)

whereas in the editor, css works fine..

i have generated data many times, but it doesn't work..

when i try to replicate it locally, this issue occurs.. i need to disable the code that generates the css file and suddenly it works again and i can't duplicate it anymore...

### Steps to reproduce

just use [this template](https://drive.google.com/file/d/1ReTwKXVy_HxL31FVlLewL0uXUJthKlOu/view?usp=share_link) or set the template like that, and you all set.. im just configure the column width in each device..

for the record, maybe you can't replicate it because right now i can't replicate it either and now im stuck

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.46 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141 OpenSSL/1.0.2u mod_wsgi/3.5 Python/2.7.13
	MySQL version: MySQL Community Server (GPL) v5.7.34
	PHP Version: 8.0.8
	PHP Memory Limit: 128M
	PHP Max Input Vars: 2000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: http://localhost/testing/elementor
	Home URL: http://localhost/testing/elementor
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: fauzanedris@yahoo.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.8.0
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
Log: showing 7 of 72022-11-02 04:28:02 [info] elementor::elementor_updater Started 
2022-11-02 04:28:02 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-02 04:28:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-02 04:28:02 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-02 04:28:02 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-02 04:28:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-02 04:28:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]

JS: showing 2 of 2JS: 2022-11-02 09:06:49 [error X 3][http://localhost/testing/elementor/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.8.0:2:32810] elementorFrontendConfig is not defined 
JS: 2022-11-02 09:16:04 [error X 1][http://localhost/testing/elementor/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.8.0:2:2932] elementor_new_template_form_controls is not defined 

PHP: showing 3 of 3PHP: 2022-11-02 09:12:44 [warning X 2][/Users/fauzan/Sites/localhost/testing/elementor/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined array key "new_version" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-02 09:16:45 [warning X 2][/Users/fauzan/Sites/localhost/testing/elementor/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-02 10:38:11 [error X 1][/Users/fauzan/Sites/localhost/testing/elementor/wp-content/plugins/elementor/core/kits/manager.php::265] Uncaught Error: Call to a member function enqueue() on null in /Users/fauzan/Sites/localhost/testing/elementor/wp-content/plugins/elementor/core/kits/manager.php:265
Stack trace:
#0 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/class-wp-hook.php(308): Elementor\Core\Kits\Manager->frontend_before_enqueue_styles('')
#1 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /Users/fauzan/Sites/localhost/testing/elementor/wp-content/plugins/elementor/includes/frontend.php(630): do_action('elementor/front...')
#4 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#5 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/script-loader.php(2180): do_action('wp_enqueue_scri...')
#7 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts('')
#8 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#9 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#10 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/general-template.php(3043): do_action('wp_head')
#11 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/template.php(783): require_once('/Users/fauzan...')
#12 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#13 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#14 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/general-template.php(38): do_action('get_header', NULL, Array)
#15 /Users/fauzan/Sites/localhost/testing/elementor/wp-content/themes/hello-elementor/index.php(15): get_header()
#16 /Users/fauzan/Sites/localhost/testing/elementor/wp-includes/template-loader.php(106): include('/Users/fauzan...')
#17 /Users/fauzan/Sites/localhost/testing/elementor/wp-blog-header.php(19): require_once('/Users/fauzan...')
#18 /Users/fauzan/Sites/localhost/testing/elementor/index.php(17): require('/Users/fauzan...')
#19 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @FauzanEdris! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello @FauzanEdris, and @ismailcseku,

Thank you for being so patient! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We cannot reproduce the issue reported in any way. 
* We tested with the latest version of Elementor (v3.8.1), and the Hello Elementor theme (v2.6.1), without being able to reproduce the issue.
* All experiments were tested active and inactive individually and all at once, we couldn't reproduce the issue either.
* From the template provided as well as a newly created template, the CSS was obeying the specificity.

### ✅ What you can do to solve your issue:
* Regenerate Elementors CSS & Files
* Clear your browser cache.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
