### ISSUE TITLE
⛔ 🐞 Bug Report: SoundCloud widget is not working anymore - Elementor v3.8

### ISSUE THREAD

**Issue by micmeistudio** [elementor/elementor#20260]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor Soundcloud widget stop working on the last 2 versions updates of Elementor. Can't embed the soundcloud player anymore and doesn't show any error. Example: https://www.usmrecordings.com/againstme/ the soundcloud player was used to be showed under artists social media links.

![soundcloud-widget-issue](https://user-images.githubusercontent.com/58848466/199665627-efecd226-87e8-45de-b4ef-c4ee158651b0.png)

Thank you!

### Steps to reproduce

Just place the soundcloud widget on a page and insert a soundcloud link that you would like to embed. 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.36
	PHP Version: 8.1.12
	PHP Memory Limit: 384M
	PHP Max Input Vars: 5120
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://www.usmrecordings.com
	Home URL: https://www.usmrecordings.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 384M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: micmei85@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0

== Active Plugins ==
	Akismet Anti-Spam
		Version: 5.0.1
		Author: Automattic

	Copy & Delete Posts
		Version: 1.3.4
		Author: Copy Delete Posts

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com

	Jetpack
		Version: 11.5.1
		Author: Automattic

	Jetpack Boost
		Version: 1.5.3
		Author: Automattic - Website Speed and Performance team

	Maintenance
		Version: 4.06
		Author: WebFactory Ltd

	Site Kit by Google
		Version: 1.86.0
		Author: Google

	Termly | GDPR/CCPA Cookie Consent Banner
		Version: 3.0.3
		Author: Termly

	Yoast SEO
		Version: 19.9
		Author: Team Yoast

== Elements Usage ==
	
	page : 1
		button : 2
		heading : 23
		spacer : 5
	section : 0
		button : 8
		divider : 2
		heading : 17
		icon-list : 1
		social-icons : 4
		text-editor : 2
	wp-post : 22
		audio : 22
		button : 17
		heading : 5
		social-icons : 5
		text-editor : 22
	wp-page : 6
		button : 9
		divider : 8
		heading : 32
		image : 1
		social-icons : 3
		spacer : 7
		text-editor : 21
		video : 2

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
JS: showing 3 of 3JS: 2022-09-04 14:22:44 [error X 4][https://www.usmrecordings.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.4:3:767248] this.store.find(...) is undefined 
JS: 2022-09-04 14:27:05 [error X 1][https://www.usmrecordings.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.4:3:286973] T.params.args.data is undefined 
JS: 2022-09-16 14:09:24 [error X 4][https://www.usmrecordings.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.4:3:586746] this.container is undefined 

PHP: showing 4 of 4PHP: 2022-09-04 15:41:53 [notice X 3][/var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/core/database/query-builder.php(1153): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/modules/notes/database/query/note-query-builder.php(520): ElementorPro\Core\Database\Query_Builder -> update()
',
)]
PHP: 2022-10-03 19:04:05 [notice X 398][/var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(236): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2022-10-20 05:45:20 [notice X 9][/var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-31 11:24:14 [notice X 77][/var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/plugin.php(153): class type include()array (
  0 => '/var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /var/www/vhosts/lefkoharti.gr/usmrecordings.com/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]

Log: showing 20 of 352022-09-21 07:15:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-23 13:19:37 [info] elementor::elementor_updater Started 
2022-09-23 13:19:37 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-23 13:19:37 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-23 13:19:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-10-03 19:04:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-03 19:04:01 [info] elementor::elementor_updater Started 
2022-10-03 19:04:01 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-03 19:04:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-03 19:04:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-03 19:04:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-31 11:23:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-10-31 11:23:40 [info] elementor-pro::elementor_pro_updater Started 
2022-10-31 11:23:40 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-31 11:23:40 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-31 11:23:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-10-31 11:25:43 [info] elementor::elementor_updater Started 
2022-10-31 11:25:43 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-31 11:25:43 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-31 11:25:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @micmeistudio,

Thank you for reaching out, and most importantly for your patience! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We can add the SoundCloud widget consistently without any issues.
* While reviewing your page, we cannot see the widget inside the section you mentioned. That section appears to be empty.
* We cannot reproduce your issue using the latest versions of Elementor (v3.8.1), and Elementor Pro (v3.8.1), using the Hello Elementor theme (v2.6.1) and no other plugin. This leads us to conclude your issue is more related to a 3rd party plugin conflict or server cache issues.

### ✅ What you can do to solve your issue:
* Try deactivating other plugins and leaving only Elementor and Elementor Pro installed.
* Try adding the widget again.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
