### ISSUE TITLE
✅ 🐞 Bug Report: Editing content created with the default editor in Elementor, generates a Section with a Text Editor inside instead of a Container when the Flexbox Container experiment is active

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20282]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor team!

I was checking the WooCommerce default pages when I noticed a bug...
If you edit the default WooCommerce pages such as cart and checkout, you will see that the shortcodes of these pages have been added inside a section. **This is while the flexbox container feature is active.**

### Steps to reproduce

Edit one of the default WooCommerce pages with Elementor. After loading the editor, you will see that its shortcode has been added in a section.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-localhost-01-11-2022.txt](https://github.com/elementor/elementor/files/9944150/system-info-localhost-01-11-2022.txt)

**Comment by nicholaszein** [comment]
Hello @79ho3ein! 

Thank you for submitting your issue! 🙏 

I can reproduce your issue, and it's not only with WooCommerce shortcodes!

#### Description

Any content converted to be edited with Elementor when the Flexbox Container experiment is active will generate a Section with a Text Editor widget inside. 

#### Steps to Replicate

1. With the **Flexbox Container experiment** active, create a post or page with any content inside and publish it.
2. Click the **Edit with Elementor** blue button at the top of the editing page.
3. After the Elementor Editor is loaded, see that a Section with a Text Editor widget inside is automatically added with the content you've created with the default WordPress editor.

#### Expected Behavior

The expected behavior would be to see a Container with the Text Editor widget inside instead.

Good catch! 👏 

I'll let the team know this workflow needs to be updated when the Flexbox Container experiment is active! 😉 

Best regards

**Comment by 79ho3ein** [comment]
Hi @nicholaszein , Great. Good luck.

cheers🥂

**Comment by 79ho3ein** [comment]
Hi @nicholaszein,

Is there any news about this matter being resolved? (Just to remind)

**Comment by nicholaszein** [comment]
Hey @79ho3ein!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v3.16! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
