### ISSUE TITLE
⛔ 🐞 Bug Report: Code Highlight - Not showing proper output 

### ISSUE THREAD

**Issue by codersbugs** [elementor/elementor#20320]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am using Elementor Pro Code Highlight , my code contains multiple && , || conditions in single line .
Example : 

if(j+i>=8 && j+i<=12 && i>=4 || j-i>=0 && j-i<=4 && i<=4)   &#38

In this case I am code not showing as expected it shows like  -

 if(j+i>=8 &&#38 j+i<=12 &&#38 i>=4 || j-i>=0 &&#38 j-i<=4 &&#38 i<=4)

Its working for || symbol but not  in case of multiple && conditions .

Please do the needful and fix it.

### Steps to reproduce

1 - add following code in Code Highlight 
public static void main(String[] args) {
        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {
                if(j+i>=8 && j+i<=12 && i>=4 || j-i>=0 && j-i<=4 && i<=4)
                    System.out.print("*");
                else 
                     System.out.print(" ");
            }
            System.out.println();
        }
    }

2 - Select any language C++ or Java 

3 - Check the output ( not showing proper output for Symbol && )

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nicholaszein** [comment]
Hello @codersbugs,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We cannot reproduce the issue you've reported. The code appears correctly in all cases:

**Backend C++:**
![image](https://user-images.githubusercontent.com/113993460/201581853-66f2470e-de39-46d0-98d6-e0451e80e660.png)

**Frontend C++:**
![image](https://user-images.githubusercontent.com/113993460/201581887-8ca5f07a-548f-42b4-85f9-f2cfb6827c02.png)

**Backend Java:**
![image](https://user-images.githubusercontent.com/113993460/201582025-24deb16f-bc36-401e-b489-82c8593f4011.png)

**Frontend Java:**
![image](https://user-images.githubusercontent.com/113993460/201582080-3033d94c-2466-462f-8241-e58e2e010e82.png)

### ❌ While reviewing your report, we noticed it was missing some key pieces of information.


- **Isolating the Problem:** You need to make sure this only happens while using Elementor, Elementor Pro, and the Hello Elementor theme. We do not provide support for 3rd-party themes and plugins.
- **System info:** You did not provide any information about your [System Info](https://elementor.com/help/systems-info/) as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).


### ✅ What you can do to solve your issue:
* Most likely your problem is related to either cache or server encoding.
* Clear your cache and test in another browser
* Check if your server is using the correct encoding

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
