### ISSUE TITLE
⛔ 🐞 Bug Report: Acf Field not working on blog list widget

### ISSUE THREAD

**Issue by abdul891** [elementor/elementor#20338]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello

I am using company name custom filed for my blog. When I am using this acf field on dynamic tag of blog widget unfortunately not working .
How to fix this isssue.

Elemento pro version -  3.8.0

![Screenshot (674)](https://user-images.githubusercontent.com/78399312/200845565-0ebead35-86d8-4e5d-8ec4-3ad15bb8f423.png)

### Steps to reproduce

Elemento pro version -  3.8.0

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Elemento pro version -  3.8.0

**Comment by nicholaszein** [comment]
Hello @abdul891,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* The Posts widget does not support custom fields, especially inside the Separator tag.

### ✅ What you can do to solve your issue:
* You can try to use the new [Loop Builder](https://elementor.com/blog/introducing-the-loop-builder/) to create your own Posts template and add your custom fields.

Learn more about the Loop Builder:

- [What is the Loop Grid?](https://elementor.com/help/loop-grid/)
- [How do I build a Loop Grid?](https://elementor.com/help/how-do-i-build-a-loop-grid/)
- [How do I customize the layout of a loop?](https://elementor.com/help/customize-layout-loop/)
- [Building a query with the loop grid](https://elementor.com/help/building-query-loop-grid/)
- [How do I paginate my loop?](https://elementor.com/help/paginate-loop/)
- [How do I build a loop from an existing template?](https://elementor.com/help/build-a-loop-existing-template/)


### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
