### ISSUE TITLE
❌ Invalid Issue: Error:Preview Could Not Be Loaded only in chrome and Edge

### ISSUE THREAD

**Issue by yxw-jp** [elementor/elementor#20376]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Error:Preview Could Not Be Loaded has happend only in chrome and Edge but Firefox is work fine.
When I edit megamenu content,I get three javascript error in DevTools.
frontend.min.js?ver=3.7.8:2 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at 3308 (frontend.min.js?ver=3.7.8:2:36746)
    at __webpack_require__ (webpack.runtime.min.js?ver=3.7.8:2:153)
    at 5654 (frontend.min.js?ver=3.7.8:2:3764)
    at __webpack_require__ (webpack.runtime.min.js?ver=3.7.8:2:153)
    at frontend.min.js?ver=3.7.8:2:40448
    at __webpack_require__.O (webpack.runtime.min.js?ver=3.7.8:2:499)
    at frontend.min.js?ver=3.7.8:2:40468
    at webpackJsonpCallback (webpack.runtime.min.js?ver=3.7.8:2:4611)
    at frontend.min.js?ver=3.7.8:2:61
3308 @ frontend.min.js?ver=3.7.8:2
__webpack_require__ @ webpack.runtime.min.js?ver=3.7.8:2
5654 @ frontend.min.js?ver=3.7.8:2
__webpack_require__ @ webpack.runtime.min.js?ver=3.7.8:2
(anonymous) @ frontend.min.js?ver=3.7.8:2
__webpack_require__.O @ webpack.runtime.min.js?ver=3.7.8:2
(anonymous) @ frontend.min.js?ver=3.7.8:2
webpackJsonpCallback @ webpack.runtime.min.js?ver=3.7.8:2
(anonymous) @ frontend.min.js?ver=3.7.8:2
preview.min.js?ver=3.7.7:2 Uncaught ReferenceError: elementorFrontend is not defined
    at new Preview (preview.min.js?ver=3.7.7:2:39196)
    at preview.min.js?ver=3.7.7:2:40454
    at preview.min.js?ver=3.7.7:2:40461
    at preview.min.js?ver=3.7.7:2:40465
Preview @ preview.min.js?ver=3.7.7:2
(anonymous) @ preview.min.js?ver=3.7.7:2
(anonymous) @ preview.min.js?ver=3.7.7:2
(anonymous) @ preview.min.js?ver=3.7.7:2
lottie.init.js?ver=2.7.3:1 Uncaught ReferenceError: elementorFrontend is not defined
    at lottie.init.js?ver=2.7.3:1:1110
(anonymous) @ lottie.init.js?ver=2.7.3:1
load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,jquery-migrate,regenerator-runtime,wp-polyfill,underscore,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,wp-&load%5Bchunk_1%5D=hooks&ver=5.9.5:5 JQMIGRATE: Migrate is installed, version 3.3.2
00

### Steps to reproduce

appearance->menu->some menu->[mega menu]->[EDIT MEGAMENU CONTENT]
<img width="958" alt="javascript error" src="https://user-images.githubusercontent.com/118003211/201378948-5f18bea0-b6b1-43ea-bc91-84563e4f4dad.png">

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<html>
<body>

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | MySQL Community Server (GPL) v5.7.40 |  
PHP Version: | 8.0.25 |  
PHP Memory Limit: | 128M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 150M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

</body>
</html>

<html>
<body>

Active Plugins |   |  
-- | -- | --
All-in-One WP Migration - 7.67 | By ServMask |  
BJ Lazy Load - 1.0.9 | By Bjørn Johansen, Aron Tornberg, angrycreative |  
Classic Editor - 1.6.2 | By WordPress Contributors |  
Classic Widgets - 0.3 | By WordPress Contributors |  
Code Snippets - 3.2.1 | By Code Snippets Pro |  
Custom Field Template - 2.5.6 | By Hiroaki Miyashita |  
Disable Right Click For WP - 1.1.6 | By Aftab Muni |  
Elementor - 3.7.8 | By Elementor.com |  
Elementor Pro - 3.7.7 | By Elementor.com |  
ElementsKit Lite - 2.7.3 | By Wpmet |  
Google XML Sitemaps - 4.1.5 | By Auctollo |  
Gravity Forms - 2.6.8 | By Gravity Forms |  
MetaSlider - 3.27.13 | By MetaSlider |  
Posts Viewed Recently Custom - 1.3.2 | By AS Tech Solutions |  
Redirection - 5.3.5 | By John Godley |  
Replace Protected Password - 1.0.3 | By Ko Takagi |  
WP All Export Pro - 1.7.7 | By Soflyy |  
WP Custom Fields Search - 1.2.34 | By Don Benjamin |  
WP Extended Search - 2.1.1 | By 5um17 |  
WP Multibyte Patch - 2.9 | By Seisuke Kuraishi

</body>
</html>Active Plugins		
[All-in-One WP Migration](https://servmask.com/) - 7.67	By [ServMask](https://servmask.com/)	
[BJ Lazy Load](https://wordpress.org/plugins/bj-lazy-load/) - 1.0.9	By [Bjørn Johansen, Aron Tornberg, angrycreative](https://angrycreative.se/)	
[Classic Editor](https://wordpress.org/plugins/classic-editor/) - 1.6.2	By [WordPress Contributors](https://github.com/WordPress/classic-editor/)	
[Classic Widgets](https://wordpress.org/plugins/classic-widgets/) - 0.3	By [WordPress Contributors](https://github.com/WordPress/classic-widgets/)	
[Code Snippets](https://codesnippets.pro/) - 3.2.1	By [Code Snippets Pro](https://codesnippets.pro/)	
[Custom Field Template](https://wpgogo.com/development/custom-field-template.html) - 2.5.6	By [Hiroaki Miyashita](https://wpgogo.com/)	
Disable Right Click For WP - 1.1.6	By [Aftab Muni](https://www.serialupdates.me/)	
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash) - 3.7.8	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=author-uri&utm_medium=wp-dash)	
[Elementor Pro](https://go.elementor.com/wp-dash-wp-plugins-author-uri/) - 3.7.7	By [Elementor.com](https://go.elementor.com/wp-dash-wp-plugins-author-uri/)	
[ElementsKit Lite](https://products.wpmet.com/elementskit) - 2.7.3	By [Wpmet](https://wpmet.com/)	
[Google XML Sitemaps](https://auctollo.com/) - 4.1.5	By [Auctollo](https://acutollo.com/)	
[Gravity Forms](https://gravityforms.com/) - 2.6.8	By [Gravity Forms](https://gravityforms.com/)	
[MetaSlider](https://www.metaslider.com/) - 3.27.13	By [MetaSlider](https://www.metaslider.com/)	
[Posts Viewed Recently Custom](https://www.astech.solutions/wordpress-javascript-jquery-plugins/posts-viewed-recently/) - 1.3.2	By [AS Tech Solutions](https://www.astech.solutions/)	
[Redirection](https://redirection.me/) - 5.3.5	By John Godley	
[Replace Protected Password](https://github.com/ko31/replace-protected-password) - 1.0.3	By [Ko Takagi](http://go-sign.info/)	
[WP All Export Pro](http://www.wpallimport.com/export/) - 1.7.7	By Soflyy	
[WP Custom Fields Search](http://www.webhammer.co.uk/wp_custom_fields_search) - 1.2.34	By [Don Benjamin](http://www.webhammer.co.uk/)	
[WP Extended Search](https://www.secretsofgeeks.com/2014/09/wordpress-search-tags-and-categories.html) - 2.1.1	By [5um17](https://www.secretsofgeeks.com/)	
[WP Multibyte Patch](https://eastcoder.com/code/wp-multibyte-patch/) - 2.9	By [Seisuke Kuraishi](https://tinybit.co.jp/)

**Comment by nicholaszein** [comment]
Hello @yxw-jp,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
Elementor does not have a Mega-Menu feature, therefore whatever add-on for Elementor you might be using, is probably the reason why you're experiencing the issue you're reporting.

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

### ✅ What you can do to solve your issue:

⚠️  Backup your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2.  Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3.  Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
