### ISSUE TITLE
⛔ 🐞 Bug Report: Theme Builder - Choose Template Type dialog shows both Section and Container options if the Container experiment is active

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20391]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

It seems that there is a simple bug in the theme builder.
The bug is that if we activate the container, the section option is still displayed in the theme builder.But if we disable the container, the container option will be removed from the theme builder.

### Steps to reproduce

**1- When the container is active**

![Screenshot 1](https://user-images.githubusercontent.com/88034902/201541400-929bf380-e1c6-4abb-8c70-115287ce9abf.png)

**2- When the container is inactive**

![Screenshot (896)](https://user-images.githubusercontent.com/88034902/201541562-b7a5027d-f492-4642-892a-eb2d4a399c84.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-localhost-26-10-2022.txt](https://github.com/elementor/elementor/files/9998073/system-info-localhost-26-10-2022.txt)

**Comment by nicholaszein** [comment]
Hello @Michaelgimii ,

Thank you again for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
Since for now Sections and Containers coexist (a website can still have Sections even if they can't be added anymore), removing this option would make it impossible to <ins>**save sections as templates**</ins>. We don't want to remove this option for the time being.

Kind regards
