### ISSUE TITLE
❌ Invalid Issue: elementor pro makes header and footer media disappear

### ISSUE THREAD

**Issue by yelicios** [elementor/elementor#20418]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I was using basic elementor plan than decided to upgrate to pro after activating pro plugin, I realized my footer and header media disappears. I re updated wordpress and they got back but after a minute media disappears again. I tried to solve this issue with the support team of theme I use but its clear that error is not because of the theme  I use because if I use only basic elementor, nothing gets broken. Please find a solution for this

### Steps to reproduce

1) activating elementro pro causes the problem. If ı disable it , everything gets normal

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-www.euromet.com.tr-15-11-2022.txt](https://github.com/elementor/elementor/files/10016025/system-info-www.euromet.com.tr-15-11-2022.txt)

**Comment by nicholaszein** [comment]
Hello @yelicios,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We could not reproduce your issue while testing with the latest versions of Elementor (v3.8.1), Elementor Pro (v3.8.1), and the Hello Elementor theme (v2.6.1).
* Moreover your issue does not describe appropriate steps to reproduce it, leading us to conclude the issue might be either related to cache, your theme, or perhaps even a change in the Document Layout or the use of an Elementor Header and Footer.

### ✅ What you can do to solve your issue:
* You need to troubleshoot your website or contact Elementor Support to help find the real cause of your issue.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should NOT BE USED FOR SUPPORT.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
