### ISSUE TITLE
⛔ 🐞 Bug Report: All Categories not Showing in Term Query Field for Posts Widget

### ISSUE THREAD

**Issue by MathewBardwell** [elementor/elementor#20449]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the Posts Widget, when you try to add a category to the Terms query and start typing "Cate..." not all the categories will show in the list. If you type the entire word "Categories" no categories will show up. You have to type the actual name of the category for it to show in the terms list.

### Steps to reproduce

1. Add the Posts Widget to a page.
2. Go to the Query section of the widget.
3. Click on "Include By"
4. Check the "Term" box
5. Try to type "Cate..." to see if all the post categories show up.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.36
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.8
	Site URL: https://sfwm24.sharefaithwebsites.net/~s27lezeu7a5xlsqm/Ez1UGGzM83
	Home URL: https://sfwm24.sharefaithwebsites.net/~s27lezeu7a5xlsqm/Ez1UGGzM83
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: mathew@sharefaith.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Duplicate Page
		Version: 4.4.9
		Author: mndpsingh287

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.1
		Author: Elementor.com

	FMS Forms Plugin
		Version: 1.2.1
		Author: Sharefaith

	Galleries by Angie Makes
		Version: 1.67
		Author: Chris Baldelomar

	Modern Events Calendar Lite
		Version: 6.7.2
		Author: Webnus

	Prayer Cloud
		Version: 1.1.6
		Author: Sharefaith

	RefTagger
		Version: 2.4.4
		Author: Logos Bible Software

	Sermon Cloud
		Version: 1.5.1
		Author: Sharefaith

	Sharefaith Church App
		Version: 2.6.14
		Author: Sharefaith

	Sharefaith Media Library Plugin
		Version: 1.3.3
		Author: Sharefaith

	Sharefaith Templates for Elementor
		Version: 1.4.4
		Author: Sharefaith

	Style Kits for Elementor
		Version: 1.9.5
		Author: AnalogWP

	W3 Total Cache
		Version: 2.2.7
		Author: BoldGrid

	WP Statistics
		Version: 13.2.7
		Author: VeronaLabs

	Yoast SEO
		Version: 17.1
		Author: Team Yoast

== Must-Use Plugins ==
	Sharefaith
		Version: 2.4.7
		Author: Sharefaith

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 402022-11-02 16:39:50 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-11-02 16:39:50 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-11-02 16:39:50 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2022-11-02 16:39:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.8.0',
)]
2022-11-02 16:39:50 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2022-11-02 16:39:50 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2022-11-02 16:39:50 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2022-11-02 16:39:50 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-11-02 16:39:50 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-11-02 16:39:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.2',
  'to' => '3.8.0',
)]
2022-11-18 23:46:07 [info] elementor-pro::elementor_pro_updater Started 
2022-11-18 23:46:07 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-18 23:46:07 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-18 23:46:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-18 23:46:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-18 23:46:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-18 23:46:21 [info] elementor::elementor_updater Started 
2022-11-18 23:46:21 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-18 23:46:21 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-18 23:46:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]

PHP: showing 2 of 2PHP: 2022-11-02 15:57:29 [notice X 2][/home/s27lezeu7a5xlsqm/public_html/Ez1UGGzM83/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-02 16:39:57 [notice X 26][/home/s27lezeu7a5xlsqm/public_html/Ez1UGGzM83/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Sharefaith Templates for Elementor: Compatibility not specified
	Style Kits for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @MathewBardwell,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* This is not a bug. You need to type the name of the term. Elementor won't show an entire list of all terms related to a taxonomy for performance reasons.

### ✅ What you can do to solve your issue:
* Always start typing the name of the term you want to query by.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
