### ISSUE TITLE
❓ Question: Two questions about the structure of html codes in Elementor.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20458]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor team!

I was checking the html codes when two things caught my attention.

1- When we add a container to the page, why are **two divs** added inside the page? In bricks builder, every container or section we add to the page, only one div will be added. But in Elementor 2.

2- Why does it have 3 div tags when we add an image? Isn't this a non-standard structure?

**Adding an image inside the container in bricks builder :**

![scA](https://user-images.githubusercontent.com/88034902/202899223-d29d920b-41a6-4440-a7e4-a308d42d05be.png)

**Adding an image inside the container in elementor :**

![scB](https://user-images.githubusercontent.com/88034902/202899230-b166b90b-f19d-4643-b518-8a14daed9407.png)

### Steps to reproduce

Just check the structure of html codes in all widgets. There are countless div tags that don't really need to exist. This is what makes sites built with elementor have a lot of dom elements.

I hope you have a program to rewrite elementor codes.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello @Michaelgimii!

Thanks for submitting your question!

There are a few reasons why our widgets have the `.elementor-widget-container` div inside. I'll try to explain a few of them:

1. With this _inner container_ we are able to implement multiple features with more flexibility:
   - Margin & Padding
   - Motion Effects
   - Background styles
   - Border styles
   - Transforms
   - Masks
   - (Essentially every feature inside the Advanced tab)
 2. Backward Compatibility: When Elementor was created, the current state of CSS 3 implementation by browsers was very limited, which forced us to implement an _inner container_ that would allow us to provide more control over our elements. For now, this won't be changed because of that.
 3. There is no issue related to "standard structure" by adding wrappers to image tags. This again allows users to have more control over image dimensions and positions.

I hope this clarifies your questions.

Take care!
