### ISSUE TITLE
⛔ 🐞 Bug Report: Nav menu isn't shown inside container

### ISSUE THREAD

**Issue by heikkiwaan** [elementor/elementor#20472]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The problem is that i can't see the menu on front end, i can see it on editor.

### Steps to reproduce

Go to create a header (templates -> theme builder -> header -> add)
here's what i did:

1) add a container by clicking on the red circle with a + sign in the middle of the screen.
2) add the nav menu moving it there from the items to its place normally.

Publish: visibility entire site
and there it is, not visible.

I tried it with Elementor and Elementor PRO latest stable versions, and also with the beta
stables: elementor 3.8.1, PRO 3.8.2
second test: Beta: elementor 3.10.0-dev1 , PRO 3.9.0-beta2

Not working even if i remade it with the beta/dev versions.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.38
	PHP Version: 7.4.33
	PHP Memory Limit: 232M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 42M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://vuokralle.3.14.fi
	Home URL: https://vuokralle.3.14.fi
	WP Multisite: No
	Max Upload Size: 41 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Helsinki
	Admin Email: heikki@bittituotanto.fi
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fi
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.10.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0-beta2
		Author: Elementor.com

== Elements Usage ==
	
	footer : 1
		container : 4
		heading : 1
		text-editor : 2
	header : 2
		container : 2
		nav-menu : 2
		theme-site-title : 1
	wp-post : 0
		container : 1
		gallery : 2
		text-editor : 2
	wp-page : 1
		container : 1
		loop-grid : 1
	single-post : 1
		container : 5
		form : 1
		google_maps : 1
		heading : 3
		text-editor : 3
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	loop-item : 1
		button : 1
		container : 4
		text-editor : 3
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Active by default
	Save as Default: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 3 of 3PHP: 2022-11-21 12:36:25 [notice X 9][/home/neljatois/vuokralle.3.14.fi/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 15:34:03 [notice X 9][/home/neljatois/vuokralle.3.14.fi/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 16:04:39 [notice X 7][/home/neljatois/vuokralle.3.14.fi/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/neljatois/vuokralle.3.14.fi/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/neljatois/vuokralle.3.14.fi/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/neljatois/vuokralle.3.14.fi/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/neljatois/vuokralle.3.14.fi/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

JS: showing 2 of 2JS: 2022-11-21 12:38:38 [error X 6][https://vuokralle.3.14.fi/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-21 15:38:08 [error X 1][https://vuokralle.3.14.fi/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:654354] Cannot read properties of undefined (reading \'get\') 

Log: showing 10 of 102022-11-21 19:49:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.10.0-dev1',
)]
2022-11-21 19:49:14 [info] elementor-pro::elementor_pro_updater Started 
2022-11-21 19:49:14 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-21 19:49:14 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-21 19:49:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0-beta2',
)]
2022-11-21 19:49:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0-beta2',
)]
2022-11-21 19:49:14 [info] elementor::elementor_updater Started 
2022-11-21 19:49:14 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-21 19:49:14 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-21 19:49:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.10.0-dev1',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by heikkiwaan** [comment]
The menu isn't even visible in the returned source code of the page.

**Comment by nicholaszein** [comment]
Hello @heikkiwaan,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We cannot reproduce your issue with the latest version of Elementor (v3.8.1) and Elementor Pro (v3.8.2) using the latest version of the Hello Elementor theme (v2.6.1).

### ✅ What you can do to solve your issue:
* Make sure you actually have a menu created in your Dashboard > Appearance > Menus, and that it was selected in the Nav Menu settings as explained in the [Nav Menu widget documentation](https://elementor.com/help/nav-menu-widget-pro/).

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
