### ISSUE TITLE
❌ 🐞 Bug Report: Elementor Creating Error Log File (nav-menu.php)

### ISSUE THREAD

**Issue by dijitalgezgin** [elementor/elementor#20494]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

Elementor has been creating an error_log file for a long time.  I waited for a long time for the problem to be fixed, but it has not. The error source here:
`[22-Nov-2022 14:15:46 UTC] PHP Notice:  Trying to access array offset on value of type null in /home/public_html/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php on line 1445
[22-Nov-2022 14:15:46 UTC] PHP Notice:  Trying to access array offset on value of type null in /home/public_html/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php on line 1458
[22-Nov-2022 14:15:46 UTC] PHP Notice:  Trying to access array offset on value of type null in /home/public_html/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php on line 1469
[22-Nov-2022 14:15:46 UTC] PHP Notice:  Trying to access array offset on value of type null in /home/public_html/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php on line 1482`

Can you help me?

Kind regards.

### Steps to reproduce

IDK.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.36
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://gloriathemes.com
	Home URL: https://gloriathemes.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Istanbul
	Admin Email: info@gloriathemes.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 5.0.1
		Author: Automattic

	BetterDocs
		Version: 2.2.1
		Author: WPDeveloper

	BetterDocs Pro
		Version: 2.2.1
		Author: WPDeveloper

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.1
		Author: Elementor.com

	Google Listings and Ads
		Version: 2.2.1
		Author: WooCommerce

	MC4WP: Mailchimp for WordPress
		Version: 4.8.11
		Author: ibericode

	PayTR Virtual POS WooCommerce - iFrame API
		Version: 2.0.4
		Author: PayTR Ödeme ve Elektronik Para Kuruluşu A.Ş.

	Pretty Links
		Version: 3.2.7
		Author: Pretty Links

	ShortPixel Image Optimizer
		Version: 5.1.3
		Author: ShortPixel

	Simple Local Avatars
		Version: 2.6.0
		Author: Jake Goldman, 10up

	WooCommerce
		Version: 7.1.0
		Author: Automattic

	WP Rocket
		Version: 3.12.3
		Author: WP Media

	Yoast SEO
		Version: 19.10
		Author: Team Yoast

== Elements Usage ==
	
	archive : 3
		archive-posts : 1
		gloria-showcase-widget : 1
		gloria-themes-widget : 1
		heading : 3
		text-editor : 4
	footer : 1
		button : 3
		gloria-button-widget : 1
		heading : 7
		html : 1
		icon-box : 1
		nav-menu : 3
		shortcode : 1
		social-icons : 1
		text-editor : 5
	header : 3
		button : 3
		image : 1
		nav-menu : 3
		text-editor : 2
		theme-site-logo : 2
	section : 2
		gloria-button-widget : 1
		heading : 3
		icon-list : 1
		text-editor : 3
	widget : 0
		counter : 1
		heading : 1
		text-editor : 1
	wp-post : 0
		counter : 6
		gloria-browsers-widget : 21
		gloria-button-widget : 16
		gloria-read-more-less-widget : 6
		gloria-testimonials-widget : 6
		gloria-theme-features-widget : 6
		heading : 75
		image : 30
		text-editor : 63
	wp-page : 13
		accordion : 1
		betterdocs-search-form : 1
		button : 2
		counter : 8
		divider : 7
		form : 3
		gloria-button-widget : 14
		gloria-docs-box-widget : 1
		gloria-hero-slider-widget : 1
		gloria-read-more-less-widget : 1
		gloria-service-box-widget : 4
		gloria-testimonials-widget : 1
		gloria-themes-widget : 2
		heading : 46
		html : 2
		icon-list : 9
		image : 7
		posts : 2
		shortcode : 3
		sitemap : 1
		text-editor : 52
	single-post : 3
		author-box : 1
		button : 1
		divider : 2
		heading : 2
		post-info : 3
		share-buttons : 1
		text-editor : 1
		theme-post-content : 2
		theme-post-featured-image : 2
		theme-post-title : 2
	error-404 : 1
		gloria-button-widget : 1
		html : 1
		text-editor : 1

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Inactive by default
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
PHP: showing 1 of 1PHP: 2022-11-22 03:50:23 [notice X 307][/home/gloriath/public_html/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1482] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @dijitalgezgin,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* This notice normally appears for any menu implementation on WordPress (not Elementor) when you have trashed or deleted a post, page, or archive page from your website, but the link is still in your menu.

### ✅ What you can do to solve your issue:
* Check your menus and remove any item with an "**_invalid_**" warning

![image](https://user-images.githubusercontent.com/113993460/203417214-544ea790-a091-4aca-a555-77ed057587a9.png)

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
