### ISSUE TITLE
⛔ 🐞 Bug Report: Can't save post if it contains the text "include:"

### ISSUE THREAD

**Issue by scole01** [elementor/elementor#20507]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Can't save post if a text editor contains the text "include:"

### Steps to reproduce

1) Create a new post, add a text editor and try to add content containing "include:"

Thats include followed by a colon.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.7.37
	PHP Version: 7.4.33
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: Australia/Sydney
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Async JavaScript
		Version: 2.21.08.31
		Author: Frank Goossens (futtta)

	Autoptimize
		Version: 3.1.3
		Author: Frank Goossens (futtta)

	Contact Form 7
		Version: 5.6.4
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.2
		Author: Elementor.com

	Enable Media Replace
		Version: 4.0.1
		Author: ShortPixel

	Flamingo
		Version: 2.3
		Author: Takayuki Miyoshi

	Honeypot for Contact Form 7
		Version: 2.1.1
		Author: Nocean

	Lazy Load - Optimize Images
		Version: 2.3.6
		Author: WP Rocket

	Login Logo
		Version: 0.10.2
		Author: Mark Jaquith

	Really Simple SSL
		Version: 6.0.11
		Author: Really Simple Plugins

	Redirection
		Version: 5.3.5
		Author: John Godley

	reSmush.it Image Optimizer
		Version: 0.4.11
		Author: reSmush.it

	Spotlight - Social Media Feeds
		Version: 1.4.1
		Author: RebelCode

	UpdraftPlus - Backup/Restore
		Version: 1.22.23
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.7.1
		Author: Wordfence

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 19.10
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @scole01,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* I've followed your steps and I could create a post without any issues, in multiple ways.
* You seem to be running a lot of optimization plugins (cache), redirection plugins, and other plugins that could be modifying your output, or preventing you (Wordfence) from publishing your posts, probably because of some script.
* You didn't follow the Isolation instructions to properly test your problem before posting.

https://user-images.githubusercontent.com/113993460/203830731-67c01cfd-1831-4580-b5e0-0f4fe6bfc76a.mp4

### ✅ What you can do to solve your issue:
* Check if the text editor is not getting any script injection, make sure to switch to the **Text view** (as I did in the video above) to check if you don't have any script injection being added along with your text. Some browser extensions tend to do this without your knowledge.
* Do the proper troubleshooting steps outlined in [this article](https://elementor.com/help/publish-update-button-not-work/).
* Disable the performance optimization plugins and fix the SSL issues you might be having with your website by following [this Facebook post](https://www.facebook.com/groups/Elementors/permalink/2661661010626335).

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

## ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
