### ISSUE TITLE
⛔ 🐞 Bug Report: Document shows horizontal scroll when the Navigator is appended to the side in smaller viewports

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20515]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor team.

In the editor, I display the navigation on the side. But it has a serious problem. When I display the navigator on the side, the content of the editor is not fully displayed, and this causes horizontal scrolling to appear in the editor. Of course, it seems that the occurrence of this bug depends on the size of the screens, Because it is displayed without problems for some users.
I think it is better that the display of the navigation on the side does not depend on the screen size.

Please check this if possible.

### Steps to reproduce

https://user-images.githubusercontent.com/77163248/203760271-1df017b3-68f6-46a5-a2ef-e81d1aed63ee.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello @79ho3ein,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- This happens when the viewport is smaller than the desktop breakpoint. We've talked about it before in [this issue](https://github.com/elementor/elementor/issues/19841).
- This might seem like a bug, but it's actually by default. We think that if we applied zoom automatically to make the entire document fit inside the space, it would probably cause users to inadvertently increase the size of things to compensate for the zoom without knowing this would affect their final design. 

### ✅ What you can do to solve your issue:
- I gave an explanation in [this comment](https://github.com/elementor/elementor/issues/19841#issuecomment-1256376076). Please check the comment to understand how it works.
- You can actually apply zoom if you want by enabling the responsive view!

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

Kind regards

**Comment by 79ho3ein** [comment]
Hi @nicholaszein , I agree with you. thank you
