### ISSUE TITLE
🚀 Feature Request: Set Default Unit for all controls in Site Settings (width, padding, margin and...)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20549]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Currently, on each control, the usable units are displayed. This has resulted in a very outdated and clumsy ui.

![e1](https://user-images.githubusercontent.com/88034902/204274230-0a97fa4b-3aec-458d-be4d-81b7bc740d20.png)

But it would be great if we set the default units for each control (width, padding, margin and...) in advance. Therefore, there will be no need to display usable units on each control. 
**For example**, in the width field, I always use the **% unit**. For padding and margin, I use **px unit**. So I can choose my default unit in advance. After that, I just need to put the number in the desired field, such as width, so that it is automatically applied as a %. Because I have already selected the default unit of width field as percentage.

### Describe the solution you'd like

In site settings, add a new section called default units. In this section, we can set the default units for each control. **for example :**

width > %
Height (in container) > Px
column gap and row gap (in container) > px
padding > px
margin > px
typography > rem
Transition Duration > s

With this feature added, we won't even need a decrease/increment button on numeric fields. Because now we have number scrubber.

**Comment by loucasl** [comment]
What if you wanted to use a combination of different units on elements throughout the site?

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

thanks for submitting your feature request! 🙏 

As you mentioned, we are working on introducing some changes to number controls that will greatly improve usability and workflow. This will definitely change how you use these fields. So let's wait until we have them.

This issue is likely not going to be added to our roadmap, but I will reference issue #965, which is on the same subject, and perhaps we can include this in the list.

For this reason, I'm closing this issue. Feel free to continue the conversation there!

Please feel free to contact us again with other feature suggestions. 😉
