### ISSUE TITLE
❌ 🐞 Bug Report: Elementor download crashes site with PHP 8.1

### ISSUE THREAD

**Issue by portrayaloflife** [elementor/elementor#20567]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Clean WordPress install, no plugins, downloading free Elementor crashed the site when using PHP 8.1

### Steps to reproduce

Download > Site crash

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

--

**Comment by portrayaloflife** [comment]
Error below:

An error of type E_ERROR was caused in line 417 of the file /www/wp-content/plugins/elementor/includes/settings/settings.php. Error message: Uncaught Error: Class "Elementor\Modules\Promotions\Module" not found in /www/wp-content/plugins/elementor/includes/settings/settings.php:417
Stack trace:
#0 /www/wp-content/plugins/elementor/includes/plugin.php(717): Elementor\Settings->__construct()
#1 /www/wp-content/plugins/elementor/includes/plugin.php(641): Elementor\Plugin->init_components()
#2 /wordpress/wp-includes/class-wp-hook.php(308): Elementor\Plugin->init('')
#3 /wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/wp-settings.php(620): do_action('init')
#6 /www/wp-config.php(115): require_once('/wordpress/wp-s...')
#7 /wordpress/wp-config.php(5): require('/www/wp-config....')
#8 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')
#9 /wordpress/wp-admin/admin.php(34): require_once('/wordpress/wp-l...')
#10 /wordpress/wp-admin/plugins.php(10): require_once('/wordpress/wp-a...')
#11 {main}
  thrown

**Comment by nicholaszein** [comment]
Hello @portrayaloflife,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* I have no problem installing Elementor and Elementor Pro on a server with PHP 8.1. Tested multiple times, with both fresh installations and also updates.
* Your issue is most likely caused by your server timing out before installing the package, which causes Elementor to crash since not all files were installed.

### ✅ What you can do to solve your issue:
* Upload the plugin via FTP.
* Increase you server's `php_max_execution_time` and `php_max_input_time`.
* Increase your site's allocated memory to at least 128M of RAM as defined in our [Requirements](https://elementor.com/help/requirements/).

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
