### ISSUE TITLE
⛔ 🚀 Feature Request: Unlink Margin and Padding controls by default

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#20586]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor.

In border, padding and margin fields, the value link is active by default. That is, if we decrease or increase any of the values, all 4 values ​​change together. I think one rarely needs to change all 4 values ​​in the same way. So, in 99% of cases, we need to turn off the link.

### Describe the solution you'd like

In the Border, Padding and Margin fields, turn off the value link by default.

![link](https://user-images.githubusercontent.com/103376243/205030409-2304f12b-d93f-4e2a-a2d6-cbebc6edd90d.png)

**Comment by nicholaszein** [comment]
Hello @Joliamendi,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

Sorry, we are not going to accept this request because of backward compatibility. 😕 

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
