### ISSUE TITLE
⛔ 🚀 Feature Request: Improve Container layouts by providing a separate Section widget with a Container inside instead of adding the .e-con-inner

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20603]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hello

In container, codes are added much less than sections and columns. But still some additional code is generated in the container.
When we add a container, two divs are added.

- parent container
- inner container

I think if you add a new layout, the codes will be much more optimized than the current situation. Please think about the solution below.

### Describe the solution you'd like

If you add a new layout (section), everything will go very well. So, we will have two widgets in the layout section. Section and container.
![section](https://user-images.githubusercontent.com/88034902/205483397-6061b28b-64ff-464e-a8d1-bf9bba0a71f4.png)
In this case, each section or container we add will have **only one div**.

**But what is the difference between container and section?**

**section :**  The section must always be the parent of the container and its default width will be 100%.
**container :** The container forms the width of the content. We can set the container width globally in Site Settings > Layout > Content Width.

So, we always add the section first and then put the container inside it. After that, every container we add, only one div will be added. It is not really necessary to add an internal container with every container we add. There is no need to specify the width of the content in each container.

**The bricks template does this very well. Please watch the following video :**

https://user-images.githubusercontent.com/88034902/205484108-94df13ea-1528-4a99-be8b-cfc660711ad3.mp4

**but in elementor**

https://user-images.githubusercontent.com/88034902/205484370-fecb82a0-4a26-46da-b49e-643094b2cb1c.mp4

Please check this issue. This is an important issue.

**Comment by Daveden2** [comment]
The current way Elementor containers (3.8.1) work is like this: if you set the Content width to Boxed Width, it adds an inner container. 
But when the content width is set to Fullwidth, no inner container is added.

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you so much for submitting such a detailed feature request! 🙏 

#### ⛔ We see value in what you're asking, but after reviewing your request, we have decided not to add this to our roadmap. This is why:

As @Daveden2, explained, the `.e-con-inner` selector is only added if the Container's `Content Width` is set to be `Boxed`.

We have experimented with multiple ways with containers over the months since they were first introduced as alpha experiments. The final version we've settled with was the best compromise between ease of use, familiarity, accessibility, and flexibility for our implementation of the Container, and how everything fits together. 

It means both beginners and seasoned users can benefit from using containers without compromising usability and layout flexibility. This will also fit in various scenarios and our plans to expand the Container capabilities in the future. 😉 

I hope this clarifies your questions and doubts.

Please feel free to contact us again with other feature suggestions. 👍 

Best regards
