### ISSUE TITLE
🔗 ⛔ 🚀 Feature Request: Update Custom Code (Code Mirror) to support CSS variables (Related to #2219)

### ISSUE THREAD

**Issue by Mij-Strebor** [elementor/elementor#20607]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I'd like to be able to create CSS Variables in custom code. Right now the parser throws errors.
![Screenshot 2022-12-04 125649](https://user-images.githubusercontent.com/17260842/205512491-bb7ed34d-cd92-4748-bb9c-13d00775dc5b.png)

### Describe the solution you'd like

I could build a snippet with CSS variables in a :root{} and then use var in other snippets.

### Describe alternatives you've considered

For a lot of my "globals" I use Site Settings and Hello theme's styling. But within the set of snippets (Custom Code) I cannot get to them. There are other settings that are not available in Site Settings that I want to peg to a single "constant" also.  Thanks.

**Comment by nicholaszein** [comment]
Hello @Mij-Strebor,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- This is not exactly a bug. You can save your custom code with CSS variables, even if there are warnings or errors appearing in the Code editor. Here's an example:

![image](https://user-images.githubusercontent.com/113993460/205935304-6e0cc517-4dd8-47f2-9aaf-45dbf11486be.png)


### ✅ What you can do to solve your issue:
* Simply ignore the error and publish your Custom Code.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
