### ISSUE TITLE
⛔ 🐞 Bug Report: Optimized DOM Output doesn't work

### ISSUE THREAD

**Issue by mattpix** [elementor/elementor#20619]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When in Experiments section of Elementor, I try to activate Optimized DOM Output and save it, Elementor not apply the request and the experiments and still unactive.
What's the problem?

### Steps to reproduce

Go to Elementor > Settings > Experiments tab.
Select Active from the Optimized DOM Output dropdown.
Click the Save Changes button.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | Percona Server (GPL), Release 38, Revision 3692a61 v5.7.35-38 |  
PHP Version: | 8.0.25 |  
PHP Memory Limit: | 1024M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 25M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

**Comment by nicholaszein** [comment]
Hello @mattpix,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We cannot reproduce your issue using the latest version of Elementor (3.8.1).
* Your issue is most likely caused by the following:
   * 3rd party add-on conflict
   * 3rd party plugin conflict
   * Server issues
   * Cache conflict

### ⚠️ This is also more of a support question, not really something we can answer here.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
