### ISSUE TITLE
⛔ 🐞 Bug Report: Refused to display editor in a frame after update 3.8.1

### ISSUE THREAD

**Issue by IshtarStar** [elementor/elementor#20631]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating from Elementor 3.8.0 to 3.8.1, I can no longer edit created pages with Elementor. The problem persists even in safe mode. In the console of the browser is the following error.

`Refused to display 'https://marc.it/' in a frame because it set 'X-Frame-Options' to 'deny'.`

In addition, the following error occurs

`Uncaught DOMException: Blocked a frame with origin "https://marc.it" from accessing a cross-origin frame.
    at Editor.onPreviewLoaded (https://marc.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:540651)
    at Editor.onPreviewLoaded (https://marc.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:1065596)
    at HTMLIFrameElement.dispatch (https://marc.it/wp-admin/load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.1.1:4:43064)
    at y.handle (https://marc.it/wp-admin/load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.1.1:4:41048)`

The log says the following:

`
...
2022-10-31 20:14:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-12-06 17:20:43 [info] elementor::elementor_updater Started 
2022-12-06 17:20:43 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-06 17:20:43 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-06 17:20:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-12-06 17:20:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]`

PHP shows:

`PHP: 2022-12-06 17:22:22 [notice X 2][/var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]`

And JS:

`JS: 2022-12-06 16:22:40 [error X 2][https://marc.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:540650] Sandbox access violation: Blocked a frame at \"https://marc.it\" from accessing a cross-origin frame. The frame being accessed is sandboxed and lacks the \"allow-same-origin\" flag. 
JS: 2022-12-06 16:25:40 [error X 5][https://marc.it/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:540651] Blocked a frame with origin \"https://marc.it\" from accessing a cross-origin frame. `

Any advice on how to fix this problem would be greatly appreciated. So far every update has worked smoothly. Only until today unfortunately not.

Thanks in advance.
![Bildschirm­foto 2022-12-06 um 19 15 27](https://user-images.githubusercontent.com/5327617/205991285-c18b4178-72a3-4ed8-ac91-ac0f18d08a25.png)
![Bildschirm­foto 2022-12-06 um 19 15 21](https://user-images.githubusercontent.com/5327617/205991292-8c0d0c90-c2d1-4dd6-ba9d-1f08e5095765.png)

### Steps to reproduce

Update Elementar Pro from 3.8.0 to 3.8.1

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

https://pastebin.com/xfTALbwg

**Comment by nicholaszein** [comment]
Hello @IshtarStar,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* This is a problem with your server's configuration (or any Web Application Firewall you may have in place).
* This is more of a support question, not really something we can answer here.

### ✅ What you can do to solve your issue:
* Follow [this guide](https://elementor.com/help/cant-edit-with-elementor/#grayendless) to help fix your issue. Look for the **_X frame restrictions and Cross-origin issue_** bullet point.
* Read [this article](https://credoinfolit.zendesk.com/hc/en-us/articles/360038339213-X-Frame-Options-Set-to-Deny#:~:text=X%2DFrame%2DOptions%3ADENY,use%20the%20iframe%20HTML%20element.) to understand what this is.
* Read [this other more technical article](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) as well.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
