### ISSUE TITLE
❓ API Question: How to access a control's value in the register_controls function?

### ISSUE THREAD

**Issue by azkalex** [elementor/elementor#20656]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have a scenario in which I need to take the value of a control and use it in another control's 'selectors'.

In the render function, I can get the values like this:

```
$settings = $this->get_settings_for_display();

$controlValue = $settings['control_name_that_i_need_to_get_value_form'];
```

But when I try to do this outside of the render function, in the register_controls function, the code breaks.

Once I get that value, I want to do something like this:

```
$this->add_control(
    'control_name_that_i_need_to_get_value_form',
    [
        'label' => esc_html__( 'Control 1', 'my-widgets' ),
        'type' => \Elementor\Controls_Manager::SELECT,
        'options' => [
            'solid' => esc_html_x( 'Solid', 'my-widgets' ),
            'dashed' => esc_html_x( 'Dashed', 'my-widgets' ),
        ],
    ]
);
```

The control from above can output 'solid' or 'dashed'. I want to take that value and concatenate it under 'selectors' of the other control below, for example:

```
$this->add_control(
    'control_i_want_to_use_the_value_from_the_previous_control_in',
    [
        'label' => esc_html__( 'Control 2', 'my-widgets' ),
        'type' => \Elementor\Controls_Manager::SLIDER,
        'selectors' => [
            '{{WRAPPER}}' => '--my-var:' . $controlValue . ' {{SIZE}}{{UNIT}}' ,
        ],
    ]
);
```

So how can I get a control value when I'm in the register_controls function?

EDIT*

I know about the {{control_name_that_i_need_to_get_value_form.VALUE}} trick, but I specifically need to have that value in a variable so I can use it in a ternary operator concatenated inside 'selectors'. If I could use get_settings_for_display() or a similar function inside register_controls function, that would do, but it doesn't work. Is there something else I can use?

### Steps to reproduce

Nothing to reproduce.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

No need.

**Comment by nicholaszein** [comment]
Hello @azkalex,

thanks for submitting your question! 🙏 

The method you're trying to do is not supported by our API. You cannot get the value from one control inside another when you are registering controls. Try copying what we did with the Border options instead, and adapt to your needs.

See: https://github.com/elementor/elementor/blob/ef19421b7637f93d427e1691427e8e87304015a7/includes/widgets/traits/button-trait.php#L374

**Comment by rami-elementor** [comment]
@azkalex

You should not access control's value with the methods you presented here. We have a standard ways to use control data.

When you add controls to your widget, you can use the `selectors` argument to style the element:
https://developers.elementor.com/docs/editor-controls/control-select/#usage

To set different styles for normal & hover state we use control tabs:
https://developers.elementor.com/docs/editor-controls/control-tabs/#examples

We use two controls normal-box-shadow and hover-box-shadow. This way the user have the ability to set different stylings for different hover states.

To add the [blur effect](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/blur), add a new [slider control](https://developers.elementor.com/docs/editor-controls/control-slider/) to the "hover tab" with a `selectors` argument like that: `'{{WRAPPER}} .your-class' => 'filter: blur( {{SIZE}}{{UNIT}} );',`.

Next time, please create a new ticket for each issue and add code examples. Otherwise, it's hard to understand what you are trying to do.

**Comment by yasirrana** [comment]
Hi @azkalex , Did you find any solution to that problem? I am facing the same problem..
