### ISSUE TITLE
⛔ 🚀 Feature Request: Container link + button widget compatibility 

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#20652]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Currently the container cannot support child widgets or elements with anchor tags (links) due to how it renders. For some design uses I would like to make the whole container a link but still have a visual button to show the element is clickable. 

### Describe the solution you'd like

My suggestion is that if a button widget is placed inside a container that is already a link then the button is converted from 'a' tag to a 'button' or 'div' tag with the link options removed but you can still stylise the button like normal.

### Describe alternatives you've considered

The only alternative is to create a container with a heading widget inside and spend more time trying to look similar to the button global styling.

**Comment by nicholaszein** [comment]
Hello @perks98,

Thank you for submitting a feature request! 🙏 

Unfortunately, this is not on our plans right now, because this would affect backward compatibility.

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

The issue with nested links is an old issue related to how WordPress sanitizes content before displaying it. When it sees there is an HTML tag that was not closed, it tries to close it, and this causes all sorts of issues. This is not something we want to have our users experience.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
