### ISSUE TITLE
❌ Section disappeared in footer editor

### ISSUE THREAD

**Issue by JakeQZ** [elementor/elementor#20658]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The footer of the page looks like this:

![actual-footer](https://user-images.githubusercontent.com/15205088/206339277-2d8ee0b7-0523-4268-93a2-7bfd29c618c8.png)

But in the editor, the contact info section has vanished:

![no-section-in-editor](https://user-images.githubusercontent.com/15205088/206339382-9c3bdcdf-53de-4616-8e25-52ff01f0a4d4.png)

I wanted to remove the extra phone icon, but couldn't manage to.  Clicking on 'edit icon list' caused the section to reinsert itself halfway between the two paragraphs to the right.

### Steps to reproduce

Unknown.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Browser is Firefox 107.0.1 (64-bit) on Windows 10.

Server is Apache with LiteSpeed V8.0.1 Cloudlinux 1.3.

WordPress and Elementor are latest versions at time of writing.

**Comment by nicholaszein** [comment]
Hey @JakeQZ, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- **Steps to replicate:** You did not provide any way for us to try to reproduce your issue;
- **Isolating the Problem:** You need to make sure this only happens while using Elementor, Elementor Pro, and the Hello Elementor theme. We do not provide support for 3rd-party themes and plugins.
- **System info:** You did not provide any information about your [System Info](https://elementor.com/help/systems-info/) as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Without them, we simply can't help. 😕 

This is also more of a support question, not really something we can answer here. Your issue most likely is a result of a conflict with a 3rd party add-on. But since you haven't provided us with enough information, we can't know for sure.

What do know, is that this doesn't happen within our tests, so we do know this is not a bug, and it's more like a conflict issue.

Please contact Elementor Support so they can help you better.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
