### ISSUE TITLE
⛔ 🚀 Feature Request: Conditional display of font weight in Elementor editor

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20683]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team.

When we add a custom font in Elementor, if we only upload 1 or two weights for our font, in the editor, when we select our custom font, the font weight section will display all the weights.I don't think this is a logical method. Rather, **it is better that only the weights that we have uploaded are visible.**

### Describe the solution you'd like

Suppose I have uploaded a custom font with two weights (300 and 400) to my website. In the editor, when I select my custom font family, in the font weight section, only the weights that I have uploaded are visible. That is, 300 and 400. There is no reason to display weights that do not exist at all.

![font](https://user-images.githubusercontent.com/77163248/206854842-19c92cfd-851e-4562-bb83-b9463c8360d3.png)

**Comment by nicholaszein** [comment]
Hello @79ho3ein,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. Here's why:

This would add a lot of overhead to the builder, and require a whole override of the current font weight control. Imagine having a low-resources server, and having to wait to fetch which weights are available for each font. Because each font has its own different weights, it would be necessary to check each font, including Google's ones each time you select a different font. This could be done _on-the-fly_ or in one go, but this would not be a good experience for everyone.

It's not that it's impossible, but this would negatively affect the Editor's performance in low-resources environments. I hope this makes sense.

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards

**Comment by fabianenzensperger** [comment]
+1
