### ISSUE TITLE
⛔ 🚀 Feature Request: Move the Empty Cart template from the Cart widget to Site Settings > WooCommerce Pages

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20714]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor developer.

In the Cart widget, we have the Customize empty cart option and this is a very important feature. But the main challenge is that if we create the shopping cart page using other plugins like jet woobuilder, we cannot use the customize empty cart feature of the element.
So it would be great if you add this feature to Site Settings > WooCommerce > Cart.
In this case, even if we have created the cart page using a third-party plugin, we can use the elementor Customize empty cart.

### Describe the solution you'd like

add Customize empty cart feature to Site Settings > WooCommerce > Cart.

![empty cart](https://user-images.githubusercontent.com/88034902/207080842-aabe6feb-f531-4ed7-92f8-953832287ebd.png)

**Comment by nicholaszein** [comment]
Hey @Michaelgimii,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. Here's why:

The Empty Cart template works a little differently from the other endpoints, and this is why it was added to the Cart widget, and not to the Site Settings. This also prevents conflicts with other WooCommerce add-ons. We encourage you to reach out to Crocoblock support and ask them to give support to this feature since they have their own implementation in place.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
