### ISSUE TITLE
⛔ 🚀 Feature Request: new UI for box shadow option

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20716]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

A simple and concise ui for the box shadow option would be great. Of course, this suggestion is simple and requires more thought and ideas. Just for a suggestion...

### Describe the solution you'd like

![new UI](https://user-images.githubusercontent.com/88034902/207096533-d85f5cd9-ef73-4517-ba2e-6311acff8e9c.jpg)

Like the padding and margin controls in version 3.10, clicking on each option expands its width.

![width](https://user-images.githubusercontent.com/88034902/207096988-5d81fb44-15fd-4c4b-a57b-53150bd96e32.png)

That would be really great.

**Comment by loucasl** [comment]
I like this quite a bit actually. And since the new UI would be quite a bit more condensed, it could be taken out of a "popup" and incorporated right in the style tab like most other controls

**Comment by 79ho3ein** [comment]
The box shadow options are great to compress (especially since they expand on click). But I don't think it makes sense to remove box shadow options from the popup.
Because the shadow of the box alone has 3 options (Color, four options and Position). If these are removed from the popup and added directly in the style section, they will take up a lot of space in the style section and this will not be interesting from the ui, ux point of view. Of course, this is my personal opinion.
