### ISSUE TITLE
📚 ❓ Question: Having the repeater item index available like {{{ index }}} in title field.

### ISSUE THREAD

**Issue by afzaliwp** [elementor/elementor#20737]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I was trying to create a repeater field that the repeater item title is like Section 1, Section 2, Section 3 instead of Item #1, Item #2, Item #3.
The only way I found was by adding a field with value of "Section 1", "Section 2", and "Section 3" like this:
```
$this->add_control(
			'list_items',
			[
				'label' => esc_html__( 'List Items', 'elementor-list-widget' ),
				'type' => \Elementor\Controls_Manager::REPEATER,
				'fields' => $repeater->get_controls(),           /* Use our repeater */
				'default' => [
					[
						'title' => esc_html__( 'Section 1', 'elementor-list-widget' ),
						'link' => '',
					],
					[
						'title' => esc_html__( 'Section 2', 'elementor-list-widget' ),
						'link' => '',
					],
					[
						'title' => esc_html__( 'Section 3', 'elementor-list-widget' ),
						'link' => '',
					],
				],
				'title_field' => '{{{ title }}}',
			]
		);
```

In my controls, I don't have anything for the title.

### Describe the solution you'd like

What I think a solution is being able to use something like {{{ index }}} in the title field.

Is it possible to achieve this in any other way now?

**Comment by nicholaszein** [comment]
Hello @afzaliwp,

Thanks for submitting your question! 🙏

Right now there is no other way to do this, and we don't have plans to change this for the time being, since it would require a whole new method to store these values, which are usually changed when they are used again.

What you could do though, is to use CSS <ins>[Counter](https://css-tricks.com/css-counters-custom-list-number-styling/)</ins> <ins>[Increments](https://css-tricks.com/almanac/properties/c/counter-increment/)</ins> on your rendered elements if you need them to always have a number, no matter what order the items in the repeater are arranged. This isn't something you would be doing in the editor though...

I hope this can help.

Kind regards
