### ISSUE TITLE
⛔ 🚀 Feature Request: Set Hidden Elements as Hidden by default in User Preferences

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20743]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team.

Currently, if we hide an element on different devices, their color changes in the editor, but it doesn't hide completely. But if we turn off the Hidden Elements option in the Hidden Elements settings, if we hide an element, it will be completely hidden in the editor.
But isn't it better if this option is disabled by default?

### Describe the solution you'd like

By default, turn off Hidden Elements in User Preferences. If desired, users can change it back to the previous state.

**Comment by perks98** [comment]
I agree

**Comment by 79ho3ein** [comment]
+1

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. Here's why:

We tried that before, and it didn't work. Many users were confused and did not understand why their elements were missing when editing in responsive mode. We found that leaving this as an option would be the best way to cater to both beginners and seasoned users since once you've selected to hide those elements, you've done it consciously, while also enabling users to see that an element was hidden when this option is disabled.

I hope this makes sense.

Best regards
