### ISSUE TITLE
⛔ 🐞 Bug Report: Loop Grid Create a Template Button Broken with Beta Tester Active 

### ISSUE THREAD

**Issue by awakekat** [elementor/elementor#20767]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Using LocalWP current Version with PHP 7.4.1 and Nginx. Mac Monterey 12.6.1 with current chrome browser.

I had the Beta Tester Active and Elementor 3.9.1 and Elementor Pro set to 3.10.0-beta1. I inserted a Loop Grid and clicked the Create a Template and the page just jumped to the top of the page. It did not give me the save page modal. I manually saved the page and tried the button again - it just jumped to the top again. I went back and turned off Beta and rolled back to 3.9 and then updated to 3.9.1 and it worked as expected. Just a heads up for 3.10

### Steps to reproduce

Set Elementor > Tools > Version Control > Beta Tester to Active
Refresh plugins page to get new beta version to 3.10 and update

Go to a page and drop in the Loop Grid. Press the Create a Template button in the grid...
The page should just jump to the top. Modal to save the page to go and make the template does not appear. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment == LocalWP
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.4.1
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://eletemps.local
	Home URL: http://eletemps.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: awakekat@aol.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.9.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.0-beta1
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	Import Export Website Kit: Inactive
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Active
	Admin Top Bar: Active by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Loop Carousel: Inactive by default
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 372022-11-09 17:37:15 [info] elementor-pro::elementor_pro_updater Started 
2022-11-09 17:37:15 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-09 17:37:15 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-09 17:37:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev34',
  'to' => '3.9.0-beta1',
)]
2022-11-09 17:37:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0-dev34',
  'to' => '3.9.0-beta1',
)]
2022-12-08 16:18:54 [info] elementor::elementor_updater Started 
2022-12-08 16:18:54 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-08 16:18:54 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-08 16:18:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-beta1',
  'to' => '3.9.0',
)]
2022-12-08 16:18:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-beta1',
  'to' => '3.9.0',
)]
2022-12-13 21:49:01 [info] elementor::elementor_updater Started 
2022-12-13 21:49:01 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-13 21:49:01 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-13 21:49:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.10.0-beta1',
)]
2022-12-13 21:49:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.10.0-beta1',
)]
2022-12-15 19:19:00 [info] elementor-pro::elementor_pro_updater Started 
2022-12-15 19:19:00 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-15 19:19:00 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-15 19:19:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-beta1',
  'to' => '3.10.0-beta1',
)]
2022-12-15 19:19:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-beta1',
  'to' => '3.10.0-beta1',
)]

JS: showing 3 of 3JS: 2022-08-14 17:09:04 [error X 6][http://eletemps.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.1:3:691794] T.getContainer is not a function 
JS: 2022-08-14 17:21:49 [error X 1][http://eletemps.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.1:3:1060434] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-12-15 23:14:10 [error X 5][http://eletemps.local/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.10.0-beta1:2:61340] Cannot read properties of undefined (reading \'createTemplate\') 

PHP: showing 2 of 2PHP: 2022-12-08 16:33:25 [notice X 6][/Users/minikat18/Local Sites/eletemps/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-13 22:18:12 [notice X 4][/Users/minikat18/Local Sites/eletemps/app/public/wp-content/plugins/elementor/app/modules/import-export/module.php::563] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @awakekat!

Thanks for submitting your issue! 🙏 

Please, **update both** Elementor Core and Elementor Pro to Beta-3.10 if you want to test both. Let us know if the issue goes away.

**Comment by nicholaszein** [comment]
Hello @awakekat,

#### 🕙 It's been a while since we answered you, and we haven't received any feedback. 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We couldn't reproduce your issue using the Loop Grid widget with version 3.10-beta3. The save template dialog appeared every time. Most likely your issue is related to either browser cache or incompatibility between using the stable version with the beta.


https://user-images.githubusercontent.com/113993460/210127277-4a2c2e05-e7f2-480a-89b5-9de96e181e88.mp4


### ✅ What you can do to solve your issue:
* Make sure you have cleared the cache after updating, and that you have the latest beta versions installed.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
