### ISSUE TITLE
⛔ 🚀 Feature Request: New button to add column in container

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20780]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team.

First of all, I need to say that this request is similar to [this issue](https://github.com/elementor/elementor/issues/19688). But much more complete and practical.

Add a container in Elementor. If we want to quickly add 2, 3 or 4 columns inside this container, we will not be able to. We need to add the containers one by one and customize their width so that we can add the desired columns. This is a long solution.

### Describe the solution you'd like

Add a new option to the container handle. This button is shown in the image below.

![elementor](https://user-images.githubusercontent.com/77163248/208314574-e1b5ca62-b340-4776-b89b-e50e2d7ac980.png)

Like the image above, after clicking this button, the structure container will be displayed (proper structures for creating columns in a row)

By selecting the desired structure, the columns are immediately added to the container.

**If you still do not understand this request, please watch the following video :**

https://user-images.githubusercontent.com/77163248/208314925-51a61f87-9ea5-4497-a726-940cadfb1949.mp4

**Comment by nicholaszein** [comment]
Hello @79ho3ein,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being. 

Having such a button would lead to users inadvertently adding more containers than they would need, and the context to choose columns works best for parent-level containers, as it's shown in the video below.

https://user-images.githubusercontent.com/113993460/208945041-afe64cd3-0e41-4f70-8624-638e33eb1759.mp4


Sometimes we need to think more about the workflow and try to protect our users from becoming confused when using our products. Some features other builders offer to seem nice, but they can also lead to user error if not properly implemented.

Take your first image for example. You have a single container inside a parent container. In this case, the correct way would be to add a parent container with the desired columns as I show in the video above since the single container inside your parent container is doing nothing but create a deeper nested stack. There would be rare occasions when you would need to add nested containers with columns inside other containers. In this case, using a grid would be more appropriate. But this is something we can discuss in the future. 😉 🤫 

I hope you can understand.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
