### ISSUE TITLE
❌ 🐞 Bug Report: Uncaught ReferenceError: elementor_new_template_form_controls is not defined

### ISSUE THREAD

**Issue by diquispe** [elementor/elementor#20800]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi, i updated elementor and elementor pro

i disabled other plugins and and the following behaviors have emerged

1.- Console Ooutput when i click in "Add New" button in "templates" page and does not open the usual modal
Uncaught ReferenceError: elementor_new_template_form_controls is not defined

2.- Right click in elementor editr page no work (with habitual context items)
3.- i cannot define "display conditions" in elementor editor page

I am currently experiencing this failure on 4 web sites

### Steps to reproduce

1) editing any eementor page
2) trying to create a template (with or witoouth elementor pro)

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.47 (Win64) OpenSSL/1.1.1k mod_fcgid/2.3.10-dev
	MySQL version: MySQL Community Server (GPL) v5.7.33
	PHP Version: 8.1.8
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://southwindsperu.web
	Home URL: https://southwindsperu.web
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%category%/%postname%
	Language: en-US
	Timezone: 0
	Admin Email: diquispe@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: JupiterX Child
	Version: 1.0.0
	Author: Artbees
	Child Theme: Yes
	Parent Theme Name: JupiterX
	Parent Theme Version: 2.5.5
	Parent Theme Author: Artbees

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.0.3
		Author: WP Engine

	Contact Form 7
		Version: 5.7.1
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.9.1
		Author: Elementor.com

	Fluent Forms
		Version: 4.3.22
		Author: Contact Form - WPManageNinja LLC

	Fluent Forms Pro Add On Pack
		Version: 4.3.21
		Author: Fluent Forms

	JetEngine
		Version: 3.0.7
		Author: Crocoblock

	JetMenu
		Version: 2.2.4
		Author: Crocoblock

	JetPopup
		Version: 1.6.3
		Author: Crocoblock

	Jupiter X Core
		Version: 2.5.4
		Author: Artbees

	Permalink Manager Lite
		Version: 2.3.0
		Author: Maciej Bis

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	WP-Sweep
		Version: 1.1.5
		Author: Lester 'GaMerZ' Chan

	WP Tripadvisor Review Widgets
		Version: 9.7.1
		Author: Trustindex.io <support@trustindex.io>

	Yoast SEO
		Version: 19.12
		Author: Team Yoast

	Yoast SEO Premium
		Version: 19.0.1
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default

== Log ==
	
Log: showing 15 of 152022-11-21 21:59:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-21 21:59:39 [info] elementor::elementor_updater Started 
2022-11-21 21:59:39 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-21 21:59:39 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-21 21:59:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-12-19 20:20:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.1',
)]
2022-12-19 20:20:06 [info] elementor::elementor_updater Started 
2022-12-19 20:20:06 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-19 20:20:06 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-19 20:20:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.1',
)]
2022-12-19 22:41:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.9.1',
)]
2022-12-19 22:41:39 [info] elementor-pro::elementor_pro_updater Started 
2022-12-19 22:41:39 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-19 22:41:39 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-19 22:41:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.9.1',
)]

PHP: showing 7 of 7PHP: 2022-11-21 22:01:06 [notice X 9][C:\laragon\www\southwindsperu\wp-content\plugins\elementor-pro\license\updater.php::84] version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 22:01:32 [notice X 343][C:\laragon\www\southwindsperu\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::304] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\laragon\www\southwindsperu\wp-content\plugins\elementor\modules\dev-tools\deprecation.php(304): class type trigger_error()
#2: C:\laragon\www\southwindsperu\wp-content\plugins\elementor\core\common\modules\finder\categories-manager.php(68): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: C:\laragon\www\southwindsperu\wp-content\plugins\elementor\core\common\modules\finder\categories-manager.php(50): Elementor\Core\Common\Modules\Finder\Categories_Manager -> register()
#4: C:\laragon\www\southwindsperu\wp-content\themes\jupiterx\lib\api\elementor\functions.php(338): Elementor\Core\Common\Modules\Finder\Categories_Manager -> add_category()
',
)]
PHP: 2022-11-21 22:01:32 [notice X 1071][C:\laragon\www\southwindsperu\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\laragon\www\southwindsperu\wp-content\plugins\elementor\modules\dev-tools\deprecation.php(304): class type trigger_error()
#2: C:\laragon\www\southwindsperu\wp-content\plugins\elementor\includes\managers\controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: C:\laragon\www\southwindsperu\wp-content\plugins\elementor\includes\managers\controls.php(501): Elementor\Controls_Manager -> register()
#4: C:\laragon\www\southwindsperu\wp-content\plugins\jupiterx-core\includes\extensions\raven\includes\plugin.php(519): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-11-21 22:03:59 [warning X 5][C:\laragon\www\southwindsperu\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 22:04:14 [notice X 430][C:\laragon\www\southwindsperu\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 22:18:21 [notice X 266][C:\laragon\www\southwindsperu\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::304] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-21 22:54:35 [warning X 20][C:\laragon\www\southwindsperu\wp-content\plugins\elementor\includes\managers\image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-11-22 00:05:48 [error X 2][https://southwindsperu.web/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-22 18:18:08 [error X 1][https://southwindsperu.web/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:1061530] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-11-22 19:53:56 [error X 2][https://southwindsperu.web/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:649119] this.model.isValidChild is not a function 
JS: 2022-11-22 20:13:33 [error X 3][https://southwindsperu.web/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:295940] Cannot read properties of undefined (reading \'html\') 
JS: 2022-12-19 22:36:11 [error X 57][https://southwindsperu.web/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.9.1:2:2932] elementor_new_template_form_controls is not defined 

== Elementor - Compatibility Tag ==

**Comment by ParaSwarm** [comment]
I am also getting this and it is causing us a major headache. May have to lose days of work to recover from this.

**Comment by nicholaszein** [comment]
Hello @diquispe and @ParaSwarm,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* Your issue is most likely related to one of the following:
   * 3rd-party add-on / theme conflict.
   * Plugin conflict.
   * Cache conflict.
* We see in your System Info that you have some add-ons using deprecated Elementor methods.

### ✅ What you can do to solve your issue:
* Make sure your theme is compatible with the latest version of Elementor.
* Make sure your Elementor add-ons are compatible with the latest version of Elementor.
   * JetEngine
   * JetMenu
   * JetPopup
   * Jupiter X Core

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
