### ISSUE TITLE
⛔ 🚀 Feature Request: Remove “Elementor |” from Browser Tab when editing an article

### ISSUE THREAD

**Issue by DieterLudwig** [elementor/elementor#20809]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hello,
I am editing several pages of my site simultanously in different Tabs of Firefox.
Each tab shows “Elementor | <Title>”.
[Screenshot](https://a8t.de/Screen_Shot_12-12-22_at_01.40_PM.JPG)
My Browser just shows "Elementor | " tabs
(Just be be clear, I am talking about editing - not display the Pages to visitors)

I am using Elementor free.

### Describe the solution you'd like

I would like to remove the “Elementor | ” part so only “<Title>” is .displayed.

**Comment by m1ga** [comment]
Think this is the wrong place to ask for that :smile: Not an issue/feature request for Elementor.

You change that in your theme, most of the time in the customizer.

**Comment by nicholaszein** [comment]
Hello @DieterLudwig,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

The title is displayed in that way so people can identify that the editor is open in a tab. It's unlikely we would change this behavior, especially because of backward compatibility.

🔖 We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future.  

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
