### ISSUE TITLE
⛔ 🐞 Bug Report: Inline Padding is being ignored on boxed outer flex container

### ISSUE THREAD

**Issue by brittaweller** [elementor/elementor#20816]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The padding on a boxed top level container `div.e-con.e-con-boxed` should be added completely to it's `div.e-con-inner`.

But padding-left and padding-right is being applied to `div.e-con.e-con-boxed`. As this container is for some reason full width (why is that by the way?! 🤔) it doesn't do anything on screens which are wider than the container width.

See screenshots:

`div.e-con.e-con-boxed`:

<img width="1435" alt="Bildschirmfoto 2022-12-21 um 16 56 11" src="https://user-images.githubusercontent.com/24314640/208877676-0db856af-90b2-404c-a75b-1e4e8ba49d00.png">

`div.e-con-inner`

<img width="1437" alt="Bildschirmfoto 2022-12-21 um 16 56 27" src="https://user-images.githubusercontent.com/24314640/208877777-50d20b57-ff40-4f13-a328-e1802fdcbe5c.png">

### Steps to reproduce

1) Create boxed container 
2) Set a padding
3) On desktop or widesceen there will be no right or left padding visibly applied

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Elementor 3.9.1

**Comment by perks98** [comment]
Personally I prefer it how it works at the moment as it can be much easier to align content together for more pixel-perfect designs for aligning to the content area width. If padding was added to the inner container it would push content inwards.

Screenshot below of if a type of inner container had the 30px padding rather than the parent:

![Screenshot 2022-12-21 114622](https://user-images.githubusercontent.com/55829113/208897997-5eeb5596-2b9d-4e23-bc91-c1d7bf80d8bb.png)

**Comment by nicholaszein** [comment]
Hello @brittaweller,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is not a bug. This is the intended behavior, and it was decided after much user feedback and research that this is the best approach. We have no intention in changing this behavior.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
