### ISSUE TITLE
❌ when use Fusion Builder showing this type error 

### ISSUE THREAD

**Issue by infoeditzone** [elementor/elementor#20828]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

There has been a critical error on this website. Please check your site admin email inbox for instructions.

### Steps to reproduce

when use Fusion Builder showing this type error - **_There has been a critical error on this website. Please check your site admin email inbox for instructions._**

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.31
	PHP Version: 8.0.25
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 250M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://editzone.in
	Home URL: https://editzone.in
	WP Multisite: No
	Max Upload Size: 250 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 5.5
	Admin Email: devisphotography1@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Avada Child
	Version: 1.0.0
	Author: ThemeFusion
	Child Theme: Yes
	Parent Theme Name: Avada | Shared By VestaThemes.com
	Parent Theme Version: 5.9
	Parent Theme Author: ThemeFusion

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Avada Custom Branding
		Version: 1.2
		Author: ThemeFusion

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Conditional Fields for Contact Form 7
		Version: 2.3.1
		Author: Jules Colle

	Contact Form 7
		Version: 5.7.1
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.9.2
		Author: Elementor.com

	Fusion Core
		Version: 3.9
		Author: ThemeFusion

	Health Check & Troubleshooting
		Version: 1.5.1
		Author: The WordPress.org community

	Popup Builder
		Version: 4.1.14
		Author: Sygnoos

	Rank Math SEO
		Version: 1.0.104.1
		Author: Rank Math

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.10
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP Mail SMTP
		Version: 3.7.0
		Author: WPForms

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default

== Log ==
	
Log: showing 20 of 402022-12-01 11:45:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-12-08 13:05:53 [info] elementor::elementor_updater Started 
2022-12-08 13:05:54 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-08 13:05:54 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-08 13:05:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-16 11:53:49 [info] elementor::elementor_updater Started 
2022-12-16 11:53:49 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-16 11:53:49 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-16 11:53:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-16 11:53:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-16 11:53:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-16 11:53:51 [info] elementor::elementor_updater Started 
2022-12-16 11:53:51 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-16 11:53:51 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-16 11:53:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-22 11:08:23 [info] elementor::elementor_updater Started 
2022-12-22 11:08:23 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-22 11:08:23 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-22 11:08:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-22 11:08:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]

PHP: showing 2 of 2PHP: 2022-12-16 11:53:50 [warning X 1][/home/editzone/public_html/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/home/editzone/public_html/wp-content/uploads/elementor/css/post-4813.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-16 11:53:50 [warning X 1][/home/editzone/public_html/wp-content/plugins/elementor/core/files/manager.php::111] unlink(/home/editzone/public_html/wp-content/uploads/elementor/css/post-6438.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @infoeditzone,

Thank you for reaching out! 🙏 

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party software.

If your issue is specifically happening only when you're using a feature from a 3rd party, or only when the 3rd party plugin or theme is active, you'll need to contact the support for that software or its developers.

Moreover, it is not recommended to use two different builders in the same installation, since usually, both will try to do the same thing and conflict with each other. We do not provide support or integration with the Fusion Builder.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

⚠️  Backup your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2.  Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3.  Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards
