### ISSUE TITLE
⛔ 🐞 Bug Report: Experiments Hello Theme Header & Footer Learn more button not working

### ISSUE THREAD

**Issue by tokyosucks** [elementor/elementor#20836]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello Theme Header & Footer setting section on Experiments within Elementor setting screen, there is a "Learn more" button with the wrong hyperlink.  

### Steps to reproduce

1) Elementor setting screen
2) Experiments tab
3) Scroll down to Hello Theme header and footer part, and click on Learn more.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.27
	PHP Version: 7.4.33
	PHP Memory Limit: 1G
	PHP Max Input Vars: 1000
	PHP Max Post Size: 1G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://bestcbd.jp
	Home URL: https://bestcbd.jp
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 1G
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Asia/Tokyo
	Admin Email: info@jetsets.jp
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.6
		Author: WP Engine

	Advanced Editor Tools (previously TinyMCE Advanced)
		Version: 5.6.0
		Author: Automattic

	Elementor
		Version: 3.11.0-dev2
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.0-beta2
		Author: Elementor.com

	Google Listings and Ads
		Version: 2.3.4
		Author: WooCommerce

	Jetpack
		Version: 11.6
		Author: Automattic

	MailPoet
		Version: 4.3.0
		Author: MailPoet

	Safe SVG
		Version: 2.0.3
		Author: 10up

	Site Kit by Google
		Version: 1.90.0
		Author: Google

	WooCommerce
		Version: 7.2.2
		Author: Automattic

	Wordfence Security
		Version: 7.8.2
		Author: Wordfence

== Elements Usage ==
	
	footer : 1
		divider : 2
		nav-menu : 1
		text-editor : 1
		theme-site-logo : 1
	header : 2
		nav-menu : 1
		theme-site-logo : 1
	wp-post : 3
		text-editor : 1
	wp-page : 4
		container : 1
		heading : 1
		posts : 1
		text-editor : 2
	single-post : 1
		container : 1
		heading : 1
		post-info : 1
		text-editor : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	loop-item : 1
		container : 1
		posts : 1

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active
	Editor V2: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Loop Carousel: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 402022-12-14 20:53:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.10.0-beta1',
)]
2022-12-14 20:53:59 [info] elementor-pro::elementor_pro_updater Started 
2022-12-14 20:53:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-14 20:53:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-14 20:53:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.10.0-beta1',
)]
2022-12-14 20:55:32 [info] elementor::elementor_updater Started 
2022-12-14 20:55:32 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-14 20:55:32 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-14 20:55:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0-dev1',
  'to' => '3.11.0-dev1',
)]
2022-12-20 08:56:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev1',
  'to' => '3.11.0-dev2',
)]
2022-12-20 08:56:52 [info] elementor::elementor_updater Started 
2022-12-20 08:56:52 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-20 08:56:52 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-20 08:56:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev1',
  'to' => '3.11.0-dev2',
)]
2022-12-20 08:56:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.0-dev1',
  'to' => '3.11.0-dev2',
)]
2022-12-20 21:50:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.0-beta1',
  'to' => '3.10.0-beta2',
)]
2022-12-20 21:50:17 [info] elementor-pro::elementor_pro_updater Started 
2022-12-20 21:50:17 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-20 21:50:17 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-20 21:50:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.0-beta1',
  'to' => '3.10.0-beta2',
)]

PHP: showing 3 of 3PHP: 2022-12-14 17:36:26 [notice X 2][/home/brworkout/bestcbd.jp/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-14 20:54:28 [notice X 2][/home/brworkout/bestcbd.jp/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: /home/brworkout/bestcbd.jp/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/brworkout/bestcbd.jp/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/brworkout/bestcbd.jp/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/brworkout/bestcbd.jp/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2022-12-14 22:10:36 [notice X 1][/home/brworkout/bestcbd.jp/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @tokyosucks,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* The link leads to the correct article in the Elementor Help Center using the latest stable versions of Elementor (v3.9.2), Elementor Pro (v.3.9.2), and the Hello Elementor theme (v2.6.1).


https://user-images.githubusercontent.com/113993460/210337525-fd921ac3-4f45-45c8-9fcf-69b767a4b15b.mp4



### ✅ What you can do to solve your issue:
* Make sure you're using the latest stable version of the plugin.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
