### ISSUE TITLE
⛔ 🐞 Bug Report: Menu Cart indicator is not displaying properly after updating Elementor to v3.9+

### ISSUE THREAD

**Issue by vasilevdiag** [elementor/elementor#20832]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After update Elementor Pro 3.9.0 the item indicator in the cart menu does not show in a bubble. While redacting the page the icon shows properly, but it does not show a bubble in the live site, just a number that is too big over the cart icon. 
In version 3.8.2 everything was ok.
In version 3.9.0, 3.9.1 and 3.9.2 the bug still exists.

![3 8 2](https://user-images.githubusercontent.com/121225560/209112118-958b0d6b-9f4c-4559-a7fc-a4dd773864fc.jpg)
![3 9 0](https://user-images.githubusercontent.com/121225560/209112236-42d4c8aa-4a98-41bd-9993-122469d29a5c.jpg)

### Steps to reproduce

While redacting the page the icon shows properly, but it does not show a bubble in the live site, just a number that is too big over the cart icon. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-staging7.stickerberry.shop-22-12-2022.txt](https://github.com/elementor/elementor/files/10286108/system-info-staging7.stickerberry.shop-22-12-2022.txt)

**Comment by snokychan** [comment]
I also encounter the exact same issue, except that the number show up on the left of the cart. Changing the cart widget settings to "don't show the number" doesn't change the issue, even though I refreshed Eementor and purged the cache.
I am waiting for the bug to be fixed to upgrade to Elementor 3.9, and stayd at 3.8.2 in the meantime.

**Comment by 79ho3ein** [comment]
Have you tried regenerating the css through settings? I can't reproduce this bug in version 3.9.2

**Comment by snokychan** [comment]
Hi, Yes I did regenerate the elementor files and CSS as well as purged the cache. I also checked the website in 2 browsers in private browsing but the result is the same.
I also tried editing the header and re created the cart widget anew but same issue.

**Comment by vasilevdiag** [comment]
Hi Snokychan! I found a solution to the problem: You need to delete the cache from the browser - history/clear browsing data/advanced/cached images and files
Unfortunately, the problem will be solved only for you, but not for customers who have already visited your site.
I'm writing this because I don't believe the Elementor developers will fix this. Good luck!

**Comment by SuperHanss** [comment]
I had this problem too, starting from 3.9.0. For some reason all three browsers I tested with were fetching an older cached version of widget-woocommerce.min.css and therefore using the incorrect CSS (which is why clearing browser cache fixes it).

The following CSS fixed it for me:

```
.elementor-menu-cart--items-indicator-bubble .elementor-menu-cart__toggle .elementor-button-icon .elementor-button-icon-qty[data-counter]{
    display:block;
    position:absolute;
    min-width:1.6em;
    height:1.6em;
    line-height:1.5em;
    top:-.7em;
    inset-inline-end:-.7em;
    border-radius:100%;
    color:var(--items-indicator-text-color,#fff);
    background-color:var(--items-indicator-background-color,#d9534f);
    text-align:center;
    font-size:10px
}
```
Paste it in Site Settings > Custom CSS (you will need to adjust it to match your config in the editor).
It's taken directly from the latest and correct Elementor Pro 3.9.2 widget-woocommerce.min.css file and is only a temporary fix until there's hopefully a proper fix!

**Comment by snokychan** [comment]
Hi @vasilevdiag and @SuperHanss 
Thanks for your feedback, it makes sense now why there's such a bug. I'll do your trick add a custom css to solve this issue, but that would be great if the problem was fixed as many websites must be affected and it's not nice to have this number popping out of nowhere for design consistency.
Cheers !

**Comment by nicholaszein** [comment]
Hello everyone,

Thank you for reaching out, and apologies for the delay! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* This issue, as pointed above, is related to cache.

### ✅ What you can do to solve your issue:
* Follow [this guide](https://elementor.com/help/changes-dont-appear-online/) to learn how to deal with this type of issue.
* Always clear the cache from both your server, site, and browser <ins>before</ins> and <ins>after</ins> any update!
* Alternatively try to deactivate the "Improved CSS Loading" experiment.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
