### ISSUE TITLE
⛔ 🐞 Bug Report: Custom Code Learn More link is broken

### ISSUE THREAD

**Issue by jaysonwebtel** [elementor/elementor#20839]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When clicking the [Learn more about adding custom code](https://go.elementor.com/wp-dash-custom-code) link on the Custom Code Page ( edit.php?post_type=elementor_snippet ), the resulting links displays an SSL Protocol error as its trying to go to https://go.elementor.com:8080/wp-dash-custom-code/ instead of https://go.elementor.com/wp-dash-custom-code/

### Steps to reproduce

When clicking the [Learn more about adding custom code](https://go.elementor.com/wp-dash-custom-code) link on the Custom Code Page ( edit.php?post_type=elementor_snippet ), the resulting links displays an SSL Protocol error as its trying to go to https://go.elementor.com:8080/wp-dash-custom-code/ instead of https://go.elementor.com/wp-dash-custom-code/

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.2
	MySQL version: MariaDB Server v10.3.37
	PHP Version: 8.0.26
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://stevestavs.com
	Home URL: https://stevestavs.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 64M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-ZA
	Timezone: Africa/Johannesburg
	Admin Email: jayson@web-telecoms.co.za
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_ZA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.6
		Author: WP Engine

	Advanced Database Cleaner
		Version: 3.1.1
		Author: Younes JFR.

	Elementor
		Version: 3.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.2
		Author: Elementor.com

	Enable Media Replace
		Version: 4.0.1
		Author: ShortPixel

	Podcast Subscribe Buttons
		Version: 1.4.6
		Author: SecondLine Themes

	Rank Math SEO
		Version: 1.0.104.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.26.1
		Author: Rank Math

	Replace Google Fonts with Bunny Fonts
		Version: 2.1.2
		Author: antonioleutsch

	TinyPNG - JPEG, PNG & WebP image compression
		Version: 3.4.1
		Author: TinyPNG

	Unlimited Elements for Elementor
		Version: 1.5.44
		Author: Unlimited Elements

	WebP Express
		Version: 0.25.5
		Author: Bjørn Rosell

	WP All Import - ACF Add-On
		Version: 3.3.8
		Author: Soflyy

	WP All Import Pro
		Version: 4.7.8
		Author: Soflyy

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		container : 5
		heading : 2
		image : 1
		shortcode : 1
		text-editor : 2
	footer : 1
		container : 1
		nav-menu : 1
		text-editor : 1
	header : 1
		container : 1
		nav-menu : 1
		social-icons : 1
		theme-site-logo : 1
	wp-post : 0
		container : 2
		text-editor : 1
	wp-page : 4
		container : 20
		form : 4
		heading : 12
		image : 9
		image-box : 4
		menu-anchor : 1
		spacer : 1
		testimonial : 8
		text-editor : 7
	single-post : 1
		container : 4
		divider : 1
		heading : 2
		icon-list : 1
		post-info : 1
		post-navigation : 1
		share-buttons : 1
		shortcode : 1
		text-editor : 3
		theme-post-content : 1
		theme-post-title : 1
		ucaddon_audio_player_mejs : 1
	loop-item : 1
		container : 1
		heading : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1

== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Landing Pages: Inactive
	Colour Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Inactive
	Lazy Load Background Images: Active
	Save as Default: Active by default
	Page Transitions: Active
	Notes: Inactive
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active

== Log ==
	
JS: showing 3 of 3JS: 2022-11-08 17:54:47 [error X 1][https://clientproofs.web-telecoms.co.za/stevestavs/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:540651] Blocked a frame with origin \"https://clientproofs.web-telecoms.co.za\" from accessing a cross-origin frame. 
JS: 2022-11-10 07:28:05 [error X 1][https://clientproofs.web-telecoms.co.za/stevestavs/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:649119] this.model.isValidChild is not a function 
JS: 2022-11-29 13:44:11 [error X 19][https://clientproofs.web-telecoms.co.za/stevestavs/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:769459] Cannot read properties of undefined (reading \'localized\') 

PHP: showing 5 of 5PHP: 2022-11-10 09:55:07 [notice X 1][/var/www/vhosts/web-telecoms.co.za/clientproofs.web-telecoms.co.za/stevestavs/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-27 14:51:50 [error X 1][/var/www/vhosts/web-telecoms.co.za/clientproofs.web-telecoms.co.za/stevestavs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/vhosts/web-telecoms.co.za/clientproofs.web-telecoms.co.za/stevestavs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/vhosts/web-telecoms.co.za/clientproofs.web-telecoms.co.za/stevestavs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/vhosts/web-telecoms.co.za/clientproofs.web-telecoms.co.za/stevestavs/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/vhosts/web-telecoms.co.za/clientproofs.web-telecoms.co.za/stevestavs/wp-includes/class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/vhosts/web-telecoms.co.za/clientproo [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-28 10:32:21 [notice X 2][/var/www/vhosts/web-telecoms.co.za/clientproofs.web-telecoms.co.za/stevestavs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-29 13:24:34 [warning X 4][/var/www/vhosts/web-telecoms.co.za/clientproofs.web-telecoms.co.za/stevestavs/wp-content/plugins/elementor/app/modules/import-export/module.php::563] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-29 13:24:35 [warning X 1][/var/www/vhosts/web-telecoms.co.za/clientproofs.web-telecoms.co.za/stevestavs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 352022-12-14 08:46:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]
2022-12-14 08:46:56 [info] elementor::elementor_updater Started 
2022-12-14 08:46:56 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-14 08:46:57 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-14 08:46:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-14 08:46:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-24 12:25:39 [info] elementor::elementor_updater Started 
2022-12-24 12:25:39 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-24 12:25:39 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-24 12:25:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-24 12:26:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-24 12:26:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.9.2',
)]
2022-12-24 12:26:46 [info] elementor::elementor_updater Started 
2022-12-24 12:26:46 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-24 12:26:46 [info] elementor-pro::elementor_pro_updater Started 
2022-12-24 12:26:46 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-24 12:26:46 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-24 12:26:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.9.2',
)]
2022-12-24 12:26:46 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-24 12:26:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Unlimited Elements for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @jaysonwebtel,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* Tested using the latest version of both Elementor and Elementor Pro (v3.9.2), I cannot reproduce your issue. See:


https://user-images.githubusercontent.com/113993460/210339113-c3c1edd0-3b30-45fa-b188-e6a5e2382092.mp4


### ✅ What you can do to solve your issue:
* Check your host, router, and DNS settings. Make sure this it not being caused by a VPN.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
