### ISSUE TITLE
⛔ 🐞 Bug Report: Logo uploads to wrong folder

### ISSUE THREAD

**Issue by jaysonwebtel** [elementor/elementor#20868]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor is uploading the logo to the folder where the old logo was instead of according to the new upload date

### Steps to reproduce

In Elementor - Settings - Site Settings
Site Identify
- Current logo & Icon will display. 
- Upload new logo and icon through this panel and the files will go the folder of the original / previous logo instead of the year and month that it was uploaded in Wordpress. eg image goes to 2020 / 09 folder instead of 2022 / 12 when the logo is uploaded, which makes it difficult to find the file on FTP.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.20.2
	MySQL version: MariaDB Server v10.3.37
	PHP Version: 8.0.26
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://staging.web-telecoms.co.za
	Home URL: https://staging.web-telecoms.co.za
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 128M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-ZA
	Timezone: Africa/Johannesburg
	Admin Email: jayson@web-telecoms.co.za
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_ZA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54

== Active Plugins ==
	Elementor
		Version: 3.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.2
		Author: Elementor.com

	Elementor WHMCS Elements
		Version: 2.0
		Author: voidCoders

	Envato Elements
		Version: 2.0.11
		Author: Envato

	Query Monitor
		Version: 3.10.1
		Author: John Blackbourn

	Rank Math SEO
		Version: 1.0.104.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.26.1
		Author: Rank Math

	Replace Google Fonts with Bunny Fonts
		Version: 2.1.2
		Author: antonioleutsch

	TinyPNG - JPEG, PNG & WebP image compression
		Version: 3.4.1
		Author: TinyPNG

	Unlimited Elements for Elementor (Premium)
		Version: 1.5.45
		Author: Unlimited Elements

== Elements Usage ==
	
	footer : 1
		container : 5
		heading : 2
		icon : 1
		image : 5
		nav-menu : 1
	header : 1
		nav-menu : 1
		theme-site-logo : 1
	section : 9
		button : 1
		divider : 3
		form : 1
		heading : 25
		icon-box : 9
		icon-list : 1
		image : 5
		price-table : 6
		slides : 1
		social-icons : 1
		text-editor : 9
	wp-page : 11
		container : 61
		divider : 4
		heading : 42
		html : 1
		icon : 12
		icon-box : 3
		icon-list : 5
		image : 9
		menu-anchor : 2
		price-table : 33
		section-domain-search : 2
		text-editor : 40
		ucaddon_border_btn_effect : 6
		ucaddon_step_process : 3
		ucaddon_timeline_bullets : 2
		ucaddon_underline_animated_button : 2

== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active
	Landing Pages: Inactive
	Colour Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Inactive
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Inactive
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 412022-12-15 10:21:30 [info] elementor::elementor_updater Started 
2022-12-15 10:21:30 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-15 10:21:31 [info] elementor-pro::elementor_pro_updater Started 
2022-12-15 10:21:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-15 10:21:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-15 10:21:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-15 10:21:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-15 10:21:31 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-15 10:21:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0',
  'to' => '3.9.1',
)]
2022-12-26 11:32:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-26 11:34:03 [info] elementor::elementor_updater Started 
2022-12-26 11:34:03 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-26 11:34:04 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-26 11:34:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-26 11:34:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-26 11:34:56 [info] elementor-pro::elementor_pro_updater Started 
2022-12-26 11:34:56 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-26 11:34:56 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-26 11:34:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-26 11:34:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]

PHP: showing 1 of 1PHP: 2022-11-21 20:25:46 [warning X 1][/var/www/vhosts/web-telecoms.co.za/staging.web-telecoms.co.za/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-11-21 18:26:52 [error X 2][https://staging.web-telecoms.co.za/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:803353] Cannot convert undefined or null to object 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Elementor WHMCS Elements: Compatibility not specified
	Unlimited Elements for Elementor (Premium): Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @jaysonwebtel,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* This is the default behavior from WordPress when you click to **REPLACE** a logo instead of removing the existing one and adding a new one.
* When you **REPLACE** a logo, it will be added to the same place where the old one was.
* When you **REMOVE** a logo, it will be added as a new file.
* Elementor uses the same methods as WordPress to add the Site Logo and Site Icon, it only wraps the function inside the Elementor interface for easy access.

### ✅ What you can do to solve your issue:
* Instead of replacing the logo, remove it by clicking the trash icon that appears when you hover the image, then add a new one.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
