### ISSUE TITLE
⛔ 🐞 Bug Report: Hamburger menu and YouTube link not working on iPad Air

### ISSUE THREAD

**Issue by DenkDigitaal** [elementor/elementor#20881]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I want to report a bug that I found on a iPad Air Model Number MD786HC/B. This is an older iPad that will not update anymore to the latest iOS. The iPad works on iOS 12.5.6. I found out that the Hamburger menu stopped working on both Safari and Google Chrome after updating Elementor. The menu that I use on my testwebsite was a default Header menu template from Elementor. I also used on my homepage a defaulth About template block from Elementor. This block contained a link to a YouTube video. The link to the YouTube also didn't work on the iPad Air. I started testing with older versions of Elementor and found out that the menu and the link to YouTube will start work again with version 3.6.5 of Elementor and Elementor Pro. I would like to use the latest versions of Elementor and Elementor Pro but then I bumb into this problem.

I made two exactly the same test websites:

1. https://www.natuurovernachting.nl/ **Elementor 3.6.5** - The hamburger menu and YouTube link is **working** on iPad Air**
2. https://www.natuurchalet.nl/ **Elementor 3.9.2** - The hamburger menu and YouTube link is **not working on iPad Air**

### Steps to reproduce

1) Set-up a WordPress test website with the Hello theme
2) Download Elementor and Elementor Pro
3) Make two pages 1.homepage 2. about us
4) Add the Beauty Salon - Home - page template to the homepage
5) Add at the bottom of the Beauty Salon - Home - page an about block with a YouTube video link
6) Add the Beauty Salon - About - page to the about page
7) Make a Menu and add the two pages that you created
8) Add the header with the FLAIR logo to both pages and in the menu you see the Home and About us link
9) Go to the iPad Air (Modelnumber: MD786HC/B)
10) Click on the Hamburger menu: the Hamburger menu will open and does not work
11) Go to the homepage and click on the YouTube link: the YouTube video link will open
12) Go to Elementor >Tools
13) Click the **Version Control** tab
14) Go back to version 3.6.0 for Elementor and Elementor Pro
15) Repeat step 10 and step 11 on the iPad and you will see that the menu and YouTube link will work

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: MySQL Community Server (GPL) v5.7.31
	PHP Version: 7.4.27
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://www.natuurovernachting.nl
	Home URL: https://www.natuurovernachting.nl
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: 0
	Admin Email: info@denkdigitaal.nl
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.6.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.0
		Author: Elementor.com

== Gebruik van elementen ==
	
	header : 1
		button : 1
		image : 1
		nav-menu : 1
	wp-page : 2
		button : 4
		call-to-action : 10
		heading : 41
		icon-box : 3
		image : 3
		nav-menu : 2
		spacer : 4
		text-editor : 13
		video : 1

== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Standaard actief
	Verbeterd laden van assets: Standaard actief
	Verbeterd laden van CSS: Standaard actief
	Pictogrammen inline lettertype: Standaard inactief
	Toegang verbeteringen: Standaard actief
	Import Export Template Kit: Standaard actief
	Extra aangepaste onderbrekingspunten: Standaard actief
	Verberg verouderde WordPress widgets voor zoekresultaten: Standaard actief
	: Standaard inactief
	Flexbox container: Standaard inactief
	Default to New Theme Builder: Standaard actief
	Hello Theme header & footer: Standaard actief
	Landingspagina&#039;s: Standaard actief
	Kleur sampler: Standaard actief
	Favoriete widgets: Standaard actief
	Beheerder bovenste balk: Standaard actief
	Page Transitions: Standaard actief
	Form Submissions: Standaard actief
	Scroll Snap: Standaard actief

== Log ==
	
PHP: showing 1 of 1PHP: 2022-12-29 10:44:04 [notice X 4][/home/groepen/domains/natuurovernachting.nl/public_html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Niet compatibel

== Elementor Pro - Compatibility Tag ==

**Comment by vicmich** [comment]
Same issue... plus: when I changed breakpoints to get text menu on landscape and portrait ipad, dropdowns are unavailable.

Hello Elementor  2.6.1
Elementor 3.10
Elementor Pro 3.10.1
ipad air 2 MH0W2LL/A
os 12.2

**Comment by nicholaszein** [comment]
Hello there,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
Unfortunately, the Safari browsers prior to version 14 are not supported anymore, since those versions do not have advanced support for newer JS technologies used by Elementor.

You can read more about the minimum requirements for Elementor [here](https://elementor.com/help/requirements/).

Moving forward Elementor will only support browsers that are compatible with those new methods.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
