### ISSUE TITLE
⛔ 🐞 Bug Report: Accordion animation janky

### ISSUE THREAD

**Issue by torchsmith** [elementor/elementor#20884]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When you open/close accordion widget the animation that opens/closes the tab is janky/chunky. It should be smooth.

### Steps to reproduce

1. Create new page.
2. Add accordion widget.
3. Add at least 2 items.
4. Open/close items to see effect.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Unix) OpenSSL/1.1.1f
	MySQL version: mariadb.org binary distribution v10.5.18
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 50000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://xxxxx
	Home URL: https://xxxxx
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Admin Email: xxxxx
	Debug Mode: Active

== Theme ==
	Name: Custom
	Version: 1.0
	Author: Custom
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.0.6
		Author: WP Engine

	Elementor
		Version: 3.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.2
		Author: Elementor.com

	Fundamento
		Version: 1.1.5
		Author: Web Programming Solutions

	Query Monitor
		Version: 3.10.1
		Author: John Blackbourn

	Safe SVG
		Version: 2.0.3
		Author: 10up

	Smush
		Version: 3.12.4
		Author: WPMU DEV

	Unlimited Elements for Elementor (Premium)
		Version: 1.5.45
		Author: Unlimited Elements

	Yoast SEO
		Version: 19.13
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Lazy Load Background Images: Active
	Save as Default: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active

== Log ==
	
Log: showing 20 of 382022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-12-28 04:37:52 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-12-28 04:37:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.7.3',
)]
2022-12-28 04:38:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.9.2',
)]
2022-12-28 04:38:45 [info] elementor-pro::elementor_pro_updater Started 
2022-12-28 04:38:45 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-28 04:38:45 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-28 04:38:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.3',
  'to' => '3.9.2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Unlimited Elements for Elementor (Premium): Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by torchsmith** [comment]
I just want to note that this has been a problem for what seems like years.

**Comment by nicholaszein** [comment]
Hello @torchsmith,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This depends greatly on your machine. The animation is executed via CSS, and your browser + machine will determine if the animation goes smoothly or not depending on the capabilities of the device. As you can see in the video below, testing the animation does not return any _"janky"_ animation. It goes very smoothly.

https://user-images.githubusercontent.com/113993460/212767850-6c40126c-2cd7-4fb7-95d3-098845cd8bfe.mp4

### ✅ What you can do to solve your issue:
* Besides testing this without any other Elementor add-on or plugin active, you should check on another device with a better graphics card.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.

* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
