### ISSUE TITLE
⛔ 🐞 Bug Report: WordPress Importer & Export does not import Elementor content correctly

### ISSUE THREAD

**Issue by Fixed-1** [elementor/elementor#20887]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I import the demo content, all Elementor widgets move in the single “Text widget” – in other words, the WordPress importer “does not recognize” the widgets and sections. All is in the one/same text widget.
![9q](https://user-images.githubusercontent.com/106771850/210123208-45619879-6df6-4f9a-80a7-630256faef01.jpg)

### Steps to reproduce

every time import xml file

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.10
	MySQL version: MySQL Community Server - GPL v8.0.17
	PHP Version: 7.3.10
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 4096M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	

== WordPress Environment ==
	Version: 6.1.1
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 4 GB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Admin Email: 
	Debug Mode: Active

== Theme ==
	Name: Twenty Twenty-Three
	Version: 1.0
	Author: the WordPress team
	Child Theme: No

== Active Plugins ==
	Elementor
		Version: 3.9.2
		Author: Elementor.com

	WordPress Importer
		Version: 0.8
		Author: wordpressdotorg

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default

== Log ==
	

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @Fixed-1,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
The WordPress Importer is not capable of importing Elementor content, therefore this is a feature we do not support. In other words, you can't import content using that tool if you want to preserve the Elementor content.

### ✅ What you can do to solve your issue:
Luckily we have the E[xport/Import Templates](https://elementor.com/help/template-library/) feature, as well as the [Export/Import Kit](https://elementor.com/help/what-is-import-export/) feature if you have Elementor Pro, which allows you to import an entire website.

If you need to export/import Elementor designs, use the built-in features pointed out above instead of using the WordPress Importer, or use a Backup Plugin to migrate your content from one website to another.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
