### ISSUE TITLE
⛔ 🐞 Bug Report: Under certain conditions, the text will go off the page.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20909]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If you enter a letter without a space in any of the text widgets such as headings, it will go off the page and horizontal scrolling will appear in the browser.

### Steps to reproduce

![bug](https://user-images.githubusercontent.com/88034902/210404863-24008c11-3732-4e7f-b24e-8a5da812b84f.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hi @Michaelgimii,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* There is a CSS property called `word-break` responsible for specifying how words should break when they reach the end of the line. For compatibility reasons Elementor does not apply this property because this might affect negatively the design of your pages.
* This is something that should be added either globally, or locally. Since this is something rare, we do not apply any styles to change this behavior to avoid limiting user choices.

### ✅ What you can do to solve your issue:
* You can use the following CSS declaration to set the `word-break` to break at any point:

````css

selector .elementor-heading-title {
    word-break: break-all;
}

For more information, please read the articles below:

https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
https://www.w3schools.com/cssref/css3_pr_word-break.php

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines.

Kind regards
