### ISSUE TITLE
⛔ 🐞 Bug Report: A very simple bug in the container settings ui

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20957]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi @nicholaszein

There is a very simple bug in the editor that will not take much time to fix. It's so simple that there's no need to mention it in the changelog😃

In the container settings, if we click on the options, the color of the active icons changes very slowly. This issue occurs in Justify Content, Align Items, Wrap, Align Self and order options. It is clear in the video below. We can also see in the video below that the Direction option does not have this problem. **If the editor is in dark mode, everything works fine. This item is only visible when the editor is in light mode.**
The problem is very minor and related to the **transition duration** in some options (Justify Content, Align Items, Wrap, Align Self and order).

### Steps to reproduce

https://user-images.githubusercontent.com/88034902/211403096-c6c75196-fa27-4a83-acd9-956ff75bff76.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
The animation for both Light and Dark modes is the same, what changes is your eye perception due to the change from a completely white background to almost the opposite color. There is nothing that can be done in this case. Moreover, your device memory, graphics card, and browser can have a great influence on how CSS animations are rendered, which might also be the reason why you are perceiving it as a delay. This is normal and expected behavior. We won't change this animation for the time being.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines.

Kind regards
