### ISSUE TITLE
⛔ 🐞 Bug Report: Possible bug in color sampler

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20956]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi

When we select the color sampler, the [structure section](https://prnt.sc/IuIWxNSHFgp8) disappears and creates a very unpleasant ux. I am just working with color sampler. Is this a normal behavior? It creates bad ux anyway. Why should this section disappear?

### Steps to reproduce

1- Add a widget
2- In the color settings of this widget, click on the color sampler.

After clicking on it, the structure section will disappear.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by SneakyMouse1** [comment]
+1

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- This is the expected behavior. When the color sample is active, the interface is hidden to allow you to sample the content of the page without interference.
- We have no plans to change this behavior at this moment.
- 

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).
Kind regards
