### ISSUE TITLE
⛔ 🐞 Bug Report: Slider too wide when put inside an inner segment

### ISSUE THREAD

**Issue by badg0n** [elementor/elementor#20952]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I try to put a slider element inside of an inner section, the slider will get too wide, ignoring the parent margin and padding values, so it overflows.

### Steps to reproduce

1) Add section
2) Add inner section within
3) Add slider element within
4) Set it to full width
5) It is too wide

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.25
	PHP Version: 8.0.20
	PHP Memory Limit: 256M
	PHP Max Input Vars: 2000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /blog/%year%/%monthnum%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Yummy Recipe
	Version: 1.0.1
	Author: Blossom Themes
	Child Theme: Yes
	Parent Theme Name: Vilva
	Parent Theme Version: 1.2.0
	Parent Theme Author: Blossom Themes

== User ==
	Role: administrator
	WP Profile lang: de_DE_formal
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Verbesserungen der Zugänglichkeit: Standardmäßig aktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	Import Export Website Kit: Standardmäßig aktiviert
	Native WordPress-Widgets aus den Suchergebnissen ausblenden: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Standardmäßig deaktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Startseiten: Standardmäßig aktiviert
	Farbpalette: Standardmäßig aktiviert
	Bevorzugte Widgets: Standardmäßig aktiviert
	Admin Leiste: Aktiv
	Lazy Load Background Images: Standardmäßig deaktiviert
	Save as Default: Standardmäßig aktiviert
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Loop: Standardmäßig deaktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Standardmäßig aktiviert


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Unkompatibel
	Polylang Connect for Elementor: Unkompatibel

== Elementor Pro - Compatibility Tag ==
	
	Polylang Connect for Elementor: Unkompatibel
				

````
</details>

**Comment by nicholaszein** [comment]
Hello @badg0n,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We could not reproduce the issue consistently on our environment using only Elementor and Elementor Pro with the Hello Elementor theme.
* Your issue is most likely caused by overflow, either not enough space for the content inside your slides, or the positioning of elements outside the slider widget, which happens with some 3rd-party add-on slider solutions. Since you have not provided the complete System Info with the information about which plugins you're using and Isolated the problem as indicated in our guidelines, we can surely say what is causing your issue.
* The issue reported can also be caused by excessive margin/padding inside your sections and inner sections.

### ✅ What you can do to solve your issue:
* Tweak the spacing around the slider.
* Check if you don't have any performance optimization plugin removing the basic styles for the slider.
* Tweak your slider styles, reduce the size of text, and adapt your content.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
