### ISSUE TITLE
⛔ 🚀 Feature Request: Element Render Optimization: apply "should_render" filter then call print_content() only if needed

### ISSUE THREAD

**Issue by knbmedia** [elementor/elementor#20970]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hello
The "should_render" filter is called after the print_content() function of the element (in element-base.php).
So the element content is first built then if should_render return false, it is not displayed.
It seems as an extra work for nothing.
I think should_render filter should be called first then if it returns true, build the element !
Regards

### Describe the solution you'd like

Call the print_content() function AFTER detecting if the element should render.

**Comment by nicholaszein** [comment]
Hello @knbmedia ,

Thank you for submitting a feature request! 🙏 

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap.

What you're requesting can't be done, because up until that point, we still don't know if there is content to be added or not, and the proper sanitization hasn't happened yet as well. We need to know if there is content to be printed first before we decide if it should be rendered.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
