### ISSUE TITLE
⛔ 🐞 Bug Report: z-index bug in menu cart (editor)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20980]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi @nicholaszein and @avivu 

When we open the Menu cart widget in the editor, the borders of the containers are placed on the menu cart widget. Please see the following image :

![Screenshot (986)](https://user-images.githubusercontent.com/88034902/211771217-dd170048-df00-4e44-ac5d-8011d3a160d4.png)

### Steps to reproduce

1- In the header, place the menu cart widget inside the container.
2- In the editor, click on the menu cart to open it.

After opening the menu cart, you will see the image above. Please fix this. It is true that it has no effect on the front end, but it is very annoying in the editor.

Thanks to the great team of Elementor

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hi @Michaelgimii,

Thank you for reaching out! 🙏 

As reported and discussed [here](https://github.com/orgs/elementor/discussions/19854#discussioncomment-3851844), [here](https://github.com/orgs/elementor/discussions/20328#discussioncomment-4268061), [here](https://github.com/elementor/elementor/issues/19842), and also [here](https://github.com/orgs/elementor/discussions/21125#discussioncomment-4769759), this is not a bug. So...

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor.
* This is the expected behavior and we have no plans to change it for the time being as explained by me on the different occasions above.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines.

PS: Please do not tag us on your issues. We have procedures in place, and we all are following GitHub very closely. Tagging us will only make it more time-consuming for us to evaluate other issues, and will take longer to answer yours as well. There is no problem in tagging one in a response inside a comment. But please do not tag Elementor staff on your issues. Thanks.

Kind regards
