### ISSUE TITLE
⛔ 🐞 Bug Report: Code deleted when I switching between visual editor and text editor

### ISSUE THREAD

**Issue by fay0913** [elementor/elementor#20991]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have a page that has pieces of additional code. When I switch between the visual editor and back to the text editor, a part of the additional code disappear that makes the button nonfunctioning.
I know that this issue has been addressed before. But is there any update that fixes the issue?

### Steps to reproduce

Click "Edit with Elementor"
Paste the code in text editor
Switch to visual editor
Back to Text editor

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

https://www.tuislittleworld.hk/wp-login.php?redirect_to=https%3A%2F%2Fwww.tuislittleworld.hk%2Fwp-admin%2F&reauth=1

**Comment by hybridmuse** [comment]
Yup, the Text Editor widget has been buggy forever.

Try entering some <br> in Text mode, then switch to Visual and back to Text, all <br> disappear.

To make things even worse, the editor defaults to Visual mode when you click on the widget.
So should you need to add more markup, all <br> are lost and you need to manually enter them all again.

A real nightmare to say the least.

**Comment by nicholaszein** [comment]
Hello @fay0913,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* This is the expected behavior of the WordPress classic editor, and it has been like that forever as @hybridmuse correctly mentioned.

### ✅ What you can do to solve your issue:
* There are two ways you can change this behavior:
  * You can install the [Advanced Editor Tools](https://wordpress.org/plugins/tinymce-advanced/) plugin and switch the option to `Keep the paragraph tags in the Classic block and the Classic Editor` on, to prevent WordPress from stripping HTML tags from the text editor.
  * You can add [this snippet of PHP code](https://gist.github.com/nicholaszein/301e1e7b9ef4c486bb74770673aa1957) using the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin to prevent WordPress (not Elementor) from stripping the tags from the text editor. (Use this code at your own risk. If you don't know how to use it, try the plugin above).

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
