### ISSUE TITLE
✔️  (Shortcode) Buttons in Text Editor don't work

### ISSUE THREAD

**Issue by Lageeek** [elementor/elementor#2099]
Referencing to
https://github.com/pojome/elementor/issues/2077#issuecomment-318547661

Edit in ELementor -> Text editor 
buttons of other plugins don't work there or are not available, Switch back to "edit in Wordpress Editor" and the buttons do their job.

Tested with several plugins, e. g. Toolset (wp-types.com).

**Comment by arielk** [comment]
Have you tried embedding your shortcode into a shortcode widget?

**Comment by Lageeek** [comment]
Hi arielk,
that's not the point. You can't use any (really not one!) 3rd Party plugin together with elementor, that uses the text editor. Try to install tttcrop (this plugin inserts editional fields in the text editor (popup/edit mode) -> does not work.
Types (free to install) let you insert queries, e.g. site title or custom field (etc) into the content, mixed with the other text.
I moved away from elementor now, I need a text editor, that have the same behavior like the normal wordpress text editor.
Also (not this bug but another bug) when I insert images in the text editor as a gallery, the post is full with emtpy p-tags. I have an article like  text - gallery - text -gallery -text - gallery, so it would drive me crazy to build 6 blocks (text editor and elementor gallery). It would be better to insert text and (default) gallery together into the text editor, but this fails.
I really like the potential of elementor, but for me these are too big issues in the workflow. May be later, when this will work.

**Comment by nicholaszein** [comment]
Hello there @Lageeek!

A lot of time has passed since you posted this, and Elementor has also evolved. Shortcodes work as expected inside Elementor, and when you need something more advanced, you can always use the Shortcode Dynamic-tag of Elementor Pro to add content dynamically.

I think it's safe to say that this is no longer an issue, and it's time to close it!

Thank you for your time with us, and I hope to see you back using Elementor soon. 🙏 

Kind regards,

Nick
