### ISSUE TITLE
⛔ 🐞 Bug Report: (CONFLICT) Flexbox conflict with Royal elementor addons plugin

### ISSUE THREAD

**Issue by F4K3YT** [elementor/elementor#21005]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Found a conflict in the Flexbox experimental settings that removes Royal elementor addons' parallax and particles optiones when editting the style of a section.

### Steps to reproduce

1) use elementor flexbox option (experimental settings). 2) download royal elementor addons. 3) see in section's style there is no parallax nor particles option available. 4)uncheck flexbox experimental setting. 5) see the parallax and particle options reappear.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-localhost-13-01-2023.txt](https://github.com/elementor/elementor/files/10413617/system-info-localhost-13-01-2023.txt)

**Comment by nicholaszein** [comment]
Hello @F4K3YT,

Thank you for reaching out! 🙏 

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

It seems the **Royal Elementor Addons** is the plugin causing the incompatibility issue. In this case, you need to contact the add-on developer and ask them to fix the incompatibility.

For now, that's all we can help you with.

Kind regards
