### ISSUE TITLE
⛔ 🐞 Bug Report: This page doesn't seems to exits

### ISSUE THREAD

**Issue by kumarsyadav2** [elementor/elementor#21009]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am following the installation and activation of elementor from documentation but after installing and activating the elementor and going to my localhost page then it is saying "this page doesn't seems to exits."

### Steps to reproduce

1. install elementor
2. activate elementor
3. going to localhost page
4. issue persists again and again

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.54 (Win64) OpenSSL/1.1.1p PHP/8.2.0
	MySQL version: mariadb.org binary distribution v10.4.27
	PHP Version: 8.2.0
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: No
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://localhost/wordpress
	Home URL: http://localhost/wordpress
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: sharkpediashubham@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.0.1
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.11.0-dev3
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Livemesh Addons for Elementor
		Version: 7.3
		Author: Livemesh

	Starter Templates
		Version: 3.1.22
		Author: Brainstorm Force

	WPForms Lite
		Version: 1.7.9.1
		Author: WPForms

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active by default
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Editor V2: Inactive by default
	Landing Pages: Active
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active
	Save as Default: Active

== Log ==
	
PHP: showing 1 of 1PHP: 2023-01-13 22:12:10 [notice X 1][C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\editor\notice-bar.php::79] Using ${var} in strings is deprecated, use {$var} instead [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 6 of 62023-01-13 22:37:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.11.0-dev3',
)]
2023-01-13 22:37:07 [info] elementor::elementor_updater Started 
2023-01-13 22:37:07 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-13 22:37:07 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-13 22:37:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.11.0-dev3',
)]
2023-01-13 22:37:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.11.0-dev3',
)]

== Elementor - Compatibility Tag ==
	
	Livemesh Addons for Elementor: Incompatible

**Comment by nicholaszein** [comment]
Hello @kumarsyadav2,

Thanks for contacting us! 🙏 

This is more of a support question, not really something we can answer here.

Your issue is most likely related to your localhost installation and configuration, which goes beyond what we offer as help, and is not an Elementor bug at all.

We advise you to ask for help on configuring your localhost installation in the [Global Elementor Community on Facebook](https://facebook.com/groups/Elementors/).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
