### ISSUE TITLE
⛔ 🚀 Feature Request: post and product terms in elementor dynamic tags

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#21022]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

In Elementor dynamic tags, we have two sections for product category option and product tag.

1 : in post terms dynamic tag.
2 : in product terms dynamic tag.

### Describe the solution you'd like

**Remove product category and product tag options from Post tems dynamic tag.** We have these two options in the product terms dynamic tag, so if they are removed from this section, there will be no problem.

**Comment by nicholaszein** [comment]
Hi @Michaelgimii,

Thank you for submitting a feature request! 🙏 

### ⛔ After reviewing your request, we have decided not to add this to our roadmap for the time being.

Posts and Products have different ways of being stored in the database, and different ways of being queried. Therefore different types of Dynamic-tags. We will continue to support WooCommerce Coding Standards, and support their CRUD objects implementation. Not to mention we have no plans to remove these options because of backward compatibility.

Please feel free to contact us again with other feature suggestions. 😉 

Best regards
