### ISSUE TITLE
⛔ 🐞 Bug Report: When clicking on the edit template button, the item loop style breaks for a moment.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#21035]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi team.

As mentioned in the title, When clicking on the edit template button, the item loop style breaks for a moment. We will have this problem 80% of the time. Sometimes the estial is not broken.

### Steps to reproduce

1- Create a loop builder template And inside it, use image and title widget and make it dynamic as title and featured  image.
2- Go back to the page and click on the edit template button. 

Before loading the loop item, its style is broken for 2 seconds.

As you can see in the video below, after clicking the edit template button, the style of the title widget, image, and icon list were broken for a few seconds. **This bug has no effect on the front end. But this is a weakness in the editor.**

https://user-images.githubusercontent.com/77163248/212571818-9b48d9b5-ad14-42fc-af2c-6135e60eaa0c.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-localhost-15-01-2023.txt](https://github.com/elementor/elementor/files/10421438/system-info-localhost-15-01-2023.txt)

**Comment by nicholaszein** [comment]
Hi @79ho3ein,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* This is the expected behavior since the editor needs to actually load the stylesheet for the Loop Item template in a way that it can be edited. So depending on the template, it will take a brief time (or not) for it to load.
* The stylesheet in question, or better speaking, the template in question is not being edited when you are not in the editing mode, so it needs to be loaded dynamically to be edited. Think of it as if you were going to the template library and clicking on the Loop Item template to edit it. So it might take some time for it to load. 
* This is how our templating system works, and for the time being, we have no plans to change it.
* This doesn't affect negatively the front-end. So no harm here.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines.

Kind regards
