### ISSUE TITLE
⛔ 🐞 Bug Report: Image widget with setted link and size set to standard media size 'large' causes the image to set srcset size to 'max-width: 800px' if the media size 'large' is larger than 800px.

### ISSUE THREAD

**Issue by koldwotr** [elementor/elementor#21076]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

My wordpress media size settings are set to their default values. So 'large' is 1024x1024 px. I drag an image widget into a container and set the media size to 'large'. The container content width is set to boxed (1120px). Then I set the link option to open a media lightbox. I leave all the other options untouched. The result I get is that the image displays with 800 px width in the frontend but it should be 1024 px as the 'large' media size is set. 

When I look into the 'img' DOM-element I can see that 'sizes=(max-width: 800px) 100vw, 800px' and 'width=800'. But it should be the 1024px. 

This only happens when I set the image-size to the standard media size option 'large'. With the other image size options it is set correctly to the expected width i.e. 'small' (150x150) -> results in srcset size max-width: 150px. But i.e. 'large' (1024x1024) -> results in srcset size max-width: 800px. If I set 'large' to below 800px width in the wordpress media settings then the widget gets the correct max-width. But as soon as I go over 800px it won't set the proper width but instead always sets the srcset size max-width to 800px. When I define i.e. the media size 'medium' as 1024x1024 or higher than large, it also works fine. So I can work around it and use another media size setting instead of 'large' and set it to my prefered size above 800px, but it would be better to use all the available options properly instead of working around.

### Steps to reproduce

1) create new post

2) drag an image widget into the content field

3) set an image from wordpress media library

4) in the 'content'-tab set 'Image Size' to 'large'

5) in the 'content'-tab set 'Link' to 'Media File'

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 11 v10.5.18
	PHP Version: 8.1.14
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Europe/Berlin
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0

== Active Plugins ==
	Elementor
		Version: 3.10.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.2
		Author: Elementor.com

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Loop Carousel: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 3 of 3PHP: 2023-01-19 13:37:30 [notice X 66][/usr/www/users/owrakr/genpress/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /usr/www/users/owrakr/genpress/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /usr/www/users/owrakr/genpress/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/usr/www/users/owrakr/genpress/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /usr/www/users/owrakr/genpress/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /usr/www/users/owrakr/genpress/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/usr/www/users/owrakr/genpress/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /usr/www/users/owrakr/genpress/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2023-01-19 13:37:30 [notice X 99][/usr/www/users/owrakr/genpress/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-19 14:57:27 [warning X 1][/usr/www/users/owrakr/genpress/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52023-01-19 15:59:00 [info] elementor-pro::elementor_pro_updater Started 
2023-01-19 15:59:00 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-19 15:59:00 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-19 15:59:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-19 15:59:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by koldwotr** [comment]
The elementor support helped me out and they found out that the problem occurs because of the 'Hello theme'. So I will move this issue over to the Hello theme repository.

**Comment by nicholaszein** [comment]
Hello @koldwotr,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* We tried to reproduce your issue internally, and in all our tests it works as expected. So the issue might be on your side.
* The actual image size needs to be larger than 1024px if you want it to appear as 1024px. WordPress does not scale up images if the dimensions are lower than the image size you're trying to use.
* Hello Elementor does not affect image sizes. If you think it is, please [submit a new bug report in the Hello Elementor repository.](https://github.com/elementor/hello-theme/issues/new)

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
