### ISSUE TITLE
⛔ 🐞 Bug Report: woo commerce app integration

### ISSUE THREAD

**Issue by andregsilvabr** [elementor/elementor#21077]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Installing Plugin: WooCommerce
Downloading installation package from https://downloads.wordpress.org/plugin/woocommerce.7.3.0.zip…

Unpacking the package…

Installing the plugin…

Destination folder already exists. /mnt/customers-3/customers-el-4092517-34374-asnative-wordpress-pvc-62f43e61e62ff20020a5bd45/wp-content/wp-content/plugins/woocommerce/

Plugin installation failed.

### Steps to reproduce

try to install woo commerce extension

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<html>
<body>

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | nginx/1.20.2 |  
MySQL version: | (Google) v8.0.26 |  
PHP Version: | 7.4.33 |  
PHP Memory Limit: | 128M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 256M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

</body>
</html>

**Comment by nicholaszein** [comment]
Hello @andregsilvabr,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* This is not an Elementor Bug. This is a problem with your WordPress installation.

### ✅ What you can do to solve your issue:
* Try first going to your WordPress Dashboard > Plugins and uninstalling WooCommerce. Then install it again. 
* Also, make sure you're using the latest version of WordPress which is 6.1.1. With this version, the problem you're reporting won't happen.
* If you have any more trouble, please contact your hosting support.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
