### ISSUE TITLE
⛔ 🐞 Bug Report: Grid Loop context lost, when using additional query inside custom widget render() function

### ISSUE THREAD

**Issue by vladninja** [elementor/elementor#21129]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am created a custom Widget with some controls.
When I am trying to create a new WP_Query based on the controls settings in the render method and use my own widget in the Grid Loop, the context of the $post after my Widget will be lost. I tried reset_post data and not reset, but the result is not good.

Example of the render method of widget:
```
protected function render() {
            $settings = $this->get_settings_for_display();
            $this->add_inline_editing_attributes( 'title', 'none' );
            
            $post = get_post();
            $post_id = $post->ID;

            $artistsField = get_post_meta($post_id, 'associated_artists', true);

            $args = array(
                'post_type' => 'artists',
                'posts_per_page' => -1,
                'post__in' => $artistsField
            );
            $artists = new WP_Query( $args );

            if ( $artists->have_posts() ) {
                echo '<div class="elementor-widget-post-info">';
                echo '<span>'.$settings['title'].' </span>';
                while ( $artists->have_posts() ) {
                    $artists->the_post();
                    echo '<span class="my-item"><a style="text-decoration: underline" href="'. get_permalink() .'">' . get_the_title() . '</a></span>, ';
                }
                echo '</div>';
            } else {
                echo 'No artists found.';
            }
            wp_reset_postdata();
        }
```

The CPT Work object has custom field CMB2 with an array of IDs to the CPT Artists, so I am trying to get the related to the Work Artists, but the context after my widget in a Grid Loop will be lost.

### Steps to reproduce

1. Create a widget with a render method which I inserted before
2. Create a page with a query loop
3. Create a loop template
4. In a loop template, use widget with any WP_Query in a render method
5. Add some context element after the widget to be able to see a context problems (e.g feature image, post link etc)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: MySQL Community Server - GPL v8.0.31
	PHP Version: 8.0.27
	PHP Memory Limit: 
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://localhost:8081
	Home URL: http://localhost:8081
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: xojeba6362@0pppp.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	custom-el
		Version: 1.0
		Author: vlad

	Elementor
		Version: 3.10.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.1
		Author: Elementor.com

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Loop Carousel: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 9 of 9PHP: 2023-01-23 14:27:43 [warning X 27][/var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-23 14:28:14 [warning X 5][/var/www/html/wp-content/plugins/elementor/includes/template-library/sources/local.php::869] Undefined array key "files" [array (
  'trace' => '
#0: /var/www/html/wp-content/plugins/elementor/includes/template-library/sources/local.php(869): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/html/wp-content/plugins/elementor/includes/template-library/manager.php(477): Elementor\TemplateLibrary\Source_Local -> import_template()
#2: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(63): Elementor\TemplateLibrary\Manager -> import_template()
#3: /var/www/html/wp-content/plugins/elementor/data/base/endpoint.php(162): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> create_items()
#4: /var/www/html/wp-content/plugins/elementor/data/base/endpoint.php(320): Elementor\Data\Base\Endpoint -> base_callback()
',
)]
PHP: 2023-01-23 14:28:14 [warning X 5][/var/www/html/wp-content/plugins/elementor/includes/template-library/sources/local.php::869] foreach() argument must be of type array|object, null given [array (
  'trace' => '
#0: /var/www/html/wp-content/plugins/elementor/includes/template-library/sources/local.php(869): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/html/wp-content/plugins/elementor/includes/template-library/manager.php(477): Elementor\TemplateLibrary\Source_Local -> import_template()
#2: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(63): Elementor\TemplateLibrary\Manager -> import_template()
#3: /var/www/html/wp-content/plugins/elementor/data/base/endpoint.php(162): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> create_items()
#4: /var/www/html/wp-content/plugins/elementor/data/base/endpoint.php(320): Elementor\Data\Base\Endpoint -> base_callback()
',
)]
PHP: 2023-01-23 14:30:49 [warning X 1][/var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(69): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/www/html/wp-content/plugins/elementor/data/base/endpoint.php(162): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> create_items()
',
)]
PHP: 2023-01-23 14:30:56 [error X 8][/var/www/html/wp-content/plugins/elementor/data/v2/base/exceptions/error-404.php::8] Class Elementor\Data\V2\Base\Exceptions\Error_404 cannot extend from interface Elementor\Data\V2\Base\Exceptions\Data_Exception [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-23 14:30:59 [warning X 25][/var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/www/html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/www/html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-01-23 14:35:23 [notice X 1][/var/www/html/wp-content/plugins/elementor/core/utils/import-export/parsers/wxr-parser-simple-xml.php::53] Function libxml_disable_entity_loader() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-23 14:41:54 [warning X 12][/var/www/html/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::84] Undefined array key "elementor-preview" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-23 17:56:55 [warning X 3][/var/www/html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2023-01-23 17:39:56 [error X 2][http://localhost:8081/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0:3:1075047] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-01-24 12:04:33 [error X 2][http://localhost:8081/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0:3:782020] Cannot read properties of undefined (reading 'localized') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @vladninja,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* Nested queries are not supported in the current version of the Loop Grid.
* What you are trying to do is not the correct way of using the Loop Grid.

If you think this could be a good addition to the Loop Builder, please submit a [new feature request](https://github.com/orgs/elementor/discussions/new?category=feature-request).

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
