### ISSUE TITLE
⛔ 📚 🐞 Bug Report: Change control event doesn't work on repeaters! 

### ISSUE THREAD

**Issue by nimaaminz** [elementor/elementor#21132]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello i read all issue related and spend a lot time to reading and debugging elementors code , 
my problem is : 
I need to listen control changing value events and by this function i found what i wanted : 
```
elementor.channels.editor.on('change' , (e) => {
   // any code here . . .     
});
```
and this events is amazing actually and i loved this until i see that this event not working on repeater controls !  
and i search a lot and try to test another ways but i couldn't found anything ! 
i think its a bug . . . 

### Steps to reproduce

1 - add the top code in somewhere in preview scripts or editor scripts 
2 - then you will see that when you change anything like a NUMBER control this function will call 
3 - but when you change a data of control that is inside a repeater , the function wont call ! 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

i use elementor 3.5.0 with elementor pro version 3.5.2 
and theme is Hello Elementor 
and i dont have any active plugin except my custom plugin add-on for elementor !  

the reason why i use elementor old version is for this bug : 
[https://github.com/elementor/elementor/issues/17839](https://github.com/elementor/elementor/issues/17839)

**Comment by nicholaszein** [comment]
Hello @nimaaminz,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* Elementor 3.5 is very outdated. Since then we have made fundamental changes to our Repeater API. 
* You did not provide your full System Info as required in our guidelines, therefore we can't consistently reproduce your issue.
* You did not provide a copy of the full code you're applying, so we can't see what might be causing the conflict you're reporting.
* The other issue you're reporting has been long resolved, and the behavior reported in that issue does not happen anymore.

### ✅ What you can do to solve your issue:
* You need to update to the latest version since we do not give support for older versions.
* If, after updating the issue still persist, it means this feature is not supported (since it's not in our [Documentation](https://developers.elementor.com)). In this case, you need to submit a new [Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request).

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
