### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor Pro + ProfileGrid

### ISSUE THREAD

**Issue by 7from1** [elementor/elementor#21140]

**Comment by nicholaszein** [comment]
Hello @7from1,

Thank you for reaching out! 🙏 

### ⛔ Please note that while we do welcome bug reports, we can't provide support for 3rd party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

For now, that's all we can help you with.

Kind Regards
