### ISSUE TITLE
⛔ 🐞 Bug Report: Just updated a client from Elementor 2.4x to latest version, though I keep getting errors in the console about things being Hard-depreciated?

### ISSUE THREAD

**Issue by jordane2086** [elementor/elementor#21153]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Just updated a client from Elementor 2.4x to latest version, though I keep getting errors in the console about things being Hard-depreciated?

### Steps to reproduce

Old version full upgrade to latest version.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 90M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://happyhippiestudios.org
	Home URL: https://happyhippiestudios.org
	WP Multisite: No
	Max Upload Size: 90 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: accounts@standandstretch.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 5.0.2
		Author: Automattic

	Breeze
		Version: 2.0.15
		Author: Cloudways

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Elementor
		Version: 3.10.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.2
		Author: Elementor.com

	Gravity Forms
		Version: 2.6.9
		Author: Gravity Forms

	Site Kit by Google
		Version: 1.92.0
		Author: Google

	Smash Balloon Instagram Feed
		Version: 6.1.1
		Author: Smash Balloon

	The7 Elements
		Version: 2.7.2
		Author: Dream-Theme

	The7 White-Label Tool
		Version: 1.0.1
		Author: Dream-Theme

	Wordfence Security
		Version: 7.8.2
		Author: Wordfence

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 20.0
		Author: Team Yoast

== Elements Usage ==
	
	archive : 2
		heading : 3
		template : 2
		the7-breadcrumb : 1
		the7_elements : 2
	footer : 3
		button : 4
		divider : 1
		heading : 11
		icon : 1
		icon-box : 4
		icon-list : 5
		image : 1
		shortcode : 1
		text-editor : 5
	header : 3
		breadcrumbs : 1
		button : 4
		heading : 2
		icon-list : 2
		image : 2
		nav-menu : 2
		social-icons : 2
		theme-page-title : 1
	page : 3
		heading : 4
		image : 1
		text-editor : 17
	popup : 3
		heading : 4
		icon-list : 2
		image : 1
		nav-menu : 1
		social-icons : 1
		text-editor : 1
	section : 28
		button : 19
		call-to-action : 15
		divider : 6
		form : 1
		heading : 37
		icon-list : 4
		image : 2
		nav-menu : 1
		posts : 1
		social-icons : 1
		spacer : 9
		text-editor : 11
		the7-breadcrumb : 2
		theme-page-title : 2
	single : 2
		button : 1
		heading : 3
		post-comments : 1
		post-info : 1
		post-navigation : 1
		share-buttons : 1
		theme-post-content : 1
	widget : 0
		button : 3
		heading : 3
	wp-post : 0
		divider : 4
		heading : 18
		image : 5
		spacer : 4
		text-editor : 9
	wp-page : 14
		button : 22
		call-to-action : 12
		divider : 6
		google_maps : 3
		heading : 56
		icon-list : 2
		image : 6
		price-list : 7
		shortcode : 1
		spacer : 9
		text-editor : 34
		video : 1

== Settings ==
	
	cpt_support: post, page, dt_portfolio, dt_testimonials, dt_team
	allow_tracking: yes
	font_display: swap

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Inactive
	Lazy Load Background Images: Inactive
	Save as Default: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
PHP: showing 5 of 5PHP: 2022-07-29 15:37:37 [notice X 3][/home/341820.cloudwaysapps.com/truzdsyqdz/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-19 23:02:53 [notice X 5][/home/341820.cloudwaysapps.com/truzdsyqdz/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-25 03:44:41 [error X 16][/home/341820.cloudwaysapps.com/truzdsyqdz/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php::47] Uncaught ReflectionException: Method get_site_editor_type does not exist in /home/341820.cloudwaysapps.com/truzdsyqdz/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php:47
Stack trace:
#0 /home/341820.cloudwaysapps.com/truzdsyqdz/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(47): ReflectionClass->getMethod()
#1 /home/341820.cloudwaysapps.com/truzdsyqdz/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(128): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_site_editor_type_bc()
#2 /home/341820.cloudwaysapps.com/truzdsyqdz/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(94): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_create_url()
#3 /home/341820.cloudwaysapps.com/truzdsyqdz/public_html/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-25 22:24:42 [notice X 3][/home/341820.cloudwaysapps.com/truzdsyqdz/public_html/wp-content/plugins/elementor/core/upgrade/elementor-3-re-migrate-globals.php::102] Undefined variable: active_kit_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-25 22:54:36 [notice X 1][/home/341820.cloudwaysapps.com/truzdsyqdz/public_html/wp-content/plugins/elementor/app/modules/import-export/module.php::628] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 8 of 8JS: 2023-01-03 13:49:49 [error X 85][https://happyhippiestudios.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.3:2:375483] Cannot read properties of undefined (reading \'get\') 
JS: 2023-01-25 03:36:32 [error X 1][https://happyhippiestudios.org/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2023-01-25 05:26:41 [error X 1][https://happyhippiestudios.org/wp-content/plugins/1elementor/assets/js/editor.min.js?ver=3.10.1:3:864436] Cannot read properties of undefined (reading 'val') 
JS: 2023-01-25 05:27:55 [error X 8][https://happyhippiestudios.org/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-01-25 05:46:03 [error X 6][https://happyhippiestudios.org/wp-content/plugins/1elementor/assets/js/editor.min.js?ver=3.10.1:3:782020] Cannot read properties of undefined (reading 'localized') 
JS: 2023-01-25 23:14:08 [error X 3][https://happyhippiestudios.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:1075047] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-01-26 02:54:40 [error X 1][https://happyhippiestudios.org/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:661291] this.model.isValidChild is not a function 
JS: 2023-01-26 03:05:36 [error X 1][https://happyhippiestudios.org/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.10.1:2:2932] elementor_new_template_form_controls is not defined 

Log: showing 20 of 302023-01-25 04:03:44 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-25 04:03:44 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2023-01-25 04:03:46 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2023-01-25 04:03:46 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2023-01-25 04:03:46 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2023-01-25 04:03:46 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2023-01-25 04:03:47 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2023-01-25 04:03:47 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2023-01-25 04:03:48 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list callback needs to run more 1 times 
2023-01-25 04:03:48 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start (2 of 2, 100%) 
2023-01-25 04:03:48 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2023-01-25 04:03:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.1',
  'to' => '3.10.2',
)]
2023-01-25 22:24:42 [notice] Re-migrate 3.0.0 globals: Start 
2023-01-25 22:24:42 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2023-01-25 22:24:42 [notice] System typography already exist. nothing to do. 
2023-01-25 22:24:42 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2023-01-25 22:24:42 [notice] System colors already exist. nothing to do. 
2023-01-25 22:24:42 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2023-01-25 22:24:42 [notice] Custom colors already exist. nothing to do. 
2023-01-25 22:24:42 [notice] Re-migrate 3.0.0 globals: End 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @jordane2086,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* It seems you're using an incompatible version of a 3rd-party Elementor add-on (probably The7 Elements).

### ✅ What you can do to solve your issue:
* You need to contact the Add-on developer and ask them to fix the incompatibility and update their code to make it compatible with the latest version of Elementor.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
