### ISSUE TITLE
🐞 Equal height is not applied when editing the loop item.

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#21164]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hey

When we are editing in the loop item, the equal height is not applied.

### Steps to reproduce

1- Add the Grid loop widget.
2- In this widget, create a template using the create template button and consider border for the parent container.
3- Click on the Save and back button.
4- Enable the equal column option.
5- Click on the template edit button to enter the loop item edit section again.

In this section, you can see that the equal height has not been applied to the item you are editing. **Please note that this bug has no effect on the front end.**

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-domain.com-26-01-2023.txt](https://github.com/elementor/elementor/files/10514024/system-info-domain.com-26-01-2023.txt)

**Comment by nicholaszein** [comment]
Hi @Joliamendi! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by aurabyte** [comment]
Any fix planned for this? Site is using containers (not converted I've always used them) Equal heights is not working at all on the loop grid with containers.

**Comment by nicholaszein** [comment]
Hello @Joliamendi, and @aurabyte!

Thank you for your patience!

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
The Equal Height functionality of the Loop Grid widget relies on the assumption that all the elements inside the Loop Item template are direct childs of the container of the template. If you nest them inside a child container, then there is no way the Loop Grid can detect what to detect as equal height. Here's a video example of how the equal height works, but does not affect any of the child elements of a child container:


https://github.com/elementor/elementor/assets/113993460/ad2e26f2-8490-45eb-b54f-38652b7f114a



### ✅ What you can do to solve your issue:
When designing your Loop Item template, make sure your elements inside are all direct child of the parent Loop Item container, as I demonstrate in the next video:

https://github.com/elementor/elementor/assets/113993460/d36a14ae-c7d1-4c4f-83e5-af8f44557d37

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor after following the troubleshooting steps above, feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

Kind regards
