### ISSUE TITLE
⛔ 🐞 Bug Report: Container a (link) HTML tag when loop builder breaks when button (even without link) exists

### ISSUE THREAD

**Issue by rhud** [elementor/elementor#21189]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using loop builder, setting the container HTML type to 'a (link)' causes the layout that contains a button (even without a link set) to duplicate and break. 

There were no links inside the container.

![CleanShot 2023-01-30 at 14 35 56](https://user-images.githubusercontent.com/136080/215388389-862610dc-dd76-4ede-b366-24ac61cd78ec.png)

Tested with only E and EPro activated on Hello theme, but still same issue.
 
**How I intended it to look:**
![CleanShot 2023-01-30 at 14 34 17](https://user-images.githubusercontent.com/136080/215388219-9e1702a4-a402-4a69-90cd-4d8f2746b193.png)

**How it looks when container set to 'a (link)':**
![CleanShot 2023-01-30 at 14 25 21](https://user-images.githubusercontent.com/136080/215388322-8d3b23bc-c0ee-4d0a-a27d-be761c7510e6.png)

### Steps to reproduce

1. Add Loop Grid to page
2. Create a new loop element
3. add content to container including a button
4. remove the # link from button
5. under 'additional options' for the container element, set HTML tag to 'a (link)'
6. set the link to 'post url' dynamic data 
7. save and return

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.11
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://monte2.scribbleandthink.dev
	Home URL: https://monte2.scribbleandthink.dev
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Australia/Sydney
	Admin Email: web@scribbleandthink.com
	Debug Mode: Inactive

== Theme ==
	Name: Page Builder Framework
	Version: 2.10.2
	Author: David Vongries
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.10.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.3
		Author: Elementor.com

== Elements Usage ==
	
	header : 1
		container : 1
		image : 1
		premium-nav-menu : 1
	page : 6
		container : 36
		heading : 6
		image : 6
		nav-menu : 8
	section : 2
		breadcrumbs : 1
		button : 5
		container : 7
		heading : 8
		text-editor : 3
	widget : 0
		breadcrumbs : 1
		spacer : 1
	wp-page : 2
		button : 3
		container : 31
		heading : 11
		icon-list : 1
		image : 4
		loop-grid : 2
		spacer : 2
		text-editor : 12
	loop-item : 2
		container : 2
		heading : 2
		theme-post-title : 2

== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Landing Pages: Inactive
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Inactive
	Notes: Active by default
	Loop: Active
	Loop Carousel: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Inactive

== Log ==
	
Log: showing 16 of 162023-01-22 05:28:39 [info] elementor-pro::elementor_pro_updater Started 
2023-01-22 05:28:39 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-22 05:28:39 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-22 05:28:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-22 05:28:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-22 18:14:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.8.4',
  'to' => '2.8.7',
)]
2023-01-30 15:16:58 [info] elementor::elementor_updater Started 
2023-01-30 15:16:58 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-30 15:16:59 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-30 15:16:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-30 15:16:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-30 15:17:06 [info] elementor-pro::elementor_pro_updater Started 
2023-01-30 15:17:06 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-30 15:17:06 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-30 15:17:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]
2023-01-30 15:17:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]

PHP: showing 6 of 6PHP: 2023-01-22 05:37:34 [notice X 538][/home/scribbl8/monte2.scribbleandthink.dev/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-22 17:54:51 [notice X 36][/home/scribbl8/monte2.scribbleandthink.dev/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/scribbl8/monte2.scribbleandthink.dev/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/scribbl8/monte2.scribbleandthink.dev/wp-content/plugins/elementor/core/common/modules/finder/categories-manager.php(68): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/scribbl8/monte2.scribbleandthink.dev/wp-content/plugins/analogwp-templates/inc/class-elementor.php(35): Elementor\Core\Common\Modules\Finder\Categories_Manager -> register()
#4: /home/scribbl8/monte2.scribbleandthink.dev/wp-includes/class-wp-hook.php(308): Analog\Elementor :: Analog\{closure}()
',
)]
PHP: 2023-01-23 12:49:10 [notice X 1][/home/scribbl8/monte2.scribbleandthink.dev/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-23 16:58:58 [notice X 13][/home/scribbl8/monte2.scribbleandthink.dev/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-23 22:12:16 [notice X 1][/home/scribbl8/monte2.scribbleandthink.dev/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-27 16:20:37 [notice X 16][/home/scribbl8/monte2.scribbleandthink.dev/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::168] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2023-01-22 05:38:18 [error X 1][https://monte2.scribbleandthink.dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:887749] elementorFrontend is not defined 
JS: 2023-01-23 01:53:39 [error X 3][https://monte2.scribbleandthink.dev/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils&ver=6.1.1:2:31703] elementor_new_template_form_controls is not defined 
JS: 2023-01-23 06:04:31 [error X 31][https://monte2.scribbleandthink.dev/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,regenerator-runtime,wp-polyfill,wp-dom-ready,wp-hooks&ver=6.1.1:2:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-01-23 11:00:39 [error X 5][https://monte2.scribbleandthink.dev/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.10.1:2:52931] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2023-01-23 11:11:35 [error X 20][https://monte2.scribbleandthink.dev/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.10.1:2:16011] Cannot read properties of undefined (reading 'global') 
JS: 2023-01-27 05:01:07 [error X 5][https://monte2.scribbleandthink.dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:1074660] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-01-30 03:54:28 [error X 1][https://monte2.scribbleandthink.dev/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.1:3:960509] Cannot read properties of null (reading 'history') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by Michaelgimii** [comment]
Hi @rhud 

I filed a suggestion for this which fixes it. Of course, if Elementor adds it. https://github.com/elementor/elementor/discussions/21190

**Comment by rhud** [comment]
@Michaelgimii ah that makes so much sense. 

I’ve got around it by replacing the button with a header (styled like the button)… but you’re right - the bricks button style would be better! 

Cheers

**Comment by perks98** [comment]
I have messaged them a few times about it. They don't plan to fix this anytime soon unless a lot of people demand this as they say it is just how WordPress works, you can see my issue thread they closed #20652

The way I got around it was to manually style a small container with an icon and heading set to span or div, then a bit of custom CSS so hovering over the container changes the colour of the icon and text.

**Comment by nicholaszein** [comment]
Hello @rhud,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* As other users mentioned, you can't add nested `<a>` tags. So adding a button widget inside a container with the `<a>` tags is not allowed as it says right underneath the URL field when you change the container tag to a link tag. 
* This is not an Elementor bug, and we won't change this behavior.

### ✅ What you can do to solve your issue:
* Use another widget as you did to simulate a button.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
