### ISSUE TITLE
📚 ❓ Which JS and CSS file related to the nav menu and their dropdown menu?

### ISSUE THREAD

**Issue by SayedTareq** [elementor/elementor#21198]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am using a speed optimization plugin that causes non-critical elements to load after the critical elements. Also JS file loads after all elements load. On the dropdown menu, I see the arrow is showing after all of the others elements load. So there must be include some js file. So I need to know which js file is included on the nav menu. files

### Steps to reproduce

Please check the previous description

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

I don't think system info need to include here needs

**Comment by nicholaszein** [comment]
Hi @SayedTareq,

Thank you for contacting us. 🙏 

This is more of a support question, not really something we can answer here.

The scripts in question are the following:
- Core: `elementor-frontend-js`
- Core: `elementor-frontend-modules-js`
- Core: `elementor-webpack-runtime-js`
- Pro: `elementor-pro-frontend-js`
- Pro: `elementor-pro-frontend-modules-js`
- Pro: `elementor-pro-webpack-runtime-js`
- Pro: `~/elementor-pro/assets/js/nav-menu.bundle.js` 
- Pro: `smartmenus-js`

Keep in mind that the scripts related to the Nav Menu are only the last two, but you will need the other scripts to be running in order to initiate the Nav Menu, and they are essential for the correct functioning of the Elementor infrastructure. You should check in your browser's Inspector Tools > Sources > your.domain > wp-content > plugins > elementor/elementor-pro > assets > js.

We do not recommend delaying any of Elementor's scripts. They already load at the bottom of the page, there is no need really to delay them, neither combine them.

I hope this helps.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports **<ins>only</ins>**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
