### ISSUE TITLE
⛔ 🐞 Bug Report: The popup event "elementor/popup/show" runs twice

### ISSUE THREAD

**Issue by AndreasH08** [elementor/elementor#21256]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm trying to use these popup events as a way to give a section and a button a class classes "active", however the " elementor/popup/show " event seems to run both when it opens, and when it closes, meaning the code I have for " elementor/popup/hide " is being overwritten by the show event.

### Steps to reproduce

1) - Add code from developers blog
2) - Connect it to a popup
3) - Add a alert to the " elementor/popup/show " and " elementor/popup/hide "
4) - Alert for " elementor/popup/show " should now run both when popup closes and opens

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.3.34
	PHP Version: 8.0.27
	PHP Memory Limit: 2147483648
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://eloomi.ashportfolio.dk
	Home URL: https://eloomi.ashportfolio.dk
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 2147483648
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/Copenhagen
	Admin Email: andreas.holst0899@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0

== Active Plugins ==
	Elementor
		Version: 3.10.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.2
		Author: Elementor.com

	Health Check & Troubleshooting
		Version: 1.5.1
		Author: The WordPress.org community

	Imagify
		Version: 2.1.1
		Author: Imagify – Optimize Images & Convert WebP

	one.com
		Version: 4.2.0
		Author: one.com

	one.com Spam Protection
		Version: 1.0.8
		Author: one.com

	Performance Cache
		Version: 3.0.6
		Author: one.com

	Yoast SEO
		Version: 20.0
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active
	Accessibility improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Landing pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Inactive
	Loop: Active by default
	Loop Carousel: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
JS: showing 2 of 2JS: 2023-01-16 10:10:52 [error X 1][https://eloomi.ashportfolio.dk/wp-includes/js/wp-auth-check.min.js?ver=6.1.1:2:652] h is undefined 
JS: 2023-02-04 20:23:03 [error X 77][https://eloomi.ashportfolio.dk/wp-includes/js/jquery/jquery.min.js?ver=3.6.1:2:40879] Cannot create property 'guid' on string 'c5265widgetsticky' 

Log: showing 15 of 152023-01-23 20:39:03 [info] elementor::elementor_updater Started 
2023-01-23 20:39:03 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-23 20:39:03 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-23 20:39:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]
2023-01-23 20:39:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0',
  'to' => '3.10.1',
)]
2023-01-23 20:39:28 [info] elementor-pro::elementor_pro_updater Started 
2023-01-23 20:39:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-23 20:39:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-23 20:39:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-23 20:39:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-30 11:47:49 [info] elementor::elementor_updater Started 
2023-01-30 11:47:49 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-30 11:47:49 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-30 11:47:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-30 11:47:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by nicholaszein** [comment]
Hello @AndreasH08,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- Using the latest version of both Elementor and Elementor Pro, we could not reproduce your issue.
- I see you have some performance optimization solutions on your website, they might be causing the issue you're reporting.
- Your code might be wrong.

See the video below:


https://user-images.githubusercontent.com/113993460/217652394-fee5fa59-f842-416d-94f6-728edee6db6c.mp4


### ✅ What you can do to solve your issue:
- Check the snippet you're using, it might not be working as expected.
- Deactivate any performance optimization solution you might be running.
- Isolate the problem by testing **<ins>ONLY</ins>** with Elementor and Elementor Pro active.

Try using the following snippet:

````js

jQuery( document ).on( 'elementor/popup/show', ( event, id, instance ) => {
  // Only run if a specific popup template ID is triggered
  if ( id = 123 ) {
    // do something here
  }
});
jQuery( document ).on( 'elementor/popup/hide', ( event, id, instance ) => {
  // Only run if a specific popup template ID is triggered
  if ( id = 123 ) {
    // do something here
  }
});

````

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
