### ISSUE TITLE
⛔ 🐞 Bug Report: Custom taxonomy not showing in conditions 

### ISSUE THREAD

**Issue by pbearne** [elementor/elementor#21278]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

We use the standard  register_taxonomy() function triggered on the init action.
We these arguments
$default_args = array(
   'labels'             => self::taxonomy_labels( $key, $taxonomy['single'], $taxonomy['plural'] ),
   'public'             => true,
   'show_ui'            => true,
   'show_in_menu'       => false,
   'show_in_nav_menus'  => false,
   'show_tagcloud'      => false,
   'show_in_quick_edit' => true,
   'show_admin_column'  => false,
   'show_in_rest'       => true,
   'hierarchical'       => false,
   'rewrite'            => self::taxonomy_rewrites( $key, $slug ),
   'sort'               => 'None',
);

### Steps to reproduce

this tax is create my Matador Jobs https://wordpress.org/plugins/matador-jobs/

install plugin
add a term to job categories
try to set the tax as a condition

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

n/a clients site

**Comment by nicholaszein** [comment]
Hey @pbearne, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

- Try setting all the arguments to true, and then reverting one by one until the option stops appearing.
- Make sure the taxonomy is registered to a publicly queriable post type.
- Make sure the post type related to the taxonomy in question is selected in your Dashboard > Elementor > Settings > General.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.
Best regards,

Nick

**Comment by zeinnicholas** [comment]
Hello there @pbearne,

any feedback on what I requested?

**Comment by pbearne** [comment]
The issue turned we had see the args to true for these options

			'show_in_menu'       => true,
			'show_in_nav_menus'  => true,

**Comment by nicholaszein** [comment]
Thank you for the feedback @pbearne! 🙏
