### ISSUE TITLE
⛔ 🐞 Bug Report: Shortcode as Dynamic Attributes executed 5 times

### ISSUE THREAD

**Issue by benni1516** [elementor/elementor#21281]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello,

when using a shortcode in the title tag or description of an icon box, the shortcode is executed 5 times.
I think this has to do with the dynamic attributes.

For example this shortcode, when loading the site once, it adds 5 to the counter, adding the shortcode through a normal shortcode tag only adds 1.

When I don’t add the shortcode through the dynamic attributes but just type [testcounter] in the title as text, is works as intended (only executes once).

```
function test_counter(){
    $fcvar = file_get_contents("test.txt");
    $fhandletxt = fopen("test.txt", "w");
    fwrite($fhandletxt, $fcvar + 1);
    fclose($fhandletxt);
    return $fcvar + 1;
}
add_shortcode('testcounter', 'test_counter');
```

### Steps to reproduce

1) Create Shortcode Counter
I provided the code for the counter.
2) Add an Elementor Element e.g. Icon Box
3) As Title or Description choose dynamic attribute shortcode and add the counter
4) Load page
5) 5 is added to the counter ( shortcode was executed 5 times )

### Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Server architecture | Linux 6.1.0-1-amd64 x86_64
Web server | Apache
PHP version | 8.0.27 (Supports 64bit values)
PHP SAPI | fpm-fcgi
PHP max input variables | 5000
PHP time limit | 300
PHP memory limit | 512M
Max input time | -1
Upload max filesize | 132M
PHP post max size | 132M
cURL version | 7.38.0 GnuTLS/3.3.30
Is SUHOSIN installed? | No
Is the Imagick library available? | Yes
Are pretty permalinks supported? | Yes
.htaccess rules | Custom rules have been added to your .htaccess file.

**Comment by nicholaszein** [comment]
Hello @benni1516,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
The code you're using is not correct. Please review your code, this is not how you safely edit a file programmatically, nor how you increment a value.
We cannot provide support for custom code like yours.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
