### ISSUE TITLE
⛔ 🐞 Bug Report: Icon widget causes brutal cumulative layout shift

### ISSUE THREAD

**Issue by lllopo** [elementor/elementor#21308]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Using the icon widget triggers a brutal cumulative layout shift when loading the page. Basically it actually look like a flash of unstyled content and the  most visible part of it are the giant black svg-s of the icons, which cause the CLS.

### Steps to reproduce

1. Add an icon widget with a FontAwesome svg icon.
2. Reload the page.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

WordPress 6.1.1
Hello Elementor 2.6.1

Elementor Experiments		
Optimized DOM Output: 	Active
Improved Asset Loading: 	Active
Improved CSS Loading: 	Active
Inline Font Icons: 	Active
Accessibility Improvements: 	Active
Additional Custom Breakpoints: 	Active
admin_menu_rearrangement: 	Inactive by default
Flexbox Container: 	Active
Upgrade Swiper Library: 	Inactive by default
Default to New Theme Builder: 	Active by default
Hello Theme Header & Footer: 	Inactive
Editor V2: 	Inactive by default
Landing Pages: 	Active by default
Nested Elements: 	Active
Lazy Load Background Images: 	Active
Save as Default: 	Active by default
Page Transitions: 	Active by default
Notes: 	Inactive
Loop: 	Active
Loop Carousel: 	Inactive by default
Form Submissions: 	Active by default
Scroll Snap: 	Active by default

**Comment by nicholaszein** [comment]
Hello @lllopo,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- You did not provide the complete information requested in our Bug Report form. We are missing crucial information like the complete System Info. Without it, we simply can't reproduce your issue.
- You are using a custom SVG, which may not be optimized for display. The custom SVG file you're using should be the same size (dimensions) you're trying to display it.
- This only happens when you combine and/or delay Elementor's CSS files. This can also happen if you try to generate Critical CSS. These features can affect the order and priority of CSS generation, causing some styles to take longer to load or be completely stripped from the default cascade. Icons in specific have a default value of 50 square pixels. The CLS only happens if you change how Elementor's CSS is distributed and rendered.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
