### ISSUE TITLE
⛔ 🐞 Bug Report: Loop Carousel DOM Elements!

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#21319]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi

Each Loop Carousel widget contains 300 DOM elements. Is this amount of DOM normal? I think it is not normal.

### Steps to reproduce

Measure the DOM Element size of each Loop Grid widget using the [DOM Size Analyzer](https://chrome.google.com/webstore/detail/dom-size-analyzer/mcneiimlodlbmohipgdbbglgbmaoojen) extention (Chrome plugin).

thanks

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

No need for system info

**Comment by mbaierl** [comment]
Did you compare it to a standard carousel widget? Would be interesting...

**Comment by Joliamendi** [comment]
Hi @mbaierl 

Sorry, I don't understand what you mean. Do you say it is normal, or the elementor has acted badly?

**Comment by mbaierl** [comment]
You talk about the Loop Carousel. How does that compare DOM-wise to a normal carousel? How about a plain Swiper widget? That would be interesting to know.

**Comment by nicholaszein** [comment]
Hello @Joliamendi,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
The number of DOM elements in a Loop Carousel will depend on how you build your Loop Item templates, and how many items appear in the carousel. I don't see how this can be considered a bug. It depends on how you optimize the template. It is expected some number of DOM elements will be created since you're using Elementor widgets.

Kind regards
