### ISSUE TITLE
⛔ 🐞 Bug Report: Mobile menu collapses on scroll at some resolutions

### ISSUE THREAD

**Issue by myralih** [elementor/elementor#21317]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I open the mobile menu in Safari on my iphone XR in landscape orientation and try to scroll down the menu collapses so nothing can be selected. My client has an iphone SE and is having the same problem even in portrait orientation.

I can't replicate the problem in the chrome dev tool so it may also not show up in other simulators.

### Steps to reproduce

1) go to https://www.aimeegiles.com/ on an iphone running safari
2) rotate the phone to landscape orientation so that the entire menu isn't visible
3) try to scroll down to the bottom of the menu

Menu will collapse before you can select a menu item.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.39-42
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www.aimeegiles.com
	Home URL: https://www.aimeegiles.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: aimee@aimeegiles.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Contact Form 7
		Version: 5.7.3
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.11.0
		Author: Elementor.com

	SiteGround Central
		Version: 2.0.9
		Author: SiteGround

	SiteGround Optimizer
		Version: 7.3.0
		Author: SiteGround

	SiteGround Security
		Version: 1.4.0
		Author: SiteGround

	Site Kit by Google
		Version: 1.93.0
		Author: Google

	Yoast SEO
		Version: 20.1
		Author: Team Yoast


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Hello Theme Header & Footer: Active by default
	Editor V2: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default


== Log ==
	
JS: showing 1 of 1JS: 2022-12-06 21:34:05 [error X 19][http://colind21.sg-host.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,shortcode,utils,jquery-core,jquery-migrate,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&loadchunk_1=ery-ui-core,jquery-ui-mouse,jquery-ui-sortable&ver=6.1.1:8:51824] Cannot read properties of undefined (reading \'replace\') 

PHP: showing 2 of 2PHP: 2022-12-16 18:14:40 [notice X 6][/home/customer/www/colind21.sg-host.com/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-10 14:22:47 [notice X 2][/home/customer/www/aimeegiles.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52023-02-13 12:54:58 [info] elementor::elementor_updater Started 
2023-02-13 12:54:58 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-13 12:54:58 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-13 12:54:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.11.0',
)]
2023-02-13 12:54:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.11.0',
)]



== Elementor - Compatibility Tag ==
	

				
````

</details>

**Comment by nicholaszein** [comment]
Hello @myralih! 

Thank you for submitting your issue! 🙏 

Can you please confirm which version of iOS are you using?

**Comment by myralih** [comment]
16.3
[image: pH7] <https://www.ph7design.com/> Hilary Duwe, Partner
ph7design.com <http://www.ph7design.com/> • 415.203.9245

**Comment by nicholaszein** [comment]
Hello @myralih,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
Currently, the option to scroll the submenu is not supported, so if you have a sticky header on the mobile landscape, you won't be able to scroll down.

### ✅ What you can do to solve your issue:
- Activate the additional breakpoints experiment in your Dashboard > Elementor > Settings > Features.
- Open your Header template in the Theme Builder, and navigate to the Site Settings.
- Go to Site Settings > Layout > Breakpoints and enable the "mobile landscape" breakpoint, then save and reload the editor.
- Click on the sticky section/container and remove the option to make it sticky on mobile landscape mode.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
