### ISSUE TITLE
⛔ 🐞 Bug Report: Save as Default in Loop Grid and Carousel also saves the selected template

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#21334]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If you use the save as default feature in the loop grid or loop carousel widget, the selected template will also be selected as the widget's default.

### Steps to reproduce

1. Add loop grid or loop carousel widget.
2. Choose or create a template for it.
3. Save the widget as default.

After that, if you add a loop grid or loop carousel widget, it will already have a template. **It would be much better if saving as default should not include template selection in these two widgets.**

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-domain.com-13-02-2023.txt](https://github.com/elementor/elementor/files/10732709/system-info-domain.com-13-02-2023.txt)

**Comment by 79ho3ein** [comment]
+1
This bug is also more widespread.

Hi @nicholaszein, save as default in the loop carousel widget, completely destroys the widget. To reproduce, please follow the steps below :

1- Add loop carousel widget.
2- In this widget, change the value of two options Gap between slides and Transition Duration (ms).
3- Then save the widget as default.
4- add the loop carousel widget again.

After you create the desired template, the carousel will not work. Even the pagination is not displayed! **In the video below, the Gap between slides option seems to have a problem with the save as default feature.**

https://user-images.githubusercontent.com/77163248/218995189-253a8354-cfa9-45fa-b10a-9edd0f34ab45.mp4

**Comment by nicholaszein** [comment]
Hi @79ho3ein,

Thank you for taking the time to record a video and explain your issue. I really appreciate it. 🙏 

However, we can't track two different issues in the same report.

Please submit a new Bug Report, as the issue you're reporting is not related to this report from Michael. What he is reporting here is not a bug.

Thanks 🙏

**Comment by nicholaszein** [comment]
Hi @Michaelgimii,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- This is the expected behavior of this feature. It saves every setting in the element as default, including anything in the content tab.
- This is not to be confused with Preset Styles. These are two different features. If you save a widget as default, it means everything, including the selected template.

### ✅ What you can do to solve your issue:
- If you want only to save Styles or maybe the default units for a specific widget, make sure you leave all the options in the Content tab of that widget empty or with their default value.

### 👍 For now, that's all we can help with. 

Kind regards
