### ISSUE TITLE
⛔ 🐞 Bug Report: Fatal error: Uncaught Error: Call to a member function get_config() on null

### ISSUE THREAD

**Issue by SalamThabet** [elementor/elementor#21349]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Fatal error: Uncaught Error: Call to a member function get_config() on null in /home/u675704732/domains/alarabinuk.com/public_html/wp-content/plugins/elementor/core/base/document.php:628 Stack trace: #0 /home/u675704732/domains/alarabinuk.com/public_html/wp-content/plugins/elementor/modules/library/documents/library-document.php(66): Elementor\Core\Base\Document->get_initial_config() #1 /home/u675704732/domains/alarabinuk.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(666): Elementor\Modules\Library\Documents\Library_Document->get_initial_config() #2 /home/u675704732/domains/alarabinuk.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1021): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_initial_config() #3 /home/u675704732/domains/alarabinuk.com/public_html/wp-content/plugins/elementor/core/editor/editor.php(383): Elementor\Controls_Stack->get_config() #4 /home/u675704732/domains/alarabinuk.com/public_html/wp-includes/class- in /home/u675704732/domains/alarabinuk.com/public_html/wp-content/plugins/elementor/core/base/document.php on line 628

### Steps to reproduce

I want to do some updates to the page that is building with Elementor!!
this error appeared!!
What's the solution? 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<html>
<body>

Operating System: | Linux |  
-- | -- | --
Software: | LiteSpeed |  
MySQL version: | MariaDB Server v10.5.15 |  
PHP Version: | 7.4.32 |  
PHP Memory Limit: | 3072M |  
PHP Max Input Vars: | 5000 |  
PHP Max Post Size: | 3072M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

</body>
</html>

**Comment by nicholaszein** [comment]
Hello @SalamThabet,

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 🧩 **Contact 3rd-party Support:** If the issue happens with an Elementor add-on, extension, compatible plugin, or integrated theme, contact their support first. We do not provide support for 3rd-party software.

- 💬 **Description:**In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our own environments. Be thorough.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Without them, we simply can't help. 😕 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Feel free to open a new issue in accordance with these guidelines. 😉 

Best regards,

Nick
