### ISSUE TITLE
⛔ 🐞 Bug Report: Problem creating loop for custom type post

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#21350]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I create a loop for a custom type post, I first place the resource on the desired custom post and then click the Create Template button. When we use dynamic content in the loop template, it displays the posts. While it should display custom post type posts.
If you look at the preview section of the loop template, it is set to posts. While it should be set on the desired custom type post. **Because before creating the template, we had set the source on the desired custom type post.**

### Steps to reproduce

1. First, make sure you have some default WordPress posts and some custom post type posts.
2. Add loop grid or loop carousel widget.
3. In the query section, put the source on the desired custom post type.
4. Click on the Create Template button.
5. After the loop template is loaded, add the dynamic image widget.

Here we see that the image is displayed from the default WordPress posts. **While it should have been displayed from the desired custom post type posts. Because in step 3, we had placed the source on the desired custom post type.**

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-domain.com-13-02-2023.txt](https://github.com/elementor/elementor/files/10742241/system-info-domain.com-13-02-2023.txt)

**Comment by nicholaszein** [comment]
Hi @Michaelgimii,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- By default, if not selected in the query before clicking to edit the template, Elementor will show the latest Post in the blog when you are editing the Loop Item template. But you can change this in the Document Settings.

### ✅ What you can do to solve your issue:
- When editing the Loop Item template, click the ⚙️ Gear icon in the Widget Panel, and select which posts to preview, as well as what to query. See the video below for more context:


https://user-images.githubusercontent.com/113993460/219396999-d0507882-018d-4de9-805d-f3605b246c09.mp4



### 👍 For now, that's all we can help with. 

Kind regards
