### ISSUE TITLE
⛔ 🐞 Bug Report: Search autofocus issue in popup

### ISSUE THREAD

**Issue by ijjimem** [elementor/elementor#21360]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Issue: Search input field is being automatically focused when the search overlay is opened on the frontend.

Cause: The toggleFullScreenSearch function in the Elementor search form widget's JavaScript code is setting the focus on the search input field when the overlay is opened.

Solution: Modify the code to prevent the focus from being set on the search input field. Specifically, remove or modify the toggleFullScreenSearch function to prevent the s.trigger("focus") call. This will prevent the focus from being set on the search input field when the overlay is opened.

### Steps to reproduce

1. Create a popup (popup as mobile menu for example)
2. Create a button to open this popup
2. Set a widget in the popup
3. Go to frontend and open the popup
4. See the autofocus on the input of the search

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Irrelevant.
Returning to version 3.10.3 fixes the issue.

**Comment by nicholaszein** [comment]
Hello @ijjimem,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is the expected behavior of the Search widget when the **Skin** is set to `Full Screen`. The idea is that once the person clicks on the search icon, they are ready to search, so the search field should be already selected and ready for user input.
This is specifically important for **<ins>Acessibility</ins>**, and we have no plans to remove or change this behavior.
- 

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
