### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor Editor keeps loading

### ISSUE THREAD

**Issue by TheSherpherdsCross** [elementor/elementor#21367]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor edit page is only loading and not able to update

### Steps to reproduce

Ensure you meet the [system requirements](https://elementor.com/help/requirements/). You can check if your system meets these requirements by going to Elementor > System Info. Two of the main things to check are the PHP version and memory limit, but also take note of any other items that might indicate a problem.
Increase your memory limit to 512M if using additional resource heavy plugins such as WooCommerce. This is the most common cause of loading issues. See below for a quick guide to increasing these or contact your hosting provider.
Make sure you are using the most updated versions of Elementor, Elementor Pro (if you are using that), WordPress and your theme. Sometimes it isn’t obvious that there is an update available. Go to Dashboard > Updates and click the Check Again button to be sure.
Deactivate all of your plugins except Elementor and Elementor Pro. If this solves the problem, reactivate each plugin one by one, until you spot the problematic plugin. If found, contact that plugin’s developers for help, or use a different plugin.
Switch your theme (temporarily) to a default WordPress theme such as Twenty Seventeen to see if your theme is causing an issue. If so, contact the theme’s developers for help, or use a different theme.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<html>
<body>

Operating System: | Linux |  
-- | -- | --
Software: | Apache |  
MySQL version: | MariaDB Server v10.4.17 |  
PHP Version: | 7.4.8 |  
PHP Memory Limit: | 128M |  
PHP Max Input Vars: | 8000 |  
PHP Max Post Size: | 20M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

</body>
</html>

**Comment by nicholaszein** [comment]
Hello @TheSherpherdsCross,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
The issue you're reporting is more related to your current installation, settings, plugins, and/or even your theme installed.

### ✅ What you can do to solve your issue:
Please follow this article to troubleshoot your issue: https://elementor.com/help/cant-edit-with-elementor/

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
