### ISSUE TITLE
❌ ⚠️ Support Request: https://roosadevelopment.com/listing/springville-ny-community-bank/

### ISSUE THREAD

**Issue by jroosa55** [elementor/elementor#21407]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The problem link:

https://roosadevelopment.com/listing/springville-ny-community-bank/

The link that it should look like:

https://roosacorp.com/listing/springville-ny-community-bank/

### Steps to reproduce

Go to www.roosacorp.com

Scroll down and click on any property 

This is what it should look like.

Now go to www.roosadevelopment.com

Scroll down and click on any property 

You will see the site loads with an error.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

I have provided the best information I can.

**Comment by vladninja** [comment]
@jroosa55 you have an error in a gallery section and error template was loaded instead of the normal one

**Comment by jroosa55** [comment]
VladNinja - Cool name by the way! Thank you for the feedback. I will have to figure try and figure out the gallery section and error template. Being a man of advanced years it takes some time to solve these puzzles. I appreciate your feedback and pointing me the right direction. Hope all is well and keep up the great work.

**Comment by nicholaszein** [comment]
Hey there, 

Thank you for submitting your report! 🙏 

This is more of a support question, not really something we can answer here.

Moreover... 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:


- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 🧩 **Contact 3rd-party Support:** If the issue happens with an Elementor add-on, extension, compatible plugin, or integrated theme, contact their support first. We do not provide support for 3rd-party software.

- ✒️ **Clear and concise title:** Please provide a clear and concise title that gives context to your issue.

- 💬 **Description:**In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our own environments. Be thorough.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache. 

Without them, we simply can't help. 😕 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.


❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind Regards
