### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: Template Export Import Error For invalid json.

### ISSUE THREAD

**Issue by mamunur105** [elementor/elementor#21403]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

When we save a template and export, then we cant import again. https://prnt.sc/Qj4XYwJC8vLi

I checked Your json file. Its really invlid json error . Check error here https://prnt.sc/HZSCemyLHYe2 this is the last text of the json file.

The missing is here: https://prnt.sc/y7fSeWzG7GF_

### Steps to reproduce

Just edit a elementor page And save as template Then export one to another website. Then you can see the error. 

You export your template as json and open in your editor . You will see the json really invlid. 
Look Like : https://prnt.sc/U17zsSEEtdIJ

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<html>
<body>

Version | 6.1.1
-- | --
Site Language | en_US
User Language | en_US
Timezone | +00:00
Home URL | http://shopbuilder.local
Site URL | http://shopbuilder.local
Permalink structure | /%postname%/
Is this site using HTTPS? | No
Is this a multisite? | No
Can anyone register on this site? | No
Is this site discouraging search engines? | Yes
Default comment status | Open
Environment type | local
User count | 1
Communication with WordPress.org | WordPress.org is reachable

</body>
</html>

<html>
<body>

Server architecture | Windows NT 10.0 AMD64
-- | --
Web server | nginx/1.16.0
PHP version | 8.0.22 (Supports 64bit values)
PHP SAPI | cgi-fcgi
PHP max input variables | 4000
PHP time limit | 1200
PHP memory limit | 256M
Max input time | 600
Upload max filesize | 300M
PHP post max size | 1000M
cURL version | 7.76.1 OpenSSL/1.1.1q
Is SUHOSIN installed? | No
Is the Imagick library available? | No
Are pretty permalinks supported? | Yes
.htaccess rules | Your .htaccess file contains only core WordPress features.

</body>
</html>

**Comment by nicholaszein** [comment]
Hey @mamunur105, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Best regards,

Nick

**Comment by nicholaszein** [comment]
Hi @mamunur105,

can you please provide the missing information?

Kind regards

**Comment by mamunur105** [comment]
https://prnt.sc/HZSCemyLHYe2 
just a `"}` Was missing the end of the generated JSON file but am not understand what the cause is.

But I am in another environment. I will knock again if I get the same issue. 

Basically, I am developing an additional with Elementor and WooCommerce. I create some demo in out live server. And save the template 	**Save as Template** And export it. But i can see every json file is not end  `"}` was missing. 
But at this moment i am out of my working environment that's why i cant send you more information. 

I will contact you again if fetch the same issue.

**Comment by mamunur105** [comment]
system info .

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.52 (Ubuntu)
	MySQL version: (Ubuntu) v8.0.32
	PHP Version: 7.4.29
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://radiustheme.net/rashid/shopbuilder
	Home URL: https://radiustheme.net/rashid/shopbuilder
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: techlabpro32@gmail.com
	Debug Mode: Active

== Theme ==
	Name: Metro Child Theme
	Version: 1.0
	Author: RadiusTheme
	Child Theme: Yes
	Parent Theme Name: Metro
	Parent Theme Version: 2.4
	Parent Theme Author: RadiusTheme

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.71
		Author: ServMask

	Elementor
		Version: 3.11.2
		Author: Elementor.com

	Metro Core
		Version: 1.7.3
		Author: RadiusTheme

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	RT Framework
		Version: 2.8
		Author: RadiusTheme

	ShopBuilder
		Version: 0.0.12
		Author: RadiusTheme

	Template Library and Redux Framework
		Version: 4.3.26
		Author: Extendify

	Variation Images Gallery for WooCommerce
		Version: 2.2.7
		Author: RadiusTheme

	Variation Images Gallery for WooCommerce Pro
		Version: 2.2.2
		Author: RadiusTheme

	Variation Swatches for WooCommerce
		Version: 2.3.5
		Author: RadiusTheme

	Variation Swatches for WooCommerce Pro
		Version: 2.2.1
		Author: RadiusTheme

	WooCommerce
		Version: 7.4.0
		Author: Automattic

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Editor V2: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default


== Log ==
	
JS: showing 6 of 6JS: 2023-02-06 08:39:20 [error X 12][https://radiustheme.net/rashid/shopbuilder/wp-content/plugins/elementor/assets/js/editor.js?ver=3.10.2:15336:22] Cannot read properties of undefined (reading 'html') 
JS: 2023-02-06 08:51:56 [error X 18][https://radiustheme.net/rashid/shopbuilder/wp-content/plugins/elementor/assets/js/editor.js?ver=3.10.2:32015:41] elementorFrontend.elements.window.jQuery is not a function 
JS: 2023-02-07 10:42:45 [error X 2][https://radiustheme.net/rashid/shopbuilder/wp-includes/js/jquery/jquery.js?ver=3.6.1:10692:36] Cannot read properties of null (reading 'clientHeight') 
JS: 2023-02-09 04:55:07 [error X 15][https://radiustheme.net/rashid/shopbuilder/wp-content/plugins/elementor/assets/js/frontend-modules.js?ver=3.10.2:575:31] Cannot read properties of undefined (reading 'attributes') 
JS: 2023-02-15 03:23:25 [error X 4][https://radiustheme.net/rashid/shopbuilder/wp-includes/js/jquery/jquery.js?ver=3.6.1:6621:14] Cannot read properties of undefined (reading 'replace') 
JS: 2023-02-22 09:32:59 [error X 7][https://radiustheme.net/rashid/shopbuilder/wp-content/plugins/elementor/assets/js/editor.js?ver=3.11.1:55412:44] Cannot read properties of null (reading 'getBoundingClientRect') 

Log: showing 10 of 102023-02-16 05:36:26 [info] elementor::elementor_updater Started 
2023-02-16 05:36:26 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-16 05:36:26 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-16 05:36:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.1',
)]
2023-02-16 05:36:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.1',
)]
2023-02-23 05:18:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.1',
  'to' => '3.11.2',
)]
2023-02-23 05:18:46 [info] elementor::elementor_updater Started 
2023-02-23 05:18:46 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-23 05:18:46 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-23 05:18:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.1',
  'to' => '3.11.2',
)]

PHP: showing 2 of 2PHP: 2023-02-17 06:14:05 [notice X 1][/var/www/radiustheme.net/public_html/rashid/shopbuilder/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-22 06:59:09 [error X 1][/var/www/radiustheme.net/public_html/rashid/shopbuilder/wp-content/plugins/elementor/includes/template-library/sources/local.php::1080] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /var/www/radiustheme.net/public_html/rashid/shopbuilder/wp-includes/class-wp-hook.php on line 310 and defined in /var/www/radiustheme.net/public_html/rashid/shopbuilder/wp-content/plugins/elementor/includes/template-library/sources/local.php:1080
Stack trace:
#0 /var/www/radiustheme.net/public_html/rashid/shopbuilder/wp-includes/class-wp-hook.php(310): Elementor\TemplateLibrary\Source_Local->on_save_post()
#1 /var/www/radiustheme.net/public_html/rashid/shopbuilder/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#2 /var/www/radiustheme.net/public_html/rashid/shopbuilder/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /var/www/radiustheme.net/public_html/rashid/shopbuilder/wp-includes/post.php(4717): do_action()
#4 /var/www/radiustheme.net/public_html/rashid/shopbuilder/wp-includes/post.php(4819): wp_insert_post()
#5 /var/www/radi [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @mamunur105,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

It seems that the theme you are using is causing the problem with the Import Kit feature. Contact the theme developer and ask them to fix the incompatibility.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
