### ISSUE TITLE
⛔ 🐞 Bug Report: Cannot set background image size per device. "Responsive Background Image Size" v3.11.x

### ISSUE THREAD

**Issue by datverse** [elementor/elementor#21450]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi in new version 3.11.x have "Responsive Background Image Size". This feature allow set background image size per device.
"Improving the performance of background images by enabling the user to choose the image size, per device".

But in my current Elementor (3.11.2) and Elementor Pro (3.11.2) I cannot do this.

### Steps to reproduce

1. Create a new page, edit it with Elementor and create a section or container.
2. Go to the Style tab, and choose an image as the background type.
3. Choice “Image Size” dropdown control.
=> Don't have select device.
Please view my screenshoot bellow
[https://ibb.co/QmcG8yT](https://ibb.co/QmcG8yT)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.19
	PHP Version: 8.2.1
	PHP Memory Limit: 64M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://my-domain.com
	Home URL: https://my-domain.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: admin@my-domain.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0

== Active Plugins ==
	Elementor
		Version: 3.11.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.2
		Author: Elementor.com

	WooCommerce
		Version: 7.4.0
		Author: Automattic


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor V2: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Mega Menu: Inactive by default

== Log ==

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==		

````
</details>

**Comment by doronwolf** [comment]
Hi @datverse the device selection dropdown is next to the 'image' title (meaning the device selection dropdown for the image is both for selecting the image and the image size together)

**Comment by nicholaszein** [comment]
Hello @XXX,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- As Doron correctly pointed out, this is not a bug. The functionality is there, just not where you're expecting. 

### ✅ What you can do to solve your issue:
- Select an image for the background. 
- A Select field with options to select the background image size will appear.
- To choose a different image size for responsive views, switch to the responsive view you want, and then select a different size.
The responsive controls for the image size are shared with the background image selector.


### 👍 For now, that's all we can help with.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
