### ISSUE TITLE
⛔ 🧩 🐞Bug Report: conflict with Theme Rex plugin

### ISSUE THREAD

**Issue by frabbi003** [elementor/elementor#21465]
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Uncaught Error: Call to undefined function trx_addons_get_the_ID()

### Steps to reproduce

I cannot use elementor editor

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.17
	PHP Version: 7.3.33
	PHP Memory Limit: 
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://rtobroker.com.au
	Home URL: https://rtobroker.com.au
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: educubebd@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Translogic
	Version: 1.2.2
	Author: ThemeREX
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	Contact Form 7
		Version: 5.7.4
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.11.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.2
		Author: Elementor.com

	MC4WP: Mailchimp for WordPress
		Version: 4.9.1
		Author: ibericode

	Really Simple SSL
		Version: 6.2.0
		Author: Really Simple Plugins

	Slider Revolution
		Version: 6.4.1
		Author: ThemePunch

	ThemeREX Addons
		Version: 1.6.09.1
		Author: ThemeREX

	WPBakery Page Builder
		Version: 6.6.0
		Author: Michael M - WPBakery.com

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elements Usage ==
	
	wp-page : 2
		button : 12
		call-to-action : 2
		heading : 14
		image : 3
		image-box : 6
		image-carousel : 1
		menu-anchor : 1
		testimonial-carousel : 1
		text-editor : 3

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Inactive by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Editor V2: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Mega Menu: Inactive by default

== Log ==
	
Log: showing 12 of 122023-02-24 17:44:12 [info] elementor::elementor_updater Started 
2023-02-24 17:44:12 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-24 17:44:12 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-24 17:44:12 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2023-02-24 17:44:12 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2023-02-24 17:44:12 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2023-02-24 17:44:12 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2023-02-24 17:44:12 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2023-02-24 17:44:12 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2023-02-24 17:44:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.1',
  'to' => '3.11.2',
)]
2023-02-24 17:44:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.1',
  'to' => '3.11.2',
)]
2023-02-24 17:44:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.2.1',
  'to' => '3.11.2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @frabbi003,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

👎 If after following these steps the problem persists, you can submit a new issue with details to reproduce it so we can take a look.

Otherwise contact the developers of the software affected.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support, especially 3rd-party themes and add-ons.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### Please next time before submitting your issue, check if there is a similar issue already posted. 

Regards
