### ISSUE TITLE
⛔ 🐞 Bug Report: Gallery not displaying until browser window is resized

### ISSUE THREAD

**Issue by MinaALord** [elementor/elementor#21471]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using the Elementor Pro Gallery in Masonry and Justified mode, the gallery wont display correctly upon loading the site. Only after the browser window is resized (e.g. once exiting and then entering full screen mode) the gallery will display fully. 

### Steps to reproduce

1) set gallery to masonry or justified
2) preview/load site in browser 
3) see how it is either only displaying a few or no images at all
4) resize the window by entering/ exiting full screen mode for instance 
5) now the images display correctly

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-www.minusgrad.de-26-02-2023.txt](https://github.com/elementor/elementor/files/10833972/system-info-www.minusgrad.de-26-02-2023.txt)

**Comment by nicholaszein** [comment]
Hello @MinaALord, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🆕 **Stay Up-to-date:** Make sure you are using the most recent and stable versions of [Elementor](https://wordpress.org/plugins/elementor/#developers), [Elementor Pro](https://elementor.com/pro/changelog/), [WordPress](https://wordpress.org/download/releases/), and your theme.

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache.

Without them, we simply can't help. 😕 

It seems you're running multiple 3rd-party add-ons, as well as a few Performance Optimization plugins. These can cause conflicts with how content is loaded, and should be the reason why you're not being able to load your galleries on the frontend.

There is also the issue that you're using the _**Elementor Beta (Developer Edition)**_ plugin on a production site. This is highly not recommended, since you're also running 3rd-party add-ons that may not be compatible with this unstable version. This plugin should only be used on staging environments by developers for testing purposes. It should never be used on production websites.

I did some tests and I could not reproduce your issue. Everything works fine here. Which means your issue is caused by something specific to your website. See the video below:


https://user-images.githubusercontent.com/113993460/221599417-6ac001d8-f188-43aa-bd9f-b5844c48321b.mp4



### Try the following procedures:

1. Uninstall the Elementor Beta (Developer Edition) plugin and [rollback](https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/) your Elementor Core plugin to version 3.11.2.
2. Update Elementor Pro to version 3.11.3 (latest version).
3. Disable the Lazy Loading on your Pro Gallery [settings](https://elementor.com/help/gallery-widget/).
4. Disable the "Upgrade Swiper Library" experiment on your WordPress Dashboard > Elementor > Settings > Feature page.
5. Temporarily deactivate all your performance optimization plugins and clear all types of cache, then check if the issue goes away. If it does, re-activate these plugins one-by-one until you find which one is causing the issue. Then either tweak the settings until the problem is fixed, or contact your performance optimization plugin developers.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
