### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: Conflic Elementor, Dynamic Link by Crocoblock and WeddingPress (Local Plugin in Indonesian)

### ISSUE THREAD

**Issue by ikhwanbreaks** [elementor/elementor#21491]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have problem conflict for Elementor, Dynamic Link and Wedding Press (Local Plugin in Indonesian).

I dont click for dynamic link in page. Example : https://unvid.my.id/add-undangan/
and the style is broken.

This is work only Guteberg, not Elementor.

Please help.

### Steps to reproduce

1. Active WeddingPress plugin
2. Create Dynamic Link in page
3. Publish
4. Preview is show plugin conflict

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.7.38
	PHP Version: 7.4.33
	PHP Memory Limit: 
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://unvid.my.id
	Home URL: https://unvid.my.id
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: id
	Timezone: 7
	Admin Email: admin@unvid.my.id
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: id_ID
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0

== Active Plugins ==
	Check Conflicts
		Version: 1.1.4
		Author: ioannup

	Elementor
		Version: 3.12.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Enable jQuery Migrate Helper
		Version: 1.3.0
		Author: The WordPress Team

	GoSMTP
		Version: 1.0.0
		Author: Softaculous Team

	JetEngine
		Version: 3.1.2
		Author: Crocoblock

	JetEngine - dynamic tables builder
		Version: 1.0.4
		Author: Crocoblock

	Loginizer
		Version: 1.7.7
		Author: Softaculous

	Simple Custom CSS and JS
		Version: 3.42
		Author: SilkyPress.com

	WeddingPress
		Version: 3.0.11
		Author: WeddingPress

== Must-Use Plugins ==
	mu-check-conflicts.php
		Version: 
		Author: 

== Eksperimen Elementor ==
	Output DOM yang Dioptimalkan: Aktif secara default
	Asset Loading telah ditingkatkan: Aktif
	Peningkatan Pemuatan CSS: Aktif
	Ikon Font Inline: Aktif secara default
	Peningkatan Aksesibilitas: Aktif
	Breakpoint Khusus Tambahan: Aktif secara default
	admin_menu_rearrangement: Tidak aktif secara default
	Flexbox Container: Aktif secara default
	Upgrade Swiper Library: Aktif
	Hello Theme Header & Footer: Aktif secara default
	Editor V2: Tidak aktif secara default
	Landing Page: Aktif secara default
	Nested Elements: Tidak aktif
	Lazy Load Background Images: Tidak aktif secara default
	Simpan sebagai Baku: Aktif

== Log ==
	
PHP: showing 1 of 1PHP: 2023-03-01 01:06:41 [notice X 1][/home/unvid/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52023-03-01 09:07:09 [info] elementor::elementor_updater Started 
2023-03-01 09:07:09 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-01 09:07:09 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-01 09:07:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.0-dev4',
)]
2023-03-01 09:07:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.0-dev4',
)]

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @ikhwanbreaks ,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes, plugins, add-ons, or extensions.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

👎 If after following these steps the problem persists, you can submit a new issue with details to reproduce it so we can take a look.

Regards
