### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor text editor styling issue

### ISSUE THREAD

**Issue by tasawar252** [elementor/elementor#21495]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have issue in the elementor text editor , elementor text editor apply styling like color and typography directly to the container not to the individual elements like p , h1 , h2 , h3 , h4 , h6. if theme or plugin have added css directly to these tag then elementor styling would not work .
like 
.elementor-text-editor {
color : 
font size etc
}

it would not be apply on h1-h6 and p tag  if they have directly styling from theme or plugin , 
 so styling must be 
.elementor-text-editor  *{
color : 
font size etc
}

### Steps to reproduce

1. install the elementor
2. install redux framework plugin 
3. Activate redux typo 
4. use elementor text editor 
5. you will see color and typo are not being applied on text editor because inline styling causing overriding of styling

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

Software: | Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/7.4.28 |  
MySQL version: | mariadb.org binary distribution v10.4.24 |  
PHP Version: | 7.4.28 |  
PHP Memory Limit: | 512M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 40M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

**Comment by nicholaszein** [comment]
Hello @tasawar252,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
That's the expected behavior. Elementor will apply the styles you add to the Text Editor widget in the styles tab only if you don't have other, more specific styles used. If you want to apply styles for heading tags (h1 to h6), and paragraph tags, go to the Site Settings > Typography and define your styles there.

Follow these articles: 

https://elementor.com/help/site-settings/

https://elementor.com/help/how-do-i-set-global-fonts-and-colors/

### 👍 For now, that's all we can help with. 

This is more of a Support Question, nothing we can help with from here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
