### ISSUE TITLE
⛔ 🐞 Bug Report: Text editor - The text is collapsing

### ISSUE THREAD

**Issue by Anders-Graitor** [elementor/elementor#21523]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Video of the problem: https://a.cl.ly/eDurAdWO

The text widget sometimes collapses the text, and other times it does not. Regardless, the text should look exactly like what you see when you view it without any changes. It should not collapse or create double spacing. Even if you use the Ctrl+C -> Ctrl+Shift+V shortcut to remove any kind of styling, the widget still collapses the text.

### Steps to reproduce

video: https://a.cl.ly/eDurAdWO

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 43, Revision c1b94a6cfd7 v5.7.40-43
	PHP Version: 7.4.33
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: #
	Home URL:  #
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 2048M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: da-DK
	Timezone: Europe/Copenhagen
	Admin Email:  #
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: da_DK
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.11.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.2
		Author: Elementor.com

	MainWP Child
		Version: 4.4
		Author: MainWP

	Temporary Login Without Password
		Version: 1.8.1.1
		Author: StoreApps

== Funktioner ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrationer ==
	
	recaptcha: Aktiv
	facebook_sdk: Aktiv

== Elementor Experiments ==
	Optimeret DOM-output: Inaktiv
	Forbedret ressourceindlæsning : Inaktiv
	Forbedret indlæsning af CSS ressourcer: Inaktiv
	Inline Font Icons: Inaktiv
	Forbedringer af tilgængeligheden: Inaktiv
	Additional Custom Breakpoints: Inaktiv
	admin_menu_rearrangement: Inaktiv som standard
	Flexbox Container: Inaktiv
	Upgrade Swiper Library: Inaktiv
	Default to New Theme Builder: Inaktiv
	Hello sidehoved og sidefod: Inaktiv
	Editor V2: Inaktiv som standard
	Landingsside: Inaktiv
	Nested Elements: Inaktiv
	Lazy Load baggrundsbilleder: Inaktiv
	Gem som standard: Inaktiv
	Page Transitions: Inaktiv
	Notes: Inaktiv
	Loop: Inaktiv
	Modtagne formularer: Inaktiv
	Scroll Snap: Inaktiv
	Mega Menu: Inaktiv som standard

== Log ==
	
Log: showing 20 of 402023-02-16 08:27:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.3',
  'to' => '3.11.1',
)]
2023-02-16 08:27:02 [info] elementor-pro::elementor_pro_updater Started 
2023-02-16 08:27:02 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-16 08:27:02 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-16 08:27:02 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-16 08:27:02 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-16 08:27:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.2',
  'to' => '3.11.1',
)]
2023-02-16 08:27:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.3',
  'to' => '3.11.1',
)]
2023-02-23 10:49:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.1',
  'to' => '3.11.2',
)]
2023-02-23 10:50:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.1',
  'to' => '3.11.2',
)]
2023-02-23 10:50:00 [info] elementor-pro::elementor_pro_updater Started 
2023-02-23 10:50:00 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-02-23 10:50:00 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-02-23 10:50:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.1',
  'to' => '3.11.2',
)]
2023-02-23 10:50:00 [info] elementor::elementor_updater Started 
2023-02-23 10:50:00 [info] Elementor/Upgrades - _on_each_version Start  
2023-02-23 10:50:00 [info] Elementor/Upgrades - _on_each_version Finished 
2023-02-23 10:50:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.1',
  'to' => '3.11.2',
)]
2023-02-23 10:50:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.1',
  'to' => '3.11.2',
)]
2023-02-23 10:50:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.1',
  'to' => '3.11.2',
)]

PHP: showing 1 of 1PHP: 2023-01-29 17:43:56 [notice X 1][/var/www #public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2023-01-30 07:46:56 [error X 1][https:// #/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.10.2:2:2932] elementor_new_template_form_controls is not defined 
JS: 2023-01-30 14:53:06 [error X 4][https:// #/wp-admin/load-scripts.php?c=0&amp;loadchunk_0=jquery-core,jquery-migrate,underscore,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&amp;loadchunk_1=hooks&amp;ver=6.1.1:2:51824] Cannot read properties of undefined (reading &#039;replace&#039;) 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatibel

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @Anders-Graitor,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is how the Classic editor (otherwise also known as TinyMCE editor) works, and it's how it has ever worked. Elementor uses the Classic editor for text editing in the Text widget and in many other widget content areas.

It uses this editor to maintain compatibility with WordPress Core and to reduce the need for 3rd-party dependencies. It also allows users to leverage other plugins that add functionality to the Classic editor/TinyMCE editor.

What happens is that every time you interact with this editor, it will run a sanitization process, when it tries to remove any unnecessary and potentially dangerous code. This means removing paragraph tags. Which is what you're referring to as "collapsing" content.

### ✅ What you can do to solve your issue:
You can use the [Advanced Editor Tools](https://wordpress.org/plugins/tinymce-advanced/) plugin, which will add extra functionality, including one called _"Keep paragraph tags"_, which will try to keep the P tags added to the text you write instead of removing them. This helps a lot, but it will depend on a case-to-case basis (meaning the content can influence if the tags are created or not, removed or not).

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
