### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor freezes when trying to edit a page with Elementor. 

### ISSUE THREAD

**Issue by Ruanc66** [elementor/elementor#21560]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have followed all the troubleshooting tips but Elementor still ends up non-responsive when I try to edit a page. What should I do?

### Steps to reproduce

Go to pages. Click on edit with Elementor. Elementor loading screen comes up and becomes unresponsive. I tried all the troubleshooting tips to no avail. I even tried to uninstall Elementor and tried a different theme.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-www.effectivelearning.co.za-06-03-2023.txt](https://github.com/elementor/elementor/files/10896084/system-info-www.effectivelearning.co.za-06-03-2023.txt)

**Comment by nicholaszein** [comment]
Hello @Ruanc66,

Thanks for contacting us! 🙏 

This is more of a support question, not something we can answer here.

It is likely your problem is related to your theme, or lack of resources in your server. Follow the article below to troubleshoot your issue:

https://elementor.com/help/cant-edit-with-elementor/

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards,

Nick
