### ISSUE TITLE
❌ 🐞 Bug Report: server error

### ISSUE THREAD

**Issue by Rehan321123** [elementor/elementor#21569]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Server error and no update option on elemetor free version

### Steps to reproduce

1) Server Error 2) no update option

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.38
	PHP Version: 8.0.28
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 2000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://channellettersbyus.com
	Home URL: https://channellettersbyus.com
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: Plain
	Language: en-US
	Timezone: 0
	Admin Email: admin@channellettersbyus.com
	Debug Mode: Inactive

== Theme ==
	Name: Customify
	Version: 0.4.0
	Author: WPCustomify
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

== Active Plugins ==
	BackWPup
		Version: 4.0.0
		Author: Inpsyde GmbH

	Breadcrumb NavXT
		Version: 7.2.0
		Author: John Havlik

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Customify Site Library
		Version: 0.0.9
		Author: WPCustomify

	Custom Sidebars
		Version: 3.36
		Author: WebFactory Ltd

	Elementor
		Version: 3.11.2
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Envira Gallery Lite
		Version: 1.8.5.3
		Author: Envira Gallery Team

	Floating Contact Button
		Version: 2.6
		Author: Christoph Nagel

	Smart Slider 3
		Version: 3.5.1.14
		Author: Nextend

	WPForms Lite
		Version: 1.8.0.2
		Author: WPForms

	WP Reset
		Version: 1.97
		Author: WebFactory Ltd

== Elements Usage ==
	
	section : 3
		heading : 4
		image : 4
	wp-page : 8
		heading : 8
		image : 8

== Settings ==
	
	cpt_support: post, page, e-landing-page
	allow_tracking: yes
	font_display: swap
	load_fa4_shim: yes

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Editor V2: Inactive by default
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Save as Default: Active

== Log ==
	
PHP: showing 1 of 1PHP: 2023-03-05 12:03:21 [warning X 24][/home/chanflpk/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2023-03-05 14:44:01 [error X 28][https://channellettersbyus.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.2:3:791668] Cannot read properties of undefined (reading 'localized') 
JS: 2023-03-06 20:05:00 [error X 1][https://channellettersbyus.com/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils&ver=6.1.1:2:31703] elementor_new_template_form_controls is not defined 

== Elementor - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hey @Rehan321123, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🔍 **Search Before Posting:** Before creating a new Bug Report, please [search for similar issues](https://github.com/elementor/elementor/issues/) to prevent creating duplicates.

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 🧩 **Contact 3rd-party Support:** If the issue happens with an Elementor add-on, extension, compatible plugin, or integrated theme, contact their support first. We do not provide support for 3rd-party software.

- ✒️ **Clear and concise title:** Please provide a clear and concise title that gives context to your issue.

- 💬 **Description:**In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our own environments. Be thorough.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache.

Without them, we simply can't help. 😕 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Feel free to open a new issue in accordance with these guidelines. 😉 

Best regards,

Nick
