### ISSUE TITLE
❌ 🐞 Bug Report: Multiple form on a page causes error in elementor pro 3.11+

### ISSUE THREAD

**Issue by delharris1981** [elementor/elementor#21613]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

when creating multiple forms on elementor pro, inside the same page, there is an error when trying to send the forms (not the first form, this sends fine, it is from form 2 and onwards). "there's something wrong. the form is invalid"

### Steps to reproduce

1. create a page
2. create a form (this one works fine)
3. create a secon form
4. save and preview the page
5. on the second form try sending it
6. you will see the "there's something wrong. the form is invalid"

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Server Environment		
Operating System:	Linux	
Software:	Apache/2.4.51 (Unix)	
MySQL version:	(LTD BeGet) v5.7.21-20	
PHP Version:	7.4.33	
PHP Memory Limit:	268435456	
PHP Max Input Vars:	10000	
PHP Max Post Size:	1047527424	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	6.1.1

**Comment by nicholaszein** [comment]
Hello @delharris1981, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 🧩 **Contact 3rd-party Support:** If the issue happens with an Elementor add-on, extension, compatible plugin, or integrated theme, contact their support first. We do not provide support for 3rd-party software.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Best regards,

Nick

**Comment by daniel-layers** [comment]
I have also ran into this issue and can replicate with the above steps, not sure why it was flagged to provide missing information as all the information requested is in the original post.

**Comment by nicholaszein** [comment]
Hello there,

Thank you for your patience! 🙏 

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the essential **<ins>System Info</ins>** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.   

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- While testing the feature reported with the latest version of both Elementor and Elementor Pro, multiple forms on the same page, worked as expected. See the video below:


https://github.com/elementor/elementor/assets/113993460/5f571542-a626-43d7-a3af-8f02fe2dcb5c



### ✅ What you can do to solve your issue:
- Update to the latest version (3.14.1 for both Elementor and Elementor Pro as of today).
- Make sure your forms are properly configured and valid. Follow the instructions [here](https://elementor.com/academy/forms-collection-2/).
- Make sure all of your add-ons are updated and compatible.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor after following the troubleshooting steps above, feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
