### ISSUE TITLE
⛔ 🐞 Bug Report: Add link to a Container issues

### ISSUE THREAD

**Issue by Pablo-Ibar** [elementor/elementor#21611]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have a problem, when I try to place a link in a container, I get a notification that says, Do not add links to elements nested in this container - it will break the layout. (and it does it)

![334766402_1494611711066689_5798041871751739348_n](https://user-images.githubusercontent.com/127416439/224053827-a38b8916-7a7e-4cdb-a8ab-b14b4e482ab7.jpg)

### Steps to reproduce

try to place a link in a container

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-serviciostesteo.ml-09-03-2023.txt](https://github.com/elementor/elementor/files/10932548/system-info-serviciostesteo.ml-09-03-2023.txt)

**Comment by nicholaszein** [comment]
Hello @Pablo-Ibar,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- You can't add links inside links in HTML. That's invalid markup. We do not support links inside containers with links.

### ✅ What you can do to solve your issue:
- Remove the link from the elements inside the container and the issue should be resolved.
- For more information please read the documentation: https://elementor.com/help/what-is-a-container/

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
