### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor Anchor text BUG HURTS SEO

### ISSUE THREAD

**Issue by pwnoobz** [elementor/elementor#21663]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Trying to create an anchor with Elementor hurts SEO. Here's why.
Anchors to the same page should follow the URL structure: `https://******.com/page#ANCHOR`

Instead - entering the URL in Elementor "list widget," or any other widget "button" for example, creates a sub-page instead of an anchor:

`https://******.com/page/#ANCHOR`

Yes, the link works and goes to the right place. The problem is SEO related. Long term this hurts the website making the search engines think that /#anchor is a subpage. _The problem is that **/#anchor** is not the same as **#anchor**, and it hurts SEO._

### Steps to reproduce

1. Set up a clean copy of the latest version of WordPress
2. Install Elementor/Elementor pro
3. Create an anchor that leads to an ID on the same page

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

I payed attention to the bug for the first time with Elementor v3.10.1, and it consistently happens with all the new versions.

**Comment by m1ga** [comment]
How do you set your anchor link? I use it this way: 
* create an anchor widget and give it an ID 
* create a button
* add `#anchor` in the link

and I only see `href="#anchor"` in the button, not `/#anchor`

**Comment by pwnoobz** [comment]
Try using a list widget and create it like this:
https://includeyourwebsitename.tld/page#pagesection

Sometimes you'll want to guide the user to a section on another page.

I also create links with just #pagesection by the way, tried it on multiple websites just with Elementor on. Please check what happens on your end. Look carefully in the left angle of the browser to where the link goes. The Elementor plugin adds "/"

**Comment by m1ga** [comment]
Define "list widget" please. This one: https://elementor.com/help/icon-list-widget/ ?

**Comment by pwnoobz** [comment]
You are absolutely correct! I'm so sorry for the trouble.

**Comment by m1ga** [comment]
@pwnoobz no problem! Didn't know that before too but I didn't have that issue that's why I quickly looked it up what the difference was :smile:

**Comment by nicholaszein** [comment]
Hello @pwnoobz,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- @m1ga was kind enough to already point out the error. Thank you!

### 👍 For now, that's all we can help with. 

Note that this is more of a Support question, and something we cannot answer from here. In the future, please ask your question in the community or Elementor support. Thanks.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
