### ISSUE TITLE
⛔ 🐞 Bug Report: Image Carousel wont work inside Loop Carousel

### ISSUE THREAD

**Issue by ckienquoc** [elementor/elementor#21687]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When place Image Carousel inside Loop Carousel
the navigation arrows of  Image Carousel wont work properly. The arrow events seem overwrite by Loop Carousel navigation arrows 
 

### Steps to reproduce

1. Create a loop template (loop_tmp) with Image carousel (post image attachments) placed inside.
2. On home page create create a loop carousel which using loop_tmp

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-ngxdavu.vn-19-03-2023.txt](https://github.com/elementor/elementor/files/11010397/system-info-ngxdavu.vn-19-03-2023.txt)

**Comment by nicholaszein** [comment]
Hello @ckienquoc,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- This feature is currently not supported. 

### ✅ What you can do to solve your issue:
- If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

### 👍 For now, that's all we can help with. 

Kind regards
