### ISSUE TITLE
⛔ 🐞 Bug Report: nested tabs issue in editor

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#21755]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor team

If we add nested tabs in the widget editor, when the mouse is placed on this widget, due to the display of [this line](https://prnt.sc/a0GCiYT3ZETe), the container border of this widget will be thicker than the parent container. See the image below.

![1](https://user-images.githubusercontent.com/88034902/227524061-e0d3fe0d-a8fa-4e3d-807f-d0bd78469113.png)

So it would be great if you could fix this. so that when hovering over this widget, the border of the inner container does not look thick. The image below is something that would be great. In the image below, if you see the thickness of the two edges of the container at the bottom, they are equal.

![nice](https://user-images.githubusercontent.com/88034902/227524436-384f4b88-23f1-4cd1-941f-9ee60e724891.jpg)

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

System information will not help.

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
Active Elements, or in other words, elements that are currently in focus, will have a thicker overlay border to indicate they are currently being edited. This is the expected behavior, and we will maintain this to help users easily identify which element is currently being edited.

### 👍 For now, that's all we can help with. 

Kind regards
