### ISSUE TITLE
⛔ 📊 🐞 Bug Report: Image widget CSS class is not added to the <img> node

### ISSUE THREAD

**Issue by gregbenz** [elementor/elementor#21799]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using "CSS Classes" for an image widget, the class is not added to the <img> node, it gets added to a parent element. As a result, you cannot directly target the image. For example, you can not add the "skip-lazy" class to direct Jetpack to avoid lazy loading a specific image.

### Steps to reproduce

Add an image widget and set the "CSS Classes"

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

n/a, this is unrelated to specifics of my installation

**Comment by nicholaszein** [comment]
Hi, @gregbenz,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

By default, adding classes to any widgets will apply the class to the widget wrapper, not to their child components.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
