### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Management of Elements (Duplicate)

### ISSUE THREAD

**Issue by ianstudio** [elementor/elementor#2184]
FOLDING
With the advent of third party Elements especially it would be nice **being able to fold a section**, just like for example we could fold PRO ELEMENTS and so on.

DEACTIVATION
Livemesh Elementor Addons for example (https://www.livemeshthemes.com/products/elementor-addons) allows to deactivate elements.. which I guess could be a "required" best practice for all 3rd parties? But what for those who do not propose that.. would there  be any way for Elementor to register all activated Elements and **give the option to deactivate them directly from the toolbox**? They could then appear in a DEACTIVATED TAB alongside ELEMENTS & GLOBAL.

FAVORITES
Along the same line as above, would be great to be able to turn certain Elements into FAVORITES either by moving them to a new FAVORITES tab or to a section at the top... **and even being able to save a configuration to only show those favorites to certain user roles..** so that people preparing sites for clients do not overwhelm then and only give them tools they actually need.

There, my 2 cents for the day :0)

**Comment by l3enito** [comment]
There should be definitely a way to show an editor only the widgets needed for a specific website. A client -who wants to edit content - gets confused by the amount of possibilities.

**Comment by JuTu83** [comment]
+1

**Comment by pb52** [comment]
+1

**Comment by thomasmalley** [comment]
+1

**Comment by black-eye** [comment]
+1

**Comment by mcinaz** [comment]
+1

**Comment by mcinaz** [comment]
+1

**Comment by arielk** [comment]
ref: https://github.com/elementor/elementor/issues/2184

**Comment by DorShahar** [comment]
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!

**Comment by pb52** [comment]
I've just tried 3.5.0 on a staging site.  

1. Although I can add favourite by right clicking, the choices aren't remembered when you move to another page. 
2. If I define new favourites I am then prompted to update the page
3. If I then refresh the page the favourites are discarded
4. If you mark a global widget as a favourite, any custom name you've previously given it is discarded and the default names is used.

The function does not work.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

It's been a while now, but...

### 📢 We're happy to announce that this feature was released with Elementor Core v3.18.0! 🥳 

Elementor now comes with the Element Manager feature, that allows you to control which widgets are loaded in the editor! 

You can learn more about it in the Help Center article:
https://elementor.com/help/element-manager/

As for "folding widgets", since version 3.15.0 there is now a new version of the Accordion widget which allows you to add any widget inside as part of our new Nested Elements.

Favorites was introduced in version 3.5.0.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
