### ISSUE TITLE
⛔ 🐞 Bug Report: save as default is not active for nested elements.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#21856]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Not sure if this is a bug or not. But we cannot use the save as default feature in nested elements. While it can be very useful.

### Steps to reproduce

If you add Tabs and Mega Menu widgets, there is no save as default option for them.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

can't help

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- This is by design and is not a feature available for Nested Elements at this time.

### ✅ What you can do to solve your issue:
- We have plans for adding this feature in the future, but not for the time being.
- You can submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request) so other users can vote for it.

### 👍 For now, that's all we can help with. 

Kind regards
