### ISSUE TITLE
⛔ 🐞 Bug Report: Remove extra text from templates and pages.

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#21865]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi

When we create a template or page, texts are displayed that really do not need to exist. For example, page name, site title and "Content Area" appear on pages.

![1](https://user-images.githubusercontent.com/103376243/228936343-6b6e1568-8a32-41a1-aa4e-45c57d95f908.png)

### Steps to reproduce

It would be great if you could remove these texts from pages and templates. Because there is really no need to show them.

### An important point

Since top bar has been added in the new version, there is no need for the **Hide Title** option in the page settings. Because the name of the page is displayed in the top bar. Therefore, it is better to remove the Hide Title option or disable it by default.

thanks

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

-

**Comment by nicholaszein** [comment]
Hello @Joliamendi,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- What you are seeing is the layout of the theme as it is. We have no plans to remove theme parts from documents.

### ✅ What you can do to solve your issue:
- You can override this behavior by switching the `Hide Title` control in the `Document Settings` (⚙️) > `General Settings`;
- You can also override this behavior by simply changing the `Page Template` in the `Document Settings` (⚙️), and selecting either `Elementor Canvas`, or `Elementor Full Width`;
- You can also go to the `Site Settings` (🎚️) > `Layout` and switch the `Default Page Layout` to either `Elementor Canvas`, or `Elementor Full Width`.

Kind regards
