### ISSUE TITLE
❌ Bug with large help button---

### ISSUE THREAD

**Issue by fatrabbitnetwork** [elementor/elementor#21877]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The help button is huge and wont let me save a new template and causing a major issue- it just started I am working on chrome.won't

### Steps to reproduce

login into wordpress- click visit site- 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

wordpress- elementor pro

**Comment by fatrabbitnetwork** [comment]
![Screenshot 2023-03-31 142321](https://user-images.githubusercontent.com/67726264/229207276-8f7c8d24-bba2-408f-bb64-3f8bb6f6dada.png)
![Screenshot 2023-03-31 122949](https://user-images.githubusercontent.com/67726264/229207293-14ea697b-8aa9-4e57-9d17-88f4589a0db7.png)

**Comment by nicholaszein** [comment]
Hello @fatrabbitnetwork , 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🆕 **Stay Up-to-date:** Make sure you are using the most recent and stable versions of [Elementor](https://wordpress.org/plugins/elementor/#developers), [Elementor Pro](https://elementor.com/pro/changelog/), [WordPress](https://wordpress.org/download/releases/), and your theme.

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 🧩 **Contact 3rd-party Support:** If the issue happens with an Elementor add-on, extension, compatible plugin, or integrated theme, contact their support first. We do not provide support for 3rd-party software.

- ✒️ **Clear and concise title:** Please provide a clear and concise title that gives context to your issue.

- 💬 **Description:**In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our own environments. Be thorough.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache.

Without them, we simply can't help. 😕 

### Aditional information:

1. Your issue is most likely caused by a cache conflict. Clear all types of cache, including Server, Site, Browser, and CDN.
2. You are using the Elementor Developer Edition plugin, which is not intended to be used on production websites. It should only be used by developers to test their add-ons for compatibility purposes. This plugin is unstable and might not work as expected.

Kind regards
