### ISSUE TITLE
✅ 🚀 Feature Request: New Widget: "Content" carousel

### ISSUE THREAD

**Issue by luizbills** [elementor/elementor#219]
A carousel with content (image, text, column... any widget), instead of just images.

**Comment by Luxamman** [comment]
Would love to get that too - like the "image box" in a carousel. for now i need to use third-party widgets (Livemesh Posts Carousel), and cannot config the widget witch category to use... config is not shown in elementor widget config

**Comment by nesoor** [comment]
I would also like a carousel that lets me add a photo, text, button and a link.
I have one website that only needs a carousel with each image a different link and one website that needs an image, text, button and a link.

**Comment by kelvinlamyou** [comment]
+1 on this - have been trying different options in the market they still do not seem to be satisfactory. Really hope that it can be added to Elementor Pro soon

**Comment by raphaelfiga** [comment]
+1 
More important than elements we choose the ability to load dynamic posts based on custom queries.

**Comment by ipokkel** [comment]
+1

**Comment by JoeDarko** [comment]
Is there any update on a post slider/carousel? 

With posts widget, single and archive builder it is now possible to build a nice magazine theme with Elementor. Except there is still no posts slider/carousel widget. :-/ 

I would say this widget should be a no-brainer. Lot of people would use it.  It seems you are adding plenty of great advanced niche features, but sometimes the most basic stuff is forgotten.

**Comment by muchadesign** [comment]
+1 

I need to be able to either put an image within a "Slides" widget (i.e. NOT a background image)
- OR -
I need to be able to add Title, text, link in an "Image Carousel" widget

**Comment by black-eye** [comment]
+1

**Comment by bentalgad** [comment]
Dynamic content slider is the most important feature this slider should have!

**Comment by cjmetacrawler** [comment]
still has no updates for this one?

**Comment by utsavmadaan823** [comment]
Any updates on this, post slider/carousel ?

**Comment by JoeDarko** [comment]
Please, give us a posts carousel/slider already. It's been years since first requested. :( This is one of those things that should almost be available from the beginning, yet after years and many other niche functions, this basic feature is still not available. 

Just like normal slider with some extra features:

- choose query - category or latest posts
- choose data it displays - post title, date, categories
- choose number of posts
- few styling options

**Comment by reemadsouza** [comment]
@arielk 

This feature request is open since 2016 and still not looked into.

Can we just not add a Heading Input field and a Text Editor field to Media Carousel or just a Text Editor field 
**OR** 
Give a width option to Slides widget, so that it can be used as a carousel or full slider.

I feel Elementor is avoiding simple feature request and going in for bigger, newer features. Content carousel is so common these days and to use another plugin having PRO version is such a waste of our money 😞 

Please can you look into this simple request

**Comment by Fanny8p** [comment]
+1

**Comment by black-eye** [comment]
Oh, my, this is simply insane! 
You have 4 different types of carousels (image, media, testimonial, review) and one slider (using different slider framework), but I'm unable to make a carousel with a simple text, not to say with a random column-like content! After almost 3 years! Oh Elementor, there are things I simply don't understand!

**Comment by elasticeye** [comment]
+1 for this very important feature.

**Comment by MichaelDarko** [comment]
Post slider/carousel is desperately needed!

I think Elementor is totally missing the oportunity to become the ultimate solution for building online magazine/blog website.

I was just browsing magazine themes on ThemeForest and realized that Elementor could make all of the themes obsolete by providing the basic building blocks for any magazine/blog website.

Every single magazine theme has some sort of post slider/carousel or post tiles in the top section.

Why can't this be done with Elementor? You can't build a nice magazine website just with the posts widget. 

The developers should look at [JetBlog](https://jetblog.zemez.io/). It's great, but why is something like this not implemented in Elementor Pro? 

WordPress is used for millions of magazine/blog websites and Elementor should strive to be the go to tool to build your own online magazine.

To build a magazine you pretty much only need this:

Post tiles (Like JetBlog) (X)
Post slider / carousel (X)
Posts widget (✓)
Archive builder (✓)
Single builder (✓)

With enough styling options you would be able to recreate any magazine/blog theme. And that would make Elementor so much more powerful.

So please, make Elementor useful for building an online magazine and give us post tiles widget and post slider / carousel widget.

**Comment by davidofug** [comment]
Isn't this feature still out? Let me go to support and find out why.

**Comment by sproutedweb** [comment]
## Your ticket has been created. ##


Ticket subject: Re: [elementor/elementor] New Widget: &quot;Content&quot; carousel (#219)


----
Author: David Wampamba 
Date: Tue, 05/14/19 1:28 am
Message:
Isn&#x27;t this feature still out? Let me go to support and find out why.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/elementor/elementor/issues/219#issuecomment-492131819



Powered by https://www.livechatinc.com/powered-by-livechat/?utm_source=ticket_footer&utm_medium=email&utm_campaign=lc_10152642"

**Comment by bentalgad** [comment]
It's funny that you have for dynamic content in every field separately instead of just having the option to add dynamic fields any where just like in beaver builder which lets you add it even inside text and even multiple dynamic content's in one field. a lot of posts on how to do fancy effects but basic features are still missing from the beginning of this plugin.

**Comment by sarahiwata** [comment]
The rep i was chatting with in Elementor asked me to submit a feature request. It's not exactly the same as the other requests on this thread but maybe similar enough to add here...? I desperately want a text overlay that is static over the image carousel (preferably responsive for mobile), not text that rotates within the carousel as a slide but that doesn't change with the images and is an overlay. Seems simple but the rep told me there is nothing like this available.

**Comment by reemadsouza** [comment]
@sarahiwata 
> The rep i was chatting with in Elementor asked me to submit a feature request. It's not exactly the same as the other requests on this thread but maybe similar enough to add here...? I desperately want a text overlay that is static over the image carousel (preferably responsive for mobile), not text that rotates within the carousel as a slide but that doesn't change with the images and is an overlay. Seems simple but the rep told me there is nothing like this available.

Did you try adding a Heading Widget(after slider) -> Setting the Custom Positioning to Absolute(might need to add some z-index) and simply drag over the slider wherever you want to position it, it wont change with the slider images. Hope it helps

**Comment by d7o1d1s0** [comment]
Genuinely amazed this has been an issue for this long. Paid for the pro version just today trying to achieve exactly this and assumed I was missing something obvious, turns out this basic feature has been missing and repeatedly requested for 4 years with no progress. I'll be trying to get a refund and looking into alternative page builders.

**Comment by srack835** [comment]
+1 dynamic content for sliders, please!

**Comment by walnut331** [comment]
+1

**Comment by levatc** [comment]
+1

**Comment by geshem** [comment]
+1

**Comment by tdechangy** [comment]
+1

**Comment by Deralict** [comment]
+1

**Comment by kyd9x** [comment]
Almost 4 years later and still no word from Elementor...?

**Comment by StillReady** [comment]
> 
> 
> Oh, my, this is simply insane!
> You have 4 different types of carousels (image, media, testimonial, review) and one slider (using different slider framework), but I'm unable to make a carousel with a simple text, not to say with a random column-like content! After almost 3 years! Oh Elementor, there are things I simply don't understand!

Yes and the sad part is. You would have all types of these slides combined with just a "content slider". I had to figure it out today the hard way. I'm only using Elementor Pro since a few weeks. I couldn't belive that there isn't a simple content slider...

**Comment by black-eye** [comment]
@StillReady 
> > Oh, my, this is simply insane!
> > You have 4 different types of carousels (image, media, testimonial, review) and one slider (using different slider framework), but I'm unable to make a carousel with a simple text, not to say with a random column-like content! After almost 3 years! Oh Elementor, there are things I simply don't understand!
> 
> Yes and the sad part is you would have all types of these slides combined with just a "content slider". I had to figure it out today the hard way. I'm only using Elementor Pro since a few weeks. I couldn't belive that there isn't a simple content slider...

Oh yes, sad. And my quote, you cited, is one year older now! BTW, this issue is literally the oldest open issue on Elementor GitHub. Almost 4 years! Which makes it (at the same time) the longest issue with no reaction from the devs (except closing other issues in favour of this one).

Welcome to the fabulous world of Elementor, the best page builder in the world! Best page builder without the ability to make a slider/carousel with your custom content. And to save you some more figuring out - the same goes with tabs and toggles (and any other content-related widget).

**Comment by folusuk** [comment]
I have Submitted a Support ticket on there website, asking them to reply and possibly solve it, lets see shall we.

**Comment by Heislitz** [comment]
I too would like to know why this still hasn´t gone into the passed versions yet. 
4 Years is definitely a long time to create such a little feature. Any Word from the Elementor Team or any alternative get a post slider or even better - a slider that can handle any content (HTML, Widget...)?

**Comment by StillReady** [comment]
> 
> 
> I too would like to know why this still hasn´t gone into the passed versions yet.
> 4 Years is definitely a long time to create such a little feature. Any word from the Elementor Team or any alternative how to get a slider with post - or even better - a slider that can handle any content (HTML, Widget...)?

I actually think it's on purpose.

There must be at least a reasonable reason for it. It might contradict some additional paid addon for that plugin or sth. in that regard. So the reason would be, that they would lose money by giving us that widget. That's my guess.

The other reason is that far too few people seem to be complaining about this particular (and really easy to fix) problem. We can just be ignored and they will be fine. And that's a shame. It would be a very usefull addition to Elementor.

Besides that Elementor should implement the possibility to create templates for WordPress login, registration, WooCommerce my account pages etc. It would be a huge feature. Which I think their marketing could imply.

All in all Elementor (Pro) is a great plugin and got way better with 3.0 but there still many thing to improve – like the "content carousel". But instead we got image, video, blurb carousel and so on...

The best you can do to get a content carousel, is to build your own (with HTML, CSS and JS)...

**Comment by rodolphebertozzo** [comment]
+1

**Comment by jgajera** [comment]
+1 & Pro user - why has this issue been open for so long and still no updates from the Elementor team?

**Comment by Heislitz** [comment]
Hello Everybody, 

since we were fed up with waiting for this issue to be solved and as a webdevelopment company ourselfes, 
we have some good news for the whole Elementor-Community:

We startet to create an advanced version of the slider and portfolio widget that is in Elementor Pro - and are almost done with the development of these missing features. So look into this thread aging, i´ll announce the release as soon as it ist done and tested.

So far the feature set of the first release will be:

All standard functions will be kept, the new features on top are:


## For the Advanced Slider
Choose Image, Post, Page as Source for each Slide
- Option to overwrite title of the source, so you can show a custom Title and a description (HTML-Tags possible)
- Choose if the link works on the whole item or on the button only

Choose Modal Content Type
- Default (no modal pop-up)
- Image (using featured image in a modal pop-up)
- iFrame (using the full content in a pop-up*) 

*Here you best use the "Elemetor Canvas" as template in the post or page, 
to only show its content without the header and footer parts)



## For the Advanced Portfolio
Choose Image, Post, Page as Source

Option to turn on Light-Box 
- Option to open the featured image in a modal pop-up window by a custom category**
- Option to open the whole post/page in a modal pop-up window by a custom category**
- Turn on/of the "show all" filter in the filter bar

**A category can be set for the content that has to be opened in a modal window for the most flexibility
  (Hint: Use a taxonomy plugin for pages for now, to give pages a category as well!)


I hope you will like it ;-)

Cheers,
Marc Heislitz

**Comment by ux4real** [comment]
> Hello Everybody,
> 
> since we were fed up with waiting for this issue to be solved and as a webdevelopment company ourselfes,
> we have some good news for the whole Elementor-Community:
> 
> We startet to create an advanced version of the slider and portfolio widget that is in Elementor Pro - and are almost done with the development of these missing features. So look into this thread again, i´ll announce the release as soon as it ist done and tested.
> 
> So far the feature set of the first release will be:
> 
> All standard functions will be kept, the new features on top are:
> 
> ## For the Advanced Slider
> Choose Image, Post, Page as Source for each Slide
> 
> * Option to overwrite title of the source, so you can show a custom Title and a description (HTML-Tags possible)
> * Choose if the link works on the whole item or on the button only
> 
> Choose Modal Content Type
> 
> * Default (no modal pop-up)
> * Image (using featured image in a modal pop-up)
> * iFrame (using the full content in a pop-up*)
> 
> *Here you best use the "Elemetor Canvas" as template in the post or page,
> to only show its content without the header and footer parts)
> 
> ## For the Advanced Portfolio
> Choose Image, Post, Page as Source
> 
> Option to turn on Light-Box
> 
> * Option to open the featured image in a modal pop-up window by a custom category**
> * Option to open the whole post/page in a modal pop-up window by a custom category**
> * Turn on/of the "show all" filter in the filter bar
> 
> **A category can be set for the content that has to be opened in a modal window for the most flexibility
> (Hint: Use a taxonomy plugin for pages for now, to give pages a category as well!)
> 
> I hope you will like it ;-)
> 
> Cheers,
> Marc Heislitz

Hi Marc! Any updates?

**Comment by fabianenzensperger** [comment]
Lilalub. Tadadadaaa. Waiting. Tüüüt. tüüüüüüüt. … 4 Years, Elementor, 4 YEARS!

**Comment by iMiek** [comment]
+1

**Comment by DoJoMast3r** [comment]
Why. Has this been taking so long!! The community update seams to have never been released, not sure why elementor hasnt atleast responded to this very old issue thats so simple to resolve.

**Comment by 79ho3ein** [comment]
+1 This is a great feature needed. I hope it will be added to elementor soon. It's been 4 years now ...

**Comment by IlPizza79** [comment]
+1, today has been released EPRO 3.5 and still, no post carousel.
I really don't understand why it takes so much time to give such a common widget to PAYING customers. I'm not sarcastic, I really don't understand.

**Comment by 79ho3ein** [comment]
I think the delay in implementing this feature does not mean ignoring the wishes of users. Developers are now working on great features. This request is definitely on their roadmap.
Megamenu, display conditions, page transitions, flexboxes, etc. are not really small things. But they will be added to elementor soon. These are definitely big improvements for elementor.
Elementor developers work very smart. For example, the features of nested column, links for column, and flexbox were among the most requested GitHub users. All three are added in version 3.6 elementor. This is a really big improvement.
I think elementor will have much bigger plans in 2022. Even bigger than 2021. I hope this request is included in it.
But it is unlikely to be added in 2021. thanks

**Comment by IlPizza79** [comment]
I can understand big plans, and I really like all new features, yet I can't understand why a simple thing like a post carousel is not available by default, I hope for the next year :-|

**Comment by SwingWizard** [comment]
A carousel with an option to display posts will be great. Also, there should be more query options in the Carousel & Posts widget such as
1. Display posts by views
2. Choose the time range of posts they trended in
3. Ability to query Posts & Carousel using more ways(such as those in Advanced Post Queries plugin)

**Comment by fabianenzensperger** [comment]
The content carousel comes with nested elements I think. So I'm expecting it this year. 🤗

**Comment by IlPizza79** [comment]
Still nothing yet? After SIX YEARS since the first comment?
I love elementor, but I REALLY don't understand this behavior. Elementor staff, please explain it to me :-(

**Comment by Kornform** [comment]
Yeah that's one reason why I will leave Elementor at some point. Now that they can't even tell when they will be able to release Flex Container after announcing it many many months ago is really disappointing...

**Comment by Michaelgimii** [comment]
Hi @arielk , Is this solved with loop builder? loop builder does not currently support carousel and does not have this feature...

**Comment by arielk** [comment]
@Michaelgimii This is an internal label that helps us manage requests. In any case, we plan to add an integration between the carousel and the loop builder

**Comment by nicholaszein** [comment]
Hello, everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the new Nested Carousel was released with Elementor Pro v3.14.0! 🥳 

You can now create Carousels or Slides with custom nested widgets without needing to use shortcodes or other features! 💪 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
