### ISSUE TITLE
✅ 🚀 Feature Request: Linkable column #351

### ISSUE THREAD

**Issue by technicalsofi** [elementor/elementor#22006]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

![image](https://user-images.githubusercontent.com/130452237/231151145-5bfc9b11-53e5-4165-9eef-41bd2b5b1b01.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/130452237/231151112-c5e9f68a-cfce-4c98-92c2-3e97f90b0c66.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

![image](https://user-images.githubusercontent.com/130452237/231150989-7811ff25-3578-4cdc-b58f-3162be9df230.png)

**Comment by nicholaszein** [comment]
Hey @technicalsofi , 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- This is not the place to submit feature requests. Moreover, the request was already solved with containers. If you need to add links to columns, switch to containers, as this feature will not be added to columns.

- 🔍 **Search Before Posting:** Before creating a new Bug Report, please [search for similar issues](https://github.com/elementor/elementor/issues/) to prevent creating duplicates.

- 🆕 **Stay Up-to-date:** Make sure you are using the most recent and stable versions of [Elementor](https://wordpress.org/plugins/elementor/#developers), [Elementor Pro](https://elementor.com/pro/changelog/), [WordPress](https://wordpress.org/download/releases/), and your theme.

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 🧩 **Contact 3rd-party Support:** If the issue happens with an Elementor add-on, extension, compatible plugin, or integrated theme, contact their support first. We do not provide support for 3rd-party software.

- ✒️ **Clear and concise title:** Please provide a clear and concise title that gives context to your issue.

- 💬 **Description:**In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our environments. Be thorough.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache.

Without them, we simply can't help. 😕 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

Best regards,

Nick
