### ISSUE TITLE
3.12.2 does not resolve the bug with the mini cart. 

### ISSUE THREAD

**Issue by asafmoraz** [elementor/elementor#22025]
Hey everyone!

We have great news! 🙌 

As @doronwolf mentioned yesterday,

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.12.2**! 🥳 

Thank you very much to everyone who contributed information to solve this issue, as well as giving your feedback about our procedures. 🙏 

We are constantly working on improving our communication, and your feedback is extremely valuable! We understand sometimes it might be frustrating to wait or to have to share all the information we request. But by doing that you are helping us identify possible related issues, and take the necessary time to fix them properly to avoid further complications.

Nonetheless, every single comment here was crucial for fixing this issue, and we are grateful for your contribution!

✅ Feel free to update your plugin to the new version!

Cheers 🥂

_Originally posted by @nicholaszein in https://github.com/elementor/elementor/issues/21836#issuecomment-1501835776_

**Comment by asafmoraz** [comment]
After reading that an update was released in version 3.12.2 that should solve the problem of the cart window, I've updated two sites to the new version and a few hours latter the problem repeated itself again :(

![Merged](https://user-images.githubusercontent.com/59032032/231652065-02c5fb42-9d3d-4c04-8352-42d3a7a08189.jpg)

**Comment by madebyaris** [comment]
Same here,

we use the Astra theme, and it also doesn't show up.

**Comment by nicholaszein** [comment]
Hello there, 

Make sure the WooCommerce Mini Cart Template is Disabled in your Dashboard > Elementor > Settings > Integrations page.

Also make sure you have cleared all levels of cache. This version was tested with the Astra Theme and everything is working as expected if the Mini Cart Template is disabled.

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🔍 **Search Before Posting:** Before creating a new Bug Report, please [search for similar issues](https://github.com/elementor/elementor/issues/) to prevent creating duplicates.

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 🧩 **Contact 3rd-party Support:** If the issue happens with an Elementor add-on, extension, compatible plugin, or integrated theme, contact their support first. We do not provide support for 3rd-party software.

- ✒️ **Clear and concise title:** Please provide a clear and concise title that gives context to your issue.

- 💬 **Description:**In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our environments. Be thorough.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache.

Without them, we simply can't help. 😕 


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Feel free to open a new issue following these guidelines. 😉 

Best regards,

Nick
