### ISSUE TITLE
⛔ 🐞 Bug Report: Critical CPU & RAM Consumption

### ISSUE THREAD

**Issue by nisiwi** [elementor/elementor#22138]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor is consuming ALL CPU & RAM resources with and without any plugins installed.

The video shows Elementor with WooCommerce installed, however the same issue occurs without ANY other plugins installed other than Elementor.

https://clipchamp.com/watch/GO8AHJy2SNY

I have opened a support ticket, however this is a serious problem and needs immediate attention, hence why I'm posting in GitHub.

### Steps to reproduce

Install Elementor

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-staging1.txt](https://github.com/elementor/elementor/files/11289396/system-info-staging1.txt)

**Comment by nisiwi** [comment]
A large part of this seems to be caused by the Flexblox Container which was left on.  With that feature disabled RAM is more stable, CPU resources are still being fully consumed albeit for a much shorter period.

**Comment by nisiwi** [comment]
After watching CPU getting consumed on a constant basis with just Elementor enabled (I removed the container feature which resolved RAM exhaustion) I decided to switch to Astra Pro and the difference is night and day and I'm shocked. I'm going to migrate this site to Astra in the short term and eventually to BricksBuilder and I'll be moving all sites in this direction unless Elementor resolve this ridiculous resource consumption issue.  Making an AJAX request was taking between 6 to 9 seconds because of the constant CPU overhead. Its now a fraction of that.

**Comment by nisiwi** [comment]
Support responded and ..... blamed the host.  This is laughable.  I will no longer be using Elementor.

**Comment by nicholaszein** [comment]
Hello @nisiwi,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
Testing on a Litespeed server with the same configurations as yours, we concluded our test website had no issues, and was not consuming more than 40% of memory and CPU usage.

### ✅ What you can do to solve your issue:
Check your hosting settings, and if possible test on another server.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
