### ISSUE TITLE
⛔ 🐞 Bug Report: Can't edit the shop page

### ISSUE THREAD

**Issue by borgesaliancas** [elementor/elementor#22172]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Prezados,

Estou desenvolvendo um site no nicho de joias utilizando os demais plugins e tema (atualizados) : 

 > Astra Pro ( 4.1.4 )
 > Start Templates Premium ( 3.2.1 )
 > Elementor Pro ( 3.12.3 )

Versão Wodrpress Atualizada 6.2 

Importei o Tema Premium Jewellery. 

Ao editar a pagina loja com elementor aparece um erro ( anexo )

Por favor podem me ajudar ?

Desde já agradeço-lhes

Obs: Certifiquei-me de desativar todos 
os plugins e deixar ativados apenas os plugins necessários para
a instalação do tema, contudo não identifiquei conflito em algum plugin e o erro persiste. 

https://user-images.githubusercontent.com/131607886/233866055-62248872-d205-4059-9e18-ec00eb0484ec.mp4

!Tema Jewellery](https://user-images.githubusercontent.com/131607886/233865380-135f0b1f-6044-4f87-89ca-d6d6b754bd77.jpg)
![Erro Editar Shop](https://user-images.githubusercontent.com/131607886/233865575-1337da8b-7b47-4355-9cfe-1bb8c7cf7785.jpg)

### Steps to reproduce

No Wordpress 

1. Páginas 

2. Editar Loja com Elementor 

3. A pré visualização não pode ser carregada.

https://user-images.githubusercontent.com/131607886/233866285-fc1f20d5-b8ec-4c48-a654-1e0d7f3bed5d.mp4

![Erro Editar Shop](https://user-images.githubusercontent.com/131607886/233866300-8503e772-d55f-4248-91a5-5646c9bd4737.jpg)

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-borgesaliancas.com.br-23-04-2023.txt](https://github.com/elementor/elementor/files/11304971/system-info-borgesaliancas.com.br-23-04-2023.txt)

**Comment by nicholaszein** [comment]
Hello @borgesaliancas,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- In WordPress, you can't edit the Shop page directly. In this case, you need to use the WooCommerce Builder and create a Products Archive template and set the display conditions to Include the Shop page.
- Moreover, you are using the Elementor Beta (Developer Edition) plugin. This plugin should not be used on production websites, and should only be used on staging websites by 3rd-party developers trying to test their add-ons. Please deactivate the Developer Edition plugin and [Rollback](https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/) Elementor and Elementor Pro to the latest stable releases.

Please read [this article](https://elementor.com/help/how-to-fix-the-preview-could-not-be-loaded-error/) to understand what you should do when editing the shop page. Especially this part:
![image](https://user-images.githubusercontent.com/113993460/235604655-1ee36de3-1800-4df0-80c4-e6e7b9cdeff8.png)

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

PS: Por favor, lembre-se de escrever seus issues em inglês na próxima vez.
