### ISSUE TITLE
⛔ 🐞 Bug Report: widget and container overlap

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#22190]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi team!

If the default padding value of containers in site settings is 0, there is no problem if we add multiple containers inside each other.

![1](https://user-images.githubusercontent.com/88034902/234251971-e45e563c-39ff-4ed9-ad9c-83a2c7924af3.png)

But if we add a widget inside the container (container padding is 0), the margin of the padding has an overlap with the widget.

![2](https://user-images.githubusercontent.com/88034902/234252616-6d5cdc17-6bfa-4470-9754-67ff13a8ed25.png)

**In fact, if you pay attention to the points mentioned in the above image, the widget border has moved out of the container border.**

### Steps to reproduce

1- add a container and make sure the padding of the container is 0.
2- Add another container inside this container. Considering that the padding was 0 in the parent container, the borders of the two containers are completely on top of each other and there is no problem here (according to the first image above)
3- Now remove the inner container and add a widget like heading widget inside it.

Finally, when you hover the mouse over this widget, if you check the heading widget start and end borders, it's out of the container's margin.

![2](https://user-images.githubusercontent.com/88034902/234252616-6d5cdc17-6bfa-4470-9754-67ff13a8ed25.png)

This issue has no effect on the front end, but can be fixed in the editor.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Needless

**Comment by nicholaszein** [comment]
Hi @Michaelgimii,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- This is just a visual illusion, the widgets have a different color for their overlay (a darker color) and they seem to appear wider than they are when overlapping a container, but they are in fact all aligned to the border-box. There is nothing to be fixed here. It's just the contrast between the two different colors that trick your eyes to see something that isn't there.

### 👍 For now, that's all we can help with. 

Kind regards
