### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor Cart Widget Not Displaying Quantity When Elementor Pro is Active

### ISSUE THREAD

**Issue by wpturnedup** [elementor/elementor#22267]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

 As soon as we disable Elementor Pro Version 3.12.3 the quantity appears. We've turned OFF all plugins except Elementor core and WooCommerce, as well as all Elementor "Features/Experiments" when Elementor Pro is active.

This is happening regardless of the theme.

### Steps to reproduce

1. Activate Elementor and Elementor Pro
2. Add items to the Cart
3. View Cart page (cart will not show qty)
4. Deactivate Elementor Pro
5. View Cart page (cart will show qty)

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.3
	MySQL version: mariadb.org binary distribution v10.5.12
	PHP Version: 8.1.3
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://metropops.com
	Home URL: https://metropops.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: My Listing Child
	Version: 1.1
	Author: 27collective
	Child Theme: Yes
	Parent Theme Name: My Listing
	Parent Theme Version: 2.10.3
	Parent Theme Author: 27collective

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

== Active Plugins ==
	Anti-Spam by CleanTalk
		Version: 6.9
		Author: СleanTalk <welcome@cleantalk.org>

	AutomateWoo
		Version: 5.6.0
		Author: WooCommerce

	AutomateWoo - Birthdays Add-on
		Version: 1.3.11
		Author: WooCommerce

	Elementor
		Version: 3.12.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.3
		Author: Elementor.com

	JetTabs For Elementor
		Version: 2.1.21
		Author: Crocoblock

	Loco Translate
		Version: 2.6.4
		Author: Tim Whitlock

	Mailchimp for WooCommerce
		Version: 2.8.3
		Author: Mailchimp

	Perfmatters
		Version: 2.0.9
		Author: forgemedia

	Permalink Manager Pro
		Version: 2.4.0
		Author: Maciej Bis

	Thanks Redirect for WooCommerce
		Version: 3.1
		Author: Nitin Prakash

	WooCommerce
		Version: 7.6.1
		Author: Automattic

	WooCommerce External Product New Tab
		Version: 1.0.4
		Author: Stuart Duff

	WooCommerce Gift Cards
		Version: 1.14.1
		Author: WooCommerce

	WooCommerce Memberships
		Version: 1.24.0
		Author: SkyVerge

	WooCommerce Product Vendors
		Version: 2.1.69
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.3.0
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 4.6.0
		Author: WooCommerce

	WPCodeBox
		Version: 1.4.1
		Author: WPCodeBox

	WP File Manager
		Version: 7.1.8
		Author: mndpsingh287

	WP Umbrella
		Version: 2.9.1
		Author: WP Umbrella - Backup & Manage WordPress


== Must-Use Plugins ==
	Kinsta Must-use Plugins
		Version: 3.0.0
		Author: Kinsta Team

	Perfmatters MU
		Version: 2.0.9
		Author: forgemedia

	WP Umbrella
		Version: 1.0.0
		Author: WP Umbrella

	_WPHealthHandlerMU.php
		Version: 
		Author: 


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Inactive
	Editor Top Bar: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active by default
	Form Submissions: Inactive
	Scroll Snap: Inactive
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 352023-04-05 15:15:52 [info] elementor-pro::elementor_pro_updater Started 
2023-04-05 15:15:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-05 15:15:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-05 15:15:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-10 11:22:20 [info] elementor-pro::elementor_pro_updater Started 
2023-04-10 11:22:20 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-10 11:22:20 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-10 11:22:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-10 11:22:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-10 11:22:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-23 09:06:02 [info] elementor::elementor_updater Started 
2023-04-23 09:06:02 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-23 09:06:02 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-23 09:06:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-23 09:06:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-23 09:06:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-23 09:06:24 [info] elementor-pro::elementor_pro_updater Started 
2023-04-23 09:06:24 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-23 09:06:24 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-23 09:06:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]

JS: showing 7 of 7JS: 2023-03-27 18:56:14 [error X 164][https://metropops.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.11.5:2:16011] Cannot read properties of undefined (reading 'global') 
JS: 2023-04-05 21:08:56 [error X 4][https://metropops.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.12.1:2:63893] Cannot convert undefined or null to object 
JS: 2023-04-19 12:19:22 [error X 6][https://metropops.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:632658] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-04-24 14:22:35 [error X 4][https://metropops.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.2:3:1081263] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-04-24 16:02:56 [error X 1][https://metropops.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.12.2:2:5009] Cannot read properties of undefined (reading 'attributes') 
JS: 2023-04-26 16:06:07 [error X 7][https://metropops.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.12.2:2:3562] jQuery is not a function 
JS: 2023-04-26 16:06:07 [error X 1][https://metropops.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.3:2:40999] Cannot create property 'guid' on string 'c48widgetsticky' 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hi @wpturnedup,

please elaborate on the following:

1. Are you using the Elementor Menu Cart widget, or are you using the Mini Cart from your theme?
2. Are you using the WooCommerce shortcode for the cart page, or are you using Elementor's Cart widget on the cart page?
3. Is the page where you have the cart shortcode/widget properly configured as the Cart page in the WooCommerce > Settings > Advanced > Page setup section?
4. Inside the Elementor Editor > Site Settings > WooCommerce, is the Cart page also properly selected there?
5. Did you test with only Elementor, Elementor Pro, WooCommerce, and the Hello Theme active? I see you have Perfmatters and other optimization plugins that might conflict with the scripts on the cart page. Please ensure that's not the case, including any custom snippets you might have.

**Comment by wpturnedup** [comment]
You bet.


  1.  Hello theme. Elementor Cart widget.
  2.  Elementor Cart widget.
  3.  Yes
  4.  Yes
  5.  Yes

Things have been find for years. This is new and it’s happening on multiple sites I’ve tested.

Thanks!

**Comment by nicholaszein** [comment]
Hey, @wpturnedup!

Thank you for providing the additional information! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- We tested with the latest release of Elementor and Elementor Pro (3.14.1) and everything seems to be working as expected. Your issue might be related to cache or a conflict with another plugin. See the video below:


https://github.com/elementor/elementor/assets/113993460/9071b25e-b309-4d92-a9ab-1ccf472c3179



### ✅ What you can do to solve your issue:
- Follow these troubleshooting steps:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor after following the troubleshooting steps above, feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
