### ISSUE TITLE
⛔ 🐞 Bug Report: Mobile uses desktop parameters when using theme editor

### ISSUE THREAD

**Issue by MrSpudd** [elementor/elementor#22309]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Currently experiencing an issue when creating a page in the "theme builder" when using "hello elementor". When having different font sizes or margins from desktop responsive editor to mobile, the mobile will always use the parameters set to desktop. For example, if a font size is set to 70 for desktop view and 30 for mobile, when accessing the site from mobile it will still use size 70. This is only apparent when in the theme builder and not when editing a normal page. Additionally, the responsive mobile view in the editor shows it correctly, until viewed from an actual mobile device. As far as I'm aware this affects small things such as font size, margins, and padding from my own testing, but could affect more.

![Screenshot 2023-05-03 213554](https://user-images.githubusercontent.com/66712279/235905421-3fc71314-2c82-4098-979a-424a5f30aac4.png)
![Screenshot 2023-05-03 213654](https://user-images.githubusercontent.com/66712279/235905433-581b0e85-e218-400b-84b9-db6222f0d7e0.png)

### Steps to reproduce

1) Go into the theme editor, such as an archive page when using hello elementor
2) Enable responsive mode
3) Set desktop title font size to 70
4) Set the mobile font size to 30 for the same title
5) Check to see the font size on a mobile device

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.19
	PHP Version: 8.1.16
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://tire-x.com.au
	Home URL: https://tire-x.com.au
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Australia/Brisbane
	Admin Email: adam@tire-x.com.au
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.68

== Active Plugins ==
	Elementor
		Version: 3.12.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.6
		Author: Elementor.com

	WooCommerce
		Version: 7.6.1
		Author: Automattic


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Mega Menu: Inactive by default


== Log ==
	
JS: showing 8 of 8JS: 2022-12-18 06:59:49 [error X 2][https://tire-x.com.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.1:3:881312] elementorFrontend is not defined 
JS: 2022-12-18 11:09:26 [error X 6][https://tire-x.com.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.1:3:1068257] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2023-03-26 10:24:03 [error X 6][https://tire-x.com.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.5:3:1087291] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-03-27 02:31:09 [error X 1][https://tire-x.com.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.5:3:791161] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-03-27 02:55:48 [error X 14][https://tire-x.com.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.5:3:791668] Cannot read properties of undefined (reading 'localized') 
JS: 2023-03-27 10:36:32 [error X 1][https://tire-x.com.au/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9:21077] Cannot read properties of null (reading 'getOptions') 
JS: 2023-05-01 02:11:05 [error X 1][https://tire-x.com.au/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.11.6:2:1101] Cannot read properties of undefined (reading '$el') 
JS: 2023-05-02 07:43:58 [error X 1][https://tire-x.com.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0:3:632658] Cannot read properties of undefined (reading 'isDesignable') 

PHP: showing 4 of 4PHP: 2023-03-03 15:10:41 [warning X 29][/home/u681012271/domains/tire-x.com.au/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-25 17:38:57 [notice X 15955][/home/u681012271/domains/tire-x.com.au/public_html/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::200] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-27 12:33:24 [warning X 1][/home/u681012271/domains/tire-x.com.au/public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::264] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-27 14:06:34 [notice X 5][/home/u681012271/domains/tire-x.com.au/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::562] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 16 of 162023-03-25 17:38:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.11.5',
)]
2023-03-25 17:38:57 [info] elementor-pro::elementor_pro_updater Started 
2023-03-25 17:38:57 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-25 17:38:57 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-25 17:38:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.11.6',
)]
2023-03-25 17:38:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.11.6',
)]
2023-03-25 17:38:57 [info] elementor::elementor_updater Started 
2023-03-25 17:38:57 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-25 17:38:57 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-25 17:38:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.11.5',
)]
2023-03-25 17:38:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.11.5',
)]
2023-03-25 17:38:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0',
  'to' => '3.11.6',
)]
2023-04-02 20:07:07 [info] elementor::elementor_updater Started 
2023-04-02 20:07:07 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-02 20:07:07 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-02 20:07:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]	

````

</details>

**Comment by nicholaszein** [comment]
Hello @MrSpudd,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
What you are experiencing is cache related.
Mobile browsers tend to have a more persistent cache policy to reduce mobile data usage. For this reason, once you visit a page a second time the browser will try to avoid downloading the styles, and instead use the styles it already downloaded. Every time you change a style for any element, it will trigger Elementor to Regenerate the CSS for that entire document. But since the mobile browser will try to avoid downloading the new stylesheet, you will view the page with the old styles. This gets more aggravated if you have a performance optimization solution such as a site or server cache that enforces an extended cache expiry policy or removes query strings from static sources.

### ✅ What you can do to solve your issue:
During your site's development process, it is recommended that you use the incognito/private mode of your mobile browser to visit the edited pages and avoid your mobile browser from caching them. Alternatively, you could either clear/delete the mobile browser history and/or disable any performance optimization solution to avoid this kind of issue. You can also try to change the `CSS Print Method` in your Dashboard > Elementor > Settings > Advanced page to `Internal Embedding`.
For more instructions on how to troubleshoot this issue, please follow the article below:
https://elementor.com/help/changes-dont-appear-online/

### 👍 For now, that's all we can help with. 

This is more of a support question, not really something we can answer here.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
