### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor 3.13 : some editor panel Facelift issues

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#22379]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Some things in the new version of the editor that need further review.

1- At the end of each section of widget settings, there is a lot of white space, which was not the case before 3.13.

![1](https://github.com/elementor/elementor/assets/88034902/41400c5d-4274-40f3-acd9-1fbd74b197c1)

2- If we close all widget settings tabs, a lot of empty space will be created at the top, which is not pleasant at all.

![2](https://github.com/elementor/elementor/assets/88034902/cbb8fe9f-aa08-49b7-925c-71bea0536d16)

![b](https://github.com/elementor/elementor/assets/88034902/4a16fccd-6e5e-470f-a109-c86562addcd3)

3- In the new version, the distance between widget settings tabs has increased. This was great. But the **border top** weight increased to 2 pixels. Please reduce it to 1px. Please see the image below. 2px is really too much for it.

![3](https://github.com/elementor/elementor/assets/88034902/da1ed2ec-5e12-499b-be9a-e54997026dfc)

4- As a suggestion, please move the arrow icon in the widget settings to the front (right).

![4](https://github.com/elementor/elementor/assets/88034902/5a5aa7d9-15de-4124-9601-c4051a4433fd)

5- Please consider hover background color for widget settings options. **The following video is a combination of options 3, 4 and 5.**

https://github.com/elementor/elementor/assets/88034902/6b5b374f-0b78-47d8-8a1a-6eff919fd769

### Steps to reproduce

-

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

It cannot be useful

**Comment by nicholaszein** [comment]
Hello @Michaelgimii! 

Thank you for the feedback! 🙏 

I will add this to our list of suggestions for the Facelift of the UI. Please keep in mind that we might not accept some of these suggestions due to some unforeseen points you might not be considering. But nonetheless, these are great suggestions and something that we will discuss internally!

Also, please, in the future if possible, these issues could have been added to the Beta Discussion (including the ones about the Mega Menu icons). We could have discussed them before the release, and maybe even implement some of the fixes for the issues you found with the colors and icons.

PS: For the sake of keeping track, it's important to have the System Info, so we know in the future exactly which version you are using so we can track when the changes to the UI were made. The System Info is very useful for us. Thanks 🙏 

Best regards

**Comment by nicholaszein** [comment]
Hello @Michaelgimii,

Thank you for your patience! 🙏 

### ⛔ After reviewing your report we concluded this is not an issue caused by Elementor. The points you raised are the expected behavior.

> _**1- At the end of each section of widget settings, there is a lot of white space, which was not the case before 3.13.**_

This is the intended behavior. This helps separate sections better.

> _**2- If we close all widget settings tabs, a lot of empty space will be created at the top, which is not pleasant at all.**_

This is the intended behavior. The same applies here, we added this for accessibility, to improve separation between the tabs at the top and the sections below. When sections are closed, they show a top border to indicate they are closed. When they are opened, the space above gives proper separation from the section before, even if there is no section before.

> _**3- In the new version, the distance between widget settings tabs has increased. This was great. But the border top weight increased to 2 pixels. Please reduce it to 1px. Please see the image below. 2px is really too much for it.**_

This was intentional as well and for the same reasons. Accessibility. This helps users understand the separation between sections better.

> _**4- As a suggestion, please move the arrow icon in the widget settings to the front (right).**_

After deliberating about your suggestions, while we agree this appears more pleasant to the eyes, it doesn't give the same level of accessibility by indicating if a section is opened or closed. With the icon before the text, the user can see at a glance if a section is closed, while if it was at the end of the container, it might not be immediately viewed by users, who would have more chances of having difficulty in understanding there is more content to be shown. So for now, we have no plans to change this behavior.

### 👍 For now, that's all we can help with. 

Kind regards
