### ISSUE TITLE
❌ Elementor Pro not available as Plugin in Wordpress maybe because of new security issue at Version 5.7.1

### ISSUE THREAD

**Issue by deni1984** [elementor/elementor#22455]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor Pro not available as Plugin in Wordpress maybe because of new security issue at Version 5.7.1

### Steps to reproduce

Just download Elementor Website Builder and try to install Elementor Pro. You can't even find it from Wordpress. Even the dowloaded version can't be run and can't be installed manually.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

Wordpress newest version (May2023)

**Comment by m1ga** [comment]
the security issue is in the 3rd party plugin "Essential Addons for Elementor":
https://www.wordfence.com/threat-intel/vulnerabilities/wordpress-plugins/essential-addons-for-elementor-lite/essential-addons-for-elementor-571-unauthenticated-arbitrary-password-reset-to-privilege-escalation

Has nothing todo with the main Elementor

**Comment by soydelia** [comment]
@deni1984 As far as I know, Elementor PRO has never been available in the WordPress repository.

@m1ga There is a vulnerability in Elementor https://www.wordfence.com/threat-intel/vulnerabilities/wordpress-plugins/elementor/elementor-3131-missing-authorization-to-settings-update

**Comment by m1ga** [comment]
@soydelia yes, but that wasn't the question by the author. He asked about `new security issue at Version 5.7.1` and that is the version of "Essentials Addons for Elementor". 
Also that security issue is fixed already in 3.13.2

**Comment by m1ga** [comment]
No problem at all @soydelia 

I only saw the "security fix" in 3.12.3 but didn't see the wordfence link yet! Better to link those and inform people than not knowing about it :smile: !

**Comment by nicholaszein** [comment]
Hello @deni1984,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- The plugin IS indeed available in the WordPress repository, and the vulnerability you're referring to as @m1ga correctly pointed out has nothing to do with the Elementor plugin.

### ✅ What you can do to solve your issue:
- Download the latest version of Elementor from the [WordPress Repository](https://wordpress.org/plugins/elemento).

### 👍 For now, that's all we can help with. 

This is more of a support question, not really something we can help with here. Please remember to check the Help Center or contact Elementor Support before submitting an issue.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
