### ISSUE TITLE
❌ 🧩 🐞 Bug Report: iPad Super zoom in of background images in landscape mode

### ISSUE THREAD

**Issue by junkmailaa** [elementor/elementor#22590]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

As documented over the last 3 years by many posters this has been a problem with your wordpress plug in. If you use attachment fixed on background pictures (which is one of the main reasons to use your page builder to add flare to a website) then once a tablet is turned to landscape mode with an 8"+ screen the pictures will zoom in so much you just see a very very small section grainy, horrible and unrecognizable. It does not matter if you try to build two images with responsive settings as your responsive design only removes images for tablet and mobile in portrait mode which has no problem showing correctly. We all understand that fixed picture position does not work on Tablet or Phone and it switches to scroll mode which is fine and works on phones, tablet portrait BUT NOT landscape on a screen larger then 8" and does not change if you edit the background image container in tablet mode to a different setting. It also does not matter how large or small of a picture you use. We have all spent far more time trying to work around this then it would take to fix this issue.

Many have asked many have attempted just trying to see if you are ever going to fix this or if I need to cancel my subscription on 5 websites and use another product.   I have taken the time to create an account here to help you with your product as you are no longer responding to 10+ user postings on Wordpress.org support.

### Steps to reproduce

Go to wheatfire.com or wheatandfire.com and turn any tablet 8" to landscape mode and watch the image be unrecognizable turn back to portrait and see how it should look.  Does not matter what browser is used I have tested this on three different iPads as this is the only tablets I own.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

turning any mobile device to landscape mode with a screen larger than 8"

**Comment by nicholaszein** [comment]
Hello @junkmailaa,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is a known issue caused by Mobile Safari, which stretches the image to the whole viewport dimensions instead of the container. If you do a quick search on the internet you'll see multiple reports about this issue.

### ✅ What you can do to solve your issue:
This is something that is beyond our control. It's a bug of the browser and one that has been purposefully ignored by Apple. They are not following web standards, and there is nothing we can do about it. There have been many attempts of fixing this issue, but all of them come with their own set of problems that when weighed against the benefits, are not worth it.

Here's something you might try:


https://github.com/elementor/elementor/assets/113993460/b0601e67-a7ea-41aa-b9f0-35f51e1b2990


----
This should be enough to make your image only stretch the width and height of the Container. You might want to also change the parent Container's `Overflow` control to `Hidden` in the parent Container's Layout tab > `Additional Options` section if your image overflows it.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
