### ISSUE TITLE
⛔ 🛟 Support Request: Elementor Mobile Navigation Toggle Submenu Broken

### ISSUE THREAD

**Issue by ocoles** [elementor/elementor#22708]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I created a brand new WordPress 6.2.2 website with only the Elementor plugin 3.13.4 installed using the default Hello Elementor 2.7.1 theme. The kit-created pages were then nested as child sub-pages in the navigation menu under the Home page. When I checked from mobile, the toggle menu is already broken and does not expand or collapse sub-menu items. Hello Elementor theme navigation sub-menu is broken from the start.

### Steps to reproduce

1) Install WordPress.
2) Install Elementor.
3) Create menu, with sub-menu items.
4) Visit website from mobile, and click toggle navigation menu.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.36
	PHP Version: 7.4.33
	PHP Memory Limit: 1G
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://testbed.hotbed.a2hosted.com
	Home URL: https://testbed.hotbed.a2hosted.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 1G
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.13.4
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default

== Log ==
	
Log: showing 1 of 12023-06-01 13:36:25 [info] Uploading Kit:  [array (
  'kit_id' => '61f6c406b3df350011ebb7b0',
  'referrer' => 'kit-library',
)]

PHP: showing 1 of 1PHP: 2023-06-01 13:36:30 [notice X 1][/home/hotbedah/public_html/testbed/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==

````

</details>

**Comment by nicholaszein** [comment]
Hello @ocoles,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the Help Center or contact Elementor Support before submitting an issue.

We see that you are hosting your website on a LiteSpeed server, and when we visited the website we could navigate through your Navigation Menu without any issues, both testing on a desktop browser as well as on a mobile browser. This means your issue is related to the server cache. Please, remember to **<ins>ALWAYS</ins>** clear the server cache when making changes to your website. LiteSpeed servers implement a very persistent cache system, and this will affect the loading of scripts and styles if you don't remember to clear the cache. You can try to use a plugin such as the official LiteSpeed cache to help clear the server cache, and it will also allow you to configure the cache system to avoid causing conflicts with Elementor scripts and styles.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
