### ISSUE TITLE
✅ ❌ 🔗 🐞 Bug Report: No Exit Button - Editor Top Bar Experiment (Duplicate of #22359) - [ED-10275]

### ISSUE THREAD

**Issue by unitedonline** [elementor/elementor#22733]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When activating the Editor Top Bar in Experiments & Features, the exit button disappears from the hamburger menu.

### Steps to reproduce

Set Editor Top Bar experiment to Active and save.
Go to edit any Elementor post or page.
The Exit button is no longer there.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Operating System: | Linux |  
Software: | Apache |  
MySQL version: | Debian 11 v10.5.19 |  
PHP Version: | 7.4.33 |  
PHP Memory Limit: | 256M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 100M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

**Comment by nicholaszein** [comment]
Hello there, @unitedonline!

Thank you for your submission! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

### 🔗 🚀 There is already a similar request submitted by someone here #22359

Feel free to continue the conversation and cast your **⬆️ Upvote** there! 👉

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards
