### ISSUE TITLE
❌ 🐞 Bug Report: CTA min-width on image stays on tablet/mobile

### ISSUE THREAD

**Issue by up-creator** [elementor/elementor#22756]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

On CTA's, the width on the image attribute sets a min-width on the image.
When changing to responsive and choose the top-image layout, it keeps the min-width, so it displays the image as if it still has room for the 465px image(example), therefore cut's the image off. If we write css to change min-width to 100%, it fixes it.

### Steps to reproduce

Change width of image in desktop, change to mobile and image is desktop-size, no options to change/fix it. Only with css.
In the video below i remove the min-width attribute set by the desktop image width attribute.

https://github.com/elementor/elementor/assets/32708034/49b66b2e-de7e-4c74-9ca8-123cbb5d5bc9

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

not necessary

**Comment by nicholaszein** [comment]
Hello @up-creator,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
You forgot to set a size for the image on a tablet or mobile. If you change it to `px` on the desktop, it will always inherit the styles from the desktop, so you have to also set the size for tablet and mobile.


### ✅ What you can do to solve your issue:
Please refer to the [documentation](https://elementor.com/help/call-to-action-widget/) on how to configure your CTA.


### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the Help Center or contact Elementor Support before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Moreover, the `System Info` is **<ins>ALWAYS</ins>** necessary when reporting a bug here.

Kind regards

**Comment by nicholaszein** [comment]
Hello @up-creator, 

as explained in [this comment](https://github.com/elementor/elementor/issues/22934#issuecomment-1613541442), please provide the missing information:

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Kind regards

**Comment by nicholaszein** [comment]
Hi @up-creator,

the System Info is a required field as we explicitly say in our Bug Report form. 

![image](https://github.com/elementor/elementor/assets/113993460/5aaaf84a-2b3f-4d9d-9595-f9d05bf6122c)

Thanks for sharing it! 🙏 

🏷️ We've labeled this issue and our team will take a look at it. If there is indeed a problem, they'll work on fixing it. We can't say exactly when it'll be sorted out, but we kindly ask for your patience. Thanks for understanding!

Best regards
