### ISSUE TITLE
✅ 📚 🐞 Bug Report: Typo: DONOTCACHCEOBJECT instead of DONOTCACHEOBJECT in `includes/utils.php`

### ISSUE THREAD

**Issue by quazgar** [elementor/elementor#22786]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The function `do_not_cache` in `includes/utils.php` has a typo in [line 370+371](https://github.com/elementor/elementor/blob/main/includes/utils.php#L370), probably `DONOTCACHEOBJECT` should be there.

### Steps to reproduce

Look at the code.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Irrelevant here.

**Comment by nicholaszein** [comment]
Hello @quazgar! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

PS: Note, Sharing the **System Info** is **<ins>ALWAYS</ins>** relevant and mandatory. Since you shared exactly the line of code where you found the typo, we'll let it slide this time. We appreciate the effort and your contribution, but going forward, we will close bug reports that do not include this information. Please when opening a new Bug Report follow the guidelines in the Bug Report form. Thanks! 🙏 

Best regards

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v.3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
