### ISSUE TITLE
❌ 🐞 Bug Report: AJAX behavior not working correctly when 'Show quantity' enabled in Add to Cart widget

### ISSUE THREAD

**Issue by TowyTowy** [elementor/elementor#22797]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Problem Statement
When using the "Add to Cart" widget in Elementor Pro version 3.13.2 with WordPress 6.2, the AJAX behavior is not functioning correctly when the "Show quantity" option is enabled. Instead of adding the item to the cart without refreshing the page, the current page reloads.

Expected Behavior
The "Add to Cart" widget should use AJAX to add the item to the cart without refreshing the page, regardless of whether the "Show quantity" option is enabled or disabled. The user should receive visual feedback confirming the item addition without any page reload.

Current Behavior
Currently, when the "Show quantity" option is enabled in the "Add to Cart" widget, clicking the "Add to Cart" button triggers a reload of the current page instead of performing an AJAX request to add the item to the cart. The user stays on the same page, but the entire page content reloads, including any changes made before clicking the button.

### Steps to reproduce

Steps to Reproduce
To reproduce the issue, follow these steps:

1. Install and activate WordPress version 6.2.
2. Install and activate Elementor Pro version 3.13.2.
3. Create a new page in Elementor.
4. Drag and drop the "Add to Cart" widget onto the page.
5. Enable the "Show quantity" option in the widget settings.
6. Preview or publish the page.
7. Make some changes on the page (e.g., text, images, etc.).
8. Attempt to add an item to the cart using the "Add to Cart" button.
9. Observe that the current page reloads completely, including any changes made before clicking the button.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Elementor Pro version: 3.13.2
WordPress version: 6.2
Browser: Google Chrome
Theme: Hello Elementor

**Comment by nicholaszein** [comment]
Hello, @TowyTowy

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

### Please, when reporting a bug, follow all the guidelines in the bug report form. We can't accept bug reports without all the information required. 

Kind regards
