### ISSUE TITLE
❌ 🧩 🛟 Support Request: WooCommerce settings page shows an error

### ISSUE THREAD

**Issue by mradmin12** [elementor/elementor#22897]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

in the woocommerce
i get that error always

There was an error getting your inbox. Please try again.

### Steps to reproduce

in the woocommerce
i get that error always

There was an error getting your inbox. Please try again.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

in the woocommerce
i get that error always

There was an error getting your inbox. Please try again.

**Comment by nicholaszein** [comment]
Hello @mradmin12,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party plugins.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for Elementor or 3rd-party plugin support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
