### ISSUE TITLE
❌ 🐞 Bug Report: CTA min-width still a problem

### ISSUE THREAD

**Issue by up-creator** [elementor/elementor#22934]
Hi, i am writing again, as this has not been fixed.
It doesn't matter if you set a width on tablet or mobile, it still uses the desktop width, as the width dissapears when you choose the image-on-top layout, because there are no width attribute for that layout. Therefore it goes to the desktop value and not the responsive value.

Please try it out yourself.
Use image-on-left in desktop, set a px width on image.
Use image-on-left on mobile, set a px/%(or any other width) on image.
Change mobile layout to image-on-top, it uses the desktop width, and not mobile width.
Therefore the image will cut and be bigger than expected, if desktop image is for example 600px.

I have contacted support as you said. But i still don't think it belongs with the support. Unless i am missing something obvious.

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
You forgot to set a size for the image on a tablet or mobile. If you change it to `px` on the desktop, it will always inherit the styles from the desktop, so you have to also set the size for tablet and mobile.

_Originally posted by @nicholaszein in https://github.com/elementor/elementor/issues/22756#issuecomment-1593738836_

**Comment by perks98** [comment]
@up-creator I could replicate your issue and do think it is a bug as it is an unintended action as it cuts off the image a bit on mobile.

**When I try and replicate using the call to action widget:** 
![Screenshot_822](https://github.com/elementor/elementor/assets/55829113/0ad5598d-ef84-4207-ad54-3240cd7cf2be)
![Screenshot_823](https://github.com/elementor/elementor/assets/55829113/cf225872-426c-4c6f-94c2-be5b8a0c69f3)

The problem is that when you change image position from left or right to top position it removes the width input so only height is available.
My only suggestion at the moment until they plan to fix this is to use a custom unit and use `min(500px,100%)` for the width.
![Screenshot_824](https://github.com/elementor/elementor/assets/55829113/a8823936-a7a0-41a4-a1e0-8423641ecace)

**Comment by nicholaszein** [comment]
Hello @up-creator,

I will reopen your original issue, with one condition: That you provide the required information, specifically the System Info, which, again, you haven't added here.

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the essential **<ins>System Info</ins>** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Please provide the missing information, and if possible include a video of your issue so we can understand better. From my tests it's working as expected.

Thanks
