### ISSUE TITLE
⛔ 🧩 🛟 Support Request: Bug with Dynamic.ooo - Dynamic Content for Elementor

### ISSUE THREAD

**Issue by robinxshooter** [elementor/elementor#22938]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have 2 problems. The first problem occurs when I try to edit a single post with Elementor. I get an error that the contnt area was not found (see screenshot)
![Screenshot 2023-06-27 at 12 48 45](https://github.com/elementor/elementor/assets/6230782/88f5a4f1-6562-4348-863a-35453ba92885)

I can bypass this error in 2 ways, the first one is to deactivate Dynamic.ooo - Dynamic Content for Elementor the other way is to switch my standard theme to 'elementor full width' or 'elementor canvas' in site settings.

The second issue is about my page speed. While Dynamic.ooo - Dynamic Content for Elementor is active my site is really slow. But I need this plugin because it's necessary for dynamic elements.

### Steps to reproduce

1) open up a single post element 2) try to edit it

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-deminornxt.com-30-06-2023.txt](https://github.com/elementor/elementor/files/11916605/system-info-deminornxt.com-30-06-2023.txt)

**Comment by nicholaszein** [comment]
Hello @robinxshooter,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

👎 If after following these steps the problem persists, you can submit a new issue with details to reproduce it so we can take a look.

Regards
