### ISSUE TITLE
⛔ 🛟 Support Request: Header and Footer Horizontal scrolling issue

### ISSUE THREAD

**Issue by KennyMqny** [elementor/elementor#22967]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello, I'm building my new website and wanted it with horizontal scrolling. Problem is, I don't know why, but I've got issues with header and footer. It add a blank section in the beginning and in the end of my webpage. You can see it here : https://mqnycreative.com/accueil_nouveau/

I find why : The header and the footer is considered as a section. In the additional code, this line : .elementor-section-wrap{display: inline-flex;} consider that both header and footer are a section (well I guess but I'm not sure). Which means that the blank is simply the footer extended (same thing for the footer) and explain why I have this white area. 

I don’t think it happens with vertical navigation but it’s not the idea on our website.

I don’t understand cause It comes from your own tutorial (https://elementor.com/academy/how-to-create-a-horizontal-scrolling-website-advanced-pro/). I've tried with different solutions like asking Chat GPT but It doesn't really work either...

Here is what Chat GPT suggested me : 

```css
/* Défilement horizontal */
body {
  overflow-x: scroll;
  overflow-y: hidden;
}

.elementor-section-wrap {
  display: flex;
  flex-wrap: nowrap;
}

.elementor-section {
  width: 100vw;
}

/* Exclusion du header et du footer */
.site-header,
.site-footer {
  position: sticky;
  z-index: 9999;
  background-color: #fff; /* Remplacez cette valeur par la couleur de fond de votre header/footer */
}

@media (max-width: 768px) {
  /* Restauration du défilement vertical sur les petits écrans */
  body {
    overflow-x: hidden;
    overflow-y: scroll;
  }

  .elementor-section-wrap {
    display: block;
  }
}
```

I've reached your customer service and after a long talk, Mr. Nemanja Markovic told me to contact you this way.

### Steps to reproduce

(Theme : Astra)
1) Create a Header and footer with Elementor
2) Follow this tutorial from Elementor : https://elementor.com/academy/how-to-create-a-horizontal-scrolling-website-advanced-pro/

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.42
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 16000
	PHP Max Post Size: 130M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://mqnycreative.com
	Home URL: https://mqnycreative.com
	WP Multisite: No
	Max Upload Size: 128 Mo
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%category%/
	Language: fr-FR
	Timezone: Europe/Paris
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.1.5
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15

== Active Plugins ==
	AI Powered Marketing
		Version: 1.2.0
		Author: Kliken

	Akismet Anti-Spam: Spam Protection
		Version: 5.2
		Author: Automattic - Anti Spam Team

	BackWPup
		Version: 4.0.0
		Author: Inpsyde GmbH

	Burst Statistics - Privacy-Friendly Analytics for WordPress
		Version: 1.4.3
		Author: Really Simple Plugins

	Complianz | GDPR/CCPA Cookie Consent
		Version: 6.4.7
		Author: Really Simple Plugins

	CookieYes | GDPR Cookie Consent
		Version: 3.1.1
		Author: CookieYes

	Creative Mail by Newfold Digital
		Version: 1.6.7
		Author: Newfold Digital

	Duplicate Page
		Version: 4.5.2
		Author: mndpsingh287

	Elementor
		Version: 3.14.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

	EWWW Image Optimizer
		Version: 7.1.0
		Author: Exactly WWW

	Favicon by RealFaviconGenerator
		Version: 1.3.27
		Author: Philippe Bernard

	Really Simple SSL
		Version: 7.0.5
		Author: Really Simple Plugins

	SecuPress Free — WordPress Security
		Version: 2.2.4.1
		Author: SecuPress

	Site Kit by Google
		Version: 1.104.0
		Author: Google

	UpdraftPlus - Backup/Restore
		Version: 1.23.6
		Author: UpdraftPlus.Com, DavidAnderson

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.15
		Author: David Anderson, Ruhani Rabin, Team Updraft

	Yoast SEO
		Version: 20.10
		Author: Team Yoast


== Must-Use Plugins ==
	burst_rest_api_optimizer.php
		Version: 
		Author: 

	SecuPress COOKIEHASH
		Version: 1.0
		Author: 

	SecuPress Salt Keys
		Version: 2.0
		Author: 


== Utilisation des éléments ==
	
	footer : 1
		button : 4
		text-editor : 1
	header : 1
		image : 1
		nav-menu : 1
	popup : 1
		button : 4
	wp-page : 21
		button : 418
		call-to-action : 20
		container : 11
		flip-box : 6
		form : 3
		heading : 129
		image : 202
		menu-anchor : 47
		nav-menu : 3
		social-icons : 4
		spacer : 31
		testimonial-carousel : 1
		text-editor : 88
		video : 13
	loop-item : 0
		button : 32
		icon-list : 2
		image : 7


== Réglages ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1


== Fonctionnalités ==
	Custom Fonts: 1
	Custom Icons: 0

== Intégrations ==
	
	recaptcha: Actif
	recaptcha_v3: Actif


== Expériences d’Elementor ==
	Sortie DOM optimisée: Inactif par défaut
	Amélioration du chargement des ressources: Inactif par défaut
	Optimisation du chargement du CSS: Inactif par défaut
	Icônes de police « inline »: Inactif par défaut
	Améliorations de l’accessibilité: Actif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Actif
	Mettre à niveau la bibliothèque Swiper: Inactif par défaut
	Grid Container: Inactif par défaut
	Par défaut vers le Nouveau constructeur de thème: Actif par défaut
	Editor Top Bar: Inactif par défaut
	Page d’atterrissage: Actif par défaut
	Éléments imbriqués: Inactif par défaut
	Nested Accordion: Inactif par défaut
	Chargement différé des images d’arrière-plan: Inactif par défaut
	Global Style Guide: Inactif par défaut
	Transitions des pages: Actif par défaut
	Notes: Actif par défaut
	Boucle: Actif par défaut
	Envois de formulaire: Actif par défaut
	Accroche de défilement: Actif par défaut
	Menu: Inactif par défaut


== Journal ==
	
Log: showing 20 of 392023-06-19 15:33:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-19 15:33:43 [info] elementor::elementor_updater Started 
2023-06-19 15:33:43 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-19 15:33:44 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-19 15:33:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.0',
)]
2023-06-19 15:33:57 [info] elementor-pro::elementor_pro_updater Started 
2023-06-19 15:33:58 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-19 15:33:58 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-19 15:33:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.0',
)]
2023-06-26 19:02:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-26 19:02:29 [info] elementor::elementor_updater Started 
2023-06-26 19:02:29 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-26 19:02:30 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-26 19:02:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-27 06:57:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-27 06:57:11 [info] elementor-pro::elementor_pro_updater Started 
2023-06-27 06:57:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-27 06:57:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-27 06:57:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]
2023-06-27 06:57:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.0',
  'to' => '3.14.1',
)]

JS: showing 3 of 3JS: 2023-06-16 10:29:14 [error X 3][https://mqnycreative.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js:2:63900] Object.entries requires that input parameter not be null or undefined 
JS: 2023-06-19 13:43:38 [error X 5][https://mqnycreative.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.14.0:3:107491] Routes: `panel/editor/settings` not found. 
JS: 2023-06-21 13:03:48 [error X 2][https://mqnycreative.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0:3:687590] this.model.isValidChild is not a function. (In 'this.model.isValidChild(C)', 'this.model.isValidChild' is undefined) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilité non spécifiée

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @KennyMqny,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the Help Center or contact Elementor Support before submitting an issue. We do not provide assistance with building and customizing websites, or custom code here. This is a place to report validated bugs.

However, here's what I found after reviewing your page:

1. You are using the sticky option to make your header sticky to the top. The sticky option generates a hidden copy of your sticky element that will remain in the place of the original section to avoid what's called Cumulative Layout Shift (CLS) when the sticky element changes its position from relative to fixed after the sticky effect is triggered. To avoid this behavior, instead of enabling the Sticky option, change the section's position to `fixed` in the Advanced tab, and ensure the width is set to `100vw`. This should fix your first reported issue. **Note that this is not a bug.**
2. If you are following the tutorial and still want to add a footer (which is not part of the tutorial), you will see it appearing as part of the horizontal scroll on your page. I assume that's not the desired effect. In this case, you will have to do something similar to what I suggested on item 1, but align it to the bottom of the page. 

### 👍 For now that's all we can help you with here.

I suggest you seek help in the Global Community, as this goes beyond the scope of this department.

Thank you for understanding.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
