### ISSUE TITLE
❌ 🐞 Bug Report: Hiding section/container/widget on navigator does not hide the equivalent in Advanced responsive mode

### ISSUE THREAD

**Issue by 4evermaat** [elementor/elementor#22976]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Everytime I try to hide a widget or container using the Navigator menu, the equivalent section

Now shouldn't these be linked?  to where switching the view of a widget off in one portion (and in a certain viewport) would also switch that same widget off in the responsive mode of the advanced section?
 

The whole point of the navigator is that you can maneuver and manipulate widget order + visibility from the navigator menu.  So I kept hiding things in mobile viewport and then trying to preview the page and it was not being hidden in the preview.   I'm wondering what I'm doing wrong....and then I researched that there is a `Advanced` menu >  `responsive` section where you are supposed to switch the equivalent option to `hide` also.

![Snag_602697c1](https://github.com/elementor/elementor/assets/830306/b8f7baa3-bfc9-4dc3-8289-599f93bb0982)

So it would make sense for the buttons to be linked and/or at least have a settings/features switch that links the switches together.   So if I hide something in the mobile viewpoint in the navigator, it should also hide it in the `responsive` section.

And vice versa

### Steps to reproduce

1) Hide a widget/container/section using the navigator

2) save the page (update or save draft)

3a) preview page and see if the widget is visible or not

3b) look at `responsive` properties of widget in advanced menu and see if the show/hide switch has been toggled or not.

![Snag_602697c1](https://github.com/elementor/elementor/assets/830306/b8f7baa3-bfc9-4dc3-8289-599f93bb0982)

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

<html>
<body>
<div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-block-end: 10px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | MariaDB Server v5.6.49-89.0 |  
PHP Version: | 7.4.33 |  
PHP Memory Limit: | 32M | We recommend setting memory to at least 128M. (256M or higher is preferred) For more information, read about how to increase memory allocated to PHP.
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 8M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div>
</body>
</html>Server Environment		
Operating System:	Linux	
Software:	Apache	
MySQL version:	MariaDB Server v5.6.49-89.0	
PHP Version:	7.4.33	
PHP Memory Limit:	32M	We recommend setting memory to at least 128M. (256M or higher is preferred) For more information, read about [how to increase memory allocated to PHP](https://go.elementor.com/wordpress-wp-config-memory/).
PHP Max Input Vars:	1000	
PHP Max Post Size:	8M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	6.2.2	
Site URL:	---
Home URL:	---
WP Multisite:	No	
Max Upload Size:	6 MB	
Memory limit:	256M	
Max Memory limit:	512M	
Permalink Structure:	/%postname%.html	
Language:	en-US	
Timezone:	0	
Admin Email:	---
Debug Mode:	Inactive	
Theme		
Name:	Hello Elementor	
Version:	2.7.1	
Author:	Elementor Team	
Child Theme:	No	If you want to modify the source code of your theme, we recommend using a [child theme](https://go.elementor.com/wordpress-child-themes/).
User		
Role:	administrator	
WP Profile lang:	en_US	
User Agent:	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

</details>

**Comment by nicholaszein** [comment]
Hi, @4evermaat,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

This is the expected behavior. As explained in the [Documentation](https://elementor.com/help/navigator-indicators/), the Show/Hide Eye icon is meant to be used in the context of the editor. This is a direct quote:

> Indicates that this element is currently being viewed. Clicking the Eye will toggle between Show and Hide states for that element. Hiding the element will only affect the view on the back end, within the Elementor Editor. It will have no effect on the front end of the site.

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the Help Center or contact Elementor Support before submitting an issue.

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the essential **<ins>[System Info](https://elementor.com/help/hare-my-system-info/)</ins>** with each issue reported. We'll need it to help you effectively. 

As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
