### ISSUE TITLE
⛔ 🛟 Support Request: Frozen Elementor Page Editor from Copy & Pasting Large Text in Text Editor

### ISSUE THREAD

**Issue by vicentele** [elementor/elementor#23063]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### The Elementor Editor completely freezes. 
The scroll bar works and you can scroll through the page but you cannot select anything, move any sliders, edit any text boxes, or use any buttons. All of it displays but loses functionality. 

### Page Does Not Save
The page does not save either if it happens. I had to redo a lot of changes on a web page I was working on. I now save a draft every 5 seconds.

### Cannot Reload Page
I am not able to reload the page either. It will sit stuck reloading forever. I must either delete the tab or go to another web page on the same tab after first trying to reload. 

### Happens in Safe Mode
This happens in Safe Mode as well. Also on a newly created web page with a blank Elementor Canvas with a simple form I just started building, and nothing else.

### Computer Works Hard
A little bit after this occurs, I get a temperature warning which only happens when my computer ramps up performance / is struggling with some process.

### No Uploaded Images
There are no uploaded images or screenshots. I figured there wasn't much to see. Take a screenshot of a frozen screen? Isn't that what a screenshot is?

### Thanks

P.S. Any chance there is some sort of Elementor Partner, etc. badge I could use on my website?

### Steps to reproduce

1) Have a page with the text editor widget.

2) Have a good amount of text in the text editor. Maybe a few paragraphs.
_Note: I copied the Lorem Ipsum sample text and pasted it 8 more times. While reproducing the error on a new page I just created with a form on it I just started building._

3) In the text box on the widget sidebar editor, not in the text box on the page itself. (Although, that may work as well.) Press Ctrl + A to select all information in the text editor. 

4) Press Ctrl + C to copy all the selected text.

5) Enjoy newly frozen web page on a hot summer day.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

I am using Opera GX web browser.

[system-info-smolderingseeds.com-15-07-2023.txt](https://github.com/elementor/elementor/files/12060820/system-info-smolderingseeds.com-15-07-2023.txt)

**Comment by nicholaszein** [comment]
Hello @vicentele,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the Help Center or contact Elementor Support before submitting an issue.


### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- We followed your steps and even added more content. And we were still able to edit the page normally.
- This usually happens when your server and device resources are limited.


https://github.com/elementor/elementor/assets/113993460/1c9fdf58-f60f-4e6c-a0a9-0201be0cca75



### ✅ What you can do to solve your issue:
- Please make sure your server meets the [minimum requirements](https://elementor.com/help/requirements) to run Elementor.
- If you wish to add large quantities of content, make sure to increase the `php_memory_limit` to at least 512M, preferably equal or above 1GB; increase `php_max_input_vars` to at least 10000; increase `WP_MEMORY_LIMIT` and `WP_MAX_MEMORY_LIMIT` to the same PHP limit; also increase `php_max_post_size` to a value that is equal or below your memory limit.

### 👍 For now, that's all we can help with. 


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
