### ISSUE TITLE
❌ 🐞 Bug Report: Swiper update with fade transition doesn't work

### ISSUE THREAD

**Issue by ronaldaug** [elementor/elementor#23069]
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

[Related Issue](https://github.com/orgs/elementor/discussions/16822)
It's 2023 and I still don't find "fade" effect option under Elementor carousel settings. 
Then, I try to update the Swiper options after init and found that it doesn't work with `{effect: "fade"}` parameter. 

### Steps to reproduce

I use Swiper's `update()` method, the transition doesn't change to fade effect at all.

```javascript
jQuery(document).ready(function($) {

   $(window).on('load', function () {
   
    const imageCarousel  = jQuery('#my-carousel .swiper');
    const swiperInstance = imageCarousel.data('swiper');
    swiperInstance.params.effect = 'fade';  
    // swiperInstance.originalParams.effect = 'fade';  
    swiperInstance.update();
    
    })
    
})
```

> Btw, I can access the swiperInstance

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

Operating System: | Darwin |  
-- | -- | --
Software: | nginx/1.23.4 |  
MySQL version: | MySQL Community Server - GPL v8.0.31 |  
PHP Version: | 7.4.33 |  
PHP Memory Limit: | 512M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 512M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

**Comment by nicholaszein** [comment]
Hi, @ronaldaug,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

Please do not submit issues to request features.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
