### ISSUE TITLE
❌ 🐞 Bug Report: Video background is not showing on Edge browsers

### ISSUE THREAD

**Issue by lokacoding** [elementor/elementor#23192]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When we set a background video for a section, the video is correctly covering the section in any size of screens in Chrome, Opera, Firefox and Safari;
But in Edge browser it is not playing (grey screen):
[](https://mofarennen-enkhausen.de)

I'm using latest Elementor free version.

### Steps to reproduce

Visit: [Mofarennen Enkhausen](https://mofarennen-enkhausen.de)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Latest WordPress 6.2.2

**Comment by nicholaszein** [comment]
Hello @lokacoding,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- We visited your site using the latest version of the Edge browser (115.0.1901.188) and we can see the video background reproducing as expected.

https://github.com/elementor/elementor/assets/113993460/24c012c2-78a4-4ec4-8ddb-3169078cb2ae

- We also tried it in our own environment. And it's working as expected:


https://github.com/elementor/elementor/assets/113993460/7f20de5c-6b1e-457b-912c-9744a79353ae

- Your issue is likely caused by cache.

### ✅ What you can do to solve your issue:
- Clear all levels of cache and try again.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

PS: We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the essential **<ins>[System Info](https://elementor.com/help/hare-my-system-info/)</ins>** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.
