### ISSUE TITLE
❌ 🐞 Bug Report : error 500

### ISSUE THREAD

**Issue by nature365resort** [elementor/elementor#23213]
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

server error 500

### Steps to reproduce

server error 500

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: nginx/1.25.1
	MySQL version: Debian 11 v10.5.19
	PHP Version: 8.1.20
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://nature365resort.fi
	Home URL: https://nature365resort.fi
	WP Multisite: No
	Max Upload Size: 16 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 3
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.1.6
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	All in One SEO
		Version: 4.4.2
		Author: All in One SEO Team

	Elementor
		Version: 3.15.0-dev6
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Jetpack
		Version: 12.3
		Author: Automattic

	Starter Templates
		Version: 3.2.6
		Author: Brainstorm Force

	Weglot Translate
		Version: 4.1.1
		Author: Weglot Translate team

	WordPress Importer
		Version: 0.8.1
		Author: wordpressdotorg

	WPForms Lite
		Version: 1.8.2.3
		Author: WPForms

	WP Mail SMTP
		Version: 3.8.2
		Author: WP Mail SMTP


== Elements Usage ==
	
	page : 40
		button : 185
		container : 57
		counter : 3
		divider : 75
		google_maps : 6
		heading : 424
		icon : 3
		icon-box : 12
		icon-list : 8
		image : 324
		image-box : 170
		image-carousel : 9
		image-gallery : 3
		shortcode : 6
		social-icons : 3
		spacer : 19
		star-rating : 15
		testimonial : 36
		text-editor : 231
		toggle : 1
		video : 44
		wpforms : 17
	section : 2
		image : 4
		image-box : 7
		social-icons : 4
		text-editor : 4
	wp-page : 45
		button : 162
		container : 60
		divider : 68
		google_maps : 8
		heading : 388
		icon : 2
		icon-box : 10
		icon-list : 4
		image : 309
		image-box : 167
		image-carousel : 10
		image-gallery : 6
		shortcode : 6
		social-icons : 4
		spacer : 24
		text-editor : 149
		toggle : 1
		video : 4
		wpforms : 9


== Settings ==
	
	cpt_support: post, page, e-landing-page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Editor Top Bar: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Global Style Guide: Active


== Log ==
	
Log: showing 20 of 382023-07-21 13:59:36 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-21 13:59:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0-dev3',
  'to' => '3.15.0-dev4',
)]
2023-07-21 13:59:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0-dev3',
  'to' => '3.15.0-dev4',
)]
2023-07-25 11:43:30 [info] elementor::elementor_updater Started 
2023-07-25 11:43:30 [info] Elementor/Upgrades - _on_each_version Start  
2023-07-25 11:43:30 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-25 11:43:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0-dev4',
  'to' => '3.15.0-dev5',
)]
2023-07-25 11:43:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0-dev4',
  'to' => '3.15.0-dev5',
)]
2023-07-29 17:44:35 [info] elementor::elementor_updater Started 
2023-07-29 17:44:35 [info] Elementor/Upgrades - _on_each_version Start  
2023-07-29 17:44:35 [info] Elementor/Upgrades - _on_each_version Finished 
2023-07-29 17:44:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0-dev5',
  'to' => '3.15.0-dev6',
)]
2023-07-29 17:44:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.0-dev5',
  'to' => '3.15.0-dev6',
)]
2023-07-30 13:02:30 [info] Elementor custom task(s) process has been queued. [array (
  0 => 
  array (
    0 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_recalculate_usage',
    ),
    1 => 
    array (
      0 => 'Elementor\Core\Upgrade\Custom_Tasks',
      1 => 'opt_in_send_tracking_data',
    ),
  ),
)]
2023-07-30 13:02:30 [info] elementor::custom_task_manger Started 
2023-07-30 13:02:30 [info] Elementor/Tasks - opt_in_recalculate_usage Start  
2023-07-30 13:02:32 [info] Elementor/Tasks - opt_in_recalculate_usage Finished 
2023-07-30 13:02:32 [info] Elementor/Tasks - opt_in_send_tracking_data Start  
2023-07-30 13:02:32 [info] Elementor/Tasks - opt_in_send_tracking_data Finished 
2023-07-30 13:02:32 [info] elementor::custom_task_manger Completed 

JS: showing 3 of 3JS: 2023-06-01 07:17:02 [error X 8][https://new.nature365resort.fi/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.0-dev2:3:568840] Blocked a frame with origin &quot;https://new.nature365resort.fi&quot; from accessing a cross-origin frame. 
JS: 2023-07-26 13:25:51 [error X 2][https://new.nature365resort.fi/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.0-dev5:3:642431] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2023-07-29 14:44:12 [error X 1][https://new.nature365resort.fi/wp-admin/load-scripts.php?c=1&amp;loadchunk_0=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&amp;ver=6.2.2:2:31823] Cannot read properties of undefined (reading &#039;value&#039;) 

PHP: showing 2 of 2PHP: 2023-07-25 13:03:27 [warning X 1][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-29 17:44:02 [warning X 1][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	



````

</details>

**Comment by nicholaszein** [comment]
Hello @nature365resort, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🔍 **Search Before Posting:** Before creating a new Bug Report, please [search for similar issues](https://github.com/elementor/elementor/issues/) to prevent creating duplicates.

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- ✒️ **Clear and concise title:** Please provide a clear and concise title that gives context to your issue.

- 💬 **Description:** In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our environments. Be thorough.

Without them, we simply can't help. 😕 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


Follow the instructions in this article: [Troubleshooting a 500 Error](https://elementor.com/help/500-error/)


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

### ⚠️ Elementor Developer Edition detected!

We noticed that you're using the **_Elementor Beta (Developer Edition)_** plugin. This edition is a playground for developers to test their plugins and themes with the most recent features of Elementor, and it's not quite intended for live websites.

### 🧪 Due to the experimental nature of this edition, we're unable to provide support for it. 

But don't worry! Our stable versions are full of great features that are ready for prime time on your website.

### 🔄 Please, [switch back to a stable version](https://elementor.com/help/revert-to-release-from-developer-edition/) if you're working on a production site.
