### ISSUE TITLE
⛔ 🐞 Bug Report: Embedded iframe via HTML Widget not working for Users with role Shop Manager

### ISSUE THREAD

**Issue by SEwebm** [elementor/elementor#23232]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am Using Elementor + Elementor Pro 3.14.1 + WooCommerce (7.9.0) with the most recent Hello Theme Version (2.8.1).

The Problem is that on my Elementor Website only admin users can add an, in my case, Open Street Map embed via pasting the embed code in the HTML widget.
If a shop manager user does that then the iframe tag including all its contents is removed from the DOM when the page is saved. 

It does not make any difference if the page was created by the admin or the shop manager user.

### Steps to reproduce

1) Setup test site with Elementor / Pro + WooCommerce
2) Create a test user with the role: shop manager
3) With the freshly created user create a page and add an HTML Widget
4) Paste any embed code (iframe)
5) Save and preview and see that any iframe is removed

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.24.0
	MySQL version: mariadb.org binary distribution v10.11.4-MariaDB-1:10.11.4+maria~ubu2204
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 2000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://b2z5nqzz.myraidbox.de
	Home URL: https://b2z5nqzz.myraidbox.de
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0

== Active Plugins ==
	Elementor
		Version: 3.14.1
		Author: Elementor.com

	WooCommerce
		Version: 7.9.0
		Author: Automattic


== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Verbesserungen der Zugänglichkeit: Standardmäßig aktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Standardmäßig deaktiviert
	Upgrade Swiper Library: Standardmäßig aktiviert
	Grid Container: Standardmäßig deaktiviert
	Hello Theme Header & Footer: Standardmäßig aktiviert
	Editor Top Bar: Standardmäßig deaktiviert
	Startseiten: Standardmäßig aktiviert
	Nested Elements: Standardmäßig deaktiviert
	Nested Accordion: Standardmäßig deaktiviert
	Hintergrundbilder nachladen: Standardmäßig deaktiviert
	Global Style Guide: Standardmäßig deaktiviert


== Protokoll ==
	


== Elementor - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @SEwebm,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
By default, and for security reasons WordPress will always try to sanitize (remove/clean) potentially malicious code from the content upon publishing/updating a page. This includes iFrames. Elementor itself passes the page through the same default process. This is particularly important when you have a user role that is not an administrator.

For security reasons, we have no plans to change this behavior.

### ✅ What you can do to solve your issue:
- Use a dedicated plugin for OSM like this one: https://br.wordpress.org/plugins/osm/
- Create a custom shortcode in combination with a custom field to show the iframe on the front end.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
