### ISSUE TITLE
❌ 🧩 🐞 Bug Report: Mega Menu - The menu is not showing for click and drop

### ISSUE THREAD

**Issue by Suschibomber** [elementor/elementor#23234]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have Flexbox Containers, Nested Elements and Menu enabled but it doesn't show the new menu item to me on the left in the drop down list in the editor to drag it to the page. 

It still only shows the old widgets. So the option of the new menu is missing. 

I'm on the newest Elementor and Elementor Pro Version 3.15.0

![Elementor-megamenu](https://github.com/elementor/elementor/assets/51985160/2b424898-e148-4b29-aa81-d8d8be30d739)

### Steps to reproduce

1. Open Page (Header)
2. Edit with Elementor
3. No option to drag and drop the menu because its missing

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.41
	PHP Version: 8.1.21
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

**Comment by nicholaszein** [comment]
Hello @Suschibomber,

Thank you for reaching out! 🙏 

### ❌ 🧩 You seem to have a plugin conflict.

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
Despite you not sharing the **<ins>FULL SYSTEM INFO</ins>** as indicated on our guidelines, I can see that it seems you have _**The Plus Add-ons**_ plugin installed. This plugin has a feature that disables native Elementor widgets by default. This means you need to go to this add-on's settings and enable the widget there too.

### ✅ What you can do to solve your issue:
- Check your Elementor add-ons settings and search for a feature that disables native Elementor widgets, and enable the widgets you want to show.

### 👍 For now, that's all we can help with. 

----

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<ins>full, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

----

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
