### ISSUE TITLE
❌ 🐞 Bug Report: mensajes de error de elementor

### ISSUE THREAD

**Issue by rso-sa2023** [elementor/elementor#23346]
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

al hacer el montaje de pagina web con elementor en la parte móvil, al actualizarlo me aparece los siguientes errores: 

Notice: Undefined index: margin_tablet in ../wp-content/plugins/elementor/core/files/css/base.php on line 776

Notice: Undefined index: margin_mobile in ../wp-content/plugins/elementor/core/files/css/base.php on line 776

Notice: Undefined index: padding_tablet in ../wp-content/plugins/elementor/core/files/css/base.php on line 776

Notice: Undefined index: padding_mobile in ../wp-content/plugins/elementor/core/files/css/base.php on line 776

### Steps to reproduce

1) edito de manera móvil en elementor
2) guardarlo
3) actualizo en el movil la pagina
4) me aparece en el encabezado los siguientes errores
Notice: Undefined index: margin_tablet in ../wp-content/plugins/elementor/core/files/css/base.php on line 776

Notice: Undefined index: margin_mobile in ../wp-content/plugins/elementor/core/files/css/base.php on line 776

Notice: Undefined index: padding_tablet in ../wp-content/plugins/elementor/core/files/css/base.php on line 776

Notice: Undefined index: padding_mobile in ../wp-content/plugins/elementor/core/files/css/base.php on line 776

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

Notice: Undefined index: margin_tablet in ../wp-content/plugins/elementor/core/files/css/base.php on line 776

Notice: Undefined index: margin_mobile in ../wp-content/plugins/elementor/core/files/css/base.php on line 776

Notice: Undefined index: padding_tablet in ../wp-content/plugins/elementor/core/files/css/base.php on line 776

Notice: Undefined index: padding_mobile in ../wp-content/plugins/elementor/core/files/css/base.php on line 776

**Comment by nicholaszein** [comment]
Hello @rso-sa2023, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🔍 **Search Before Posting:** Before creating a new Bug Report, please [search for similar issues](https://github.com/elementor/elementor/issues/) to prevent creating duplicates.

- 🆕 **Stay Up-to-date:** Make sure you are using the most recent and stable versions of [Elementor](https://wordpress.org/plugins/elementor/#developers), [Elementor Pro](https://elementor.com/pro/changelog/), [WordPress](https://wordpress.org/download/releases/), and your theme.

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 🧩 **Contact 3rd-party Support:** If the issue happens with an Elementor add-on, extension, compatible plugin, or integrated theme, contact their support first. We do not provide support for 3rd-party software.

- ✒️ **Clear and concise title:** Please provide a clear and concise title that gives context to your issue. **<ins>Use only English!</ins>**

- 💬 **Description:** In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our environments. Be thorough.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Without them, we simply can't help. 😕 

### ⚠️ As a gentle reminder, issues that do not follow our 🐞 Bug Report Guidelines may need to be closed without troubleshooting. 

Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏

Best regards
