### ISSUE TITLE
❌ 🧩 🐞 Bug Report: Editor Wont load - Backbone JS Error

### ISSUE THREAD

**Issue by ColbyDevOps** [elementor/elementor#23370]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Editor wont load

Console:

TypeError: C is undefined
    validateHTMLTag /plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3
    Backbone 3

web-cli.min.js:3:157475
    error /plugins/elementor/assets/js/web-cli.min.js?ver=3.15.2:3
    catchApply /plugins/elementor/assets/js/web-cli.min.js?ver=3.15.2:3
    64708/applyRunAfterAsync/_callee/_callee$/< /wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.15.2:3
Uncaught (in promise) TypeError: C is undefined
    validateHTMLTag /wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3
    Backbone 3

### Steps to reproduce

Load a page:

1. Click the "Edit with Elementor" link
    - note this is a blue button or a link

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Ubuntu)
	MySQL version: MySQL Community Server - GPL v8.0.32
	PHP Version: 8.0.27
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 64M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Debug Mode: Inactive

JS: showing 2 of 2JS: 2023-06-22 17:32:55 [error X 68]/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:17898] this.getColorRepresentation() is null 
JS: 2023-07-14 11:49:04 [error X 1][/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:806979] T.originalEvent.key is undefined 

PHP: showing 4 of 4PHP: 2023-07-14 06:47:24 [warning X 7][//wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-14 07:31:34 [warning X 1][/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-23 08:20:26 [warning X 1][//plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::199] unlink(checkmark-white.png): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-23 08:20:33 [warning X 1][/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::208] unlink(checkmark-white.zip): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by nicholaszein** [comment]
Hello @ColbyDevOps, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🆕 **Stay Up-to-date:** Make sure you are using the most recent and stable versions of [Elementor](https://wordpress.org/plugins/elementor/#developers), [Elementor Pro](https://elementor.com/pro/changelog/), [WordPress](https://wordpress.org/download/releases/), and your theme.

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 🧩 **Contact 3rd-party Support:** If the issue happens with an Elementor add-on, extension, compatible plugin, or integrated theme, contact their support first. We do not provide support for 3rd-party software.

- ✒️ **Clear and concise title:** Please provide a clear and concise title that gives context to your issue.

- 💬 **Description:** In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our environments. Be thorough.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

- 🗑️ **Clear the cache:** Always clear the cache after any update (WordPress, Theme, Plugins, Posts, and Pages). This includes but is not limited to server cache, site cache, CDN cache, and browser cache.

Without them, we simply can't help. 😕 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<ins>full, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Best regards
