### ISSUE TITLE
❌ 🐞 Bug Report: Custom breakpoints in the editor don't appear with the maximum resolution for that particular breakpoint

### ISSUE THREAD

**Issue by fxaviers** [elementor/elementor#23385]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have a custom breakpoint, laptop, where it measures 1366 pixels wide.
Ideally, when clicking on the icon for this, anywhere on the interface, the window size of the chosen editor would be selected.
However, the width is never respected, and a smaller value is always selected.
<img width="257" alt="image" src="https://github.com/elementor/elementor/assets/17536232/af95950a-1581-4ea0-a006-5eae1512dc6c">

### Steps to reproduce

Just click on the custom breakpoint.
<img width="794" alt="image" src="https://github.com/elementor/elementor/assets/17536232/92efdb15-e2e7-465d-8731-1da034b7f45d">

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

.

**Comment by nicholaszein** [comment]
Hello @fxaviers,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- This is the expected behavior. By default, Elementor will always show the minimum size for any particular breakpoint. This way you can visualize how the page will appear for the smallest size possible and adapt your designs to fit correctly.

### ✅ What you can do to solve your issue:
- Simply adjust the size by dragging the handles outside the Editor Preview, or change the value in the field above.

### 👍 For now, that's all we can help with. 

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Kind regards
