### ISSUE TITLE
⛔ 🐞 Bug Report: Masonry Loop Grid with Flip Box Widget

### ISSUE THREAD

**Issue by orofri** [elementor/elementor#23527]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

Hey there!

I'm trying to build a portfolio with Masonry layout using the loop grid. The reason I am not using the 'portfolio' widget is mainly because I need pagination as well which is not exists in this widget.

So I thought I could get a similar hover behavior (where you can see the title of the item on hover) like the 'portfolio' widget using the 'flip box' widget.

I tried the 'loop grid' with the Masonry layout and seems like it doesn't work with the 'flip box' widget. It does work with a simple image widget though.

I suspect it is because there's no way to use auto height / 100% height for the 'flip box' widget.

### Steps to reproduce

1. Create a 'loop grid' with 'flip box' widget.
2. Remove the default graphic elements titles and descriptions on the content tabs of both front and back.
3. In the background tabs of both front and back, assign dynamic tags of the image to the feature images of the posts.(make sure you have images in very different sizes)
4. Set images to No-Repeat and size to custom -> width: 100%.
5. Wider images will be shown with top and bottom stripes and the Masonry layout is not working because all the 'flip boxes' has the same width and height.
![image](https://github.com/elementor/elementor/assets/37490842/515e8738-ff8e-4ad2-ba66-9dbf8dccb784)

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.2.4
	MySQL version: mariadb.org binary distribution v10.4.28
	PHP Version: 8.2.4
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: No
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3
	Site URL: http://localhost/Neko
	Home URL: http://localhost/Neko
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.54

== Active Plugins ==
	Custom Post Type UI
		Version: 1.14.0
		Author: WebDevStudios

	Duplicate Page
		Version: 4.5.2
		Author: mndpsingh287

	Elementor
		Version: 3.16.0-dev1
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.0-beta1
		Author: Elementor.com

	User Role Editor
		Version: 4.64
		Author: Vladimir Garagulya

	WooCommerce
		Version: 8.0.2
		Author: Automattic


== Elements Usage ==
	
	footer : 1
		container : 2
		social-icons : 2
		text-editor : 4
	header : 2
		container : 4
		nav-menu : 6
		theme-site-logo : 2
	page : 1
		container : 5
		gallery : 1
		heading : 2
		image : 1
		progress : 6
		spacer : 2
		text-editor : 1
		video : 2
	popup : 2
		container : 5
		form : 1
		heading : 2
		icon : 1
		icon-box : 1
		image : 1
		text-editor : 1
	wp-post : 0
		animated-headline : 4
		container : 105
		gallery : 11
		heading : 40
		hotspot : 2
		html : 2
		icon-list : 10
		image : 21
		image-carousel : 2
		loop-grid : 3
		progress : 66
		spacer : 24
		taxonomy-filter : 2
		text-editor : 19
		video : 22
	wp-page : 3
		container : 5
		form : 1
		hotspot : 1
		image : 1
		loop-grid : 1
		shortcode : 1
	loop-item : 2
		container : 2
		flip-box : 1
		image : 1


== Settings ==
	
	cpt_support: post, page, portfolio
	allow_tracking: yes
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Active
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Pages Panel: Inactive by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Active


== Log ==
	


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

**Comment by nicholaszein** [comment]
Hello @orofri,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
That's the expected behavior of the Flip Box widget. The images are added as background images, not as objects (<img> tags). This means that the height you set for your Flip Box widget in the **`Content`** _tab_ > **`Settings`** _section_, will be applied to the entire Flip Box, and will be the same for every Loop Item in the Loop Grid, negating the Masonry Layout effect altogether.

### ✅ What you can do to solve your issue:
To achieve the effect you want you would need to use the Image or Featured Image widgets, and then for the text you would set the **`Position`** of the text as **`Absolute`** and place it at your desired location like in the video below:


https://github.com/elementor/elementor/assets/113993460/e8af7cbe-b9b7-4a1a-81f0-fc0652e4fa7d


### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
