### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: Elementor Update breaks the site

### ISSUE THREAD

**Issue by imaqib** [elementor/elementor#23540]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I'm using Elementor free version on my website (https://kitcheny.co.uk/) For 3 days my website layout broke I don't know why this is happening I contacted my hosting provider, but all in vain. but now I found the issue. whenever I updated the elementor the website layout broke and everything was changed. Now what do I have to do about that?

### Steps to reproduce

update the plugin

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-kitcheny.co.uk-23-08-2023.txt](https://github.com/elementor/elementor/files/12421227/system-info-kitcheny.co.uk-23-08-2023.txt)

**Comment by nicholaszein** [comment]
Hi @imaqib!

Thank you for contacting us.

### ❌ 🧩 You seem to have an Elementor add-on conflict.

To isolate this conflict please try these **Troubleshooting** steps:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

2. 🗑️ **Clear the cache:** Clear all levels of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.

3. 📋 **Meet the Requirements** Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

### 👎 If the issue persists use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

----

### ⚠️ Elementor Developer Edition detected!

We noticed that you're using the **_Elementor Beta (Developer Edition)_** plugin. This edition is a playground for developers to test their plugins and themes with the most recent features of Elementor, and it's not quite intended for live websites.

### 🧪 Due to the experimental nature of this edition, we're unable to provide support for it. 

But don't worry! Our stable versions are full of great features that are ready for prime time on your website.

### 🔄 Please, [switch back to a stable version](https://elementor.com/help/revert-to-release-from-developer-edition/) if you're working on a production site.

Regards
