### ISSUE TITLE
⛔ 🛟 Support Request: Elementor Popups not working - Broken flex

### ISSUE THREAD

**Issue by nicoalma** [elementor/elementor#23626]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Im setting up popups in elementor and now they appear cropped on Chrome. I've tried to fix it with custom code, and re built it all over again but the issue keeps on happening. 

Previewing in Elementor works,  not on front.

Any ideas? ---> I saw an old thread on inputting Flexibility script to the popup, but that shouldn't be the case here.

Apparently safari shows them properly, but neither Chrome or Firefox do. 
![image (2)](https://github.com/elementor/elementor/assets/67433162/041ce84a-fc81-4b46-abd8-e47c99f58b15)
![Screenshot 2023-08-30 at 12 18 01](https://github.com/elementor/elementor/assets/67433162/5caa8e6b-4f70-47dd-abb7-b674649cfaa1)

### Steps to reproduce

1. Login to Elementor
2. Create a popup with trigger conditions
3. Post

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-www.boardofinnovation.com-31-08-2023.txt](https://github.com/elementor/elementor/files/12484308/system-info-www.boardofinnovation.com-31-08-2023.txt)

**Comment by nicholaszein** [comment]
Hello @nicoalma,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

We tested the Popup with **<ins>only</ins>** the latest stable versions of Elementor (3.15.3) and Elementor Pro (3.15.1), without any other plugin or performance optimization enabled, and we were able to load the Popup without any layout issues.

Your issue is likely caused by cache.

Check this article in the Help Center to help fix your issue:
https://elementor.com/help/changes-dont-appear-online/


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
