### ISSUE TITLE
⛔ 📊 🐞 Bug Report: WordPress Menu Dropdown won't work if JS compression is on with the Litespeed cache

### ISSUE THREAD

**Issue by deveraybektas** [elementor/elementor#23627]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In Litespeed cache plugin, if you enable js file compression, elementor's menu will not open in mobile view. However, if you turn off Js compression, the menu will open.

### Steps to reproduce

1) Activate Hello elementor, elementor, and elementor pro
2) Add Headers' wordpress menu widget or choose from ready template
3) Go to litespeed plugin settings and enable js compression.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-peronmedya.com-31-08-2023.txt](https://github.com/elementor/elementor/files/12485323/system-info-peronmedya.com-31-08-2023.txt)

**Comment by nicholaszein** [comment]
Hello @deveraybektas ,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- The WordPress Menu widget relies on a couple of scripts to work properly, if you alter the order they are loaded, or concatenate them with other scripts in the wrong order, which is what the option in your performance optimization plugin does, you might break its functionality.
- You are using the Elementor Pro v3.16.0-beta2 version, with the Elementor Core v3.15.3 version. It's not recommended to mix and match beta versions with stable versions. You shouldn't even be using an unstable beta version on a production website.


### ✅ What you can do to solve your issue:
- Once you update any plugin on a LiteSpeed website, it's imperative that you also purge all levels of cache, more than one time to avoid having residual scripts and styles affecting the functionality of the components of your website. LiteSpeed cache is famously known for not clearing after itself when needed, and affecting the functionality and order of scripts.
- Exclude the following scripts from being cached and/or optimized entirely>
   1. nav-menu
   2. jquery.smartmenus

You're going to have to make some tests and exclude scripts from being cached in order to make the WordPress Menu start working again.

Elementor can't control or avoid how a performance optimization plugin behaves. If the plugin is causing the issue, stop the plugin from causing the issue.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
