### ISSUE TITLE
⛔ 🐞 Bug Report: CSS ID doesn't get copied over when copying widget / container with CSS ID

### ISSUE THREAD

**Issue by toineenzo** [elementor/elementor#23646]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I copy a widget or container where I put in a css class and ID, only the class gets copied over when pasting the copied widget/container. The CSS ID will be empty.

### Steps to reproduce

1. Make a container with optionally a widget in it
2. Add a CSS class and ID to the container (and widget)
3. Copy and paste the container / widget somewhere
4. You'll see that the copy and pasted container / widget only contains the class and not the ID
Please see the following demonstration video: https://github.com/elementor/elementor/assets/4921397/321a9a47-94f6-4ef4-bb39-646f17dd46d3

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
Operating System: Linux
Software: Apache/2.4.57 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f
MySQL version: mariadb.org binary distribution v10.11.3-MariaDB-1:10.11.3+Maria~ubu2004
PHP Version: 7.4.33
PHP Memory Limit: 128M
PHP Max Input Vars: 1000
PHP Max Post Size: 256M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected

== WordPress Environment ==
Version: 6.3.1
Site URL: https://y-antelope-xebo.instawp.xyz
Home URL: https://y-antelope-xebo.instawp.xyz
WP Multisite: No
Max Upload Size: 256 MB
Memory limit: 128M
Max Memory limit: 128M
Permalink Structure: /%postname%/
Language: en-US
Timezone: 0
Debug Mode: Inactive

== Theme ==
Name: Twenty Twenty-Three
Version: 1.2
Author: the WordPress team
Child Theme: No

== User ==
Role: administrator
WP Profile lang: en_US
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15

== Active Plugins ==
Elementor
Version: 3.15.3
Author: Elementor.com

== Elementor Experiments ==
Optimized DOM Output: Active
Improved Asset Loading: Active
Improved CSS Loading: Active
Inline Font Icons: Active
Additional Custom Breakpoints: Active
admin_menu_rearrangement: Inactive by default
Flexbox Container: Active
Upgrade Swiper Library: Active
Grid Container: Active
Editor Top Bar: Active
Landing Pages: Active
Nested Elements: Active
Lazy Load Background Images: Inactive by default
Global Style Guide: Active

== Log ==
PHP: showing 1 of 1PHP: 2023-09-02 20:02:34 [notice X 1][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==

````

</details>

**Comment by mcrowell** [comment]
This is normal behavior as Elementor makes sure there's only 1 unique IDs on each page. This has always been a behavior in Elementor.

**Comment by black-eye** [comment]
Yes, I'm afraid, it's not a bug, it's there by design. On the other hand, I don't find it this very fortunate and useful. Yes, there should be only one unique ID on the page, but let us, developers, take control of managing it. Because trying to help us sometimes causes more harm than good.

For example, I usually copy the content from one page to another and in most of the cases there are on-page links from button to section using IDs. This stuff gets broken (and I usually forget about this "feature", so I do not notice it). Another example is duplication of one section to test different design and then later delete the one less appealing. Sometimes this section has an ID, which get lost.

To make it short, roughtly in 80 % of the cases, when I copy & paste something, I need the ID to stay. In less then 20 % I would need to delete it.

So please, let us control this behaviour somehow. For example, delete the ID only when duplicating the section, but don't delete it when pasting the whole page content (there's a high chance you need the whole structure to stay as it is).

Thanks for the consideration

**Comment by nicholaszein** [comment]
Hello @toineenzo,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
As @mcrowell correctly pointed out, this is the expected behavior. You can only have **<ins>one</ins>** unique ID per document, and Elementor can't predict if you already have a similar ID. So we purposefully leave out the ID from being copied from anywhere to anywhere. It's important to always review the settings of copied content if you know they have unique IDs. This is true for any imported template as well.

We have no plans to change this behavior, and we can't accept this as an Enhancement Request either (@black-eye). The impact of allowing IDs to be copied over is far worse than not allowing them to be copied, even if it seems that 80% of the time you don't have this problem.

As a suggestion, IDs should be added as the last step in the design of a page, when you know you have finished it.

I hope you can understand.

Kind regards
