### ISSUE TITLE
⛔ 🐞 Bug Report: Converting a Section with a Min Height set to vw to a Flexbox Container

### ISSUE THREAD

**Issue by tamelander** [elementor/elementor#23669]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When converting a section that has a Min Height vw unit to a flexbox container, it is possible for the container to inherit a Min Height vw unit – though vw is not a selectable Min Height unit for a flexbox container (px, em, rem, vh, custom). As long as I don't change the Min Height, the vw unit sticks. Not sure if this is a bug or meant to be of help for the user?

### Steps to reproduce

Converting a Section with a Min Height set to vw to a Flexbox Container

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


	== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.22
	PHP Version: 8.1.22
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://omitted
	Home URL:  https://omitted
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Stockholm
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 1.0.0
	Author: 
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 4.1.7
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: sv_SE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Asset CleanUp: Page Speed Booster
		Version: 1.3.9.3
		Author: Gabe Livan

	Astra Pro
		Version: 4.1.6
		Author: Brainstorm Force

	Astra Widgets
		Version: 1.2.12
		Author: Brainstorm Force

	CAOS
		Version: 4.7.8
		Author: Daan from Daan.dev

	Code Snippets
		Version: 3.4.2
		Author: Code Snippets Pro

	Cookie Notice & Compliance for GDPR / CCPA
		Version: 2.4.10
		Author: Hu-manity.co

	Custom Facebook Feed Pro Business
		Version: 3.16.1
		Author: Smash Balloon

	Disable Gutenberg
		Version: 3.0
		Author: Jeff Starr

	DoLogin Security
		Version: 3.7
		Author: WPDO

	Duplicate Menu
		Version: 0.2.2
		Author: Jonathan Christopher

	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

	Email Return Path Fix
		Version: 
		Author: Abdussamad Abdurrazzaq

	Enable Media Replace
		Version: 4.1.2
		Author: ShortPixel

	Essential Addons for Elementor
		Version: 5.8.7
		Author: WPDeveloper

	Extensions for Leaflet Map
		Version: 3.5.2
		Author: hupe13

	Formidable Forms
		Version: 6.4.2
		Author: Strategy11 Form Builder Team

	Formidable Forms Pro
		Version: 6.4.2
		Author: Strategy11

	Formidable Views
		Version: 4.0.05
		Author: Strategy11

	Happy Elementor Addons
		Version: 3.8.6
		Author: weDevs

	Headers Security Advanced & HSTS WP
		Version: 5.0.28
		Author: 🐙 Andrea Ferro, Augusto Bombana

	Leaflet Map
		Version: 3.3.0
		Author: bozdoz

	LiteSpeed Cache
		Version: 5.6
		Author: LiteSpeed Technologies

	Loco Translate
		Version: 2.6.4
		Author: Tim Whitlock

	Max Mega Menu
		Version: 3.2.2
		Author: megamenu.com

	Max Mega Menu - Pro Addon
		Version: 2.2.8
		Author: megamenu.com

	Ninja Tables
		Version: 5.0.2
		Author: WPManageNinja LLC

	OMGF
		Version: 5.6.6
		Author: Daan from Daan.dev

	OoohBoi Steroids for Elementor
		Version: 2.1.5
		Author: OoohBoi

	Post SMTP
		Version: 2.5.9.3
		Author: Post SMTP

	Rank Math SEO
		Version: 1.0.122
		Author: Rank Math

	Really Simple SSL
		Version: 7.0.8
		Author: Really Simple Plugins

	Relevanssi
		Version: 4.21.0
		Author: Mikko Saari

	Sidebar Manager
		Version: 1.1.8
		Author: Brainstorm Force

	Simple File List
		Version: 6.1.8
		Author: Mitchell Bennis

	Smash Balloon Instagram Feed
		Version: 6.2.1
		Author: Smash Balloon

	TablePress
		Version: 2.1.7
		Author: Tobias Bäthge

	Widget Detector for Elementor
		Version: 1.2.7
		Author: ElementInvader & FreelancersTools (Ivica Delić)

	Widget Options
		Version: 3.9.6
		Author: Widget Options Team

	WPS Hide Login
		Version: 1.9.9
		Author: WPServeur, NicolasKulka, wpformation


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Active
	Default to New Theme Builder: Active
	Editor Top Bar: Active
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Active
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


````

</details>

**Comment by nicholaszein** [comment]
Hello @tamelander,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an Elementor bug. Here's what we found out:
The Container does not include the **`VW`** unit by design, and it's the intended behavior. 

As you concluded by yourself, if the Section _to-be-converted_ uses a unit that is not part of the Container's units list, it will still inherit the same settings for the converted Container, as long as you don't change the unit for any reason.

### ✅ What you can do to solve your issue:
If you still wish to use the **`VW`** unit on Containers, switch the Container's unit to **`Custom`** and write the whole value as exemplified below:

Example: `40vw`

![image](https://github.com/elementor/elementor/assets/113993460/0c94aff1-5393-497d-8637-e02d335be850)


### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
