### ISSUE TITLE
⛔ 🧩 🐞 Bug Report: JS code doesn't work in mobile

### ISSUE THREAD

**Issue by VolodymyrOnyshchenko** [elementor/elementor#23672]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In a WordPress form that I use for mobile, I'm trying to add a reCaptcha using a Google script:
<script src="https://www.google.com/recaptcha/api.js"></script>
    <script>
    function timestamp() { var response = document.getElementById("g-recaptcha-response"); if (response == null || response.value.trim() == "") {var elems = JSON.parse(document.getElementsByName("captcha_settings")[0].value);elems["ts"] = JSON.stringify(new Date().getTime());document.getElementsByName("captcha_settings")[0].value = JSON.stringify(elems); } } setInterval(timestamp, 500); 
    </script>
it works fine in the desktop version and if I open my mobile form from the desktop but if I open it from mobile I get nothing
I'm also trying to set an alert and it works only on the desktop

### Steps to reproduce

Add this script to your wordpress form and check this form on mobile device

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-05-09-2023.txt](https://github.com/elementor/elementor/files/12523403/system-info-05-09-2023.txt)

**Comment by nicholaszein** [comment]
Hello @VolodymyrOnyshchenko! 

Thank you for submitting your issue! 🙏 

Please clarify if you are referring to an Elementor Pro Form, or if you are talking about another Form generated by another plugin.

### ⛔ 🧩 Note that while we do welcome bug reports, we can't provide support for 3rd-party plugins. This channel is reserved only for <ins>Elementor Bug Reports</ins>.

Best regards

**Comment by nicholaszein** [comment]
@VolodymyrOnyshchenko,

Do you use the Elementor Pro Form on this page or are you using the Gravity Form on the page?

Please clarify, because if you are using the Elementor Pro Form there is a correct way of implementing Google Recaptcha.

Please elaborate and be precise on your answer. Share a screenshot of the form, or a link to the page in question.

**Comment by VolodymyrOnyshchenko** [comment]
Hi Nicholas,
I'm using a custom HTML block for my form
[image: image.png]
[image: image.png]

вт, 5 вер. 2023 р. о 17:36 Nicholas Zein ***@***.***> пише:

**Comment by nicholaszein** [comment]
Hi @VolodymyrOnyshchenko, 

In this case, your issue is probably caused by a cache.

Elementor Pro Forms have their [own integration with Google Recaptcha](https://elementor.com/help/recaptcha-elementor-integration/), and we can only provide support for that. If you have custom code not working, or a 3rd-party plugin issue, you're going to have to find a developer to help you with that or contact the developers of the 3rd-party plugin.

## ⛔ 🧩 Please remember that Elementor GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for 3rd-party support.

### ⚠️ As a gentle reminder, issues that do not follow our 🐞 Bug Report Guidelines may need to be closed without troubleshooting. 

Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏
