### ISSUE TITLE
❌ 🛟 Support Request: Can't edit with Elementor

### ISSUE THREAD

**Issue by FaridBeiranvand** [elementor/elementor#23686]
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

hi all versions starting from 3.15.0 until the last version have a problem that just solve with rollbacking to version 3.14.1. 
when i click on the edit with elementor button page remain in loading and not show the edit section, this is the console error:

```
web-cli.min.js?ver=3.15.3:3 SyntaxError: Unexpected token '>'
    at new Function (<anonymous>)
    at Function.template (underscore.min.js?ver=1.13.4:2:15198)
    at Marionette.TemplateCache.compileTemplate (common.min.js?ver=3.15.3:3:157849)
    at f.TemplateCache.load (backbone.marionette.min.js?ver=2.4.5.e1:24:17324)
    at Function.get (backbone.marionette.min.js?ver=2.4.5.e1:24:16987)
    at n.getTemplate (editor.min.js?ver=3.15.3:3:603389)
    at n._renderTemplate (backbone.marionette.min.js?ver=2.4.5.e1:25:1524)
    at n.render (backbone.marionette.min.js?ver=2.4.5.e1:25:1137)
    at n.render (editor.min.js?ver=3.15.3:3:619377)
    at n.render (editor.min.js?ver=3.15.3:3:670178)
error @ web-cli.min.js?ver=3.15.3:3
catchApply @ web-cli.min.js?ver=3.15.3:3
(anonymous) @ web-cli.min.js?ver=3.15.3:3
Promise.catch (async)
_callee$ @ web-cli.min.js?ver=3.15.3:3
tryCatch @ web-cli.min.js?ver=3.15.3:3
(anonymous) @ web-cli.min.js?ver=3.15.3:3
(anonymous) @ web-cli.min.js?ver=3.15.3:3
asyncGeneratorStep @ web-cli.min.js?ver=3.15.3:3
_next @ web-cli.min.js?ver=3.15.3:3
(anonymous) @ web-cli.min.js?ver=3.15.3:3
(anonymous) @ web-cli.min.js?ver=3.15.3:3
applyRunAfterAsync @ web-cli.min.js?ver=3.15.3:3
applyRunAfter @ web-cli.min.js?ver=3.15.3:3
runInstance @ web-cli.min.js?ver=3.15.3:3
run @ web-cli.min.js?ver=3.15.3:3
internal @ web-cli.min.js?ver=3.15.3:3
onPreviewLoaded @ editor.min.js?ver=3.15.3:3
onPreviewLoaded @ editor.min.js?ver=3.15.3:3
dispatch @ jquery.min.js?ver=3.7.0:2
v.handle @ jquery.min.js?ver=3.7.0:2
VM1241:22 Uncaught (in promise) SyntaxError: Unexpected token '>'
    at new Function (<anonymous>)
    at Function.template (underscore.min.js?ver=1.13.4:2:15198)
    at Marionette.TemplateCache.compileTemplate (common.min.js?ver=3.15.3:3:157849)
    at f.TemplateCache.load (backbone.marionette.min.js?ver=2.4.5.e1:24:17324)
    at Function.get (backbone.marionette.min.js?ver=2.4.5.e1:24:16987)
    at n.getTemplate (editor.min.js?ver=3.15.3:3:603389)
    at n._renderTemplate (backbone.marionette.min.js?ver=2.4.5.e1:25:1524)
    at n.render (backbone.marionette.min.js?ver=2.4.5.e1:25:1137)
    at n.render (editor.min.js?ver=3.15.3:3:619377)
    at n.render (editor.min.js?ver=3.15.3:3:670178)
template @ underscore.min.js?ver=1.13.4:2
Marionette.TemplateCache.compileTemplate @ common.min.js?ver=3.15.3:3
load @ backbone.marionette.min.js?ver=2.4.5.e1:24
get @ backbone.marionette.min.js?ver=2.4.5.e1:24
getTemplate @ editor.min.js?ver=3.15.3:3
_renderTemplate @ backbone.marionette.min.js?ver=2.4.5.e1:25
render @ backbone.marionette.min.js?ver=2.4.5.e1:25
render @ editor.min.js?ver=3.15.3:3
render @ editor.min.js?ver=3.15.3:3
Jn @ underscore.min.js?ver=1.13.4:2
(anonymous) @ underscore.min.js?ver=1.13.4:2
(anonymous) @ underscore.min.js?ver=1.13.4:2
n @ underscore.min.js?ver=1.13.4:2
renderChildView @ backbone.marionette.min.js?ver=2.4.5.e1:24
_addChildView @ backbone.marionette.min.js?ver=2.4.5.e1:24
addChild @ backbone.marionette.min.js?ver=2.4.5.e1:24
(anonymous) @ backbone.marionette.min.js?ver=2.4.5.e1:24
(anonymous) @ underscore.min.js?ver=1.13.4:2
N @ underscore.min.js?ver=1.13.4:2
showCollection @ backbone.marionette.min.js?ver=2.4.5.e1:24
_renderChildren @ backbone.marionette.min.js?ver=2.4.5.e1:24
_renderChildren @ backbone.marionette.min.js?ver=2.4.5.e1:25
render @ backbone.marionette.min.js?ver=2.4.5.e1:25
render @ editor.min.js?ver=3.15.3:3
Jn @ underscore.min.js?ver=1.13.4:2
(anonymous) @ underscore.min.js?ver=1.13.4:2
(anonymous) @ underscore.min.js?ver=1.13.4:2
renderChildView @ backbone.marionette.min.js?ver=2.4.5.e1:24
_addChildView @ backbone.marionette.min.js?ver=2.4.5.e1:24
addChild @ backbone.marionette.min.js?ver=2.4.5.e1:24
(anonymous) @ backbone.marionette.min.js?ver=2.4.5.e1:24
(anonymous) @ underscore.min.js?ver=1.13.4:2
N @ underscore.min.js?ver=1.13.4:2
showCollection @ backbone.marionette.min.js?ver=2.4.5.e1:24
_renderChildren @ backbone.marionette.min.js?ver=2.4.5.e1:24
_renderChildren @ backbone.marionette.min.js?ver=2.4.5.e1:25
render @ backbone.marionette.min.js?ver=2.4.5.e1:25
render @ editor.min.js?ver=3.15.3:3
Jn @ underscore.min.js?ver=1.13.4:2
(anonymous) @ underscore.min.js?ver=1.13.4:2
(anonymous) @ underscore.min.js?ver=1.13.4:2
renderChildView @ backbone.marionette.min.js?ver=2.4.5.e1:24
_addChildView @ backbone.marionette.min.js?ver=2.4.5.e1:24
addChild @ backbone.marionette.min.js?ver=2.4.5.e1:24
(anonymous) @ backbone.marionette.min.js?ver=2.4.5.e1:24
(anonymous) @ underscore.min.js?ver=1.13.4:2
N @ underscore.min.js?ver=1.13.4:2
showCollection @ backbone.marionette.min.js?ver=2.4.5.e1:24
_renderChildren @ backbone.marionette.min.js?ver=2.4.5.e1:24
_renderChildren @ backbone.marionette.min.js?ver=2.4.5.e1:25
initPreviewView @ editor.min.js?ver=3.15.3:3
(anonymous) @ editor.min.js?ver=3.15.3:3
attachDocumentToPreview @ editor.min.js?ver=3.15.3:3
(anonymous) @ editor.min.js?ver=3.15.3:3
Promise.then (async)
onPreviewLoaded @ editor.min.js?ver=3.15.3:3
onPreviewLoaded @ editor.min.js?ver=3.15.3:3
dispatch @ jquery.min.js?ver=3.7.0:2
v.handle @ jquery.min.js?ver=3.7.0:2
Interframe.ts:52 Cannot resolve parent frame. Use fallback values

```

please fix this fatal bug with high priority. thank you

### Steps to reproduce

1)click on the sit with elementor button

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

WordPress 6.3
elementor last version

**Comment by nicholaszein** [comment]
Hello @FaridBeiranvand,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

There is an article that guides you to troubleshoot the issue you're reporting, which is usually caused by a cache or a plugin conflict, especially if you're using incompatible 3rd-party add-ons. 

#### There is no bug here, this is a problem with your installation.
You also did not follow the guidelines for submitting a Bug Report, your report is missing a lot of crucial information, like the System Info for example.

#### To solve your issue, please follow this article: https://elementor.com/help/cant-edit-with-elementor/

----

# ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
