### ISSUE TITLE
⛔ 🛟 Support Request: A warning about the missing "the_content" appears when I try to create a Theme Builder template

### ISSUE THREAD

**Issue by breachag** [elementor/elementor#23713]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

i cant add elements to elementor (header, error 404, popup .....) in the theme builder. a screen shows sorry the content area was not found in your page.  you must call 'the_content' function in the current template, in order for elementor to work in this page
![Plugins ‹ breach website — WordPress - Google Chrome 08_09_2023 16_36_10](https://github.com/elementor/elementor/assets/141773954/b79f8b87-66ef-4b43-9709-b457fce5ef34)

### Steps to reproduce

1- templates
2- theme builder
3- add new
4- header
5- create template

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-breach.website-08-09-2023.txt](https://github.com/elementor/elementor/files/12561464/system-info-breach.website-08-09-2023.txt)

**Comment by nicholaszein** [comment]
Hello @breachag,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

You are using a Block theme (Spectra One) on your website. Block themes do not add support for classic PHP function like **`the_content`**. For Elementor to work properly you need a classic theme that has support for PHP functions like the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme, or even one of the more popular themes like the [GeneratePress](https://wordpress.org/themes/generatepress/), [Blocksy](https://wordpress.org/themes/blocksy/), or [Astra](https://wordpress.org/themes/astra/) themes.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

----

### ⚠️ Elementor Developer Edition detected!

We noticed that you're using the **_Elementor Beta (Developer Edition)_** plugin. This edition is a playground for developers to test their plugins and themes with the most recent features of Elementor, and it's not quite intended for live websites.

### 🧪 Due to the experimental nature of this edition, we're unable to provide support for it. 

#### 🔄 Please, [switch back to a stable version](https://elementor.com/help/revert-to-release-from-developer-edition/) if you're working on a production site.

----

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
