### ISSUE TITLE
⛔ 🐞 Bug Report: Maintenance Mode template does not show the template Background color on the entire page

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#23779]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

I created a page template and activated it for the maintenance mode.

In the editor, I styled the page to have a green background for the whole page (

![image](https://github.com/elementor/elementor/assets/5083355/f0b191d2-ad55-4b0d-9c71-6b53211c6840)

That background works in the front end when logged in: 
![image](https://github.com/elementor/elementor/assets/5083355/e743eda7-e719-412b-8cd6-5b2846068404)

But for a visitor (not logged in), the background color isn't working.

![image](https://github.com/elementor/elementor/assets/5083355/c7d8bd8e-ceab-4c23-8909-442189049c33)

### Steps to reproduce

1. Create a page template with a colored background
2. Set the maintenance mode with that page template
3. Logout (or open a private browser) and look at the site. The background color isn't there.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.7.38
	PHP Version: 8.0.30
	PHP Memory Limit: 32M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	WP Multisite: No
	Max Upload Size: 128 Mo
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: fr-CA
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: fr_CA
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Columns
		Version: 4.6.1
		Author: AdminColumns.com

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Custom Post Type Permalinks
		Version: 3.5.2
		Author: Toro_Unit

	Duplicator
		Version: 1.5.5.1
		Author: Duplicator

	DynamicConditions
		Version: 1.6.2
		Author: RTO GmbH

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.2.4
		Author: Dudaster.com

	Elementor
		Version: 3.16.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.0
		Author: Elementor.com

	Enable Media Replace
		Version: 4.1.2
		Author: ShortPixel

	Filter Everything — WooCoomerce Product & WordPress Filter
		Version: 1.7.15
		Author: Andrii Stepasiuk

	Filter Everything PRO
		Version: 1.7.15
		Author: Andrii Stepasiuk

	LiteSpeed Cache
		Version: 5.6
		Author: LiteSpeed Technologies

	Pods - Custom Content Types and Fields
		Version: 3.0.1
		Author: Pods Framework Team

	Yoast SEO
		Version: 21.1
		Author: Team Yoast


== Fonctionnalités ==
	Custom Fonts: 3
	Custom Icons: 0

== Intégrations ==
	
	recaptcha: Actif


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Inactive by default
	Landing Pages: Inactive
	Éléments imbriqués: Inactive by default
	Lazy Load Background Images: Active
	Global Style Guide: Inactive by default
	Page Transitions: Inactive
	Notes: Inactive
	Envois de formulaire: Active
	Scroll Snap: Inactive
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default



````

</details>

**Comment by nicholaszein** [comment]
Hello @vgstef,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- We tried to reproduce your issue with the latest version of Elementor and without any cache, and as you can see in the video below the Maintenance Mode template appeared with the entire background of the document with the correct background color.


https://github.com/elementor/elementor/assets/113993460/db40f7e3-fff5-4e25-8b11-d487787b53cb



- We see you use a LiteSpeed server with the LiteSpeed Cache plugin. Your issue is most likely caused by your cache.

### ✅ What you can do to solve your issue:
1. Go to your WordPress **`Dashboard`** > **`Elementor`** > **`Tools`** > **`General`** and click to **`Regenerate CSS & Data`**.
2. In your LiteSpeed Cache Settings page, purge all levels of cache.
3. In your LiteSpeed Cache Settings make sure you are not applying the following CSS optimizations, as they usually can cause conflicts with Elementor:
   - CSS Combine
   - Generate UCSS
   - CSS Combine External and Inline
   - Load CSS Asynchronously
   - CSS Per URL
   - Inline CSS Async Lib
4. Purge the cache again, especially your browser cache.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
