### ISSUE TITLE
⛔ 🐞 Bug Report: Loop Carrousel Navigation Arrows are missing after updating to 3.16

### ISSUE THREAD

**Issue by progenthemes** [elementor/elementor#23772]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Updated to Elementor Pro 3.16.1 and the carousel broke on my client's carousel, the carousel is showing a custom loop. When updating to latest version the navigation arrow vanish. I tried all the usual stuff like clearing cache, regenerate css and even went through the steps of recreating it and nothing worked. I had to roll back to 3.15 for the navigation to start working again. 

### Steps to reproduce

Make a carousel and update to 3.16.x and it breaks. 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-escrowleaders.com-13-09-2023.txt](https://github.com/elementor/elementor/files/12598701/system-info-escrowleaders.com-13-09-2023.txt)

**Comment by hein-obox** [comment]
@progenthemes 
Maybe revert to 3.15 and upgrade it again next week?
https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/

**Comment by nicholaszein** [comment]
Hello @progenthemes,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- We tried to reproduce your issue, but as you can see in the video below the Navigation Arrows appeared as expected. Keep in mind that while I am using Products to demonstrate the issue, it also applies to posts. There are no differences between queries in the Loop Carousel widget. The navigation arrows still behave the same way using any query.


https://github.com/elementor/elementor/assets/113993460/5215d1ce-b97b-44f3-8d4b-86274234eaf3

----
- I see you have updated to Elementor Core version 3.16.2, and Elementor Pro version 3.16.0. Sice you submitted your issue, we have released two new versions, v3.16.3 for the Elementor Core, and v3.16.1 for Elementor Pro.
- I also see your hosting is SiteGround, and you are using the SiteGround Optimizer plugin paired with Server Cache. Your issue is most likely caused by this cache.


### ✅ What you can do to solve your issue:
- ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

- 🗑️ **Clear the cache:** Clear all levels of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and most importantly **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
   - It's important to note that SiteGround's Server cache has a history of not cleaning up after itself even when you manually purge the cache, requiring you to perform this task at least twice, sometimes even more.
   - Before updating try to temporarily disable all levels of cache that apply to your website. This helps prevent conflicts with scripts and styles after updating. In fact, this is the recommended procedure before any update in WordPress, for any theme, plugin, or even core WordPress. The cache can cause all sorts of issues if not handled correctly.
- 🔄 **Update Elementor and Elementor Pro** to the latest version and don't forget to execute the crucial Data Updater procedure. This will ensure Elementor applies all the changes that affect your templates and styles.
- 🗑️ **Clear the cache again!** Perform the same steps as before.

For further troubleshooting, please refer to this document:
https://elementor.com/help/update-issues/ 

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
