### ISSUE TITLE
Closed a Bug Report You Shouldn’t have

### ISSUE THREAD

**Issue by wpturnedup** [elementor/elementor#23825]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

https://github.com/elementor/elementor/issues/23820

Elementor’s changelog clearly states…

“Tweak: Enabled Flexbox Container feature by default for new installations”

This clearly means Elementor is fully capable of determining what is a new installation and what isn’t a new installation.

You assume everyone that uses Elementor understands popup warnings or cares to read them, before taking action/inaction.

Based on the links you provided within that other bug report, it clearly says that sections can only be used by duplicating a section (I.e., converting to a container.

New installs do not have sections. It’s not a hard concept to understand, or is it?

### Steps to reproduce

See other ticket.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

See other ticket

**Comment by nicholaszein** [comment]
@wpturnedup,

# ⛔ 🐞 This is not a Bug. Please don't insist. 

We want people to have the option to switch off Containers if they want to, not to mention Sections can still appear side-by-side with Containers, and you can still import a template with Sections on a site that has Containers activated.

### This is intentional and the expected behavior. We are not going to change this for the time being.

# ⛔ ⚠️ Do not use GitHub issues to request features. Please respect our Guidelines.

Kind regards
