### ISSUE TITLE
⛔ 🐞 Bug Report: Should Not Be Able to Disable the Flexbox Container Feature on New Sites

### ISSUE THREAD

**Issue by wpturnedup** [elementor/elementor#23820]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

**Should Not Be Able to Disable the Flexbox Container Feature on New Sites**

New builds default to using Containers. Therefore, there should be no option to disable this feature, as it effectively renders the site "dead" (i.e., content-less).

Help protect people from themselves.

### Steps to reproduce

1. Set up new Elementor site
2. Add Elementor widgets to a page
3. Disable Elementor's Flexbox Container feature

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: mariadb.org binary distribution v10.4.10
	PHP Version: 8.1.23
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://elementor-pro.local
	Home URL: https://elementor-pro.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.16.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.1
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
PHP: showing 1 of 1PHP: 2023-09-15 15:24:45 [notice X 1][..\wp-content\plugins\elementor\core\upgrade\manager.php::63] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2023-09-15 18:05:38 [error X 1][https://elementor-pro.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.3:3:601264] Cannot read properties of null (reading 'id') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by sreidnoe** [comment]
Feature does give an alert when deactivating.

When I switched to containers, it was not on at all which is where I lost
the render after the update.

An if/else checking to see if that feature is tuned on and sending an alert
that can be dismissed with “do not show this again”

And onClick event for both the widget selector and “covert” to container
button for the warning to run. To send the same alert that in order to use
containers “{features} must be used”.

Info linking to webpage content

Or even better yet, use bloggers, get on podcasts, get with your web devs
with a social audience, put it in your community chat of over 100K use your
authority.

**Comment by nicholaszein** [comment]
Hello @wpturnedup,

## ⛔ While reviewing your report we concluded this is not a bug caused by Elementor.

If you want to **Request a Feature,** please submit your request in the right channel, GitHub issues are reserved only for Bug Reports!

However...

### ⛔ 🚀 After reviewing your request, we have decided not to add this to our roadmap.

We won't limit what our users can do, and we don't have any intention of forcing our users to use a feature that they are not ready to use. This is not how Elementor works. Containers are here to stay, but until we make them permanent (which will take a long time), we want to give every user the possibility to switch at their own pace, and still be able to use Sections when needed.

@sreidnoe is correct in pointing out that there are plenty of alerts explaining the risks of disabling Containers. Our [documentation](https://elementor.com/help/container-faq-and-troubleshooting/#:~:text=What%20happens%20if%20I%20decide%20to%20deactivate%20containers%3F) also makes it clear the consequences of deactivating Containers, and we also have plenty of [tutorials](https://www.youtube.com/watch?v=JTSB49E5wro&list=PLZyp9H25CboFLsiad-zQOs-o-pGiv0a54) on YouTube, Q&As on Facebook, and even plenty of [Blog Posts.](https://elementor.com/blog/search/container/)

For now, that's all. 

Thank you for your feedback! 🙏 

Kind regards
