### ISSUE TITLE
⛔ 🛟 Support Request: I can't edit the Shop Page directly

### ISSUE THREAD

**Issue by aleynazsalmanz** [elementor/elementor#23822]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I have been making my cake website using Elementor, however I keep getting the issue of not being able to edit the main page for "cakes". The only option i get is "debug elementor". i have a deadline for this projectt in a week and i need this to be sorted as soon as possible. I'll attach two screenshots: one which shows the "edit with elementor" and the one that doesn't let me.

![Screenshot 2023-09-15 at 23 13 02](https://github.com/elementor/elementor/assets/139361542/4f16a427-a989-4d32-9060-aa24bcb0b878) (doesn't show the edit with elementor option.)

![Screenshot 2023-09-15 at 23 14 09](https://github.com/elementor/elementor/assets/139361542/427e9d72-22ef-4708-ad46-415c113b28fe) (other pages let me edit )

### Steps to reproduce

I just need to be able to edit the page, which isn't an option at the moment.

Everytime, i open the "cakes" page through WP, it just doesn't allow me to open and allow to edit.

I dont understand how i can give you steps to reproduce .

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - GPL v8.0.34
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 60M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://cakesbyaleyna.co.uk/my_business
	Home URL: https://cakesbyaleyna.co.uk/my_business
	WP Multisite: No
	Max Upload Size: 60 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Woostify
	Version: 2.2.5
	Author: Woostify
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0

== Active Plugins ==
	Akismet Anti-Spam: Spam Protection
		Version: 5.2
		Author: Automattic - Anti Spam Team

	Backuply
		Version: 1.1.8
		Author: Softaculous

	Elementor
		Version: 3.16.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Google Listings and Ads
		Version: 2.5.2
		Author: WooCommerce

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 10.2.1
		Author: HubSpot

	Jetpack
		Version: 12.4
		Author: Automattic

	MailPoet
		Version: 4.24.0
		Author: MailPoet

	Pinterest for WooCommerce
		Version: 1.3.8
		Author: WooCommerce

	Razorpay for WooCommerce
		Version: 4.5.4
		Author: Team Razorpay

	TI WooCommerce Wishlist
		Version: 2.7.4
		Author: TemplateInvaders

	WooCommerce
		Version: 8.0.2
		Author: Automattic

	WooCommerce Payments
		Version: 6.3.2
		Author: Automattic

	WooCommerce Shipping & Tax
		Version: 2.3.2
		Author: WooCommerce

	Woocommerce Sidebar Category Accordion
		Version: 1.1.3
		Author: Marc Randall

	Yoast SEO
		Version: 21.1
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elements Usage ==
	
	wp-page : 4
		button : 1
		container : 32
		divider : 1
		heading : 14
		icon : 3
		image : 7
		image-box : 11
		spacer : 1
		text-editor : 17


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Editor Top Bar: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Pages Panel: Inactive by default
	Global Style Guide: Active


== Log ==
	
JS: showing 3 of 3JS: 2023-08-17 01:26:05 [error X 1][https://cakesbyaleyna.co.uk/my_business/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.15.2:3:107472] Routes: `panel/page-settings/yoast-tab` not found. 
JS: 2023-08-28 13:40:51 [error X 2][https://cakesbyaleyna.co.uk/my_business/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.2:3:1106601] $ is null 
JS: 2023-08-29 09:38:29 [error X 1][https://cakesbyaleyna.co.uk/my_business/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.15.2:3:107472] Routes: `panel/editor/actions` not found. 

PHP: showing 1 of 1PHP: 2023-08-17 23:00:30 [notice X 2][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 9 of 92023-09-10 16:23:00 [info] elementor::elementor_updater Started 
2023-09-10 16:23:00 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-10 16:23:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.2',
  'to' => '3.16.0-dev4',
)]
2023-09-10 16:23:00 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-10 16:23:00 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2023-09-10 16:23:00 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2023-09-10 16:23:00 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-10 16:23:00 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-10 16:23:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.2',
  'to' => '3.16.0-dev4',
)]



== Elementor - Compatibility Tag ==
	

				

````

</details>

**Comment by aleynazsalmanz** [comment]
Please respond or help as soon as possible, as my whole masters project depends upon this.

**Comment by nicholaszein** [comment]
Hello @aleynazsalmanz,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. GitHub issues are for Bug Reports only!

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

You are trying to edit the WooCommerce Shop Page directly. When you assign a page to be the **`Shop Page`** in the **`WooCommerce Settings`** > **`Products`** > **`General`** page, it automatically becomes a Product post-type Archive Page. Archive Pages can't be edited directly, and even if you use the Block editor to edit these pages, the changes won't appear on the front end. This is how WordPress always worked with Archive Pages, including the Posts (Blog) page you define in your Dashboard > Settings > Reading page.

If you follow the link in this [article](https://elementor.com/help/how-to-fix-the-preview-could-not-be-loaded-error/#:~:text=website%20with%20Elementor.-,Note%3A,-If%20this%20message), you'll see a notice explaining that you can't edit archive pages directly. You need to use Elementor Pro's Theme Builder and create a Product Archive template for your Shop Page.

Here's another article that also explains the same limitation:
https://elementor.com/help/the-content-area-was-not-found-error/#:~:text=of%20possible%20solutions%3A-,Archive%20pages,-When%20creating%20or

Note that this is not an Elementor limitation, it's a WordPress limitation, and it was always like this. Archive Pages don't have the essential functions that Elementor requires to edit them.

----

### ⚠️ Elementor Developer Edition detected!

We noticed that you're using the **_Elementor Beta (Developer Edition)_** plugin. This edition is a playground for developers to test their plugins and themes with the most recent features of Elementor, and it's not quite intended for live websites.

### 🧪 Due to the experimental nature of this edition, we're unable to provide support for it.

### 🔄 Please, [switch back to a stable version](https://elementor.com/help/revert-to-release-from-developer-edition/) if you're working on a production site.

----


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
