### ISSUE TITLE
⛔ 🛟 Support Request: Slider not working after the "Paste from other website" option

### ISSUE THREAD

**Issue by vladninja** [elementor/elementor#23844]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When the user uses a Container with a Slider option (from Style tab) the slide is broken on the first slide.
After the full page load, only the first slide will be shown (autoplay option not working) but user is able to change a slide with a gestures.
It's generate a flick effect during the page loading, so it's easy to see.
The problem here is a Paste from other website. I compared a 2 versions of JSONs with the same settings but 1 of them not working, and second one working good.
The 1 difference there is a ```"background_slideshow_slide_duration": "1900",
      "background_slideshow_transition_duration": "1000",```

When you paste data from other website some mechanism replaces numbers by the strings. In the most cases it's not causes any issues, but not for the Swiper which accept only the numbers! https://swiperjs.com/swiper-api

Probably the Slider widget also affected (not tested yet).

### Steps to reproduce

1. Create a Container with a slider option on website 1 (screen with example options)
2. Copy Container
3. On a website 2 use Paste from other website option

-> the slider not working anymore

![image](https://github.com/elementor/elementor/assets/76119088/bd13ea1f-7735-48a8-9fda-9141fe137a4f)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: MySQL Community Server - GPL v8.0.31
	PHP Version: 7.4.33
	PHP Memory Limit: 
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: No
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://localhost:8083
	Home URL: http://localhost:8083
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==

	Elementor
		Version: 3.14.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.0
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Editor Top Bar: Active
	Landing Pages: Active
	Nested Elements: Active
	Nested Accordion: Inactive by default
	Lazy Load Background Images: Active
	Global Style Guide: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Active


== Log ==
	


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	
				

````

</details>

**Comment by vladninja** [comment]
Solution:
in the ``frontend.js`` file in the method ``getSwiperOptions`` for ``speed`` and ``deplay`` parseInt() option needs to be added to provide a fix for the current websites which used "Paste from other website" before

**Comment by vladninja** [comment]
As our client mentioned, he can break that in some way which we do not know (after the paste and after some changes later), but the issue is the same strings instead of numbers

**Comment by nicholaszein** [comment]
Hello @vladninja,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

As [noted in the documentation](https://elementor.com/help/how-do-i-copy-elements-from-one-site-to-another/#:~:text=or%20Ctrl%2DV.-,Note,-%3A%20in%20order%20to), to copy and paste from one site to another, both sites need to have identical settings and features. They also need to be on the same version and have the same add-ons installed.

It seems in your case that you are importing content from an old website to a new one, where settings for the feature in question have changed. This is causing the issue you are reporting because of incompatibility between the two installations. As an example, here is a video showing the feature working when two websites have identical settings and are on the same version:


https://github.com/elementor/elementor/assets/113993460/659b1833-0b61-4322-8a00-6d965ea03e2e



### ✅ What you can do to solve your issue:
Ensure both sites are identical in Elementor versions and enabled features, as well as installed add-ons.

### 👍 For now, that's all we can help with. 


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
