### ISSUE TITLE
❌ 🐞 Bug Report: [The Beta Menu Containers] Dont work the Z-Index

### ISSUE THREAD

**Issue by DonKolia** [elementor/elementor#23853]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The Z-Index of containers simply does not work.

### Steps to reproduce

The Z-Index of containers simply does not work. I mean here;
![image](https://github.com/elementor/elementor/assets/55564649/ecba1a27-9c61-4b78-bbd3-24a7556d93f1)

Original header background: 
![image](https://github.com/elementor/elementor/assets/55564649/67bc883e-d68c-47a7-85ad-ca9e8dfc2bf0)

Dropdown Content container is bug.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-minetenia.com-19-09-2023.txt](https://github.com/elementor/elementor/files/12665390/system-info-minetenia.com-19-09-2023.txt)

**Comment by nicholaszein** [comment]
Hello @DonKolia, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- ✒️ **Clear and concise title:** Please provide a clear and concise title that gives context to your issue.

- 💬 **Description:** In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our environments. Be thorough.

Without them, we simply can't help. 😕 

Keep in mind that if the problem is related to the content below the header appearing in front of the menu, you need to increase the z-index of the header Container that wraps around the Menu widget, not the Menu widget, nor the container inside it. Z-index works on a multi-level basis, not on a document basis.

Please refer to these articles to understand how to properly use z-index. This is not a bug caused by Elementor.
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index
https://blog.hubspot.com/website/z-index#:~:text=z%2Dindex%20is%20the%20CSS,a%20lower%20z%2Dindex%20value.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Best regards
