### ISSUE TITLE
⛔ 📊 🐞 Bug Report: Page Transitions don't use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by mercadder** [elementor/elementor#23898]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Pagespeed gives this error: Does not use passive listeners to improve scrolling performance, file:  mywebsite/wp-content/plugins/elementor-pro/assets/js/page-transitions.min.js?ver=3.17.0-cloud4

Can you please revise this.

### Steps to reproduce

Just run pagespeed with an Elementor Cloud website

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-ai4k.eu-26-09-2023.txt](https://github.com/elementor/elementor/files/12725120/system-info-ai4k.eu-26-09-2023.txt)

**Comment by nicholaszein** [comment]
Hello @mercadder,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- The script in question is responsible for handling the [Page Transitions](https://elementor.com/help/page-transitions/) experimental feature on your site. 
- The Google Page Speed test suggests to _"Consider marking your touch and wheel event listeners as passive to **improve your page's scroll performance.**"_. This suggestion doesn't apply to the Page Transitions, since they will always cover the entire page, and will only appear briefly. They do not require any user interaction.

### 👍 For now, that's all we can help with. 

----

### 🛟 This is more of a support question, not really something we can help with here. 


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
