### ISSUE TITLE
⛔ 🛟 Support Request: Serve static assets with an efficient cache policy: Pagespeed error Elementor Cloud

### ISSUE THREAD

**Issue by mercadder** [elementor/elementor#23899]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

This problem happens in Elementor hosting website. Pagespeed gives this error: Serve static assets with an efficient cache policy.

### Steps to reproduce

Run a elementor hosted website in pagespeed.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-ai4k.eu-26-09-2023 (1).txt](https://github.com/elementor/elementor/files/12725184/system-info-ai4k.eu-26-09-2023.1.txt)

**Comment by nicholaszein** [comment]
Hello @mercadder! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment]
Hello @mercadder,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- It seems you are using WP Rocket on your website. This means the plugin is the one responsible for setting up an efficient policy.
- Elementor GitHub issues are meant to report bugs with the Elementor plugin. This does not qualify as a bug, as there is nothing broken in the Elementor plugin or the Elementor Hosting service. 
- Elementor Hosting websites use proper headers for cache through the Cloudflare CDN by default. I've tested on an Elementor Hosting website and did not receive this warning. 
- I've run the Page Speed Insights on your site, and the items that need to be served with an efficient cache policy are not at all related to Elementor. You seem to have a few **webp images** that do not have a proper policy (see how to to solve it below), and **scripts from Hubspot** that do not have a cache policy. The article shared below suggest a few ways you can fix these issues. As for the **Cloudflare script, it's a false positive** and it doesn't really affect performance or SEO in any way, despite the warning.

![image](https://github.com/elementor/elementor/assets/113993460/6624ee10-9ca3-4a9e-bf15-0db91411eb2b)


### ✅ What you can do to solve your issue:
- Please follow [the instructions](https://wp-rocket.me/google-core-web-vitals-wordpress/serve-static-assets-with-an-efficient-cache-policy/#:~:text=the%20.htaccess%20file.-,Note%3A,-WP%20Rocket%20will) on [this article](https://wp-rocket.me/google-core-web-vitals-wordpress/serve-static-assets-with-an-efficient-cache-policy/) from WP Rocket to learn how to properly configure it to set an efficient cache policy for your images.
- If you are seeing a problem with your Elementor Hosting website, you need to contact Elementor Support through your [Elementor Account](https://my.elementor.com).


## 🛟 This is more of a support question, not really something we can help with here. 


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
