### ISSUE TITLE
⛔ 🛟 Support Request: Elementor not loading editor

### ISSUE THREAD

**Issue by nne** [elementor/elementor#23918]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

Greetings,

I get this error when i try to edit with elementor:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

I meet all the system requirement and have deativated all plugins. 

Please help out.

### Steps to reproduce

1) click on the "edit with elementor"
2.) elementor loads forever without opening the edit mode
3) try safe mode. still the same issue
4) installed 3.16.4. still the same issue.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.32
	PHP Version: 8.1.22
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://hammam-sultana-renens.ch
	Home URL: https://hammam-sultana-renens.ch
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 640M
	Max Memory limit: 640M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Medical Spa
	Version: 1.0.5
	Author: Rara Theme
	Child Theme: Yes
	Parent Theme Name: Spa and Salon
	Parent Theme Version: 1.2.7
	Parent Theme Author: Rara Theme

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0

== Active Plugins ==
	Elementor
		Version: 3.16.0
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com


== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Upgrade Swiper Library: Inactive
	Grid Container: Inactive
	Editor Top Bar: Inactive
	Landing Pages: Inactive
	Nested Elements: Inactive
	Lazy Load Background Images: Inactive
	Global Style Guide: Inactive


== Log ==
	
JS: showing 7 of 7JS: 2020-12-04 12:54:59 [error X 3699][https://dev-sultana-hamman.pantheonsite.io/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read property \'clone\' of null 
JS: 2020-12-04 12:55:04 [error X 91][https://dev-sultana-hamman.pantheonsite.io/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read property \'changestop\' of null 
JS: 2020-12-10 10:08:41 [error X 1][https://dev-sultana-hamman.pantheonsite.io/wp-admin/post.php?post=1385&action=elementor:2:16] Paylike is not defined 
JS: 2020-12-10 10:09:26 [error X 1][https://dev-sultana-hamman.pantheonsite.io/wp-admin/post.php?post=1385&action=elementor:7:12] Unexpected token \',\' 
JS: 2020-12-10 10:27:29 [error X 14][https://dev-sultana-hamman.pantheonsite.io/wp-admin/post.php?post=1385&action=elementor:7:4] Unexpected token \')\' 
JS: 2020-12-10 10:28:59 [error X 1][https://dev-sultana-hamman.pantheonsite.io/wp-admin/post.php?post=1385&action=elementor:13:1] missing ) after argument list 
JS: 2023-09-29 09:49:35 [error X 1][https://hammam-sultana-renens.ch/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.16.4:2:2869] elementor_new_template_form_controls is not defined 

Log: showing 20 of 252021-11-30 15:51:22 [info] Elementor/Upgrades - _on_each_version Finished 
2021-11-30 15:51:22 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-11-30 15:51:22 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-11-30 15:51:22 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Start  
2021-11-30 15:51:22 [info] Elementor/Upgrades - _v_3_4_8_fix_font_awesome_default_value_from_1_to_yes Finished 
2021-11-30 15:51:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.4.8',
)]
2021-11-30 15:51:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.4.8',
)]
2023-09-27 14:19:05 [info] elementor::elementor_updater Started 
2023-09-27 14:19:05 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-27 14:19:05 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-27 14:19:05 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Start  
2023-09-27 14:19:05 [info] Elementor/Upgrades - _v_3_5_0_remove_old_elementor_scheme Finished 
2023-09-27 14:19:05 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2023-09-27 14:19:05 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2023-09-27 14:19:05 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2023-09-27 14:19:05 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2023-09-27 14:19:05 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-27 14:19:05 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-27 14:19:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.16.4',
)]
2023-09-27 14:19:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.8',
  'to' => '3.16.4',
)]

PHP: showing 1 of 1PHP: 2023-09-29 11:09:54 [warning X 3][../wp-content/plugins/elementor/app/modules/import-export/module.php::753] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment]
Hello @nne,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

As an example, here's an in-depth article explaining how to handle Elementor Editor loading issues:
https://elementor.com/help/cant-edit-with-elementor/

We noticed that you're using the **_Elementor Beta (Developer Edition)_** plugin. This edition is a playground for developers to test their plugins and themes with the most recent features of Elementor, and it's not quite intended for live websites.

### 🧪 Due to the experimental nature of this edition, we're unable to provide support for it. 

### 🔄 Please, [switch back to a stable version](https://elementor.com/help/revert-to-release-from-developer-edition/) if you're working on a production site.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
