### ISSUE TITLE
⛔ 🛟 Support Request: My Menu is missing styles intermittently when viewed on the front-end 

### ISSUE THREAD

**Issue by 3in1Designer** [elementor/elementor#23998]
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

![Screenshot (30)](https://github.com/elementor/elementor/assets/147489021/bb08ff30-9d88-457e-9979-7eb8b34abf39)

Every once in a while I get menu displayed like in the picture but every time I open it in elementor it does not show any problem, but still displays menu wrong if I open my website on new tab or on the phone. (rutadesign.dk)

can see that that menu rearrangement is inactive but how to fix it?

### Steps to reproduce

just open rutadesign.dk and could see that menu displayed wrong

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

[REDACTED]

**Comment by betatester07** [comment]
Hi,

there are missing some .css files regarding the menu (they are loaded with HTTP which is not permitted in HTTPS context..). No idea why, might be some bug in the new dev version.

However, according to your system info, you are using `Elementor 3.17.0-dev2` together with `Elementor Pro 3.16.2`.

Things to consider:
- it is probably not a good idea to mix different major versions of Elementor and Elementor Pro (3.17 vs 3.16)
- do not use dev / beta version if you expect stable behavior or want to have production ready site (unless you want to test some new functionality)

Cheers

**Comment by nicholaszein** [comment]
Hello @3in1Designer,

Thanks for contacting us! 🙏 

As @betatester07 correctly pointed out, your issue seems to be related to mixed content and also cache.

I have [written a tutorial on the Elementor Global Community](https://www.facebook.com/groups/Elementors/posts/2661661010626335/) on Facebook that should help fix this issue. Please try following that tutorial.

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
