### ISSUE TITLE
📚 🧩 ❓ Developer Question: Real Cookie Banner is marked as "not compatible" in Elementor Hosting

### ISSUE THREAD

**Issue by matzeeable** [elementor/elementor#24174]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hey!

Here is Matthew, one of the developers behind [Real Cookie Banner](https://wordpress.org/plugins/real-cookie-banner/).

When I try to install the plugin on [Elementor Hosting](https://elementor.com/wordpress-hosting/), I get the following error:

![image](https://github.com/elementor/elementor/assets/1008534/69bed912-f572-41f4-a0f0-f6bf10b4d68f)

I already was in contact with the Elementor support, and they told me, that I needed to open an issue here. After some research, I found that Real Cookie Banner is "Incompatible" on Elementor Hosting: https://elementor.com/help/elementor-hosted-incompatible-plugins/

We would also like to recommend Elementor Hosting to our users, but we currently have to advise against it. What is the technical reason that Real Cookie Banner is incompatible? :-)

### Steps to reproduce

1. Sign up for Elementor Hosting
2. Try to install Real Cookie Banner plugin

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Not needed

**Comment by nicholaszein** [comment]
Hello @matzeeable,

Thank you for reaching out! 🙏 

After checking with the team, we concluded Cloudflare flagged your plugin as a possible XSS attack. Since we use Cloudflare for our networking infrastructure, we marked your plugin incompatible with our hosting service.

At the time of this decision, a user reached out to our support complaining about having trouble using your plugin, and after many discussions, they also reported reaching out to you to help solve this issue and said you were adjusting your code in a beta version to avoid it being recognized as an XSS attack by Cloudflare.

Do you happen to know if since then you can confirm this problem was fixed? The incident happened around December 2021.

Kind rgards

**Comment by matzeeable** [comment]
Hey @nicholaszein !

Yeah, this issue got fixed and Cloudflare does no longer recognize the request payload as XSS attack, when creating a service in Real Cookie Banner. We have a lot of customers and users using Cloudflare and we got feedback that all is working fine.

Have you tested Real Cookie Banner again on a Elementor Hosting? In general, just install the plugin, navigate to *Cookies > Services > Add service > Create individual service* and put a e.g. `<script>console.log("Test");</script>` into the *Code on opt-in* textfield and *Save*.

**Comment by nicholaszein** [comment]
Thank you @matzeeable!

Let me check with the team responsible for the hosting plugins and I'll get back to you when they have a position.

Kind regards

**Comment by nicholaszein** [comment]
Hi @matzeeable,

As of last week, your plugin was reinstated as supported by Elementor Hosting websites. Thank you for reaching out! 🙏 

If you're interested, Elementor has a Developers Partnership Program that you can join if you have support for Elementor. This would ensure better communication between us. You can submit your request to join the partnership [here](https://elemn.to/devloop**).

Kind regards
