### ISSUE TITLE
⛔ 🐞 VideoPress video is not playing on frontend (not logged in) as a container background video

### ISSUE THREAD

**Issue by ZoltanGalCMDesign** [elementor/elementor#24448]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I wanted to try VideoPress as Elementor added support for it in the video widget. So I tried it in the video widget and it works fine. But when I want to use the video as a container background, it will not play on the frontend (not logged in). Interestinly it plays in the Elementor editor, only on the frontend fails to show the video.

### Steps to reproduce

Uploaded VideoPress plugin, uploaded video, copied the video full URL from media library, inserted the url in the background video field in container style settings. The video plays in the Editor but will not play on frontend (not logged in)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-hoteldivinus.cmdesign.dev-29-11-2023.txt](https://github.com/elementor/elementor/files/13500269/system-info-hoteldivinus.cmdesign.dev-29-11-2023.txt)

**Comment by TakacsAdrian** [comment]
i have the same problem

**Comment by vitozev** [comment]
I'm able to reproduce the same issue on my site as well.

**Comment by Johndo36** [comment]
Same problem here.

**Comment by rplawate** [comment]
Exactly the same issue

**Comment by nicholaszein** [comment]
Hello everyone!

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

The integration with VideoPress is only supported in the Video widget.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v4.2.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elemn.to/changelog)

Cheers 🥂 

----

If you think this is still an issue caused by Elementor after updating to the latest version, and can reproduce it consistently after following our [Contribution Guidelines](https://elemn.to/gh-contributing-bug-reports), feel free to open a new 🐞 [Bug Report](https://elemn.to/gh-new-bug-report), and we will be happy to review your case.
