### ISSUE TITLE
🔗 ⛔ 🐞 Elementor Background Video not working with external Video URL by Jetpack Videopress

### ISSUE THREAD

**Issue by Johndo36** [elementor/elementor#24467]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor's Background Video Feature stopped working for Jetpack Videopress Videos (about 1 month ago).

The videos meet all the video specs and play normally, when they are added through the video widget, but not so much, when you add them as a background video using the URL field.

It shows up in editor view, but not on the frontend. When you check the source code, elementor doesn't output the html video tag at all.

### Steps to reproduce

Create a container or block, have an active jetpack videopress plugin installed and upload a video.
As soon as the video is compressed and ready to go, copy/paste the URL into the container background video URL field.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[REMOVED by Moderator]

**Comment by rplawate** [comment]
I am also facing this exact issue

**Comment by Johndo36** [comment]
> Same problem #24448

Ou thanks for pointing that one out. I didn't see it, when I was searching for similar problems. I closed this issue here.

**Comment by nicholaszein** [comment]
Hi, @Johndo36,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

----

### 🔗 🐞 This issue is a Duplicate of #24448 

Which is on the same subject. 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Comment by nicholaszein** [comment]
Hi!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v4.2.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elemn.to/changelog)

Cheers 🥂 

----

If you think this is still an issue caused by Elementor after updating to the latest version, and can reproduce it consistently after following our [Contribution Guidelines](https://elemn.to/gh-contributing-bug-reports), feel free to open a new 🐞 [Bug Report](https://elemn.to/gh-new-bug-report), and we will be happy to review your case.
