### ISSUE TITLE
❌ 🛟 Support Request: Elementor is DEAD after upgrade to version 3.9

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#25004]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Elementor is DEAD after upgrade to version 3.9 IF PHP version is < 7.4.
Elementor disables itself AND website is broken.

### Steps to reproduce

1. Any Wordpress website with PHP version < 7.4
2. Upgrade Elementor to 3.9
3. BOOM - No Elementor:
3.1 Website is broken
3.2 You cannot downgrade Elementor version
See example for a warning when PHP version is NOT supported by a plugin
and thus the option for upgrade does not exist.

![EBUG](https://github.com/elementor/elementor/assets/765651/c6c15183-3a4f-4e7f-a5e4-f891bdf7e39c)

### Expected behavior

Elementor MUST check PHP version BEFORE upgrade and committing suiside (disable itself)
Elementor SHOULD NOT upgrade to 3.9 if PHP version < 7.4

![EBUG2](https://github.com/elementor/elementor/assets/765651/c56cd9a1-4374-4ef0-9a2b-540533425c08)
![EBUG3](https://github.com/elementor/elementor/assets/765651/2cc86ea3-3101-444c-a2dc-19cd88bcfe36)

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
No Elementor data to show since its dead!
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by m1ga** [comment]
* 3.19.0
* they've announced it in June 2023 https://developers.elementor.com/elementors-roadmap-to-upgrade-php-versions/
* you shouldn't run a webserver with that php version
* you are responsible for updates, don't set it to auto-update if you didn't test it before.

**Comment by Mulli** [comment]
@m1ga Please note that your comment while valid is irrelevant to the issue of a plugin "commiting suiside".
See example for expected behavior 
![EBUG2](https://github.com/elementor/elementor/assets/765651/0e11af06-21a6-46ad-9622-f12f15670f2c)

**Comment by m1ga** [comment]
The official 3.19.0 readme has that:
https://github.com/elementor/elementor/blob/3.19.0/readme.txt#L6

it shouldn't install on php < 7.4 as it is the minimum inside the readme file. Also: it would really help if you switch to english for the screenshots.

**Comment by Mulli** [comment]
@m1ga Please find the attached example for correct handling of unsupported PHP version 
![EBUG3](https://github.com/elementor/elementor/assets/765651/e60dbe23-ba54-4874-b846-cc17a61e8a37)

The correct **plugin behavior** is NOT to ALLOW upgrade to a non PHP supported version.
All readme files & zilion reasons why not use old PHP versions are valid - but irrelevant to the ill plugin behavior, as I see it.

**Comment by m1ga** [comment]
> All readme files & zilion reasons why not use old PHP versions are valid - but irrelevant to the ill plugin behavior, as I see it.

Please understand how "readme.txt" works. The notification you are seeing is triggered by WordPress by reading the readme.txt. The plugin you are showing has the same setting https://plugins.trac.wordpress.org/browser/groups/trunk/readme.txt

**Comment by Mulli** [comment]
@m1ga Please note that you are missing the main point: The correct plugin behavior is NOT to ALLOW upgrade to a non PHP supported version.

If you can justify this ill behavior, it will be helpful.
Thanks

**Comment by nicholaszein** [comment]
Hello @Mulli,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
Elementor (and WordPress) already have a mechanism in place when your PHP version is incompatible. It will not show up as an update in this case, and you won't be able to see it until you upgrade the PHP version to a compatible one. Moreover, there are warnings about the incompatibility that appear both in the Plugins list, and the Update page.

However, Elementor does not control the auto-update mechanism, and can't prevent you from installing the version manually, or through a website management system such as MainWP, WP Engine, ManageWP, and others, including server-side management.

If your plugin was updated using any of the methods above, Elementor will deactivate itself and warn you about the PHP incompatibility. So what you are reporting here is incorrect, and what @m1ga explaining is correct (thanks @m1ga 🙏).

**We DO NOT provide support for older versions of PHP anymore, and the behavior your experienced is the expected behavior.**

### ✅ What you can do to solve your issue:
Update your PHP version to at least 7.4 as pointed in the [Elementor Requirements](https://elementor.com/help/requirements/) page.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor after following the troubleshooting steps above, feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
