### ISSUE TITLE
⛔ Button stuck in hover state

### ISSUE THREAD

**Issue by yukaiin** [elementor/elementor#25107]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

There isn't much detail to be talked about. After clicking it just gets stuck in the hover state. Literally set up a new website with only Elementor + Hello Elementor Theme. Also all websites that use Elementor buttons have this bug. 

### Steps to reproduce

1. Create a button
2. set some kind of visible hover setting
3. publish website
4. middle-click button

### Expected behavior

Well... The button should go back to it's normal state

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.23
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: http://test.local
	Home URL: http://test.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.19.2
		Author: Elementor.com


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Global Style Guide: Active by default


== Log ==
	
PHP: showing 1 of 1PHP: 2024-02-12 13:24:19 [notice X 1][..\wp-content\plugins\elementor\core\experiments\manager.php::161] preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2024-02-12 13:24:35 [error X 1][../wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.19.2:2:2932] elementor_new_template_form_controls is not defined 



== Elementor - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by lensbreak** [comment]
I can confirm this happens to me too. A very minor detail and not impacting the UX. Still nice catch @yukaiin

PS: Middle-click button means to open the link in a new tab, for example by clicking the button with the mouse wheel or right click on it and open link in a new tab. after that if you unhover the button, the color doesn't go back to original state.

**Comment by yukaiin** [comment]
> I can confirm this happens to me too. A very minor detail and not impacting the UX. Still nice catch @yukaiin
> 
> PS: Middle-click button means to open the link in a new tab, for example by clicking the button with the mouse wheel or right click on it and open link in a new tab. after that if you unhover the button, the color doesn't go back to original state.

Yes i know what middle click does. It's the best way to demonstrate the issue since you stay in the same tab and immediately see the issue when moving the mouse

**Comment by nicholaszein** [comment]
Hello @yukaiin,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is the expected behavior due to how Elementor handles `:hover` and `:focus` states. The styles for the `:hover` state are also applied for the `:focus` state. By default, browsers will maintain any clicked element in `:focus` until you move the focus to something else in the page. When you use the middle-click, the browser opens a new tab, but retains the context of the existing tab, by keeping the `:focus` on the element you've clicked so you can know which element was clicked before you changed tabs.



### ✅ What you can do to solve your issue:
For now we do not have any plans to change this behavior due to backward compatibility. However, you can apply your own custom CSS to Elementor Buttons in the `:focus` state if you wish by using the following selector in your CSS declaration:

```css
.elementor-button:focus {

}
```

If you think Elementor should implement the option to style the `:focus` state of buttons individually, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users. 

### 👍 For now, that's all we can help with. 

Kind regards
