### ISSUE TITLE
❌ 🛟 Support Request: `.elementor-invisible` class is not removed when using animations.

### ISSUE THREAD

**Issue by vardumped** [elementor/elementor#25108]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The issue still occurs. When using Elementor to dynamically add CSS animation rules to elements, the animation does not work as expected. The goal is to fade in elements when they become visible in the viewport, but the animation does not trigger upon visibility change.

I wrote this temporary solution in JavaScript. It checks if the element is at least 50% in the viewport and then removes the elementor-invisible class. The element is displayed, it's only set up to work with the fadeIn animation.

```
// Function to check if an element is in the viewport
function isInViewport(element) {
  var rect = element.getBoundingClientRect();
  var windowHeight = window.innerHeight || document.documentElement.clientHeight;

  // Check if at least 50% of the element is visible
  return (
    rect.top <= windowHeight * 0.50 &&
    rect.bottom >= 0 &&
    rect.left >= 0 &&
    rect.right <= (window.innerWidth || document.documentElement.clientWidth)
  );
}

// Function to toggle visibility class based on viewport
function toggleVisibility() {
  var elements = document.querySelectorAll('.elementor-invisible');
  elements.forEach(function (el) {
    if (isInViewport(el)) {
      if (el.classList.contains('elementor-invisible')) {
        el.classList.remove('elementor-invisible');
        el.classList.add('animate'); // Add CSS class for animation

        // Dynamically add CSS animation rules
        var style = document.createElement('style');
        style.textContent = `
          @keyframes fadeIn {
            from {
              opacity: 0;
            }
            to {
              opacity: 1;
            }
          }
          .animate {
            animation: fadeIn 0.5s ease;
          }
        `;
        document.head.appendChild(style);
      }
    }
  });
}


// Add event listener to scroll event
window.addEventListener('scroll', toggleVisibility);

// Initial check when page loads
toggleVisibility();
```

### Steps to reproduce

1. Create an animation for an element / widget using the Elementor preview editor.
2. Save and preview your changes, then view it in the frontend (not the Elementor preview)
3. The elementor-invisible class is applied on the Elementor element and not removed when in viewport.

### Expected behavior

1. Show animation when in viewport.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [x] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Elementor: v3.19.2
Elementor Pro: 3.19.2
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @vardumped ,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
You seem to be having a conflict with cache, a script or 3rd-party addon. We just tested and the class is removed correctly when an animated element entered the viewport.

### ✅ What you can do to solve your issue:
- Check your cache settings, especially those related to JS optimization.
- Make sure you are not running conflicting scripts, plugins, or themes.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor after following the troubleshooting steps above, feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

----

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Kind regards
