### ISSUE TITLE
❌ Legacy Accordion widget throws warning about the <a> tag as descendant of a role=button in the w3 validator

### ISSUE THREAD

**Issue by Konstantin-77** [elementor/elementor#25207]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Checking for https://validator.w3.org/ / the accordion contains the error “The element a must not appear as a descendant of an element with the attribute role=button“. 20 points in the accordion – 20 mistakes. How can I fix it?

### Steps to reproduce

The page I need help with: https://cpspec.ru/courses/inzhener-tehnolog-po-proizvodstvu-izdelij-mikrojelektroniki/

### Expected behavior

No validation errors when checking ACCORDION

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
WordPress 6.4.3
Server 	Apache/2.4.55 (Unix)
Elementor - 3.17.3
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @Konstantin-77,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is a false positive and has no negative effect on any functionality, performance, or SEO scores. You can ignore it safely. This widget uses `<a>` tags to trigger the toggle of each accordion, and due to backward compatibility we have no plans to change this behavior.

### ✅ What you can do to solve your issue:
If you want a semantically correct accordion, please enable the **`Nested Elements`** feature in your WordPress **`Dashboard`** > **`Elementor`** > **`Settings`** > **`Features`** page, and use the new (nested) **Accordion** widget. This widget won't trigger any warnings from the W3 validator.

### 👍 For now, that's all we can help with. 

Note that we saw that you didn't submit the whole **Elementor System Info** as required in the Bug Report form. This information is not optional, and going forward we won't accept bug reports without it. Please, next time make sure you share the required information.

Kind regards
