### ISSUE TITLE
❌ 📚 Add filters and hooks to the Hints API

### ISSUE THREAD

**Issue by mbaierl** [elementor/elementor#25739]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The Hints:: API (elementor/core/utils/hints.php) does not contain any filter or hook , which would allow to supress the displaying of the (useless) Image Optimization Plugin. 

Please add filters and hooks that allow the removal of those ads inside Elementor.

My clients have another image optimization plugin installed, activated and running, but still keep installing the Plugin.

Education does not help. 

Removing the ads will.

### Steps to reproduce

Open elementor/core/utils/hints.php and add filters (add_filter) and hooks (add_action).

### Expected behavior

Having a filter or hook which allows to disable the nag screens one by one or all of the at once.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
not needed.
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi, @mbaierl,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

This is more of a feature request, not a bug. Please only use GitHub issues to report bugs. If you want a feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and required</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. It's not optional.

### ⚠️ As a gentle reminder, issues that do not follow our [Contribution Guidelines](https://elemn.to/gh-contributing) may need to be closed without troubleshooting. 

Thank you for understanding! 🙏

Kind regards
