### ISSUE TITLE
❌ 📚 Text Control Value Not Updating in custom widget

### ISSUE THREAD

**Issue by FarjadAkbar** [elementor/elementor#25768]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I am encountering an issue where the value of the Text control in my custom Elementor widget is not updating properly. Despite modifying the default value of the Text control within the widget's settings, the updated value does not appear on the frontend when I view the widget. This issue only occurs with Text and Textarea controls; other controls are functioning as expected.

### Steps to reproduce

1. Added a custom widget on the page with default settings (Text control = "Testing Heading") and previewed it. In the preview, it showed "Testing Heading". 
```php
$this->add_control(
    'header_heading_ahi',
    [
        'label' => esc_html__( 'Heading', 'annuities' ),
        'type' => Controls_Manager::TEXT,
        'default' => esc_html__('Testing Heading', 'annuities' ),
    ]
);
```
2. Changed the default value (Text control = "Heading Test") from the widget's code.   
```php
$this->add_control(
    'header_heading_ahi',
    [
        'label' => esc_html__( 'Heading', 'annuities' ),
        'type' => Controls_Manager::TEXT,
        'default' => esc_html__('Heading Test', 'annuities' ),
    ]
);
```
5. Previewed it again, but it still showed "Testing Heading" instead of displaying "Heading Test".

### Expected behavior

If no changes are made to the control, it should always display the default value. If the default value is changed via code, it should update accordingly. This issue specifically affects Controls_Manager::TEXT and Controls_Manager::TEXTAREA. I have tested other controls (Number, Code, WYSIWYG), and they are functioning as expected.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Elementor Version: 3.21.0
Elementor Pro Version: 3.21.0
WordPress Version: 6.5.2
Theme: Essentials theme
Active Plugins: (Animated Typed JS Shortcode, Contact Form 7, Elementor, Elementor Pro, Envato Market, Graphina - Elementor Charts and Graphs, pixfort Core, PixFort Likes, Custom Wigdet, Safe SVG, Two Factor Authentication)
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @FarjadAkbar,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
You need to regenerate CSS & Data, and clean your site's transients if you want to see changes you make to your widgets.

We do not provide support for custom code or 3rd-party add-ons. Make sure you are correctly following all the instructions in the [Developers Documentation](https://developers.elementor.com/docs) for creating custom widgets.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
