### ISSUE TITLE
❌ 🧩 🛟 3rd-party Support Request: Home Pages, Editing and Display

### ISSUE THREAD

**Issue by estlacksensory** [elementor/elementor#27676]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

WordPress version 6.5.4 just released and upgraded to this version on WPEngine. Site is on a multisite network. Many homepages use Elementor for layout. Internal pages (non-homepage or Front pages) seem fine. Home pages are not displaying elementor layouts and are reverting to a cached version of a "Genesis" layout. This seems like a new issue. Not sure if anyone is running into this.

### Steps to reproduce

1. use wp 6.5.3 (on nginx) - not sure if this is specific to WPEngine
2. create elementor layouts
3. use elementor on wpmudev, multisite
4. create elementor layouts for internal pages and homepages on each microsite of network
5. verify that elementor layouts are working
6. upgrade to wp 6.5.4
7. test if homepages break in new version

### Expected behavior

1. on upgrade to 6.5.4 elementor layouts completely break on front pages, home pages and are uneditable

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

**[Moderation edit: The contributor did not provide the full and required Elementor System Info.]**

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by estlacksensory** [comment]
Correction - I think the issue is with the pages in the primary microsite on the network. Might not exist on home pages on each microsite. Sorry for any confusion.

**Comment by nicholaszein** [comment]
Hello @estlacksensory,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

Moreover you seem to be using a 3rd-party theme (Genesis) that might be conflicting with your site or server cache.

Since you have not provided the required Elementor System Info, we are unable to validate your issue. While testing Elementor on a Multisite installation everything worked as expected.

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for 3rd-party or personal support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
