### ISSUE TITLE
[Feature Request] Hotspot image with tooltips widget

### ISSUE THREAD

**Issue by parfilov** [elementor/elementor#2768]
Hi! Instead of 1000 words see an [example](http://nativewptheme.net/twenty_second/) scroll down to the silver car. And here is effect adding tutorial from theme's author https://www.youtube.com/watch?v=5IWEH1tuS6Q

I want it in Elementor Pro!

**Comment by avermat** [comment]
In case you are unaware, this features is currently available with Elementor Extras: https://shop.namogo.com/elementor-extras/widgets/hotspots/

**Comment by themedleb** [comment]
+1

**Comment by Basilakis** [comment]
Great to leave some things for the developers and the extra addons. That keeps the community running, promote Elementor and let people earn some bucks to keep doing what they are doing good!

**Comment by parfilov** [comment]
@Basilakis I don't want to use theirs bug widgets. Let they do their work better the first, then let's talk about it.

**Comment by Giffordcl** [comment]
I agree with it being a pro feature as well, kind of like an image map, been looking, and I don't mind supporting developers for the addons but most of the packages have things I've already  received in pro so why am I paying for one widget I can use out of 20 when it can easily be integrated, plus we haven't seen many additional widgets as of late. 5 developes releasing the same widget in their packages - confusing. I left one company because of too many plugin requirements, tutorials needed and hand holding, too many templates, codes, and tweaks when it should just be native. In addition developer told me I needed widget to add ability to embed pinterest board on my website, guess what didn't listen, researched did it myself, saved 20 bucks. ?

**Comment by adi0071** [comment]
I would like to see this feature added as it would be great enhncement for anyone building woocommerce websites

**Comment by shimsim** [comment]
+1

**Comment by mauriziogalli** [comment]
Image Hotspots: I would like this feature added, to explain some useful detail on an image

**Comment by shilo-ey** [comment]
Hey all,

This feature has been added to Elemetnor Pro v3.3.0

Feel free to update

Cheers!
