### ISSUE TITLE
❌ Display Conditions not working using URL and query strings

### ISSUE THREAD

**Issue by creative-andrew** [elementor/elementor#27815]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Display Conditions not working using URL and query strings

### Steps to reproduce

(1) Add a display condition to an element

![image](https://github.com/elementor/elementor/assets/18492002/1960c63f-a64e-4d82-b4b9-5a2b8c210e3b)

(2) Visit the URL including the query arg: example.com/yourpage/?login=failed

Notice that it won't appear.

### Expected behavior

It should show or hide the element

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by Daveden2** [comment]
The display condition reads "From URL", not the current URL. It is checking for the referral URL that the user visited from, not the current URL.

**Comment by creative-andrew** [comment]
Gotcha. If that is the case, it is not as useful as knowing the current URL.

**Comment by nicholaszein** [comment]
You can use it to show elements for people coming from social media, or another website... 

Please, before submitting you issue use the help center to troubleshoot it. A simple search would hare returned the information about display conditions. Since you are a Pro user, you could have reached out to Elementor Support too. 

Only use GitHub if you are certain that you have troubleshooter your issues. This is not a place for personal support.

**Comment by nicholaszein** [comment]
Hi, @creative-andrew,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

We have plans to add more functionality for the Element Display Conditions, but currently it doesn't support a condition for the Current URL.

Thank you for showing interest though!

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
