### ISSUE TITLE
Fade In Up animation is doubling or even tripling when combined with video background

### ISSUE THREAD

**Issue by godlesowned** [elementor/elementor#27851]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

As I combined Fade in animation with video background it's almost tripeling and definitely doubling. Here is proof:
Only Elementor

https://github.com/elementor/elementor/assets/12765198/3953d681-03c4-45d2-847f-22437517d480

### Steps to reproduce

1. Create Flexbox with video background
2. Add Headlines and add Fade In Up
3. Effect.

### Expected behavior

1. Doubling animation

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Not needed
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @godlesowned!

Thank you for submitting your issue, and apologies for the delay in answering you! 🙏 

Unfortunately, we were not able to reproduce your issue, and since you did not share the required Elementor System Info, and there is little to no information to understand your problem, we cannot continue evaluating your issue.

You can see an example of the effect working as expected in the video below:

https://github.com/user-attachments/assets/8df7f67e-f6e2-4e18-bafa-5c7d66a4d423



If you think you're still experiencing your issue, after troubleshooting it and isolating the problem, please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Keep in mind, we will not accept issues without the required information.

Thank you for understanding.

Kind regards
