### ISSUE TITLE
❌ 🔗 Carousel component with offset on 1 slide does not work without zoom (Duplicate of #23062)

### ISSUE THREAD

**Issue by rwkyyy** [elementor/elementor#28028]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

This was already mentioned in #23062 and closed, but I have ended up here with the same issue, no matter what setup I use it will not show any other slides in offset, except when using zoom (css).

### Steps to reproduce

as mentioned in initial ticket, just zoom in/out from your browser.

### Expected behavior

expecting offset to work with 1 slide per view.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
same as ticket 23062
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @rwkyyy.

While we appreciate your contribution, we cannot troubleshoot and validate issues that do not include the required information as stated in the Bug Report form. Moreover, as explained in #23062, we cannot reproduce the issue on our end.

It's important to note that if you have only one slide in your carousel, regardless if you set it to infinite loop or not, you won't see the slide offset because there is only one slide. You need to have at least two different slides in your carousel, even if you still select to show only one per view.

It's unclear weather you've troubleshooted your issue, you have the latest version of Elementor and Elementor Pro installed, and all the other requirements defined in the Bug Report form. For this reason we cannot properly evaluate and validate your issue.

Required fields are not optional.

Regards
