### ISSUE TITLE
❌ Active Page highlight not working in the (mega) Menu widget

### ISSUE THREAD

**Issue by Jonathlee** [elementor/elementor#28022]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

![image](https://github.com/elementor/elementor/assets/696956/2394d0a5-aa45-4895-9c74-baa20a7d431e)

My Elementor version :  3.22.3 and Elementor Pro version :  3.22.1
Elementor Pro > Menu

### Steps to reproduce

1. Added menu and configured each page
2. When visiting the actual page
3. Clicking on each of the link in the menu DID NOT highlight the current active page

### Expected behavior

1. Added menu and configured each page
2. When visiting each of the respective page
3. The menu will highlight the current page with the menu's "Active" color 

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt
== Active Plugins ==
	Bookme
		Version: 4.8
		Author: Bylancer

	Duplicate PP
		Version: 3.5.1
		Author: Zakaria Binsaifullah

	Elementor
		Version: 3.22.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.22.1
		Author: Elementor.com

	Flying Pages
		Version: 2.4.6
		Author: WP Speed Matters

	Independent Analytics
		Version: 2.6.3
		Author: Independent Analytics

	Post Types Order
		Version: 2.2.3
		Author: Nsp Code

	Rank Math SEO
		Version: 1.0.223
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.66
		Author: Rank Math

	Spectra
		Version: 2.14.0
		Author: Brainstorm Force

	UpdraftPlus - Backup/Restore
		Version: 1.24.4
		Author: UpdraftPlus.Com, DavidAnderson

	Web Stories
		Version: 1.37.0
		Author: Google

	WP Crontrol
		Version: 1.16.3
		Author: John Blackbourn

	WP Revisions Control
		Version: 1.4.3
		Author: Erick Hitter

	WPS Hide Login
		Version: 1.9.16.7
		Author: WPServeur, NicolasKulka, wpformation


== Elements Usage ==
	
	archive : 1
		archive-posts : 2
		container : 1
		text-editor : 1
		theme-archive-title : 2
	footer : 1
		container : 7
		heading : 4
		icon-list : 3
		social-icons : 1
	header : 1
		button : 4
		container : 11
		mega-menu : 1
		nav-menu : 1
		off-canvas : 1
		theme-site-logo : 1
	section : 1
		button : 1
		form : 2
		heading : 2
		nav-menu : 1
		theme-archive-title : 1
		theme-post-featured-image : 1
		wc-archive-products : 1
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-price : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
	single : 1
		button : 1
		container : 11
		heading : 3
		post-info : 3
		post-navigation : 1
		posts : 1
		share-buttons : 1
		table-of-contents : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	wp-post : 12
		blockquote : 1
		breadcrumbs : 4
		button : 29
		call-to-action : 7
		divider : 26
		facebook-comments : 1
		form : 4
		heading : 239
		icon-list : 50
		image : 179
		image-box : 6
		image-carousel : 1
		image-gallery : 12
		posts : 2
		shortcode : 1
		spacer : 78
		table-of-contents : 12
		text-editor : 81
		theme-page-title : 5
		video : 8
	wp-page : 26
		blockquote : 2
		breadcrumbs : 4
		button : 30
		call-to-action : 5
		container : 9
		divider : 2
		facebook-embed : 1
		form : 6
		heading : 173
		html : 3
		icon : 4
		icon-box : 10
		icon-list : 15
		image : 34
		image-box : 4
		posts : 4
		price-table : 6
		shortcode : 2
		spacer : 19
		text-editor : 90
		toggle : 2
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
	single-post : 1
		container : 3
		post-info : 2
		posts : 1
		search-form : 1
		theme-post-content : 1
		theme-post-title : 1


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	facebook_sdk: Active


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Active
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Header &amp; Footer: Inactive by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Element Caching: Active
	Conversion Center: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Active
	Taxonomy Filter: Active by default


== Log ==
	
Log: showing 20 of 302023-06-12 10:55:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.13.2',
)]
2023-06-12 10:55:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.13.2',
)]
2024-05-25 21:32:45 [info] elementor::elementor_updater Started 
2024-05-25 21:32:45 [info] Elementor/Upgrades - _on_each_version Start  
2024-05-25 21:32:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.21.7',
)]
2024-05-25 21:32:48 [info] Elementor/Upgrades - _on_each_version Finished 
2024-05-25 21:32:48 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2024-05-25 21:32:48 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2024-05-25 21:32:48 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2024-05-25 21:32:48 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2024-05-25 21:32:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.21.7',
)]
2024-07-10 18:36:20 [info] elementor::elementor_updater Started 
2024-07-10 18:36:20 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-10 18:36:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.7',
  'to' => '3.22.3',
)]
2024-07-10 18:36:22 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-10 18:36:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.7',
  'to' => '3.22.3',
)]
2024-07-10 20:30:59 [info] elementor-pro::elementor_pro_updater Started 
2024-07-10 20:30:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-10 20:30:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-10 20:30:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.22.1',
)]


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @Jonathlee,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
You seem to have the **Element Caching** experimental feature enabled while leaving it **`Active`** for your Mega Menu. In this case, **since the current page indicator is dynamic**, and applied on a per-page basis, you need to ensure this option is set to **`Inactive`** in the Menu Settings **`Advanced`** tab > **`Layout`** section.

![image](https://github.com/user-attachments/assets/d47e65d5-7a2e-471f-b475-4bb759e12af4)


Please watch the video to see it in action:


https://github.com/user-attachments/assets/1aa1a069-cba2-48f7-b070-53939a4c025f



### ✅ What you can do to solve your issue:
Unfortunately, your report is missing key and required information (the Full System Info) that would allow us to pinpoint your issue, not to mention you are running several 3rd-party plugins that could affect your results. Moreover, you didn't mention how you setup your Menu Items Active states so we can understand what is the actual problem, nor did you provide a link to a website that we can see the issue in action. Therefore we conclude this is an issue specific to your site, caused by either a conflict, or incorrect Style settings.

When using the Element Caching experimental feature, make sure you set it to inactive on dynamic elements to avoid rendering issues.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
