### ISSUE TITLE
⛔ 🛟 Support Request: Icon List icons are not rendered correctly in the Footer

### ISSUE THREAD

**Issue by JonJHale** [elementor/elementor#28131]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Within an elementor template, we created a footer. Within the footer we added the element list for sitemap and contact links. We attached icons from your normal library (phone / mail) and they were added fine, along with the tel: mailto: links. They also appear within the elementor edit screen. Then on a save / refresh, they vanish from the actual footer, although they are still attached within the element list. Artbees support (themeforest) have looked at it and reported it to us as a bug within elementor itself. NB: Artbees support have written some custom code to allow the icons to show. The hide my site PW if you need is: somersetconsult2024!

### Steps to reproduce

1. create a footer elementor template
2. create 4 columns
3. in one add a heading, then an element list
4. add an icon and text, and link to either phone tel: or mailto:  / refresh

### Expected behavior

You should see the icons appearing. And then when saved, and a refresh they disappear from the portal view. When you open up the element list, the icons are still uploaded. 

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.38
	PHP Version: 8.1.29
	PHP Memory Limit: 768M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6
	Site URL: https://training.figadigital.com/somersetconsulttwo
	Home URL: https://training.figadigital.com/somersetconsulttwo
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: JupiterX
	Version: 4.4.0
	Author: Artbees
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	301 Redirects
		Version: 2.76
		Author: WebFactory Ltd

	Advanced Custom Fields
		Version: 6.3.3
		Author: WP Engine

	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Elementor
		Version: 3.22.3
		Author: Elementor.com

	GDPR Cookie Compliance
		Version: 4.15.2
		Author: Moove Agency

	JetElements For Elementor
		Version: 2.6.17.1
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.2.2
		Author: Crocoblock

	Jupiter X Core
		Version: 4.4.0
		Author: Artbees

	Wordfence Security
		Version: 7.11.6
		Author: Wordfence

	WP Fastest Cache
		Version: 1.2.8
		Author: Emre Vona

	WPS Limit Login
		Version: 1.5.9.1
		Author: WPServeur, NicolasKulka, wpformation

	Yoast SEO
		Version: 23.0
		Author: Team Yoast


== Elementor Experiments ==
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active by default
	Grid Container: Active
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Inactive by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Active
	Build with AI: Active by default
	Landing pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active by default
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Conversion Center: Inactive by default


== Log ==
	
PHP: showing 1 of 1PHP: 2024-06-01 14:16:00 [error X 1][../wp-content/plugins/elementor/includes/base/widget-base.php::198] Allowed memory size of 100663296 bytes exhausted (tried to allocate 81920 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2024-07-11 12:35:59 [error X 50][../wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2024-07-14 12:45:08 [error X 1][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.22.3:3:16087] Cannot read properties of undefined (reading &#039;global&#039;) 
JS: 2024-07-15 20:52:17 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:825128] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 

Log: showing 5 of 52024-07-12 23:41:59 [info] elementor::elementor_updater Started 
2024-07-12 23:41:59 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-12 23:41:59 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-12 23:41:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.8',
  'to' => '3.22.3',
)]
2024-07-12 23:41:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.8',
  'to' => '3.22.3',
)]



== Elementor - Compatibility Tag ==
	
	JetElements For Elementor: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @JonJHale,

Thanks for contacting us! 🙏 

### 🛟 This is more of a personal support question, not really something we can help with here. 

We followed your steps to reproduce, and tested on different site, however we haven't been able to reproduce your issue. On all attempts, the icons were rendered correctly. Here's an example:
![image](https://github.com/user-attachments/assets/51893daa-c774-4c9b-8e80-bcd3809794fe)

From your System Info I can see you make use of multiple Elementor Addons, a theme that claims integration with Elementor, and also a plugin for cache. All of these can directly interfere on how Elementor works. It's likely your issue is caused by one of them.

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
