### ISSUE TITLE
⛔ Imported demo image link showing from another server

### ISSUE THREAD

**Issue by raziul6** [elementor/elementor#28222]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When I import demo data using XML all media files are being loaded from the theme’s original server, where the XML file was exported, rather than from my own server where I imported the demo data. How can I resolve this issue? this issue only made custom widgets or use elementor default image widget both are facing this issue

### Steps to reproduce

No

### Expected behavior

No

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.23
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: http://localhost:10129
	Home URL: http://localhost:10129
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Fladient
	Version: 1.0.1
	Author: themexriver
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	AI Engine
		Version: 2.4.7
		Author: Jordy Meow

	Contact Form 7
		Version: 5.9.8
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.23.3
		Author: Elementor.com

	Fladient Plugin
		Version: 1.0.1
		Author: Raziul Islam

	MC4WP: Mailchimp for WordPress
		Version: 4.9.14
		Author: ibericode

	WooCommerce
		Version: 9.0.2
		Author: Automattic


== Elementor Experiments ==
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Inactive
	Grid Container: Inactive
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Inactive
	Landing Pages: Inactive by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active by default
	Element Caching: Inactive by default
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default


== Log ==
	
JS: showing 7 of 7JS: 2024-07-01 06:24:13 [error X 24]../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.22.3:3:14246] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `link` value. Expected array or object.',
)]
JS: 2024-07-02 05:32:01 [error X 4]../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:322949] Cannot read properties of undefined (reading &#039;children&#039;) 
JS: 2024-07-02 12:28:23 [error X 7]../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:825128] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2024-07-06 11:16:23 [error X 8]../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:1176313] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 
JS: 2024-07-08 09:51:37 [error X 28]../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:825635] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2024-07-14 05:49:11 [error X 11]../wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.22.3:2:2932] elementor_new_template_form_controls is not defined 
JS: 2024-07-14 05:49:21 [error X 25]../wp-admin/load-scripts.php?c=0&amp;loadchunk_0=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&amp;ver=6.5.5:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 

Log: showing 10 of 102024-07-16 05:45:32 [info] elementor::elementor_updater Started 
2024-07-16 05:45:32 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-16 05:45:32 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-16 05:45:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]
2024-07-16 05:45:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]
2024-07-27 04:18:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.3',
)]
2024-07-27 04:18:21 [info] elementor::elementor_updater Started 
2024-07-27 04:18:21 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-27 04:18:21 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-27 04:18:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.3',
)]

PHP: showing 2 of 2PHP: 2024-07-27 04:18:21 [warning X 1][../wp-content/plugins/elementor/core/files/manager.php::112] unlink(../wp-content/uploads/elementor/css/post-947.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-27 04:18:22 [warning X 1][../wp-content/plugins/elementor/core/files/manager.php::112] unlink(../wp-content/uploads/elementor/css/post-1713.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==

````

</details>

### Agreement

- [ ] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @raziul6!

Thank you for reaching out! 🙏 

Unfortunately, this is not an Elementor issue. This is how WordPress always worked when importing XML data. Let me explain:

XML Files are not like ZIP files that would include a copy of all the file attachments in your documents. XML is essentially a text file with a set of instructions that WordPress can read and recreate your imported data. Links to any media files or other documents in your site are maintained as they where when they were exported. So they will point to media files from the original source. In this case you would need to download all the media files, and replace the existing references by uploading them again to your library.

However, if you use Elementor's [Export and Import Kit](https://elementor.com/help/what-is-import-export/) functionality, you might have more success. This built-in feature allows you to export almost your entire website as Elementor templates in JSON format. These are also essentially text files with a set of instructions that will continue to link to your original website (they also don't include the media files), however, differently from the WordPress method, Elementor will attempt to download all the media files, upload to your library, and replace their references in your documents. This is the official Elementor method of Exporting/Importing Elementor-built documents, and the only one we give support.

Keep in mind that not all media flies can be migrated, some like SVG images may require you to replace manually due to the security concerns around these files. Menu items created in the WordPress Menu may also require rebuilding.

If you need to migrate a website using any of the methods above also make sure the existing site is accessible, otherwise you won't be able to import the media library items.

Finally, if you intention is to migrate an entire website, you should consider using an appropriate solution, such as backup and migration plugins (All-In-One WordPress Migration, WP Vivid Backups, Updraft Plus, and others), or use a service like Migrate Guru. Migrating websites using the built-in WordPress Export/Import Tools is not recommended.

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal support or assistance. Neither for issues with 3rd-party software such as the WordPress Tools mentioned here.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
