### ISSUE TITLE
Angular 17 TypeError : e.animate is not a function

### ISSUE THREAD

**Issue by naveeth06** [elementor/elementor#28346]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

 e.animate is not a function
    at xc._triggerWebAnimation (/node_modules/@angular/animations/fesm2022/browser.mjs:4027:20)
    at xc._buildPlayer (/node_modules/@angular/animations/fesm2022/browser.mjs:3999:27)
    at xc.init (/node_modules/@angular/animations/fesm2022/browser.mjs:3991:10)  
    at player (/node_modules/@angular/animations/fesm2022/animations.mjs:1354:43)
    at Array.forEach (<anonymous>)
    at Bs.init (/node_modules/@angular/animations/fesm2022/animations.mjs:1354:18)
    at Bs.play (/node_modules/@angular/animations/fesm2022/animations.mjs:1377:12)
    at Gs.play (/node_modules/@angular/animations/fesm2022/browser.mjs:3610:34)  
    at player (/node_modules/@angular/animations/fesm2022/browser.mjs:3415:14)   
    at Array.forEach (<anonymous>)

Node.js v18.16.0

`import { Component, ElementRef, ViewChild } from '@angular/core';
import { CarouselModule, OwlOptions } from 'ngx-owl-carousel-o';
import { AnalyticsService } from '../../../analyticsService.service';
import { CommonModule } from '@angular/common';
import { dataModule } from '../../../assets/data';
import { BrowserAnimationsModule, NoopAnimationsModule } from '@angular/platform-browser/animations';
@Component({
  selector: 'app-project',
  standalone: true,
  imports: [CommonModule,CarouselModule, BrowserAnimationsModule],
  templateUrl: './project.component.html',
  styleUrls: ['./project.component.scss']
})
export class ProjectComponent {
  customOptions: OwlOptions = {
    loop: true,
    mouseDrag: true,
    touchDrag: true,
    pullDrag: false,
    navSpeed: 700,
    items: 1,
    autoplay: true,
    autoplayTimeout:3000
  };
    @ViewChild('imgContainer') imgContainer: ElementRef | any;

data = dataModule
slide: string = '';
  constructor(
    public analyticsService: AnalyticsService
  ) { }

debug(){

  this.imgContainer.nativeElement.scroll({
    top: this.imgContainer.nativeElement.scrollHeight,
    left: 0,
    behavior: 'smooth',    
  });
}

}
`
this is my ts file

this is the versions
    "@angular/animations": "^17.3.0",
    "@angular/common": "^17.3.11",
    "@angular/compiler": "^17.3.0",
    "@angular/core": "^17.3.11",

### Steps to reproduce

1. import BrowserAnimationModule

after that no error is shown in the termonial but once it gets compiled im getting the above type error in the terminal

### Expected behavior

1. the type error gets displayed and  nothing is shown in the screen .

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
"ngx-owl-carousel-o": "^17.0.0",
"@angular/animations": "^17.3.0",
"@angular/common": "^17.3.11",
"@angular/compiler": "^17.3.0",
"@angular/core": "^17.3.11",
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @naveeth06, 

Thank you for submitting your report! 🙏 

Unfortunately, we were unable to validate your issue because it was missing crucial information. You are required to share your Elementor System Info, describe your issue with detail, and provide steps to reproduce. Moreover, we do not provide for 3rd-party code, or guidance on how to develop for our plugins. For that use the [Developer Center](https://elemn.to/dev-center).

If you think you found a bug in the code, and cand reproduce it consistently, lease follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better. Make sure to provide enough information so we can properly validate your issue. We may close your issue again if you don't follow these guidelines.

Best regards
