### ISSUE TITLE
⛔ 🛟 Support Request: BUG TEXT EDITOR

### ISSUE THREAD

**Issue by alisssrossi** [elementor/elementor#28356]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Unable to change font size of text editors through "Typography"

![image](https://github.com/user-attachments/assets/0971e6fa-b88c-46c2-a78a-4676e3acf5e8)

### Steps to reproduce

[Bug text editor2.zip](https://github.com/user-attachments/files/16579885/Bug.text.editor2.zip)
1. Insert text editor from widget
2. Click "Style"
3. Click "Typography"
4. Choose family (works)
5. Choose size (doesn't work)

### Expected behavior

I expect that by changing the number of "Size" or dragging the cursor, the font size will change

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 25, Revision 9468fd1d v8.0.33-25
	PHP Version: 8.0.30.2
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.5
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_GB
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Go
	Version: 1.8.11
	Author: GoDaddy
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-GB

== Active Plugins ==
	CoBlocks
		Version: 3.1.13
		Author: GoDaddy

	Elementor
		Version: 3.23.4
		Author: Elementor.com

	ElementsKit Lite
		Version: 3.2.3
		Author: Wpmet

	Envato Elements
		Version: 2.0.14
		Author: Envato

	Template Kit Import
		Version: 1.0.16
		Author: Envato

	Yoast SEO
		Version: 23.2
		Author: Team Yoast


== Must-Use Plugins ==
	Object Cache Pro (MU)
		Version: 1.21.2
		Author: Rhubarb Group

	System Plugin
		Version: 4.134.1
		Author: 


== Elements Usage ==
	
	wp-page : 7
		container : 1
		ekit-nav-menu : 1
		elementskit-heading : 1
		heading : 1
		icon-list : 1
		image : 2


== Settings ==
	
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	font_display: swap


== Elementor Experiments ==
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active by default
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Active by default
	Build with AI: Active by default
	Landing pages: Inactive by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active by default
	Pages Panel: Inactive by default
	Element Caching: Active by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default


== Log ==
	
JS: showing 4 of 4JS: 2024-08-09 12:40:40 [error X 1] Cannot read properties of undefined (reading 'val') 
JS: 2024-08-09 13:41:00 [error X 2] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2024-08-10 07:25:57 [error X 1]Cannot read properties of undefined (reading 'isDesignable') 
JS: 2024-08-10 07:26:30 [error X 2] Cannot read properties of undefined (reading 'value') 



== Elementor - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @alisssrossi,

Thanks for contacting us! 🙏 

### 🛟 This is more of a support question, not really something we can help with here. 

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue.

Your issue was most likely caused by pasting styled text. You can avoid this by holding the **`SHIFT`** key when pasting text inside the Text Editor.


### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

Thank you for understanding! 🙏 

Kind regards
