### ISSUE TITLE
📚 Need a filter hook to turn Off element cache on certain post types/pages

### ISSUE THREAD

**Issue by xlplugins** [elementor/elementor#28372]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

We are the developers of funnelKit & we provide deep compatibility with elementor with our addons since couple of years. 
In past few days we are getting a lot of complaints about users are seeing cached order no. emails and usernames. 

After troubleshooting we found out that they new beta feature Element Caching
 was turned on on their site. As soon as we turned off it worked fine. 

 We are looking for a fitlter hook that will disable caching for specific post types so that we could add our post types in the filter and get rid of this issue for our upsell and thankyou pages (that conatins dynamic content). 

 The best place for the filter to be here https://imgur.com/TwjmaAR
~/plugins/elementor/core/base/document.php:1801 under  \Elementor\Core\Base\Document::print_elements

### Steps to reproduce

1. install elementor v3.23.0 or above
2. Enable beta feature "Element Caching"

### Expected behavior

After leaving a filter hook, developers will be able to exclude their pages. 

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.18.0
	MySQL version: (Ubuntu) v8.0.39
	PHP Version: 8.0.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: No
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: http://localamrt2.com
	Home URL: http://localamrt2.com
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /archives/%post_id%
	Language: en_US
	Timezone: Asia/Kolkata
	Debug Mode: Active

== Theme ==
	Name: Bricks
	Version: 1.9.8
	Author: Bricks
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.6.5.1
		Author: Code Snippets Pro

	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0-dev2
		Author: Elementor.com

	FunnelKit Funnel Builder
		Version: 3.4.7
		Author: FunnelKit

	FunnelKit Funnel Builder Pro
		Version: 3.4.5
		Author: FunnelKit

	FunnelKit One Click Upsells
		Version: 3.11.2
		Author: Funnelkit

	JSM Show Post Metadata
		Version: 4.3.0
		Author: JS Morisset

	JSM Show User Metadata
		Version: 4.3.0
		Author: JS Morisset

	Stripe Payment Gateway for WooCommerce
		Version: 1.8.8.beta1
		Author: FunnelKit

	User Switching
		Version: 1.8.0
		Author: John Blackbourn

	WooCommerce
		Version: 9.1.4
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 8.6.1
		Author: WooCommerce

	WooFunnels Debug Log Viewer
		Version: 1.0.0
		Author: WooFunnels

	Woo Subscriptions
		Version: 5.9.0
		Author: WooCommerce

	WordPress Beta Tester
		Version: 3.5.6
		Author: WordPress Upgrade/Install Team


== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 

	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash


== Elements Usage ==
	
	header : 2
		image : 4
		nav-menu : 4
	page : 8
		button : 5
		heading : 73
		icon : 5
		icon-list : 4
		image : 19
		spacer : 21
		star-rating : 3
		text-editor : 1
		video : 1
	wp-post : 5
		button : 50
		container : 1
		divider : 93
		heading : 1432
		icon : 46
		icon-box : 48
		icon-list : 231
		image : 473
		image-box : 12
		image-gallery : 27
		progress : 11
		shortcode : 1
		social-icons : 1
		spacer : 85
		star-rating : 114
		testimonial : 4
		text-editor : 331
		toggle : 2
		video : 21
		wfacp_form : 1
		wfocu-accept-offer-button : 61
		wfocu-offer-price : 22
		wfocu-offer-product-title : 20
		wfocu-offer-reject-button : 1
		wfocu-offer-reject-link : 58
		wfocu-product-images : 22
		wfocu-qty-selector : 43
		wfocu-short-description : 16
		wfocu-variation-selector : 49
	wp-page : 15
		container : 5
		form : 1
		heading : 11
		icon-box : 1
		image : 11
		shortcode : 1
		social-icons : 1
		text-editor : 3
	single-page : 1
		theme-post-content : 1


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active by default
	Element Caching: Active
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
Log: showing 20 of 412024-07-16 20:13:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]
2024-07-16 20:13:26 [info] elementor::elementor_updater Started 
2024-07-16 20:13:26 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-16 20:13:28 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-16 20:13:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.1',
)]
2024-07-25 19:18:14 [info] elementor::elementor_updater Started 
2024-07-25 19:18:14 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-25 19:18:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-25 19:18:16 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-25 19:18:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-30 18:53:07 [info] elementor::elementor_updater Started 
2024-07-30 18:53:07 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-30 18:53:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-07-30 18:53:09 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-30 18:53:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-07 12:58:06 [info] elementor::elementor_updater Started 
2024-08-07 12:58:06 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-07 12:58:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]
2024-08-07 12:58:07 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-07 12:58:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]

PHP: showing 2 of 2PHP: 2024-05-24 13:42:27 [warning X 1][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-26 11:55:08 [warning X 6][../wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): ^ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by remcokalf** [comment]
FacetWP dev here. We are experiencing the same issues. 

We're not sure, but it seems like Element Caching is being enabled for users without them choosing to do that? If this is the case, this exacerbates the problem.

We now have to instruct users in our support to turn this setting off globally, or on each FacetWP related widget individually, which could be: Shortcode, HTML, Text Editor widgets containing FacetWP shortcodes, our own 2 Facet- and Listing widgets, and each [supported FacetWP-enabled Post/Loop widget](https://facetwp.com/help-center/using-facetwp-with/elementor/#supported-widgets). This is a lot. 

Having a hook to disable it for pages would be great.
But even better (or additionally) would be a hook in which you can pass widget types/names or even widget content parsed, like FacetWP shortcodes. Because ideally we would like to be able to incorporate a fix in our plugin, so our users are not bothered with all of this.

Currently, we need to have a warning banner and a whole doc page section on this, which is not ideal:
[https://facetwp.com/help-center/using-facetwp-with/elementor/](https://facetwp.com/help-center/using-facetwp-with/elementor/)
[https://facetwp.com/help-center/using-facetwp-with/elementor/#fix-issues-caused-by-elementors-element-caching-feature](https://facetwp.com/help-center/using-facetwp-with/elementor/#fix-issues-caused-by-elementors-element-caching-feature)

**Comment by nicholaszein** [comment]
Hi @xlplugins and @remcokalf!

Apologies for the delay in the response. We are currently handling a huge influx of issues.

Please refer to [this article](https://developers.elementor.com/elementor-3-22-developers-update/#:~:text=Caching%20Widgets%20Output) that guides you on how you can prevent your custom widgets from being cached.

As a suggestion, please reach out on our [Contact Page](https://elementor.com/contact/), and submit to the Partnership Program form, and ask to be added to the Developers Newsletter, this way you can be updated every time we introduce a new feature, including when there are Blog posts outlining how you can leverage a new feature such as the Element Caching. If you decide to join the partnership program, you'll have direct access to our team on Slack, and first party updates about our upcoming changes.

![image](https://github.com/user-attachments/assets/c02ac73e-a960-4a76-97cf-e6a1c4495ca4)

You can also subscribe to the Newsletter by following this guide: https://elementor.com/help/how-to-become-a-beta-tester/

When you switch this option to `Enable`, a modal will appear where you can subscribe to the same Newsletter.

I'm closing this issue as solved, since the information is already ready for usage.

(Btw, I'm a huge fan of both of your work! My clients use your plugins all the time! 🙂)

I hope this helps!

Take care

**Comment by remcokalf** [comment]
@nicholaszein Thank you for pointing us to that function and article! Also did not know about the Partnership program, Slack access and dev newsletter, great!

**Comment by dbjpanda** [comment]
@nicholaszein How can I apply it for a form field? I dynamically render few fields as per url parameter. Or do I need to apply it for entire form?

**Comment by nicholaszein** [comment]
@dbjpanda you apply it to the whole form widget. In the Form widget Settings go to the Advanced tab > Layout section and switch the Cache Settings to inactive.

Any widget you intent to use with dynamic data, you should set the Cache Settings to Inactive.

This feature was designed to be handled at the widget level.

**Comment by dbjpanda** [comment]
@nicholaszein I am asking in terms of programming.

**Comment by nicholaszein** [comment]
@dbjpanda this feature was designed to work at the widget level. 

If when using dynamic data in the Elementor Form fields, it is still being cached, then you found a bug and this would need to be addressed.

**Comment by tomandersen** [comment]
I found the elementor element cache turned on on automatically on all our sites (30) and on at least two of them serious issues. 1) A FacetWP widget failed. 2) The woocommerce 'my account' page (done as elementor) was cached - very bad User Experience. I'm quite sure I would find more issues if I left the ridiculous 'beta experiment (WHY AUTO TURN IT ON)' on. The woo problem is **extremely serious**... shows users as logged in or out at random (depending on what was cached at /my-account/

It's fully broken. Please turn this feature off. Then redesign so its opt in. 

I could also use a timing report on web page generation that showed the slow elements - then I could pick to cache those...

WP 6.7.1, Elementor Pro latest

<img width="1278" alt="Screenshot 2024-12-17 at 11 56 48 AM" src="https://github.com/user-attachments/assets/75d8752f-e31a-4a25-b8ca-d3b2ea75613b" />

**Comment by nicholaszein** [comment]
@tomandersen , before you continue ranting, please read the document below.

https://elemn.to/gh-code-of-conduct

This repository is not the place for the kind of comments you are making on multiple threads, nor the place to make disrespectful remarks.

Please, keep the conversation on-topic and civilized. We will not tolerate offensive or aggressive commentary.

If you wish to file a complaint, the correct place is via Elementor Support (especially since you are a Pro user). From here, we are unable to take any actions on your complaints. The role of this space is to report bugs and suggest features.

Thank you

**Comment by tomandersen** [comment]
Hi,

I am not trying to violate your terms. I left more comments as I figured out the huge scope of this problem. 

I am trying to get your attention. 
This is a very serious security problem. Elementor will create caches of widgets while Users are logged in. Then it will spill those contents to the entire web. 
This is with default settings on the (now active by default "Element Caching" setting). 

I seem to have achieved the attention thing. 

Good luck, 

--Tom

**Comment by tomandersen** [comment]
Sorry, and thanks for replying. This is a serious security issue, and I wanted to make sure elementor staff know about it.

**Comment by nicholaszein** [comment]
You can do it without losing respect and articulating your words. There is absolutely no problem and sharing your frustrations @tomandersen. We completely understand where you're coming from. 

But not by attacking us the way you did. That is not helpful and won't solve your problem. No one here has any reason or desire to harm you in any way.

For what is worth, what you've been reporting seems to be a problem exclusive to your setup, as we are not experiencing these issues on other WooCommerce sites. I personally run a few WooCommerce sites myself, and I am experiencing zero issues with Element Caching and the checkout. In fact the experience has only improved since the editor feels a lot snappier.

But we understand that with the virtually infinite combinations of plugins, server settings, object cache, theme, etc, it is not impossible that some bumps and conflicts could appear. However, in order for us to troubleshoot and if necessary fix these issues, it's crucial that we communicate in a civilized and collaborative way.

Please, don't forget that we are also humans on this side of the screen. And our goal remains to empower your web creation journey. No one here wishes you harm. I hope you can consider this next time. 

Thank you

**Comment by tomandersen** [comment]
Reproduction steps. 

1) Login as admin
2) Visit your /my-account/ page. 
3) **Edit with elementor**. 
4) View /my-account/
5) Proceed to launch another web browser, or incognito, and visit  /my-account/

**Comment by tomandersen** [comment]
https://wordpress-1319077-5120794.cloudwaysapps.com/my-account/orders/￼

That page has the woocommerce my-account widget in two times. Once, in a text widget - works fine - but is agressively cached by woocommerce, and second in a 'shortcode' widget where it works.

**Comment by nicholaszein** [comment]
Elementor has a My Account widget specifically built for this purpose.

The text widget is a static component. Anything you write on it is, and should be static. It shouldn't be used to add dynamic content on it. But if you will, then it's your responsibility to toggle the Cache Settings in the Advanced tab to Inactive.

The Shortcode widget, which was built exclusively for shortcodes, doesn't get cached because it expects its content to be dynamic.

But if you are building for WooCommerce, you should use the widgets that are optimized to handle WooCommerce site parts such as the My Account widget. This would have prevented the problems you're described.

Elementor is not the issue here. It's how you are using it @tomandersen . It is working the way it's intended to work.
