### ISSUE TITLE
More languages broken with the update bug

### ISSUE THREAD

**Issue by SirLouen** [elementor/elementor#28459]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Remember this?
https://github.com/elementor/elementor/issues/14297

Here we go again @nicholaszein 
![image](https://github.com/user-attachments/assets/3546c202-7e84-4e85-858e-60937da8dd4a)

### Steps to reproduce

Opening Issue again...

### Expected behavior

Opening Issue again...

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Opening Issue again...
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @SirLouen!

Thank you for reaching out! 🙏 

As I mentioned in [this comment](https://github.com/elementor/elementor/issues/14297#issuecomment-2253252567), I closed that issue because the old reported bug does not reflect the current version of Elementor. 

As for the language in question, I checked with the team, and the problem is that there is no translation for this language (hi_IN).

Unfortunately, we don't have native speakers to translate Elementor Pro to this language, but we would really appreciate if you would like to contribute. You can follow [these instructions](https://elemn.to/gh-to-help-localize-elementor), and join other community contributors to help translate Elementor to more languages.

Kind regards

**Comment by SirLouen** [comment]
@nicholaszein 

There must be obviously a code issue in Elementor, on why is trying to fetch the `hi_IN` language when you actually don't have this translation available. Probably the "translation" fetcher is broken and should be repaired

Please refer to this conversation:
https://wordpress.org/support/topic/plugin-language-updates-protocol/

I will look into the code when I have time to see if I can spot something. But since this is coming from Elementor Pro, not Elementor, I think that your team should give it a chance and review this flaw, which is seriously annoying (having all the time a pending update, the nonexistent Elementor `hi_IN` translation file, which is false).
