### ISSUE TITLE
Support page is broken - 404 when clicked from logged-in account portal

### ISSUE THREAD

**Issue by czaremanuel** [elementor/elementor#28497]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Issue is with the elementor website, not plugin. When logged into the account portal at my.elementor.com, navigating to "support center" and clicking the link, the page I am redirected to (https://my.elementor.com/support-center) produces a 404 error. 

I've been trying to submit a support ticket all morning. This is unacceptable for a paid plugin. 

![Elem1](https://github.com/user-attachments/assets/35f60326-2963-40be-87f9-bb03331c8b79)
![Elem2](https://github.com/user-attachments/assets/0c129829-63dc-415d-bcc1-56b3c7c47daa)

### Steps to reproduce

1. Go to elementor.com
2. Click "log in" in top-right corner
3. Click "support center" in left-hand menu bar
4. Observe broken 404 page

### Expected behavior

Expected behavior is seeing a support form and submitting a support ticket...

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
NA - elementor.com issue, nothing to do with plugin/my site.
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @czaremanuel!

This space is meant to be used to report issues in the Elementor Editor plugin. For anything else, you need to reach out to support. We are unable to provide support from this repository. In your case, if you cannot access your Elementor Account, or you are having difficulty in reaching out to support, use the form labeled "Account Access & Billing" on our [Contact Page](https://elementor.com/contact):

![image](https://github.com/user-attachments/assets/57e6e80a-e9f6-4c5c-a024-746e487c3aa9)

This issue was solved in the same day you reported it, both here and in the Global Elementor Community on Facebook.

Kind regards
