### ISSUE TITLE
Dynamic Short Codes not Working Properly

### ISSUE THREAD

**Issue by amalsaad28** [elementor/elementor#28490]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Dynamic Short Codes not working properly it shows this error /*! elementor – v3.23.0 – 10-07-2024 */ and shows the css codes.

### Steps to reproduce

It was working properly in the previous versions

### Expected behavior

Sort it out like it was in the previous version dynamic short codes would be coming properly

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Server Environment		
Operating System:	Linux	
Software:	LiteSpeed	
MySQL version:	MariaDB Server v10.11.8-MariaDB-cll-lve	
PHP Version:	8.3.2	
PHP Memory Limit:	512M	
PHP Max Input Vars:	5000	
PHP Max Post Size:	256M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected

WordPress Environment		
Version:	6.5.5	
Site URL:	https://clycksumo.com	
Home URL:	https://clycksumo.com	
WP Multisite:	No	
Max Upload Size:	256 MB	
Memory limit:	40M	
Max Memory limit:	512M	
Permalink Structure:	/index.php/%year%/%monthnum%/%day%/%postname%/	
Language:	en_US	
Timezone:	0	
Admin Email:	mohsin@enlmtd.com	
Debug Mode:	Inactive

Theme		
Name:	Hello Elementor	
Version:	3.0.1	
Author:	Elementor Team	
Child Theme:	No	If you want to modify the source code of your theme, we recommend using a child theme.
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @amalsaad28, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🆕 **Stay Up-to-date:** Make sure you are using the most recent and stable versions of [Elementor](https://wordpress.org/plugins/elementor/#developers), [Elementor Pro](https://elementor.com/pro/changelog/), [WordPress](https://wordpress.org/download/releases/), and your theme.

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 💬 **Description:** In your description, provide examples, screenshots, and screen recordings (just drag and drop in the field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!

- 👣 **Steps to replicate:** Think of it as explaining to someone over the phone how to replicate your issue. They can't see the problem, so explain it in detail in a way that we can try to replicate your issue in our environments. Be thorough.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Without them, we simply can't help. 😕 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.
Best regards
