### ISSUE TITLE
❌ Header duplicates menu  when using the Elementor Developer Edition plugin

### ISSUE THREAD

**Issue by jessreishus** [elementor/elementor#28634]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The WordPress menu previously worked, but the last few weeks it broke somehow and nothing I do fixes it. The preview on the edit screen does not match the final/published format. It duplicates the menu and adds a huge gap/icons between the menus. It appears the menu is not communicating with wordpress and elementor corrrectly. Also, whenever I "delete" the header, and recreate the header using my site logo and word press menu, it pops up the same format as shown in the pictures. 

![Screenshot 2024-09-06 123148](https://github.com/user-attachments/assets/2456fa9a-e6e4-4904-bc46-af5c039410d7)
![Screenshot 2024-09-06 123336](https://github.com/user-attachments/assets/a4c50c6a-cc84-46b6-9ec3-c801da319a88)
![Screenshot 2024-09-06 123350](https://github.com/user-attachments/assets/2bffd56c-ec38-4925-bc2c-9cc26f8e13d4)
![Screenshot 2024-09-06 123406](https://github.com/user-attachments/assets/a3959659-62f8-4fdd-8f72-081766b5b4f0)

https://github.com/user-attachments/assets/48589ea3-5fd8-48ee-afb5-0894dcd94215

### Steps to reproduce

1. Click on header to edit
2. Click on right flex box grid listed as word press menu
3. Review details, it should fit in the space and be legible
4. Click publish
5. Click on preview 
6. Look at the previwe, Observe, scroll down page, it looks totally different

### Expected behavior

1. The menu is duplicated
2. It does not match the stimulus created in Elementor at all 

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

**[Moderation Edit: The user did not provide the full Elementor System Info as <ins>REQUIRED</ins> in the Bug Report Form.]**

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by Daveden2** [comment]
Please the dev edition of Elementor should not be used on a production site. 

Deactivate the dev edition plugin and revert back to Elementor 3.23.x under WP Dashboard > Elementor > Tools

**Comment by nicholaszein** [comment]
Hello @jessreishus!

Thank you for reaching out! 🙏 

We noticed that you're using the **_Elementor Beta (Developer Edition)_** plugin. This edition is a playground for developers to test their plugins and themes with the most recent features of Elementor, and **<ins>it's not quite intended for use on live websites.</ins>**

In the most recent release of this Developer Edition plugin, a conflict between the Core version (3.24.0-dev3) and older versions of the Pro plugin has caused an incompatibility in the rendering of the CSS. This should be fixed with the release of the Elementor Core (Free) version 3.24.0, and Elementor Pro version 3.24.0 tomorrow.

### 🧪 Due to the experimental nature of this Developer Edition plugin, we're unable to provide support for it. 

But don't worry! Our stable versions are full of great features that are ready for prime time on your website.

### 🔄 Please, [revert back to a stable version of Elementor](https://elementor.com/help/revert-to-release-from-developer-edition/) if you're working on a production site.

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [Elementor System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Kind regards
