### ISSUE TITLE
❌ 🧩 Elementor Advanced Tabs are not loading as expected 

### ISSUE THREAD

**Issue by flexyy07** [elementor/elementor#28700]
### Prerequisites

- [x] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I recently built a new page and used the Elementor Advanced Tabs, I noticed this morning the tables aren’t displaying correctly and I can’t figure out what went wrong.

There are 9 tabs and each should be displaying content from different saved templates. Instead all of the tabs are displaying all of the templates. I updated my plugins and tried to completely rebuild the table but still it does not work i do not know its coming from elementor or i did something wrong if someone has similar issue and he resolved this issue let me know 

I thought this might be a bug, but a second website I built which is also using the advanced tabs is also having this problem.

### Steps to reproduce

the screen recording is not uploading it is taking so much time
 

https://github.com/user-attachments/assets/4c18bc28-59d9-4fa5-8dcd-1285095e54e4

### Expected behavior

1. i just want the issue to be resolved .

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Go daddy 
Wordpress
Elementor child theme
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @flexyy07, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 🧩 **Contact 3rd-party Support:** If the issue happens with an Elementor add-on, extension, compatible plugin, or integrated theme, contact their support first. We do not provide support for 3rd-party software.

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Without them, we simply can't help. 😕 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

Elementor doesn't have an _**"Advanced Tabs"**_ widget. This is probably a widget from the **Essential Addons** plugin. See: https://essential-addons.com/advanced-tabs/

Since you haven't provided the required information, we can't know for sure.

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

**🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.**

Best regards
