### ISSUE TITLE
❌ 🧩 Element Pack does not load CSS styles after updating Elementor

### ISSUE THREAD

**Issue by RoninSolution** [elementor/elementor#28708]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Since udapte of elementor pro, all plugin from element pack pro doesn't work. It's mean all CSS file seems corrupted

### Steps to reproduce

1.Put anyone plugin from element pack pro
2. check it in front end and it's look différent
3.Change Elenmetor-setting-performance with "Internal Embedding" for all CSS in the <head> instead of  External File
4. Check front end - It's works now

### Expected behavior

1. Back
2. Front
![Back end elementor](https://github.com/user-attachments/assets/02e48507-69e8-410c-ab39-db83a75abdc3)
![Front end - all element pack pro plugin down](https://github.com/user-attachments/assets/5c9c0a2b-b2c8-44de-ba5f-72c4b7c42f4f)

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

**[Moderation Edit: The contributor did not provide the <ins>full and required</ins> Elementor System Info.]**

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.35
	PHP Version: 8.2.21
	PHP Memory Limit: 512M
	PHP Max Input Vars: 16000
	PHP Max Post Size: 130M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://roninsolution.fr
	Home URL: https://roninsolution.fr
	WP Multisite: No
	Max Upload Size: 128 Mo
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: fr_FR
	Timezone: Europe/Paris

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by TLLIKG** [comment]
Rollback to Elementor 3.23.3, there is a bug in the latest version. I think they will fix it soon

**Comment by nicholaszein** [comment]
Hello @TLLIKG,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Regards
