### ISSUE TITLE
❌ 🔗 🧩 All animations disappeared after updating to 3.24 (Duplicate of #27851)

### ISSUE THREAD

**Issue by setcero** [elementor/elementor#28714]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I found that all the animations are gone after updating to 3.24 (3.23.3 does not have this problem.)

The issue is only when you are logged in. If you are not logged in, all the animations will still appear normally.

Core version is 3.24.2, Pro is 3.24.1

### Steps to reproduce

![Screenshot 2024-09-13 205405](https://github.com/user-attachments/assets/f3bfc465-bb0f-4e82-a9d4-fbff6ad8f8f6)

### Expected behavior

1. Login as admin
2. Checking the frontend, you will see that all the animations are missing.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

**[Moderation Edit: The contributor did not provide the <ins>full and required</ins> Elementor System Info as outlined in the Bug Report form.]**

<details>
<summary>Click to reveal</summary>

````txt


Server Environtment
Linux 3.10.0-1062.el7.x86_64
Web server	Apache/2
PHP version	7.4.21
PHP memory limit	512M
PHP max input variables	1000

Wordpress 
Version	6.6.2

Theme
Name: Hello Elementor
Version: 3.1.1

Active Plugins
Elementor Version: 3.24.2
Author: Elementor.com

Elementor Pro Version: 3.24.1
Author: Elementor.com

The Plus Addons for Elementor 5.6.8
The Plus Addons for Elementor - Pro 5.6.3
Prime Slider 3.15.7
Prime Slider Pro  3.14.2
````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @setcero,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

This is a known problem caused by the Plus Addons plugin. Reach out to their support and ask them to fix the compatibility with Elementor.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

2. 🗑️ **Clear the cache:** Clear all levels of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.

3. 📋 **Meet the Requirements:** Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

### 👎 If after following these steps the problem persists, you can submit a new issue with details to reproduce it so we can take a look.

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [Elementor System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Regards
