### ISSUE TITLE
Advanced Tabs Plus Elementor Tabs Issue 

### ISSUE THREAD

**Issue by flexyy07** [elementor/elementor#28768]
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

last week i submitted a report where i miss to mention that the issue is coming from the elementor tabs as well as Advanced Tabs which is from the plugin and i don't know why my issue is being closed.

The issued i faced is that the tabs are not displaying in the front-end but its show in the elementor 

### Steps to reproduce

https://github.com/user-attachments/assets/36c607ca-380d-4c9a-9070-4eafa35116f4

Here is the video of the Tabs , I have tried both the Elementor Tabs and the plugin (Essential Addons) Advanced Tabs 

### Expected behavior

I think the issue is coming from the Custom Styling when i apply my custom styling to it , and when i removed the custom styling some time it works on the front-end but not always.

And i am using the Hello Elementor Theme 
after deactiviting the plugins the i still encounter the issue. 

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Server Environment		
Operating System:	Linux	
Software:	Apache	
MySQL version:	MariaDB Server v10.6.18	
PHP Version:	8.2.22	
PHP Memory Limit:	256M	
PHP Max Input Vars:	1000	
PHP Max Post Size:	32M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected

WordPress Environment		
Version:	6.6.2	
Site URL:	https://maqx.org	
Home URL:	https://maqx.org	
WP Multisite:	No	
Max Upload Size:	32 MB	
Memory limit:	40M	
Max Memory limit:	256M	
Permalink Structure:	/%category%/%postname%/	
Language:	en_US	
Timezone:	0	
Debug Mode:	Inactive
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by flexyy07** [comment]
Note:
I also clear the server issue and i cannot give the access to anyone because its a company website

**Comment by nicholaszein** [comment]
Hello, @flexyy07.

As explained in the last issue you've submitted, Elementor does not have a "Advanced Tabs" widget. This is likely a widget from a 3rd-party add-on.

**We are unable to provide support for 3rd-party addons.**

Since you haven't provided the full and required Elementor System Info as instructed in the Bug Report Form, we cannot continue evaluating your issue. Keep in mind that you agreed that your issue would be closed without any action if you didn't provide the required information.

In the video you shared, it's clear that the widget is not a native Elementor widget.

Please, reach out to the addon developer and ask them for help to fix your issue with their widget.

Best regards
