### ISSUE TITLE
⛔ Custom Code can't be deleted without adding space

### ISSUE THREAD

**Issue by spasauna** [elementor/elementor#28783]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Custom code snippets can't be deleted when just selecting all and then delete it. You always need to add a space before deleting everything because it seems like a custom code snippet can't be empty.

### Steps to reproduce

1. Create a custom code snippet in Elementor
2. Put something into it
3. Delete everything
4. Save/update it
5. Be surprised that deleting didn't work because you need to add a space to your empty code snippet to make it not totally empty and saveable

### Expected behavior

1. I expect to make it possible to have a completely empty code snippet without having the need to add a space. I messed up a few times until I realized that the code snippet is still there although I deleted it... but didn't add a space.

### Isolating the problem

- [x] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.37
	PHP Version: 8.3.10
	PHP Memory Limit: 512M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://XXXXXXXXXXXXXXX.com
	Home URL: https://XXXXXXXXXXXXXXX.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.3.6
		Author: WP Engine

	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com


== Features ==
	Custom Fonts: 5
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Header & Footer: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Inactive
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Element Caching: Inactive by default
	Link In Bio: Inactive by default
	Floating Buttons: Active
	Elementor Editor Events: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active
	Menu: Active
	Taxonomy Filter: Active by default
	Search: Active


== Log ==
	


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @spasauna,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not a bug caused by Elementor. Here's what we found out:
That's the intended behavior. When you create a new Custom Code, it's expected you'll add something to it, as it will be displayed in the frontend depending on the location chosen. If you leave it empty, it means there is nothing to be displayed, but the action to display it is based on the default WordPress Post Status (Draft, Pending Review, Published, etc.), and the Display Condition set, since Custom Codes are nothing more than a customized Custom Post Type. Leaving the code empty or with a space may potentially impact your website performance or even cause an error, since there is a whole mechanism working behind the scenes to render the contents of your Custom Code CPT in the frontend of your site.

![image](https://github.com/user-attachments/assets/63638467-1e7f-483b-b1ba-b14cc827d1e7)


### ✅ What you can do to solve your issue:
If you wish to delete a Custom Code, instead of removing the contents of the code, you should simply send the Custom Code to the **Trash**. This will ensure the Custom Code is no longer loaded in the frontend.

![image](https://github.com/user-attachments/assets/63ed21a1-1282-471f-9bda-be9236893dde)


### 👍 For now, that's all we can help with. 

Kind regards
