### ISSUE TITLE
⛔ 🧩 📚 3rd-party Locomotive-scroll.js script does not work with the new native CSS Smooth Scroll

### ISSUE THREAD

**Issue by brunoalbim** [elementor/elementor#29103]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The new Elementor Core v3.25.0 (https://github.com/elementor/elementor/issues/13773) update that adds "CSS smooth scrolling" by default, ended up generating conflicts with the "locomotive-scroll.min.js" library that I use on some websites to generate smooth navigation, as the features of Elementor natively does not meet this demand.

With just a simple code, you can add this library:

```
<script src="https://cdn.jsdelivr.net/npm/locomotive-scroll@beta/bundled/locomotive-scroll.min.js"></script>
<script>
    (function () {
        const locomotiveScroll = new LocomotiveScroll();
    })();
</script>
```

Which works normally.

However, with the new update, and the addition of the "scroll-behavior: smooth" CSS code, the scroll does not work correctly.

The only alternative to this problem would be to add CSS code right below the library's JS code:

```
<style>
	html {
		scroll-behavior: auto;
	}
</style>
```

This is a great library, and works very well with Elementor and the Hello Elementor Theme, I believe it would be very beneficial to also analyze the possibility of adding it to Elementor, and having more advanced control over page scrolling.

For example (leaving a little on the problem above), Elementor's scroll effect does not have the possibility of adding a dynamic size of the fixed Header at the top naturally, for this I use this JS code that uses standard Elementor resources, and add the size value of the page's "header" tag:

```
window.addEventListener('elementor/frontend/init',function(){
	elementorFrontend. hooks.addFilter( 'frontend/handlers/menu_anchor/scroll_top_distance', function(scrollTop) {
			return scrollTop - jQuery('header').outerHeight();
	});
});
```

### Steps to reproduce

1. Adicione o código no "Elementor custom code":

```
<script src="https://cdn.jsdelivr.net/npm/locomotive-scroll@beta/bundled/locomotive-scroll.min.js"></script>
<script>
    (function () {
        const locomotiveScroll = new LocomotiveScroll();
    })();
</script>
```

2 . Ative de maneira global.

3. Use com a versão mais recente (v3.25.0)

### Expected behavior

The page needs to scroll smoothly when scrolling down. This will be possible, just by disabling the added CSS scroll feature:

```
<style>
	html {
		scroll-behavior: auto;
	}
</style>
```

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 8.0.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: pt_BR
	Timezone: -3
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pt-BR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.25.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.0
		Author: Elementor.com

	JetEngine
		Version: 3.5.7
		Author: Crocoblock

	JetSmartFilters
		Version: 3.5.7.1
		Author: Crocoblock

	Reading Time WP
		Version: 2.0.16
		Author: Jason Yingling

	UpdraftPlus - Backup/Restore
		Version: 1.24.6
		Author: TeamUpdraft, DavidAnderson

	WP Renamer Image SEO
		Version: 0.1.9
		Author: Bruno A


== Uso dos elementos ==
	
	archive : 1
		container : 1
		jet-listing-grid : 1
		jet-smart-filters-pagination : 1
		jet-smart-filters-search : 1
		theme-archive-title : 1
	footer : 1
		button : 1
		container : 3
		image : 1
		text-editor : 3
	header : 1
		container : 3
		icon : 1
		image : 1
		nav-menu : 1
	page : 1
		button : 1
		container : 4
		heading : 2
		text-editor : 4
		theme-site-logo : 1
	section : 2
		button : 1
		container : 6
		form : 1
		heading : 2
		icon : 1
		text-editor : 2
	wp-page : 1
		container : 4
		jet-listing-grid : 1
	single-post : 2
		container : 8
		heading : 2
		icon : 1
		jet-listing-grid : 2
		share-buttons : 2
		spacer : 1
		text-editor : 2
		theme-post-content : 2
		theme-post-excerpt : 1
		theme-post-featured-image : 2
		theme-post-title : 2
	single-page : 1
		container : 1
		spacer : 1
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	jet-listing-items : 0
		button : 2
		container : 7
		heading : 2
		image : 2
		text-editor : 2
	error-404 : 1
		container : 1
		heading : 2


== Configurações ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Recursos ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrações ==
	


== Experimentos do Elementor ==
	Carregamento de CSS melhorado: Inativo por padrão
	Ícones de fontes em linha: Inativo por padrão
	Pontos de interrupção personalizados adicionais: Inativo
	Contêiner: Ativo
	Atualizar a biblioteca Swiper: Ativo por padrão
	Desempenho de elementos aninhados: Ativo por padrão
	Carregamento de controle otimizado: Ativo por padrão
	Marcação otimizada: Inativo por padrão
	Carregar condicionalmente os arquivos CSS do Swiper: Inativo por padrão
	Integração de plugins: Ativo por padrão
	Rolagem suave em CSS: Ativo por padrão
	Padrão para Novo Construtor de Tema: Ativo por padrão
	Cabeçalho e rodapé: Ativo por padrão
	Tela inicial do Elementor: Ativo por padrão
	Páginas de destino: Ativo por padrão
	Elementos aninhados: Ativo por padrão
	Barra superior do editor: Ativo
	Painel de páginas: Inativo por padrão
	Cache de elementos: Inativo por padrão
	Link na biografia: Ativo por padrão
	Botões flutuantes: Ativo por padrão
	Eventos do editor do Elementor: Inativo por padrão
	Widgets atômicos: Inativo por padrão
	Lista de verificação do Launchpad: Inativo por padrão
	Menu: Inativo por padrão



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatível

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @brunoalbim,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We do not officially provide or intent to provide support for locomotive-scroll.js, therefore the feature you're referring to is working as intended.

### ✅ What you can do to solve your issue:
If you wish to apply smooth scroll using locomotive, this will require custom code that is out of our scope to support. Meaning that you are responsible for making it compatible. Applying a single line of CSS as you mentioned does seem to solve the issue for you. You can add this line of CSS to your child theme's style.css file, or even to Elementor's Site Settings > Custom CSS styles to solve your issue.

As for the **Scroll Offset** for sticky elements, this feature was added to Elementor Pro in version 3.25.0, and you can define the value in pixels by going to the sticky element in question, then navigating to the Advanced tab > Motion Effects, and you'll find the option to set the Scroll Offset there.

Please keep in mind that Elementor GitHub issues are not intended to be used as feature requests, and we cannot handle feature requests posted here. If you have an idea and wish to suggest it, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal support or feature requests.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
