### ISSUE TITLE
⛔ Smooth Scroll with Native CSS not working with Firefox Browser

### ISSUE THREAD

**Issue by mikedoyledesign** [elementor/elementor#29333]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I noticed on 3.25.8 that my Elementor sites on Firefox do not correctly Smooth Scroll on anchor links. It jumps to the section, whether in a header or back-to-top button, or general anchor link. This is happening on multiple sites I have built on Elementor 3.25.X
Rolling back to any 3.25.X produces the same issue on Firefox.
Rolling back to any 3.24.X and earlier fixes this issue as I assume the JavaScript library is implemented again. 

This issue does not occur on Chrome or Edge on Desktop, nor does it occur on Safari on Mobile. 

### Steps to reproduce

1. Update Elementor to 3.25.X
2. In Firefox, click on anchor links.
3. Page doesn't smooth scroll to destination.

https://github.com/user-attachments/assets/976d5b03-8cf9-469c-a16a-eebc8201feaf

### Expected behavior

1. Update to Elementor 3.25.X
2. In Firefox, clicking on anchor links provides a smooth CSS experience as intended.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Ubuntu) v8.0.28
	PHP Version: 8.1.27
	PHP Memory Limit: 256M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7
	Site URL: https://awdeinfo.com
	Home URL: https://awdeinfo.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0

== Active Plugins ==

	Elementor
		Version: 3.25.8
		Author: Elementor.com

	Elementor Header &amp; Footer Builder
		Version: 1.6.46
		Author: Brainstorm Force, Nikhil Chavan

	Smooth Back To Top Button
		Version: 1.1.14
		Author: Tanvirul Haque


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Inactive by default
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Elementor Home Screen: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Launchpad Checklist: Inactive by default
	Nested Elements: Inactive by default
	Editor Top Bar: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default


== Log ==
	
Log: showing 20 of 432024-04-10 20:38:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.3',
  'to' => '3.20.4',
)]
2024-04-10 20:38:21 [info] elementor::elementor_updater Started 
2024-04-10 20:38:21 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-10 20:38:21 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-10 20:38:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.3',
  'to' => '3.20.4',
)]
2024-04-23 02:06:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.4',
  'to' => '3.21.1',
)]
2024-04-23 02:06:13 [info] elementor::elementor_updater Started 
2024-04-23 02:06:13 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-23 02:06:13 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-23 02:06:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.4',
  'to' => '3.21.1',
)]
2024-07-23 21:30:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.1',
  'to' => '3.23.2',
)]
2024-07-23 21:30:42 [info] elementor::elementor_updater Started 
2024-07-23 21:30:42 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-23 21:30:42 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-23 21:30:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.1',
  'to' => '3.23.2',
)]
2024-11-19 15:53:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.2',
  'to' => '3.25.8',
)]
2024-11-19 15:53:44 [info] elementor::elementor_updater Started 
2024-11-19 15:53:44 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-19 15:53:44 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-19 15:53:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.2',
  'to' => '3.25.8',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatible

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @mikedoyledesign,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's why:
Elementor's new CSS Smooth Scroll feature follows the **best practices for accessibility**, this means smooth scroll will only work if the visitor's Operating System (OS) or browser doesn't disable animations/motion effects. It uses the [**`prefers-reduced-motion`**](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) media feature and only triggers the smooth scrolling if **`no-preference`** is detected. This ensures your visitors' preferences are respected since a significant par of the population suffers from [motion sickness](https://www.a11yproject.com/posts/understanding-vestibular-disorders/).

When we test on an environment where reduced motion isn't enabled, we can see the Smooth Scroll behaving as intended and expected:

https://github.com/user-attachments/assets/f4251880-1ece-4871-90ca-8885578f576a

Moreover, from the video you shared, we see you haven't performed the **Elementor Data Updater** after updating, neither cleared, flushed, or purged all levels of cache (server, site, CDN, browser), which are essential procedures that need to be executed after an update. Which may lead to your browser not loading the most recent assets from Elementor.

### ✅ What you can do to solve your issue:
1. If you have enabled Reduced Motion on your browser or OS level, revert to allow motion effects if you want to see the Smooth Scroll.
2. Make you have executed the **Elementor Data Updater** procedure after updating Elementor.
3. Ensure all levels of cache applicable to your website are cleared after running the Data Updater. Most hosting services have cache enabled at the server level. Make sure it is purged from your hosting dashboard, or reach out to your hosting provider for assistance.
4. Make sure your plugins are not conflicting with Elementor by temporarily deactivating them and testing the page on a incognito/private window.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
