### ISSUE TITLE
❌ 🔗 Invalid Issue: Editors should be able to add HTML inside heading elements (Duplicate of #27939)

### ISSUE THREAD

**Issue by caspervoogt** [elementor/elementor#29366]
Issue https://github.com/elementor/elementor/issues/27939 was closed stating:

> ### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's why:
> This is part of a security enhancement for the Heading widget introduced with Elementor v3.22. Only administrator roles are allowed to add html to the Heading widget.
> 
> We have no plans to change this behavior due to security concerns.
> 
> ### ✅ What you can do to solve your issue:
> Only administrator roles are allowed to add html attributes to the Heading widget. Ensure your user has the administrator role.
> 
> ### 👍 For now, that's all we can help with. 

Clearly, this issue IS caused by Elementor, as described in the response: "This is part of a security enhancement for the Heading widget introduced with Elementor v3.22". 

This change in 3.22 broke HTML elements on the front page of one of our customers' sites, due to editors editing that page. When they did so, it stripped the HTML from those heading elements, even though they were editing other elements on the page, and not the heading elements.

I understand you have no plans to change this behavior due to security concerns, but for at least some sites it has caused breakage and is a regression introduced by updates made by Elementor. 

Please consider adding a WordPress permission to let site owners decide for themselves if they want editors to be able to add HTML to heading elements.

**Comment by nicholaszein** [comment]
@caspervoogt. As pointed, **"We have no plans to change this behavior due to security concerns."** This means it is not a bug, as the widget is working as intended.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Please don't use GitHub issues to request features, or to submit issues without using the Bug Report form.

Kind regards
