### ISSUE TITLE
⛔ 🧩 🛟 3rd-party Support Request: Footer disappears when using Polylang and Polylang for Elementor

### ISSUE THREAD

**Issue by SaraBroi** [elementor/elementor#29678]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hello everyone,

I am experiencing an issue with a website I am creating when using Elementor and the Polylang plugins. Specifically, when I activate the Polylang and Polylang for Elementor plugins, the footer of the theme I am using (Pura) disappears.

Here are the details of the issue:
	•	The footer, which was created as a container in Elementor, disappears not only on the live website but also in the “Edit with Elementor” section.
	•	Additionally, I cannot make changes to the footer from the Footer section in WordPress when these plugins are active.
	•	When I deactivate Polylang and Polylang for Elementor, the footer reappears and functions normally.

Could you please advise me on how to resolve this issue?
If additional information is required, I am happy to provide it. Thank you in advance for your assistance!

### Steps to reproduce

1. Istall and activate the Polylang and Polylang for Elementor plugins
2. Go to the page where the footer is already present and visible
3. Check the live website or try to edit the footer in the “Edit with Elementor” section and also modify it in the Footer section in WordPress.

Expected result
The footer should remain visible on the live website, be editable in the “Edit with Elementor” section, and also modifiable in the Footer section in WordPress.

Actual result 
The footer disappears from the live website and is not visible or editable in Elementor, nor is it editable in the Footer section in WordPress.

### Expected behavior

Expected Behavior

When activating the Polylang and Polylang for Elementor plugins, the footer should remain visible on the live website, editable in the Elementor editor, and also modifiable from the Footer section in WordPress. There should be no conflict between the plugins and the footer, allowing it to be accessible and editable in all relevant areas.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	•	Operating System: Darwin
	•	Software: nginx/1.26.1
	•	MySQL Version: MySQL Community Server - GPL v8.0.16
	•	PHP Version: 8.2.23
	•	PHP Memory Limit: 256M
	•	PHP Max Input Vars: 4000
	•	PHP Max Post Size: 1000M
	•	GD Installed: Yes
	•	ZIP Installed: Yes
	•	Write Permissions: All right
	•	Elementor Library: Connected

== WordPress Environment ==
	•	Version: 6.7.1
	•	Site URL: http://squillami.local
	•	Home URL: http://squillami.local
	•	WP Multisite: No
	•	Max Upload Size: 300 MB
	•	Memory limit: 40M
	•	Max Memory limit: 256M
	•	Permalink Structure: /%postname%/
	•	Language: it_IT
	•	Timezone: 0
	•	Debug Mode: Inactive

== Theme ==
	•	Name: Pura Child
	•	Version: 1.0.0
	•	Author: Pura
	•	Child Theme: Yes
	•	Parent Theme Name: Pura
	•	Parent Theme Version: 1.0.0
	•	Parent Theme Author: Pura

== User ==
	•	Role: Administrator
	•	WP Profile Language: it-IT
	•	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

== Active Plugins ==
	•	All-in-One WP Migration: Version: 7.87, Author: ServMask
	•	Contact Form 7: Version: 6.0, Author: Takayuki Miyoshi
	•	Elementor: Version: 3.25.4, Author: Elementor.com
	•	Loco Translate: Version: 2.6.14, Author: Tim Whitlock
	•	MC4WP: Mailchimp for WordPress: Version: 4.9.18, Author: ibericode
	•	Uxper Booking: Version: 1.1.8, Author: Uxper
	•	Uxper Elementor: Version: 1.0.0, Author: Uxper
	•	Uxper Metabox: Version: 1.0.0, Author: Uxper
	•	WooCommerce: Version: 9.3.3, Author: Automattic
	•	Yoast SEO: Version: 23.4, Author: Team Yoast

== Elementor Experiments ==
	•	Enhanced CSS Loading: Disabled by default
	•	Inline Font Icons: Enabled by default
	•	Additional Breakpoints: Enabled by default
	•	Container: Enabled by default
	•	Swiper Library Update: Enabled by default
	•	Nested Elements Performance: Enabled by default
	•	Optimized Control Loading: Enabled by default
	•	Optimized Markup: Disabled by default
	•	Conditionally load Swiper CSS files: Disabled by default
	•	Plugin Onboarding: Enabled by default
	•	Smooth Scroll CSS: Enabled by default
	•	Elementor Home Screen: Enabled by default
	•	Landing Page: Disabled by default
	•	Nested Elements: Enabled by default
	•	Unified Toolbar in Editor: Enabled by default
	•	Pages Panel: Disabled by default
	•	Element Cache: Enabled by default
	•	Link In Bio: Enabled by default
	•	Floating Buttons: Enabled by default
	•	Elementor Editor Events: Disabled by default
	•	Atomic Widgets: Disabled by default
	•	Launchpad Checklist: Enabled by default

== Log ==

PHP: showing 4 of 4
	•	2024-11-03 18:07:19 [warning X 70] [image.php::113] Trying to access array offset on value of type bool [array]
	•	2024-11-03 18:25:38 [warning X 4] [revisions-manager.php::363] Undefined array key “editor_post_id” [array]
	•	2024-12-01 18:40:44 [warning X 1] [js.php::17] Undefined array key “url” [array]
	•	2024-12-22 17:59:03 [notice X 1] [api.php::164] Automatic conversion of false to array is deprecated [array]

JS: showing 6 of 6
	•	2024-11-20 16:41:54 [error X 3] [icons.min.js:1:4333] undefined is not an object (evaluating ‘window.elementorV2.ui’)
	•	2024-11-20 16:41:54 [error X 3] [ai-media-library.min.js:3:489883] Can’t find variable: elementorV2
	•	2024-11-27 16:45:37 [error X 4] [load-scripts.php:2:28767] undefined is not an object (evaluating ‘c[0].value’)
	•	2024-12-01 18:38:03 [error X 14] [pickr.min.js:2:19552] null is not an object (evaluating ‘this._eventListener[t]’)
	•	2024-12-01 18:38:06 [error X 2525] [pickr.min.js:2:14798] null is not an object (evaluating ‘this._lastColor.clone’)
	•	2024-12-08 15:13:15 [error X 2] [react-dom.min.js:10:23781] Blocked a frame with origin “http://squillami.local” from accessing a cross-origin frame. Protocols, domains, and ports must match.

== Elementor - Compatibility Tag ==
	•	Uxper Elementor: Compatibility unspecified.

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @SaraBroi ,

Thank you for reaching out! 🙏 

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party themes/plugins/add-ons/extensions.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. 🆕 **Stay Up-to-date:** Make sure you are using the most recent and stable versions of [Elementor](https://wordpress.org/plugins/elementor/#developers), [Elementor Pro](https://elementor.com/pro/changelog/), [WordPress](https://wordpress.org/download/releases/), and your theme.

2. 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

3. 🗑️ **Clear the cache:** Clear all levels of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.

4. 📋 **Meet the Requirements:** Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

5. 🧩 **Contact 3rd-party support:** Reach out to the 3rd-party addon support and ask for assistance to ensure compatibility with the latest version of Elementor. 

Regards
