### ISSUE TITLE
🚀 Feature Request: Add a User Registration Form widget (Duplicate of #2775)

### ISSUE THREAD

**Issue by rafaramos** [elementor/elementor#3253]
Option of register in WordPress into the forms.

**Comment by bainternet** [comment]
@rafaramos 

as far as we know there is no native WordPress registration form like there is for [login](https://codex.wordpress.org/Function_Reference/wp_login_form)

which is what the Forms widget uses for login.

So Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

But for now, if you want to implement it yourself you can use the provided hook of [the forms widget ](https://github.com/pojome/elementor/blob/master/docs/content/pro/forms.md) and recreate the registration process.


Thanks for the feedback.

**Comment by tmhopper** [comment]
@rafaramos  & @bainternet 

I see the hook link however it is broken

Do either of you have the link? or documentation for the registration hook?

**Comment by nicholaszein** [comment]
> Do either of you have the link? or documentation for the registration hook?

Hello @tmhopper!

I'm Nick, I'm the new Developers Community Moderator. Thank you for having the patience to wait for an answer, and I'm sorry it took us so long to get back to you. 🙏 

You can find the documentation for the Form widget here: https://developers.elementor.com/docs/hooks/forms/

I hope this helps.

Kind regards

**Comment by nicholaszein** [comment]
Hello @rafaramos!

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #2775, which is on the same subject. For this reason, I'm ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
