### ISSUE TITLE
✅ 📚 🚀 Feature Request: Possibility to install Elementor Pro with Composer

### ISSUE THREAD

**Issue by wolfika** [elementor/elementor#4042]
Many other premium WordPress vendors provide the possibility to install their plugins as a Composer dependency. For example, ACF PRO can be installed by declaring a custom Composer repository in your `composer.json`, and you need to include your license key in the package URL as a query parameter, as such, their server can identify the request caller, and decide whether to serve them the plugin's zip, or not. See methodology here: https://github.com/PhilippBaschke/acf-pro-installer

I wonder if such thing is possible with Elementor? This is a feature I really miss, because at our company, we very much like to have every dependency in version control. We have a way to have Elementor PRO in version control right now, but when it comes to updates, it becomes kind of a manual task, and it'd be really nice if we didn't have to deal with this anymore. I'm sure other people would benefit from this too.

Any comments?

Thanks!

**Comment by notechup** [comment]
Just stopped by to voice my support to support this :)

**Comment by abdusfauzi** [comment]
Would love to know if there's some plan with this 👍

**Comment by lf-jeremy** [comment]
Yoast just recently rolled this out. Would be great to have this option with elementor as well.

https://github.com/Yoast/wordpress-seo/issues/4560

This comment laid down a lot of the options for implementation of auth.

https://github.com/Yoast/wordpress-seo/issues/4560#issuecomment-355287039

In their case, they opted for an auth token specified in the http-basic section of `~/.composer/auth.json`, with the auth token available to users through their licensing portal, my.yoast.com, which pretty much parallels elementor's own my.elementor.com

Upgrading elementor has always felt like a chore having the pro plugin install alongside the free version rather than replace it. Being able to rely on semantic versioning and composer to manage upgrades would be a great addition, especially when it offers authentication schemes that allow premium publishers to maintain proper control - since the alternative is having your users privately host their own repos with your premium plugin and manually update their repo with each release in addition to pulling the latest version into their projects.

**Comment by tristanbes** [comment]
Please please please, we need this :-) 

FYI, DeliciousBrains (wpmigrate pro) did this: https://deliciousbrains.com/wp-migrate-db-pro/doc/installing-via-composer/

**Comment by tristanbes** [comment]
The WordPress plugin community is vastly a nightmare. Having to cry about this for a *paid* plugin is pathetic and exhausting.

**Comment by ramzi-is** [comment]
Hello, 

I would like to know if it is possible to install Elementor Pro with Composer.

Thank you

**Comment by TimLamoureux** [comment]
+1 for this feature request!

And thank you so much for how great Elementor is

**Comment by pabloaugusto** [comment]
Need this feature too! Please

**Comment by thelar** [comment]
So, well over a year since this thread was started and just silence from the plugin authors??? I too have many wordpress sites all using roots/bedrock with plugins maintained and manged with composer - the capability to have this for elementor pro is a MUST, not a 'nice to have'!!!

**Comment by tristanbes** [comment]
sorry, they're to busy winning money to read this github issue... compose...what ?

**Comment by synio-wesley** [comment]
+1 also using roots/bedrock and composer

**Comment by BartoszLobejko** [comment]
+1 also using roots/bedrock and composer

**Comment by wolfika** [comment]
@KingYes @arielk At least an acknowledging response to all these paying customers would be decent.

**Comment by yangm97** [comment]
I went ahead and made a public repository for elementor pro while this isn't addressed: https://github.com/yangm97/elementor-pro

**Comment by Daisuke-sama** [comment]
I have a fresh answer from support

> Thank you for contacting us.
> 
> I assume that you're referring to the Composer PHP Package manager (https://getcomposer.org/).
> If this is the case, unfortunately I'm not familiar with this tool, however I would advise you to join our Facebook community and check with our users there as somebody may have already used it.

**Comment by ekandreas** [comment]
Wow! Impressive! "I'm not familiar with this tool"

**Comment by anthonyjesmok** [comment]
Adding my vote for this issue to be prioritized. It would really help keep our WP repos down in size.

**Comment by tomslominski** [comment]
Just adding my support to this 🙂

**Comment by epoplive** [comment]
@anthonyjesmok @yangm97 out of curiosity how are you guys handling the css being stored in the uploads folder?  We've had to resort to using the option to inline it to make the plugin work in a load balanced environment and because we deploy from git and don't use the uploads folder except as temp storage before sending to s3.

**Comment by anthonyjesmok** [comment]
> @anthonyjesmok @yangm97 out of curiosity how are you guys handling the css being stored in the uploads folder? We've had to resort to using the option to inline it to make the plugin work in a load balanced environment and because we deploy from git and don't use the uploads folder except as temp storage before sending to s3.

We inline it or use it in our Global CSS.

**Comment by epoplive** [comment]
My guess is the main objection to doing this is that their primary user base is people just smart enough to find out how to remove the activation check, as any kind of support for an modern hosting environment and even simple developer requests complete with test passing pull requests go completely unanswered.

This is a definite +1 from me, as I didn't even know installing wordpress and plugins from composer was possible without a ton of work on my end.  I'll be looking into this and i guess probably hosting my own copy of the pro repo if that's what it takes to support it.  Wordpress is pretty powerful but things need to catch up to modern times and development practices.  

Wordpress and Elementor are unfortunately a necessary evil for my company currently, it would be great if they could at least give us a repo so we could send pull requests to.  I've found some bugs that result in things like 1.4megs of css being added to a page for no reason when a cta widget has a certain setup, but there's not really even a place to report it because the support is genuinely clueless.

**Comment by yangm97** [comment]
It's very frustrating as a paying customer to come back to this issue after almost a year later and see it sits unresolved, especially given how little effort it gets for them to push elementor pro as a composer package.

@epoplive I currently run wordpress from a read-only container along with a rw,noexec volume for the uploads directory (which is also set up on nginx to not execute php files). However I'm contemplating the idea of using some s3 plugin instead, but seeing as Elementor likes to hardcode URLs in the db I'm not sure this would work well or at all.

I also wonder how you guys manage dev->stag->prod db/uploads/etc. changes. Although that's kind of offtopic for this issue, so if anyone knows a better place to discuss best practices don't be afraid to link here.

**Comment by yashasolutions** [comment]
+1 for Elementor to provide a normal way to install the pro version using composer

**Comment by zenopopovici** [comment]
I don't understand why this is so hard.... for ACF and WPML, at least you can download the file via a key and you can also version it because they have a clear url naming scheme. With Elementor it's impossible to automate this. They don't serve file versions or any discernible url naming scheme.

Really frustrating and annoying for paying customers with tens of sites running elementor.

**Comment by IRTBNSM** [comment]
+1  - Very very welcome feature for the pro version.

**Comment by danharper83** [comment]
This needs solving before I purchase.

**Comment by g000m** [comment]
+1, this is an important feature

**Comment by ekandreas** [comment]
Three years not understanding the importance of this issue speaks for itself 😢

**Comment by ianrandmckenzie** [comment]
Throwing my hat in the ring. Composer support would make my life infinitely easier when it comes to maintaining my clients' sites.

**Comment by leonardopinori** [comment]
+1

**Comment by Leadsquad** [comment]
Any update?

**Comment by jeazyee** [comment]
It is so annoying that I always have to update my private repo with composer support when a new version of ep is out...

**Comment by SiliconMachine** [comment]
+1

**Comment by MisatoTremor** [comment]
+1

**Comment by vanhovepieter** [comment]
It seems we all do this in the same way, maintaining a mirror repository ourselves and exposing this as a composer package, so it would save us so much effort if you would simply make an official package for this.

**Comment by dvincitravis** [comment]
+1

**Comment by chriswagoner** [comment]
I saw we fork Elementor PRO, combine it with free, package it for composer and charge for it. Let Elementor team keep paying to develop it and we'll just keep updating our package.

**Comment by FaithlessLooting** [comment]
Another team checking in to say why doesn't this exist... we've got 10+ elementor sites on roots/bedrock and maintaining them is a nightmare at times

**Comment by ianrandmckenzie** [comment]
> Another team checking in to say why doesn't this exist... we've got 10+ elementor sites on roots/bedrock and maintaining them is a nightmare at times

@FaithlessLooting I ended up making a shell script to partially resolve this. If you want, I can share. It's private right now because I wasn't really sure if anyone would have a use for it since a lot of stuff is hard-coded.

**Comment by mjatzgit** [comment]
+1

**Comment by susihab** [comment]
+1

**Comment by diomededavid** [comment]
+1 *2

**Comment by ibobo** [comment]
+1

**Comment by PasinduOshadha** [comment]
+1 from me too.

**Comment by andronocean** [comment]
Another +1.

**Comment by tahiratta** [comment]
Come on. Please fix it

**Comment by mafudelaptu** [comment]
+1

**Comment by juhojama** [comment]
Still nothing?

**Comment by synio-wesley** [comment]
I talked to the Global Community Manager of Elementor in September 2022 at Wordcamp Netherlands. I discussed this issue in length but the team that was present didn't know what Composer was. They told me to send them a mail or message on WhatsApp, so I did both. After a few days I got a reply that they would put a new recruit on this issue. But I haven't heard back yet. 2 months have passed now. I just asked for another status update but I'm still awaiting feedback.

**Comment by synio-wesley** [comment]
UPDATE: I got a reply from the Global Community Manager. He says that the new recruit began working at a later time than expected and that he forgot to mention the Github issues to him because of that.

He asked me to tag him and his colleague. So that's what I will do now. Hopefully Elementor Pro will soon get Composer support, which will make it much more useful for professional and modern website builds.

@nicholaszein @VerdiH Thanks for looking into this for us! Let me know if you need any help in implementing this. There are a lot of ways to do this. Delicious Brains has written a blog post about how they achieved this. I'm not saying it's necessarily the right approach for Elementor, but maybe it can give you some insight in how to set it up: https://deliciousbrains.com/composer-premium-wordpress-plugins/

**Comment by vincequeiroz** [comment]
The Yoast SEO team have been doing the same as Delicious Brain team.

https://yoast.com/help/how-to-install-yoast-plugins-using-composer/

**Comment by nicholaszein** [comment]
Hello everyone!

I'm here to give you an update about this feature request.

First of all, let me make it clear: **We hear you**! You want to be able to install Elementor Pro via Composer, and we have discussed this request internally.

To make this possible there are some challenges we need to overcome, and this is not a simple task. We are considering the best way to make this possible, as well as when, and if we will implement such a feature.

All I can say for now is that we are looking into it, and we will update you with an answer when we have news. For now, all I can ask you is to be patient. We have many other features to introduce, as well as changes to our infrastructure before considering implementing this option. I hope you can understand. 🙏 

Kind regards

**Comment by tristanbes** [comment]
4 years to aknowledge the issue (2018). 
4 more years to finally use composer, open your bets 👯 
See you in 2026.
(Pardon the tone of my message but this is not open source, this is paid software)

**Comment by synio-wesley** [comment]
Yes, it's very sad. Unfortunately Elementor is not the only WP company that is behind the times.
Right now I'm using Satispress to manage those pesky plugins that don't have Composer support: `https://github.com/cedaro/satispress`
That way I can update the pro plug-ins on 1 install and the other installs will pick them up as regular composer packages.
Not perfect at all, but the best I can do right now for pro plugins not supporting Composer.

**Comment by slimzc** [comment]
2026 is near! I have hope! 😅

**Comment by nicholaszein** [comment]
Hey Everyone!

We just released the new 3.13-beta1 version for public testing, and one of the new features includes this request!

We would love to have your feedback on this new feature on our dedicated [Announcement](https://github.com/orgs/elementor/discussions/22119).

Please try it out and let us know how it works for you!

Thanks 🙏

**Comment by nicholaszein** [comment]
Hello, everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro **v3.13.0**! 🥳 

You can now install both Elementor and Elementor Pro via WP-CLI. To learn more please check the [documentation](https://developers.elementor.com/docs/cli/), and the [companion blog post](https://developers.elementor.com/elementor-3-13-developers-update/).

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
