### ISSUE TITLE
Feature request: Table of contents widget

### ISSUE THREAD

**Issue by MiMoHo** [elementor/elementor#5171]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
There are a few plugins for WordPress to enable Table of Contents for posts. However, they either lack features, cannot be unsynced from the sidebar or are incompatible with Elementor. Why not create an own Table of Contents widget for Elementor (Pro)? I'm sure this is a feature most bloggers are waiting for to bring an overview and better structure into their long posts.

**Describe the solution you'd like**
A TOC widget that can be used around the entire blog where I can choose hierarchy for bigger vs. smaller headlines, which headline size to include (i.e. only H1, H3), with or without numeration and the typical options for styling and sizing.

**Describe alternatives you've considered**
Currently using the third party plugin "Easy Table of Contents" which can only be used in the post or post + sidebar but not just in the sidebar. I can also just make global settings including the TOC when a certain number of headlines is reached. However, I'd like to decide for every single post if, how and where to use Table of Contents.

**Comment by OCpublishing** [comment]
Yes please. **Table of content**. Did not find any plugin working properly. 
I have found some interesting image wich could bring some ideas related to this in the easy toc plugin https://github.com/shazahm1/Easy-Table-of-Contents/issues/27

**Comment by parfilov** [comment]
+1

**Comment by itolimp** [comment]
I also need this widget. Please add like in Thrive Architect. Simple and useful widget. Very needed in posts, articles. https://imgur.com/a/3A437q1

**Comment by marciotoledo** [comment]
Yes, this widget is really necessary without add-ons.
To build simple tables, price comparison, etc.
+1

**Comment by iMiek** [comment]
I need this widget to create table of content.
+1

**Comment by dbjpanda** [comment]
Did anyone here get a similar plugin ?

**Comment by Ultimanubis** [comment]
Has anyone found a solution or a workaround yet?

**Comment by iMiek** [comment]
I use LuckyWP Table of content in the meanwhile. Works with a shortcode that you can use in Elementor

**Comment by alriksson** [comment]
@iMiek Does not work for me? I tried to place it in the pop ups field of navigation I built. Should work but only displays shortcode on the frontend.

So please show me how it works for you and what shortcode you use and place it in text editor?

**Comment by iMiek** [comment]
@alriksson  You must place a shortcode throug the widget "shortcode" from Elementor, see https://docs.elementor.com/article/72-shortcode
The shortcode for Lucky Wp is [lwptoc]. You must use headers (or H1 - H6) in your text, the table of content is generated automaticly. In LuckyWP Table of content you can specify default settings.

<img width="1483" alt="Schermafbeelding 2019-05-02 om 19 57 11" src="https://user-images.githubusercontent.com/42237516/57097318-bf241880-6d17-11e9-8f0f-d310854b0201.png">

**Comment by alriksson** [comment]
@iMiek Thanks but I've tried this without success. Tried to place both in the single template and my pop up neither works for me.

Thanks, using and following semantic HTML5 with H1-H6

**Comment by elasticeye** [comment]
+1

**Comment by alriksson** [comment]
Any Crocoblock users? If so +1 over here and we might get it into jet/crocoblock: https://github.com/CrocoBlock/suggestions/issues/20

**Comment by dbjpanda** [comment]
Well after trying a lot of plugins like TOC+ and some short code widgets I didn't find any of those are suitable in my case. They are not made purely for Elementor. They are just ported from normal WP plugin to Elementor widget. So I had to create one myself. I also found the existing plugins are using [tocfy](https://github.com/gfranko/jquery.tocify.js/issues/96) jquery plugin which wasn't been updated since 2013. So I used a modern native js plugin for performance increase and created a plugin [KB Elementor](https://github.com/dbjpanda/kb-elementor) . However I have made it open source and seeking for your feedback and contribution. The plugin mainly aims to include widgets those are necessary to create simple wiki like **knowledge based** site. 

Here is the working plugin : https://github.com/dbjpanda/kb-elementor and the [demo](https://www.youtube.com/watch?v=B8SpkyEaAU4)   

[![Demo](https://j.gifs.com/6XmN07.gif)](https://www.youtube.com/watch?v=B8SpkyEaAU4)   

**Note** I am not self promoting my plugin here, You can see my previous comment in this issue, I was really looking for one a long ago, no one did it. So I had to. :)

**Comment by alriksson** [comment]
@dbjpanda Great job! Even including the scroll motion 🌮🌮🌮🌮🌮 for you! Would it be possible to make it align horizontally and then maybe as a carousel mode to fit everything? This since making it align on a line and carousel to fit all headlines. Then we have the possibility to create a sticky bar. Which we then can stick upon scroll, which would be good for mobile users. That don't have to scroll back to the top to see the overview once again. 

Either to options to only enable carousel on tabler and/or mobile or for everything or for none etc.

And what about enable disable the numbers to give more styling control to the user?

**Comment by dbjpanda** [comment]
@alriksson Thanks for your suggestion. For me it is working perfectly.  To grab any headings tag outside of post content you have to provide the class name. That option is in additional settings. 

**Note**: I just released the plugin, so it needs more test case as like yours. So please create issue on the plugin page itself ( https://github.com/dbjpanda/kb-elementor ) instead of mentioning here. 
As now I am working on the project actively so I will surely try to figure out what is your use case and why you are facing the problem.

**Comment by alriksson** [comment]
@dbjpanda Thanks noted addressed in the github issues for the plugin.
