### ISSUE TITLE
[Feature Request] Widget for Woocommerce Cart & Checkout

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#5383]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Add a widget for Cart and Checkout with some level of customisation (colors, fonts, show&hide items).
I suppose it's on the roadmap somewhere (or will be declared as impossible), but I think the subject should be here to discuss.

**Describe the solution you'd like**

**Describe alternatives you've considered**
For now I can use native Woo shortcodes, but I'm unable to design them.

**Additional context**

**Comment by Artneo7** [comment]
When trying to edit with Elementor the WooCommerce checkout page the following error occurs:
“Sorry, the content area was not found in your page.”
![greenshot 2018-10-05 13 02 00](https://user-images.githubusercontent.com/17693529/46546519-a9449700-c89f-11e8-86da-e2e8c79a1534.png)
I'm looking forward to a solution – being able to **edit the page with Elementor** or @black-eye idea to have **widgets for cart and checkout**.

**Comment by muzaffarsiddiqui** [comment]
+1 and we also request to add default checkout page option in elementor "My Templates" with add condition to display and this should enable us to customize our checkout page depending on added conditions.

Many thanks for your consideration and understanding of the issue.

**Comment by WimMar** [comment]
Woocommerce cart and checkout page customization in elementor templates is something I'm eagerly waiting on :)

**Comment by smile00000** [comment]
+1

**Comment by wpnovice** [comment]
Please provide the ability to edit woocommerce **cart, checkout and my-account** pages.  A process similar to single-product and product-archive themes which provided that ability for woocommerce product and archive pages would be ideal.

**Comment by zrk4444** [comment]
+1

**Comment by Skyagent42** [comment]
> Please provide the ability to edit woocommerce **cart, checkout and my-account** pages. A process similar to single-product and product-archive themes which provided that ability for woocommerce product and archive pages would be ideal.

Hi Everyone, thank you for suggesting these nice features update 🙋‍♂️🔦

It would be really unique and continue to push Elementor towards more experienced level developers and continue to increase its reach! 

I mean it already has so many amazing cababilities in terms of styling, etc. 🌟The Elementor team is outstanding in terms of support and creating new features regularly (for which I am grateful everytime 🙏). That's why I feel more and more at ease to propose Elementor Pro to clients with international companies. 

On the other hand, I think Elementor Pro could bring an even better experience for companies who would like to create professional looking online store. Right now it looks a little odd because the whole website is just so beautiful, smooth navigation and UX👌 ...and... then people arrive on the checkout page... and haaargh what is this kind of 90s-like design! 😬 

Please, please, please, could you bring more customization power for online store with Woocommerce? (checkout page, my account, my orders, smart filters with taxonomy, product categories, etc.) 🙏😇

Best thanks for everything you've already achieved!

Sky

**Comment by stlorenz** [comment]
+1

**Comment by pgilfernandez** [comment]
+1

**Comment by kunthawat** [comment]
+1

**Comment by silvercodeau** [comment]
+1

**Comment by cobusvanvuuren** [comment]
+1

**Comment by cobusvanvuuren** [comment]
@shilo-ey @bainternet any chance of getting this feature in the pipeline?

**Comment by IlPizza79** [comment]
+1

**Comment by aaronmyers34** [comment]
+1

**Comment by aaronmyers34** [comment]
Any time frame when more woocommerce customizations may be realeased?

**Comment by shilo-ey** [comment]
This feature has been added to Elementor Pro v3.5.0

Feel free to update

Thanks!
