### ISSUE TITLE
🔗 🔃 🚀 Feature Request: Map widget and Video widget (Merged with #3313 - videos, #1319 - maps) 

### ISSUE THREAD

**Issue by topdog1965** [elementor/elementor#626]
hello

iam using elemetor and i must say iam liking it i know you have the option for full width to prevent scrolling on themap widget but it also disables the plus and minus buttons in the bottom right of the google map. so if visitors want to zoom in for details directions etc they can not.

also on the video widget can you make the option to add a video file like mp4 which can be obtained from free sources like pixabay.

keep up the good work

thanks again i feel this builder if it is going the way it is will be a leader in the front page builder wars

**Comment by joshmarom** [comment]
Hi.
We are glad you find Elementor useful and enjoy using it.

In regards to the Google map question, since we are not using the API for maps (in order to keep it easier for the users, so they don't need an API key), we are preventing all mouse interactions with the map when prevent-scrolling is set.
I do agree it is not ideal, we are looking into some solutions for this situation.

Regarding the self hosted video option, we already have this option as a draft, we will consider including it in future updates.

Thank you for your feedback.

**Comment by drawcard** [comment]
Is there a particular way in which we could hide the zoom in / out buttons, if they are non functional?  Would you recommend using CSS to achieve this?

**Comment by arielk** [comment]
Long time...

But I merged this issue with another issues https://github.com/pojome/elementor/issues/3313 https://github.com/pojome/elementor/issues/1319 so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!
