### ISSUE TITLE
Video backgrounds load when section is hidden

### ISSUE THREAD

**Issue by i2g-lweiss** [elementor/elementor#6718]
We noticed that our site  took a lot longer to load on mobile.  After all the content appear there is still about 6- 20 seconds of loading.  Turns out the site was loading the section's background video on mobile even though it's hidden.

The following code added to my own custom javascript in a child theme fixed it.

if (Modernizr.mq('(max-width:767px)')) {
  jQuery(".elementor-hidden-phone").attr("data-settings",'{"background_background":"classic"}');
  jQuery(".elementor-hidden-tablet").attr("data-settings",'{"background_background":"classic"}');
}

**Comment by Luxamman** [comment]
Yes, we would also want to see that a hidden element, especially videos, is not loaded in the background. We work in the agency also with a lot of videos on desktop/tablet and the mobile version is still loading the video and not only the fallback pic. This is SEO hell^^

Thanks!

**Comment by Alex-Tola** [comment]
Same problem here.

Our company uses a video on the frontpage, which is not shown on mobile.
Now that google decided to care much more about mobile view, our site dropped drastically on google page speed.
Turns out, that the video is taking a ton of CPU resources and also network traffic, although mobile viewers can't even see the video.

After googles decision to change the impotence of mobile devices a new feature for elementor would be really needful.

Thanks

**Comment by lior-sh** [comment]
Hi @i2g-lweiss,

Fixed in version 2.0.13.

Thanks.

**Comment by jorgeiglesiasca** [comment]
my videos today with latest version still loading when hidden on mobile.

**Comment by WarnerV** [comment]
In May 2023 this still seems to be the case:
- On desktop a video is on autoplay
- On mobile it's loaded, even though the video is not visible to the user

Can this please be fixed?
