### ISSUE TITLE
POD's Field Type

### ISSUE THREAD

**Issue by mandarpatil09** [elementor/elementor#7108]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Issue1: I am using POD's and Elementor, I had came across some issue such as some of the field type in POD's are not visible under dynamic section in elementor designer.
I can able to see only few Types such as,

1. Plain Paragraph Text
2. WYSIWYG 
3. Phone
4. Plain Text
5. Website
6. Email
7. Password

I came with an issue when i want to use Shortcode with Dynamic content.

Issue 2:
Can't able to set template based on Custom Tags (Taxonomy)

**Describe the solution you'd like**
Issue 1: Provide a Solution for adding shortcodes dynamically.
Issue 2: Setting template based on Tags is an required feature but priority is less.

**Describe alternatives you've considered**
Issue 1: Creating an Static Pages as currently i am having less content so i can able to do that.
Issue 2: Created an New Author and set template based on Author.

**Comment by shilo-ey** [comment]
Hi @mandarpatil09 

As for your first report: This is not an issue because you are using shortcode, which supports "text" fields. see the [full list here](https://docs.elementor.com/article/385-elementor-integration-with-pods).

As for your second report: we cannot replicate this issue.

Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

Read here about the [conditions system](https://docs.elementor.com/article/311-conditions).
