### ISSUE TITLE
Show pop up after click on URL

### ISSUE THREAD

**Issue by dzejkeyy** [elementor/elementor#7173]
Hi,
is possible to show pop up  windows, after click on some hyperlink or run it from processor at form?

Can't find way to make it... Thanks :+1:

**Comment by shilo-ey** [comment]
You can add a dynamic tag to your link in order to launch a popup.

[Learn more here](https://docs.elementor.com/article/472-popups)(under "Control Popup Via Manual Triggering").

Thanks.

**Comment by parfilov** [comment]
@shilo-ey You're wrong. There is no way to set popup to the Slides widget items buttons because there is no Dynamic feature at this moment.

@dzejkeyy mean that he want to open popup by link, for example: https://mysite.com/#popitup
As it made in Popup Maker.

Manual selector by class or tag is good idea but they are useful not in every situation. Sometimes we should place popup link inside 3rd party plugin's link field and the troubles begins from here.

**Comment by parfilov** [comment]
@shilo-ey I think that this issue/request should be reopened because many of my subscribers asks about it every time.

**Comment by shilo-ey** [comment]
@parfilov This IS available. 
1. The fact that in Slides widget there's no dynamic is not relevant to @dzejkeyy request. He asked about link click or form action. both of them can be done.

2. As for your note regarding link - use "when arriving from" advanced rule.

**Comment by nicholaszein** [comment]
This feature was released with Elementor Pro **v2.5**!
