### ISSUE TITLE
🔗 🚀 Feature Request: Allow for single post template or content to be displayed in a popup from an archive page (Duplicate of #7106)

### ISSUE THREAD

**Issue by SauntValerian** [elementor/elementor#7187]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
A nice user interaction where single posts appear in a popup over an archive instead of navigating the browser to the single post page.

**Describe the solution you'd like**
A nice feature to more fully enhance the popup functionality would be to allow the single template or content to popup when clicked to on an archive page.

This functionality would be similar to what is offered by this plugin: https://wordpress.org/plugins/wp-post-modal/

It may require the ability for Elementor to offer the customization of Loops (which currently requires a third-party plugin to accomplish: https://wordpress.org/plugins/ele-custom-skin/

However, being able to load the single post template or single post content in a popup on the archive page would create a nice user interaction.

**Describe alternatives you've considered**
The only current solution is to use a mix of third party plugins, but the process still fails.

**Comment by shilo-ey** [comment]
Hi @SauntValerian 

This issue is already been discussed in this repo.

See #6713 & #7106.

The answer given there still applies.

Thanks for your feedback.

**Comment by verak1** [comment]
I am looking for this feature, as well. 
And I see that the searches show this question asked in all possible combinations.
I mention it because in your reply to the closed tickets you stated that you will do so if there is demand... So yes, there is. Only very few people actually get HERE to ask.
Thank you.

**Comment by nicholaszein** [comment]
Hello there!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #7106.

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Best regards

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.26.0! 🥳 

You can now use the **Off-Canvas** widget inside your **Loop Item** templates to display additional Dynamic Content for each post in your **Loop Grid** widgets! 🎉 🥳 🙌 

You can learn more about the Off-Canvas widget (and how to use it) here: 
https://elementor.com/help/off-canvas-widget/
And about the Loop Grid here: 
https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
