### ISSUE TITLE
[BUG] WP CLI flush-css comand not working on multisite

### ISSUE THREAD

**Issue by reardestani** [elementor/elementor#7190]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When running `wp elementor flush-css --network` it does not regenerate the sites CSS. It only does so for the primary site as shown in this video: http://take.ms/E9U5M

The expected behavior is deleting all `elementor > css > *` directory contents in all sites not only primary site. 

## Steps to reproduce

- Create a network with some sites
- Do same as above video.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by reardestani** [comment]
Tested the codes in the new commit, it fixes the issue. FYI

**Comment by tristanleboss** [comment]
https://github.com/elementor/elementor/issues/7237

Okay, I had the same issue... I just failled to pinpoint the problem.

Since we use Elementor, our `wp-content/uploads/elementor/css/` folder was in our .gitignore and I used the WP Cli `flush_css` command to remove the CSS files on the production website before uploading the new database. I never imagined flushing the cache was also regenerating the files... I thought Elementor was regenrating them on page load because the files were missing.

The word `flush` is not correctly used. `flushing the toilet` imply removing its content not putting new one; and the definition is the same in software. When you `ipconfig flushdns` in WIndows, you clear the cache, you don't put new entries in it. To me, it doesn't imply an automatic regeneration of the flushed content. This command should be labelled `regenerate_css`.

The danger is that Elementor does no check at all afterwards if a CSS file is present,..

**Comment by tristanleboss** [comment]
@reardestani How do you regenerate the CSS files? You use the `Tools` > `Regenerate CSS` option?

If `flush_css` only removes the files, when are they recreated? bainternet confirmed me Elementor doesn't check for file existence and so doesn't trigger regeneration by itself.

**Comment by reardestani** [comment]
@tristanleboss Right, it doesn't trigger regeneration.

In our case, we need a UI option in network to regenerate Elementor CSS in all network sites. 

At first, we developed a way to recursively delete all elementor folders in upload dirctory and we faced the issue that you mentioned.

Later we changed our way to use similar codes as below to fix the auto regeneration of assets.

https://github.com/elementor/elementor/blob/723041e1847b9622077600af86284afd6b831035/modules/wp-cli/command.php#L36

`Plugin::$instance->files_manager->clear_cache()` function deletes the **assets** and **their options** in database so the assets will be regenerated on the first load.
