### ISSUE TITLE
syntax error #/

### ISSUE THREAD

**Issue by Jaglag** [elementor/elementor#7231]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Description

Hello i Using VikBooking for a Customer Homepage.
when i open up a specific search site theres a js error which is related to Elementor and crashing the site like this:

http://prntscr.com/mqij1t

that reply i got from a other dev:

http://prntscr.com/mqimlz

when disabling elementor everything is fine

## Steps to reproduce

 contact me so i can give you the links for the page

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shilo-ey** [comment]
Hi @Jaglag 

Thanks for your feedback.

Your issue report lacks the steps to reproduce, and therefore we cannot try to resolve this.

In addition, this issue is possible to be caused by encoding that Elementor performs on the 3rd party plugin code.

You can contact this plugin developers and ask them to make this plugin compatible with Elementor.

Thanks.
