### ISSUE TITLE
add "Line" social network to share button widget

### ISSUE THREAD

**Issue by yodpol** [elementor/elementor#7330]
In out country we use "Line" social network as main social network (40 million account )
can you add "Line" to share button widget?

here is the link of code plugin
https://social-plugins.line.me/en/how_to_install

**Comment by trouni** [comment]
+1
also for the Social Icons

**Comment by shilo-ey** [comment]
Hi @yodpol 

Thanks for your feedback,
As mentioned in #2739, we will look into adding this feature as soon as we will integrate FontAwesome5 icon library.

Therefore, I merged this issue with #4430, which is on the same subject so we could deal with it more efficiently.
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by cagewei** [comment]
+1

**Comment by Jrg33** [comment]
Line - Share Button

This task is open since 2017 and there is almost no communication. Line is a very popular software with hundreds of millions of users, especially in Asia. Can you please start to communicate and act like a company that cares about his customers? This is in your own interest because WordPress is growing in Asia. We have 2020 and companies should be able to adapt fast when they wanna grow.

Thank you very much!

**Comment by DODMax** [comment]
+1
Or a filter to add our own buttons

**Comment by fourkosi** [comment]
+1

**Comment by toyza55k** [comment]
+1

**Comment by acornavi** [comment]
Can you please add Line Social Network for the citizens of Japan, Cambodia, Thailand, Hong Kong, Indonesia many people around the world. Thanks
