### ISSUE TITLE
[conflict] Elementor's image widget don't appear in popup because of jetpack

### ISSUE THREAD

**Issue by Knoclar** [elementor/elementor#7362]
Hi elementor !
I'm using jetpack for perfomance and security in my website, but the image that I put in my elementor popup don't load because of jetpack
I've turned off Jetpack and the image load normaly in popup

Regards

**Comment by shilo-ey** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

As for your issue, this is due to the fact that JetPack's uses Lazy Load triggered by scroll to show the images, and the popup never scroll into view.

Try to tell JetPack to exclude the image inside the popup from Lazy Load.

Thanks.

**Comment by offthewallprints** [comment]
Hi, I have been through the few articles that address this issue with images not appearing on elementor popups and i have not been able to fix it. i am having the same problem as everyone else with the same details. i have tried disabling jetpack changing themes reuploading, turning off all lazy loads etc and images just dont appear on elementor popups.

can anyone help with this simple problem that seems to have no fix? see example of what happens on my site: https://offthewallprints.co/product/black-white-tiger/ any of the 2 links in product description should have images where there are just gaps.

thanks
