### ISSUE TITLE
Search Overlay on iPhone

### ISSUE THREAD

**Issue by rmorabia** [elementor/elementor#7368]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When using the Full Screen search on iPhone, the height of the overlay does not adjust to the screen height when the keyboard is up. This means that in order to reach the X button, a user has to scroll up. (I realize you can exit the overlay by tapping anywhere, but this is not very intuitive to our userbase.) The height needs to be responsive with the keyboard up.

![img_4958](https://user-images.githubusercontent.com/3877076/53980788-35711980-40df-11e9-838c-a8177e72e478.PNG)

You can see in the image above, there is no X to close. It is above.

## Steps to reproduce

Add Full Screen search to page.
Open Full Screen search on iPhone X/XR/XS.

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

https://pastebin.com/0DVX2Kdb

System Details here are what I normally use with Elementor. I have tested with the default theme, no plugins, etc.
</details>

**Comment by bainternet** [comment]
@rmorabia 

Thanks for reporting, this is the behavior of IOS when you set your input font size to less than 16px.

Sadly there is nothing we can do about it.

thanks.

**Comment by knowinglydave** [comment]
Hi,

I just made an awesome header with Elementor Pro and only to break out my phone and have it have a bug. The bug explained on this page. It could have been solved by now. But it seems that bainternet is okay with being sad. "sadly". 

Could we please get some css code so that the keyboard does not cover the search input form on iPhones?

There is no reason why the search input field needs to come in the (vertical) middle on the device. Just have the padding-top set so that in comes down about 50px from the top in stead of the middle where a user can not even see the input field. 

Please help.

**Comment by elilar3** [comment]
Hey!

I don't have very much coding-experience, but i found a workaround by adding this code to the searchwidget in elementor: 

```
.elementor-search-form--skin-full_screen .elementor-search-form__container {
    
    height: 125vh; 
    margin-top:-180px;
}
```

**Comment by rafaviana** [comment]
Hi, I also have this issue and the input font-size is greater than 16px… so I think the problem isn't related with that. 
I solved the issue by replacing the height of the container `height: 100vh` with `height: 100%`
This way the input will show up right above the keyboard
