### ISSUE TITLE
Padding Issues

### ISSUE THREAD

**Issue by dottydoo** [elementor/elementor#7383]
All headings now include around 20px of bottom padding.
This is a significant issue for larger sites running the new update as it means manually adding -20 bottom margin to every single heading across the site in order to remove the large gaps.

**Comment by shilo-ey** [comment]
Hi @dottydoo 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

As for your issue - we are aware of this and it should be patched soon. 
This is caused by the implementation of flexbox to the columns. The patch will add flexbox properties only for pages edited/created since 2.5.0

Please follow this thread for updates.
