### ISSUE TITLE
Flex alignment and spacing not working after 2.5.4 update

### ISSUE THREAD

**Issue by StreetDog1971** [elementor/elementor#7404]
After updating to 2.5.4 the flex alignment and spacing are not working as expected.
Inline elements display as blocks, on top of each other.
In a column, if I set the Vertical Align to "Space Between", there's no spacing at all.

It was working fine before the update and I haven't change anything besides updating Elementor.

**Comment by ScottMadore** [comment]
Same issue for me. Please fix ASAP

**Comment by SniffleValve** [comment]
Confirmed. Same here.

**Comment by black-eye** [comment]
Same here.

**Comment by Lorenzoup** [comment]
The update broke my site!!!!! All the inline objects not works!  before the update I had no problems

**Comment by nerdtech** [comment]
I must be the only one where both are working?! Have all plugins been disabled except elementor and elementor pro when testing?

**Comment by Lorenzoup** [comment]
I have not made any changes to the site I have only updated and all the inline elements have moved one below the other.

**Comment by SniffleValve** [comment]
A post from Ben Pines in the Elementor Facebook Group regarding this issue suggested to simply re-save the page.
While this does in fact work, it will be an onerous task to do so on every page on every site on which one has implemented this option.
Therefore, I suggest that this method is a bandaid and that a fix is required :)

**Comment by zeinnicholas** [comment]
> A post from Ben Pines in the Elementor Facebook Group regarding this issue suggested to simply re-save the page.

Yes, I can confirm this worked, and I guess if it was implemented from the beginning no one would be having to deal with this on their new designs... That being said, if this means we'll no longer have people complaining about their site being broken after they update from 2.4.X to 2.5.4 then I guess this is the lesser evil of all this mess...

**Comment by shilo-ey** [comment]
Hi to all!

As @SniffleValve mentioned, this release resolved an issue with Collapsing Margins in Flexbox and prevented a mislocation of widgets.

Last week, we introduced Elementor 2.5.0, which included advanced layout capabilities made possible thanks to the transition to the Flexbox CSS method, incorporated into the columns.

Until v2.5.0, the `display: block` method set the default spacing between all widgets to 20px, and if you had set a different value, let's say 40px, per widget - the larger value was added and displayed.

Most users were not affected by this update. We have just rolled out a new version 2.5.4 which fixes possible 'extra spacing' issues that some users faced.

The main issues happened because of a particular use of 'margin-bottom' that cause the disrupted spacing.

**For users who already used the advanced inline option from v2.5 on pages, and came across these issues, go ahead and edit the page with Elementor, then save it again.**

---------

This behavior was due to the "[Collapsing Margins](https://css-tricks.com/what-you-should-know-about-collapsi…/)". 

Since v2.5.0, Flexbox display method has been embedded in columns and affected the way margins act.

Now, if you will edit an existing page or create a new one, the calculation of the margins will be summed and not relate just to the higher value.

Let's use our previous example:
- Space between widgets: 20px
- Margin-bottom on specific widget: 40px

In this new method, the value of the margins will be summed and will set to be 60px.

This may affect your website, only if you edit existing pages that were created before v2.5.0.
Your newly created pages will use the flexbox rules.

We strongly recommend you to review your website before hitting the Publish button and make sure all of your spacings are correct.

We are keeping a close eye on this issue, and are here to help solve any problem that may rise.
