### ISSUE TITLE
How to use "index.php" instead of "single.php" while creating a new page.

### ISSUE THREAD

**Issue by romares777** [elementor/elementor#7450]
Hello! I know that I can create single template by using Elementor.

But I need to do this by creating the "single.php" file and putting the code there.
But when I trying to create a new page via Elementor - it uses the layout of the "single.php" file, and it looks wrong.

How can I create new Elementor pages so it will use the "index.php" file?
Hope I described the problem clearly, thank you :)

**Comment by shilo-ey** [comment]
Hi @romares777 

Regardless of Elementor, in order to add a page template to the list of templates your WordPress uses, you need to add a page header like this:
```PHP
<?php
/**
* Template Name: Index Page
*/
```

Add this to the begining of your index.php file and you will be able to use it.

Thanks.

**Comment by terremoth** [comment]
Does not matter how many `.php` templates I create within the my-theme folder, elementor seems to always use the `single.php` file instead of another, I didn't find a way to choose other file instead. I am editing someone's else custom theme.

Is this indeed the default behavior for Elementor, or is there a place I can change the file Elementor can edit?

Any of the options I choose: Page, Section, Container - it will always use `single.php` in my scenario
