### ISSUE TITLE
Events Calendar

### ISSUE THREAD

**Issue by get8bit** [elementor/elementor#7480]
When will Elementor add an Events Calendar equivalent?

Events Calendar, which is in no way Elementor friendly, has over 700,000 active installations, so I'm pretty sure there's a need for this feature.

I've yet to see even a third party option that comes close to the styling and flexibility of Events Calendar.

**Comment by shilo-ey** [comment]
Currently, this feature is not in our changelog, but we will look into it in the future if we see a large demand for it.

Consider contacting the developers of that plugin to make it compatible with Elementor.

Thanks for the feedback.

**Comment by get8bit** [comment]
Stop closing these tickets so fast! How do you know there is no demand for it? My clients certainly need it? Have you asked in a survey?

An events calendar would work for campgrounds, bed and breakfasts, bands, magicians entertainers, hair dressers, barbers, authors with book signings, anyone of celebrity, retreat centers (a personal case wherein elementor failed me), surf instructors, ski instructors, any teacher or tutor, financial gurus with seminars, demonstrations of products, cooking classes, YOUTUBERS, literally any form of meetup for ANY interest, school functions, work functions........ the list goes on.

**Comment by senator94** [comment]
A majority of WordPress calendar plugins do not play well with Elementor. I would like to have control of the design elements through Elementor instead of overriding styles through custom CSS. I would not mind paying a premium for Elementor Pro addition of an events calendar that is a standalone plugin or builtin Elementor.

The majority of businesses I deal with have a regular schedule with events throughout the month. Please reconsider adding a calendar function to Elementor Pro.

**Comment by get8bit** [comment]
@senator94 These assholes still haven't attempt to address this glaringly huge issue in their platform.

I haven't tried it yet, but I may have a work around:

1. Get custom post type plugin
2. Create an events page post(as events post type) for each event with ACF (advanced custom fields) allowing you to easily change each date, speaker, location, tag, etc without having to remake each page
3. Create an archive template page for the full calendar with sort by date, tag, location, etc

Here are some helpful videos and links:

https://www.youtube.com/watch?v=ruMtMAVVF_Y
https://www.youtube.com/watch?v=f1tN4em56uA
https://www.collectiveray.com/wp/plugins/elementor-pro-advanced-custom-fields

**Comment by Brink67** [comment]
+1 on the need for an event calendar that is elementor based. I've spent the better part of a few weeks trying just such a thing.

There is the calendar widget in the elementor extras pack by Namogo that accepts dynamic input for events. It does support pulling data from custom posts types. Unfortunately it does not support taxonomies or custom meta fields. I turned in a couple  of feature requests for those. You can get the extras from https://shop.namogo.com/product/elementor-extras/ (premium only) It pulls event dates from the post publication date instead of the event date due to it's lack of support for custom meta fields. Your voice added to the request for taxonomy and custom meta field support would surely help.

There is also a calendar function for jetengine. (https://crocoblock.com/plugins/jetengine/) Tt requires some fidgeting to get it going but does not play well with smaller devices currently. (The calendar shows on a phone but the events are not visible. You can at least so some reasonable style to it though.

Neither is ideal but they are as close as I've seen to an event calendar that works well with Elementor. Both of these rely on custom post types, so neither are a solution to repeating events or events that last for more than 1 day. (You can always create the event 3 times for a 3 day event though.) The jetengine has it's own provisions for creating the custom post types. 

I would be interested in a better solution to the need for an events calendar that plays well with Elementor as well.

**Comment by sommarzan** [comment]
Yes, please re-open this. We are many that need this.

**Comment by marketingfans** [comment]
+1 for adding a event plugin compatible with Elementor.
I've been searching (ánd trying = waisting time) for a good solution for over a month now.
The Events Calendar is good...but incompatible.

I'm now looking at Modern Events Calendar (https://webnus.net/modern-events-calendar/) and it's looking promising.

**Comment by NoNomNomsToday** [comment]
+1 for adding an event plugin compatible with Elementor. Thanks all before me for the tips in the meantime.

**Comment by vnewee** [comment]
+1 for adding an even plugin compatible with Elementor which have the option for multiple events and multiple countries/cities as well.

**Comment by r3xxx4r** [comment]
+1 for adding an even plugin compatible with Elementor which have the option for multiple events and multiple countries/cities as well. Thanks all before me for the tips in the meantime.

**Comment by Raysanders911** [comment]
I know the one that’s compatible with Elementor. Actually surprised no one else had recommended it so far. It’s called modern events calendar.
I used the free version which was enough for my needs and arguably better than EventOn. Though it does have a premium version with a bunch of features that might be more helpful to someone who’s running a business through events and not just announcing them.

**Comment by JessicaParler** [comment]
> A majority of WordPress calendar plugins do not play well with Elementor. I would like to have control of the design elements through Elementor instead of overriding styles through custom CSS. I would not mind paying a premium for Elementor Pro addition of an events calendar that is a standalone plugin or builtin Elementor.
> 
> The majority of businesses I deal with have a regular schedule with events throughout the month. Please reconsider adding a calendar function to Elementor Pro.

Hello my friend,
I recommend you the Modern Events Calendar (MEC). It's awesome. It works perfectly with Elementor and is one of the best calendar plugins Ive ever used. :)

**Comment by JessicaParler** [comment]
> +1 for adding an event plugin compatible with Elementor which have the option for multiple events and multiple countries/cities as well. Thanks all before me for the tips in the meantime.

Dear friend,
I had the same problem as you and after a lot of search, I got to MEC (modern events calendar)
Just try it. It's amazing. I hope I couldve helped.

**Comment by get8bit** [comment]
> Modern Events Calendar

This looks amazing! The pricing is a bit confusing. I don't understand which addons are necessary, but looks great otherwise! Thanks!

**Comment by vgstef** [comment]
Please Elementor team, why do you close this ticket before letting users express their needs for it?

I often need a widget calendar and I see I'm not the only one. 

A good approach would be to the choose the post type for the widget, so we could have a custom post type for Events. 

It would also be awesome to be able to choose between monthly view or chronological listing.

**Comment by get8bit** [comment]
Modern Events Calendar is on sale right now, but only for another day. https://appsumo.com/modern-events-calendar/

**Comment by yeswycan** [comment]
Hello,
Since now news about that, we've created a simple plugin who do the job :)
You can check it here : https://wycan.fr/en/plugin/elementor-calendar-for-acf/
