### ISSUE TITLE
Add a support ticket system to Elementor account admin

### ISSUE THREAD

**Issue by 5patttttes** [elementor/elementor#7537]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Not having a support ticket sytems makes following-up on issues / questions raised cumbersome.

**Describe the solution you'd like**
Access to my tickets from my account admin on Elementor website to be able to see all the tickets I submitted as well as their status and replies from Elementor team and manage the conversation from there (instead of my mailbox).

**Comment by shilo-ey** [comment]
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by bluepresley** [comment]
@shilo-ey 

The OP **was not asking for support**, nor was he asking for links on how to get support, so the response was not helpful at all. 

The OP was asking for a feature request on elementor.com to be able see support tickets submitted through the system.

I have the same issue, which a quick Google search lists this as the top result.

I am an elementor pro member. I understand how to access and get community support and how to submit tickets at elementor.com.  Now, I need to look back through some of those conversations. The problem is there is no way to look at tickets submitted through the support requests, and I don't have access to the conversation in email.

Secondly, there are several requests I have submitted and no one has answered. I need to understand why. Either the customer support rep isn't doing what he's supposed to, or maybe there is a problem with the emails getting to my inbox.

Either way, we need to be able to access support tickets. As an Elementor Pro Expert License holder, I manage several tickets daily. Being able to reference them on elementor.com is important.

If this channel is for the Elementor product / plugin itself, that's fine. But a much more helpful answer would be where can we submit this request so it's considered by the team that manages the elementor.com website.

So where can we submit this request to make sure it goes through the proper channels if this is not it?

Thank you.
