### ISSUE TITLE
Ruler tool

### ISSUE THREAD

**Issue by kikiyop** [elementor/elementor#7540]
I would like to have a ruler tool that is similar to wix's ruler tool in Elementor.

That is simply because I always wonder if certain elements are spaced equally, are the same size etc...

**Comment by shilo-ey** [comment]
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

As for your request, we feel that this should be a 3rd party/browser extension.

Thanks.

**Comment by rossclurman** [comment]
Any update on this feature request? As a user, I'd love to be able to activate a ruler and/or grid system while editing my site in Elementor. Bonus: Guides (to reference screen sizes/break points, etc.).

**Comment by Tigerlilly3** [comment]
Hi, Can this be re-opened as I also agree a ruler tool to ensure elements are aligned would be so helpful. I've looked and there are no third party plugins available that do this.

**Comment by nnikor** [comment]
I second greatly re-opening this. I can't understand why such a common design helptool doesn't already exist in Elementor after all these years. It's so time consuming to be guessing what the spacing and gaps are if you use multiple different values and edit multiple different sites with different layouts because you need to click open every element/container separately to see them.
