### ISSUE TITLE
Improve responsive editing through better UI

### ISSUE THREAD

**Issue by Helmi** [elementor/elementor#7575]
When editing values for mobile breakpoints it's a pain to see what you have edited already. Also it's a similar pain that when switching to a breakpoint other than "desktop" to not see where you have set any values.

Let's say for example you set padding or margin in some area but you're not sure on which element you have done it exactly. When going through mobile after finishing the desktop Design you have no chance but switching back and forth all the time to see where it makes sense to overwrite values. 

It would be great to have:

- Indication of what value has been set on a "higher" breakpoint or at least in the basic desktop version. Maybe a greyed out value shown could help here (just as an example for padding/margin, might need some different UI in other places)
- clear indication in lower hierarchy levels (like desktop) to see which of those values has been overriden higher up.

This would be very helpful to not have to switch around a lot between breakpoints.

**Comment by zeinnicholas** [comment]
I'm not sure what you mean... I'm always on board of improving UI, but I couldn't understand what are you referring to...

Are you trying to indicate that if I, for example, add custom values to a section padding, I should also be able to see what values I added when I'm on tablet mode until I change them manually?

I think I've seen other people asking for this in other threads. 

(I'm not from the support team)

**Comment by Helmi** [comment]
Yes, that's what I was trying to say. Sorry if my post was confusingly worded, I'm not a native english speaker and my english isn't perfect.

**Comment by zeinnicholas** [comment]
Allright, no problem at all. English is not my native language as well.

From what I've seen, there's a couple of issues in this forum that target the same problem, and there's a discussion on how this would add more confusion from the user perspective, since it would mean they could think Elementor is adding something without their input, making them override unnecessary settings. This would also mean a fundamental change in the code base and would also add more load to the overall editor interface (imagine a huge page with every single widget field filled with redundant data), since it would need an active JS parser to fetch the information from one field to another every time. I don't know, I'm just thinking what this would cost, I may be wrong.

**Comment by Helmi** [comment]
Honestly, I have high doubts about the theory of people not understanding the UX.

Here's an example of how Microthemer (a commercial CSS editing plugin for Wordpress) does the same:

<img width="681" alt="Screen_2019-03-27_01-24-34_PM2" src="https://user-images.githubusercontent.com/175346/55075799-28b76400-5094-11e9-86bd-3daf7e11821b.png">

The values are shown with a lighter shade of grey and as soon as you hover the field, the value disappears. I think it's common UX to do it that way. I have seen it on other tools before.

I don't have any clue about how easily this is doable from a dev side but I think the current state is problematic enough to think about a way to solve it.

**Comment by zeinnicholas** [comment]
Agree... It would improve my experience.

**Comment by squadcar** [comment]
One idea on this would just be to show all three breakpoints at the same time, instead of having to switch between them to see the values. As of right now there's two clicks required to get to tablet/mobile, and you can only ever see one at a time.

You could have it so, if another breakpoint has values set, there's an indicator (blue dot).

![elementor-ui-1](https://user-images.githubusercontent.com/263485/55104339-78436300-5087-11e9-9bd4-1e466070bea0.png)

Clicking on the desktop icon would show all the breakpoints, instead of:
1. Click on desktop to show breakpoint icons
2. Click on breakpoint icon to view values for said breakpoint.

![elementor-ui-2](https://user-images.githubusercontent.com/263485/55104349-80030780-5087-11e9-8e07-7752ff0e4e1f.png)

Clicking on the breakpoint icon beside each input would let you navigate through the visual editor devices, but you would always be able to see the values for each and compare/edit.

Not sure how well it would work across the board, just spitballing.

**Comment by Helmi** [comment]
There's another thing on this topic that I forgot initially: When hiding elements for device class, there's no visual indicator that you did so. It's still there in the visual editor after hiding it (which basically is okay) but you can't easily see which elements may be hidden - even if you selected the device clas that hides it. Some indication would be very helpful.

**Comment by black-eye** [comment]
+1

**Comment by MichaelDarko** [comment]
+1

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #3356, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!
