### ISSUE TITLE
Does elementor support WooCommerce mix & match product view?

### ISSUE THREAD

**Issue by manektechmayank** [elementor/elementor#7584]
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

Can you please confirm this please? Does Elementor support this : https://woocommerce.com/products/woocommerce-mix-and-match-products/  ??

I wanted to show single product of mix & match using elementor.
Can I create single template by using elementor pro?
Can you please provide any guide or steps how can I create mix & match single product  using Elementor?

**Comment by TheShaveIceCo** [comment]
Im very interested in this too... Ive been in touch with developers of woocommerse mix and match and they said to contact you guys so that you can add this code to the exceptions:

You will need to ask the Elementor team to also exclude Mix and Match forms from this flex display. They can add :not(.cart_group) to their list of exclusions and they will get better compatibility with Mix and Match, Product Bundles, and Composite Products.

For now, I've added this rule in the additional CSS section of the Customizer:

.woocommerce div.product.elementor form.mnm_form.cart_group {
    display: block !important;
}

Which resolves the issue of the poorly floating reset/error messages.


Hope you can help

**Comment by shilo-ey** [comment]
Hi @manektechmayank 

We are not aware of any issue, if you are aware of an issue, please use our guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.

Without it we simply can't help.

Thanks.
