### ISSUE TITLE
Popup Form - Where is the code located?

### ISSUE THREAD

**Issue by born2fly** [elementor/elementor#7599]
I was sent over by Elementor support to ask the following:

Where does the code to the popup form reside? I am trying to integrate an email address validation plugin with the popup form and it's(the popup) not playing nice. I need to experiment by tweaking the code.

I have tried 3 validator plugins and none have worked with Elementor popup. Supposedly all should be compatible because they all supposedly use the WP email() function.

**Comment by bainternet** [comment]
The code for the popup forms resides in elementor pro /modules/forms/widgets/form.php

but you really shouldn't modify the plugin core files because you will lose these changes once you update. Instead, you should use the [API and Action/Filter](https://developers.elementor.com/forms-api/) hooks provided.

ex: 
```PHP
add_action( 'elementor_pro/forms/validation/email', function( $field, $record, $ajax_handler ) {
	// validate email format
	if ( ! is_email( $field['value'] ) ) {
		$ajax_handler->add_error( $field['id'], 'Invalid Email address, it must be in the format XX@XX.XX' );
		return;
	}

	// Do your validation here.
}, 10, 3 );
```

thanks.
