### ISSUE TITLE
Form doesn't send, reloads page when set as Global Widget

### ISSUE THREAD

**Issue by hybridmuse** [elementor/elementor#7632]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When a form element is set to Global Widget, the form fails to submit (send email) and instead triggers a page reload. Unlinking the Global element makes it work again normally.

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by lauranunez** [comment]
Is there a bug with forms? I have problems with all my forms. Is it for a bug?

**Comment by shilo-ey** [comment]
> Is there a bug with forms? I have problems with all my forms. Is it for a bug?

It seems to be an issue with global widgets only.

**Comment by shilo-ey** [comment]
Hi @hybridmuse 

This issue has been fixed in Elementor Pro v2.5.2

Feel free to update!

**Comment by hybridmuse** [comment]
Thanks, that was fast! ⚡️

**Comment by tomas-eklund** [comment]
Thanks. It was affecting other global widgets as well. A global slider went completely invisible on all pages after updating to 2.5.1, but came back with 2.5.2.

**Comment by gsusI** [comment]
Experinecing it with the latest version, in my case the form is inside a popup:

- Elementor - 2.9.14 | By Elementor.com 
- Elementor Pro - 2.10.3 | By Elementor.com

Form submission triggers reload but it is never submitted.

**Comment by githailey** [comment]
I am having this issue as well

**Comment by CaseyShimata** [comment]
I am having this issue in 3.5.2 I have a form on an Elementor loop template. The loop template is displayed by using an Elementor Posts widget. I place this widget in a template. I load this template on my cart page using a short code widget. 

The issue occurs when I use the following to re-build the template:

\Elementor\Plugin::instance()->frontend->get_builder_content_for_display(get_page_by_path('eshop-cart-coupons-container', OBJECT, 'elementor_library')->ID) 

After AJAX returns and replaces the template with the output ^ clicking the submit button in the form redirects instead of triggering submit.
