### ISSUE TITLE
CSS Documentation for hardcoded elements

### ISSUE THREAD

**Issue by carlosromanxyz** [elementor/elementor#7656]
Hello, I have asked for help via Helpdesk, but they sent me here.

I'm looking for a document where I can see the CSS classes that are used in HTML tags to reuse them in my own hardcoded elements via shortcodes and not have to invoke Bootstrap that only generates conflicts with fonts and styles.

I can currently use FontAwesome because it is loaded by default in Elementor.

For example: Bootstrap offers me documentation like this to understand your grid system https://getbootstrap.com/docs/4.3/layout/grid/

Any ideas?

**Comment by RetourtjeVos** [comment]
1+

**Comment by thimfy** [comment]
Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

**Comment by RetourtjeVos** [comment]
> Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

Sorry, what do you mean exactly? I like and support Elementor 👍

**Comment by thimfy** [comment]
Are getting reply on github or anywhere? just about fontawesome and then you will see what i am talking about.

**Comment by carlosromanxyz** [comment]
> Are getting reply on github or anywhere? just about fontawesome and then you will see what i am talking about.

Hey friend, have a little patience.

Elementor above all other Visual Builders is the best, personally I do not like page builders, I prefer to write lines of code and based on the Wordpress Codex, but Elementor has changed that paradigm.

I think I'm not the only one in the world who thinks the same, therefore, I assume that developers must be quite busy due to the workload that means being the best.

Patience.

**Comment by shilo-ey** [comment]
Thanks, everyone for keeping this discussion relevant.

Currently, this is not a priority for many reasons, but mainly because the whole point of using a page builder like Elementor is to have the ability to break out of girds and each column width is (or at least, can be) dynamic.

We do have plans for a developers partially in this area.

I can refer you to the CSS file responsible for our grid system which is located in `/wp-content/plugins/elementor/assets/css/frontend.css` and search for the `.elementor-grid` classes (keep in mind that there is a particular classes for mobile and tablet - `.elementor-grid-tablet-`, `.elementor-grid-mobile-` )

Hope that it will help you achieve what you are looking for.

Thanks again.
