### ISSUE TITLE
Is there a connection between element render and  _content_template ?

### ISSUE THREAD

**Issue by danyj** [elementor/elementor#7682]
I added custom control to all elements via  these 3 actions

```
add_action( 'elementor/element/section/section_custom_css/after_section_end', array($this,'_action_add_custom_options'), 10, 2  );
add_action( 'elementor/element/column/section_custom_css/after_section_end', array($this,'_action_add_custom_options'), 10, 2 );
add_action( 'elementor/element/common/section_custom_css/after_section_end', array($this,'_action_add_custom_options'), 10, 2 );
```

And I can add my class or data attr to all elements wrappers via 

`add_action( 'elementor/frontend/before_render', array($this,'_action_element_add_attr'), 10, 2);`

	public function _action_element_add_attr( $element ){
		
		$settings = $element->get_settings();
	
		if ( isset( $settings['something'] ) && 'yes' === $settings['something'] ) {
			$element->add_render_attribute( '_wrapper', 'class', 'my-class' );
                    $element->add_render_attribute( '_wrapper', 'data-mydata', 'data' );
		}		
		
	}

But how do we do this in editor  preview?

I tried via `elementorFrontend.hooks.addAction( 'frontend/element_ready/global'` but the scope does not have options and I am not sure if you expect us to filter trough element classes and attributes or is there a simple sync between the element `render` and `_content_template`

All I am trying to do is add/remove data-attr and class while in preview.

**Comment by latheeshvmv** [comment]
Any update on this? +1

**Comment by Paras16699** [comment]
@latheeshvmv https://github.com/elementor/elementor/issues/8436#issuecomment-514959391

**Comment by udidol** [comment]
The title on this issue is not really related to your question.
The Elementor Control Stack's `render()` method is responsible for rendering the front-end markup of Elementor elements. 

The `content_template()` method is used in the editor only (not the front end), and utilizes a Backbone Javascript template for the rendering. It is rendered **in place** of the `render()` method in the editor preview.

A widget that outputs markup needs to implement the `render()` method, but the `content_template()` method is not a necessity.

As per the content of your issue, if I understand correctly, you want to manipulate the output from all of the Elementor elements that use `content_template()`? 

This includes all of Elementor's controls, widgets, elements, everything - so I would advise against it. However, if you still want to do it, there is a filter that is run on the output before it is rendered: `"elementor/{$element_type}/print_template"`, and it passes the `$template_content` as a parameter. Note that there is no global filter. `$element_type` is the value returned from the element's `get_type()` method.
