### ISSUE TITLE
Shortcode in image widget not working

### ISSUE THREAD

**Issue by martine59** [elementor/elementor#7730]
Hello,
We try to put a shortcode on image widget but it is not working.
It is the same issue as described here :
https://stackoverflow.com/questions/55289244/image-widget-dynamic-shortcode-no-output

Please tell us how to fix this

**Comment by mw108** [comment]
Hi,

I'm the author of this StackOverflow question and just wanted to add a few notes.

- Since we are a Pro customer we've been trying to get personal support from the Customer Support twice. But our request was refused twice with the note to open a ticket here.

> Cesar replied
> 
> Mar 23, 19:01
> 
> I'm afraid we can't provide support for custom code. If it works in the text widget you can safely use it there. You can also post this inquiry on our GitHub project page, maybe one of our developers will have some insights into this.

And

> Kai replied
> 	
> Mar 28, 4:11
> 
> I suggest that you also post this to our Github page so you can be answered by our developers who have more expertise on this subject.
> 
> Please let them know that you were referred by the support team.

But since I wasn't sure if this is really a bug or just an operating error, I didn't open an issue here but first on StackOverflow, in the (inofficial) Elementor forum at https://elementorforum.com/threads/image-widget-dynamic-shortcode-not-working.3677/ and in the WordPress support forum at https://wordpress.org/support/topic/image-widget-dynamic-shortcode-no-output/

As none of these threads received any (helpful) reply in almost over two weeks, I was just about to open a ticket here and saw this post.

- We don't want to use the `Text` widget as we would lose all the properties and options the `Image` widget provides.

- We found out that the Shortcode function works in a different Widget, for instance a `Call To Action` Widget. If we set `Title` and `Description` to `Shortcode` and enter our custom shortcodes, it works and the expected output is generated.

- Only with the `Image` widget, there is *NO* output generated at all if we set it to `Shortcode`

Again, I'm not sure if this is a bug in Elementor or if we just do something wrong. So it would be very helpful to get a feedback.

## Prerequisites

- [ x ] The issue still exists against the latest stable version of Elementor.

## Description

- Please see the StackOverflow question.

## Steps to reproduce

- Please see the StackOverflow question.

## Isolating the problem
- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

<details>
<summary>System Info</summary>
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.14.0
	MySQL version: (Ubuntu) v5.7.25
	PHP Version: 7.2.15-0ubuntu0.18.04.2
	PHP Max Input Vars: 3000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1
	Site URL: https://development.foobar.de
	Home URL: https://development.foobar.de
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Permalink Structure: Plain
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP Child
	Version: 1.0
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.6.4
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.11
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.3
		Author: Elementor.com

	Email Customizer for WooCommerce with Drag Drop Builder
		Version: 2.2.8.1
		Author: CidCode

	Foobar - Elementor/Newsletter2go-Integration
		Version: 1.0.0
		Author: Andreas Behr

	Foobar - SEPA.net - WooCommerce Subscription Gateway
		Version: 1.0
		Author: Mario Werner

	Foobar - WooCommerce Admin Orders List Company Column
		Version: 1.0
		Author: Mario Werner

	Foobar Premium
		Version: 1.0.0
		Author: Mario Werner

	German Market
		Version: 3.8.1
		Author: MarketPress

	Ocean Extra
		Version: 1.5.3
		Author: OceanWP

	SVG Support
		Version: 2.3.15
		Author: Benbodhi

	Toolset Forms
		Version: 2.3.3
		Author: OnTheGoSystems

	Toolset Types
		Version: 3.2.7
		Author: OnTheGoSystems

	Toolset Views
		Version: 2.7.5
		Author: OnTheGoSystems

	WooCommerce
		Version: 3.5.7
		Author: Automattic

	WooCommerce Brands
		Version: 1.6.7
		Author: WooCommerce

	WooCommerce Order Status Control
		Version: 1.10.0
		Author: SkyVerge

	WooCommerce Subscriptions
		Version: 2.5.3
		Author: Prospress Inc.


== Log ==

Log: showing 20 of 312019-03-29 00:41:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.9',
  'to' => '2.5.10',
)]
2019-03-29 00:42:00 [info] elementor-pro::elementor_pro_updater Started 
2019-03-29 00:42:00 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start  
2019-03-29 00:42:01 [info] Elementor Pro/Upgrades - _v_2_5_0_form Finished 
2019-03-29 00:42:01 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Start  
2019-03-29 00:42:01 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Finished 
2019-03-29 00:42:01 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Start  
2019-03-29 00:42:01 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Finished 
2019-03-29 00:42:01 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Start  
2019-03-29 00:42:01 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Finished 
2019-03-29 00:42:01 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-03-29 00:42:01 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-03-29 00:42:01 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-03-29 00:42:01 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-03-29 00:42:01 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-03-29 00:42:01 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-03-29 00:42:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.2',
)]
2019-03-29 00:42:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.2',
)]
2019-04-02 15:39:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.10',
  'to' => '2.5.11',
)]
2019-04-02 15:39:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.2',
  'to' => '2.5.3',
)]

PHP: showing 4 of 4PHP: 2019-02-16 10:35:07 [notice X 19][/var/releases/development-20190207-140617-90a68dcdd8cb619bfacd8f3dc3dfa9982f704bfc/wp-content/plugins/elementor-pro/modules/dynamic-tags/toolset/tags/toolset-url.php::67] Undefined variable: value [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-22 11:15:34 [notice X 1][/var/releases/development-20190221-181034-5707dd62db9979ad4405762d6bc3538a04b69183/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::202] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-02-22 14:38:04 [notice X 1][/var/releases/development-20190222-143735-cfbc1c0e0d028a4b67529adda4a7622170ae97f2/wp-content/plugins/elementor-pro/modules/forms/widgets/form.php::1281] Undefined index: button_hover_animation [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-29 00:46:17 [error X 8][/var/releases/development-20190329-004605-cd48a8424e276ffcf7f9fe78146de921f430d391/wp-content/plugins/elementor-pro/includes/modules-manager.php::58] Uncaught Error: Class 'ElementorPro\Modules\MotionFx\Module' not found in /var/releases/development-20190329-004605-cd48a8424e276ffcf7f9fe78146de921f430d391/wp-content/plugins/elementor-pro/includes/modules-manager.php:58
Stack trace:
#0 /var/releases/development-20190329-004605-cd48a8424e276ffcf7f9fe78146de921f430d391/wp-content/plugins/elementor-pro/plugin.php(319): ElementorPro\Manager->__construct()
#1 /var/releases/development-20190329-004605-cd48a8424e276ffcf7f9fe78146de921f430d391/wp-includes/class-wp-hook.php(286): ElementorPro\Plugin->on_elementor_init('')
#2 /var/releases/development-20190329-004605-cd48a8424e276ffcf7f9fe78146de921f430d391/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /var/releases/development-20190329-004605-cd48a8424e276ffcf7f9fe78146de921f430d391/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#4 /var/releases/development-20190329-004605-cd48a8424e276ffcf7f9fe78146de921f430d391/wp-content/plugins/elementor/includes/plugin.php(475): do_action('ele [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2019-03-21 12:08:03 [error X 2][https://development.foobar.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.9:2:6867] this.ui.select is undefined 
JS: 2019-04-03 11:11:03 [error X 6][https://development.foobar.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.11:2:75375] setting getter-only property \"type\" 
JS: 2019-04-03 11:45:23 [error X 6][https://development.foobar.de/wp-content/plugins/elementor/assets/js/frontend-modules.js?ver=2.5.11:584:8] settings is undefined 
JS: 2019-04-03 11:47:14 [error X 2][https://development.foobar.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.11:2:53410] this.ui.sliders.filter(...)[0] is undefined 
JS: 2019-04-03 15:39:34 [error X 3][https://development.foobar.de/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.11:2:218381] elementorFrontend.elements.window.jQuery is not a function 
JS: 2019-04-03 15:39:34 [error X 7][https://development.foobar.de/wp-includes/js/mediaelement/mediaelement-and-player.min.js?ver=4.2.6-78496d1:12:0]  
</details>

**Comment by bainternet** [comment]
@martine59 @mw108 

the Shortcode Dynamic tag cannot be used in any kind of control that expects any data other than text, and Image/gallery controls in elementor expect array which a shortcode can never return. The is simple how shortcodes work.

The only full proof solution I can suggest is to create a custom dynamic instead of the shortcode and use that, ex:

```PHP
// custom image dynamic tag
add_action( 'elementor/dynamic_tags/register_tags', function( $dynamic_tags ) {
	class Custom_Image_Tag extends Elementor\Core\DynamicTags\Data_Tag {

		public function get_name() {
			return 'my-custom-image';
		}

		public function get_categories() {
			return [ 'image' ];
		}

		public function get_group() {
			return [ 'site' ];
		}

		public function get_title() {
			return 'My Custom Image';
		}

		protected function get_value( array $options = [] ) {
			// You need to return an array of this structure but you only need either attachment ID or URL
			return [
				'id' => 123, // attachment id
				'url' => '', // attacment URL
			];
		}
	}
	$dynamic_tags->register_tag( 'Custom_Image_Tag' );
} );
```

for gallery see this: https://github.com/elementor/elementor/issues/7528#issuecomment-474889528

thanks.

**Comment by mw108** [comment]
Thanks for clarifying that issue @bainternet 

Wouldn't it be better to modify the Image control to be able to handle non-array values? For instance something like ...

    if ( !is_array( $value ) )
    {
        if ( is_numeric( $value ) ) // $value contains an attachment ID
        {
            ...
        }
        else // $value contains an URL
        {
            ...
        }
    }
    else
    {
        // Default handling
    }

**Comment by dbjpanda** [comment]
I too agree with @mw108 to support shortcode for image widget. Else it is better to remove that short code option from dynamic option lists. It is confusing and I wasted 2 hrs for the same. Atlast found this issue.

**Comment by madmeur** [comment]
Hi!

> 
> 
> @martine59 @mw108
> 
> the Shortcode Dynamic tag cannot be used in any kind of control that expects any data other than text, and Image/gallery controls in elementor expect array which a shortcode can never return. The is simple how shortcodes work.
> 
> The only full proof solution I can suggest is to create a custom dynamic instead of the shortcode and use that, ex:
> 
> ```
> // custom image dynamic tag
> add_action( 'elementor/dynamic_tags/register_tags', function( $dynamic_tags ) {
> 	class Custom_Image_Tag extends Elementor\Core\DynamicTags\Data_Tag {
> 
> 		public function get_name() {
> 			return 'my-custom-image';
> 		}
> 
> 		public function get_categories() {
> 			return [ 'image' ];
> 		}
> 
> 		public function get_group() {
> 			return [ 'site' ];
> 		}
> 
> 		public function get_title() {
> 			return 'My Custom Image';
> 		}
> 
> 		protected function get_value( array $options = [] ) {
> 			// You need to return an array of this structure but you only need either attachment ID or URL
> 			return [
> 				'id' => 123, // attachment id
> 				'url' => '', // attacment URL
> 			];
> 		}
> 	}
> 	$dynamic_tags->register_tag( 'Custom_Image_Tag' );
> } );
> ```
> 
> for gallery see this: [#7528 (comment)](https://github.com/elementor/elementor/issues/7528#issuecomment-474889528)
> 
> thanks.

Can you sample this kind of array, that used in the dynamic image field, maybe it will work if i create that kind of array in artificial way?

**Comment by DLX23** [comment]
its 2022 any solution for this?

**Comment by Stevemoretz** [comment]
You may want to checkout https://github.com/elementor/elementor/issues/7528#issuecomment-1222671749, I made it work with a custom image tag which accepts a shortcode.

**Comment by YossiDavid** [comment]
Thank you @bainternet 
I configured your code to actually get both parameters - ID and URL by padding them into a controller field:
`// custom image dynamic tag
add_action( 'elementor/dynamic_tags/register_tags', function( $dynamic_tags ) {
	class Shortcodes_Image_tag extends Elementor\Core\DynamicTags\Data_Tag {

		public function get_name() {
			return 'image_shortcodes';
		}

		public function get_categories() {
			return [ 'image' ];
		}

		public function get_group() {
			return [ 'site' ];
		}

		public function get_title() {
			return 'Images Shortcodes';
		}

		protected function get_value( array $options = [] ) {
			// You need to return an array of this structure but you only need either attachment ID or URL
			return [
				'id' => $this->get_settings( 'image_id' ), // attachment id
				'url' => $this->get_settings( 'image_url' ), // attacment URL
			];
		}

		protected function _register_controls() {
			$this->add_control(
				'image_id',
				[
					'label' => __( 'ID', 'elementor-pro' ),
					'type' => Elementor\Controls_Manager::TEXT,
				]
			);
			$this->add_control(
				'image_url',
				[
					'label' => __( 'URL', 'elementor-pro' ),
					'type' => Elementor\Controls_Manager::TEXT,
				]
			);
		}


	}
	$dynamic_tags->register_tag( 'Shortcodes_Image_tag' );
} );` 

Now you can add shortcodes into the fields.

![image](https://user-images.githubusercontent.com/40799241/236672529-ec3a7e68-1265-4b5a-bd66-11435266a12e.png)
