### ISSUE TITLE
Add a text field in elementor form widget elements

### ISSUE THREAD

**Issue by MAthez** [elementor/elementor#7753]
- [x I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
One often need to add a decription or tip in form elements. 
For example, for a select, I'd likke to say "multiple select possible with Ctrl or ⌘"

**Describe the solution you'd like**
I'd like to have a field for such tips inside each form widget element

**Describe alternatives you've considered**
I am using HTML element to add a text below, but then it also gets into the email sent, which ois ugly.

**Comment by tristanleboss** [comment]
Great idea

**Comment by bainternet** [comment]
@MAthez 

This is what the HTML field is for, are you sure you get it in your EMAIL? because our forms don't send HTML fields as far as I know.

**Comment by gwmbox** [comment]
I realise that the HTML is an option, but why does it have to be HTML, why not just a content area?  A simple add item of paragraph text would be the simplest way to go.  It also enables formatting the text instead of having to do that in the hTML.  Elementor is made to not require HTML (as much as possible) so this is really a fair request.

So yes a +1 for this

**Comment by bainternet** [comment]
closing as HTML field type already allows dynamic shortcodes and any arbitrary HTML, which in Elementor Pro v2.7.0 will also get simple typography styling controls.

thanks for the suggestions.
