### ISSUE TITLE
Post widget term category AND / OR label

### ISSUE THREAD

**Issue by OCpublishing** [elementor/elementor#7787]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Hi there
Since some of the last updates on the pro version I have some really annoying problem when using post widget
<b>Before, when I used 'TERMS', I could choose a category and inside this category a specific tag.
Now if I chose a category and a tag I got both</b>

For example lets say I have 2 categories :
<i>Buying guides</i> and <i>Reviews</i>
And labels like :
<i>Juicer, headphones, Wireless mouse</i>

Before I could use query to select <i>Reviews</i> (category) about <i>Juicer</i> (tag) and I only got Juicer reviews

Now if I do do a term query with <i>reviews</i> (category) and <i>juicer</i> (tag) I got ALL articles with juicer tag (including buying guide) and ALL articles with Review category.

It looks like it changed to an option_a <b>AND</b> option_b and that it is now a option_a <b>OR</b> option_b
Is this a bug? If this is how you want to handle it can you insert a AND / OR selector?

Please do something fast about it. I have to change manually ALL the 'related posts' by hand where I used them.

Is this problem linked to 
https://github.com/elementor/elementor/issues/7653
?

Thank you

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.7.25
	PHP Version: 7.1.27
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://anonymous.com
	Home URL: https://anonymous.com
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress Child
	Version: 0.1
	Author: Tom Usborne
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 2.2.2
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
<details>
<summary>

Elementor
		Version: 2.5.11
		Author: Elementor.com
	
Elementor Pro
		Version: 2.5.4
		Author: Elementor.com
</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by redfox22222** [comment]
I am having the same issue. It was introduced with Version 2.5.3 - 2019-03-31 when trying to resolve this bug
Fix: Changed query method from term_id to term_taxonomy_id (#7653)

**Comment by redfox22222** [comment]
I am having the same issue. It was introduced with Version 2.5.3 - 2019-03-31 when trying to resolve this bug
Fix: Changed query method from term_id to term_taxonomy_id (#7653)

**Comment by OCpublishing** [comment]
Any update on this issue? Or Fix ETA? Hard to know whats going on since the elementor pro changelog has not been updated with the last update
Thanks

**Comment by evandonovan** [comment]
I believe that the entire new interface of the Advanced Query Control is a *regression* due to bugs like https://github.com/elementor/elementor/issues/7653 and this one.

We have a large number of custom taxonomies on our site, and we use Elementor Pro 2.4.x and cannot upgrade currently because it is too confusing to select the proper terms now. 

I spent over 4 hours debugging this issue today, and only now found this ticket.

I understand that "Advanced Query Control" (https://elementor.com/blog/introducing-advanced-query-control/, https://docs.elementor.com/article/101-posts) may be useful in some instances, but it should be an option - not the default, I believe.

**Comment by evandonovan** [comment]
I just realized that technically my comment is slightly different than the above, since I am referring to how the old interface showed each taxonomy as a separate control, whereas the bug above is about how the select queries work.

However, it is related insofar as it shows the limitations of the new interface. It is not an adequate query builder, in my view.

Let me know if you would like me to post mine as a separate ticket.

**Comment by lior-sh** [comment]
Hi @evandonovan,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
* One issue per thread
Without it, we simply can't help.
Thanks.
