### ISSUE TITLE
Plugin Update Needed to Correct URL requests (Elementor)

### ISSUE THREAD

**Issue by prodancer2015** [elementor/elementor#7788]
This plugin is inserting outdated URL’s into the page, for example, this one;

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 283.5 19.6" preserveAspectRatio="none">`

w3 website now uses HTTPS and the developers of Elementor need to update ALL their coding that uses outdated HTTP protocols to use HTTPS. 

This would also correct issues regarding HTTPS protocol websites that have HTTP URL calls in their website source coding. 

If the URL call goes to a website that still uses HTTP, then I suggest to find a replacement source.

**Comment by shilo-ey** [comment]
Hi @prodancer2015 

`SVG xmlns` value is used as namespace string and not a URL.
See [more here](https://stackoverflow.com/questions/39960017/does-svg-xmlns-attribute-value-requires-protocol-can-it-be-https-or-relative)

If we will change this it will cause issues in the editor.

Thanks!

**Comment by pandjarov** [comment]
This causes tons of problems when you're forcing HTTPS for resources. 

The way you have constructed this makes impossible to use https_rewrite_links without breaking the plugin. Please, look into it, we're using this on our Force HTTPS tool used by thounsands of Elementor users and it's causing a lot of support tickets and issues.

**Comment by kappaluppa** [comment]
@pingram3541 is right, this needs to be fixed in Elementor code:

It's not a W3 website issue. Elementor is using hard coded http://www.w3.org/2000/svg when it should use https and is generating a not secure message.

I came across this by editing a section and applying a border. The border is generated via SVG. It is using http://www.w3.org/2000/svg, it should be using https://www.w3.org/2000/svg
Find the code that needs to be corrected here:
/elementor/assets/shapes
Example:
<svg xmlns=”http://www.w3.org/2000/svg&#8221; viewBox=”0 0 1000 100″ preserveAspectRatio=”none”>
<path class=”elementor-shape-fill” d=”M0,6V0h1000v100L0,6z”/>
</svg>

**Comment by pingram3541** [comment]
@kappaluppa I think you may have misread my last response on this.  It supports the disposition of this ticket being closed due to nothing needing to be fixed.

The short of my long explanation above is, this specification is a "name" and not a "url" even though it appears as a url declaration.  The browser does not see this as a url nor treats as such.

The key here being the attribute is `xmlns=` and not atts expecting actual urls like `src=`, `href=`,etc.
