### ISSUE TITLE
Image Carousel Create Video Playlist

### ISSUE THREAD

**Issue by sinchocode** [elementor/elementor#7803]
Hi there,

I use elementor pro and I want to create a video playlist in the image carousel element. So in the content section I select Add Images -> "Create Video Playlist" then choose my file and upload it. 

Then either wp or elementor doesn't recognize my file because the thumbnail is not video's image. This shows that there is a problem. After selecting the video that I uploaded, I press on the create a new video playlist on the buttom and then insert it. In the content section video doesn't show up and in the site it doesnt show either.

I can upload gif files and they can work however since gif are bigger than mp4 files I want to use mp4 files in the video playlist. Can you please suggest a solution or fix the bug.

[https://yadi.sk/i/XQF2Vl1Ql1BE3A](https://yadi.sk/i/XQF2Vl1Ql1BE3A)
[https://yadi.sk/i/puWd0QA34Kaf1g](https://yadi.sk/i/puWd0QA34Kaf1g)
[https://yadi.sk/i/sG_lZfr76aMnlg](https://yadi.sk/i/sG_lZfr76aMnlg)
[https://yadi.sk/i/sQNP6dPYOfDxzA](https://yadi.sk/i/sQNP6dPYOfDxzA)

Best Regards

**Comment by bainternet** [comment]
@sinchocode 

Our Image Carousel widget is for images and not videos. I see no bug here so there is nothing to fix.

as for a solution, try using a 3rd party plugin that supports a video playlist.

**Comment by sinchocode** [comment]
Hi there, thanks for your answer. Since there is the option of a videoplaylist in the carousel I wanted to use it... anyway thanks

**Comment by wsbcollective** [comment]
hello, i have the same issue. I have both elementor pro and ultimate addons but still can't find a way to put mp4 files in something like a carousel. Also since i'm already here, if i use the video section i can upload the video and it works nicely, the only problem is that i can't put any url link with the video. I use self hosted videos and i like to make it so that one after clicking it is redirected to the original page.
