### ISSUE TITLE
Form sent to address selected in a select field

### ISSUE THREAD

**Issue by fedeoasis** [elementor/elementor#7837]
I have a single contact form, the first field (it's a select field) is placed to let users choose the type of the contact: technical, commercial, administrative, info.

Every contact type have a related email address:
technical -> technical@domain.com
commercial -> commercial@domain.com
administrative -> administrative@domain.com
info -> info@domain.com

Now I need to send the form to the address related to the contact type choosed by the user.

How can I do this?
There isn't an option in the form widget setting, right?
Form widget let to enter only a predetermined email address as "to" address.

Thanks!

**Comment by bainternet** [comment]
@fedeoasis 

Yes you can do that,
create a form widget >> add a select field >> use the pipe (‘|’) to differentiate between label and value. 

If you use a pipe (‘|’) character in an option value, the part before the pipe will be used as the label, and the part after the pipe will be the actual value. 

so your options should look something like this:
```
technical|technical@domain.com
commercial|commercial@domain.com
administrative|administrative@domain.com
info|info@domain.com
```

and in the form Email To setting, set the field's shortcode instead of an address which will be dynamically set once the user selects an option.
