### ISSUE TITLE
Toggle Text Color Bug

### ISSUE THREAD

**Issue by zdesigner1** [elementor/elementor#7915]
- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

The toggle title is stuck with this style and I am unable to change or update the color using the style menu, it requires CSS to update.

I have attached an image of the bug below. 

<img width="1440" alt="Screen Shot 2019-04-19 at 9 54 00 AM" src="https://user-images.githubusercontent.com/49654917/56434438-71c09980-6289-11e9-90e1-bcdf15b30a24.png">

**Comment by shilo-ey** [comment]
Hi @zdesigner1 

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Steps to replicate.
* Isolating the problem.
* System info.

Without it we simply can't help.

as for your issue, if I understand correctly this is probably caused by your theme's CSS attributes.

Please try to add this to your CSS file / custom CSS tab :
```CSS
.elementor-widget-toggle .elementor-toggle .elementor-tab-content {
   background: #fff /* (or any other color) */
}
```

Thanks

**Comment by ss198939** [comment]
Just to inform you

this is not theme issue. this is Elementor issue

I also faced this issue and i changed 4 themes to check if this is elementor issue or Theme issue

and same issue was with all themes

So you can understand. 

and after 5 days it got rectified automatically 

as i forgot to escalate this due to my busy schedule

**Comment by misterrobato** [comment]
The code
```
.elementor-widget-toggle .elementor-toggle .elementor-tab-content {
   background: #fff /* (or any other color) */
}
```
doesn't work.
