### ISSUE TITLE
Disable Nav Menu Dropdown/Toggle for Mobile/Tablet 

### ISSUE THREAD

**Issue by mbrinson** [elementor/elementor#7916]
I couldn't find any way to request re-opening a closed issue, so I'm re-creating here. A developer posted a custom css solution, but the entire point of Elementor is to reduce coding time and make things simple.

Including a toggle or checkbox option to "Disable Mobile Hamburger Collapsing" or something like that is much preferred over a custom coding solution.

-------------

Currently the navigation automatically toggles in mobile or tablet. There is no option to disable this.
While this is awesomely responsive and helpful, I have some instances where I want my navigation to look like how it is on desktop.

Setting the 'Toggle Button' to 'None' only hides the Hamburger Icon and the nav is still essentially in a different styling on top of the page.

For now, if someone can send me some css codes to disable this, that would be awesome.

Thanks

**Comment by MaxZiebell** [comment]
Yes. I run into this often when using the menu in the footer area and that is very common. So please add this basic feature.

**Comment by black-eye** [comment]
+1

**Comment by soulfulwater** [comment]
+1

**Comment by KingGrizzly** [comment]
+1 I encounter this on every build. Sometimes navs just don't need to collapse at smaller screen sizes. 

The second request here would be the option to hide the flyouts/dropdowns on smaller screens. Keep the top level items in non-hamburger mode, but disable the flyouts/dropdowns on small screens.

Thanks!

**Comment by simonclay** [comment]
Same for me, every build. + 1

**Comment by drewclifton** [comment]
I agree 1000% that on the majority of small sites a vertical menu is required, and a hamburger does not fit at all (eg - how many times have you seen a hamburger menu in a footer? Yeah, pretty much never). This leaves us with a real design/UX problem.

I need to stop the menu from turning into a hamburger immediately. **Can someone please share a CSS workaround to suppress this, for now?**

Thank you so much! 😄

**Comment by therarecommoner** [comment]
I rolled my own css but it relies on the unique ID of each menu-1-ID and menu-2-ID and mucho !importants... I too would want to see this as a feature. In the meantime, I'd love if you could point me to the css solution provided as mentioned @mbrinson

**Comment by scott8035** [comment]
@therarecommoner : Issue https://github.com/elementor/elementor/issues/3064 has the CSS you need.

**Comment by MichaelDarko** [comment]
+1 Please, give us an amazing Nav Menu Widget. It's long overdue. The current one is extremely limiting.

**Comment by MaxZiebell** [comment]
Or at least fix the basic one you have. 
The amazing one can be a new one to not break backwards compatibility

**Comment by houseshawbash** [comment]
Thanks for merging my thread with this @shilo-ey , I would have to ask though if the fix would also apply to other widgets that turns into a list after reaching the mobile break point? I understand that the 2.60 release will fix the nav menu, however, how about how about the Post widget that I mentioned on my thread? 

Right now, instead of using the Post widget of Elementor, I am using the Recent Post widget of Wordpress. 
Then I added this code 
`.recent-post li {
  display: inline-block;
	margin-right:5px;
	margin-left:10px;
}

.recent-post {
  white-space:nowrap;
  overflow-x:scroll;
  -webkit-overflow-scrolling: touch; 
  -ms-overflow-style: -ms-autohiding-scrollbar;
  -webkit-scrollbar-display: hidden;

}`

That prevents it from turning into a list after reaching the mobile breakpoint. In which this code doesn't work with the Post widget of Elementor so that it would give this scrollable list
![Screenshot 2019-06-13 at 07 35 12](https://user-images.githubusercontent.com/51769418/59409329-ec9bc180-8dad-11e9-8760-909b47cf024f.png)

It would be much better if we'll have this function on Elementor so we can query and filter the post we can display there.

Thank you

**Comment by hackernewbie** [comment]
That one feature I pretty much need to do a CSS workaround for the footer menu of every website I do!

Surprised to see the issue hasn't been taken care of still!

Hope there's an easy way to 

> enable/disable

 this soon, in one of the next updates!

**Comment by houseshawbash** [comment]
@shilo-ey 

Thank you for merging my thread here, I do have a question as my thread is with regard to several features. Because this same thing happens with your Post Widget on mobile view. I have attached [here](https://www.dropbox.com/s/frptkg2zea2ewfx/HS%20Blog%20home.mov?dl=0) what our current homepage looks like using the Recent Post widget of WordPress instead of the Post Widget. Basically just title of posts and on a scrollable in-line block -- which Post Widget can't do no matter how much CSS I add. I hope this can be fixed too because Post Widget allows me to filter the post to be displayed on our 'Trending' part of our header. This is the CSS I used that doesn't work on Elementor Post Widget -- I renamed the class ID to recent-post

`.recent-post li {
  display: inline-block;
	margin-right:5px;
	margin-left:10px;
}

.recent-post {
  white-space:nowrap;
  overflow-x:scroll;
	text-transform:uppercase;
	text-decoration-color: red;
	  border-style:solid;
	border-width:2px;
		border-color:#353839;
    border-right-style: hidden;
    border-left-style: hidden;
	border-top-style:hidden;
	-webkit-overflow-scrolling: touch !important;

}
.recent-post::-webkit-scrollbar {
display: none !important;
}

h5 {
	color: #D92121;
font-size: 20px;
margin-bottom: -5px}

.recent-post a:link {color: #919191;
}
.recent-post a:hover {color: #000000;
}
	.recent-post a:visited {color: #C32148;
}

h5::after {
	content: url(https://blog.houseshaw.co.uk/wp-content/uploads/sites/2/2019/06/trending-2.gif);
}
`

**Comment by houseshawbash** [comment]
> That one feature I pretty much need to do a CSS workaround for the footer menu of every website I do!
> 
> Surprised to see the issue hasn't been taken care of still!
> 
> Hope there's an easy way to
> 
> > enable/disable
> 
> this soon, in one of the next updates!

You can try and use the native widget nav menu of WordPress , instead of the Elementor nav menu widget, and used the code above and just adjust the selectors to make sure it targets the right class ID you would want to target.

**Comment by hackernewbie** [comment]
Thanks @houseshawbash , I do have my CSS _hack_ that I have been using for a while. 

What I was hoping for was a straight-forward solution to this problem.

Thanks for your time anyways :)

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.6.0

Feel free to update

Thanks!
