### ISSUE TITLE
added space under text Widget

### ISSUE THREAD

**Issue by zdesigner1** [elementor/elementor#7958]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When using a text editor widget and I edit under the "Visual" tab, I receive a small space at the bottom of the text. I attached a screen shot with the CSS that is producing it. If I click the "Text" tab and start typing, the space goes away. 

## Steps to reproduce

1. Add a text widget.
2. edit under the Visual tab. (Do you see the space?)
3. Edit under the Text tab. (Did the space go away?)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
Company does not allow me to share. (I removed all plugins but kept Elementor & used Wordpress 2017 Theme)
<details>

**Comment by shilo-ey** [comment]
Hi @zdesigner1 

Thanks for your feedback.

The space is added due to a CSS property which origins from your theme's style.css file after each `<p>` tag.

When you edit it with the text tab, you are deleting the `<p>` tags and therefore the spaces are disappearing.

Try removing that line from your CSS file or adding a stronger one for the use of Elementor:
```CSS
.elementor p {
    margin-bottom: 0;
}
```

Thanks

**Comment by zdesigner1** [comment]
Thanks for the support. I solved it

**Comment by batyanko** [comment]
Does this mean it can only be solved with Elementor Pro?
