### ISSUE TITLE
Plugin Output Styling

### ISSUE THREAD

**Issue by zrk4444** [elementor/elementor#7980]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It'll allow people to style plugins with gross output styles from shortcodes.

**Describe the solution you'd like**
Let me style shortcode outputs from plugins via Elementor.

**Comment by bainternet** [comment]
@zrk4444 

What you are asking for is not really possible unless the 3rd party itself creates an Elementor widget.

To style the output we need to control and know the markup which we don't since each plugin/shortcode has its out output markup and there is no real standard we can work with.

thanks.
