### ISSUE TITLE
[BUG] custom acf-fields for url and image still cannot be reached!

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#7999]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and can find at least one closed (!) duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

the dynamic options for contend doesnt find any custom acf-fields for 'url' or 'image'!!
no matter how you try, they wont show up in the dropdown to select.

this seems to be a very old bug - there are issues about it in this repo which are closed and therein remarks to open a new issue if this still persists. and it does!
PLEASE FIX!!!

## Steps to reproduce

e.g. create a headline, text or listing-field with dynamic content and try to fetch a custom acf-field for image or url - you wont find both of it in the dropdown!

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

three different installations. suppose to find the same result on others ...

**Comment by jmkucerak** [comment]
Have you modified the Preview Settings and selected a Post/Page that contains one of the said fields.  In my experience, getting data from dynamic tags has at least 2 processes; depending on whether you are editing a Post or a Template.

Editing Post:
- Create ACF Field Group and make sure it is actually going to be attached to a Post/Page/CPT...etc. via the Location rules.
- Edit at least one of the Post/Page/CPT/etc. and put some data into the ACF Field(s).  Save.
- Edit the Post/Page/CPT/etc. with Elementor.
- You should now be able to see the different ACF fields available form the dynamic tags.

Editing Template:
- Create ACF Field Group and make sure it is actually going to be attached to a Post/Page/CPT...etc. via the Location rules.
- Edit at least one of the Post/Page/CPT/etc. and put some data into the ACF Field(s).
- Create an Elementor Template.
- Modify the Preview Settings so that a Post/Page/CPT/etc. is chosen that will have the ACF Field(s) and preferably has data in said fields.  Click Apply & Preview
- Save the template and hard refresh the page.  Alternatively you can exit back to the WP admin area and then edit the template with Elementor again.
- You should now be able to see the different ACF fields available form the dynamic tags.

**Comment by dasigna** [comment]
thanks @jmkucerak but all this you mentioned is crystal clear and well prepared :)

images:
i dont know why, but started again from scratch and now i am able to choose a custom acf image field in image widget. before that was no longer the case. as sonn as one had coosen a 'normal' image e.g. a a placeholder the dynamic option didnt show up any longer ...
so seems to be solved for now, but i fear i have to observe this in future because from time to time its also the case that dynamic content doesnt refresh upon changes an leavesbehind blank fields... on different kind of servers - even the best ones. curious.

url-field:
maybe wron thought on my side, but - when showing a acf-mail-field e.g. in list widget i am able to choose the acf-mail in the 'text' section to show the mail-adress in plain text and choose the same field in the 'link' option to show it with the corresponding link.
if i want to do the same with the acf-url-field this is not possible. i can choose the url as a link, but i am not able to choose the url-field in the 'text' option to show up as plain text as can be done with the mail ... very confusing!

**so the question that is left behind is basically - why cant the acf-url be chosen in the 'text'-option??**
just an oversight from elementor, godd reason behind it or just some fault on my side??

any answer highly appreciated.

**Comment by jmkucerak** [comment]
So, I am not sure if there is a 'good reason', but I can tell you that the code only allows the acf-url tag to be used on controls within the \ElementorPro\Modules\DynamicTags\ACF\Module::URL_CATEGORY

I suppose the straight forward fix would be to update that code to include \ElementorPro\Modules\DynamicTags\ACF\Module::URL_TEXT as well.

**Comment by shilo-ey** [comment]
Hi @dasigna 

This is not an issue, and works exactly as designed.

Text fields can only be used by:
‘text’, 
‘textarea’, 
'number’, 
‘email’, 
‘password’, 
‘wysiwyg’, 
‘select’, 
‘checkbox’, 
‘radio’, 
‘true_false’,

Pro
‘oembed’, 
‘google_map’, 
‘date_picker’, 
‘time_picker’, 
‘color_picker’
'date'
'date_time_picker'

And URL fields only by:
‘email’, 
‘image’, 
‘text, 
‘file’, 
‘page_link’, 
‘post_object’, 
‘relationship’, 
‘taxonomy’, 
‘Url’


Read more here: https://docs.elementor.com/article/381-elementor-integration-with-acf

You can extract this code using dynamic > shortcode > and paste the fields shortcode or use a different type of field.

Thanks
