### ISSUE TITLE
Navigator bulk operations

### ISSUE THREAD

**Issue by godschisel** [elementor/elementor#8006]
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )
As far as I know, yes.

**What problem is your feature request going to solve? Please describe.**
I just created long list of widgets in section. There is no quick action in Navigator how to delete them all at once. Or at least select them. Now I can select only one element and delete that...
**Describe the solution you'd like**
ctrl/Shift + click action to select multiple widgets, columns or sections at once. 
Then ability to perform certain tasks upon this selection - delete them, update style, move, etc...

**Describe alternatives you've considered**
Just clicking and performing actions one at a time.
**Additional context**

**Comment by moseskerub** [comment]
This is very much needed
I always prefer to work in an atom system - hence I'll try to use the basic widgets in combinations instead of pre-made ones.

for example, I'd use a headline, text and button widget instead of a CTA widget.

The drawbacks are:
1. i can't duplicate parts fast enough. I can duplicate the entire column or section to another one, but what if I want to duplicate these three to the same column?

2. I'm missing some functionality of the pre-made widget. like linking the whole box , and hover states.

I think adding more granular control like that would omit almost entirely the need to create more complicated widgets, and allow us web creators to use Elementor with much more versatility and much more easily.

**Comment by mayowaolu** [comment]
Yes, this will be a good feature. Group widget duplicating and deleting.

**Comment by DorShahar** [comment]
This feature has been added to Elementor Core v3.5.0

Feel free to update

Thanks!

**Comment by Yadley** [comment]
Thank you so much @DorShahar
