### ISSUE TITLE
Potential conflict with Cookiebot plugin

### ISSUE THREAD

**Issue by kovac031** [elementor/elementor#8056]
Hello! I was directed here by the Elementor support team.

I am attempting to implement prior cookie consent to my website because of EU law. I have discovered [this](https://wordpress.org/plugins/cookiebot/) plugin called Cookiebot that gets the job done. 

However, for some reason the plugin manages to block all cookies (before a visitor gives consent) on all pages EXCEPT any of my blog posts. My website is entirely built using Elementor pro, and I even use Elementor's blank Hello theme. 

My website is www.odnule.com, please take a look.

Blog post design has been done by creating a template using Elementor, and the videos that are NOT responding to the Cookiebot plugin on those blog posts are placed with the Elementor video widget, source set to dynamic -> custom field -> featured_video ... so each time I make a new post, below the wordpress editing section there is a field where I simply paste the video URL.

I have already checked if switching to a fixed URL will solve the issue - it does not. 

I have contacted Cookiebot support and they have provided me with [this solution](https://support.cookiebot.com/hc/en-us/articles/360003790854-Iframe-cookie-consent-with-YouTube-example), but I do not know how to implement it (or if it is even possible because of using Elementor) and they haven't responded to my explanation request still, while Elementor support directed me to ask for help here. 

I am hoping you will be able to help me - if not with specifically this issue, then potentially with another solution for implementing prior cookie consent on a Elementor-built website.

Thank you!

**Comment by shilo-ey** [comment]
Hi @kovac031 
Our video widget parses the YouTube video URL and inserts it into the iframe tag.

The cookie consent plugin needs to make changes in the way they are handling with YT videos.

Currently, you have two options:
1. Use this filter: 
`apply_filters( 'oembed_result', $iframe_html, $video_url, $frame_attributes )`
in order to grab every iframe created by Elementor, check if it's youtube address and modify the structure of the iframe to your needs.
2. Get the Embed code from YT, modify it to your needs and insert it via HTML widget.

Thanks

**Comment by kovac031** [comment]
Thank you for your reply!

However, could you explain where would I copy the code you provided and how
to use it? I am a complete non-techie. I was not expecting to come across
obstacles such as these.
