### ISSUE TITLE
Problem with responsive choose control

### ISSUE THREAD

**Issue by imranharoon2018** [elementor/elementor#8073]
Hi,
I am facing a problem with the code for responsive choose control for text alignmnet available in this link:

https://developers.elementor.com/add-responsive-controls-to-widgets/

When the "desktop" is selected the control(please see the image below) is working(it is aligning the text to left/right/center depending on the button clicked).

![responsive](https://user-images.githubusercontent.com/40739748/57427459-342eab00-724e-11e9-9d42-ebf59a2d9138.png)

However, the buttons are not working when I am selecting tablet.  I am writing down the some code for your reference
The css classes
`.content-align-left{
	border:1px solid red;
	text-align:left;
}
.content-align-right{
	border:1px solid blue;
	text-align:right;
}
.content-align-center{
	border:1px solid green;
	text-align:center;
}
`
the register control function
`	protected function _register_controls() {
		
		$this->start_controls_section(
			'style_section',
			[
				'label' => __( 'Style Section', 'elementor-test-extension' ),
				'tab' => \Elementor\Controls_Manager::TAB_STYLE,
			]
		);

		$this->add_responsive_control(
			'content_align',
			[
				'label' => __( 'Alignment', 'elementor-test-extension' ),
				'type' => \Elementor\Controls_Manager::CHOOSE,
				'options' => [
					'left' => [
						'title' => __( 'Left', 'elementor-test-extension' ),
						'icon' => 'fa fa-align-left',
					],
					'center' => [
						'title' => __( 'Center', 'elementor-test-extension' ),
						'icon' => 'fa fa-align-center',
					],
					'right' => [
						'title' => __( 'Right', 'elementor-test-extension' ),
						'icon' => 'fa fa-align-right',
					],
				],
				 'devices' => [ 'desktop', 'tablet' ],
				'prefix_class' => 'content-align-%s',
			]
		);			
		$this->end_controls_section();
			
	}`
The render function
`protected function render() {				
		echo "hello world!";
	}`

Thanks

**Comment by DeliciousThemes** [comment]
If you'll check out the source code, the content-align- class appears multiple times, based on the device versions you're having. I'm having the same issue http://prntscr.com/pf5wim because the class is added multiple times, each time for each device. So the classes basically "fight" each other, the last one in the list winning and overwriting the styles of the other ones. 

We need a way to define a specific class for every device size: mobile, tablet, desktop. Ex: 

'prefix_class_desktop' => 'desktop content-align-%s',
'prefix_class_tablet' => 'tablet content-align-%s',
'prefix_class_mobile' => 'mobile content-align-%s',

If anyone knows how to do this, that would be cool! 

Thanks!

**Comment by arielk** [comment]
You can use 'selectors' instead of 'prefix_class' for this, learn more here: https://developers.elementor.com/add-responsive-controls-to-widgets/
