### ISSUE TITLE
Dotted Divider turns into squares on Mobile

### ISSUE THREAD

**Issue by cmvrtmktg** [elementor/elementor#8110]
Using the divider element and selecting "Dotted" styling does not translate on Mobile (iphone/ipad). Displays as dots on Elementor interface and Google Chrome (desktop) and dots turn into squares on Safari/Chrome Mobile. The issue also exists when using one-sided borders to create circles on Elementor Contact form. The issue does not exist on Chrome for Android. 

The following images show the problem. 
![chrome-desktop-view](https://user-images.githubusercontent.com/50594416/57645515-6e6cb500-758c-11e9-887b-f20296bfd009.png)
![elementor-mobile-view](https://user-images.githubusercontent.com/50594416/57645516-6f054b80-758c-11e9-802b-c3cb1f748596.png)
![chrome-mobile-view](https://user-images.githubusercontent.com/50594416/57645534-7a587700-758c-11e9-80f6-0580effa01ff.jpg)
![Safari-mobile-view](https://user-images.githubusercontent.com/50594416/57645575-90fece00-758c-11e9-8549-edf8983edeb8.jpg)

**Comment by shilo-ey** [comment]
Hi @cmvrtmktg 

WebKit browsers render the `dotted` border attributes different. [see here](https://css-tricks.com/almanac/properties/b/border/), [and here](http://old.macedition.com/cb/resources/safari/bordertest1.html).

A solution for your case can be [using SVG element](https://codepen.io/azzcatdesign/pen/HmtaB) instead of the dashed border.

Thanks
