### ISSUE TITLE
How to use elementor group control with responsive control

### ISSUE THREAD

**Issue by imranharoon2018** [elementor/elementor#8111]
Hi All, 
Is it possible to make the Group_Control_Typography available in the following link with responsive control.

link: https://developers.elementor.com/add-group-controls-to-widgets/

I am attaching code for the widget for your reference.

[test-responsive-typography.zip](https://github.com/elementor/elementor/files/3175717/test-responsive-typography.zip)

Thanks

**Comment by sproutedweb** [comment]
## Your ticket has been created. ##


Ticket subject: [elementor/elementor] How to use elementor group control with responsive control (#8111)


----
Author: imranharoon2018 
Date: Mon, 05/13/19 8:31 pm
Message:
Hi All, 
Is it possible to make the Group_Control_Typography available in the following link with responsive control.

link: https://developers.elementor.com/add-group-controls-to-widgets/

I am attaching code for the widget for your reference.

[test-responsive-typography.zip](https://github.com/elementor/elementor/files/3175717/test-responsive-typography.zip)

Thanks

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/elementor/elementor/issues/8111



Powered by https://www.livechatinc.com/powered-by-livechat/?utm_source=ticket_footer&utm_medium=email&utm_campaign=lc_10152642"

**Comment by bainternet** [comment]
@imranharoon2018 

You cannot add a group control via `add_responsive_control` only via `add_group_control`.

thanks.
