### ISSUE TITLE
[Elementor CLI] Ability to enable / disable maintenance mode

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#8112]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be fantastic to allow maintenance mode to be enabled / disabled through the WP CLI system, so that we can toggle this on and off in deploy scripts on a server.

Let's say you have a staging server that you're developing on, and a production server visible to the public. You want to protect the staging server from public access by using a 'maintenance mode' splash page, but it's not necessary for production. However, each time you push from staging to production, the status of the maintenance page follows it, and you have to manually disable it all the time on production.

So, having a command line that enables or disables this, allows you to automate the process in a deployment script, eg git hooks. So you can still keep the maintenance page live on staging, but it gets toggled off when pushing to production.

Similarly, each time you pull from production, you don't want to manually enable the maintenance mode page all the time. So, another hook script can turn it back on for you.

But even cooler, you might want to disable your production site periodically (for instance, your dev team does scheduled maintenance on the last Friday of each month). So, a cron job could toggle maintenance mode on or off during that time and the site visitors would see 'Maintenance mode' for that time period.

**Describe the solution you'd like**
Have a command line like ```wp elementor maintenance on``` or ```wp elementor maintenance off``` to toggle maintenance mode in deployment scripts. See: https://docs.elementor.com/article/461-wp-cli

**Describe alternatives you've considered**
There's probably a longer way of doing this using standard WP CLI and hiding / showing the maintenance template or manipulating wp_options but it's kinda messy.

**Comment by sproutedweb** [comment]
## Your ticket has been created. ##


Ticket subject: [elementor/elementor] [Elementor CLI] Ability to enable / disable maintenance mode (#8112)


----
Author: Drawcard 
Date: Mon, 05/13/19 9:42 pm
Message:
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be fantastic to allow maintenance mode to be enabled / disabled through the WP CLI system, so that we can toggle this on and off in deploy scripts on a server.

Let&#x27;s say you have a staging server that you&#x27;re developing on, and a production server visible to the public. You want to protect the staging server from public access by using a &#x27;maintenance mode&#x27; splash page, but it&#x27;s not necessary for production. However, each time you push from staging to production, the status of the maintenance page follows it, and you have to manually disable it all the time on production.

So, having a command line that enables or disables this, allows you to automate the process in a deployment script, eg git hooks. So you can still keep the maintenance page live on staging, but it gets toggled off when pushing to production.

Similarly, each time you pull from production, you don&#x27;t want to manually enable the maintenance mode page all the time. So, another hook script can turn it back on for you.

But even cooler, you might want to disable your production site periodically (for instance, your dev team does scheduled maintenance on the last Friday of each month). So, a cron job could toggle maintenance mode on or off during that time and the site visitors would see &#x27;Maintenance mode&#x27; for that time period.

**Describe the solution you&#x27;d like**
Have a command line like &#x60;&#x60;&#x60;wp elementor maintenance on&#x60;&#x60;&#x60; or &#x60;&#x60;&#x60;wp elementor maintenance off&#x60;&#x60;&#x60; to toggle maintenance mode in deployment scripts. See: https://docs.elementor.com/article/461-wp-cli

**Describe alternatives you&#x27;ve considered**
There&#x27;s probably a longer way of doing this using standard WP CLI and hiding / showing the maintenance template but it&#x27;s kinda messy.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/elementor/elementor/issues/8112



Powered by https://www.livechatinc.com/powered-by-livechat/?utm_source=ticket_footer&utm_medium=email&utm_campaign=lc_10152642"

**Comment by bainternet** [comment]
@drawcard 

Elementor saves its maintenance mode settings in the options table, meaning you can already trigger it from WP-CLI, ex:

```
wp  option update elementor_maintenance_mode_mode  maintenance
wp  option update elementor_maintenance_mode_template_id  21
```

where 21 is the desired template id. And to toggle it off simple delete the `elementor_maintenance_mode_mode` option, ex:

```
wp option delete elementor_maintenance_mode_mode
```

or if you really want to you can simply extend the Elementor CLI command, ex:

```PHP
if ( defined( 'WP_CLI' ) && WP_CLI ) {

	class Elementor_Maintenance_Mode_Command extends \Elementor\Modules\WpCli\Command {
		/**
		 * Toggle Elementor Maintenance mode
		 *
		 * ## OPTIONS
		 *
		 * <state>...
		 * : Toggle on/off
		 * ---
		 * options:
		 *   - on
		 *   - off
		 * ---
		 *
		 * [<template-id>]
		 * : Optional set template ID when Toggle state is set to 'on'
		 *
		 * ## EXAMPLES
		 *
		 *     # Toggle On
		 *     wp elementor maintenance on
		 *     Success: Maintenance Mode Activated!
		 *
		 *     # Toggle On and set template id
		 *     wp elementor maintenance on 21
		 *     Success: Maintenance Mode Activated!
		 *
		 *     # Toggle Off
		 *     wp elementor maintenance off
		 *     Success: Maintenance Mode Deactivated!
		 */
		public function maintenance( $args, $assoc_args ) {
			$message = 'Please see Help for wp elementor maintenance';
			if ( empty( $args[0] ) || ! in_array( $args[0], [ 'on', 'off' ] ) ) {
				return WP_CLI::error( $message );
			}
			switch ( $args[0] ) {
				case 'on':
					update_option( 'elementor_maintenance_mode_mode', 'maintenance' );
					WP_CLI::success( 'Maintenance Mode Activated!' );
					if ( ! empty( $args[1] ) ) {
						update_option( 'elementor_maintenance_mode_template_id', (int) $args[1] );
					} else {
						$template_id = (bool) get_option( 'elementor_maintenance_mode_template_id' );
						if ( ! $template_id ) {
							WP_CLI::warning( 'Maintenance Mode Activated, But no template ID was specified!' );
						}
					}
					break;
				case 'off':
					delete_option( 'elementor_maintenance_mode_mode' );
					WP_CLI::success( 'Maintenance Mode Deactivated!' );
					break;
			}
		}
	}

	WP_CLI::add_command( 'elementor', 'Elementor_Maintenance_Mode_Command' );
}
```

**Comment by drawcard** [comment]
That's great - thanks for the information! I should have looked at ```wp option``` a bit more closely.

**Comment by RonR-WebDesign** [comment]
I use this in Code Snippets:

// Disable Elementor Maintenance Mode
// Schedule a cron job to turn off Elementor maintenance mode

// Set the timezone for the scheduled event
date_default_timezone_set( 'America/Los_Angeles' );

// Schedule a cron job to turn off Elementor maintenance mode at 10:00 AM on May 1st, 2023
wp_schedule_single_event( strtotime( '2023-05-01 10:00:00' ), 'turn_off_elementor_maintenance_mode' );

// Register a custom action to turn off Elementor maintenance mode
add_action( 'turn_off_elementor_maintenance_mode', 'turn_off_elementor_maintenance_mode' );
function turn_off_elementor_maintenance_mode() {
    delete_option( 'elementor_maintenance_mode_mode' );
}

**Comment by kansinghrathore** [comment]
> I use this in Code Snippets:
> 
> // Disable Elementor Maintenance Mode // Schedule a cron job to turn off Elementor maintenance mode
> 
> // Set the timezone for the scheduled event date_default_timezone_set( 'America/Los_Angeles' );
> 
> // Schedule a cron job to turn off Elementor maintenance mode at 10:00 AM on May 1st, 2023 wp_schedule_single_event( strtotime( '2023-05-01 10:00:00' ), 'turn_off_elementor_maintenance_mode' );
> 
> // Register a custom action to turn off Elementor maintenance mode add_action( 'turn_off_elementor_maintenance_mode', 'turn_off_elementor_maintenance_mode' ); function turn_off_elementor_maintenance_mode() { delete_option( 'elementor_maintenance_mode_mode' ); }

how to active Maintenance Mode through cron
