### ISSUE TITLE
Missing i18n function in role manager

### ISSUE THREAD

**Issue by wpmarmite** [elementor/elementor#8145]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

As a french Elementor user, I noticed that an i18n function is missing in the role manager.
It's located at https://github.com/elementor/elementor/blob/master/core/role-manager/role-manager.php#L124

To make it work, we can replace `echo esc_html( $role_data['name'] );`
by `esc_html_e( $role_data['name'] );`

**Comment by bainternet** [comment]
@wpmarmite 

When you use `esc_html_e` instead of `esc_html` and pass a variable you will get a PHPCS error and the translation won't be picked up by translation tools/plugins:

> You cannot use constants, variable or anything other than actual strings with translation functions.
This is because the code that reads your code, and produces the translatable strings does not actually run your code, it is reading your code.

Here is a more detailed post on the topic: http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/ by Otto.

Thanks.
