### ISSUE TITLE
[bug] text widget adds extra line break when using live text editor

### ISSUE THREAD

**Issue by avermat** [elementor/elementor#8167]
I've seen this bug on multiple installs. When I click on a text widget it adds an extra line break to the end of the text. When I edit the text using the live (inline) text editor, it permanently keeps this extra line break. 

**Here's a video of the issue:**
https://www.dropbox.com/s/51wtrm90wb5uoif/text-widget-extra-spacing.mp4?dl=0

**Setup:**
Fresh local install
Hello Theme
Elementor
Nothing else installed

**Comment by shilo-ey** [comment]
Hi @avermat 

Thanks for reporting.

Wordpress has native function named `wpautop` which adds `<p>` tags instead of `<br>` tags.

In order to stay compatible with it, we added support to this function.

When editing the text editor widget - Elementor wraps the text with `<p>` tag and therefore gets the bottom margin to it.

Thanks.

**Comment by BRadHoc** [comment]
How can we stop this from happening? I can't give a website to a client where it does this and breaks the design everytime they click a field in the editor?
