### ISSUE TITLE
Error: noUiSlider (13.0.0): 'start' option is incorrect.

### ISSUE THREAD

**Issue by vgeek** [elementor/elementor#8180]
When editing sections, the editor sidebar is gray and browser console shows:

"Error: noUiSlider (13.0.0): 'start' option is incorrect."

It only happens on <10% of sections, some have columns inside, others do not. No common element/feature of the sections. Deleting and recreating sections works, but you are unable to edit the existing. Tried different browsers, hard refreshes, etc..

WordPress Environment |   |  Version: | 5.2.1
Elementor - 2.5.15 | By Elementor.com |  
Elementor Pro - 2.5.8 | By Elementor.com

**Comment by vasnakos** [comment]
+1

**Comment by caetanolima** [comment]
after the update gave the same problem here, has anyone managed to solve?

**Comment by NicholasTEllis** [comment]
No, not yet. The only workaround we have now is what vgeek mentioned. Deleting and recreating sections works, but you are unable to edit the existing.

**Comment by kmoloo** [comment]
I'm getting this issue too, but only when trying to edit sections I've added from the template library (both pages and blocks)

Elementor v2.5.16
Elementor Pro v2.5.9
Wordpress 5.2.1
Jupiter theme 6.1.5

**Comment by shilo-ey** [comment]
@kmoloo can you please specify a specific template & section in which this issue occurs?

**Comment by caetanolima** [comment]
Hello, I found the error here! the problem is in a caydon Element Pack plugin, its slider element is incompatible with the updated version of the pro elementor. I just disable it and everything returns to normal. You can also check out some Slide plugin. Success and thanks for the feedbacks

**Comment by shilo-ey** [comment]
Thanks @caetanolima !

Please contact the developer of this plugin and update them regarding this issue.

Cheers.

**Comment by Sanabria** [comment]
Popup builder plugin also has this very same incompatibility...

**Comment by jasperf** [comment]
> Popup builder plugin also has this very same incompatibility...

You are right. I just had this same error. Once Popup Builder was deactivated Elementor did fine again and I could edit sections properly again.

**Comment by geri777** [comment]
For me it was "Modern Events Calendar" Version 6.4.2 which caused the troubles. 
https://wordpress.org/plugins/modern-events-calendar-lite/
After deactivation everything worked again.

**Comment by hendrasyp** [comment]
Where I can disable Popup Builder ?

**Comment by ZaDarkSide** [comment]
This happens also if you run Elementor 3.7.8 with Yoast SEO 19.7.1 and Yoast SEO Premium 19.1

**Comment by gerardreches** [comment]
Happening now to my containers in an specific template after converting my sections to containers. So this doesn't only happen to sections, it happens to the new containers as well.

**Comment by nicholaszein** [comment]
Hello!

### ❌ 🧩 This issue is caused by add-on conflicts.

To isolate this conflict please try these **Troubleshooting** steps:

#### ⚠️ Make a Backup of your website before proceeding, and if possible do it in a staging environment!

1. 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

2. 🗑️ **Clear the cache:** Clear all levels of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.

3. 📋 **Meet the Requirements** Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). 
    - To check this information go to your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

### 👎 If the issue persists use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Regards
