### ISSUE TITLE
Waitlist

### ISSUE THREAD

**Issue by Steriotis** [elementor/elementor#8215]
It would be a great add to the Elementor if we have a "waitlist" implementation.

When a product is out of stock, the customer will have the option to leave an email and
get in the waiting list of the product.

I believe it's a must plugin for WooCommerce and generally e-shops.

**Comment by bainternet** [comment]
@Steriotis 

Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

As for the request itself, since this is not a feature of WC, we feel that this should stay in the 3rd party plugin territory.

thanks.
