### ISSUE TITLE
JavaScript Performance

### ISSUE THREAD

**Issue by pcfreak30** [elementor/elementor#8221]
## Prerequisites

- [ * ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ * ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Improve the performance of a page due to how javascript loads and executes. If you were to use a plugin, such as Asset Cleanup to remove all javascript Elementor adds in, then use a widget such as animated headline, you could not go back and allow only the js for that headline. It would be an all or nothing.

The javascript in total is about 7-9 javascript bundles that make up all the JS-based features in elementor. The JS is also a few hundred KB more of JS that has to load on mobile. The JS can have a severe performance penalty as tested on Page Speed Insights and GTMetrix.

**Describe the solution you'd like**
Javascript assets should load on demand as needed for each widget. If a widget has logic to not show in any conditional situation, then its JS should not be enqueued.

Right now, you have things such as frontend, frontend-modules, and some dependency libraries. These should all spit up and loaded as needed so if you only have 1 JS-based widget, only the minimum JS required for it to function gets loaded.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by black-eye** [comment]
+1
Yes pls. It should be done either automatically (if widget is used, JS is loaded) or at least by some kind of widget manager (turn on/off the whole widet INCLUDING it's JS and CSS).

**Comment by bainternet** [comment]
@pcfreak30 

Elementor loads his core JS when elementor is loaded. this core JS file holds the functionality of initializing the page elements in many aspects ( animations, responsiveness, anchor handling, stretched elements, lightbox and a few more). Other than that this core JS file also holds functionality for a few widgets which are small in size and frequently used like: tabs, accordion, video, drop-cap and a few more.

Other than that, Widgets that require extra scripts/libraries enqueue the library them selfs per need which is what you are describing.

In our view, we load the minimal and most common needed functionality bundled instead of loading many JS files per each page, which in turn actually boosts performance on 2nd to (n)th page loads since the JS file is already loaded in the browser cache.

Thanks.

**Comment by pcfreak30** [comment]
@bainternet I understand your perspective and reasoning but respectfully disagree

The core framework itself should be its own file. Mainly the hook system and basic classes.

The animations should be in their own file at a minimum, ideally separating them so they can be selectively loaded. 

```In our view, we load the minimal and most common needed functionality bundled instead of loading many JS files per each page, which in turn actually boosts performance on 2nd to (n)th page loads since the JS file is already loaded in the browser cache.```

The problem here is that by doing that it penalizes the sites that don't use these widgets/assets and that are conscious about site performance. I have recently gone out of my way to put as little JS on a page as practical. I just now had to undo nearly at that to get a mobile hamburger menu to load.

Loading the core and pro assets selectively would end up allowing better performance by not loading what is not needed. Combine with a minify plugin, and you are not running JS that's never actually used on a page.

Thanks
