### ISSUE TITLE
Share Icons not showing up. I'm just seeing the circle because I put the circle shape.

### ISSUE THREAD

**Issue by luizzyng** [elementor/elementor#8556]
Hi team,

I added Share buttons of Elementor to my website but the icons are not showing anymore. I'm using GeneratePress as theme. Please help me.

![Capture](https://user-images.githubusercontent.com/44413962/61147739-04618500-a4d5-11e9-9ef0-af4f70b51084.PNG)

**Comment by bainternet** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by TinyGiantStudios** [comment]
@luizzyng - We managed to replicate the same thing on our side and have submitted a bug report in the meantime.

In short, the bug is a result of the new Font-Awesome library switch. Here are the relevant screenshots:

## Error

![Font-Awesome-Error-1](https://user-images.githubusercontent.com/685686/61631029-86963a00-ac89-11e9-9054-896c45d73b0a.png)

## Fix

![Font-Awesome-Fix-1](https://user-images.githubusercontent.com/685686/61631039-8d24b180-ac89-11e9-9165-853d3b3295ae.png)

This is something that the Elementor Pro devs will need to fix in a future update.

CC @bainternet
