### ISSUE TITLE
How to remove action enqueue font awesome in Icons_Manager class?

### ISSUE THREAD

**Issue by steve231293** [elementor/elementor#8581]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Hello Elementor team,

I'm developing a theme use Elementor + Font Awesome Pro.
I want to my clients have Font Awesome Pro font by default instead of input "Kit ID" at Elementor -> Settings -> Integrations -> Font Awesome Pro.

So, I manual enqueue & add font to libraries. Everything is working ok, but there is small problem.
I can't remove action enqueue font awesome in Icons_Manager class.

I tried:
`remove_action( 'elementor/editor/after_enqueue_scripts', [ 'Elementor\Icons_Manager', 'enqueue_fontawesome_css', ] );`

and: 
```
add_action( 'wp_enqueue_scripts', 'remove_fontawesome_enqueue_styles' ], 999999 );
function remove_fontawesome_enqueue_styles() {
  remove_action( 'elementor/editor/after_enqueue_scripts', ['Elementor\Icons_Manager', 'enqueue_fontawesome_css' ] );
}
```

But it's not working.

Could you help me, please? Many Thanks

**Comment by bainternet** [comment]
@steve231293 

Not sure you can Include Font Awesome Pro for your clients ( FA PRO subscription limitation) which is why we added the option to use FA pro new KIT API. 

Also, the new Icon Library when used correctly, takes care of enqueuing per-use bases so you don't need to manually enqueue anything.

But if you know what you are doing then you can simply deregister the font-awesome styles:

```PHP
add_action( 'elementor/frontend/after_register_styles',function() {
	foreach( [ 'solid', 'regular', 'brands' ] as $style ) {
		wp_deregister_style( 'elementor-icons-fa-' . $style );
	}
}, 20 ); 
```

Thanks
