### ISSUE TITLE
Motion effect not working

### ISSUE THREAD

**Issue by lcswillems** [elementor/elementor#8593]
Motion effect is not working anymore. Here is a page where I use them: https://www.miple.co/

The elements were meant to fade in, but they just appear.

It was working when I made the page 2 months ago, but is not working anymore.

I tested it on Chrome, under MacOS. I have Elementor 2.6.

![image](https://user-images.githubusercontent.com/5437552/61366559-1606ac00-a88a-11e9-8ff5-59bcc7920401.png)

**Comment by shilo-ey** [comment]
Hi @lcswillems 

Since Elementor v2.6 respects the accessibility "reduced motion" property preference that a user may set. If a user has set any of the following, then motion effects will be disabled for that user:

- Mac: "System Preferences > Accessibility > Display" and check/un-check the box for "Reduce motion"
- iOS: "Settings > General > Accessibility" and turn on/off "Reduce Motion"
- Windows 10: "Settings > Ease of Access > Display > Simplify and personalise Windows" 

Simply disable this option in your computer and you will be able to see those animations again.

**Comment by lcswillems** [comment]
Thank you for the answer.

Is this Elementor choice documented somewhere? If yes, my bad. If no, it should.

The problem this choice from Elementor is that, in the case user activated "Reduce motion", my website will badly behave. Is it possible to completely disable the animations in the case "Reduce motion" is checked?
