### ISSUE TITLE
Conflict with custom plugin

### ISSUE THREAD

**Issue by dkag** [elementor/elementor#8645]
Hello

We created a custom made extensionplugin for elementor pro.
This plugin connect between forms based on elementor and ZebraCRM. All details are automatically sending form to this CRM,
The development of plugin based on 2.2.4 version of elementor and it works correct. Now we updated the version to 2.5.12 and got some conflict. We get fatal error in each time of entering to elementor editor of any page.
We checked this issue and saw that in this version in file module.php was added line 51 (see the screenshot http://prntscr.com/ofd4k8) and this line is reason to conflict. If I comment this line everythins is work fine.
What is this line? Is there any way to disable it from outside without change elementor plugin code? 

Please advice
Dmitry Kagan

**Comment by bainternet** [comment]
@dkag 

No, there is no way to disable that line, which actually fixes issues with Global Widget.

But if you have developed your custom form action [according to our docs](https://developers.elementor.com/forms-api/custom-form-action/), I see no reason that this "line"  would cause any issues.

if you want to provide details with the actual error, and your code, we'll take a look and try to help.

**Comment by dkag** [comment]
thanks for reply
checked again the code according to your docs but still don`t see any problem in the code
I attached the code. The problem: if you active my plugin and elementor pro v 2.5.12 so you can`t enter to elementor editor of pages. You get fatal error
Please advice
[zebra-crm-with-elementor.zip](https://github.com/elementor/elementor/files/3434290/zebra-crm-with-elementor.zip)

**Comment by bainternet** [comment]
@dkag 	

I checked your code,( which in no way looks like our docs) there are so many things wrong:
* The whole run function in the action class is empty.
* You copied the exact class name from the docs.
* Defined multiple namespaces on right after the other which makes no sense.
* you register your section without a condition if the action was actually added.
* you call `get_active_settings` inside the `register_settings_section` (the actual cause for the fatal error)

and on and on...

as for the fatal error, you can't call `get_active_settings` inside the `register_settings_section` because `register_settings_section` runs before there are any settings and it only runs on the PHP side so you are not aware of the fields being added to the form at that point.

thanks
