### ISSUE TITLE
[Pro, Forms module] Add post ID of current viewed page when a form is in a modal

### ISSUE THREAD

**Issue by tristanleboss** [elementor/elementor#8708]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
We have different pages which use different forms in modals. We want to save leads in a database depending on the page it comes from.

When a form from a modal is submitted, the `post_id` sent through ajax is the one of the popup template.
So, if we are on page with id 69 which uses a form from the template with ID 70, we receive post_id = 70.
This is problematic because it's impossible to find out from which page the lead is coming.
A modal can be reused on different pages so we can't find out from where it comes from.

**Describe the solution you'd like**
When a form from a modal is submited, add a `parent_post_id` to the ajx request with the ID of the page the user is on.

**Comment by bainternet** [comment]
@tristanleboss 

Elementor Form Widget has no context of which post (any custom/template/...) is the main page loaded and which is just the container of the form.

Elementor Form sends the post id of the container so the backend will know were to pull the settings from in order to process the form.

You can, however, use a hidden field and set its default value to Dynamic post ID, which should give you the actual post id of the page you are coming from if you are on a post, page or custom post type single item.

thanks.
