### ISSUE TITLE
Youtube background Youtube video has audio active on mobile +  audio notification ICON

### ISSUE THREAD

**Issue by cecofuli** [elementor/elementor#8782]
Hello,

in the last version of Elementor I have this same, exact problem:

https://github.com/elementor/elementor/issues/5275

In short:
I have a section with a Youtube background video.
On Tablet this video is hidden.
But, with Chrome, when I watch this page,  I'm able to hear the music and I see the audio notification on Chrome browser...

I don't remember such behavior in the past...

Can you fix it?

Thank you

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by cecofuli** [comment]
Thankssss! ^__^

**Comment by shilo-ey** [comment]
Hi @cecofuli 

Until now, Video backgrounds had the `display: none` property in mobile media queries, in order to avoid issues with autoplay on mobile devices.

In the upcoming fix, we will completely remove this script from being loaded in the page in mobile devices to avoid this issue and provide better performance.

We are planning to release this fix in v2.7 due to the fact that some users forced the background video to show up on mobile devices, with `display: block` property, and to allow them the time to adjust to the upcoming change - we will post a blog post in our [developers blog](https://developers.elementor.com/) and let them know about it.

Thanks!

**Comment by cecofuli** [comment]
Hello Shiro,

so, if I understand correctly, in the next release you will fix this problem. 
Do I have understand correctly? sorry, but I'm a bit newbie ^__^

Thank you!

**Comment by cecofuli** [comment]
Hello,

I update Elementor to the last version, But I still have soud in the background with my mobile. 
Why? 
Thank you
