### ISSUE TITLE
Font Awesome 5 Pro loading freeze editor

### ISSUE THREAD

**Issue by codeagencybe** [elementor/elementor#8833]
Hello,

When integrating FA5 Pro, the editor freezes completely upon loading all the assets. 
My KIT is validated, all fine. Icons are also visible if I drop in the official <i class</i> tags inside the editor. 

But when I try adding an elementor widget like icon, icon box etc... and click the button to open the icon library, the editor freezes for like 30 seconds because it seems trying to load all 7000+ assets. 
After those 30 seconds, the editor becomes responsive again, I can scroll a little bit down and then it freezes up completely until my screen turns white completely. 
Now I have to force reload my screen and my re-do my changes again (if one didn't click change first)
I can repeat this process over and over, tried on existing websites upgraded, new fresh installs, ... 

It just seems that the integration is overloaded by the massive amount of icons from the PRO library. 
When I disable the FA5 KIT, everything turns back to normal. 
Working on a dedicated server (128 GB RAM, 16 cores, max_memory is set to 2048M) so too few resources is also not the cause because all the rest is working excellent, fast, snappy, ... it's just the PRO library. 

I made a screen recording to show how slow it is loading. 
https://www.loom.com/share/10b83f8311ee45c89d22f1ad287159da

**Comment by bainternet** [comment]
@codeagencybe 

The Icon Library runs on the Frontend and not on the server so your server config has nothing to do with it.

So too few resources could be a problem in your client/browser.

Now with that said, we are aware that when loading Font Awesome 5 pro icons there is a little delay which is caused by the amount (over 5000 icons) of elements in the library, but we can't replicate this crash you have reported.

please try with a different browser, maybe even same browser but in "safe-mode" with extensions disabled.

Thanks.
