### ISSUE TITLE
Change Icon showing Blank panel

### ISSUE THREAD

**Issue by techitint** [elementor/elementor#8932]
As identified in the issue: https://github.com/elementor/elementor/issues/8513
and not answered by anyone, I have the same problem.

I have two identical websites running on the same Plesk server with identical setup, one is showing the Icons correctly (running a commercial theme), the other running OceanWp theme is showing a blank empty panel instead of the icon list.

Elementor Pro for both
Server config is the same.
Nginx config is the same (plesk template)
No Caching for both
Driving me nuts (only the one without icons).

Thanks for your support
Renato
![Screen Shot 2019-08-29 at 12 59 02](https://user-images.githubusercontent.com/7043124/63907894-7b8cb180-ca60-11e9-9462-d1d450baa444.jpg)

**Comment by shilo-ey** [comment]
Hi @techitint 

Thanks for your feedback.

We tried to reproduce your issue based on the information you provided, but without success.

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by techitint** [comment]
My solutions and work around: 
1st. I've built an Icon block on another website, exported as template and reimported... all good.
2nd I have created a small pack of Fontello icons, and imported in the website, magically all other icons re-appeared.

**Comment by iamdanbarrett** [comment]
This is a bug, so I repeated this 3 times and the same result. If you add a custom font and publish it wipes out the default FontAwesome icons, furthermore the same happens if you leave any in draft or in the bin - it simply kills the default icons by adding any new ones. Make sure you totally delete them all eve empty the bin and the icons come back. Strange, annoying and not clearly some bugs in the codebase somewhere.
