### ISSUE TITLE
onElementChange does not fire on Repeater or its child controls

### ISSUE THREAD

**Issue by danyj** [elementor/elementor#9063]
Add this as test class for your frontend

```
class TestClass extends elementorModules.frontend.handlers.Base {

	onElementChange( propertyName ) {
	  console.log(propertyName);
	}

}

jQuery( window ).on( 'elementor/frontend/init', () => {
   const addHandler = ( $element ) => {
       elementorFrontend.elementsHandler.addHandler( TestClass, {
           $element,
       } );
   };

   elementorFrontend.hooks.addAction( 'frontend/element_ready/global', addHandler );
});
```
The console logs every element changed controls name except the repeter and its child controls

Here https://monosnap.com/file/7KrlCT5c3En7b1H3RybFkIV4lQWSOO

**Comment by bainternet** [comment]
@danyj 	

You are mixing things:

* `elementorModules.frontend.handlers` should be used for front end handlers and not editor controls related actions.
* Because of the above `elementorFrontend.hooks.addAction( 'frontend/element_ready/global', addHandler );` is not the way to go.
* Even if `onElementChange` of `elementorModules.frontend.handlers.Base` actually gets triggred for regualr controls, a repeater control is a control stack and not a simple control. 

So if you want to listen to changes of a repeater control you need to add a listener to a specific repeater control collection, ex:

```JS
// Helper to get the control by id
const getEditorControlView = function( id ) {
	const editor = elementor.getPanelView().getCurrentPageView();
	return editor.children.findByModelCid( this.getEditorControlModel( id ).cid );
};
// Get the repeater control named "CONTORL_ID" view
const repeaterControlView = getEditorControlView( 'CONTORL_ID' );

// Attach your listeners
repeaterControlView.collection
	.on( 'change', model => console.log( 'change:', model ) )
	.on( 'update', ( collection, update ) => {
		if ( update.add ) {
			return console.log( 'true add:', collection, update );
		}
		return console.log( 'add on sort:', collection, update );
	} )
	.on( 'remove', model => console.log( 'removed:', model ) );
```

Hope this helps.

**Comment by riadcitaku** [comment]
@bainternet is there any way to add new items to the repeater via JavaScript?

- https://github.com/elementor/elementor/issues/12048

**Comment by CodeExplore** [comment]
@bainternet 

Can you help me one thing ? I am trying to add "change event" for repeater fields but no luck.

```javascript
elementor.hooks.addAction( 'panel/open_editor/widget/mywidget', function( panel, model, view ) {

  model.get( 'settings' ).on( 'change', function( changedModel ){
    console.log( changedModel );
  });

});
```

This code only works for panel text, textarea, select etc. It doesn't listening inside repeater field changes. I did try your code but not understand totally.

Thanks
