### ISSUE TITLE
Shortcodes get executed more than once

### ISSUE THREAD

**Issue by methgyver** [elementor/elementor#9071]
By means of Elementor shortcodes get excecuted more than once. In this screencast I am demonstrating this: https://www.loom.com/share/968f16b039fc42c7adbb408c2eb2c826

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

No as for the actual issue you are reporting, Elementor can call/execute the shortcode multiple times in order to render it correctly with all styling applied but as long as it will not actually output the returned value of the shortcode, Then its working as designed.

If this is not the case and you are getting the output of the shortcode multiple times on your page, please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.
