### ISSUE TITLE
Responsive mode previews don't honor visibility in editor.

### ISSUE THREAD

**Issue by poehaldur** [elementor/elementor#9191]
In editor if you hide something on mobile and change preview window to desktop and then mobile again, you still see the element in backend even tho in frontend it is hidden like needed.

Is there a way to fix this at 15:18?
https://youtu.be/7EG_CBVw9vc?t=917

I have the same problem, everything is smushed up in editor but looks fine on front end. Really difficult to develop mobile if mobile hidden desktop section is mushed over whole mobile header.

**Comment by shilo-ey** [comment]
Hi @poehaldur 

Thanks for your feedback.

This is the expected behavior.

When entering responsive mode in the editor - the only way to simulate the exact behavior that will be in the frontend is to collapse the panel by clicking on the panel collapse button:

![image](https://user-images.githubusercontent.com/45009641/65685974-f818ad00-e06b-11e9-8a5f-c86bab005061.png)

Thanks!

**Comment by poehaldur** [comment]
Ah, very cool. Now I know. Thanks.
