### ISSUE TITLE
Difference between render() and _content_template() functions for custom Elementor Widget

### ISSUE THREAD

**Issue by sladjanstojcic** [elementor/elementor#9208]
Hi, I am working on a quite big Elementor project and so far I developed around 10 custom widgets. As I am more of junior web dev, I am not sure if I am doing it right.

Most of my custom widgets are displaying data from APIs and I am using render() function to print HTML and external JS file to do all the logic. My _content_template() function is empty. Is that right approach? Everything is working ok on the frontend so I am not sure should I write _content_template() function too? What is the purpose of _content_template() function?

Thanks,
Sladjan

**Comment by EnjeruTantei** [comment]
_content_template() is a function that gets called in the Elementor Editor when something causes the preview to be reloaded (adding animations to buttons, etc). It honestly depends on if your widgets need that type of functionality and just how complex they are.

**Comment by eatbuildplay** [comment]
I am also confused by the role of _content_template() which I believe is now deprecated (use content_template() without underscore prefix). I find it is never utilized at all, but I must not be using the type of preview where it is needed. My custom widget has controls, and those controls when updated are shown in preview using render(). I find all forms of preview, live editor, and preview page, both use render() and never use _content_template(). 

I think the documentation should demonstrate the exact situation where _content_template() would actually be used, because this is a point of confusion for new widget builders. We're expecting based on the docs, that content_template() is being used to generate the previews, that's not true, render() generates template output at least for basic widgets.

**Comment by EnjeruTantei** [comment]
My understanding of content_template right now is that it's called when certain controls are changed on the editor, such as certain button animations such as 'grow', 'shrink', etc. If content_template is not defined for these cases, sometimes the widget will get re-rendered as a gray box. It's important to note that this only occurs while in the editor, and will revert back if the page is refreshed; it does not effect the widget outside of the editor in the slightest.

**Comment by udidol** [comment]
Hi,
Here is a short and concise explanation about the difference between the two:

### The `render()` Method

The `render()` method is used in the front end for rendering an element's content.  The PHP prints its HTML content directly into the page's markup. This method is also used in the editor, if an element does not implement the `_content_template()` method.

### The `content_template()` Method

The `content_template()` method is used in **the Editor only**. It should return an **HTML template** which is parsed and used by the [Backbone Marionette](https://marionettejs.com/) framework to render its content using JavaScript. It allows for modifying element controls, while immediately displaying those changes in the Editor Preview area, without performing a re-render of the element.

This is the reason that the [section](https://github.com/elementor/elementor/blob/master/includes/elements/section.php) and [column](https://github.com/elementor/elementor/blob/master/includes/elements/column.php) elements only implement `content_template()` and not `render()` - they only exist in the Editor.
