### ISSUE TITLE
Developer docs - extending form widget

### ISSUE THREAD

**Issue by stevecove** [elementor/elementor#9323]
Hi, could anyone point me to docs on extending the elementor pro form widget with additional field types. 

I have written plenty of custom widgets but cannot find information on this.
I would like to add some 'non field' fields, if that makes sense, eg a heading field. A divider field. 

This can be accomplished via the html field, bit isn't client friendly. 

Up to now I have been creating individual custom widgets for specific forms, but would prefer the flexibility of extending the forms widget

**Comment by lior-sh** [comment]
Not support
----
Thanks,
Please create GitHub issues only for bugs reports and feature requests.
GitHub issues **ARE NOT FOR SUPPORT!**
- If you have questions or need general support, Please try:
* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org
* [Elementor Developers docs](https://developers.elementor.com/)
If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.
thanks.

**Comment by carlos-talavera** [comment]
Hi. I'm developing a custom widget for Elementor. It's a billing form for a plugin I'm developing too. The issue I have right now is that I want to extend the form widget and just implement it within my widget. What is the correct way to achieve this? I thought about extending the Form class that Elementor Pro provides, but I think that in the end I'll have to customize the class as I want, because of the hooks, mainly.

**Comment by carlos-talavera** [comment]
Okay, I figured it out :")
