### ISSUE TITLE
[backward compatibility] Slider's class names changed from `slick-slide` to `swiper-slide`

### ISSUE THREAD

**Issue by vovafeldman** [elementor/elementor#9380]
## Description
 
Pro version 2.6.5 was using `slick-slide` for the slider class names. Pro version 2.7.2 now uses `swiper-slide` for the class name prefixes, which makes all custom CSS styles that were previously created not functional, which breaks the site's design.

**Comment by shilo-ey** [comment]
Hi @vovafeldman 

Since v2.7, we use `swiper.js` instead of `slick.js` to handle the carousel functionality in Image Carousel and Slides widgets.

[We announced our planned changes](https://developers.elementor.com/elementor-2-7-moving-sliders-from-slick-to-swiper/) before the version went "live"

Simply change the `slick-slide` to `swiper-slide`.

Thanks.

**Comment by hfoelsing** [comment]
OK seriously about to lose a client over (not elementor) issues but now this. All her pages showing gibberish. I do not know what or use Slick slide. Where do I change this? Not in functions.php at all. Do you mean an actual element? These are WOO pages.
