### ISSUE TITLE
Star Rating Widget not compatible with Google Rich Snippet Guidelines

### ISSUE THREAD

**Issue by Netzlichter** [elementor/elementor#9388]
Hello,

The Star Rating widget is not compatible with Google Guidelines of structured data. If I integrate the Star Rating Widget, Google Testing tool throws errors...

Improve or remove the widget?

**Comment by riklewis** [comment]
Well this is definitely a problem, it creates markup like this...

`<div class="elementor-star-rating__wrapper"><div class="elementor-star-rating" title="5.0/5" itemtype="http://schema.org/Rating" itemscope="" itemprop="reviewRating">`

However, this returns errors from Google because it is not properly nested.  A Review must either be nested inside something like a Product, Book, etc., or have an "itemReviewed" child to detail what the review relates to.  It must also have an "author" child, that is mandatory.

Here's an example of a good snippet that passes validation... [https://search.google.com/structured-data/testing-tool?utm_campaign=devsite&utm_medium=jsonld&utm_source=microdata](https://search.google.com/structured-data/testing-tool?utm_campaign=devsite&utm_medium=jsonld&utm_source=microdata)
