### ISSUE TITLE
✔️ 🚀 Feature Request: Cross Domain Copy / Paste [Again]

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#9424]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Now, when Happy Addons released their [Cross Domain Copy Paste](https://demo.happyaddons.com/cross-domain-copy-paste%e2%80%8b/), isn't there a time for having it in Elementor too? They've definitely proven it's doable. ;-)

**Describe the solution you'd like**
See https://demo.happyaddons.com/cross-domain-copy-paste%e2%80%8b/

**Describe alternatives you've considered**
Import / Export via Templates, but it's a bit complicated.

**Additional context**
The problem is mentioned in already closed issues #7794 and #5736, but I decided to start a new one to bring it back to your attention.

**Comment by Paras16699** [comment]
@bainternet, perhaps use a library like [xdLocalStorage](https://www.npmjs.com/package/xdlocalstorage) so that it can be accessed cross-domain?

**Comment by derrickmg** [comment]
I wish for this as well.

Perhaps its something like a chrome extension, that can do it?
 (...added publicity for elementor if they are in the chrome store as well.)

**Comment by codeability-ab** [comment]
I vote for this feature too! It would be very useful in a multi site setup.
/johan

**Comment by DeathStapler** [comment]
This would be a nice feature.  We have a development server that we design the form and write a plugin to process the data.  Right now we have to recreate the form on the production site, which can be a pain, when the form is fairly long/complex.

**Comment by SirChopper** [comment]
It's time that this was introduced into Elementor Pro. Everyone else is doing it. It would be a great addition rather than exporting / importing templates.

**Comment by jaysonwebtel** [comment]
Please, please please!!!  this would save hours of exporting as template to move from staging to live.

**Comment by hybridvision** [comment]
This would be really useful indeed. I understand the technical challenges but maybe there could be an advanced option that allows the "clipboard" JSON content that is normally added to the local storage to instead be put on the user's clipboard. Then on the other site in the editor, we'd need somewhere to paste this raw clipboard data so it could be processed and added to the page. Maybe this could even be done via a 3rd-party plugin if the core editor can be extended...

The most frustrating and time consuming part of the current process is having to save a template, download it, upload it to the destination and then select and insert it. It's a very convoluted process and we end up with a bunch of templates that have no value (they're only saved because there's no other way. It would be very rare to ever use them again). I like the idea of templates but I would rather use them only for elements that are true, reusable templates.

Please Elementor developers, consider giving this more priority. A lot of Elementor's success is thanks to how pleasant and efficient it is to use. This would really improve the experience!

**Comment by black-eye** [comment]
Just to sum things up, here is the list of the addons, which provide this feature:

- Mightry Addons (free)
- Premium Addons (free)
- Ultimate Addons
- Dynamic Content
- Power Pack
- Plus Addons
- e-Addons

There are probably even more of them, I did just a quick Google search.

@arielk, @shilo-ey, @lior-sh, @bainternet, @udidol, @joshmarom, maybe time has come and Elementor can introduce this feature too?

**Comment by d19dotca** [comment]
Even if it was an Elementor Pro feature at least, would be awesome to have it natively in Elementor rather than purchasing third-party plugins (assuming naturally that other items in those third-party plugins aren't needed by the user to make it worth purchasing).

**Comment by jaysonwebtel** [comment]
I agree.  They market it as an all in one but then you need so many add one to complete a site. Simple things like this would really help round it out.

**Comment by hybridvision** [comment]
I would have no problem with this being a Pro feature except that I wouldn't want to activate the Pro plugin _just_ to have such a core piece of functionality.

I even bought a pro license originally for one project but in the end I never used it because I didn't need any of the pro features and the extra overhead of having it installed wasn't worth it (extra JS/CSS required on the front end). I've used Elementor for several years now and if I need to do anything more complex, I much prefer creating my own custom widgets. I realise I'm probably in the minority but I hope we won't have to pay a performance penalty just to have proper copy and paste functionality.

**Comment by AF1QUE** [comment]
This feature is a must-have now, even Webflow has this feature and its users are able to import templates/elements on fly from other websites. We would really appreciate this feature for Elementor Pro too. 

We know that the current Elementor Pro approach of copying & pasting elements within the same website is limited in functionality and due to that cross-domain copy paste is not being possible but the Elementor team should be able to work a way around to achieve this cross domain copy-paste feature because it's an important feature to consider. 

I hope this message gets the attention of the developers of Elementor Pro.

**Comment by AF1QUE** [comment]
> @bainternet, perhaps use a library like [xdLocalStorage](https://www.npmjs.com/package/xdlocalstorage) or [zendesk/cross-storage](https://github.com/zendesk/cross-storage) to facilitate cross-domain LocalStorage transfer?

@bainternet

**Comment by AF1QUE** [comment]
> This feature is a must-have now, even Webflow has this feature and its users are able to import templates/elements on fly from other websites. We would really appreciate this feature for Elementor Pro too.
> 
> We know that the current Elementor Pro approach of copying & pasting elements within the same website is limited in functionality and due to that cross-domain copy paste is not being possible but the Elementor team should be able to work a way around to achieve this cross domain copy-paste feature because it's an important feature to consider.
> 
> I hope this message gets the attention of the developers of Elementor Pro.



> @bainternet, perhaps use a library like [xdLocalStorage](https://www.npmjs.com/package/xdlocalstorage) or [zendesk/cross-storage](https://github.com/zendesk/cross-storage) to facilitate cross-domain LocalStorage transfer?

@bainternet

**Comment by ronaldtveen** [comment]
Sad thing about those third party plugins is that they are so bloated. 

If it would be integrated into Elementor itself we wouldn't have to install those third party plugins on both domains, copy/paste the block/content and then delete that third party plugin again...

**Comment by hybridvision** [comment]
Three years and counting... It is possible to get around this limitation without plugins by digging in the devTools and copying the `elementor` key manually from one site's local storage to another but it's a pain having to resort to this each time. 😩 

![image](https://user-images.githubusercontent.com/11492432/200793367-effd3f9b-23f7-4749-88da-3fe4007d54a1.png)

![image](https://user-images.githubusercontent.com/11492432/200793484-987ea898-6e4e-4fce-a130-c30d72a92499.png)

**Comment by derrickmg** [comment]
Some of those plugins are now not working on new (beta) flexbox containers.

**Comment by Michaelgimii** [comment]
Finally, it will be added in version 3.11. Thank you Elementor team🥂

**Comment by AF1QUE** [comment]
> Finally, it will be added in version 3.11. Thank you Elementor team🥂

Can you send me the reference link for this announcement?

**Comment by Joliamendi** [comment]
Hi @arielk 

First of all, thank you for this great feature. I had a question about this feature...

Using this feature, can we transfer only the style between two websites, or can the content (the container and the content inside it) also be transferred? For example, if we copy the image widget from one website and paste it on another website, will the image also be transferred(along with the file)?

**Comment by arielk** [comment]
> Using this feature, can we transfer only the style between two websites, or can the content (the container and the content inside it) also be transferred? For example, if we copy the image widget from one website and paste it on another website, will the image also be transferred(along with the file)?

Hi @Joliamendi,

As part of the cross-site copy/paste feature, we are also testing the possibility of importing media. 
I hope it works out for us :)

**Comment by Michaelgimii** [comment]
Hi @arielk, Thank you for this good news. We are very excited for the new version. Is the 3.11 beta coming soon like the last two version?

**Comment by arielk** [comment]
> Hi @arielk, Thank you for this good news. We are very excited for the new version. Is the 3.11 beta coming soon like the last two version?

Yes!!!

**Comment by nicholaszein** [comment]
Hello everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor **v3.11**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
