### ISSUE TITLE
Compatibility Issue with WooCommerce Templates and 3rd Party Plugin

### ISSUE THREAD

**Issue by bolderelements** [elementor/elementor#9460]
This issue is related to ticket #9256 that one of my users previously opened. When customizing the WooCommerce templates using Elementor, my product comparison plugin is not able to function properly.

One of the features with this plugin is a floating box at the bottom of the page that contains the items customers have selected to compare. It needs to be added at the very bottom of the page for the styling to work, so it uses the get_footer() filter function since all themes require this function. However, in order to ensure this box only appears on WooCommerce shop pages, and not general content pages elsewhere in the site, it looks for the 'shop' argument that WooCommerce passes in this template file.
https://github.com/woocommerce/woocommerce/blob/master/templates/archive-product.php#L105

The problem we found is that when a user edits the archive template using Elementor, this argument seems to go away and my plugin can no longer recognize that this is a WooCommerce page. 

Any help you can offer would be great, thank you for looking into this for us.

**Comment by bainternet** [comment]
@bolderelements 

Elementor uses the `get_footer` and `wp_footer` actions but has no control over the theme which is calling these to append the `shop` as a parameter.

However, I would suggest that you do not rely on that because custom themes and plugins can call the `get_footer` without the `shop` parameter (this issue) and instead check if you are on a WC page using [`is_woocommerce`](https://docs.woocommerce.com/wc-apidocs/function-is_woocommerce.html) ex:

``
add_action( 'get_footer`, function() {
	if ( ! is_woocommerce() ) {
		return;
	}
	// Do you stuff
} )
```

hope this helps.
