### ISSUE TITLE
image gallery PRO improvements [request]

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#9487]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

i would like to have the great new gallery widget more versatile and useful... currently i am trying to replace 'justified image grid' plugin with the elementor pro gallery and facing quite a lot of constraints!

so the pro gallery widget might have more features:

1. presets to save for multiple gallerys on several pages without having to do all settings again and again. would be a huge timesaver!

2. allow ordering for different scenarios (crucial!):
    - sort by date - asc/dsc
    - sort by file name - asc/dsc
    - random sorting

sorting of dozens of bulk uploaded images in one gallery via wordpress manual sorting is a mess. because mostly they dont have logical id-order after bulk upload other options are needed.
most cases demand date or file name sorting anyway ...

3. option for setting a hover icon -> e.g. magnifier. frequent client request!

4. having the option to show image full page in lightbox.

5. smoother loading of images. just like 'jig' :)

**Describe the solution you'd like**

having at least the first three natively.
for the time being i am not able to maintain existing functionalities by switching to el pro gallery

**Describe alternatives you've considered**

- external plugins :(
- keeping 'jig' :(

**Comment by marceloaof** [comment]
I find totally relevant to include the "random sorting" in random sorting. I needed a new plugin just because of it. I do not have the enough skills to do it in code, nor should we need it! And since there are threads open for almost all the widgets out there asking for random sorting, Elementor could include it not only in gallery pro, but also in old widgets.

**Comment by marceloaof** [comment]
I find totally relevant to include the "random sorting" in gallery pro. I need a new plugin just because of it. I do not have enough skills to do it in code, nor should we need it! Since there are threads open asking for random sorting in almost all widgets out there, Elementor could include it not only in gallery pro, but also in old widgets.

**Comment by shilo-ey** [comment]
I merged this issue with #9269, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
