### ISSUE TITLE
Problem with Advanced Controles in Widgets

### ISSUE THREAD

**Issue by mladenrad** [elementor/elementor#9556]
Hello,

My name is Mladen, I am a senior developer at Qode Interactive, a company that specializes in WordPress premium themes development. We are a home base to five established development teams and boast more than 300,000 happy clients.

We want to use Elementor on some of our new themes and our goal is to create some custom widgets. However, we’ve encountered a few problems and we need assistance from you.

Since we already have our own framework, we want to 'translate' our shortcodes to Elementor widgets. We made one generic class that extends your Widget_Base. Our class has properties and methods, so we can create objects and set names, controls, titles, etc. dynamically from our shortcodes. 

https://www.screencast.com/t/0nHMRWlbc
https://www.screencast.com/t/5Q17Jc9yLI

All of that works except for one thing. When we add the widget for the first time, we get all the Advanced Controls and everything works fine. However, when we save widgets and refresh the page, all the Advanced controls fail to display.

https://www.screencast.com/t/5Q17Jc9yLI
https://www.screencast.com/t/sX95j7cWGroI
https://www.screencast.com/t/qPi2iZMvP

As you can see, in your editor.js file, on window load, there is a check if widgets generated in js have 'commonMerged' property. If not, advanced controls and widget controls are merged. After this, 'commonMerged' property is set to true.

https://www.screencast.com/t/FdSr8EClF

The problem is, when 'getElementData' function is triggered on initialization, our widget controls are 'undefined' (on widgets that are added on the page). If we click on that widget, controls are there, but they can not be merged with advanced options since 'commonMerged' property is set to true. So, the initial load of added widgets is the problem for us.

Could you please help us overcome this problem, since we are planning to use your plugin for our themes? 

Kind regards,
Mladen

**Comment by bainternet** [comment]
@mladenrad 

Without seeing the full code of the flow to register the widgets it's hard to tell what is the cause of the issue but this kind of issue is usually caused by the widgets being registered either too late or simply incorrect.

I can only suggest that you make sure that the widgets are registered inside the `elementor/widgets/widgets_registered` without any conditions (ex: `! is_admin()`... )

Other than that, if you want me to take a look at your code, contact our support at support @elementor.com, mention that you were directed by me and reference this issue.

thanks.
