### ISSUE TITLE
Displaying the name of the page

### ISSUE THREAD

**Issue by webstarspro** [elementor/elementor#9699]
1.  What problem is your feature request going to solve? Please describe.
Every time when I edit the page - I'm asking "what's the name of this page?"
If you are in editor - you can not see the name of the page you are editing at the moment.
If you are switching beetween many websites or pages you are confused many times a day.

2. Describe the solution you'd like
I need to see the name the name of the page without clicking anything. The name should be seen all the time.
It's especially important if you work on many pages - switching beetween you need to now what's the name of the page.

![image](https://user-images.githubusercontent.com/57489251/69673916-b6bc7200-109b-11ea-8589-bf3933aa10a7.png)

**Comment by drawcard** [comment]
Which theme are you using? The name of the page should appear if it's a default WP theme or Elementor Hello theme. If it's not appearing chances are your theme is not including `the_title()` somewhere, or you didn't add the Post Title widget in your page template if using Theme Builder (Pro).

**Comment by webstarspro** [comment]
> Which theme are you using? The name of the page should appear if it's a default WP theme or Elementor Hello theme. If it's not appearing chances are your theme is not including `the_title()` somewhere, or you didn't add the Post Title widget in your page template if using Theme Builder (Pro).

I usually use Elementor Hello theme, but it depens.

I always hide `the_title()`  using Elementor option and I don'u use Post Title widget. I don't want to display these options on my pages.
I'm not goint to use Post Title widget on all websistes and all sub-pages.

You don't understand the idea.

Let's look at my image.
I opened Elementor editor. Now, tell me what's the name of the page I opened?
You can not see that. It's not displayed anywhere.

**Comment by drawcard** [comment]
Ok I understand the idea now. You just want a label somewhere that says "Page XYZ" even when the page you're editing doesn't say that (because of the hidden text).

I guess it could be done. But think about how you got to that page in the first place. If it was via WP's backend, you know the page you're editing because you clicked on it to edit. Or if you used the Finder command you'd type the page name in to access it. 

I can't really see how you'd end up on a random page and not know what page it is that you're editing. Does this happen a lot? Is it worth adding another UI element to the page just for edge case uses? :think: 

It would be nice maybe to see it in the Navigator panel, bracketing all of the elements together as the topmost hierarchy. Clicking on it could reveal the Page settings pane in Elementor.

**Comment by DorShahar** [comment]
Hi @webstarspro, 
Thanks for reaching out, and sorry for the delay in answering.

As @drawcard said - "how you got to that page in the first place?".

This could be achieved in the tab-title and editor page setting.

If we will get more requests like this we will consider a solution. 

Closing the issue.
Thanks.
