### ISSUE TITLE
Custom Icons for all widgets

### ISSUE THREAD

**Issue by rickywolff** [elementor/elementor#9704]
Hi there,

I'd like to request a feature.

I'd like to create custom icons for all Elementor Widgets that use icons. For example the Navigation Widget or the Social Share Icons.

The goal is to eliminate font awesome and other Icon packs.

**Comment by drawcard** [comment]
You can (with Pro) https://docs.elementor.com/article/590-custom-icons-pro

The way I understand it, Font Awesome is a requirement in Elementor because it is used for things like chevrons in nav menus, etc. as well as within the editor UI, and it would break too much stuff if it was excluded from the plugin.

**Comment by shilo-ey** [comment]
Hi @rickywolff 

Elementor and Elementor Pro uses [e-icons](https://github.com/elementor/elementor-icons) (Editor) and FontAwesome (Frontend)

If you don't want to use FA, you can deregister it [as provided here](https://docs.elementor.com/article/286-speed-up-a-slow-site), and use your own.
