### ISSUE TITLE
Why Elementor loads Scripts and CSS files for all admin panel pages

### ISSUE THREAD

**Issue by techjewel** [elementor/elementor#9708]
## Description
This is what I am talking about. If I just login to wp-admin/any-settings-page where Elementor should not have any feature to add. Elementor are loading 12 files (700KB).

So, around 3+ millions using Elementor and if on average 1 person login to the admin panel then it's 2100 gigabytes of bandwidth elementor is wasting everyday.

## Steps to reproduce
Just Go to any settings page of any other plugins

## Environment
Any WordPress Admin panel

**Comment by shilo-ey** [comment]
Hi @techjewel 

Thanks for your feedback.

Elementor is an extensive plugin, feature-rich, which provides a wide range of capabilities and features to our users, both in the Editor and in the WP Admin area.


1. In order for the specified features to run smoothly, Elementor loads SOME of its assets, such as the “Finder” to allow it to work from any screen.
2. As for the point of bandwidth wasting, those assets should only be requested once, and then be loaded from the memory/browser cache, so no bandwidth is wasted
3. In the Editor - we load those assets by default to allow faster interactions so when the script is needed it’s already available. basically, it’s a key requirement for Elementor to run.


Having said that, Elementor is on constant infrastructure improvements, as you can see in our latest versions. Those things take time because we do things responsibly and gradually to prevent harming our users' sites.

Thanks
