### ISSUE TITLE
[bug] version 8.2 - icon list and shapes alignment 

### ISSUE THREAD

**Issue by uanber** [elementor/elementor#9927]
Updating Elementor Pro V. 8.2 and now the icon lists and shapes looked out of alignment (this is only after I hit preview or the content goes live. Everything looks normal during the editing process). 

Icon lists: 
(During editing)
![Elementor_Before_1 copy](https://user-images.githubusercontent.com/20911737/71138414-6ab3a780-21d9-11ea-86d5-7bbe33d93ab4.jpg)

(After - Live)

![Elementor_Icon_List_After](https://user-images.githubusercontent.com/20911737/71138429-7c954a80-21d9-11ea-9d05-ef5b6444baea.jpg)

border: 
(During editing)
![Elementor_Before2 copy](https://user-images.githubusercontent.com/20911737/71138481-acdce900-21d9-11ea-8203-25c6f1d1369d.jpg)

(After - Live)

![Elementor_After2](https://user-images.githubusercontent.com/20911737/71138499-b7977e00-21d9-11ea-903e-a05746e5d99b.jpg)

**Comment by Zahtar** [comment]
Just spent an hour tracking this down on multiple posts with iconlists  - and can confirm that updating E-Pro to 2.8.2 added a line break after the .elementor-icon-list-icon class on the Single post template.

It's only noticeable when the iconlist text is long enough to wrap to 2 or more lines, at which point the icon appears positioned next to the second line of text. Appears correct in the Elementor editor, but the line break shows up on the frontend view.

Only happened on the Single template - other pages/posts with iconlists seem fine. 

Rolling back to version E-Pro 2.73 fixed the issue.

**Comment by reachdigitalaus** [comment]
Yes, I am facing the same issue with the latest update, also my form buttons lost styles ( became fatter as it added spacing). Edit mode looks ok, live breaks.

**Comment by shilo-ey** [comment]
Hi,
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* **Steps to replicate.**
* **Isolating the problem.**
* **System info.**


Without it we simply can't help.


Awaiting your prompt reply

Thanks.

**Comment by toopixel** [comment]
Same issue for me but not only for list icons

Since last update of Elementor Pro to 2.8.0 it introduced problem in certain places of my website.

For example here: https://www.fusionten.ch/blog/tunnels-de-ventes-le-marketing-de-demain-avec-patrick-grobety-de-marketing-extreme/

You can see the player (which is composed with an image above the audio player coming from JetElements) shouldn't have space between. In the Elementor editor it doesn't have any and margins are set to zero. Note: it's not JetElements related, this is really Elementor which adds extra spacing!

Also near the end of article, there are 2 links with an icon which is the list icons widget, and they aren't aligned, also some spacing is added wrongly since last update.

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by reachdigitalaus** [comment]
Thank you @shilo-ey , I created a doc with both my issues, what is teh best way to send to you?

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.8.2

Feel free to update

Thanks!
